### PR TITLE
6666 Make age column width relative vaccination card

### LINKED ISSUE #6666: Encounters: age column is not wide enough
## What went wrong? 😲

Image

## Expected behaviour 🤔

Wider pls

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure you have Immunization Programs and Vaccination Card enabled for your store
2. Create an encounter for a patient enrolled into a program
3. Create a vaccine course with a few doses, possibly for ages 10+
4. Go to the encounter to issue vaccination -> see some values do not fit into the Age column

## Your environment 🌱

- Open mSupply Version: V2.6.0-RC2
- Legacy mSupply Central Server Version: V8.00.11

- Platform: Google Chrome (browser for Mac)

- Database type: PostgreSQL

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #6666

# 👩🏻‍💻 What does this PR do?
Change age column width to be relative. It now resizes based on the text in the field. 

Screenshot 2025-04-04 at 17 28 31
Screenshot 2025-04-04 at 17 29 16

## 💌 Any notes for the reviewer?
I initially just thought of increasing the fixed width but then it looked funky when there was only age in months being displayed. 

The columns are inheriting width which makes them ridiculously wide if you remove the width prop altogether
Screenshot 2025-04-04 at 17 27 30

I tried to go up the chain to see if I could track down where that was being inherited from but I didn't have much luck so I came to this solution. 

# 🧪 Testing

- [ ] Make sure you have Immunization Programs and Vaccination Card enabled for your store
- [ ] Create an encounter for a patient enrolled into a program
- [ ] Create a vaccine course with a few doses
- [ ] For scenario 1 you will need an age that has both years and months e.g 10 years 12 months
- [ ] For scenario 2 you should only have ages in months
- [ ] Go to the encounter to issue vaccination -> see that the age column adjusts to fit the length of the text correctly

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx [hunk 1]
```diff
@@ -165,7 +165,7 @@ const VaccinationCardComponent = ({
           // Only show age label for first of each "block", when repeated
           return sameAsPrev ? null : getAgeLabel(rowData);
         },
-        width: 140,
+        width: '5%',
```
Comment (lache-melvin) [inline client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx:168]: Hm, so looks like `5` of the 5% isn't actually for a specific purpose, just that its smaller than actual width so stretching to min-content... in this case, I think safer to go with 1% (as its more obviously not the actual width) and add a comment:

```suggestion
        // Hack for "min-content"
        width: '1%',
```

I have added this to table refactor issue, something else to consider in new table API definition: https://github.com/msupply-foundation/open-msupply/issues/4744

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Thanks for finding this fix! Just requesting comment around it for clarity

File: client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx]: Resolved here 6cdeb7c49460d0136127b63faa407c204e7fb20a

**Review by lache-melvin — APPROVED** [review]
Thank you!
