### PR TITLE
Check for undefined value in NumberCell

### LINKED ISSUE #4536: Cannot create Stocktakes from Master Lists or for Items with Stock
## What went wrong? 😲

We are not able to create Stocktakes that pull items from the Master Lists or that are for Items with Stock. Seems like any interaction with the items causes the app to crash. If you try to create a blank stocktake, it works as expected

**Master Lists:** 

https://github.com/user-attachments/assets/661c1dc9-b5a9-4d83-939c-936caee20812

**Items with Stock:** 

https://github.com/user-attachments/assets/e51a4fc3-3f07-48d6-b0a5-acdae3b41521

## Expected behaviour 🤔

Stocktake should be produced as expected, without crashes. Anusha shared a similar issue from a while ago - #2743, but there the app was crashing when the list of items was 5000+. Here, I am trying to pull <500 records, not 5000+. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> Stocktakes
2. Create a New Stocktake -> try to add items from a Master List OR tick the 'Items with Stock' checkbox
3. See error occur. If you exit to Dashboard or log out and log in again, the stocktake entry will be there, however if you click on it, the app will crash again. So the entry gets created, but you cannot interact with it. 

## Your environment 🌱

- Open mSupply Version: `V2.2.0-RC1`
- Legacy mSupply Central Server Version: V7.16.08

- Platform: Remote Desktop (Windows)

- Database type: SQLite3

### LINKED ISSUE #4563: V2.2.0 Release Test: Stocktakes
### **TEST ENVIRONMENT**
oms Version: `v2.2.00-RC2` 
mSupply Cloud-Server: `v7-16-04`
oms app-mode: `oms-server` + `browser(chrome)`
oms db: `sqlite`

# Stocktakes
- [x] Make sure your user account has permission to do Stocktake processes like New, Edit, Delete, etc.
- [x] Open Stocktakes, a list of existing Stocktakes should come up.
- [x] Button ‘New stocktake’ should be enabled
- [x] Click the ‘New stock take’ and create a new stock take. Stock take sheet window will open and the cursor will show:
- [ ] option to start from a Masterlist, with a drop down list, according to store visibility **- problem seen in multiple-stores setup**; see comment for details
- [x] option to start from a location, with a drop down list.
- [x] option to start from "Items with Stock", with a checkbox.
    - [x] All options above should take you to the stocktake initial page with appropriate outcome. ex: if selected from Masterlist, all items form that specific Masterlist should appear.
- [x] On the left corner, click on 'Description' and type something.The information should be saved.
- [x] Click on the top button “Add item" and you can search by item name or code
- [x] Click ‘Add new’, the newly added item should be shown on the list.
- [x] Batch,  pack size, counted packs and expiry date are editable fields.
- [x] If 'Reason' is configured on mSupply central server, you can add 1 from the dropdown list.
- [x] If you press 'cancel' it takes you back to the main page and no new line will come up.
- [x] If you add item details and press 'OK' it takes you back to the main page and the new line is there.
- [x] If you add item details and press 'OK & next' a new window will come up for you to add another item to the stocktake. The previous item is saved and available on the main list.
- [x] Select a line , the checkbox should be active. Click on 'Actions' and 'Delete selected lines'. There should be a confirmation dialog, click ‘Yes’, the line should be deleted in the list
- [x] Try to Delete line again, click ‘No’, the line should NOT be deleted in the list.
- [x] Click on 'More' on the right corner of the screen
- [x] Add a Comment. The information should be saved.
- [x] If you click 'Delete', a message will come up asking if you would like to delete the stocktake. If you press 'cancel', it takes you back to editing details. If you press 'yes' the whole stocktake will be deleted,
- [x] When you double click on any item line, a new window will cone up. All fields must be enterable except for ‘Snapshot packs’ 
- [x] 'Add batch' button should be enabled
- [x] When you add a batch, a new item line comes up
- [x] If you click on 'Expiry', a calendar window will come up. A month and year should be selected before the window closes
- [x] 'Reason' has a drop down list of reasons configured for the store
- [x] If 'counted packs' is not equal to ''snapshot packs', a 'Reason' must be provided before you click on 'Ok', otherwise a warning message comes up
- [x] Try changing the ‘Counted packs', the change should reflect on the dropdown option also.
- [x] Check the Log tab, all your changes must show in the Log list. **- addition/deletion of lines isn't there; maybe sth to be done in future later**
- [x] Test the ‘Group by’ button. It should sort properly depending on the option you selected.
- [ ] Test the ‘Print’ button. For ‘General’, the output should match depending on the option you chose. **- issue found with report itself**; see comments for details
- [x] Finalised Stocktake
- [x] Once the process is done, the Stocktake is Finalised. When status = Finalised, you should not be able to edit any details.

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #4536

# 👩🏻‍💻 What does this PR do?
An innocuous change in #4403 - the value of a NumberCell can be undefined, but the tooltip is using `value.toString()`

The change is to account for undefined / null values.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create a stocktake

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ export const NumberCell = <T extends RecordWithId>({
         padding: '4px 8px',
       }}
     >
-      <Tooltip title={value.toString()}>
+      <Tooltip title={value?.toString()}>
```
Comment (andreievg) [inline client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx:34]: @mark-prins can you please change `as number` above to be `as number | undefined`

**Review by andreievg — APPROVED** [review]

File: client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx:34]: Good point - have also corrected the other two usages of `value` based on the expected typing
