### PR TITLE
6630 prevent saving empty vaccine courses

### LINKED ISSUE #6630: Able to save vaccine courses and doses for them with no names
## What went wrong? 😲

Able to save blank vaccine courses and doses for the courses

Image

## Expected behaviour 🤔

I think fields like `Vaccine Course name`, `Vaccine Items` and possibly `Target Demographic` need to be compulsory?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have Immunization Programs and Vaccination Card enabled for your store
2. Go to Programs -> Immunization and create a new program
3. Create a vaccine course of it
4. Note you can save it with no essential information entered
5. Same for doses - you can save a dose with no name entered

## Your environment 🌱

- Open mSupply Version: `V2.6.0-RC1`
- Legacy mSupply Central Server Version: `V8.00.11`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #6630

# 👩🏻‍💻 What does this PR do?

Disables save button while course name or dose labels are empty, adds asterisks to communicate:
Screenshot 2025-02-27 at 8 37 23 AM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] OMS Central > Programs > Immunisations > a program
- [ ] Add/edit vaccine course
- [ ] While no name entered, button is disabled
- [ ] Add a dose, when label is empty, button is disabled

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx [hunk 1]
```diff
@@ -146,6 +146,9 @@ export const VaccineCourseEditModal: FC<VaccineCourseEditModalProps> = ({
     }
   };
 
+  const isValid =
+    draft.name && !draft.vaccineCourseDoses?.some(dose => !dose.label);
```
Comment (lache-melvin) [inline client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx:150]: `.some()` will return true as soon as it finds an empty label so this is slightly more efficient than `.every()`

Comment (roxy-dao) [reply client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx:150]: Can we trim white space from name? Still can save blank name if we don't 😉

**Review by roxy-dao — CHANGES_REQUESTED** [review]
LGTM! Just a lil change below (:

**Review by roxy-dao — APPROVED** [review]
LGTM~
