### PR TITLE
Remove extra div

### LINKED ISSUE #6021: There are 2 scroll bars in the item list of the internal order edit window
## What went wrong? 😲

See the screenshot
https://drive.google.com/file/d/1bvqGag9ZJj9uYaRg_HAT9jUXtjWhdGIP/view?usp=sharing

and 

The comment label is overlapped by the comment field when omSupply is in french.

image

## Expected behaviour 🤔
I think 1 scroll bar should be enough :) 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Replenishment > Internal order'
2. Click on New order to create a new program internal order
3. click on a line. 
4. See error. The list of items has 2 scroll bars
5. Change your language to french
6. See that the comment label in french is partly obscured by the field

## Your environment 🌱

- Open mSupply Version: 2.5.0RC2
- Legacy mSupply Central Server Version: v8.00dev29

- Platform: omSupply desktop 

- Database type: SQLLite3

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6021

# 👩🏻‍💻 What does this PR do?
Remove extra div that was creating 2nd scrollbar

# 🧪 Testing

- [ ] Have a lot of items in a program like... over 100? 
- [ ] Create Program IO/Requisition 
- [ ] Go to line edit page
- [ ] See extra scrollbar gone

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx [hunk 1]
```diff
@@ -64,39 +64,35 @@ const ResponseLineEditPageInner = ({
       <DetailContainer>
```
Comment (CarlosNZ) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx:64]: I think you can actually remove `DetailContainer` too. I did so in Prescriptions (https://github.com/msupply-foundation/open-msupply/blob/ee9739d4e078218420b4842336434496a381923b/client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx#L151) and I think we benefit from the lesser padding. Any CSS from DetailContainer can be added to `PageLayout` if we really need it.

Then again, can leave that till we do #5973 if you prefer?

**Review by CarlosNZ — APPROVED** [review]
Great, works for me, thanks.

(Weirdly the double-scroll bar doesn't appear on Firefox, but does on Chrome)
