### PR TITLE
9971 [CCEI / GAPS] Editing assets is not resricted by the edit asset permission

### LINKED ISSUE #9971: [CCEI / GAPS] Editing assets is not resricted by the edit asset permission
## What went wrong? 😲

Any user with permission to view assets,  is also able to edit the asset regardless of the edit asset permission (can any field on this form, status is controlled separately)

Image

## Expected behaviour 🤔

Editing assets is restricted by the edit asset permission (OG: Add/Edit Assets, OMS: AssetMutate). A user without this permission would not be able to edit the asset information

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have an asset set up on your store
2. Have OG user preferences: 
 - Can view assets: yes
 - Can add/edit assets: no
4. Go to your asset and edit some details - serial number, location etc. See that the asset is editible

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #9971

# 👩🏻‍💻 What does this PR do?
Fix permissions and have separated add and edit asset permissions like adam requested

# 🧪 Testing

- [ ] Have Equipment at a store
- [ ] Don't have edit permissions
- [ ] Try to edit the equipment
- [ ] Shouldn't be able to

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/auth.rs [hunk 1]
```diff
@@ -677,21 +701,16 @@ fn all_permissions() -> HashMap<Resource, PermissionDSL> {
     // configure
     map.insert(
         Resource::ConfigurePlugin,
-        PermissionDSL::Any(vec![
-            PermissionDSL::HasPermission(PermissionType::ServerAdmin), // Server admins can install plugins
-        ]),
+        PermissionDSL::HasPermission(PermissionType::ServerAdmin), // Server admins can install plugins
```
Comment (roxy-dao) [inline server/service/src/auth.rs]: Fixed other permissions as well

File: server/service/src/auth.rs [hunk 2]
```diff
@@ -617,23 +612,60 @@ fn all_permissions() -> HashMap<Resource, PermissionDSL> {
...
+            PermissionDSL::HasPermission(PermissionType::EditCentralData),
+        ]),
+    );
+
+    map.insert(
+        Resource::EditAsset,
+        PermissionDSL::Any(vec![
+            PermissionDSL::And(vec![PermissionDSL::HasPermission(
+                PermissionType::AssetMutate,
+            )]),
```
Comment (GeronimoJohn) [inline server/service/src/auth.rs]: Since only one permission, could just go without the `vec`:

`PermissionDSL::HasPermission(PermissionType::AssetMutate),`

Same thing for `QueryAsset`

File: server/service/src/auth.rs [hunk 3]
```diff
@@ -617,23 +612,60 @@ fn all_permissions() -> HashMap<Resource, PermissionDSL> {
...
+                PermissionDSL::HasPermission(PermissionType::AssetMutateViaDataMatrix),
+            ])]),
+            PermissionDSL::HasStoreAccess,
+            PermissionDSL::HasPermission(PermissionType::EditCentralData),
+        ]),
+    );
+
+    map.insert(
+        Resource::EditAsset,
+        PermissionDSL::Any(vec![
```
[the remark this answers is not in the document]
Comment (roxy-dao) [reply server/service/src/auth.rs]: Yeah, if they have central edit data and it's central they should be able to edit ... else they can only edit at their store if they have permission... it's a complicated permission set up

File: server/service/src/auth.rs (hunk 2 above)
Comment (roxy-dao) [reply server/service/src/auth.rs]: It's not one permission tho..

**Review by GeronimoJohn — APPROVED** [review]
Thanks for the changes. 🔥
