### PR TITLE
9087 integration test compilation

### LINKED ISSUE #9087: Fix integration test compilation
## What went wrong? 😲

Integration_test feature flag won't compile. I can't run load test.

- Open mSupply Version: 2.11 dev

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #9087

# 👩🏻‍💻 What does this PR do?

Fix compiler errors

I added default- bite me!

I did not actually test integration_tests. I just want the feature flag to build so I can use the `load_test` cli!

# 🧪 Testing

```sh
cargo check --features integration_test
```

### CODE REVIEW

File: server/service/src/sync/test/integration/mod.rs [hunk 1]
```diff
@@ -154,6 +154,8 @@ pub(crate) fn integrate_with_is_sync_reset(
     let cursor = changelog_repo.latest_cursor().unwrap();
     // Need to reset is_sync_update since we've inserted test data with sync methods
     // they need to sync to central (if is_sync_update is set to true they will not sync to central)
-    integrate(&connection, integrations, None).unwrap();
+    let integrations: Vec<(Option<_>, IntegrationOperation)> =
+        integrations.iter().cloned().map(|i| (None, i)).collect();
+    integrate(&connection, &integrations).unwrap();
```
Comment (Chris-Petty) [inline server/service/src/sync/test/integration/mod.rs:159]: All the cloning trait shenanigans was so I could do this cause otherwise I was refactoring chains of functions to take `&[(Option<i32>, IntegrationOption)]` becoming a mess.

Idk how to trait good, copilot on claude 4.0 helped a lot.

**Comment by Chris-Petty** [comment]
Ah I got carried away and committed some changes to load_test procedure rather than make a new issue/branch 🤦

File: server/repository/src/lib.rs [hunk 2]
```diff
@@ -63,6 +63,32 @@ pub trait Upsert: DebugTrait {
     }
 }
 
+pub trait UpsertAndClone: Upsert {
```
Comment (jmbrunskill) [inline server/repository/src/lib.rs:66]: Spent WAAY too much time trying to find a nicer solution but it turns out it's harder than it looks.
I found a rust crate https://crates.io/crates/dyn_clone that solves this problem but is an extra dependancy and uses unsafe code so not sure how much I can trust it.

I also tried the use `Arc` instead of box approach which works apart from the use mutable downcast in test cases. I'm not clear why we can get a mutable ref for downcast from a box but I can't get. non-mutable ref in an arc. If we make upsert `Send + Sync` we can clone in the arc but I'm not sure it's safe to do that either.

Maybe just add a quick comment here to explain why the trait is needed?

```
Because upsert is used as a `Dyn trait` we can't ensure that the types also implement `Clone` without creating an additional Trait like this, or us a similar trait from a library such as `dyn-clone`
```

**Review by jmbrunskill — APPROVED** [review]
Looks all good to me, thanks @Chris-Petty just would like an explanation for the extra Trait.

**Review by andreievg — CHANGES_REQUESTED** [review]
I would suggest this, instead of new trait: https://github.com/msupply-foundation/open-msupply/compare/9087-integration_test-compilation...9087-integration_test-compilation(New-trait-alternative)

**Comment by Chris-Petty** [comment]
Yep that works thanks @andreievg!

File: server/service/src/sync/test/mod.rs [hunk 3]
```diff
@@ -25,7 +25,7 @@ impl TestSyncIncomingRecord {
         upsert: U,
     ) -> TestSyncIncomingRecord
     where
-        U: Upsert + 'static,
+        U: Upsert + Clone + 'static,
```
Comment (andreievg) [inline server/service/src/sync/test/mod.rs:28]: I think this is still remainder from the trait stuff ? If so :nit to delete please

**Review by andreievg — APPROVED** [review]
Looks great, thanks
