### PR TITLE
6637 fix date translations

### LINKED ISSUE #6637: Date picker not translated in FR (and possibly other languages)
## What went wrong? 😲

Date picker in Open mSupply shows months in english rather than the selected language. Even when the device (laptop/tablet) is configured in FR

## Expected behaviour 🤔

Months should be displayed in the selected language. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Choose another language than english 
2.  Go to a transaction where you need to select a date (expiry date) such as stocktake
3. Enter a date using the date picker

## Your environment 🌱

- Open mSupply Version: 2.5+
- Legacy mSupply Central Server Version: 
- Platform: Android/Browser/Desktop
- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #6637

# 👩🏻‍💻 What does this PR do?

Initialises the i18n-next singleton outside of React, as intended usage. 

It's initialisation doesn't trigger a re-render, it's only because child components are re-rendering/querying the Intl context again that they end up with updated values. Higher in the component tree = higher risk that it is not initialised when you are first rendered.

This was the case with getting language settings in time to configure date translations. I wonder if this was also the actual cause of that translation keys on the discovery page bug?

Months now translated
Screenshot 2025-02-28 at 10 29 55 AM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Set language to something other than english, e.g. french
- [ ] Open date picker (e.g. stock expiry date filter)
- [ ] Months are in selected language 
- [ ] Given translation set up has changed please double check discovery page on electron (desktop app) is also translated!

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [x] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [x] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [x] Frontend

### CODE REVIEW

File: client/packages/common/src/intl/context/IntlContext.tsx [hunk 1]
```diff
@@ -14,86 +14,80 @@ const appVersion = require('../../../../../../package.json').version; // eslint-
...
-    const languageDetector = new LanguageDetector();
-    languageDetector.addDetector(browserLanguageDetector);
-
-    const minuteInMilliseconds = 60 * 1000;
-    const isDevelopment = process.env['NODE_ENV'] === 'development';
-    const expirationTime = isDevelopment
-      ? 0
-      : 7 * 24 * 60 * minuteInMilliseconds; // Cache for 7 days, on rebuild we should get a new language version so we can use a reasonably long cache
+/** Must be initialised outside of react */
+export function initialiseI18n({
```
Comment (lache-melvin) [inline client/packages/common/src/intl/context/IntlContext.tsx:25]: Ah sorry, bit of noise in here - it's all just shuffling. Only change is the addition of this function, to be called by app root, rather than inside useEffect
