### PR TITLE
3936 you can finalise a stocktake with only placeholder lines

### LINKED ISSUE #3936: You can finalise a stocktake with only placeholder lines
## What went wrong? 😲
 

New stocktake, only generated placeholder lines: 
Screenshot 2024-05-17 at 4 37 15 PM

Click finalise, you now have empty stocktake!
Screenshot 2024-05-17 at 4 37 25 PM

## Expected behaviour 🤔

To be consistent with other areas of the app, you shouldn't be able to finalise to an empty stocktake. Should be an error/warning if only placeholder rows are present. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create new stocktake from a master list
2. Click finalise
3. Finalised stocktake is empty

## Your environment 🌱

- Open mSupply Version: 2.1.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3936

# 👩🏻‍💻 What does this PR do?
Don't allow status change if no lines or placeholder lines: Inbound, Outbound, Prescription and Stocktake. Have used snack instead of disabled because of agreed issue ages ago 👀 

# 🧪 Testing

- [ ] Create Inbound, Prescription, Outbound or Stocktake with placeholder lines
- [ ] Try change status
- [ ] Should see snack

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx [hunk 1]
```diff
@@ -208,7 +224,7 @@ export const StatusChangeButton = () => {
       selectedOption={selectedOption}
       onSelectOption={setSelectedOption}
       Icon={<ArrowRightIcon />}
-      onClick={() => getConfirmation()}
+      onClick={onStatusClick}
```
Comment (lache-melvin) [inline client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx:227]: I think need to remove the isDisabled, never get the toast like this 😁

File: client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx [hunk 2]
```diff
@@ -133,7 +134,9 @@ export const StatusChangeButton = () => {
     useStatusChangeButton();
   const isDisabled = usePrescription.utils.isDisabled();
   const t = useTranslation();
-  const noLines = lines?.totalCount === 0;
+  const noLines =
+    lines?.totalCount === 0 ||
+    lines?.nodes?.every(l => l.type === InvoiceLineNodeType.UnallocatedStock);
```
Comment (lache-melvin) [inline client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx:139]: This button also disabled rather than toasting... wanting to be consistent?

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Looks goooood! Just a couple of clean ups so its consistent everywhere 🔥

File: client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx (hunk 2 above)
Comment (roxy-dao) [reply client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx:139]: Opps thought I removed them thanks Lache :D

Comment (lache-melvin) [reply client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx:139]: Hehe oops, gotta add the toast here now 😁

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Sorry wasn't super clear in my review comment, in prescriptions need to add the toast!

File: client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx (hunk 2 above)
Comment (roxy-dao) [reply client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx:139]: Nope, my bad should have triple checked

**Review by lache-melvin — APPROVED** [review]
Beaut ✨
