### PR TITLE
6779 default patient page should be translatable into other languages

### LINKED ISSUE #6779: Default patient page should be translatable into other languages
## What went wrong? 😲

Noticed the default patient schema (when NO custom JSON forms have been uploaded) is not getting translated when switching languages

Image

## Expected behaviour 🤔

I think it's quite important this page is translated, because at the moment we don't have the 'default' JSON forms uploaded to view this page - it comes by default. Translations cannot be done in weblate, so basically this is untranslatable at the moment. 

And considering only one client is using a custom patient schema, the other clients will need a way to view the patient's edit page in their own languages. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have no custom patient forms enabled for your datafile
2. Go to Dispensary -> Patients and edit an existing patient or create a new one
3. On the edit page, switch languages to French or Russian (the most translated ones)
4. See some areas (in the actual content area, not in the headers) is not translated

## Your environment 🌱

- Open mSupply Version: V2.6.0-RC5
- Legacy mSupply Central Server Version: V8.00.11

- Platform: Google Chrome (browser for Mac)

- Database type: PostgreSQL

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6779

# 👩🏻‍💻 What does this PR do?
- Translate history button on the patient page
- Handle translations in the select component 
- Change display label for gender to translation key

## 💌 Any notes for the reviewer?
Still needs: 
- Translations for jsonform error handling (should be another issue)
- Translations for datepicker buttons

# 🧪 Testing

- [ ] Don't have any custom patient UI schemas configured
- [ ] Go to patient
- [ ] Click on a patient
- [ ] Change language to French
- [ ] See translation for history button and genders

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/programs/src/JsonForms/common/components/Select.tsx [hunk 1]
```diff
@@ -100,7 +102,12 @@ const getDisplayOptions = (
         );
         return prev;
       }
-      prev.push({ value: key, label: value ?? key, description, right });
+      prev.push({
```
Comment (roxy-dao) [inline client/packages/programs/src/JsonForms/common/components/Select.tsx:105]: Need to do this since the default json isn't saved in database and therefore won't be translated

File: client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json [hunk 2]
```diff
@@ -29,12 +29,12 @@
           "label": "label.gender",
           "options": {
             "show": [
-              ["MALE", "Male"],
-              ["FEMALE", "Female"],
-              ["TRANSGENDER_MALE", "Transgender Male"],
-              ["TRANSGENDER_FEMALE", "Transgender Female"],
-              ["NON_BINARY", "Non-binary"],
-              ["UNKNOWN", "Unknown"]
+                  ["MALE", "gender.male"],
```
Comment (Chris-Petty) [inline client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json:32]: I saw other reports using some kinda tag like `T#gender.female`. What's with that and why not here?

**Review by Chris-Petty — APPROVED** [review]
LGTM

File: client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json (hunk 2 above)
Comment (roxy-dao) [reply client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json:32]: Cause those are being served from backend, backend translates.. this one isn't saved in DB >.< so have to handle it somehow
https://github.com/msupply-foundation/open-msupply/pull/6953#discussion_r1999975776 <-
