### PR TITLE
6896 Deleting an immunization program master list in OG is not reflected in OMS

### LINKED ISSUE #6896: Deleting an immunization program master list in OG is not reflected in OMS
## What went wrong? 😲

If an immunization program master list is deleted in OG it still appears in `Programs > Immunizations` in OMS

Image

Image

## Expected behaviour 🤔

Master lists deleted in OG should not be shown in the UI in OMS

Quote: "Chris sez we probably ain't filtering soft deleted program table records, or we're forgetting to soft delete them as an effect of soft deleting a master list"

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an immunization program master list in OG
2. Observer the immunization program appear in OMS
3. Delete the master list in OG
4. Observer the immunization program remains in OMS

## Your environment 🌱

- Open mSupply Version: 2.6.00
- Legacy mSupply Central Server Version: 8.00.17

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6896

# 👩🏻‍💻 What does this PR do?
Save deleted_datetime based on inactive field for program master lists

# 🧪 Testing

- [ ] Have an immunisation program master list 
- [ ] Go to immunisation page, see that it is there
- [ ] Go to OG central and delete the immunisation master list 
- [ ] Sync OMS and refresh immunisation page
- [ ] Deleted program master list should be gone

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/sync/translations/program_requisition_settings.rs [hunk 1]
```diff
@@ -29,6 +29,7 @@ pub struct LegacyListMasterRow {
     #[serde(rename = "programSettings")]
     program_settings: Option<LegacyProgramSettings>,
     is_immunisation: Option<bool>,
+    inactive: Option<bool>,
```
Comment (Chris-Petty) [inline server/service/src/sync/translations/program_requisition_settings.rs:32]: I don't think this or `is_immunisation` would be `Option`? Hmm issue doesn't have much detail 😆  https://github.com/msupply-foundation/open-msupply/issues/2534. But from what I have gleaned it's to keep backwards compatibility if you're syncing OMS on an old version of OG central server. Fair enough.

**Review by Chris-Petty — APPROVED** [review]
LGTM!

File: server/service/src/sync/translations/program_requisition_settings.rs (hunk 1 above)
Comment (roxy-dao) [reply server/service/src/sync/translations/program_requisition_settings.rs:32]: Yes that's why it's optional (:
