### PR TITLE
6533 pagination for period

### LINKED ISSUE #6533: Pagination for period
## What went wrong? 😲
Some reports require filtering by period but this currently doesn't implement any kind of pagination. 

## Expected behaviour 🤔
Implement pagination for period and use AutocompleteWithPagination for the json component

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6533

# 👩🏻‍💻 What does this PR do?
Defaults shown periods to 15 and only show past periods. 

# 🧪 Testing

- [ ] Have lots of periods over 30? 
- [ ] Set up CIV stocktake report 
- [ ] Go to report and click on stocktake report
- [ ] Only limited of periods shown until you keep scrolling

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/programs/src/JsonForms/components/PeriodSearch.tsx [hunk 1]
```diff
@@ -29,11 +32,23 @@ const UIComponent = (props: ControlProps) => {
...
+  const today = new Date();
+  const lastDayOfMonth = DateUtils.lastDayOfMonth(today);
+  const { data, isFetching, fetchNextPage } = usePeriodList(
+    RECORDS_PER_PAGE,
     programId,
-    options?.findByProgram ? !!programId : true
+    options?.findByProgram ? !!programId : true,
+    {
+      endDate: {
+        beforeOrEqualTo: Formatter.naiveDate(lastDayOfMonth),
```
Comment (roxy-dao) [inline client/packages/programs/src/JsonForms/components/PeriodSearch.tsx:43]: Want to get all periods until the last day of current month in case there are transactions done in this time

File: client/packages/programs/src/JsonForms/components/PeriodSearch.tsx [hunk 2]
```diff
@@ -29,11 +32,23 @@ const UIComponent = (props: ControlProps) => {
   const programId = options?.findByProgram
     ? extractProperty(core?.data, 'programId')
     : null;
-  const { data, isLoading } = usePeriodList(
+  const today = new Date();
+  const lastDayOfMonth = DateUtils.lastDayOfMonth(today);
+  const { data, isFetching, fetchNextPage } = usePeriodList(
```
Comment (fergie-nz) [inline client/packages/programs/src/JsonForms/components/PeriodSearch.tsx:37]: nit but I like consistency of isLoading which we use everywhere else. Is there a reason to change to fetching?

Comment (roxy-dao) [reply client/packages/programs/src/JsonForms/components/PeriodSearch.tsx:37]: cause we are fetching next page so the loading was just changed to fetching to match, but guess can use isLoading

File: client/packages/programs/src/JsonForms/components/PeriodSearch.tsx (hunk 1 above)
Comment (fergie-nz) [reply client/packages/programs/src/JsonForms/components/PeriodSearch.tsx:43]: This is great but I think it misses some edge cases:

If a period is monthly but doesn't begin on the first day of the month, then it won't capture this period (in my case I had a monthly period schedule which began on the 10th, and wasn't visible). I'm not sure if this is a common case, but there it is.

I wonder if it would be better to filter instead by startDate and filter for startDate < now.

I recognise requires refactoring of backend filters, but makes for a more simple front end use.

**Review by fergie-nz — CHANGES_REQUESTED** [review]
Looks awesome - some issue showing the current period when not mapped exactly to months

File: client/packages/programs/src/JsonForms/components/PeriodSearch.tsx (hunk 2 above)
Comment (fergie-nz) [reply client/packages/programs/src/JsonForms/components/PeriodSearch.tsx:37]: I'm easy, just a minor preference

File: client/packages/programs/src/JsonForms/components/PeriodSearch.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/programs/src/JsonForms/components/PeriodSearch.tsx:43]: Yup good idea

**Review by fergie-nz — APPROVED** [review]
nice LGTM! 🎸
