### PR TITLE
5009 mobile modal improvements

### LINKED ISSUE #5009: Improve/simplify modal heights
## The suggestion

Two issues:

- The margins around the modal take up valuable screen real estate on tablet

Refactor modals to be full screen (this would need some design - should it only go to full screen for mobile, keep modal look for desktop?) 

Probably needs to be an option, rather than changing all modals... thinking those modals with just one input cell probably don't need to change?

- The `useKeyboardHeightAdjustment` hook is easy to miss, and we should remove responsibility on the developer to remember it every time

Call `useKeyboardHeightAdjustment` inside the `Modal` component instead, with whatever `height` prop was passed to the `Modal`.

Maybe these can be done separately (second one its pretty easy to implement) but maybe we just want to do the refactor of modals once 😁  

### Why should we invest time in this?

Modals are notoriously horrible to use on mobile. Would be a lot of work to move away from modals completely (maybe we'll get there one day?) but we should aim to make what already exists as easy to use as possible.

### Are there any risks associated with this change?

Just need to smoke test all the modals, that they're definitely all usable on mobile

### How much effort is required?

The `height` fix - couple hours.

More work for full screen modals, maybe a few days, between design discussions, refactoring the `Modal` component, and ensuring all existing modals display correctly in the new size.

### LINKED ISSUE #5416: iSC/Cold chain/GAPS: Cold storage location selector appears off-screen when the field is interacted with on Android
## What went wrong? 😲

Cold chain -> Equipment: cold storage location selector is off the screen when the dropdown is interacted with on Android

Video captured ->>> [here](https://drive.google.com/drive/folders/1eiT14EmmoG1BKb2HNdDlBKv-YYWAtZEi)

## Expected behaviour 🤔

Selector should stay with the dropdown field, not detached

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Cold chain -> Equipment`
2. Create a new equipment or edit an existing one
3. Click on the cold storage location dropdown to select an entry
4. See the selector window flying off the screen

## Your environment 🌱

- Open mSupply Version: `V2.4.0-RC1`
- Legacy mSupply Central Server Version: `V7.18.11`

- Platform: Galaxy Samsung Tab8 (Android)

- Database type: `SQLite3`

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #5009
Fixes #5416

TEST APK HERE: https://drive.google.com/drive/folders/1ghNna7Di0AcN-hzVheDaeE8FxQaQSZI5

# 👩🏻‍💻 What does this PR do?

Full screen modals! Also fixes autocomplete dropdowns going crazy places and some other funchy behaviour!

Screenshot 2025-01-15 at 4 57 18 PM

## 💌 Any notes for the reviewer?

Please give her a thorough sweep 😅 Modals had different ways of setting their widths, I think they're all okay now..

Few threads solved here, will put comments throughout

# 🧪 Testing

- [ ] Browser/desktop modals are working as expected
- [ ] On android
  - [ ] The bigger input modals are all in full screen mode
  - [ ] Dropdowns on android don't jump to strange places when keyboard comes up
  - [ ] In filters (e.g. Internal Order detail view -> filter) the footer hides while typing, so you can see more results

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Maybe worth mentioning somewhere that modals look different on android?
  2.

### CODE REVIEW

**Comment by lache-melvin** [comment]
uploaded a full screen modals test APK here: https://github.com/msupply-foundation/open-msupply/releases/tag/v2.5.0-RC1

File: client/packages/common/src/hooks/useDialog/useDialog.tsx [hunk 1]
```diff
@@ -250,8 +273,8 @@ export const useDialog = (dialogProps?: DialogProps): DialogState => {
           <DialogActions
             sx={{
               justifyContent: 'center',
-              marginBottom: '30px',
-              marginTop: '30px',
+              marginBottom: keyboardIsOpen ? 0 : '30px',
+              marginTop: keyboardIsOpen ? 0 : '30px',
```
Comment (lache-melvin) [inline client/packages/common/src/hooks/useDialog/useDialog.tsx:277]: Makes the margins around the buttons smaller while using the keyboard (because they take up a lot of space)

File: client/packages/common/src/hooks/useDialog/useDialog.tsx [hunk 2]
```diff
@@ -161,6 +166,9 @@ export const useDialog = (dialogProps?: DialogProps): DialogState => {
       isRtl,
       animationTimeout
     );
+    const { isOpen: keyboardIsOpen } = useKeyboardContext();
+    const isSmallerScreen = useMediaQuery('(max-height: 850px)');
```
Comment (lache-melvin) [inline client/packages/common/src/hooks/useDialog/useDialog.tsx:170]: Felt like a reasonable height to be okay with sticking with modals as they are, most tablets around 750-800 high... happy to play around with this

File: client/packages/common/src/hooks/useDialog/useDialog.tsx [hunk 3]
```diff
@@ -224,7 +234,20 @@ export const useDialog = (dialogProps?: DialogProps): DialogState => {
         sx={sx}
         TransitionComponent={Transition}
         disableEscapeKeyDown={false}
+        fullScreen={fullScreen}
       >
+        {fullScreen && (
+          <IconButton
```
Comment (lache-melvin) [inline client/packages/common/src/hooks/useDialog/useDialog.tsx:240]: Some modals used clicking on the backdrop to close (e.g. internal order create) so added close button

File: client/packages/common/src/ui/components/modals/InputModal/InputModal.tsx [hunk 4]
```diff
@@ -21,7 +21,11 @@ export const InputModal = ({
   onClose,
   title,
 }: InputModalProps) => {
-  const { Modal } = useDialog({ isOpen, onClose });
+  const { Modal } = useDialog({
+    isOpen,
+    onClose,
+    disableMobileFullScreen: true,
+  });
```
Comment (lache-melvin) [inline client/packages/common/src/ui/components/modals/InputModal/InputModal.tsx:28]: Input modal is small (used for like tax input) so don't need the full screen capability here

File: client/packages/common/src/ui/components/portals/AppFooter/AppFooter.tsx [hunk 5]
```diff
@@ -26,8 +27,10 @@ export const AppFooter: FC = () => {
     setAppSessionDetailsRef(appSessionDetailsRef);
   }, []);
 
+  const hideFooter = fullScreen || keyboardOpen;
+
   return (
-    <Box sx={{ display: fullScreen ? 'none' : undefined }}>
+    <Box sx={{ display: hideFooter ? 'none' : undefined }}>
```
Comment (lache-melvin) [inline client/packages/common/src/ui/components/portals/AppFooter/AppFooter.tsx:33]: When not in modal, i.e. typing in a table filter, hide the footers so can see more of the results

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditModal.tsx [hunk 6]
```diff
@@ -46,7 +44,7 @@ export const StocktakeLineEditModal: FC<
       okButton={
         <DialogButton variant="ok" onClick={onOk} disabled={!isValid} />
       }
-      height={height}
+      height={600}
```
Comment (lache-melvin) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditModal.tsx:47]: no longer need the `useKeyboardHeightAdjustment`! So move all the heights back to hard coded

File: client/packages/system/src/Report/components/ReportArgumentsModal.tsx [hunk 7]
```diff
@@ -68,11 +68,10 @@ export const ReportArgumentsModal: FC<ReportArgumentsModalProps> = ({
           }}
         />
       }
+      contentProps={{ sx: { margin: '0 auto' } }}
```
Comment (lache-melvin) [inline client/packages/system/src/Report/components/ReportArgumentsModal.tsx:71]: some styling is a little off in full screen mode, i need to review this more fully

File: client/packages/common/src/hooks/useDialog/useDialog.tsx [hunk 8]
```diff
@@ -224,14 +236,30 @@ export const useDialog = (dialogProps?: DialogProps): DialogState => {
...
         {title ? <ModalTitle title={title} /> : null}
         <form
           style={{
             display: 'flex',
             flexDirection: 'column',
             flex: '1 1 auto',
             overflow: 'auto',
+            ...(fullWidthOnMobile
+              ? {}
+              : { width: dimensions.width, margin: '0 auto' }),
```
Comment (lache-melvin) [inline client/packages/common/src/hooks/useDialog/useDialog.tsx:262]: Wide modals (like outbound shipment edit) should take up as much width as possible, but most want the content centered

File: client/packages/common/src/hooks/useDialog/useDialog.tsx [hunk 9]
```diff
@@ -154,13 +160,17 @@ export const useDialog = (dialogProps?: DialogProps): DialogState => {
...
     deleteButton,
+    fullWidthOnMobile,
   }) => {
     // The slide animation is triggered by cloning the next button and wrapping the passed
     // on click with a trigger to slide.
     const { slideConfig, onTriggerSlide } = useSlideAnimation(
       isRtl,
       animationTimeout
     );
+    const { isOpen: keyboardIsOpen } = useKeyboardContext();
```
Comment (GeronimoJohn) [inline client/packages/common/src/hooks/useDialog/useDialog.tsx:171]: NIT: Noticed that sometimes the context values are destructured and sometimes they're not. Not sure where we stand on things. I'm a big fan of destructuring, but I'm wondering if we should update the variables returned from the context to `isKeyboardOpen` and `isKeyboardEnabled`. This would remove the need to alias them as well 😃

File: client/packages/common/src/hooks/useKeyboard/Keyboard.tsx [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+  defaultKeyboardControl
+);
+
+const { Provider } = KeyboardContext;
+
+export const KeyboardProvider = ({
+  children,
+}: {
+  children: React.ReactNode;
+}) => {
```
Comment (GeronimoJohn) [inline client/packages/common/src/hooks/useKeyboard/Keyboard.tsx:27]: NIT: Noticed this pattern recurring in our codebase. Thoughts on creating an interface for it to easily distinguish it as the props type?

File: client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx [hunk 11]
```diff
@@ -167,6 +176,18 @@ export function AutocompleteWithPagination<T extends RecordWithId>({
...
+    if (!keyboard.isEnabled) return open;
+
+    // Keep popper closed until keyboard is open
+    // keyboard moves popper up & out of correct position
+    if (!keyboard.isOpen) return false;
+
+    // Use externally controlled `open` state if provided
+    return open ?? keyboardSelectControl.isOn;
+  };
+
```
Comment (GeronimoJohn) [inline client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx:190]: I noticed this pattern has been defined twice so far. If we plan to use it more in the future, I'm wondering if it would be a good idea to define it as a reusable function, either on its own or provided by the context. 😃

**Review by GeronimoJohn — APPROVED** [review]
Code looks good to me! This is awesome stufffff. Just left a bunch of NITs 😅. Still need to test it manually - will let you know once I've done sooo ~

**Review by andreievg — COMMENTED** [review]
Thanks @lache-melvin, it's looking great.

I just had a quick look, just small suggestions for now.  Will try to review by the end of the day

**Review by andreievg — COMMENTED** [review]
Great work, thank you!. 
I have a couple of suggestions in this branch: https://github.com/msupply-foundation/open-msupply/compare/5009-mobile-modal-improvements...5009-mobile-modal-improvements(Avoid-context-and-use-use-helper-for-autocomplete-open-state)

Would be great to get those in, i tested (btw this helped a lot: https://github.com/msupply-foundation/open-msupply/pull/6235)

In the test i found the new requisition (manual requisition), wans't quite behaving, but it work good with the suggestion (even though technically behaviour is not identical in the select customer list view, because you can enter out of the autocomplete and it will 'close' the list, previously list always stays open, but that's extra logic that I didn't really want to get into)

File: client/packages/common/src/hooks/useDialog/useDialog.tsx [hunk 12]
```diff
@@ -154,13 +160,17 @@ export const useDialog = (dialogProps?: DialogProps): DialogState => {
     enableAutocomplete,
     sx = {},
     deleteButton,
+    fullWidthOnMobile,
```
[the remark this answers is not in the document]
Comment (lache-melvin) [reply client/packages/common/src/hooks/useDialog/useDialog.tsx:163]: no... I put this in to be able to maximise tablet width for inbound/outbound shipment & returns modal, where there are a lot of columns. Might as well be full width if we can.

Other modals, we had a width on them (e.g. 500px), so in full screen version, we should still keep the content 500px width, and centre it.

Maybe better solution is just to make the shipment/return modals wider everywhere if possible...

File: client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx [hunk 13]
```diff
@@ -132,6 +132,7 @@ export const CreateStocktakeButton: React.FC<{
     isOpen: modalController.isOn,
     onClose,
     disableBackdrop: true,
+    disableMobileFullScreen: true,
```
[the remark this answers is not in the document]
Comment (lache-melvin) [reply client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx:135]: kind of figured these ones didn't need to be, but maybe just as nice to have them as full screen, bit more consistent? 🤷‍♀️

File: client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx (hunk 11 above)
Comment (lache-melvin) [reply client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx]: Yeah great point - thought this could be part of clean up issue somewhere to consolidate the different autocomplete components, but andrei has fixed in his commit! 🔥

File: client/packages/common/src/hooks/useKeyboard/Keyboard.tsx (hunk 10 above)
Comment (lache-melvin) [reply client/packages/common/src/hooks/useKeyboard/Keyboard.tsx]: We actually do have a PropsWithChildren type that we should be using... this was a copy paste that I didn't even see 😅  Also removed by Andrei's changes though!

**Comment by lache-melvin** [comment]
Thanks team, have applied changes 🙏 Will merge now, hopefully any tweaks can come up in feedback over the next while before 2.6 release 😁
