### PR TITLE
6165 disable directions if cant add item

### LINKED ISSUE #6165: Able to interact with the 'Directions' field in a prescription even if can't add the item
## What went wrong? 😲

I am able to interact/fill out the directions field in a prescription, even if I cannot add an item

Weirdly enough, it lets me click the 'Save' button but does not save the prescription or the directions. But the status of the prescription changes to 'Picked'? Can be very confusing for the user

Video & screenshot attached ->>> [here](https://drive.google.com/drive/folders/1RWoAZLYoV1nONLde8dYUJe4Pno7dMId2)

## Expected behaviour 🤔

I think directions field should not be interactable with/should be greyed out. Save button disabled if no information has been entered or if the item has not been added? And the status should not be updated to 'Picked' if nothing meaningful was added to the prescription.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Prescriptions
2. Create a new prescription
3. Add an item that cannot be added - for example, you can backdate your prescription and try and add an item that did not have any stock on that day
4. Note the message the item cannot be added
5. Interact with the directions field and try and save the prescription
6. Note the button is enabled but nothing is saved
7. Note the status of the prescription changed to 'Picked'

## Your environment 🌱

- Open mSupply Version: V2.5.0-RC4
- Legacy mSupply Central Server Version: V7.18.00

- Platform: Galaxy Tab A8 (Android 14)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #6165 

# 👩🏻‍💻 What does this PR do?

When adding or editing a prescription, if the issued quantity is 0 directions inputs are disabled

If the item cannot be added to a prescription (no placeholders) the user should not need to complete the directions section

Screenshot 2025-02-25 at 2 53 52 PM

Also mentioned in the issue was the save button and picked status. These cases had been handled since:
Changing the status to 'Picked' in close/cancel is intended behaviour. 
When adding an item that does not have stock, the save button remains disabled -> expected behaviour

Another case that was still allowing to save + pick an empty prescription is if a user added an item in stock, entering a quantity to issue will enable the save button. If the user then changes the issued quantity to 0 the save button remains enabled. In this case it will 'save' the line and 'pick' the prescription, but not include any lines, as placeholders are not yet implemented

I added a step to disable the save button (via existing isDirty check) if the number of packs issued is 0. If a user wants to remove an item, that can do so via deleting the line rather than reducing the quantity to be issued

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to Dispensary -> Prescriptions
- [ ] Create a new prescription
- [ ] Add an item that cannot be added (stock of 0)
- [ ] Interact with the directions field and try and save the prescription
- [ ] Note the Save button is disabled
- [ ] Add an item that has stock -> add a quantity -> see the save button activate 
- [ ] Change the quantity to 0 -> see the save button and directions disable
- [ ] Close a prescription that has only lines with 0 quantity issued -> see the prescription status remain as new with no lines

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [x] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [x] Frontend

### CODE REVIEW

**Comment by lache-melvin** [comment]
Not related but looks like abbreviation state is still persisting between items? Did you implement the clearing?

**Comment by aimee-mcneil-melville** [comment]
Yes that went in on #6456, and it is clearing for me here.. Can you show me please?

**Review by lache-melvin — APPROVED** [review]
LGTM!

> Another case that was still allowing to save + pick an empty prescription is if a user added an item in stock, entering a quantity to issue will enable the save button. If the user then changes the issued quantity to 0 the save button remains enabled. In this case it will 'save' the line and 'pick' the prescription, but not include any lines, as placeholders are not yet implemented
>
> I added a step to disable the save button (via existing isDirty check) if the number of packs issued is 0. If a user wants to remove an item, that can do so via deleting the line rather than reducing the quantity to be issued

Thanks for adding - I think there are more cases to cover too (e.g. save button doesn't disable if you go through and individually clear the prescription lines rather than using Issue cell, or if you fill out a new item, then pick new item via dropdown...)

Will add a separate issue, I think fine for now. I think we need something to distinguish "dirty" (you have unsaved changes) and "complete/valid to save"

Will raise the abbreviation not clearing separately too :)

**Comment by mariyamsupply** [comment]
I think it'd be better if instead of disabling Directions we communicate  'Add quantity to add directions'

LineEditView 17

File: client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx [hunk 1]
```diff
@@ -380,82 +380,85 @@ export const PrescriptionLineEditForm: React.FC<
...
-                  }}
-                  onBlur={saveAbbreviation}
-                  onKeyDown={e => {
-                    if (e.key === 'Enter') {
-                      saveAbbreviation();
-                    }
-                  }}
-                  style={{ flex: 1 }}
+          {isDirectionsDisabled ? (
+            <Typography>{'Add a quantity to add directions'}</Typography>
```
Comment (lache-melvin) [inline client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx:388]: Needs a translation string

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Working great thanks Aimee, just need to update translation string

File: client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx (hunk 1 above)
Comment (aimee-mcneil-melville) [reply client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx:388]: Ah of course, thanks!

**Review by lache-melvin — APPROVED** [review]
🚀
