### PR TITLE
Fix opening balance for first R&R Form when stock is reserved.

### LINKED ISSUE #4472: R&R initial balance returning negative values!
## What went wrong? 😲

Screenshot 2024-07-31 at 10 40 47 AM

Its calculating based on AVAILABLE stock on hand now (from the the stock_on_hand view) but it actually needs to use TOTAL stock on hand...

## Expected behaviour 🤔

Balances should always be >= 0.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have some reserved stock for an item in program master list
2. Create R&R form for that program
3. Backwards calcs of the SOH at start of period are negative!

## Your environment 🌱

- Open mSupply Version: 2.2 develop
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #4472

# 👩🏻‍💻 What does this PR do?

Adds total_stock_on_hand to stock_on_hand view
Changes RnR Form logic to use total_stock_on_hand

## 💌 Any notes for the reviewer?

Also fixed an RnR Form test.
There's another unrelated test failing though.

# 🧪 Testing

- [ ] Setup for testing R&R forms (see: https://github.com/msupply-foundation/open-msupply/issues/4405)
- [ ] Create a stockline that will be part of your RnR Form with less available stock, than total stock. (This can be done by creating an outbound shipment, with a stock stock assigned, but leave the outbound shipment status as `Allocated` (Don't confirm `Picked`)
- [ ] Check the opening `stock on hand` is calculated correctly when the R&R form is created for that item.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/repository/src/migrations/v2_02_00/stock_on_hand_add_total_stock.rs [hunk 1]
```diff
@@ -0,0 +1,64 @@
+use crate::{migrations::sql, StorageConnection};
+
+pub(crate) fn migrate(connection: &StorageConnection) -> anyhow::Result<()> {
+    // re-create stock_on_hand and store_items
+    sql!(
+        connection,
+        r#"
+        DROP VIEW IF EXISTS stock_on_hand;
```
Comment (jmbrunskill) [inline server/repository/src/migrations/v2_02_00/stock_on_hand_add_total_stock.rs:8]: Postgres required both views to be re-created as they're dependant...

File: server/service/src/rnr_form/tests/finalise.rs [hunk 2]
```diff
@@ -71,11 +71,6 @@ mod finalise {
             .context(mock_store_a().id, "".to_string())
             .unwrap();
 
-        let last_requisition_number = RequisitionRowRepository::new(&context.connection)
```
Comment (jmbrunskill) [inline server/service/src/rnr_form/tests/finalise.rs:74]: This was just a test warning, I'd removed the need for this already but hadn't removed this query...

File: server/repository/src/migrations/v2_02_00/stock_on_hand_add_total_stock.rs [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+          LEFT OUTER JOIN (
+            SELECT
+              item_id,
+              store_id,
+              SUM(pack_size * available_number_of_packs) AS available_stock_on_hand,
+              SUM(pack_size * total_number_of_packs) AS total_stock_on_hand
+            FROM
+              store_items
+            WHERE
+              store_items.available_number_of_packs > 0 OR store_items.total_number_of_packs > 0
```
Comment (lache-melvin) [inline server/repository/src/migrations/v2_02_00/stock_on_hand_add_total_stock.rs:54]: I wondered whether this would affect anything, if there was anywhere that we were expecting all stock_on_hand lines to have available stock, but a quick code search seems like it's fine... 🤷‍♀️

**Review by lache-melvin — APPROVED** [review]
LGTM! Thanks James!

File: server/repository/src/migrations/v2_02_00/stock_on_hand_add_total_stock.rs (hunk 3 above)
Comment (jmbrunskill) [reply server/repository/src/migrations/v2_02_00/stock_on_hand_add_total_stock.rs:54]: Good call to check! I also think it's ok, but maybe worth mentioning in the chat just so people are aware...
