### PR TITLE
4587 basic reports error shows eternal loading indicator

### LINKED ISSUE #4587: Basic Reports error shows eternal loading indicator
## What went wrong? 😲

If something goes wrong generating the report, you get the error snack, and then the loading indicator for the rest of time:

image

## Expected behaviour 🤔

Nothing here component? Something went wrong? Some way to indicator that we tried and failed, but we aren't still trying 🤷‍♀️ 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Bang something up with your report config (or in my case, don't have the right permissions on for the report query hehe)
2. Generate the report
3. Its a disaster, you get an error
4. Circles of doom

## Your environment 🌱

- Open mSupply Version: V2.2.0 RC3
- Legacy mSupply Central Server Version: 7.16

- Platform: Android, also verified in browser

- Database type: sqlite

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4587 & #4589

# 👩🏻‍💻 What does this PR do?
Cover print structure error and change the spinner to a nothing here with the error message.
Screenshot 2024-08-15 at 7 29 46 AM

# 🧪 Testing

- [ ] Remove view item permissions in OG
- [ ] Load stock status report 
- [ ] Sync OMS 
- [ ] Try to view stock status report
- [ ] Should show Nothing here page with no permission message

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/reports/src/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -29,21 +34,24 @@ export const DetailView = () => {
     (reportArgsJson && JSON.parse(reportArgsJson.toString())) || undefined;
 
   return !report?.id ? (
-    <BasicSpinner />
```
Comment (andreievg) [inline client/packages/reports/src/DetailView/DetailView.tsx:32]: I think this one is ok to be a spinner (basically won't ever happen, unless user tries to edit url ?)

**Review by andreievg — APPROVED** [review]
Looks great thanks, I tested by building front end and accessing via bundle served by back end.

I think it's completely fine as is, but I would have moved error state to useGenerateRporet (so it returns muateAsync and error)

File: client/packages/reports/src/DetailView/DetailView.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/reports/src/DetailView/DetailView.tsx:32]: That's what I did 😉
