### PR TITLE
3909 display structured errors for edit inbound shipment lines

### LINKED ISSUE #3909: Quantity value in Inbound cannot be updated after the stocked-in lines are touched
## What went wrong? 😲
 
If I'm to compare the behavior with mSupply, this is definitely a big issue; but again it's oms : is it decided yet what should be the expected-behavior around modifying lines after the Inbound is delivered?

## Expected behaviour 🤔
As long as the inbound is not Verified (strictly not editable anymore), the values changed should reflect in the SoH despite the previous stocks being touched/issued out?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Create a inbound with a item
2. Put quantity sth like `1` and just confirm the status till `Delivered`. Your `1` stock is in which you can see under `Inventory>View Stocks`
3. Now go back to that same inbound and open the line.
4. This time, change that value to `2`.
5. See `Inventory>View Stocks`, the SoH has been updated to `2`
6. Now create a outbound with that same item-line and issue out `1` item. 
7. Confirm it as `Shipped` so that you can see the SoH now as `1` under `Inventory>View Stocks`
8. Go back to that same Inbound and try to edit the line again
9. This time, change the quan to sth like `3`. 
10. On clicking OK, it resets back to the previous value: if the value is not to be updated, maybe there should be alert or info like why the quan is not adjustable anymore suddenly

In mSupply normally, we're actually allowed to update the values in `cn` SI regardless of those stocks have been issued out or not (i.e., the change reflects the SoH as well accordingly; and obviously you can't reduce the issue-out lines from SI though). So should we expect the same in oms here? 

## Additional
[Here's the link to my database](https://drive.google.com/file/d/1M1SqTd99C6kpqAjS-2lA5RrGQ0mdmrfv/view?usp=drive_link): open the Inbound there and edit the quan and click OK; it resets to previous values everytime. 

## Your environment 🌱

- Open mSupply Version: v2.0.0 exe
- Legacy mSupply Central Server Version: v7-14-02

- Platform: server exe + browser (chrome)

- Database type: sqlite

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #3909

# 👩🏻‍💻 What does this PR do?

Surface the `batch reserved` error when trying to update an inbound shipment line after that batch has been reserved/issued:
Screenshot 2024-05-22 at 5 39 55 PM

(And adds mapping of other update_inbound_shipment_line structured errors to displayable messages)

## 💌 Any notes for the reviewer?

Related to the question in the issue, `why can't I edit an inbound shipment line once I've issued/reserved stock?`, it comes back to this validate step:

https://github.com/msupply-foundation/open-msupply/blob/0db98a1877d654df50b1706f7512fb99bd12854f/server/service/src/invoice_line/inbound_shipment_line/validate.rs#L28-L36

Note that `line` is the existing invoice_line.

I think this is a little strict? Yes, if `line.number_of_packs != batch.available_number_of_packs`, some of the batch has been reserved/issued. But let's say we were wanting to increase the number of packs (`updated_line.number_of_packs > line.number_of_packs`) - I don't see a problem with some of the packs being reserved?

Well, I suppose the better check would be like we have for inventory adjustments: Would the new number_of_packs reduce `available_number_of_packs` below 0? If so, obviously we need an error, but otherwise its fine?

Any objections to changing this?

# 🧪 Testing

- [ ] Create a inbound with a item
- [ ] Set pack qty to 1 
- [ ] confirm the status to Delivered. 
- [ ] Now go back to that same inbound and open the line
- [ ]  change that pack qty to 2 (should save fine)
- [ ] Now create a outbound with that stock line and issue out 1 pack
- [ ] Go back to that same Inbound and try to edit the line again
- [ ] Change quantity to 3
- [ ] TEST: on save you should get an error snack saying batch is reserved

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Comment by mark-prins** [comment]
When I add a line to an inbound, I get an error 😱 

Screenshot 2024-06-06 at 10 02 15 AM


The changes are checking for a `__typename` prop to be returned but the query hasn't been updated to include it. Only the error node returns the typename.
For the `operations.graphql` file I had to apply these changes:

```
diff --git a/client/packages/invoices/src/InboundShipment/api/operations.graphql b/client/packages/invoices/src/InboundShipment/api/operations.graphql
index 8a8f9b82d..8c5671a12 100644
--- a/client/packages/invoices/src/InboundShipment/api/operations.graphql
+++ b/client/packages/invoices/src/InboundShipment/api/operations.graphql
@@ -279,6 +279,7 @@ mutation updateInboundShipment(
       }
     }
     ... on InvoiceNode {
+      __typename
       id
       invoiceNumber
     }
@@ -304,6 +305,7 @@ mutation deleteInboundShipments(
           }
         }
         ... on DeleteResponse {
+          __typename
           id
         }
       }
@@ -370,6 +372,7 @@ mutation deleteInboundShipmentLines(
           }
         }
         ... on DeleteResponse {
+          __typename
           id
         }
       }
@@ -459,6 +462,7 @@ mutation upsertInboundShipment(
           }
         }
         ... on DeleteResponse {
+          __typename
           id
         }
       }
@@ -486,6 +490,7 @@ mutation upsertInboundShipment(
           }
         }
         ... on InvoiceLineNode {
+          __typename
           id
         }
       }
@@ -521,6 +526,7 @@ mutation upsertInboundShipment(
           }
         }
         ... on InvoiceLineNode {
+          __typename
           id
         }
       }
@@ -544,6 +550,7 @@ mutation upsertInboundShipment(
           }
         }
         ... on InvoiceLineNode {
+          __typename
           id
         }
       }
@@ -567,6 +574,7 @@ mutation upsertInboundShipment(
           }
         }
         ... on InvoiceLineNode {
+          __typename
           id
         }
       }
@@ -594,6 +602,7 @@ mutation upsertInboundShipment(
           }
         }
         ... on DeleteResponse {
+          __typename
           id
         }
       }
@@ -625,6 +634,7 @@ mutation upsertInboundShipment(
           }
         }
         ... on DeleteResponse {
+          __typename
           id
         }
       }
```

File: client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx [hunk 1]
```diff
@@ -95,8 +96,15 @@ const useDraftInboundLines = (item: InboundLineItem | null) => {
...
 
   const saveLines = async () => {
-    if (isDirty) await mutateAsync(draftLines);
-    setIsDirty(false);
+    if (isDirty) {
+      const { errorMessage } = await mutateAsync(draftLines);
+
+      if (errorMessage) {
+        error(errorMessage)();
+      }
```
Comment (mark-prins) [inline client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx:104]: Because this function doesn't throw an error, the modal is closed when an error is shown. 
We keep the modal shown when an error happens, so that the user can correct values without losing all changes - to me it felt odd when the modal closed. I'd suggest this:

```suggestion
      if (errorMessage) {
        throw new Error(errorMessage);
      }
```

as well as fixing the error handler in the button onClick:

```
              } catch (e) {
                error((e as Error).message)();
              }
```

.. I'll make a suggestion branch tho, this comment isn't terribly clear!

**Review by mark-prins — CHANGES_REQUESTED** [review]
Very nice!
Couple of quick things
* adding __typename
* changing error handling behaviour

and it would also be nice to loosen the validation check, as you say in the pr comment 🙏 

I've put my change into a [suggestion branch](https://github.com/msupply-foundation/open-msupply/compare/3909-show-error-if-adjusting-inbound-once-stock-issued...3909-show-error-if-adjusting-inbound-once-stock-issued(suggestion)) if that's helpful

**Comment by lache-melvin** [comment]
Thanks for review Mark!

> * adding __typename

[65ee046](https://github.com/msupply-foundation/open-msupply/pull/3979/commits/65ee0464058137e0aaffe0984f96420640aa7eca)

> * changing error handling behaviour

[501d3c8](https://github.com/msupply-foundation/open-msupply/pull/3979/commits/501d3c86773950060f6b86c3236b38f6c20d566e)


> and it would also be nice to loosen the validation check, as you say in the pr comment 🙏

I started on the loosening validation check, but realised there was a bit to rework there... need the stock line data available in places that it isn't currently, and wanted to keep this PR targetted. Also think it might just be creating more rework for #3933, so have flagged to consider this there!
