### PR TITLE
6592 clearable json form fields

### LINKED ISSUE #6592: Vaccination (vax) card patient schema: nationality and education fields keep the value when cleared, only shows correct upon refreshing
## What went wrong? 😲

I have a custom vaccination (vax) patient schema in my store :)

Issue 1: when clearing certain fields (so far confirmed with nationality and education as per the video), they keep the values entered after saving and only show the cleared one when refreshing the page. Does not happen the other way - e.g. when adding the values back in, they show straight away instead of a previously empty field. 

Issue 2: even though we can clear multiple fields at the same time, because of the above it looks like you aren't able to. So actually any action brings back the values previously entered in those fields. 

https://github.com/user-attachments/assets/81f47397-9ce7-440d-ab93-f418b8c70aae

## Expected behaviour 🤔

Should be behaving like other fields and clearing smoothly (not bringing the values back)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have the custom vaccination card patient schema uploaded to your store
2. Go to Dispensary -> Patients and create a new patient
3. See extra fields added and the form is now in French
4. Choose nationality and education and save your changes -> refresh -> remove -> save -> see the values are back
5. Refresh -> the values are now gone

## Your environment 🌱

- Open mSupply Version: V2.6.0-RC1
- Legacy mSupply Central Server Version: V8.0.11

- Platform: Google Chrome (browser for Mac)

- Database type: PostgreSQL

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #6592

# 👩🏻‍💻 What does this PR do?

Allows clearing of autocomplete fields in JSON forms.

Also fixed the date of birth bc she was jank and squish like this:
Screenshot 2025-02-25 at 4 07 33 PM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Upload custom patient schema
- [ ] Try to set and clear the autocomplete fields (e.g. nationality) - you can
- [ ] On narrow screen, age wraps so that date of birth date picker is always readable

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx [hunk 1]
```diff
@@ -102,12 +110,12 @@ const UIComponent = (props: ControlProps) => {
             flexBasis: '100%',
           }}
           options={options}
-          value={localData ?? { value: '', label: '' }}
+          value={localData ?? null}
```
Comment (lache-melvin) [inline client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx:113]: null instead of empty object here means the clear `X` won't show when the value is empty

File: client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx [hunk 2]
```diff
@@ -52,7 +52,15 @@ const UIComponent = (props: ControlProps) => {
     () => getDisplayOptions(schemaOptions),
     [schemaOptions]
   );
+
+  const clearable = !props.config?.required;
+
   useEffect(() => {
+    if (!data && clearable) {
+      setLocalData(undefined);
+      return;
```
Comment (lache-melvin) [inline client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx:61]: issue was we were only updating local state if data matched one of the options

File: client/packages/programs/src/JsonForms/common/components/Group.tsx [hunk 3]
```diff
@@ -27,13 +27,7 @@ const UIComponent = (props: LayoutProps) => {
     return <MaterialLayoutRenderer {...layoutProps} />;
   }
   return (
-    <Box
-      sx={{
-        paddingLeft: 2,
-        paddingRight: 2,
-        marginBottom: 2,
```
Comment (lache-melvin) [inline client/packages/programs/src/JsonForms/common/components/Group.tsx:34]: side quest, group was getting squished in by extra padding, not needed

File: client/packages/programs/src/JsonForms/components/DateOfBirth.tsx [hunk 4]
```diff
@@ -81,13 +81,20 @@ const UIComponent = (props: ControlProps) => {
...
+          width="100%"
+          flexWrap="wrap"
+        >
           <BaseDatePickerInput
             // undefined is displayed as "now" and null as unset
             value={dob}
             onChange={onChangeDoB}
             format="P"
-            width={135}
+            sx={{ width: 135 }}
```
Comment (lache-melvin) [inline client/packages/programs/src/JsonForms/components/DateOfBirth.tsx:97]: this wasn't getting passed through, works through sx

File: client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx (hunk 1 above)
Comment (andreievg) [reply client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx:113]: Should localData be nullable, or undefined ?

File: client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx [hunk 5]
```diff
@@ -52,7 +52,15 @@ const UIComponent = (props: ControlProps) => {
     () => getDisplayOptions(schemaOptions),
     [schemaOptions]
   );
+
+  const clearable = !props.config?.required;
+
   useEffect(() => {
+    if (!data && clearable) {
```
Comment (andreievg) [inline client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx:59]: is clearable always available (are params and config available from the start) ? need to be in dependencies ?

**Review by andreievg — COMMENTED** [review]
Wanted to approve but wasn't sure about dependencies in the hook

**Comment by Chris-Petty** [comment]
image

re the dat input

(b4 ur pr):
image

It has confused me what happened but I figured it out now - if the age is less than a year it doesn't let you edit the "Age" input, it go hidden? I guess to show the age text in months/days. Also kinda expected 0.5 to be valid input but as soon as I type `0` it changes to `1 month, 24 days`, which would be 01/01/2025. New issues I suppose if at all.

File: client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx (hunk 5 above)
Comment (andreievg) [inline client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx:59]: does data update when handleChange is called (from parent) ?

**Review by Chris-Petty — APPROVED** [review]
image
LUVIT

Also the clearing of ddl values works good now.

THE ALIGNMENT of this DDL though haha

image

File: client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx (hunk 5 above)
Comment (lache-melvin) [reply client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx:59]: I think it was ok, bc if clearable is false, can't set data to be undefined anyway, but good catch thanks have added 🙏

Comment (lache-melvin) [reply client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx:59]: Yep

File: client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx (hunk 1 above)
Comment (lache-melvin) [reply client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx:113]: Aw noice

Comment (lache-melvin) [reply client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx]: [f41caad](https://github.com/msupply-foundation/open-msupply/pull/6678/commits/f41caad5e06319e23f360c7f11fdc0a40db19638)

File: client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx (hunk 5 above)
Comment (lache-melvin) [reply client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx:59]: [23a5727](https://github.com/msupply-foundation/open-msupply/pull/6678/commits/23a5727f0757512e8ad51cf1821a3c51bf840099)

**Comment by lache-melvin** [comment]
> if the age is less than a year it doesn't let you edit the "Age" input, it go hidden? I guess to show the age text in months/days. Also kinda expected 0.5 to be valid input but as soon as I type `0` it changes to `1 month, 24 days`, which would be 01/01/2025. New issues I suppose if at all.

That is funky, probs worth an issue at some point 😢
