### PR TITLE
10980 dashboard decimals

### LINKED ISSUE #10980: Stock widget fails if there are decimal under/over stock preference values
## What went wrong? 😲

With the change introduced in #10922 the values of understock and overstock which are defined in OG

Image

are used for the stock dashboard widget in place of the hard coded `3` and `6` values we had.

However if you enter a decimal for these parameters then the widget fails:

Image

Image

## Expected behaviour 🤔
Should be able to enter decimals

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Update store preferences
2. Sync, logout and log in again

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #10980 

Taking changes from copilot (#10981) but basing on 2.17.0-RC

`monthsUnderstock`/`monthsOverstock` store preferences are `f64`, but the `itemCounts` GraphQL query typed `lowStockThreshold`/`highStockThreshold` as `Int`. Passing a decimal value (e.g. `1.5`) caused a GraphQL type validation error and the stock widget rendered "No data available".

# 👩🏻‍💻 What does this PR do?

- **GraphQL schema** (`lib.rs`, `item_counts.rs`): Change `lowStockThreshold` / `highStockThreshold` arguments from `Option<i32>` → `Option<f64>`, exposing them as `Float` in the schema. Update default constants accordingly.
- **Service layer** (`item_count.rs`): Update all threshold parameters in the trait and `ItemServiceCount` impl from `i32` → `f64`; remove now-redundant `as f64` casts in comparisons. Update tests to use float literals.
- **Client GraphQL operation** (`operations.graphql`, `operations.generated.ts`): Change variable declarations from `Int!` → `Float!` and update generated TypeScript types (`Scalars['Int']` → `Scalars['Float']`).

Screenshot 2026-03-25 at 9 46 39 AM

## 💌 Any notes for the reviewer?
The separate notification-alert preferences (`NumberOfMonthsThresholdToShowLowStockAlertsForProducts`, `NumberOfMonthsThresholdToShowOverStockAlertsForProducts`) remain `i32` — they are loaded from a different preference key and are not affected by this issue. The `as f64` casts at their call sites are therefore intentional.

# 🧪 Testing

- [ ] Update the preferences in OG to be decimals and view the dashboard (after sync and logout/login)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/printer/update.rs [hunk 1]
```diff
@@ -71,8 +70,8 @@ pub fn update_printer(
     let result = ctx
         .connection
         .transaction_sync(|connection| {
-            let existing = validate(connection, &input)?;
```
Comment (mark-prins) [inline server/service/src/printer/update.rs]: warnings in console when building - I can see that the `existing` is unused

**Comment by mark-prins** [comment]
sorry @roxy-dao! I had intended to comment.. not sure why I didn't 🥺
