### PR TITLE
10454/honeywell UI issues

### LINKED ISSUE #10454: Honey Well Scanner, Mobile view : UI issues
## What went wrong? 😲

- [ ] Date format is mm/dd/yyyy which is different to oms date formate - dd/MM/yyyyy
- [ ] The Name label should be changed to "Item" as oms uses the label Item. And please add a <space > in between item and the label

Image

- [ ] Back button not functioning to navigate though the screen ( back button in touch screen works) 
- [ ] Tab button, escape button and Enter button are not work as expected.
 i.e. Insert user name and password, and press Enter Key in log in screen : < not working > : user has to press log in button on the screen.
- [ ] User warning/ confirmation messages not mobile screen freindly.
Image

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2.16.0
- Legacy mSupply Central Server Version:

- Platform: Honey Well / Android

- Database type:

### LINKED ISSUE #10458: Honey Well Scanner, Mobile view : It is hard to find the qty received field and navigate through the screens for IS
## What went wrong? 😲

Although the user has been navigated to the Item Edit screen, the item qty field is not immediately visible. User needs to scroll horizontally to see the received qty field which is also not showing the full label.
 
Image

**Item variant field is not displaying the manufacturer details**

Image

**User is not sure where to insert the qty?**

Image

**Other details tab is not showing properly and cannot access it**

Image

## Expected behaviour 🤔

It would be better, if the user can directly able to insert the Batch number, Expiry Date and the Qty Received without scrolling the screen. 
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Log in to oms via honeywell scanner
2. Go the IS
3. Scan the product barcode 

## Your environment 🌱

- Open mSupply Version: 2.16.0
- Legacy mSupply Central Server Version:

- Platform: Android

- Database type:

### PR DESCRIPTION
**Pull request by esmehm**
Fixes #10454 
And Fixes #10458 

# 👩🏻‍💻 What does this PR do?

This PR works on the inbound shipments with a honeywell scanner (or any other mobile sized screen). It:
- Fixes bug in item name, which was already right aligned for short names but breaking for long ones (in LTR languages)

Before this PR:
image

After this PR:
image

Checked it's fine on RTL languages:
image

- Removes the on hold button on mobile (initially raised as User warning/ confirmation messages not mobile screen friendly.)
Before this PR:
image

After this PR:
image

- Change default "columns" which show on mobile to match zapp app (namely default mobile fields should be name, code, batch, expiry, pack size, quantity of packs). User can turn on more columns if they wish and resetting takes you back to defaults
After this PR it has the right ones:
image
- Prevent opening and editing existing items in the shipment detailed view - it should not open the wide modal on mobile
Previously these cars were clickable:
image

And opened this modal which was unusable on small screens;
image

After this PR the cards are not clickable on mobile, and so you never see that modal. Note in the future we may make them clickable again and go to a different modal.

## 💌 Any notes for the reviewer?

Thanks for reviewing! Voila tout!

# 🧪 Testing

Best tested on the honeywell scanner

- [ ] _(e.g.)_ Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] _(e.g.)_ This sample datafile: _google drive link_
- [ ] _(e.g.)_ Open a requisition with some lines
- [ ] _(e.g.)_ Make a couple invoices supplying some amount of those lines
- [ ] _(e.g.)_ Review that "issued" column is the sum of the amount already issued in invoices for this requisition

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -131,7 +131,7 @@ const DetailViewInner = () => {
     grouping: { enabled: true },
     isLoading: false,
     initialSort: { key: 'itemName', dir: 'asc' },
-    onRowClick: !isDisabled ? onRowClick : undefined,
+    onRowClick: !isDisabled && !isExtraSmallScreen ? onRowClick : undefined,
```
Comment (esmehm) [inline client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx]: I chose to do this instead of including this logic within `isDisabled` in case it had unforseen impacts and so it is easier to change as we expect to change it soon to have its own functionality (opening another modal)

**Review by jmbrunskill — APPROVED** [review]
Works great for me, thanks!
