### PR TITLE
6139 stocktake page performance improvement

### LINKED ISSUE #6139: Store becomes incredibly slow when a big stocktake is generated
## What went wrong? 😲

Scenario: I am generating a stocktake with 923 items. All the lines are placeholders for now, as I generated a stocktake for items with an expiry date of 31/01/2025. As seen on the video, a simple action of changing pages or accessing the sync modal or syncing records takes an incredibly long time.

This is happening on a tablet, where I have my remote site running. A stocktake of 923 items doesn't seem too large to me, so I am hoping this is not an expected behaviour :') This does not happen on a Central Server when I create a stocktake with ~500 items

Video of the behaviour is attached ->>> [here](https://drive.google.com/drive/folders/1YBdcZqu1A2C0s4y6N2Y43E6Dd1mwfVe7)

## Expected behaviour 🤔

Should be faster

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have a remote site running on a tablet
2. Have many items added to your store and a few master lists visible
3. Generate a stocktake with a few hundred items - for example, I did one for an expiry date before end of month
4. Click around and try to perform basic actions - see even a simple action like changing pages takes a very long time

## Your environment 🌱

- Open mSupply Version: V2.5.0-RC3
- Legacy mSupply Central Server Version: V7.18.00

- Platform: Galaxy Tab A8 (Android 14)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #6139 

# 👩🏻‍💻 What does this PR do?

Makes stocktake page bearably slow rather than outrageously slow. Turns out we didn't fully remove "grouping by item" code and is vestiges were skipping virtualising the DataTable :(

## 💌 Any notes for the reviewer?

I went from react dev tools profiler crashing on refresh to actually capturing a trace!

# 🧪 Testing

- [ ] Make a stocktake with 500 lines, set pagination to 500
- [ ] Refreshing the page takes less the the 4s it used to on a macbook
- [ ] Edit rows loading the modal is reasonably fast (rather than having a 2-4s delay on Macbook)
- [ ] When you edit a row, the expando arrow thing doesn't weirdly show until you refresh the page image
- [ ] When you finish editing a row, we highlight all the related batches 

https://github.com/user-attachments/assets/14df3b30-aa20-4a16-9a38-6763cfeadc38

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/DataTable.tsx [hunk 1]
```diff
@@ -93,7 +93,6 @@ const RenderRows = <T extends RecordWithId>({
         {(row, idx) => (
           <DataRow
             key={row.id}
-            ExpandContent={ExpandContent}
```
Comment (Chris-Petty) [inline client/packages/common/src/ui/layout/tables/DataTable.tsx:96]: It's guaranteed to be undefined by the condition scope

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx [hunk 2]
```diff
@@ -63,7 +63,6 @@ export const StocktakeLineEdit: FC<StocktakeLineEditProps> = ({
   const t = useTranslation();
   const { highlightRows } = useRowHighlight();
   const { error } = useNotification();
-  const { isGrouped } = useIsGrouped('stocktake');
```
Comment (Chris-Petty) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx:66]: Simply calling this hook seems to make that "expand all" chevron appear in the data table headers

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx [hunk 3]
```diff
@@ -116,13 +115,8 @@ export const StocktakeLineEdit: FC<StocktakeLineEditProps> = ({
...
 
-    if (item) {
-      const rowIds = draftLines.map(line =>
-        isGrouped ? line.itemId : line.id
-      );
-
-      highlightRows({ rowIds });
-    }
+    const rowIds = draftLines.map(line => line.id);
+    highlightRows({ rowIds });
```
[the remark this answers is not in the document]
Comment (roxy-dao) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx:118]: Half works... I would keep it in still

**Review by roxy-dao — APPROVED** [review]
🚀
