### PR TITLE
6188-6407-5035 Add debounced value callback for prescription comment field

### LINKED ISSUE #6188: On the internal order Info panel what I am writing disappear after I wrote it
## What went wrong? 😲
As recording

Nb: When working on this issue please fix https://github.com/msupply-foundation/open-msupply/issues/6407 as well 

## Expected behaviour 🤔
As the translation of the french saying says "Spoken words fly away, written words stay". I believe my comment should stay :)
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Replenishment > Internal order'
2. Open an internal order
3. click on the More button
4. Write a comment in the comment box
5. Wait
6. See error. What you have written disappear

## Your environment 🌱

- Open mSupply Version: 2.5.0RC4
- Legacy mSupply Central Server Version: v8.00RC43

- Platform: omSupply, desktop, android

- Database type: SQLlite3

### PR DESCRIPTION
**Pull request by noel-yeldos**
Multi-issue PR (Main issue is #6188 with #6407 and #5035 as linked issues)

This PR Fixes #6188 (Actually the issue that is fixed is #6407 - unable to replicate #6188 and #5035 - only written this way to satisfy sync labels action)

# 👩🏻‍💻 What does this PR do?
Add debounced value callback for prescription comment field input so that updatePrescription does not fire for each keystroke.

https://github.com/user-attachments/assets/7ad61090-ddc4-40c3-be9c-7901d417a7f5

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to Dispensary -> Prescriptions
- [ ] Create a new prescription or edit an existing one
- [ ] Click on more and type some text - either fast or slow, long or short sentences into the comment field
- [ ] Observe that entered text does not disappear randomly

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx [hunk 1]
```diff
@@ -27,6 +28,8 @@ export const AdditionalInfoSectionComponent: FC = () => {
   const [commentBuffer, setCommentBuffer] = useBufferState(comment ?? '');
   const { localisedDate } = useFormatDateTime();
 
+  const debouncedUpdate = useDebouncedValueCallback(update, [commentBuffer]);
```
Comment (roxy-dao) [inline client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx:31]:
```suggestion
  const debouncedUpdate = useDebouncedValueCallback(update, [commentBuffer], 1000);
```

Your change is still causing numerous API calls.. 

https://github.com/user-attachments/assets/45fe62c8-220c-4f31-84b8-0172223b632b

If you look at examples where the comment is not being jumpy, you will see that there is a 1k timeout on the API call.. looks like the 500 timeout on the `useDebouncedValueCallback` is not enough and still causes constant API calls while throttlin' network to 3G....

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks Noel~

See comment below

The issues in the other ones might be caused by networks slower than 3G, so might need to extend the timeout =/...

File: client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx:31]: @roxy-dao thanks for catching that! For some reason when I tested previously it wasn't behaving strangely. But I'm still finding that using ```useBufferState``` with the ```debouncedValueCallback``` even with 1000 timeout doesn't fully resolve the issue. I'm finding that using ```useState``` instead seems to be working fine. Is it ok to swap?

Comment (roxy-dao) [reply client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx:31]: If extending the timeout to 1k causes problems then your original fix definitely caused problems...? useBuffer is saving the value into state.... maybe needs some thinking?

Comment (noel-yeldos) [reply client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx:31]: Oh my original fix did cause problems. It's just for whatever reason when I tested before putting the PR in it was working and so I didn't catch it then. When I test now it is causing problems. UseState isn't but I'll have a look at how it's being used in other places.

File: client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx [hunk 2]
```diff
@@ -24,9 +24,11 @@ export const PrescriptionDetailsSectionComponent: FC = () => {
   const [theirReferenceInput, setTheirReferenceInput] =
     useState(theirReference);
 
-  const debouncedUpdate = useDebouncedValueCallback(update, [
-    theirReferenceInput,
-  ]);
+  const debouncedUpdate = useDebouncedValueCallback(
+    update,
+    [theirReferenceInput],
+    1500
```
Comment (noel-yeldos) [inline client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx:30]: Added here as well because the same issue was happening

**Review by roxy-dao — APPROVED** [review]
Thanks Noel~
