### PR TITLE
7196 sync http request timeout

### LINKED ISSUE #7196: Sync getting stuck indefinitely
## What went wrong? 😲

While syncing it gets stuck forever sometimes. One client has this happen daily. 

## Expected behaviour 🤔

Should timeout any request after modest period.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. have an interpreted 4D server
2. OMS remote (can be central)
3. put a breakpoint in `Web Authentication` method
4. Try sync, feel free to progress to one or 2 steps by continuing the 4D breakpoint
5. It sits, waiting forever for the request to finish

## Your environment 🌱

A client was having this issue so representing that below, although this is easy to repro in dev env as above

- Open mSupply Version: 2.6
- Legacy mSupply Central Server Version: 8.0

- Platform: windows

- Database type: sqlite I think

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #7196

# 👩🏻‍💻 What does this PR do?

Adds total timeout of 5mins to sync http requests using the api helper. Long duration in case reading big response on low bandwidth, and otherwise covers all bases such as getting stuck writing body in the request.

read_timeout too of 30s. If it stops reading anything from the connection for over 30s we timeout. 

image

You will see an error like this. We can make it pretty by handling it properly later.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] OG interpreted
- [ ] Init OMS central
- [ ] Sync - all good
- [ ] put breakpoint in `Web Authenticate` method
- [ ] Sync - should timeout after 30s
- [ ] It's quite hard to effectively manually test the 300s overall timeout... need to limit bandwidth really

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/util/src/api_helper.rs [hunk 1]
```diff
@@ -20,8 +20,10 @@ where
     loop {
         let client = Client::builder()
             .connect_timeout(Duration::from_secs(connection_timeouts.0[index]))
+            .read_timeout(Duration::from_secs(30)) // If there is no read from the socket after 30s abort
+            .timeout(Duration::from_secs(300)) // generous because some sync records may have big payloads like reports that take a long time to sync on low bandwidth
```
Comment (andreievg) [inline server/util/src/api_helper.rs:24]: can do from minutes in this case

**Review by andreievg — APPROVED** [review]
Looks good to me, let's merge and make a build !

File: server/util/src/api_helper.rs [hunk 2]
```diff
@@ -20,8 +20,10 @@ where
...
             .build()
-            .unwrap();// This method fails if a TLS backend cannot be initialized, or the resolver cannot load the system configuration.
+            .unwrap(); // This method fails if a TLS backend cannot be initialized, or the resolver cannot load the system configuration.
```
Comment (craigdrown) [inline server/util/src/api_helper.rs:26]: important improvement!

File: server/util/src/api_helper.rs (hunk 1 above)
Comment (andreievg) [reply server/util/src/api_helper.rs:24]: Thanks, i should have checked, it's nightly feature
