### PR TITLE
3885 fix catalogue item autocomplete duplicates

### LINKED ISSUE #3885: Search filter for Catalogue item while creating new CCE looks weird
## What went wrong? 😲
 
Search filter for `Catalogue item` while creating new CCE looks weird

## Expected behaviour 🤔
Search filter results should return exactly the correct number of results only (exclude duplicates especially like in the recording, the number of times it duplicates increases with more attempts to search)

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Do the minimum to see the Coldchain module in your view
2. Under Coldchain>Equipment, create a new asset
3. Choose a category
4. Now type some search-term for `Catalogue item`. For eg, type `emvolio`. You'll see one result at first
5. Backspace your search-term and retype it. Retype `emvolio` again
6. See error: the same entry is duplicated there
7. Backspace that again and repeat, this time 3 duplicates and so on.

## Recordings
Video reference: https://screenrec.com/share/2UbMZaidse

## Your environment 🌱

- Open mSupply Version: v2.0.0-rc5 exe
- Legacy mSupply Central Server Version: v715-dev2

- Platform: standalone + browser(chrome)

- Database type: sqlite

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #3885

# 👩🏻‍💻 What does this PR do?

Before, entering some search value in the catalogue item input, backspacing and then entering again, caused duplicates like this:

Screenshot 2024-06-24 at 1 10 57 PM

Working now:

Screenshot 2024-06-24 at 1 12 15 PM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create new equipment/CCE asset
- [ ] Search in the autocomplete input for catalogue item
- [ ] Backspace
- [ ] retype same input
- [ ] Repeat
- [ ] Still the same number of search results, all unique

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx [hunk 1]
```diff
@@ -41,6 +41,7 @@ interface CreateAssetModalProps {
 const mapCatalogueItem = (catalogueItem: AssetCatalogueItemFragment) => ({
   label: `${catalogueItem.code} ${catalogueItem.assetType?.name} ${catalogueItem.manufacturer} ${catalogueItem.model}`,
   value: catalogueItem.id,
+  id: catalogueItem.id,
```
Comment (lache-melvin) [inline client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx:44]: React needed the ID for unique key on list rerender

File: client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx [hunk 2]
```diff
@@ -175,8 +176,8 @@ export const CreateAssetModal = ({
 
   // when the pagination changes, fetch the next page
   useEffect(() => {
-    fetchNextPage({ pageParam: pagination });
-  }, [fetchNextPage, pagination]);
+    fetchNextPage({ pageParam: pagination.page });
+  }, [fetchNextPage, pagination.page]);
```
Comment (lache-melvin) [inline client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx:180]: Changing search params was creating a new pagination object, resulting in multiple pages of the same data 😭

File: client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx [hunk 3]
```diff
@@ -231,7 +232,7 @@ export const CreateAssetModal = ({
                     typeId: '',
                   });
                 }}
-                value={draft.categoryId}
+                value={draft.categoryId ?? ''}
```
Comment (lache-melvin) [inline client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx:235]: Side quest to remove a console warning about invalid values

File: client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx (hunk 2 above)
Comment (jmbrunskill) [reply client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx:180]: Great find!

**Review by jmbrunskill — APPROVED** [review]
Looks good to me!
