### PR TITLE
9613 query document_registry name

### LINKED ISSUE #7583: No patient is found by the number of program enrolment when using the program enrolment filter
## What went wrong? 😲

When we are looking for a patient through the program enrolment filter with the unique number generated per patient, we don't find anything. 
I don't really understand what the filter shows: even by writing the name of the program 'vaccination des enfants', nothing comes out. 

https://github.com/user-attachments/assets/8b8df12e-10e8-4e58-aa63-bfeea91133a4

## Expected behaviour 🤔

We should be able to find a patient through their program enrolment number. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'patient'
2. Click on 'filter', 'program enrolment'
3. Type a number '001' or 'vaccination des enfants'
4. nothing appears 

## Your environment 🌱

- Open mSupply Version: Demo 2.7.00 Central server
- Legacy mSupply Central Server Version: NA

- Platform: Mac book 

- Database type: NA

### LINKED ISSUE #9613: Program filter in 'Encounters' does not work
## What went wrong? 😲

When viewing Encounters, we can see the program they are associated with in one of the columns

When typing out the name, the 'Program' filter does not bring the results you'd expect

Actually, can't seem to figure out what the field wants the user to type?

https://github.com/user-attachments/assets/8897b66a-a5f0-4c1a-ab2c-ff8396b17b29

## Expected behaviour 🤔

If the program name is typed out, then the encounters associated with that program should come up

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have vaccines/immunization program setup in your store
2. Have a few encounters created for your patients
3. Go to Dispensary -> Encounters and see the list of your encounters there
4. Go to Filters -> Program and start typing out the name of your program(s)
5. See the results are not coming up

## Your environment 🌱

- Open mSupply Version: `V2.12.00-develop-10231639`
- Legacy mSupply Central Server Version: `V8.05.08`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #9613, fixes #7583

# 👩🏻‍💻 What does this PR do?

Change the `program_name` filter for encounters to filter on `document_registry::name` instead of `program::name`.

This is unintuitive but save for renaming everything because we've overloaded "program name" between the backend and UI (or even just within UI lol), that's all I've changed.

## 💌 Any notes for the reviewer?

Patients list page to search program (i.e. by `document_registry::name`) then use "Program Enrolment" search. To search by the patients' enrolment IDs, use "Patient Identifier" which also searches on code, name, NHI, and program enrolment ID:

https://github.com/msupply-foundation/open-msupply/blob/8d67c9012516a0090ef8c908a7e13593116316af/server/repository/src/db_diesel/patient.rs#L37-L43

Encounters list page doesn't have an effective way of searching by a patients enrolment id. The program name search is purely the `document_registry::name`

# 🧪 Testing

- [ ] Have patient programs/enrolments configured e.g. a vaccine program, another one
- [ ] Enrol some patients in one or the other or both
- [ ] Go to encounters page and search by program name (based on values in the "Program Name" column) and get expected search results
- [ ] Go to patients page, select extra filter "Program Enrolment" and search program names (from corresponding column), get expected results.
- [ ] To search the patient ID that's included in the Program Enrolment column values, use the "Patient ID" filter.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. The filter explanations in both places need double checking to ensure they're clear

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Review by jmbrunskill — COMMENTED** [review]
Did you investigate why this wasn't working for Mark. Codewise it looks fine but haven't tested myself yet. Can do but was going to wait for you to update?

Oops: Updated, read the comments sounds like we can't replicate?

**Comment by mark-prins** [comment]
I am using postgres - would be worth trying that. when I manually run the query above I get all patients who are enrolled in any program

**Comment by Chris-Petty** [comment]
@mark-prins has shared his datafile and his particular setup is why I can't see it :)

image

Note the the `Immunisation Program` program (first row) and the `Reproductive Health` program (second row) have the same master list as a context. For the purposes of the SQL query, that master list is the "program" table. 

When we filter the document registry by name, that in turn filters the program. As these document registry records have the same program, both show up in the results.

I'm not sure what are normal constraints for program (i.e. document registry) configuration. There are are virtually no restrictions on how you configure them in OG, hell the name can even be undefined, let alone not unique. You can also edit the name later.

I'm not sure what to make of a datafile that has Immunisation program and reproductive health both against a tuberculosis master list. While that's nonsensical, is the case of having several documents registered for the same master list something we want?

Anyyyway I think there is a way to get the filter to work on `search_term -> document_registry::name -> document_registry::document_type -> program_enrolment::document_type -> program_enrolment::patient_link_id -> ...` rather than what it's currently doing through `program`.

**Comment by mark-prins** [comment]
ah thanks Chris - that's just sloppy setup on my part then. thanks for checking it out 🙏

**Comment by Chris-Petty** [comment]
> Did you investigate why this wasn't working for Mark. Codewise it looks fine but haven't tested myself yet. Can do but was going to wait for you to update?
> 
> Oops: Updated, read the comments sounds like we can't replicate?

Can definitely replicate! Just needed several patient programs (`document_registry` records) using the same OG master list (mapped to `program` in OMS). I've improved it IMO, but I think for lack of uniqueness on `document_registry::document_type` it might be a sideways improvement depending on how people _really_ configure things. Our docs don't really suggest how to really use the thing by example tbh.

File: server/repository/src/db_diesel/document_registry.rs [hunk 1]
```diff
@@ -99,32 +101,33 @@ impl<'a> DocumentRegistryRepository<'a> {
 
         result
     }
+
+    pub fn create_filtered_query(filter: Option<DocumentRegistryFilter>) -> BoxedDocRegistryQuery {
```
Comment (Chris-Petty) [inline server/repository/src/db_diesel/document_registry.rs]: FWIW this doesn't use the connection in `Self` ('cause it returns a boxed query to use later), so doesn't really need to be associated with the struct. But it is elsewhere so I just did the same here
