### PR TITLE
Move migrations to correct folder

### LINKED ISSUE #2941: App won't start after upgrading to 1.7 (develop) - migration errors
## What went wrong? 😲
 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to run DB migrations

Caused by:
    0: Error during migration (1.7.0)
    1: "UNKNOWN" ("\"\\\"database disk image is malformed\\\"\"")', /Users/jamesbrunskill/open-msupply/server/server/src/lib.rs:77:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected behaviour 🤔
Open-mSupply should start!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Initialise your sqlite database from the main branch v1.6.02
2. Switch to develop
3. `cargo run`

## Your environment 🌱

 - Version: 1.7
 - Platform:
   - [ x ] android (tablet)
   - [ x ] desktop (macOS)

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #2941 

# 👩🏻‍💻 What does this PR do? 
Revert all changes made to the 1.6 migration folder. Some changes just re-order the sql statements but the entry that caused a problem was adding a new column to the sync_log in the wrong migration folder.

Luckily this was a develop only problem (please double check this claim).

# Testing:
Check that there where no changes in the 1.6 migration folder on the 1.6 branch:
`git difftool -d --tool=kdiff3 v1.6.00:server/repository/src/migrations..v1.6.02:server/repository/src/migrations`

Check that there are no changes in the 1.6 migration folder between 1.6 and this branch:
`git difftool -d --tool=kdiff3 v1.6.02:server/repository/src/migrations..HEAD:server/repository/src/migrations`

### CODE REVIEW

**Comment by roxy-dao** [comment]
Just tested it... still seem to be getting the error James was getting

**Comment by Chris-Petty** [comment]
Gah unassigned, looks good but needs more looking - I've got meetings for the rest of the day.

**Comment by jmbrunskill** [comment]
> Just tested it... still seem to be getting the error James was getting

Same for me.

**Comment by clemens-msupply** [comment]
Works here:
1) removed my DB
2) checkout main
3) run it
4) checkout this branch
5) run it (1.7.0 migration is applied)

However, I never saw the "database disk image is malformed" but an error about a missing column so maybe its something different?

This PR is good to have anyway though...

**Comment by roxy-dao** [comment]
> Works here:
> 
> 1. removed my DB
> 2. checkout main
> 3. run it
> 4. checkout this branch
> 5. run it (1.7.0 migration is applied)
> 
> However, I never saw the "database disk image is malformed" but an error about a missing column so maybe its something different?
> 
> This PR is good to have anyway though...

I did the same but still getting:
``` 
0: Error during migration (1.7.0)
1: "UNKNOWN" ("\"\\\"database disk image is malformed\\\"\"")
```

Agree, PR is good to have but it doesn't close 2941. Happy to approve this change and remove the link in issue, so it doesn't close

**Comment by mark-prins** [comment]
I've tried with this branch, both for postgres and sqlite and the migrating has worked.
Not sure how to replicate now.. I'm using cargo 1.65.0 - assume that you both are using the later?

**Comment by roxy-dao** [comment]
> I've tried with this branch, both for postgres and sqlite and the migrating has worked. Not sure how to replicate now.. I'm using cargo 1.65.0 - assume that you both are using the later?

Upgrading from 1.6.02

**Comment by mark-prins** [comment]
oh! I used Clemens list of instructions - which is to start with a blank slate. will retry with 1.6.02
and my other question was about rust/cargo version, probably irrelevant now!

**Comment by mark-prins** [comment]
Ok, so it's this line in `v1_07_00/mod.rs` that breaks:

```
    changelog_repo.delete((cursor_before_job + 1).try_into()?)?;
```

@clemens-msupply do you want to take it from here?

**Comment by clemens-msupply** [comment]
At least I can also see the corruption in the changelog now. The migration order also looks wrong, will have a look...

**Comment by jmbrunskill** [comment]
I've pushed a fix, which is to create a new table instead of using drop column.

I'm pretty sure the triggers and indexes are safe but is there anything else that could be missed?
https://github.com/msupply-foundation/open-msupply/pull/2946/commits/719a05526a637eec31fb01625be3b16725e8537c

Tests pass for both `postgres` and `sqlite`.
I've change postgres to be more consistent by renaming the column rather than creating a new one. Is this ok?

**Review by jmbrunskill — APPROVED** [review]
I'm happy with the changes if you are @clemens-msupply

File: server/repository/src/migrations/v1_07_00/changelog_add_name_link_id.rs [hunk 1]
```diff
@@ -52,20 +53,33 @@ pub(crate) fn migrate(connection: &StorageConnection) -> anyhow::Result<()> {
...
         -- Adding changelog.name_link_id
         PRAGMA foreign_keys = OFF;
-        ALTER TABLE changelog
-        ADD COLUMN name_link_id TEXT REFERENCES name_link(id);
-        
-        UPDATE changelog
-        SET name_link_id = name_id;
+
+        CREATE TABLE tmp_changelog AS SELECT * FROM changelog;
+        DROP TABLE changelog;
```
Comment (roxy-dao) [inline server/repository/src/migrations/v1_07_00/changelog_add_name_link_id.rs:58]: Can't this just be a table rename? 🤔

**Review by roxy-dao — APPROVED** [review]

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Sorry didn't mean to approve... postgres tests are failing for me at:

```
        -- Triggers need to be disabled for these tables to avoid setting them off before
        -- their functions referring to the old changelog.name_id field is updated to changelog.name_link_id.
        -- They are enabled again in each tables' migration in for merging where the functions are updated.
        ALTER TABLE invoice DISABLE TRIGGER ALL;
        ALTER TABLE invoice_line DISABLE TRIGGER ALL;
        ALTER TABLE requisition DISABLE TRIGGER ALL;
        ALTER TABLE requisition_line DISABLE TRIGGER ALL;
        ALTER TABLE name_store_join DISABLE TRIGGER ALL;

    "UNKNOWN" ("\"\\\"constraint \\\\\\\"changelog_name_id_fkey\\\\\\\" of relation \\\\\\\"changelog\\\\\\\" does not exist\\\"\""), version: Version { major: 1, minor: 7, patch: 0, pre_release: None } }
```

Seems to have something to do with the triggers interacting with the renamed column..

**Comment by jmbrunskill** [comment]
> Sorry didn't mean to approve... postgres tests are failing for me at:
> 
> ```
>         -- Triggers need to be disabled for these tables to avoid setting them off before
>         -- their functions referring to the old changelog.name_id field is updated to changelog.name_link_id.
>         -- They are enabled again in each tables' migration in for merging where the functions are updated.
>         ALTER TABLE invoice DISABLE TRIGGER ALL;
>         ALTER TABLE invoice_line DISABLE TRIGGER ALL;
>         ALTER TABLE requisition DISABLE TRIGGER ALL;
>         ALTER TABLE requisition_line DISABLE TRIGGER ALL;
>         ALTER TABLE name_store_join DISABLE TRIGGER ALL;
> 
>     "UNKNOWN" ("\"\\\"constraint \\\\\\\"changelog_name_id_fkey\\\\\\\" of relation \\\\\\\"changelog\\\\\\\" does not exist\\\"\""), version: Version { major: 1, minor: 7, patch: 0, pre_release: None } }
> ```
Oops thought I'd run the postgres tests but clearly not with that line in there.

File: server/repository/src/migrations/v1_07_00/changelog_add_name_link_id.rs (hunk 1 above)
Comment (jmbrunskill) [reply server/repository/src/migrations/v1_07_00/changelog_add_name_link_id.rs:58]: If I rename it seems like the triggers get moved with the table, but that does make me worry that triggers might get screwed up here...

File: server/repository/src/migrations/v1_07_00/changelog_add_name_link_id.rs [hunk 2]
```diff
@@ -52,20 +53,33 @@ pub(crate) fn migrate(connection: &StorageConnection) -> anyhow::Result<()> {
...
+            -- Below fields are extracted from associated record where it's deemed necessary (see changelog/README.md)
+            name_link_id TEXT REFERENCES name_link(id), -- RENAMED from name_id
+            store_id TEXT,
+            is_sync_update BOOLEAN NOT NULL DEFAULT FALSE
+        );
+        INSERT INTO changelog SELECT * FROM tmp_changelog;
+        DROP TABLE tmp_changelog;
+
         PRAGMA foreign_keys = ON;
+        PRAGMA wal_checkpoint(TRUNCATE);
```
[the remark this answers is not in the document]
Comment (jmbrunskill) [reply server/repository/src/migrations/v1_07_00/changelog_add_name_link_id.rs:75]: Nah it's not needed. Have removed.
Does feel like an SQLite bug, the drop column feature is relatively new and we're not on the latest sqlite possibly lots of fixed bugs since our version?

Definitely could be some other errors though...

**Comment by clemens-msupply** [comment]
This sqlite issue looks like it could be it:
https://sqlite.org/forum/forumpost/96896f825d

We are using SQLite 3.35.4 (according to https://crates.io/crates/libsqlite3-sys/0.22.2) and the bug was fixed in 3.36.0.

So another reason to do: https://github.com/msupply-foundation/open-msupply/issues/2881

**Review by roxy-dao — APPROVED** [review]
gif


Works now and tests passing 👍🏻 Thanks Clemens and James!

**Comment by clemens-msupply** [comment]
Thanks James for fix!

**Comment by Chris-Petty** [comment]
Thanks James and thanks everyone for throwing weight into this one! Not everyday you find a bug in with the underlying database (probably). 

A bit unfortunate, we were generally avoiding dropping tables and remaking them as it could take a while, and changelog is the most busy table of them all!

**Comment by jmbrunskill** [comment]
> Thanks James and thanks everyone for throwing weight into this one! Not everyday you find a bug in with the underlying database (probably).
> 
> A bit unfortunate, we were generally avoiding dropping tables and remaking them as it could take a while, and changelog is the most busy table of them all!

Luckily the Postgres version doesn't need this work around, and hopefully we don't have any massive db's that will need to go through this migration.

As part of https://github.com/msupply-foundation/open-msupply/issues/2881 we could re-consider this if you want?
The issue is fixed in newer SQLite versions.

**Comment by Chris-Petty** [comment]
Yea as you say for sqlite DBs at this stage it'll probably be all good. Maybe some of the cold chain ones though I'm not 100% sure there are many sites using OMS cold chain monitoring yet?

**Comment by roxy-dao** [comment]
> Yea as you say for sqlite DBs at this stage it'll probably be all good. Maybe some of the cold chain ones though I'm not 100% sure there are many sites using OMS cold chain monitoring yet?

Yes. OMS cold chain is being used
