### PR TITLE
prevent delete on inbound transferred shipment

### LINKED ISSUE #5120: Don't allow deleting inbound shipment lines for transfers
## What went wrong? 😲

Screenshot -> [here](https://drive.google.com/drive/folders/1BN7odKHMWxWhVex7WsnvikyREu2xC445)

Database uploaded [here](https://mega.nz/fm/NY5BWSjS)

## Expected behaviour 🤔

Error should be user-friendly :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an Outbount Shipment from another store, mark it as Shipped so it will appear as Inbound Shipment in the testing store
2. Confirm the item as Delivered
3. Select the item -> click on Actions -> try to remove it from the shipment

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC8
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (apk)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #5120

# 👩🏻‍💻 What does this PR do?

Disable deletion of lines transferred from another store (inbound shipment)
This prevents the user from being able to delete items shipped from another mSupply user

This is done in three parts:

- [ ] Check and error in server side repository layer - stops the deletion
- [ ] Check and error in front end - provides error message to user
- [ ] Disable the 'Delete' action when lines are selected in a transferred shipment - prevents this action being taken by the user

If in any case the button is not disabled but the item is on a linked invoice, this is the error that will display to the user
Screenshot 2025-01-07 at 10 16 34 AM

## 💌 Any notes for the reviewer?

Along the way I tidied up duplicated delete function in the api as this was unused

Created new mock data for a an inbound shipment with a linked invoice

# 🧪 Testing

- [ ] Create an Outbound Shipment from a store to another of your stores, mark it as Shipped so it will appear as Inbound Shipment in the testing store
- [ ] Go to the store that the shipment was made to -> Inbound Shipments
- [ ] Confirm the shipment as Delivered
- [ ] Select an item -> click on Actions -> `Delete` should be disabled

If in code, comment out line 7 in this file to re-enable the delete button, to see the error message and that the item does not get deleted
client/packages/invoices/src/InboundShipment/api/hooks/utils/useIsInboundDisabled.ts

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/repository/src/mock/invoice.rs [hunk 1]
```diff
@@ -368,6 +368,27 @@ pub fn mock_unique_number_inbound_shipment() -> InvoiceRow {
     })
 }
 
+pub fn mock_inbound_shipment_linked_transfer() -> InvoiceRow {
```
Comment (lache-melvin) [inline server/repository/src/mock/invoice.rs:371]: Not a biggie, but something like `mock_transferred_inbound_shipment_a` might match existing naming conventions better?

File: server/repository/src/mock/invoice_line.rs [hunk 2]
```diff
@@ -592,13 +650,16 @@ pub fn mock_inbound_shipment_invoice_lines() -> Vec<InvoiceLineRow> {
...
+        .extend(mock_inbound_shipment_linked_transfer_invoice_lines());
+    mock_inbound_shipment_invoice_lines
 }
 
 pub fn mock_invoice_lines() -> Vec<InvoiceLineRow> {
     let mut mock_invoice_lines: Vec<InvoiceLineRow> = Vec::new();
 
     mock_invoice_lines.extend(mock_outbound_shipment_invoice_lines());
     mock_invoice_lines.extend(mock_inbound_shipment_invoice_lines());
+    mock_invoice_lines.extend(mock_inbound_shipment_linked_transfer_invoice_lines());
```
Comment (lache-melvin) [inline server/repository/src/mock/invoice_line.rs:662]: would remove this one again 😉

File: server/service/src/invoice/validate.rs [hunk 3]
```diff
@@ -10,6 +10,13 @@ pub fn check_invoice_type(invoice: &InvoiceRow, r#type: InvoiceType) -> bool {
     false
 }
 
+pub fn check_invoice_is_linked(invoice: &InvoiceRow) -> bool {
+    if invoice.linked_invoice_id.is_none() {
+        return true;
+    }
+    false
```
Comment (lache-melvin) [inline server/service/src/invoice/validate.rs:17]: `is_none` is already returning a boolean 🤷‍♀️ 
```suggestion
    invoice.linked_invoice_id.is_none()
```

Though actually! This function should be called `check_invoice_is_not_linked`!

File: server/service/src/invoice_line/stock_in_line/delete/mod.rs [hunk 4]
```diff
@@ -184,6 +185,18 @@ mod test {
             Err(ServiceError::BatchIsReserved)
         );
 
+        // // TransferredShipment
+        assert_eq!(
+            delete_stock_in_line(
+                &context,
+                DeleteStockInLine {
+                    id: mock_inbound_shipment_linked_transfer_line_b().id, //'id' doesn't exist -not an object?
```
Comment (lache-melvin) [inline server/service/src/invoice_line/stock_in_line/delete/mod.rs:193]: Is this comment still relevant?

File: server/service/src/invoice_line/stock_in_line/delete/validate.rs [hunk 5]
```diff
@@ -40,6 +43,9 @@ pub fn validate(
     if !check_line_not_associated_with_stocktake(connection, &line.id, store_id.to_string()) {
         return Err(LineUsedInStocktake);
     }
+    if !check_invoice_is_linked(&invoice) {
```
Comment (lache-melvin) [inline server/service/src/invoice_line/stock_in_line/delete/validate.rs:46]: Yeah per above, should read either `!check_not_linked`, or `check_linked` 🙏

File: client/packages/invoices/src/InboundShipment/api/hooks/utils/useIsInboundDisabled.ts [hunk 6]
```diff
@@ -4,5 +4,6 @@ import { isInboundDisabled } from './../../../../utils';
 export const useIsInboundDisabled = (): boolean => {
   const { data } = useInbound();
   if (!data) return true;
+  if (data.linkedShipment) return true;
```
Comment (lache-melvin) [inline client/packages/invoices/src/InboundShipment/api/hooks/utils/useIsInboundDisabled.ts:7]: Hm the one thing this raises for me is that this also disables the `reduce lines to 0` button... I'm checking with Mark whether that's actually a good thing?

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Looking great Aimee! Just a couple of clean ups 🙏

File: client/packages/invoices/src/InboundShipment/api/hooks/utils/useIsInboundDisabled.ts (hunk 6 above)
Comment (lache-melvin) [reply client/packages/invoices/src/InboundShipment/api/hooks/utils/useIsInboundDisabled.ts:7]: Confirmed with Mark - preference is to still be able to reduce lines to 0. So we should move this check to only the delete button, rather than in this hook!

Should make sure Noel's ActionFooter changes are merged, and then do the change there I think!

File: server/repository/src/mock/invoice.rs (hunk 1 above)
Comment (aimee-mcneil-melville) [reply server/repository/src/mock/invoice.rs:371]: Great, I have updated these

File: server/service/src/invoice_line/stock_in_line/delete/mod.rs (hunk 4 above)
Comment (aimee-mcneil-melville) [reply server/service/src/invoice_line/stock_in_line/delete/mod.rs:193]: No not needed anymore, thank you

File: server/repository/src/mock/invoice_line.rs (hunk 2 above)
Comment (aimee-mcneil-melville) [reply server/repository/src/mock/invoice_line.rs:662]: Oops, done!

File: server/service/src/invoice/validate.rs (hunk 3 above)
Comment (aimee-mcneil-melville) [reply server/service/src/invoice/validate.rs:17]: Have updated this!

File: client/packages/invoices/src/InboundShipment/api/hooks/utils/useIsInboundDisabled.ts (hunk 6 above)
Comment (aimee-mcneil-melville) [reply client/packages/invoices/src/InboundShipment/api/hooks/utils/useIsInboundDisabled.ts:7]: Cool I've done this now!

**Review by lache-melvin — APPROVED** [review]
Great thanks for changes Aimee!
