### PR TITLE
#9612 #9609 #9610 Fix dose skipping behaviour

### LINKED ISSUE #9610: Button mismatch when administering vaccines
## What went wrong? 😲

Seeing this: 

Image

Image

Looks like buttons are intended for the whole encounter

## Expected behaviour 🤔

Matching buttons (for example, Ok and Cancel) - but not encounter-related

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure you have vaccination/immunization programs setup in your store
2. Have a patient enrolled into a program and have a few vaccination courses setup for the program
3. Make sure at least one has the preference to skip doses ON
4. Go to the patient -> administer a dose with skipping a few (e.g. dose 3 but the first 2 are not given)
5. Note the prompts - buttons not making sense :)

## Your environment 🌱

- Open mSupply Version: `V2.12.00-develop-10231639`
- Legacy mSupply Central Server Version: `V8.05.08`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### LINKED ISSUE #9612: User still can edit previous doses even when skipping them
## What went wrong? 😲

When administering a dose and skipping some along the way, the user will get a prompt they are not able to edit the previous doses - e.g. they should become uneditable

Image

Yet, I am still able to go back to skipped doses and edit the details

https://github.com/user-attachments/assets/241bd458-fbce-4b15-a0f6-cdd2cee07b8b

## Expected behaviour 🤔

Either 1. the prompt is outdated and it is expected behaviour to be able to edit skipped doses or 2. the prompt is correct and the behaviour does not match it

Either way, should be fixed according to what the expected behaviour is!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure you have vaccines/immunization program set up in your store
2. Have a patient enrolled into a program and some vaccine courses for that program
3. Make sure you are testing the course with the preference to skip doses ON
4. Go to the encounter -> administer a dose while skipping some (for example, dose 3 out of 4 so 1 and 2 are skipped)
5. Note the prompt - previous doses should become uneditable
6. Save the changes -> go to Dose 2 or Dose 1 -> make some changes
7. You are able to do so

## Your environment 🌱

- Open mSupply Version: `V2.12.00-develop-10231639`
- Legacy mSupply Central Server Version: `V8.05.08`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #9612 #9609 #9610

# 👩🏻‍💻 What does this PR do?

The specifics of issues #9609 and #9612 are somewhat inconsistent, so I've established what the "rules" should be here (after discussing with @mark-prins) and made sure they are implemented and enforced here.

The rules are:
- For ALL vaccination course schedules:
  - Once a dose has been *entered* (either Given or Not Given), you can no longer edit the details of previous doses. You can open them up to see the details, but the controls are all disabled.
- For vaccination course schedules that are NOT skippable:
  - You can't click on (open) any doses beyond the one that is next to be administered (the first one with no current status)
- For vaccination course schedules that ARE skippable:
  - You can click on _any_ row, including ones beyond the current
  - If clicking on a row that skips a dose, you will only have the option to "Give" (otherwise you wouldn't actually be "skipping" anything), and you'll see a warning box in the modal that you'll be skipping doses (as well as the confirmation dialog on submission)

### Screenshots

The modal for doses that are no longer editable (i.e. later ones have been entered):
Screenshot 2025-10-30 at 1 31 55 PM

The modal when skipping a dose. Note only a single option is available, and the additional warning (warning only appears after selecting the Radio button option):
Screenshot 2025-10-30 at 1 31 41 PM

I've also fixed #9610, which was caused by context state persistence of the button labels.

## 💌 Any notes for the reviewer?

See inline comments

# 🧪 Testing

- [ ] Have multiple vaccination courses, with a mixture of skippable and non-skippable
- [ ] Try various operations (administering, not-administering, skipping) and confirm that the rules as described above are enforced

To test #9610, the problem only happens when something else has modified the button labels prior to coming to this page. Here are the steps to reproduce:
- Go to an Encounter (non Vaccination) that is still in the "Pending" state (not "Visited)
- Change something, and save (non-visited)
- Attempt to go to another page, you should get a modal saying "This encounter is still marked as pending. If you are finished, mark it as visited." Click "Leave as pending"
- Now go to a vaccination Encounter, and attempt to skip a dose. When the warning comes up, the buttons should show the standard "Okay" and "Cancel" labels -- before this fix they would continue to show the previous labels, as per the issue description

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Vaccination/utils.ts [hunk 1]
```diff
@@ -5,18 +5,35 @@
 import { VaccinationDraft } from './api';
 import { VaccinationCardItemFragment } from './api/operations.generated';
 
-export const isPreviousDoseGiven = (
+export const getPreviousDoseStatus = (
```
Comment (CarlosNZ) [inline client/packages/system/src/Vaccination/utils.ts]: Needed to check what the previous status actually is to determine how the modal should display. Can use this value to also do the same thing `isPreviousGiven` does, so have removed that function.

File: client/packages/system/src/Vaccination/utils.ts [hunk 2]
```diff
@@ -5,18 +5,35 @@
...
-  if (!items) return false;
+  if (!items) return undefined;
   const itemsForCourse = items.filter(
     item => item.vaccineCourseId === vaccineCourseId
   );
   const doseIndex = itemsForCourse.findIndex(dose => dose.id === row.id);
-  if (doseIndex === 0) return true;
-  return itemsForCourse[doseIndex - 1]?.given;
+  if (doseIndex === 0) return undefined;
+  return itemsForCourse[doseIndex - 1]?.status;
```
Comment (CarlosNZ) [inline client/packages/system/src/Vaccination/utils.ts]: If it returns `undefined`, it means there is no previous dose (i.e. it's the first). If it returns `null`, it means the previous dose hasn't been entered at all (neither Given nor Not Given), which means the current dose will be skipping a dose.

Comment (jmbrunskill) [reply client/packages/system/src/Vaccination/utils.ts]: Lets add this to the code as a comment, I'd prefer to have specific status returned I wonder how hard that would be...

**Comment by jmbrunskill** [comment]
Just one error currently with Marking A Dose as not given in a non-skippable v-course, trying to administer the next dose gives an error, not clear what `clickable` means in the description.

image

Waiting to confirm with @mark-prins

**Comment by jmbrunskill** [comment]
> * You can't click on (open) any doses beyond the one that is next to be administered (the first one with no current status)

Confirmed with Mark, when skip doses is turned on, you don't have to fill in the previous dose to say `Not Given` it will be applied automatically.
Otherwise, you need to manually set it to `NotGiven` then you can edit the next dose.
So `skipping` is really just a short cut for extra manual Not Given entries.

**Review by jmbrunskill — APPROVED** [review]
THanks Carl, I did a quick update for the backend logic...
