### PR TITLE
5987 fix tests

### LINKED ISSUE #5987: Fix tests
## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #5987

# 👩🏻‍💻 What does this PR do?
Don't compare `None` elmis code

# 🧪 Testing

- [ ] Tests pass

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/service/src/requisition/program_settings/customer_program_settings/map.rs [hunk 1]
```diff
@@ -19,7 +19,18 @@ pub(super) fn map_customer_program_settings(
...
+                            .elmis_code
+                            .as_ref()
+                            .map_or(false, |elmis_code| {
+                                elmis_code
+                                    == program_setting
+                                        .program_row
+                                        .elmis_code
+                                        .as_ref()
+                                        .unwrap_or(&"".to_string())
+                            })
```
Comment (jmbrunskill) [inline server/service/src/requisition/program_settings/customer_program_settings/map.rs:33]:
```suggestion
                        || (customer.program.elmis_code == program_setting.program_row.elmis_code && !customer.program.elmis_code.is_none())
```

Comment (jmbrunskill) [reply server/service/src/requisition/program_settings/customer_program_settings/map.rs:33]: Can't we just do this?

Was trying to get my head around the filter change as if wasn't entirely clear to me what it was doing.
This seems much clearer and simpler?
Maybe I'm missing something but tests are passing now...

If we need the more complicated filter that's fine but would be nice to have a comment explaining it as it's not immediately obvious, at least to me :)

**Review by jmbrunskill — APPROVED** [review]
Tests pass which is good.
I don't have enough context to fully understand what un-intended consequences there might be but feels safe enough.

I've made a suggestion to simplify the filter, hopefully that's correct and you agree it's simpler. Otherwise would like a comment and/or a function call to wrap the functionality with a useful name to explain the intention of the filter.

File: server/service/src/requisition/program_settings/customer_program_settings/map.rs (hunk 1 above)
Comment (roxy-dao) [reply server/service/src/requisition/program_settings/customer_program_settings/map.rs:33]: That also looks fine to me! Will test in a bit

Sometimes stores might have different programs that are essentially the same (this is very CIV specific), CIV uses elmis code to match master lists
