### PR TITLE
8007 can't select vvm status when adding new stock line

### LINKED ISSUE #8007: Can't select VVM status when adding new stock line
## What went wrong? 😲
Wasn't part of the specs, but thought nice to have. Reuse the component available. This should default to largest usable level
Image

## Expected behaviour 🤔
I should be able to add a vvm status to a new stock line and a log should be created for the status.

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #8007

# 👩🏻‍💻 What does this PR do?
- Allows user to input VVM status when introducing new stock in Inventory Adjustment. 
- This defaults to the 'best' status
- Read only component in the stock edit page

# 🧪 Testing

- [ ] Have manage VVM status OMS store preference on
- [ ] Stock > Add stock (select a vaccine item)
- [ ] Should see VVM status component and be able to interact with it
   - [ ] If unchanged, should save the default -> make sure vvm status log has been created
   - [ ] If changed, should save whatever the vvm status is -> make sure vvm status log has been created
- [ ] VVM status log should be READ ONLY in the stock page

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusInputCell.tsx [hunk 1]
```diff
@@ -20,20 +17,12 @@ export const VVMStatusInputCell = <T extends RecordWithId>({
     column.setter({ ...rowData, vvmStatus });
   };
 
-  if (useDefault && defaultVal && !selected) {
```
Comment (roxy-dao) [inline client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusInputCell.tsx:23]: Moved to search input to have it save default for other areas as well

**Review by Chris-Petty — CHANGES_REQUESTED** [review]
image

image

Forgive me I know VVMs are special wee things... is 2 truly the best status? I would assume 1 is haha. My reading of docs is that that `1` would be best https://docs.msupply.org.nz/cold_chain_equipment:configure#priority_of_vvm_status

It's a shame the vvm status can't be edited when adjusting an existing line, only when introducing stock?

**Comment by roxy-dao** [comment]
> It's a shame the vvm status can't be edited when adjusting an existing line, only when introducing stock?

Level = the distribution priority, so Level 1 is always the priority, by its nature.
But that means Level 1 = VVM Stage 2 (not VVM Stage 1)

**Comment by Chris-Petty** [comment]
> 
> Level = the distribution priority, so Level 1 is always the priority, by its nature. But that means Level 1 = VVM Stage 2 (not VVM Stage 1)
> 
> So when you're entering store... shouldn't it be at the best status (Status = 1, but Level = 2). 1 should be prioritised to go out.

Hmm by my reading of the docs the "level" field should really be called "priority" as that's what it is, and "level" gets jumbled with VVM jargon. Maybe check with @adamdewey? Either the docs should change or "level" 1 in OG settings should be the higher priority (though you may/should want stage 2 to be level 1 in priority)

**Comment by roxy-dao** [comment]
> > Level = the distribution priority, so Level 1 is always the priority, by its nature. But that means Level 1 = VVM Stage 2 (not VVM Stage 1)
> > So when you're entering store... shouldn't it be at the best status (Status = 1, but Level = 2). 1 should be prioritised to go out.
> 
> Hmm by my reading of the docs the "level" field should really be called "priority" as that's what it is, and "level" gets jumbled with VVM jargon. Maybe check with @adamdewey? Either the docs should change or "level" 1 in OG settings should be the higher priority (though you may/should want stage 2 to be level 1 in priority)

Have checked. I've been through this many times Chris. Yes, should be called priority instead. Level / Status gets very confusing!

**Comment by Chris-Petty** [comment]
image

image

IDK if that helps haha. That said, the "level" setting is described specifically for _issuing stock_ not adding/receiving stock

**Comment by roxy-dao** [comment]
> IDK if that helps haha. That said, the "level" setting is described specifically for _issuing stock_ not adding/receiving stock

Sure, but the user can still change the VVM status if it is wrong...

**Review by Chris-Petty — APPROVED** [review]
Looks good even if I am eternally confused by what we are doing with "level"

Image

Why do we even show level in the status history - it's just a priority field for issuing stock, not the vvm status/level 🤪
