### PR TITLE
Translate labels

### LINKED ISSUE #6496: No translation for indicator field labels
## What went wrong? 😲

Image

Regimen data labels for `comment` and `value` are not being localised, showing the resource identifier instead.

## Expected behaviour 🤔

Localised for English and ideally other languages too!

## How to Reproduce 🔨

1. View indicators

## Your environment 🌱

- Open mSupply Version: 2.5.1 android

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #6496

# 👩🏻‍💻 What does this PR do?
The labels were being provided with a string that is supposed to be a translation key, but isn't.

I've changed the utility method to return a LocaleKey rather than a string, as that can be used as a string when required. It does remove the fallback, but we only have comment and value so I think it's ok.

image

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create a program based internal order and check that the labels are correct in the indicators tab

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx [hunk 1]
```diff
@@ -95,7 +95,7 @@ const InputWithLabel = ({
     <InputWithLabelRow
       Input={inputComponent}
       labelWidth={LABEL_WIDTH}
-      label={indicatorColumnNameToLocal(data.name)}
+      label={t(indicatorColumnNameToLocaleKey(data.name))}
```
Comment (andreievg) [inline client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx:98]: This looks like the one change that would fix the issue

Comment (andreievg) [reply client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx:98]: Actually `It does remove the fallback, but we only have comment and value so I think it's ok.`, we should pass `t` to `indicatorColumnNameToLocaleKey` and then use it there, so we can keep fallback

File: client/packages/requisitions/src/utils.ts [hunk 2]
```diff
@@ -155,13 +155,13 @@ enum IndicatorColumnName {
...
+  columnName: string
+): LocaleKey => {
   switch (columnName) {
     case IndicatorColumnName.Comment:
       return 'label.comment';
-    case IndicatorColumnName.Value:
-      return 'label.value';
     default:
-      return columnName;
+      return 'label.value';
```
[the remark this answers is not in the document]
Comment (mark-prins) [reply client/packages/requisitions/src/utils.ts:165]: The HIV use their own labels rather than 'label'/'value':
image

File: client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx]: I've changed to pass around the TypedTFunction

**Review by andreievg — APPROVED** [review]
Thanks Mark
