### PR TITLE
#11214 Aggregate customer indicators across elmis_code-linked programs

### LINKED ISSUE #11214: The district Customers Indicators values doesn't aggregate when it does its own Internal order to the NPSP
## What went wrong? 😲

The district customers indicators syncs correctly to the district but when the district does it is own Internal order, the Customers indicators are not included and the indicators values shows -0 and the aggregation box at the bottom of the list doesn't the value of each customer indicator

For example:
This is the indicators on one of the customers internal order
https://drive.google.com/file/d/1eY5hoSbMG62YAhQuVoavaU1airMDw5HG/view?usp=sharing

This is the indicators from the requisitions created on the district for that customer
https://drive.google.com/file/d/1eLL4Uylf3Rp4qGKSNnLw8CzASU-yAqQa/view?usp=sharing

This what I have when I create the district internal order (The name of the customer store is shown in the aggregation detail box which means that it has been configured correctly in OG as the Dsitrict of San Pedro is his configured as its default supplier 
https://drive.google.com/file/d/1hUxwIqXJKdDUYut5GUd6-V82kwT9qFq7/view?usp=sharing

None of the customer indicators for that program seems to be integrated in the District Internal order and also I have the infamous -0 value that shows.

## Expected behaviour 🤔
When created a program Internal order for a district, customer Indicators for requisitions finalised of the program and the period targeted in the internal order should be aggregated in the internal order.
 
## How to Reproduce 🔨

Steps to reproduce the behaviour:
on a customer store
1. Create an internal order with the district store which is his default supplier and populate the indicators and click on the Send button and sync
2. Go the district store, Sync and go to the requisition automatically created from the customer internal order and check that the indicators have the same values as the internal order  
3. Fulfill the requisition and finalise it.
4. Still in the district store. create a new Internal order for the same program and period
5. Go the indicators tab
6. See error. Instead of aggregated values from the finalised customer requisitions, you only see -0 and the aggregated detail box is empty except for the period date  

## Additional Info
Found while doing pre-UAT testing which makes it a hotfix

## Your environment 🌱

- Open mSupply Version: v2.17.0
- Legacy mSupply Central Server Version: v8.17

- Platform: Browser or desktop

- Database type: Postgres

### LINKED ISSUE #11226: The indicators aggregation detail box is showing for stores which is the default supplier of patients only
## What went wrong? 😲

Normally, the indicators aggregation detail box should only show for district sanitaire ie stores which are the default supplier of other stores. But we can see them for health center (ESPC). I think it is because, they are the default supplier of patients. Maybe, we should show the indicators box only if the store is the default supplier of at least one other store. We should hide it if it is the default supplier of only patients.

For example:

The store below is displaying the indicator aggregation detail box

https://drive.google.com/file/d/1br3lavPGMHoDne_C46WcTouXGRytf1Kt/view?usp=sharing

even though, it is a store which is the default supplier of only patients

The number of names which our store is the default supplier to
https://drive.google.com/file/d/1zWY6GDWj3wzh3tIeH2vm19hI7UmiQPy_/view?usp=sharing

the number of names from the above results that are patients
https://drive.google.com/file/d/1kdzLuCBfR6i1zVCT7tT_MhZmCfzuKIBc/view?usp=sharing

The default supplier store for patients is to identify the home dispensary of a patient

## Expected behaviour 🤔
The indicator aggregation box should be hidden for stores that are the default supplying store of only patient 

## How to Reproduce 🔨

Steps to reproduce the behaviour:
On Ivory Coast demo server, Choose a store that is an ESPC like the one above
1. Go to 'Replenishment > Internal order'
2. Click on 'New Internal order' and create a program internal order
3. Click on the indicator tab
4. See error. The aggregation detail box is not hidden 

## Additional Info
Found on pre-UAT testing 

## Your environment 🌱

- Open mSupply Version: 2.17.0
- Legacy mSupply Central Server Version: v8.17

- Platform: Desktop and Browser

- Database type: Postgres

### PR DESCRIPTION
**Pull request by ria8651**
Fixes #11214

# 👩🏻‍💻 What does this PR do?

When a district store creates a program internal order, the indicators tab aggregates values from finalised customer requisitions for the same period. The aggregation was scoped to the current program only, so deployments that split a single logical program across multiple `program` rows per facility level (e.g. CIV's `CS` vs `DISTRICT` variants sharing an `elmis_code`) saw `-0` in the main values and an empty per-customer breakdown.

Changes:
- New `related_program_indicator_ids` / `related_indicator_schema` helpers in `requisition/common.rs` expand starting `program_indicator_ids` to include all indicators from programs sharing the same `elmis_code`. Falls back to the input IDs when no `elmis_code` is set.
- `generate_program_indicator_values` (on request requisition creation) and `get_indicator_information` (per-customer breakdown query) now match customer indicator values by line `code` and column `(header, column_number)` across related programs, not by raw IDs. This mirrors Legacy mSupply's `elmisCode`-based lookup in `indicatorSetValuesFromReponse.4dm`.
- `get_indicator_information` remaps customer column IDs onto the requested (district) column IDs so the frontend `CustomerIndicatorInfo` table — which joins values by `columnId` — renders them under the correct columns.
- Aggregation query gains a `store_id` filter to stop double-counting customer rows + the district's transferred copies when both exist in the same DB.
- Frontend: `IndicatorLineEdit` now checks `customerIndicatorInfo?.length` instead of truthy, so the breakdown box hides when there are no customers with store-type accounts (covers #11226).
- Tangentially, `IndicatorValueLoader` was rewritten to group inputs by `(period, store, customer)` so batched GraphQL requests with different filter combinations no longer silently drop all but the first.

## 💌 Any notes for the reviewer?

- The `elmis_code` approach matches how Legacy does cross-level aggregation; see `Project/Sources/Methods/indicatorSetValuesFromReponse.4dm` in the legacy repo.
- `indicator_information.rs` builds `requested_column_key_to_id` from only the requesting program's columns (filtered by `own_pi_id_set`) to ensure the remap targets the district-side column IDs, not any other program's.
- New tests in `requisition/common.rs` cover the three behaviours of `related_program_indicator_ids` (empty input, elmis_code expansion, no-elmis_code fallback) and the `related_indicator_schema` mapping output.
- Also closes the frontend side of #11226 (empty aggregation box visible on stores with no store-type customers), which the issue author has also confirmed is a related symptom of the same CIV setup.

# 🧪 Testing

- [ ] Two customer stores (e.g. CIV CS-level) sharing a district supplier, plus the district creating its own internal order to a central supplier
- [ ] Customer programs use a different `program_id` from the district program but share the same `elmis_code`
- [ ] Both prefs enabled on the district store: `useConsumptionAndStockFromCustomersForInternalOrders`, `extraFieldsInRequisition`
- [ ] Create request requisitions from two customer stores with indicator values, send and finalise at the district
- [ ] Create a new district internal order for the same period → main indicator values should be the sum of the two customers' values, per-customer breakdown box should show each customer with their individual values under the correct columns
- [ ] Repeat on a deployment with a single program (no `elmis_code` split) to confirm fallback path still aggregates correctly

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**:
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/graphql/core/src/loader/program_indicator_value.rs [hunk 1]
```diff
@@ -48,44 +48,43 @@ impl Loader<IndicatorValueLoaderInput> for IndicatorValueLoader {
...
 
-        let filter = IndicatorValueFilter::new()
-            .store_id(EqualFilter::equal_to(store_id.to_string()))
-            .customer_name_id(EqualFilter::equal_to(customer_name_id.to_string()))
-            .period_id(EqualFilter::equal_to(period_id.to_string()));
+        let mut result = HashMap::new();
 
-        let values =
-            IndicatorValueRepository::new(&service_context.connection).query_by_filter(filter)?;
+        for (period_id, store_id, customer_name_id) in &groups {
```
Comment (jmbrunskill) [inline server/graphql/core/src/loader/program_indicator_value.rs:66]: Nice thanks for fix this!

**Review by jmbrunskill — APPROVED** [review]
Looks great, thanks for figuring this one out not easy!

Claude found 2 `should fixes` and I've pushed something to branch if you want to consider it.

🟡 Should fix
Mixed inputs drop elmis-less PIs silently — [common.rs:168-198](vscode-webview://1u031oloet9kb4iv2peptecpvus5se97l1qro1bj2knt0tjc3p0q/server/service/src/requisition/common.rs#L168-L198). If program_indicator_ids contains PIs from both an elmis-coded program and a non-coded program, the function returns only the elmis-related PIs — the non-coded ones are lost. Both current callers pass PIs from a single program, so this isn't reachable today, but the contract isn't defended. Either document the single-program precondition in the doc-comment, or union non-coded input IDs into related_pi_ids before returning. A targeted test would help.

requested_column_key_to_id silently collapses duplicates — [indicator_information.rs:82-87](vscode-webview://1u031oloet9kb4iv2peptecpvus5se97l1qro1bj2knt0tjc3p0q/server/service/src/requisition/request_requisition/indicator_information.rs#L82-L87). If two district columns happen to share the same (header, column_number) (e.g. a duplicated column row or a legacy data case), one gets dropped by the HashMap insert. Remapped customer values would all land on the surviving column. Worth adding a short comment noting the assumption that (header, column_number) is unique within a program, and/or logging when a collision occurs.

https://github.com/msupply-foundation/open-msupply/compare/11214-aggregate-customer-indicators-across-elmis-code...11214-review-fixes

I'm ok merging as it is though these are just defensive things I think. Maybe we'll rethink when we do the next indicators project :)

**Comment by ria8651** [comment]
Haha I got exactly the same two things in my review and decided to leave them.
