### PR TITLE
3981 fix $NaN currency display for outbound shipment placeholder lines

### LINKED ISSUE #3981: Unit price is `-$NaN.00` when you create outbound shipments by masterlist
## What went wrong? 😲

Unit price is `-$NaN.00` when you create outbound shipments by masterlist

Screenshot 2024-05-22 at 16 46 23

## Expected behaviour 🤔

There should be numeric value like `0.00`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Outbound Shipments
2. Create new outbound shipments 
3. Add items form the masterlist 
4. After the items are added see the Unit Price Column
5. The label `-$NaN.00` is seen(BUG)

## Your environment 🌱

- Open mSupply Version: v2-0-01
- Legacy mSupply Central Server Version: v7-15-dev12

- Platform: Server 

- Database type: Sqlite

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #3981

# 👩🏻‍💻 What does this PR do?

Similar to #3975 (fixes $NaN in currency inputs) this fixes currency display cell:

Screenshot 2024-05-23 at 10 33 58 AM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create outbound shipment
- [ ] Add lines from master list (so placeholder lines created)
- [ ] TEST: Unit price shows $0.00

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ export const CurrencyCell = <T extends RecordWithId>({
   CellProps<T>
 > => {
   const { c } = useCurrency(currencyCode);
-  const price = Number(column.accessor({ rowData })) ?? 0;
+  const price = Number(column.accessor({ rowData }) ?? 0);
```
Comment (CarlosNZ) [inline client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx:30]: Ooooh, I was like "Didn't I just do this yesterday?", but I see it's the CurrencyCell, not the CurrencyInput. 🙄

Thanks 🙏

**Review by CarlosNZ — APPROVED** [review]
Sweet -- thank you :)
