### PR TITLE
7868 add running balance total for ledger queries

### LINKED ISSUE #7868: Item ledger calculations not adding correctly
## What went wrong? 😲

Image

8000 - 1000 does not equal -3800...

## Expected behaviour 🤔

Calculate correctly

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #7868 

# 👩🏻‍💻 What does this PR do?

Refactors item_ledger to prevent double counting of ledger items in cases where they occur at the same datetime.
Preserve multiple id query logic without mapping to keep functionality for reports which use this query
Add tests to ensure logic is stable

## 💌 Any notes for the reviewer?

Note that the ledger balance is always calculated based on dateTime, which leads to strange displaying results if we sort by datetime in the front end in a reverse order from how we calculate the balance.

You can see this when you change the datetime order from ascending to descending in the item ledger tab of items.
Some ways the ledgers are out of order.

Unsure quite how to handle this, but I am thinking this is still better than the alternative of prematurely summing of total values.

# 🧪 Testing

- [ ] Navigate to Items and then ledger tab 
- [ ] See that balance is calculated for each line where more than one line exists for the same datetime.
- [ ] Also should double check the stockouts report [here](https://github.com/msupply-foundation/open-msupply-reports/blob/8b5414fc9ee03de983f1f20da1812b90723c059f/clients/Ivory-Coast/stockouts/latest/src/query.graphql#L2) is still working without regression

# 📃 Documentation

- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/ledger.rs [hunk 1]
```diff
@@ -43,7 +50,6 @@ pub fn get_item_ledger(
         .unwrap_or_default()
         .store_id(EqualFilter::equal_to(store_id));
 
-    let rows = repository.query(pagination, Some(filter.clone()), sort)?;
     let all_ledger_items = repository.query(
```
Comment (fergie-nz) [inline server/service/src/ledger.rs:53]: I am slightly worried about the consistency of this query. 

Will it always return ledgerRows in the same order if datetime is equal?
Does it depend upon the database?

Would be confusing for users if we calculate in one order for sqlite, and differently for postgres for example.
Would it change order for the same query randomly?

Won't make a difference in terms of final calculation, but different order of operations would look weird for users.

I almost want to add the cursor to the ledgerRow so that we can define what happens first / next, even if arbitrarily, so that it tells a consistent story to users.
