### PR TITLE
9979 add database connection configuration

### LINKED ISSUE #9979: Server crash with too many database connections
## What went wrong? 😲

With too many users accessing an oms instance at once it is possible to run out of database connections and crash the server.

<details>

<summary>Stack Trace</summary>

```
2025-12-08 17:06:51.121162000 [ERROR] <log_panics:130>:thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DBError { msg: "Failed to open Connection", extra: "Error(None)" }': service/src/sync/mod.rs:150
   0: backtrace::backtrace::libunwind::trace
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.74/src/backtrace/libunwind.rs:116:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.74/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.74/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.74/src/capture.rs:292:9
   3: backtrace::capture::Backtrace::new
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.74/src/capture.rs:257:22
   4: <backtrace::capture::Backtrace as core::default::Default>::default
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.74/src/capture.rs:517:9
   5: log_panics::Config::install_panic_hook::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/log-panics-2.1.0/src/lib.rs:115:29
   6: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/alloc/src/boxed.rs:1980:9
      std::panicking::rust_panic_with_hook
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:841:13
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:706:13
   8: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:168:18
   9: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
  10: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
  11: core::result::unwrap_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/result.rs:1732:5
  12: core::result::Result<T,E>::unwrap
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1137:23
      service::sync::is_initialised
             at /Users/brian/Documents/GitHub/open-msupply.worktrees/origin-Bench-server/server/service/src/sync/mod.rs:150:15
  13: service::sync::file_sync_driver::FileSyncDriver::run::{{closure}}
             at /Users/brian/Documents/GitHub/open-msupply.worktrees/origin-Bench-server/server/service/src/sync/file_sync_driver.rs:76:16
  14: server::start_server::{{closure}}::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/macros/select.rs:557:49
  15: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/future/poll_fn.rs:58:9
  16: server::start_server::{{closure}}
             at /Users/brian/Documents/GitHub/open-msupply.worktrees/origin-Bench-server/server/server/src/lib.rs:339:5
  17: remote_server::main::{{closure}}
             at /Users/brian/Documents/GitHub/open-msupply.worktrees/origin-Bench-server/server/server/src/main.rs:14:40
  18: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/task/local.rs:995:42
  19: tokio::task::local::LocalSet::with::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/task/local.rs:747:13
  20: std::thread::local::LocalKey<T>::try_with
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:315:12
  21: std::thread::local::LocalKey<T>::with
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:279:15
  22: tokio::task::local::LocalSet::with
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/task/local.rs:745:9
  23: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/task/local.rs:985:9
  24: tokio::task::local::LocalSet::run_until::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/task/local.rs:639:19
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:124:9
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:124:9
  27: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:57
  28: tokio::runtime::coop::with_budget
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/coop.rs:73:5
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:25
  29: tokio::runtime::scheduler::current_thread::Context::enter
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:423:19
  30: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:695:36
  31: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:68
  32: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/context/scoped.rs:40:9
  33: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/context.rs:180:26
  34: std::thread::local::LocalKey<T>::try_with
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:315:12
  35: std::thread::local::LocalKey<T>::with
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:279:15
  36: tokio::runtime::context::set_scheduler
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/context.rs:180:9
  37: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:27
  38: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:683:19
  39: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:191:28
  40: tokio::runtime::context::runtime::enter_runtime
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  41: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:179:9
  42: tokio::runtime::runtime::Runtime::block_on_inner
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/runtime.rs:361:47
  43: tokio::runtime::runtime::Runtime::block_on
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/runtime/runtime.rs:333:13
  44: tokio::task::local::LocalSet::block_on
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.40.0/src/task/local.rs:596:9
  45: actix_rt::runtime::Runtime::block_on
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/actix-rt-2.10.0/src/runtime.rs:138:9
  46: actix_rt::system::SystemRunner::block_on
             at /Users/brian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/actix-rt-2.10.0/src/system.rs:244:9
  47: remote_server::main
             at /Users/brian/Documents/GitHub/open-msupply.worktrees/origin-Bench-server/server/server/src/main.rs:5:1
  48: core::ops::function::FnOnce::call_once
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  49: std::sys::backtrace::__rust_begin_short_backtrace
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
  50: std::rt::lang_start::{{closure}}
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:199:18
  51: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
      std::panicking::try
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
      std::panic::catch_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/rt.rs:168:24
      std::panicking::try::do_call
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
      std::panicking::try
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
      std::panic::catch_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
      std::rt::lang_start_internal
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/rt.rs:164:5
  52: std::rt::lang_start
             at /Users/brian/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:198:5
  53: _main
```

</details>

## Expected behaviour 🤔

For the server to not crash.

## How to Reproduce 🔨

To reproduce I used the [Bench-server](/msupply-foundation/open-msupply/tree/Bench-server) branch and ran it concurrently in 100 processes (`seq 100 | parallel -j 100 cargo run`). Most of the time the server returns an error instead of crashing however with enough clients the server crashes.

## Your environment 🌱

- Open mSupply Version: `Bench-server` branch
- Platform: macOS
- Database type: SQLite

### PR DESCRIPTION
**Pull request by ria8651**
Fixes #9979

# 👩🏻‍💻 What does this PR do?

Allows for configuration of the database connection pool settings. In particular the max connections the pool will manage and the timeout before the pool will close the connection. These settings can be used to stop the server crashing under load when too many connections are opened.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Use the [Bench-server](/msupply-foundation/open-msupply/tree/Bench-server) branch to make many requests to the server. If one instance isn't enough to crash the server you can run multiple instances using gnu `parallel`: `seq 50 | parallel -j 50 cargo run`
- [ ] If you still can't crash the server you can decrease `connection_pool_max_connections` or `connection_pool_timeout` to make it easier
- [ ] Once you're able to crash the server you can increase the `connection_pool_max_connections` or the `connection_pool_timeout` to stop the server crashing.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ x] **These areas should be updated or checked**: The configuration file and environment variable documentation should be updated

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/repository/src/database_settings.rs [hunk 1]
```diff
@@ -20,6 +21,8 @@ pub struct DatabaseSettings {
     pub host: String,
     pub database_name: String,
     pub database_path: Option<String>,
+    pub connection_pool_max_connections: u32,
+    pub connection_pool_timeout: u64,
```
Comment (andreievg) [inline server/repository/src/database_settings.rs]: can you specify units in the name please, when ambiguous

**Comment by ria8651** [comment]
> Also for postgres should default be something like 50-60% of default max connections, i think default is 100

The default in r2d2 for sqlite and Postgres is 10 which seems pretty reasonable.

**Review by andreievg — APPROVED** [review]
Looks great thanks. 

Btw instead of optional can use https://serde.rs/attr-default.html, but then would need to create a method for each default. This means slightly less code, however there is only two places you're doing unwrap_or.

@jmbrunskill this can go into 2.14.2, @ria8651 if you can wait before merge please
