### PR TITLE
7208 fix import asset and equipment csv error

### LINKED ISSUE #7208: Importing an asset or equipment returns an error
## What went wrong? 😲

Import an asset for coldchain returns an error for developer environment.

Cold Chain -> Equipment -> Click on `Import` button -> Upload equipment csv file -> Returns error: maximum depth update, state issue

Error after dropping a file into dropzone
Image

Image

## Expected behaviour 🤔

Be able to import an asset for cold chain -> equipment

## How to Reproduce 🔨

Steps to reproduce the behaviour:

**ColdChain**
1. Navigate Cold Chain -> Equipment
2. Click on Import Button
3. Upload an equipment csv File
4. Error!

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #7208 

# 👩🏻‍💻 What does this PR do?

Importing an asset or equipment CSV returns an error. This happens because `useTableStore` is called within `useAssetList`, which causes a bunch of re-renders. 

These re-renders occur due to the state or data in `useTableStore` being updated/populated when a new file is imported.

Created a `useAssetDelete` hook to separate the concern of managing `useTableStore's` state. Keeping `useTableStore` within `useAssetList` was causing unnecessary re-renders, so moving the delete logic to its own hook resolves this issue.

## 💌 Any notes for the reviewer?

Applying memoization techniques (`useMemo`, `useCallback`) didn't produce any luck in terms of solving this issue, hence created a dedicated hook for it instead

# 🧪 Testing

- [ ] Navigate ColdChain -> Equipment -> Click on Import Button -> Drop CSV File -> Works!
- [ ] Navigate Catalogue -> Asset -> Click on Import Button -> Drop CSV File -> Works!
- [ ] Navigate Catalogue -> Asset -> Select an asset -> Delete -> Works!
- [ ] Navigate Catalogue -> Asset -> Select a bunch of assets -> Delete -> Works!

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx [hunk 1]
```diff
@@ -305,7 +305,7 @@ export const EquipmentImportModal: FC<EquipmentImportModalProps> = ({
           steps={importSteps}
           activeStep={activeStep}
           onClickStep={onClickStep}
-        ></ClickableStepper>
+        />
```
Comment (CarlosNZ) [inline client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx:308]: 🙏

**Review by CarlosNZ — APPROVED** [review]
Cool, looks good thanks John.

Looks like this area is a weird mix of the new pattern and the old one, is that right?

**Comment by GeronimoJohn** [comment]
> Cool, looks good thanks John.
> 
> Looks like this area is a weird mix of the new pattern and the old one, is that right?

Yea a little bit, tried keeping everything related within the hook 😃
