### PR TITLE
9367 ledger views use item link

### LINKED ISSUE #9367: Ledger Fix: merged items show wrong ledger - ledger views don't traverse item_link
## What went wrong? 😲

After merging items, Catalogue > item > ledger hasn't been merged to represent the stock movements across the joint histories of the merged items.

My item's stock:

Image

That item's ledger's final balance:

Image

Which is what it was before the merge.

## Expected behaviour 🤔

After merging items, the ledger should include all the stock movements from across the original 2 items. We have item histories A and B, after A merge into B we should get the merged history of A∪B. when we view B's ledger it has all the stock movements of A as well as B, and the final balance matches the final stock.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. 2 items A and B
2. say 100 units of A and 200 units of B. Both have ledgers that say 100 and 200 respectively
3. Merge A into B
4. A is hidden/soft deleted so can't see ledger. B total across stock lines (as it respects item_link) is 300, but ledger only shows its original stock movements resulting in 200 balance (as it does not respect item_link). 

## Your environment 🌱

- Open mSupply Version: From about a year ago long since the ledger views were created. Right now is v2.10.1

### PR DESCRIPTION
**Pull request by Chris-Petty**
# Tests failing haha 

Fixes #9367 

# 👩🏻‍💻 What does this PR do?

Make the item ledger and stock movement views respect item_link 

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Have 2 items, and check their ledger in catalogue > item > ledger
- [ ] merge the 2 items
- [ ] Check the kept item's ledger, should match the SOH

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/repository/src/db_diesel/stock_movement.rs [hunk 1]
```diff
@@ -307,6 +322,12 @@ mod test {
             })
             .collect();
 
+        // TODO: unwrap this into various assertions that state what we are actually testing for
```
Comment (jmbrunskill) [inline server/repository/src/db_diesel/stock_movement.rs:325]: Should we do this todo, or is it done? Seems like maybe an old comment?

**Review by jmbrunskill — APPROVED** [review]
Looks good to me! Thanks Chris
