### PR TITLE
Fix outbound and suppler return statuses

### LINKED ISSUE #4890: Can't mark an Inbound Shipment as 'Delivered' without it affecting current stock levels
## What went wrong? 😲

The current workflow does not allow a user to confirm receipt of a delivery without triggering stock levels to be updated, regardless of whether they have had time to verify the contents of the delivery or not. 

These steps are separate in medium to large facilities as it takes time to verify the contents. 

It would be preferable to wait until the delivery has been marked as 'Verified' to update stock levels. 

As soon as this is marked as 'Delivered', the stock levels will be increased by 800 and can be distributed to customers (even if the stock doesn't actually exist):

telegram-cloud-photo-size-1-5163525153903193193-y

## Expected behaviour 🤔

Stock levels should not be updated until the delivery is 'Verified'

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open a new Inbound Shipment
2. Mark the shipment as 'Delivered'
3. Note stock levels have been updated

## Your environment 🌱

- Open mSupply Version: 2.2.2
- Legacy mSupply Central Server Version: 7-17-10

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #4890

# 👩🏻‍💻 What does this PR do?

Fixes outbound and supplier return issues when status is received (they were editable in front end and statuses not shown and status button shown)

Fixes customer return statuses

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] _(e.g.)_ Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] _(e.g.)_ This sample datafile: _google drive link_
- [ ] _(e.g.)_ Open a requisition with some lines
- [ ] _(e.g.)_ Make a couple invoices supplying some amount of those lines
- [ ] _(e.g.)_ Review that "issued" column is the sum of the amount already issued in invoices for this requisition

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/utils.ts [hunk 1]
```diff
@@ -23,6 +23,16 @@ import {
   SupplierReturnRowFragment,
 } from './Returns';
 
+export const allStatuses: InvoiceNodeStatus[] = [
```
Comment (andreievg) [inline client/packages/invoices/src/utils.ts:26]: I made this to separate StatusCrumbs from createStatusLog (the latter needs all statuses, otherwise statusIdx = 0, and the former just needs subset of statuses for display)

File: client/packages/invoices/src/Returns/CustomerDetailView/Footer/Footer.tsx [hunk 2]
```diff
@@ -38,12 +38,13 @@ const createStatusLog = (invoice: CustomerReturnFragment) => {
...
   }
-  if (statusIdx >= 2) {
+  if (statusIdx >= 1) {
     statusLog[InvoiceNodeStatus.Picked] = invoice.pickedDatetime;
   }
-  if (statusIdx >= 3) {
+  if (statusIdx >= 2) {
     statusLog[InvoiceNodeStatus.Shipped] = invoice.shippedDatetime;
   }
+  // Skipping delivered
```
Comment (roxy-dao) [inline client/packages/invoices/src/Returns/CustomerDetailView/Footer/Footer.tsx:47]: Why are we skipping received? 🤔 Should it not follow the same flow as Inbound since items are shipped to use, so we want to confirm that it has been delivered then received?

Also statusIdx has been changed to `  const statusIdx = allStatuses.findIndex(s => invoice.status === s);`
but this file is still using inboundStatuses

File: client/packages/invoices/src/Returns/SupplierDetailView/Footer/Footer.tsx [hunk 3]
```diff
@@ -46,7 +47,8 @@ const createStatusLog = (invoice: SupplierReturnRowFragment) => {
   if (statusIdx >= 4) {
     statusLog[InvoiceNodeStatus.Delivered] = invoice.deliveredDatetime;
   }
-  if (statusIdx >= 5) {
+  // Skipping received
```
Comment (roxy-dao) [inline client/packages/invoices/src/Returns/SupplierDetailView/Footer/Footer.tsx:50]: 🚀

File: client/packages/invoices/src/utils.ts [hunk 4]
```diff
@@ -182,11 +192,20 @@ export const getStatusTranslator =
...
+  switch (outbound.status) {
+    case InvoiceNodeStatus.New:
+    case InvoiceNodeStatus.Allocated:
+    case InvoiceNodeStatus.Picked:
+      return false;
+    case InvoiceNodeStatus.Delivered:
+    case InvoiceNodeStatus.Received:
+    case InvoiceNodeStatus.Verified:
+    case InvoiceNodeStatus.Cancelled:
+    case InvoiceNodeStatus.Shipped:
```
Comment (roxy-dao) [inline client/packages/invoices/src/utils.ts:204]: Nit: Would move shipped as first case to keep it grouped with the 'Outbound statuses'

File: client/packages/invoices/src/utils.ts [hunk 5]
```diff
@@ -197,11 +216,11 @@ export const isInboundDisabled = (inbound: InboundRowFragment): boolean => {
...
     case InvoiceNodeStatus.New:
-    case InvoiceNodeStatus.Allocated:
     case InvoiceNodeStatus.Delivered:
     // Inbound shipments can be edited when having been received (Note: was previous known as Delivered)
     case InvoiceNodeStatus.Received:
       return false;
+    case InvoiceNodeStatus.Allocated:
     case InvoiceNodeStatus.Picked:
     case InvoiceNodeStatus.Shipped:
     case InvoiceNodeStatus.Verified:
```
Comment (roxy-dao) [inline client/packages/invoices/src/utils.ts:226]: Nit: same comment as above for verified

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks for testing, finding and fixing this Andrei~

Few things to note below~ 

- Even though you've shipped the `Received` status in Detail View, it's still showing in List View~
Screenshot 2025-07-01 at 9 26 15 PM

File: client/packages/invoices/src/Returns/CustomerDetailView/Footer/Footer.tsx (hunk 2 above)
Comment (roxy-dao) [reply client/packages/invoices/src/Returns/CustomerDetailView/Footer/Footer.tsx:47]: Can we note this down to have a discussion somewhere. I think it's good to be consistent?

Comment (roxy-dao) [reply client/packages/invoices/src/Returns/CustomerDetailView/Footer/Footer.tsx:47]: I'm okay with keeping this as is for now~ but would like to discuss in the near future
