### PR TITLE
3895 Username no longer being displayed in sidepanels

### LINKED ISSUE #3895: Username no longer being displayed in sidepanels
## What went wrong? 😲
Usernames are no longer being displayed in the frontend even though the information is available

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3895

# 👩🏻‍💻 What does this PR do?
Users can be unknown if they are new users since they don't get synced back to Open mSupply. It is also possible to migrate existing data with no user_ID saved in the table. 

This PR shows a dash if the username is unknown. This has been made consistent throughout the app 

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Need an existing datafile
- [ ] Go to any invoice
- [ ] Open side panel
- [ ] If user is not known, dash should be shown

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Maybe the side panel screenshots if they show unknown user
  2.

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx [hunk 1]
```diff
@@ -25,11 +25,9 @@ export const RelatedDocumentsSectionComponent = () => {
     tooltip = t('messages.internal-order-created-on', {
       date: d(new Date(createdDatetime)),
     });
-    if (user?.username && user.username !== 'unknown') {
-      tooltip += ` ${t('messages.by-user', {
-        username: user?.username,
-      })}`;
-    }
+    tooltip += ` ${t('messages.by-user', {
```
Comment (roxy-dao) [inline client/packages/invoices/src/InboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx:28]: Opted to not have this hidden throughout since it could confuse users if it's displayed in some places and not others

File: client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx [hunk 2]
```diff
@@ -23,11 +23,7 @@ const RelatedDocumentsSectionComponent = () => {
     let tooltip = t('messages.customer-requisition-created-on', {
       date: d(createdDatetime),
     });
-    if (username && username !== 'unknown') {
-      tooltip += ` ${t('messages.by-user', { username })}`;
-    }
-
-    return tooltip;
+    return (tooltip += ` ${t('messages.by-user', { username })}`);
```
Comment (jmbrunskill) [inline client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx:26]: Pretty sure this will show as just `by` with no `-` I think that's ok right?

**Review by jmbrunskill — APPROVED** [review]
Looks fine to me, but I haven't tested all the places this can occur...
Could potentially just push it out to 2.1 to get testing done if we think there's any risk.

File: client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx (hunk 2 above)
Comment (roxy-dao) [reply client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx:26]: The place where it's being called passes in '-' if no username XD

**Comment by roxy-dao** [comment]
> Looks fine to me, but I haven't tested all the places this can occur... Could potentially just push it out to 2.1 to get testing done if we think there's any risk.

Low risk.
