### PR TITLE
3741 cannot sort the list in equipment table

### LINKED ISSUE #3741: Cannot sort the list in equipment table
## What went wrong? 😲
 
There's no sorting way in the CCEI module list as shown in the given teble.

Screenshot 2024-05-02 at 3 24 37 pm

## Expected behaviour 🤔
sorting is needed for some columns
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to coldchain > equipment list
2. Try to sort in the column

## Your environment 🌱

- Open mSupply Version: v2.0.00-rc2
- Legacy mSupply Central Server Version: V7-14-00

- Platform: web, mobile

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3741

# 👩🏻‍💻 What does this PR do?
Adds sorting for `store` and `asset number` to equipment and as a bonus a `functional status` filter too~

https://github.com/msupply-foundation/open-msupply/assets/61820074/3ff2cba3-987a-4170-92b9-2d0762c6ba7c

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to `Coldchain` -> `Equipment`
- [ ] Have some equipment
- [ ] Try sort by store or asset number
- [ ] Use the functional status filter

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Possibly screenshots? idk
  2.

### CODE REVIEW

File: client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx [hunk 1]
```diff
@@ -61,6 +63,36 @@ export const Toolbar = () => {
       name: t('label.non-catalogue'),
       urlParameter: 'isNonCatalogue',
     },
+    {
+      type: 'enum',
```
Comment (roxy-dao) [inline client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx:67]: Moved to top and made it default since I thought users would probably like to know which asset is actually functioning or not, etc... but can move if it isn't XD

File: server/repository/src/db_diesel/assets/asset_log.rs [hunk 2]
```diff
@@ -190,6 +191,12 @@ fn create_latest_filtered_query(filter: Option<AssetLogFilter>) -> BoxedLatestAs
     query
 }
 
+impl AssetLogStatus {
```
Comment (roxy-dao) [inline server/repository/src/db_diesel/assets/asset_log.rs:194]: moved this closer to where the filtering is happening 👀

File: server/repository/src/db_diesel/assets/asset_log_row.rs [hunk 3]
```diff
@@ -1,14 +1,10 @@
...
-use crate::asset_row::AssetRowRepository;
-use crate::ChangeLogInsertRow;
-use crate::ChangelogRepository;
-use crate::ChangelogTableName;
-use crate::EqualFilter;
-use crate::RepositoryError;
-use crate::RowActionType;
-use crate::StorageConnection;
-use crate::Upsert;
+use crate::asset_row::{asset, AssetRowRepository};
```
Comment (roxy-dao) [inline server/repository/src/db_diesel/assets/asset_log_row.rs:3]: Sorry.. just some refactoring

File: client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts [hunk 4]
```diff
@@ -14,6 +14,7 @@ export const useAssets = () => {
       { key: 'typeId', condition: 'equalTo' },
       { key: 'isNonCatalogue', condition: '=' },
       { key: 'store' },
+      { key: 'functionalStatus', condition: 'equalTo' },
```
Comment (clemens-msupply) [inline client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts:17]: Not related to this change, but IMHO we shouldn't fetch query params in the api hooks. This should be done closer to the page where it is used.

File: server/repository/src/db_diesel/diesel_schema.rs [hunk 5]
```diff
@@ -13,6 +14,8 @@ use super::{
 };
 
 allow_tables_to_appear_in_same_query!(
+    latest_asset_log,
+    asset,
```
Comment (clemens-msupply) [inline server/repository/src/db_diesel/diesel_schema.rs:18]: I would prefer to move the following to `asset.rs`:

```rust
allow_tables_to_appear_in_same_query!(
    latest_asset_log,
    asset,
    store,
);
```
(I think these are the three tables, right?)

This macro generates code for all combinations of its argument, i.e. there will be a lot of unnecessary code generated.

Also its clearer which tables we want to have in the same query.

**Review by clemens-msupply — CHANGES_REQUESTED** [review]

File: client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts (hunk 4 above)
Comment (roxy-dao) [reply client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts:17]: I agree 100%

**Review by clemens-msupply — APPROVED** [review]
Thanks works nicely
