### PR TITLE
6895 don't round displayed prescribed quantity

### LINKED ISSUE #6895: Decimal packs in prescriptions don't always show
## What went wrong? 😲

I was trying to issue some decimal packs in a prescription, and although saved, when you navigate away and navigate back to the item you are prescribing, the quantity appears as a whole number. 

Although, when i refresh the page, the decimal numbers are there - but as soon as i add a new item, the problem is back for new items onwards! 

Does not happen when you expand batches - there, the numbers are still decimals 

Video of the behaviour is ->>> [here](https://drive.google.com/drive/folders/1upJfbAClsZFiFX77bQDkRyb9xizsyuLH)

## Expected behaviour 🤔

Should be saving in decimal packs and even when you navigate away and back, it should still show the same numbers

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Prescriptions
2. Create a new prescription and add an item
3. Issue decimal quantity -> save -> without navigating away, the number is still decimal
4. Navigate away and back -> the number is back to a whole number
5. Add another item -> repeat steps -> the issue is there
6. Go back to the first item - most likely, there the quantity is now showing decimal number
7. Inconsistent

## Your environment 🌱

- Open mSupply Version: V2.6.1-RC1
- Legacy mSupply Central Server Version: V8.00.11

- Platform: Google Chrome (browser for Mac)

- Database type: PostgreSQL

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #6895 

# 👩🏻‍💻 What does this PR do?

Removes rounding to no decimals from prescription prescribed quantity display.

## 💌 Any notes for the reviewer?

You can more easily view changes without new linting changes [here](https://github.com/msupply-foundation/open-msupply/compare/53c6b07271bc0e64962a45717574b72ea2a210ce...c694f1e940236352115c8128870232e25daa9d0d)

Values passed around retain all information; they were just getting rounded before front end display.

# 🧪 Testing

- [ ] Navigate to prescriptions
- [ ] Add 2 or more items to the prescription
- [ ] Set the quantity to a decimal for one of the items and save
- [ ] See that this decimal value is retained when navigating between items

# 📃 Documentation

- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx [hunk 1]
```diff
@@ -559,7 +557,7 @@ const summarise = (
     } else {
       counts[packSize] = {
         unitName: (stockLine?.item as ItemNode)?.unitName ?? 'unit',
-        count: NumUtils.round(packSize * numberOfPacks),
+        count: NumUtils.round(packSize * numberOfPacks, 2),
```
Comment (fergie-nz) [inline client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx:560]: Still rounding to 2 to avoid unwieldy numbers

File: client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx [hunk 2]
```diff
@@ -89,396 +89,394 @@ export const PrescriptionLineEditForm: React.FC<
...
+          selectedItem?.lines?.find(
+            ({ prescribedQuantity }) => prescribedQuantity != null
+          )?.prescribedQuantity ?? 0;
+        setPrescribedQuantity(newPrescribedQuantity);
+      }
 
-    setAbbreviation('');
-    setDefaultDirection('');
-  }, [item?.id]);
+      const newIssueQuantity = NumUtils.round(allocatedUnits / Math.abs(Number(packSizeController.selected?.value || 1)), 2);
```
Comment (fergie-nz) [inline client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx:225]: Rounding to 2dp here also to be consistent with other parts of app for input values.
