### PR TITLE
#4152 Date filter label fix

### LINKED ISSUE #4125: Immunisation program/vaccine course UI issues
## What went wrong? 😲

https://github.com/msupply-foundation/open-msupply/assets/55115239/df7146ae-12a7-4239-9f12-3163506862ee

- Create modals not clearing on save
- App crashes when try to create duplicate name
- Vaccine course create modal not titled correctly
- Can create duplicate vaccine courses... is that fine?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

See video

### LINKED ISSUE #4152: Date Inputs do not show titles or text unless interacted with
## What went wrong? 😲

In a few areas of Open mSupply, date inputs do not have/show titles or text unless interacted with.

For example, `Inventory -> View Stock` looks like this when the filter is first applied -> 

Screenshot 2024-06-14 at 9 34 28 AM

`Replenishment -> Inbound Shipment`

Screenshot 2024-06-14 at 9 39 40 AM

`Patients -> Date of Birth`

Screenshot 2024-06-14 at 9 46 45 AM

`Cold Chain -> Equipment -> Installation Date and Replacement Due`

Screenshot 2024-06-14 at 9 48 58 AM

## Expected behaviour 🤔

Field titles and text should be showing at all times, not just when interacted with fields :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to any of the admin areas outlined above
2. Add the filter if not shown by default
3. See the error

## Your environment 🌱

- Open mSupply Version: `V2.1.0-IA-test-2`
- Legacy mSupply Central Server Version: `V7.15.00`

- Platform: Galaxy Tab A8 (Android)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #4152

*PLEASE NOTE: I had a moment of dyslexia and mis-named my branch as `4125-`* 🙄

# 👩🏻‍💻 What does this PR do?

Quite a subtle problem here. Turns out that the Mui `sx` prop can actually be an *array* of SX objects as well as a single SX object. What was happening here is that the `sx` styles for the "textField" slotProps in the DateTimePickerInput were being converted to such an array before being passed down to the BasicTextInput component (presumably due to additional styles being injected internally by the Mui DateTimePicker component). And then, when we merged the `sx` objects, the resulting prop was not correct (I think it turned array indexes into object keys, which is why it never threw an error).

Solution here is to just put the SX object into a flattened array when merging, regardless, so that it doesn't matter if the incoming `sx` is already an array or an object.

## 💌 Any notes for the reviewer?

We're merging `sx` objects a lot throughout the app, so this could turn out to be a problem elsewhere. Something to be aware of, and maybe we should establish a convention for merging styles. Any thoughts, @mark-prins ?

# 🧪 Testing

Labels should show up correctly for the Date filters when initialised, and look basically the same as the Text filter:

Screenshot 2024-06-21 at 11 42 47 AM

### CODE REVIEW

**Review by roxy-dao — APPROVED** [review]
👀  classic ~

LGTM! Thanks Carl~

File: client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx [hunk 1]
```diff
@@ -56,11 +57,20 @@ export const BasicTextInput: FC<BasicTextInputProps> = React.forwardRef(
...
+          // the incoming sx prop
+          sx={
+            [
+              {
+                '& .MuiInput-underline:before': { borderBottomWidth: 0 },
+                '& .MuiInput-input': { color: 'gray.dark', textAlign },
+              },
+              sx,
+            ].flat() as SxProps
+          }
```
Comment (mark-prins) [inline client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx:73]: to avoid the type coercion, you could just remove the possibility of `undefined`
 
```suggestion
          sx={[
            {
              '& .MuiInput-underline:before': { borderBottomWidth: 0 },
              '& .MuiInput-input': { color: 'gray.dark', textAlign },
            },
            sx ?? {},
          ].flat()}
```

**Review by mark-prins — COMMENTED** [review]
Good find!
Wonder if we should create a helper to do the sx merging and avoid this problem?

**Comment by CarlosNZ** [comment]
> Wonder if we should create a helper to do the sx merging and avoid this problem?

You mean an `sxMerge()` method that handles all possible merge configurations? I did start to make one, but figured I should clarify all the cases first.

I guess it's just:

- multiple objects => merge as object
- if any items are array => flatten and push all to array

Sound about right? I'll do that on Monday, but if you want to merge this to include in the release today @roxy-dao, I'll make a new PR next week.

**Comment by roxy-dao** [comment]
> > Wonder if we should create a helper to do the sx merging and avoid this problem?
> 
> You mean an `sxMerge()` method that handles all possible merge configurations? I did start to make one, but figured I should clarify all the cases first.
> 
> I guess it's just:
> 
> * multiple objects => merge as object
> * if any items are array => flatten and push all to array
> 
> Sound about right? I'll do that on Monday, but if you want to merge this to include in the release today @roxy-dao, I'll make a new PR next week.

Yes please. I think we got a good amount of issues done to make a new RC build today
