### PR TITLE
R&R Form performance

### LINKED ISSUE #4568: R&R Forms perfomance
## What went wrong? 😲

When you have a number of rows in an R&R form the performance degrades

## Expected behaviour 🤔
Editing a single line should be pretty snappy

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an R&R form using a master list with 50+ rows
2. Edit a row on a tablet, or
3. add a `console.info` to the RnRFormLine component

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #4568

# 👩🏻‍💻 What does this PR do?

Some further improvements - only store draft state in zustand, so we're not resetting the whole store every change. 

+ some other fixes - see inline

## 💌 Any notes for the reviewer?

I tried the 800 line one on tablet, its pretty snappy - biggest thing is waiting for the lines to load when you scroll, but its manageable!

# 🧪 Testing

- [ ] Get big master list
- [ ] make R&R
- [ ] can update fast?
- [ ] plz test on android that it works and you can type in bottom row (this broke w virtualisation)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx [hunk 1]
```diff
@@ -84,7 +84,7 @@ export const ContentArea = ({
           '.first-column': {
             left: 0,
             position: '-webkit-sticky',
-            width: 80,
+            minWidth: 80,
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx:87]: code column was still jumping around on scroll -

File: client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx [hunk 2]
```diff
@@ -172,11 +172,12 @@ export const ContentArea = ({
             axis="y"
             renderSpacer={({ ref, style }) => <tr ref={ref} style={style} />}
             initialDelay={1}
+            itemSize={60}
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx:175]: This helps the scrollbar be the right size

File: client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx [hunk 3]
```diff
@@ -172,11 +172,12 @@ export const ContentArea = ({
...
           >
             {line => (
               <RnRFormLine
                 key={line.id}
-                id={line.id}
+                line={line}
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx:180]: We are already mapping over the lines - might as well use that line, rather than pass the id, to get it separately from zustand store

File: client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts [hunk 4]
```diff
@@ -40,22 +39,12 @@ export const useRnRForm = ({ rnrFormId }: { rnrFormId: string }) => {
     return result.__typename === 'RnRFormNode' ? result : null;
   };
 
-  const query = useQuery({ queryKey, queryFn, enabled: !form });
-
-  if (!isLoading && query.isLoading) setIsLoading(true);
-  if (form?.id !== query.data?.id && !!query.data) {
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts:46]: This was resulting in sometimes getting an R&R form not found error 🤷‍♀️

File: server/omsupply-chc-baoknana.sqlite.zip
Comment (lache-melvin) [inline server/omsupply-chc-baoknana.sqlite.zip:1]: not sure how this got committed lol

File: client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx [hunk 5]
```diff
@@ -172,11 +172,13 @@ export const ContentArea = ({
             axis="y"
             renderSpacer={({ ref, style }) => <tr ref={ref} style={style} />}
             initialDelay={1}
+            itemSize={60}
+            overscan={5} // Gives a buffer for when android keyboard opens
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx:176]: hopefully enough?

File: client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx [hunk 6]
```diff
@@ -84,31 +84,31 @@ export const ContentArea = ({
...
-            left: 79,
+            left: 80,
             minWidth: '300px',
             position: '-webkit-sticky',
           },
         }}
       />
       <Table
         sx={{
-          height: '500px',
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx:99]: was getting a bit of this 😁

File: client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx [hunk 7]
```diff
@@ -84,31 +84,31 @@ export const ContentArea = ({
...
           borderCollapse: 'separate',
           overflowY: 'scroll',
           '& th': {
             textAlign: 'left',
             padding: 1,
             fontWeight: 'bold',
             border: '1px solid',
+            borderLeft: '0px',
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx:105]: Border only on the right means sticky border won't jump around on side scroll

File: client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx:87]: I had to give `second-column` a `left: 82` to prevent the border disappearing on scroll though. 
Is it ok for you?

This is how my screen looks at `80`

https://github.com/user-attachments/assets/55abc4f5-5204-4e2c-a406-c2c11176411f

Comment (lache-melvin) [reply client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx:87]: Oh, I think some of your codes are longer than any I have - maybe we need to go a little bigger, and add an overflow?

File: client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts [hunk 8]
```diff
@@ -1,41 +1,28 @@
...
 
 interface RnRFormContext {
-  isLoading: boolean;
-  form: RnRForm | undefined;
-  lines: Record<string, RnRFormLine>;
-  setForm: (form: RnRForm) => void;
-  setIsLoading: (isLoading: boolean) => void;
-  setLine: (line: RnRFormLine) => void;
-  setLines: (lines: RnRFormLineFragment[]) => void;
+  dirtyLines: Record<string, RnRFormLineFragment>;
```
Comment (mark-prins) [inline client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts:5]: :nit the inconsistent naming is bothering me.
can you change 'dirty' to 'draft' plz? We have `setDraftLine` which updates the `dirtyLines`

File: client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx (hunk 3 above)
Comment (mark-prins) [reply client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx:181]: yeah, I went with Andrei's suggestion of using IDs and putting the fetch into the rows. given the refactor back to useQuery the line id is even more pointless than it was

**Review by mark-prins — APPROVED** [review]
Thanks - the changes are very nice.
Can you please rename `dirty` though? that's troubling me; and the table border isn't working for me as is. maybe merge in the 2.0.2 branch and check though, to pick up that other change to the col widths

**Comment by mark-prins** [comment]
lovely 😍 thanks!
