### PR TITLE
2513 count spinner control needs an option to unset the value

### LINKED ISSUE #2513: Count Spinner Control needs an option to unset the value
image

When setting and deleting the value in the spinner the value is not fully unset. This causes a validation to fail.

For example, if the blood pressure field has been accidentally touched but the the blood pressure has not been measured the clinician is forced to enter a made up value in order to continue.

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #2513 

# 👩🏻‍💻 What does this PR do? 
Sets up a custom control for `blood pressure`. This control shows systolic and diastolic values next to each other separated by `/` which is normal(?) since blood pressure is usually shown as e.g. 120/80. And also doesn't prompt error if none of these values are set.

https://github.com/msupply-foundation/open-msupply/assets/61820074/1ce2cb6d-409b-4aa6-a210-0436b70b35a0

# 🧪 How has/should this change been tested? 
- [ ] Have programs set up (make sure to have latest program updates)
- [ ] Add encounter to patient
- [ ] Go to `physical exam`
- [ ] Enter different values into blood pressure

### CODE REVIEW

File: client/packages/programs/src/JsonForms/components/BloodPressure.tsx [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+    if (core) {
+      const getChildErrors = subErrorsAt(path, schema);
+      const errors = getChildErrors(core);
+      setCustomError(errors[0]?.message);
+    }
+  }, [core]);
+
+  if (!props.visible) {
+    return null;
+  }
```
Comment (clemens-msupply) [inline client/packages/programs/src/JsonForms/components/BloodPressure.tsx:48]: You are not allowed to conditionally call a hook, i.e. you return here and then call useEffect later. You can just move this return down just before returning the "tsx html".

There should already be an active lint rule for it...

**Review by clemens-msupply — CHANGES_REQUESTED** [review]
Look good! Just one main change request. When entering the systolic value very quickly e.g. 11 then it often reverts to 1. You need to debounce the input like in other controls...

**Comment by clemens-msupply** [comment]
I still had some editing issues. I was not 100% sure how to fix it so I tinkered arround a bit to make it work. I create a PR with a solution that worked for me. If you could please have a look.
