### PR TITLE
8137 fix zebra printer crash

### LINKED ISSUE #8137: Label Printing is Not Working and Making Printer Unaccessible
> UPDATE - some logs around this have gone into 2.9 but keeping issue open, further work needed

## What went wrong? 😲

When printing from Open mSupply:

- The test printer configuration says 'Connected successfully to printer!'
- Going to a prescription and printing it says 'Label printed successfully.'
- Check printer, no label has been printed
- Try printing, and it fails with the message 'Error printing label.: connection timed out'
- Before printing a prescription, you can visit the printer webui
- After printing the prescription, you can no longer visit the printer webui
- The printer has to be power-cycled to get it to respond again

Logs set to 'Debug', and only the following is recorded:

`2025-06-18 12:57:25.959502000 [INFO ] <actix_web::middleware::logger:424>:127.0.0.1 "POST /print/label-prescription HTTP/1.1" 200 13 "http://localhost:3003/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36" 1.008868
2025-06-18 12:57:51.753221000 [INFO ] <actix_web::middleware::logger:424>:127.0.0.1 "POST /print/label-prescription HTTP/1.1" 500 20 "http://localhost:3003/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36" 5.005547`

Tested with two Zebra label printers and two different networks

@louisaw123 has requested to try and have this fixed before August for a deployment

## Expected behaviour 🤔

Connection Test:
Image

Label Printed (Which it isn't)
Image

Try printing again, get error:
Image

Before and after printing (Printer webui):

Image
Image

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Set up label printing, test connection
2. Print prescription
3. See printing was 'successful' (but not really)
4. Print again and see the timeout error

## Your environment 🌱

- Open mSupply Version: 2.7.3
- Legacy mSupply Central Server Version: 8.02.12
- Platform: Tablet, Desktop, Docker
- Database type: SQLite (4D Demo data)

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #8137

# 👩🏻‍💻 What does this PR do?

A stray `\` was causing the Printers to hang expecting more data I think.

Added a sanitation function to try to avoid these issues occuring again.

## 💌 Any notes for the reviewer?

Any potenital issues with my sanitisation function?

# 🧪 Testing

- [ ] Try to print prescription labels with no warnings in OMS
- [ ] Check that the label prints...

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [x] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/print/label.rs [hunk 1]
```diff
@@ -91,7 +110,7 @@ pub fn print_prescription_label(
                 ^A0,25
                 ^FO,10
                 ^FB575,3,0,C
-                ^FD{item_details}\&^FS
+                ^FD{item_details}^FS
```
Comment (jmbrunskill) [inline server/service/src/print/label.rs:113]: Removed these new lines as didn't seem needed, maybe it was an attempt to avoid issues like we had.
@Chris-Petty ?

File: server/service/src/print/label.rs [hunk 2]
```diff
@@ -100,7 +119,7 @@ pub fn print_prescription_label(
                 ^A0,25
                 ^FO10,75
                 ^FB580,5,0
-                ^FD{item_directions}\&{warning}\^FS
+                ^FD{item_directions}\&{warning}^FS
```
Comment (jmbrunskill) [inline server/service/src/print/label.rs:122]: This is the real issue! Extra `\` causing havoc

File: server/service/src/print/label.rs [hunk 3]
```diff
@@ -125,3 +151,31 @@ pub fn host_status(settings: LabelPrinterSettingNode) -> Result<String> {
...
+// ^CI13 must be selected to print a backslash (\).
+fn sanitise_fd_field(value: &str) -> String {
+    let mut fd: String = value
+        .replace('^', "-") // Control characters are replaced with -
+        .replace('~', "-") // Control characters are replaced with -
+        .replace('\n', "\\&") // Newline characters are replaced with \& in ZPL
+        .replace('\r', "\\&") // Carriage return characters are replaced with \&
+        .replace('\\', "-") // Backslashes are replaced with - can be \\\\ but apparently only works with CI13?
+        .chars()
+        .map(|c| if c.is_ascii() && c != '-' { c } else { ' ' }) // Non-ASCII characters are replaced with a space
```
Comment (jmbrunskill) [inline server/service/src/print/label.rs:170]: This might cause problems with UTF-8, I'm not entirely clear if we can use UTF-8 Here. The `^CI28` command suggests maybe we can, but the docs for `FD` say `Characters with codes above 127, or the ^ and ~ characters, can be printed using the ^FH and ^FD
commands.` - https://www.zebra.com/content/dam/support-dam/en/documentation/unrestricted/guide/software/zpl-zbi2-pg-en.pdf
(page 190)

**Review by zachariah-at-msupply — COMMENTED** [review]
Thanks for letting me take a look at this James! It does the job very well! I also have a few refinements to suggest.

File: server/service/src/print/label.rs (hunk 3 above)
Comment (zachariah-at-msupply) [reply server/service/src/print/label.rs:170]: I investigated how to print the entrie UTF-8 charset on a zebra printer...
	- The good news: zebra printers do support printing the whole UTF-8 charset!
	- The bad news: the printer wont show the characters unless we...
	- either add ^FH to the ^FD command and then input the character's hexadecimal codes preceded by '_' (e.g. `^FH^FD some text and then _D0_94^FS` prints 'some text and then Д')
	- or change the printer's font to one that can handle UTF-8 (this is not hard to do but MIGHT require a new font to be added to the printer) (see comments in the highest scoring answer of this stack overflow thread: https://stackoverflow.com/questions/13040822/unicode-characters-on-zpl-printer#13041688)

File: server/service/src/print/label.rs [hunk 4]
```diff
@@ -81,7 +99,8 @@ pub fn print_prescription_label(
                 details,
             } = d;
             let warning = warning.unwrap_or_default();
-            format!(
+
+            let label = format!(
                 r#"
```
Comment (zachariah-at-msupply) [inline server/service/src/print/label.rs:104]: Here's the suggested updated spacings (the values in here came from finding out that the maximum width of the label is ~600 px and giving the label a left and right margin of 18. I tested it on the real printer, result below):

```suggestion
r#"
^XA
^FX CI command parameters:
^FX - encoding (28 = UTF-8)
^CI28

^A0,25
^FO18,18
^FB582,3,0,C
^FD{item_details}^FS


^FX Line
^FO18,65
^GB582,2,2^FS

^A0,25
^FO28,75
^FB562,5,0
^FD{item_directions}\&{warning}^FS

^FX Line
^FO18,210
^GB582,2,2^FS

^A0,20
^FO18,220
^FB582,3,0,C
^FD{patient_details}\&{details}^FS

^XZ
"#
```

File: server/service/src/print/label.rs [hunk 5]
```diff
@@ -109,11 +128,18 @@ pub fn print_prescription_label(
                 ^A0,20
                 ^FO,220
                 ^FB575,3,0,C
-                ^FD{patient_details}\&{details}\&^FS
+                ^FD{patient_details}\&{details}^FS
 
                 ^XZ
                 "#
```
Comment (zachariah-at-msupply) [inline server/service/src/print/label.rs:134]: Suggested updated spacings (the values in here came from finding out that the maximum width of the label is ~600 px and giving the label a left and right margin of 18. I tested it on the real printer, result below):

```suggestion
r#"
^XA
^FX CI command parameters:
^FX - encoding (28 = UTF-8)
^CI28

^A0,25
^FO18,18
^FB582,3,0,C
^FD{item_details}^FS


^FX Line
^FO18,65
^GB582,2,2^FS

^A0,25
^FO28,75
^FB562,5,0
^FD{item_directions}\&{warning}^FS

^FX Line
^FO18,210
^GB582,2,2^FS

^A0,20
^FO18,220
^FB582,3,0,C
^FD{patient_details}\&{details}^FS

^XZ
"#
```

File: server/service/src/print/label.rs [hunk 6]
```diff
@@ -125,3 +151,31 @@ pub fn host_status(settings: LabelPrinterSettingNode) -> Result<String> {
     let printer = Jetdirect::new(settings.address, settings.port);
     printer.send_string("~HS".to_string(), Mode::Sgd)
 }
+
+// Format a field for the FD command in ZPL
```
Comment (Chris-Petty) [inline server/service/src/print/label.rs:155]: Tangential but I wonder how hard it'll be to support fonts for Arabic or Russian...

Comment (jmbrunskill) [reply server/service/src/print/label.rs:155]: Sounds like it's all possible.

File: server/service/src/print/label.rs [hunk 7]
```diff
@@ -125,3 +151,31 @@ pub fn host_status(settings: LabelPrinterSettingNode) -> Result<String> {
...
+// https://www.zebra.com/content/dam/support-dam/en/documentation/unrestricted/guide/software/zpl-zbi2-pg-en.pdf
+// Comments: The ^ and ~ characters can be printed by changing the prefix characters—see ^CD ~CD on
+// page 153 and ^CT ~CT on page 166. The new prefix characters cannot be printed.
+// We'll map them to a `-` so they can be printed as part of the field.
+// Any character codes > 127 will be replaced with a space, as they are not valid in ZPL.
+// ^CI13 must be selected to print a backslash (\).
+fn sanitise_fd_field(value: &str) -> String {
```
[the remark this answers is not in the document]
Comment (jmbrunskill) [reply server/service/src/print/label.rs:162]: Yeah I did think that, however not entirely sure how stable they'll be. Will create some anyway...

File: server/service/src/print/label.rs (hunk 3 above)
Comment (jmbrunskill) [reply server/service/src/print/label.rs]: Created new issue to follow up on this...
