### PR TITLE
Fix report name column width + fix warnings

### LINKED ISSUE #4082: Dispensary reports: name column is too small
## What went wrong? 😲
image

## Expected behaviour 🤔

Column should be wider + tooltip

## Your environment 🌱

- Open mSupply Version: 2.1.0

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #4082

# 👩🏻‍💻 What does this PR do?
Increase the column width (requested by @louisaw123 )

image

Also fixes some warnings.

### CODE REVIEW

**Review by roxy-dao — APPROVED** [review]
LGTM~

File: client/packages/system/src/Report/ListView/ListView.tsx [hunk 1]
```diff
@@ -91,13 +92,18 @@ const ReportListComponent = ({ context }: { context: ReportContext }) => {
 
   const columns = useColumns<ReportRowFragment>(
     [
-      'name',
+      {
+        key: 'name',
+        label: 'label.name',
+        width: 300,
+        Cell: TooltipTextCell,
+      },
```
Comment (roxy-dao) [inline client/packages/system/src/Report/ListView/ListView.tsx:100]:
```suggestion
    ['name', { width: 300, Cell: TooltipTextCell }],
```
