### PR TITLE
Set is dirty state when updating quantity

### LINKED ISSUE #6552: Cannot allocate placeholder lines in Outbound Shipment
## What went wrong? 😲

I have some placeholder lines, either from OS created from requisition, or from master list. I want to select the stock to allocate... but nothing happens when I do! (API call is not being fired, haven't looked into why):

https://github.com/user-attachments/assets/2be8efdf-9430-4514-9885-d9956a36ccaa

Note that auto-allocation from the footer actions still works, just not from this modal.

## Expected behaviour 🤔

Stock gets allocated, line to turns black.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create new outbound shipment
2. Click `Add from master list` to add some placeholder lines
3. Click on the placeholder line to select stock to allocate
4. Click Ok - see stock has not been allocated

## Your environment 🌱

- Open mSupply Version: 2.6 develop
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6552

# 👩🏻‍💻 What does this PR do?
Issuing pack size straight from the batch line wasn't updating the dirty state, thus the api call never gets called 😅 

# 🧪 Testing

- [ ] Create an Outbound Shipment 
- [ ] Add from master list to get quick lines
- [ ] Click on a line, allocate from batch level. 
- [ ] Click ok
- [ ] API should be called and line should be updated

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [x] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [x] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [x] Frontend

### CODE REVIEW

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx [hunk 1]
```diff
@@ -102,6 +102,7 @@ export const OutboundLineEdit: React.FC<ItemDetailsModalProps> = ({
   const onUpdateQuantity = (batchId: string, quantity: number) => {
     updateQuantity(batchId, quantity);
     setIsAutoAllocated(false);
+    setIsDirty(true);
```
Comment (noel-yeldos) [inline client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx:105]: So what exactly does setting this to "true" do? Is dirty state just letting the DOM know that state has changed but not to re-render?

**Review by noel-yeldos — APPROVED** [review]
LGTM! Tested and API call is being triggered

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx:105]: Yes, isDirty is used to track if something has changed. So if something has changed, we want to call the API.
