### PR TITLE
3704-Fix-fully-issued-lines-dissapearing-in-outbound-shipment

### LINKED ISSUE #3704: Picked OS: Can no longer edit stock in invoice line if all has been issued
## What went wrong? 😲
Stock lines disappearing from invoice line after allocating all the stock since stock leaves inventory at `Picked`, but we are still allowing the user to edit the invoice, so the user should still be able to edit the stock. 

Q. Why does OMS `picked` functionality have to match OG `cn` functionality? Why can stock not still be in inventory but just unavailable?

Screenshot 2024-04-30 at 10 08 37

## Expected behaviour 🤔
The user should still be able to edit the stock line!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an `Outbound Shipment` 
2. Add invoice line
3. Issue all stock from stock line
4. Change status to `Picked`
5. Go back to invoice line
6. See that stock line has disappeared

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #3704

# 👩🏻‍💻 What does this PR do? 

Combined stock lines frmo invoice lines with stock lines from item availableStockLines (which filters out totalNumberOfPack == 0) when creating draftLines in OS line edit

# 🧪 How has/should this change been tested? 

1. Create an `Outbound Shipment` 
2. Add invoice line
3. Issue all stock from stock line
4. Change status to `Picked`
5. Go back to invoice line
6. See that stock line has disappeared

Also it's good to check that no duplicate lines appear in OS line edit. Issue some stock in new status and refresh page

### CODE REVIEW

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx [hunk 1]
```diff
@@ -46,7 +47,18 @@ export const useDraftOutboundLines = (
     if (!data) return;
 
     setDraftStockOutLines(() => {
-      const rows = data.nodes
+      // Stocklines (date.nodes) are coming from availableStockLines from itemNode
```
Comment (roxy-dao) [inline client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx:50]:
```suggestion
      // Stocklines (data.nodes) are coming from availableStockLines from itemNode
```

**Review by roxy-dao — COMMENTED** [review]
I'm still seeing them disappear =/ 

The stock list is being loaded from item.available_batches ;x

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx [hunk 2]
```diff
@@ -33,31 +33,33 @@ export const useDraftOutboundLines = (
...
-      // these are filtered by totalNumberOfPacks > 0 but it's possible to issue all of the packs
-      // from the batch in picked status, need to make sure these are not hidden
-      const invoiceLineStockLines = (lines ?? []).flatMap(l =>
-        l.stockLine ? [l.stockLine] : []
-      );
-      const stockLines = uniqBy(
-        [...data.nodes, ...invoiceLineStockLines],
-        'id'
-      );
+    // Stocklines (data.nodes) are coming from availableStockLines from itemNode
```
Comment (roxy-dao) [inline client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx:48]:
```suggestion
    // Stock lines (data.nodes) are coming from availableStockLines from itemNode
```

**Review by roxy-dao — APPROVED** [review]
Great! Thanks Andrei (:
