### PR TITLE
3949 fix taxPercentage mapping for service charges

### LINKED ISSUE #3949: Issues with adding service charges with tax
## Describe the bug 😲
Just noticed that trying to add tax in service-charges is not accepted directly 

## To Reproduce ⬇️
Steps to reproduce the behaviour:
1. Have some service items set up in your datafile
2. Create a outbound
3. Add some lines (good to have price values)
4. Now Add a service item and add amount first
5. Switch to `Tax` field and enter value like `1` and click OK
6. See error: it doesn't save at all
7. Delete that service-charge entry
8. Add same service-item again
9. Add amount and this time, don't put any value under `tax` field and save. It saves
10. Open that service-charge line again
11. This time, add your `1` value to the `tax` field. This time, it saves.

## Expected behaviour 🤔
service-charge entry should be smooth

## Screenshots 📸

https://github.com/msupply-foundation/msupply/assets/59193490/ff9e2a07-d0f2-41d2-adec-9a86a4203969

## Your environment 🌱

- Open mSupply Version: v2.0.0 exe, apk
- Legacy mSupply Central Server Version: v7-14-6

- Platform: server exe + browser (chrome)

- Database type: sqlite

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #3949

# 👩🏻‍💻 What does this PR do?

Correctly map tax -> taxPercentage so you can add a service line with a tax percentage set 😅 

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Have some service items configured
- [ ] Create an outbound shipment
- [ ] Add some lines
- [ ] In more details, add a service item
- [ ] Enter amount and tax percentage
- [ ] Click OK
- [ ] TEST: the service charge saves as expected, you can see the updated value in Pricing section

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/api/api.ts [hunk 1]
```diff
@@ -119,22 +122,28 @@ const inboundParsers = {
...
-  toInsertServiceCharge: (line: DraftInboundLine) => ({
+  toInsertServiceCharge: (
+    line: DraftInboundLine
+  ): InsertInboundShipmentServiceLineInput => ({
     id: line.id,
     invoiceId: line.invoiceId,
     itemId: line.item.id,
     totalBeforeTax: line.totalBeforeTax,
-    tax: line.taxPercentage,
+    taxPercentage: line.taxPercentage,
```
Comment (lache-melvin) [inline client/packages/invoices/src/InboundShipment/api/api.ts:132]: Honestly impressed that it didn't throw a type error all the time before, only when tax is set? TIL graphql prunes undefined inputs 👀

File: client/packages/invoices/src/OutboundShipment/api/api.ts [hunk 2]
```diff
@@ -137,22 +140,28 @@ const outboundParsers = {
   toDeletePlaceholder: (line: DraftStockOutLine) => ({
     id: line.id,
   }),
-  toInsertServiceCharge: (line: DraftStockOutLine) => ({
+  toInsertServiceCharge: (
+    line: DraftStockOutLine
+  ): InsertOutboundShipmentServiceLineInput => ({
```
Comment (lache-melvin) [inline client/packages/invoices/src/OutboundShipment/api/api.ts:145]: added return types to hopefully reduce any naming changes being missed in future

File: client/packages/invoices/src/InboundShipment/api/api.ts (hunk 1 above)
Comment (roxy-dao) [reply client/packages/invoices/src/InboundShipment/api/api.ts:132]: Nice catch!

File: client/packages/invoices/src/OutboundShipment/api/api.ts (hunk 2 above)
Comment (andreievg) [reply client/packages/invoices/src/OutboundShipment/api/api.ts:145]: I really like de-structure and re-structure for these sorts of things, not sure if it would have helped here, but might have !

**Review by andreievg — APPROVED** [review]
Looks good to me, thank you

Interesting awhile ago we had an issue to consolidate all of the tax inputs to,  `tax: { percentage: line.taxPercentage }`, this could have helped ¯\_(ツ)_/¯

**Comment by andreievg** [comment]
@lache-melvin oops, can you rebase please

**Comment by roxy-dao** [comment]
> Looks good to me, thank you
> 
> Interesting awhile ago we had an issue to consolidate all of the tax inputs to, `tax: { percentage: line.taxPercentage }`, this could have helped ¯_(ツ)_/¯

It was only for all non-insert mutations 👀

**Comment by lache-melvin** [comment]
> @lache-melvin oops, can you rebase please

lol it would seem i don't learn 🙏
