### PR TITLE
6784 report arguments selected program is not repopulated

### LINKED ISSUE #6760: When Refiltering the satisfaction rate per program report, the period filter displays more periods than hte ones associated with the program Schedules
## What went wrong? 😲
The filtering when launching the report works properly as I only see the periods of the schedule associated with the program I have chosen. However, when refiltering the report, instead of seeing only the periods of the Mensuelle (Monthly) schedule I see also the periods of the Trimestrielle (Quaterly) schedule.

 https://drive.google.com/file/d/1EHHloBiSNeB33bV31KR-I_-yUnpeS4GR/view?usp=sharing

## Expected behaviour 🤔
I believe that even when refiltering, only the periods of the schedule associated with the program selected should be visible.  

## How to Reproduce 🔨

Steps to reproduce the behaviour:
See video above

## Your environment 🌱

- Open mSupply Version: v2.6.0RC4
- Legacy mSupply Central Server Version: v8-0-12

- Platform: omSupply Desktop

- Database type: SQLlite

### LINKED ISSUE #6784: Report arguments selected program is not repopulated
## What went wrong? 😲

When viewing a report, there is a `Filters` button in the toolbar, so you can edit filters. However, when I open this, my currently selected program is not repopulated, making it look like currently I have no program selected, even though I do!

Image

Happening for both `ProgramSearch` and `PatientProgramSearch`

## Expected behaviour 🤔

Like other filters, should be repopulated based on the current selected program Id (in URL)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports
2. Generate pending encounters - select a program
3. Once report generated, click `Filters` in the toolbar
4. See program selector is empty 

## Your environment 🌱

- Open mSupply Version: 2.6 RC5
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6784 & Fixes #6760

# 👩🏻‍💻 What does this PR do?
Retain program/period information when re-filtering 

https://github.com/user-attachments/assets/61c12fa1-1524-4486-8f23-6819feec35de

Also fixes periods not loading correctly

https://github.com/user-attachments/assets/33a34ee2-a977-4b2e-80ef-2136b1406811

# 🧪 Testing

- [ ] Go to a report that has program or period filtering
- [ ] Select a program/period
- [ ] Wait for report to load, then click filter at the top of the report page
- [ ] Should see information retained
- [ ] Have different periods for each program
- [ ] Change between programs and check that periods are loading correctly

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx [hunk 1]
```diff
@@ -93,7 +93,7 @@ export function AutocompleteWithPagination<T extends RecordWithId>({
     lastOptions.current = newOptions;
 
     return newOptions;
-  }, [pages]);
+  }, [pages, value]);
```
Comment (roxy-dao) [inline client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx:96]: Needs to shift the correct value if it changes

File: client/packages/programs/src/JsonForms/components/PeriodSearch.tsx [hunk 2]
```diff
@@ -43,6 +44,21 @@ const UIComponent = (props: ControlProps) => {
...
+  const periodId = extractProperty(core?.data, 'periodId');
+  useMemo(() => {
+    if (periodId && !period) {
+      const period = data?.pages
+        ?.find(page => page.data.nodes.some(period => period.id === periodId))
+        ?.data.nodes.find(period => period.id === periodId);
+      if (period) {
+        setPeriod(period);
+      }
+    }
```
Comment (fergie-nz) [inline client/packages/programs/src/JsonForms/components/PeriodSearch.tsx:56]: Having to use nested searching like this almost makes me want to have separate usePeriodList hooks (one for infinateQuery, one just returning nodes).

But I imagine this remains the most streamlined way to manage this.

**Review by fergie-nz — APPROVED** [review]
Nice Roxy looks great 🚀
