### PR TITLE
2667 Can we auto-confirm requisition after the shipment has been created from the requistion?

### LINKED ISSUE #2667: Can we auto-confirm requisition after the shipment has been created from the requistion?
## What went wrong? 😲
 
Currently, on getting a new requisition, there's no way to differentiate the requisitions which are new (unprocessed) or which have associated shipments already.

I think this can be confusing for the users (at least, for the first time users who are using/understanding the order flow: Internal Order>>Requisition>>Shipment) 

## Expected behaviour 🤔
Maybe it'll be good to have three statuses (like the OG mSupply):
sg - for newly received requisitions (or the ones where NO related shipment line has been made)
cn - once the outbound shipment has been created from the requisition
fn - User can finalise it. No any changes can be made afterwards

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get multiple requisitions (by creating IO from other stores)
2. Fulfill some requisitions: supply requested and create outbound shipment (either finalise it or not) while leave the other requisitions without supplying (literally do nothing for some).
3. Go back to the Requisitions List
4. See error: it is kinda difficult to know which were fulfilled and which are remaining from that list. [You'll have to manually open the requisition and click `Create shipment` to know which orders are in the process of being fulfilled/acknowledged]
At times of multiple requisitions, I think this can be quite frustrating?
Worst case: User can get confused and end up finalizing the wrong requisition (then, again another order may have to be processed from the customer/requester)

## Agreed solution
Rather than add a third status value, and automatically set the shipment to that status, display that a shipment has been created.

To do this:
* add a filter to the requisition api for `Shipment created` ( open to alternative naming suggestions ): boolean, indicates whether any shipment has been created for this requisition
* add the `Shipments` property ( again, open to naming suggestions ) which gives the number of shipments created for this requisition
* add a column to the requisition list view which shows the number of shipments

## Your environment 🌱

 - Version: v1.5.4
 - Platform:
   - browser (extra points if you tell us which one)

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #2667

# 👩🏻‍💻 What does this PR do?
1. Adds a `Shipment Created` boolean filter to Response Requisition list view
2. Adds a column to display how many shipments have been created from the Requisition in the list view

https://github.com/msupply-foundation/open-msupply/assets/61820074/c65479fd-6174-4a7e-85c9-5a9fff8e8c11

# 🧪 Testing

- [ ] Have some response requisitions
- [ ] Have at least one with shipment/s created and one without
- [ ] Add the `Shipment Created` filter
- [ ] Toggle on and off to see requisitions that have shipments created
- [ ] Also make sure `Shipments` count in column is correct.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Response requisition screenshots
  4.

### CODE REVIEW

File: server/graphql/requisition/src/requisition_queries.rs [hunk 1]
```diff
@@ -239,6 +240,7 @@ impl RequisitionFilterInput {
             linked_requisition_id: None,
             store_id: None,
             order_type: self.order_type.map(EqualFilter::from),
+            shipment_created: self.shipment_created,
```
Comment (andreievg) [inline server/graphql/requisition/src/requisition_queries.rs:243]: can we make this sound like a boolean ?

File: server/graphql/types/src/types/requisition.rs [hunk 2]
```diff
@@ -213,6 +213,13 @@ impl RequisitionNode {
         Ok(InvoiceConnector::from_vec(result))
     }
 
+    pub async fn number_of_shipments(&self, ctx: &Context<'_>) -> Result<i32> {
```
Comment (andreievg) [inline server/graphql/types/src/types/requisition.rs:216]: hmm, could also use the shipments loader, just select the ids in graphql and length in front end, it's not as direct but since we are using graphql already could re-use existing

File: client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx [hunk 3]
```diff
@@ -51,6 +51,10 @@ export const ResponseRequisitionListView: FC = () => {
         key: 'status',
         condition: 'equalTo',
       },
+      {
+        key: 'shipmentCreated',
```
Comment (andreievg) [inline client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx:55]: Mark mentioned 'a shipment has been created' filter, is that name too big to fit in filters ?

File: server/repository/src/db_diesel/requisition/requisition.rs [hunk 4]
```diff
@@ -216,7 +218,24 @@ fn create_filtered_query(
         apply_string_filter!(query, comment, requisition_dsl::comment);
 
         apply_equal_filter!(query, store_id, requisition_dsl::store_id);
-        apply_equal_filter!(query, order_type, requisition_dsl::order_type)
+        apply_equal_filter!(query, order_type, requisition_dsl::order_type);
+
+        if let Some(shipment_created) = shipment_created {
+            let requisition_ids = invoice_dsl::invoice
```
Comment (andreievg) [inline server/repository/src/db_diesel/requisition/requisition.rs:224]: I think this can be simplified to just use invoice, don't need to join requisition

**Review by andreievg — CHANGES_REQUESTED** [review]
Looks great Roxy, just one small request, to use invoice rather then joining requisition

File: client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx (hunk 3 above)
Comment (roxy-dao) [reply client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx:55]: How about `has shipment created`?

File: server/graphql/types/src/types/requisition.rs (hunk 2 above)
Comment (roxy-dao) [reply server/graphql/types/src/types/requisition.rs]: [7d73206](https://github.com/msupply-foundation/open-msupply/pull/4385/commits/7d73206b18caf1f8caf92a546317e77be0344ba6)

File: server/repository/src/db_diesel/requisition/requisition.rs (hunk 4 above)
Comment (roxy-dao) [reply server/repository/src/db_diesel/requisition/requisition.rs:224]: [078ab88](https://github.com/msupply-foundation/open-msupply/pull/4385/commits/078ab886f9377578904887f19118e76681709a16)

File: client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx (hunk 3 above)
Comment (andreievg) [reply client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx:55]: I would go with what product owner has decided in the issue comment.

File: server/graphql/types/src/types/requisition.rs (hunk 2 above)
Comment (andreievg) [reply server/graphql/types/src/types/requisition.rs]: https://github.com/msupply-foundation/open-msupply/compare/2667-Can-we-auto-confirm-requisition-after-the-shipment-has-been-created-from-the-requistion-...2667-Can-we-auto-confirm-requisition-after-the-shipment-has-been-created-from-the-requistion-(Work-around-types)

**Review by andreievg — APPROVED** [review]
Thanks @roxy-dao, approve with small changes here: https://github.com/msupply-foundation/open-msupply/compare/2667-Can-we-auto-confirm-requisition-after-the-shipment-has-been-created-from-the-requistion-...2667-Can-we-auto-confirm-requisition-after-the-shipment-has-been-created-from-the-requistion-(Work-around-types)
