### PR TITLE
4765 outbound shipment unit price incorrect, when multiple lines are grouped

### LINKED ISSUE #4765: Outbound Shipment: Unit Price incorrect, when multiple lines are grouped
## What went wrong? 😲

image

image

## Expected behaviour 🤔

Unit Price should either say `Multiple` if there is more than one price attached, or should be calculated as an average cost?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create outbound shipment
2. Select stock from two stock lines
3. click Group By Item button
4. Check if the Unit Price is correct

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4765

# 👩🏻‍💻 What does this PR do?
- Corrects the calculation for unit price.
- Defaults all price to 10 dp to show in tooltip (displays @ 2dp with ellipsis)
- Pack qty now gets the correct total
- Pack size now shows multiple if the batches are different sizes.

Screenshot 2024-10-01 at 2 25 13 PM
Screenshot 2024-10-01 at 2 25 32 PM

# 🧪 Testing

- [ ] Have stock lines with different prices maybe different pack sizes as well
- [ ] Add them to outbound shipment
- [ ] Calculate unit price to see that it matches with unit price (and that the logic is correct lul)
- [ ] Pack qty total should be sum of packs 
- [ ] Pack size should show multiple if multiple (and now same pack size)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Maybe screenshots? 
  2. Description of columns to avoid confusion?

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx [hunk 1]
```diff
@@ -28,12 +28,12 @@ export const CurrencyCell = <T extends RecordWithId>({
...
   const { c } = useCurrency(currencyCode);
   const price = Number(column.accessor({ rowData }) ?? 0);
-  // format prices > 1 with default precision
-  const precision = price < 1 ? 10 : undefined;
-  const fullText = c(price, precision).format();
+  const fullText = c(price, 10).format();
   let text = fullText;
-  if (price !== 0 && price < 0.001) {
-    text = `< ${c(0.001, 3).format()}`;
+  if ((price * 100) % 1 !== 0) {
```
Comment (jmbrunskill) [inline client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx:33]: A comment here might be nice?

File: client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx [hunk 2]
```diff
@@ -28,12 +28,12 @@ export const CurrencyCell = <T extends RecordWithId>({
 > => {
   const { c } = useCurrency(currencyCode);
   const price = Number(column.accessor({ rowData }) ?? 0);
-  // format prices > 1 with default precision
-  const precision = price < 1 ? 10 : undefined;
-  const fullText = c(price, precision).format();
+  const fullText = c(price, 10).format();
```
Comment (roxy-dao) [inline client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx:31]: Just defaulting it to 10 dp for now... since we don't do precision customisations >.>

File: client/packages/invoices/src/OutboundShipment/DetailView/columns.ts [hunk 3]
```diff
@@ -36,9 +36,6 @@ const notePopoverColumn = getNotePopoverColumn<
 const isDefaultPlaceholderRow = (row: StockOutLineFragment) =>
   row.type === InvoiceLineNodeType.UnallocatedStock && !row.numberOfPacks;
 
-const getPackSize = (row: StockOutLineFragment) =>
```
Comment (roxy-dao) [inline client/packages/invoices/src/OutboundShipment/DetailView/columns.ts:39]: Placeholder pack size still shows. Don't need this.

**Review by jmbrunskill — APPROVED** [review]
Looks good to me, I'll just let the team know about the common component changes.
Feels like we might want to allow some customisation or precision, especially when calculating which could result in more outlandish numbers?

File: client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx [hunk 4]
```diff
@@ -28,12 +28,12 @@ export const CurrencyCell = <T extends RecordWithId>({
...
   let text = fullText;
-  if (price !== 0 && price < 0.001) {
-    text = `< ${c(0.001, 3).format()}`;
+  if ((price * 100) % 1 !== 0) {
+    price < 0.01
+      ? (text = `< ${c(0.01, 2).format()}`)
+      : (text = `${c(price, 2).format()}...`);
```
Comment (jmbrunskill) [inline client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx:36]: Not clear to me when this ellipsis applies?

File: client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx (hunk 1 above)
Comment (jmbrunskill) [reply client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx:33]:
```suggestion
// if the price has more than 2 decimal places, round to 2 DP and add ellipsis, if less than 0.01 just show "<0.01"
  if ((price * 100) % 1 !== 0) {
```

Comment (roxy-dao) [reply client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx:33]: Comment in connecting PR (:

Comment (jmbrunskill) [inline client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx:33]:
```suggestion
// Some numbers have floating precision errors e.g. 2.05 * 100 == 204.99999999999997 so rounding the result to be more reliable...
  if (Math.round(price * 1000) / 10) % 1 !== 0) {
```

Comment (roxy-dao) [reply client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx:33]: https://github.com/msupply-foundation/open-msupply/pull/4939
