### PR TITLE
4014 You can query patient data without View Patients permission (via name query)

### LINKED ISSUE #4014: You can query patient data without `View Patients` permission (via name query)
## What went wrong? 😲

I have a user with no `View Patients` permission... but via API I can use the `name` query with a `type = PATIENT` filter and I get some patients back!

(FYI Patient list in omSupply won't work without view patients permission, but data shouldn't be accessible via names API either!)

## Expected behaviour 🤔

If no view patients permissions, I should not be able to see any patients!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure user has no `view patients` permissions in mSupply
2. Use something like Hasura to create a name query for patients (see below) 
3. Use a store_id that patients are visible for
4. You still get back some patients!

```gql
query Patients() {
  names(
    storeId: "STORE_ID_HERE"
    filter: {type: {equalAny: [PATIENT]}}
  ) {
    ... on NameConnector {
      totalCount
      nodes {
        type
        code    
        name
        dateOfBirth
        email
        address1
      }
    }
  }
}
```

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version: 7.14

- Platform: browser

- Database type: PG

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4014

# 👩🏻‍💻 What does this PR do?
Filters all patients out for names by default since there's a separate endpoint to get patients

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Call names endpoints with Type.Patient
- [ ] Shouldn't see any patients

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/repository/src/db_diesel/name.rs [hunk 1]
```diff
@@ -395,15 +395,12 @@ impl Name {
...
-    pub fn equal_to(&self) -> EqualFilter<NameType> {
-        EqualFilter {
-            equal_to: Some(self.clone()),
-            not_equal_to: None,
-            equal_any: None,
-            not_equal_all: None,
-            equal_any_or_null: None,
-            is_null: None,
-        }
+    pub fn equal_to(&self) -> EqualFilter<Self> {
```
Comment (roxy-dao) [inline server/repository/src/db_diesel/name.rs:398]: Just a lil refactor

**Review by CarlosNZ — APPROVED** [review]
Tested -- working 👍🏼 

Thanks
