### PR TITLE
7097 approval status to pending if item is in a program

### LINKED ISSUE #7097: Program items do not pass the authorisation module via general order
## What went wrong? 😲

Users can sometimes order program items from general orders, even though they have been trained to order them via the program. In doing so, they bypass the authorisation module.

## Expected behaviour 🤔

That it works like OG : each items from a program should be approved within the authorisation module, even though the order comes from General orders. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Store A
2. Go to 'Internal orders', 'new order', 'general', select store B
3. Order a program item
4. Go to Store B 
5. See Requisition Approval status : none

## Your environment 🌱

- Open mSupply Version: 2.6.01
- Legacy mSupply Central Server Version: N/A

- Platform: Mac

- Database type:

@richardmoizeau

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #7097

# 👩🏻‍💻 What does this PR do?

Checks if items that is selected/added to a requisition are part of a program. If they are and remote authorization is configured, approval status is set to pending.

## 💌 Any notes for the reviewer?

Docs for configuring OMS to use Remote Authorisation: https://docs.msupply.foundation/docs/replenishment/remote-authorisation/. Feel free to reach out if help is needed.

# 🧪 Testing

- [ ] Go to Store A
- [ ] Go to 'Internal orders', 'new order', 'general', select store B
- [ ] Order a program item (item that is part of a program)
- [ ] Go to Store B
- [ ] See Requisition `Approval status: Pending`

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/processors/transfer/requisition/create_response_requisition.rs [hunk 1]
```diff
@@ -62,9 +63,15 @@ impl RequisitionTransferProcessor for CreateResponseRequisitionProcessor {
...
             get_store_preferences(connection, &record_for_processing.other_party_store_id)?;
+
+        // Check if requisition has items that are part of programs
+        let has_program_items =
+            requisition_has_program_items(connection, &request_requisition.requisition_row.id)?;
+
         // TODO Rework once plugin functionality has been implemented
         let approval_status = if store_preference.response_requisition_requires_authorisation
             && request_requisition.requisition_row.program_id.is_some()
+            || has_program_items
```
Comment (fergie-nz) [inline server/service/src/processors/transfer/requisition/create_response_requisition.rs:74]: Hey John, wondering if this should be in brackets?

ie:
 `   let approval_status = if store_preference.response_requisition_requires_authorisation
            && (request_requisition.requisition_row.program_id.is_some()
            || has_program_items)`

Comment (GeronimoJohn) [reply server/service/src/processors/transfer/requisition/create_response_requisition.rs:74]: Yes! Good catch, thanks @fergie-nz. Will apply soon

**Review by fergie-nz — CHANGES_REQUESTED** [review]
Looks great John!

I think missing bracket in logic is only thing I'm noticing.

Plus optional query refactor if you think it is worthwhile

**Review by fergie-nz — APPROVED** [review]
Nice John!

LGTM

Nit is that Clippy had a few recommendations (ie I don't think you need clone program_master_list_ids)

**Comment by GeronimoJohn** [comment]
Heya @fergie-nz, appreciate the review. Do you mind doing one again please? Would appreciate it 😃. I checked with Jonna to ensure that OG and OMS have the same logic. I updated my logic to check items against ALL master lists not just programs

**Review by fergie-nz — APPROVED** [review]
Nice John looks great!

Though just flagging I'm surprised that that is the intended logic because my understanding was that if an item is not on a master list, it is not visible in any store. So wouldn't be able to be added to a requisition in the first place.

**Comment by GeronimoJohn** [comment]
Hi @fergie-nz, can I please get another review 🙏🏽

Fixed bug where items not part of programs were incorrectly requiring approval. Solution checks other store's programs and if selected items are part of them before setting approval to `pending` (initially considered masterlist checks but couldn't find a way to determine if specific items need admin approval)

**Review by fergie-nz — APPROVED** [review]
Nice John looks great, thank you for coordinating all of that to make sure logic is consistent. I'm curious what mSupply is doing under the hood.
