### PR TITLE
#6677 Don't show expired or inactive insurances in Prescription payment

### LINKED ISSUE #6677: Prescription Insurance Fixes
## What went wrong? 😲

Expired or inactive insurance can be selected when paying for a prescription

## Expected behaviour 🤔

If an insurance policy isn't active or it has expired, it shouldn't show in the drop down 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Mark an insurance policy as Inactive for a patient
2.Set the expiry data for an insurance policy as  in the past
3. Verify a prescritption (with a cost)
4. Check that the insurance polices above don't show in the dropdown on the payments modal

## Your environment 🌱

- Open mSupply Version: V2.6.0-RC
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #6677 (& #6692)

# 👩🏻‍💻 What does this PR do?

I just did the quick and dirty approach here and filtered out in the front-end rather than creating a whole new Filter structure on the server. Seemed acceptable given that the insurance list for a given patient should be pretty short and doesn't involve any pagination.

Also squeezed in a quick fix for #6692, since it's literally a one word change.

## 💌 Any notes for the reviewer?

See inline 

# 🧪 Testing

- [ ] Set up a patient with multiple insurances, make some of them expired, some inactive, some both
- [ ] Create a prescription for that patient, add some items, then "Verify"
- [ ] In the Payments modal that pops up, the list of "Insurance Schemes" should not include any that are expired or inactive

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/intl/utils/DateUtils.ts [hunk 1]
```diff
@@ -149,7 +149,8 @@ export const DateUtils = {
     fromUnixTime(Math.max(...dates.map(d => getUnixTime(d as Date)))),
   isPast,
   isFuture,
-  isExpired: (expiryDate: Date): boolean => isPast(expiryDate),
+  isExpired: (expiryDate: Date | string | number): boolean =>
```
Comment (CarlosNZ) [inline client/packages/common/src/intl/utils/DateUtils.ts:152]: Changed the input type of this to match the input type of `isPast` (string dates are fine)

File: client/packages/system/src/Patient/apiModern/hooks/useInsurances.ts [hunk 2]
```diff
@@ -22,7 +22,7 @@ const defaultDraftInsurance: DraftInsurance = {
   policyNumberPerson: '',
   insuranceProviderId: '',
   policyType: '' as InsurancePolicyNodeType,
-  isActive: false,
+  isActive: true,
```
Comment (CarlosNZ) [inline client/packages/system/src/Patient/apiModern/hooks/useInsurances.ts:25]: #6692 !

**Review by jmbrunskill — APPROVED** [review]
Looks good to me @CarlosNZ 

Might have some merge conflicts with me but that's ok :)

**Review by jmbrunskill — APPROVED** [review]
Thanks Carl, works good.
