### PR TITLE
5155 patient info update not showing in prescription

### LINKED ISSUE #5155: Updated patient's information is not showing in a prescription
## What went wrong? 😲

Scenario: I am changing patient's personal information, like first name. 

The change is reflected under `Dispensary -> Prescriptions` (in the overall view), but not when clicking on an individual prescription issued to that patient. Video of the behaviour is attached ->>> [here](https://drive.google.com/drive/folders/1e4sJzD7AfvKBYgKTkWdxHg51QRq6h2Az)

Marking as `Normal` as technically there is a workaround of removing the patient and retyping their new information to re-add them to the prescription

## Expected behaviour 🤔

Information should be updated consistently across the platform

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Dispensary -> Prescriptions`
2. Create a prescription for a patient
3. Go to `Dispensary -> Patients`
4. Change the patient's first name for testing purposes
5. Go back to the prescriptions window -> you can see the change in the overall view but not when clicking on a specific prescription
6. Inconsistency! 

## Your environment 🌱

- Open mSupply Version: `V2.3.0-RC9-b`
- Legacy mSupply Central Server Version: `V7.17.10`

- Platform: Tablet (apk)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #5155 

# 👩🏻‍💻 What does this PR do?

Updated the `Autocomplete` component within `PatientSearchInput` to use the `value` prop instead of the defaultValue prop. This change effectively converts the `Autocomplete` component to a controlled component, which aligns with our desired behaviour.

https://github.com/user-attachments/assets/67d7d79f-2ba9-4bc8-9db7-b2d9586c70a8

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to Dispensary -> Prescriptions
- [ ] Create a prescription for a patient
- [ ] Go to Dispensary -> Patients
- [ ] Change the patient's first name for testing purposes
- [ ] Go back to the prescriptions window -> you can see the change in the overall view but not when clicking on a specific prescription
- [ ] Consistencies!

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/host/src/components/Sync/SyncModal.tsx [hunk 1]
```diff
@@ -140,8 +140,8 @@ export const SyncModal = ({
           <Typography sx={{ paddingBottom: 2, fontSize: 12, maxWidth: 650 }}>
             {t('sync-info.summary')
               .split('\n')
-              .map(line => (
-                <div>{line}</div>
+              .map((line, index) => (
+                <div key={index}>{line}</div>
```
Comment (GeronimoJohn) [inline client/packages/host/src/components/Sync/SyncModal.tsx:144]: Side Quest! Have added a key to this div to get rid of the error below

Screenshot 2025-01-20 at 4 00 20 PM

**Review by noel-yeldos — APPROVED** [review]
Nice, LGTM!
