### PR TITLE
filter master list by store id

### LINKED ISSUE #7850: Master Lists that are not set to be visible in a store still show up in that store
## What went wrong? 😲

In OG, my store only has visibility to 4 Master Lists: 

Image

However, when I log into my store in omSupply, under Catalogue -> Master Lists I can see all Master Lists

Image

## Expected behaviour 🤔

Should only show Master Lists that have visibility set for this store in OG mSupply

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to OG mSupply -> Special -> Stores -> your store
2. Go to Master Lists and take note of which ones are visible to your store
3. If none, tick a few options
4. Now, log into your omSupply store -> go to Catalogue -> Master Lists
5. Note _all_ master lists are showing, not only the ones you made visible

## Your environment 🌱

- Open mSupply Version: `V2.8.0-RC1`
- Legacy mSupply Central Server Version: `V8.02.02`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #7850 #7852 

# 👩🏻‍💻 What does this PR do?

Filter Master List with the Store ID. Before the filtering, it would either show all of the Master List or none at all, depending on the page that you're in. 

_**Master List Page**_
Screenshot 2025-05-27 at 4 47 52 PM

_**Item's Master List Tab**_
Screenshot 2025-05-27 at 4 47 58 PM

## 💌 Any notes for the reviewer?

# 🧪 Testing

**_Check in OG mSupply what Master List you have turned on for the Store_**
- [ ] Navigate to Catalogue -> Master List
- [ ] List should match what you've selected in OG
- [ ] Navigate to Catalogue -> Items -> Select an Item -> Master List Tab
- [ ] Should render the Master List that is related to the Item

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx [hunk 1]
```diff
@@ -13,26 +13,29 @@ import {
   createQueryParamsStore,
   TooltipTextCell,
   useTranslation,
+  useAuthContext,
 } from '@openmsupply-client/common';
 
 const MasterListsTable = ({ itemId }: { itemId?: string }) => {
+  const t = useTranslation();
+  const { store } = useAuthContext();
```
Comment (GeronimoJohn) [inline client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx:21]: Side Quest: Move `useTranslation` hook to the top. It's an import hook, but not essential for understanding the component’s main business logic

File: client/packages/system/src/MasterList/ListView/ListView.tsx [hunk 2]
```diff
@@ -10,29 +10,39 @@ import {
   createQueryParamsStore,
   useUrlQueryParams,
   TooltipTextCell,
+  useAuthContext,
 } from '@openmsupply-client/common';
 import { Toolbar } from './Toolbar';
 import { AppBarButtons } from './AppBarButtons';
 import { MasterListRowFragment, useMasterLists } from '../api';
 
 const MasterListComponent: FC = () => {
```
Comment (roxy-dao) [inline client/packages/system/src/MasterList/ListView/ListView.tsx:19]: Just a side quest... but can you remove FC? No longer supported in React 18~

**Review by roxy-dao — APPROVED** [review]
Thanks John~!

File: client/packages/system/src/MasterList/ListView/ListView.tsx (hunk 2 above)
Comment (GeronimoJohn) [reply client/packages/system/src/MasterList/ListView/ListView.tsx]: Done~ https://github.com/msupply-foundation/open-msupply/pull/7909/commits/f803486bfadf448d87e2c04649a476f32383e2a3

Comment (roxy-dao) [reply client/packages/system/src/MasterList/ListView/ListView.tsx]: Thanks!
