### PR TITLE
3927 ccei / gaps] transferring a cce between stores creates duplicate cce

### LINKED ISSUE #3927: [CCEI / GAPS] Transferring a CCE between Stores creates duplicate CCE
## What went wrong? 😲
 
If central-oms allows to assign store to an equipment, I understand that equipment can be moved from one site to another. 
If I move an equipment from one site to another, shouldn't it disappear from list in previous site?

## Expected behaviour 🤔
If I move an equipment from one site to another,  it should disappear from list in previous site and now only exist in the new chosen site

## How to Reproduce 🔨
Steps to reproduce the behaviour:

1. Have sync setup with at least two oms-sites
2. Create a equipment in siteA and assign locationA.
3. Sync
4. In central-oms, view that.
5. Change its store to siteB's and sync
6. On siteB, you can see that equipment.
7. On siteA, sync and See 1st error: the equipment still exists.
8. On central-oms, at this point, the equipment's store is storeB
9. From siteA, assign location sth like locationA2 and sync
10. On central-oms, see 2nd error: now the equipment's store is changed to storeA automatically

And hey, one more: On central-oms, when you assign equipment's store, why is it showing whole list of mSupply stores? Shouldn't that list be filtered; only show eligible ones, like vaccine-stores who actually store equipments? (that's the store-pref needed for Equipments after all) 

## Your environment 🌱

- Open mSupply Version: v2.0.0 exe
- Legacy mSupply Central Server Version: v7-14-02

- Platform: server exe + browser(chrome)

- Database type: sqlite

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3927

# 👩🏻‍💻 What does this PR do?
Creates two changelogs if an asset has been moved from one store to another from central server. One changelog to update the existing record, and another to delete the record at the original site where it was added.

P.S. I should update the integration tests but I think they're failing badly right now, so gonna avoid that hornet 👀 sorry

# 🧪 Testing

NOTE SYNC BEFORE MOVING TO A DIFFERENT SITE AND SYNC AT THE DIFFERENT SITE TOO
- [ ] Have 3 sites set up. 
- [ ] Create an asset in Site 2
- [ ] Go to Central server and change this asset to a store in Site 3
- [ ] Go back to Site 2, sync, asset should no longer be visible in UI
- [ ] Go to Site 3, sync, asset should be visible
- [ ] Now go to Central and move asset back to site 2. Sync
- [ ] Go to Site 3 - shouldn't see asset
- [ ] Go to Site 2 - should see asset

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/asset/update.rs [hunk 1]
```diff
@@ -106,38 +112,33 @@ pub fn validate(
 
     // Check asset number is unique (on this site)
     if let Some(asset_number) = &input.asset_number {
-        if check_asset_number_exists(connection, &asset_number, Some(input.id.clone()))?.len() >= 1
+        if !check_asset_number_exists(connection, asset_number, Some(input.id.clone()))?.is_empty()
```
Comment (roxy-dao) [inline server/service/src/asset/update.rs]: Sidequests here... just some refactoring

File: server/service/src/asset/update.rs [hunk 2]
```diff
@@ -163,6 +164,7 @@ pub fn generate(
     }: UpdateAsset,
     mut asset_row: AssetRow,
 ) -> AssetRow {
+    asset_row.deleted_datetime = None;
```
Comment (roxy-dao) [inline server/service/src/asset/update.rs]: Set this to null anytime it's updated to ensure that the record isn't lost when moved back to a store. We use a separate method to delete...

File: server/service/src/asset/update.rs [hunk 3]
```diff
@@ -202,9 +200,8 @@ pub fn generate(
         asset_row.warranty_end = warranty_end.value;
     }
 
-    if let Some(needs_replacement) = needs_replacement {
-        asset_row.needs_replacement = Some(needs_replacement);
-    }
+    asset_row.properties = properties;
```
Comment (roxy-dao) [inline server/service/src/asset/update.rs]: More side quest refactoring...
