### PR TITLE
#4884 Vax config age range improvement

### LINKED ISSUE #4884: Vaccine course - Issue filling Age Range for doses
## What went wrong? 😲

When creating a new Vaccine Course, if you try to edit the age range starting with 'From age' the field won't accept any number smaller than the 'To age'. This causes a problem when the default value for 'To age' is pre-filled with 0Y 2M.

Considering the design, the user is lead to start filling the form by 'From age', but with this restriction, for now the user needs to edit 'To age' first.

For example, if the interval is supposed to be "From age" = 5Y ", To age"= 10Y, the only way to make it work is inputting 10Y first. See video below:

https://github.com/user-attachments/assets/32bea7b8-08b4-48a7-bdca-b9437d2b0194

If not done in this order, the system will not accept the number 5Y, as the default value for 'To age' is 0Y 2M
Screenshot 2024-09-26 at 4 19 49 PM

## Expected behaviour 🤔

If 'To age' < ' From age', error message appears.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Programs' >Immunisations
2. Click on 'Add Vaccine course'
3. Scroll down to '+ Dose'
4. Try typing 'From age' = 3Y 
5. See error

## Your environment 🌱

- Open mSupply Version: V2.3.RC1
- Legacy mSupply Central Server Version: V7.17

- Platform: Desktop app

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #4884 (sort of)

# 👩🏻‍💻 What does this PR do?

All it does currently is:
- remove the min/max constraints
- set the new min default to the previous dose maximum

I had started to add some additional constraints (max must be more than min, doses can't overlap), but have stopped that for now for two reasons:

- we're probably going to update this UI anyway, as per #4928, which would make this unnecessary for now
- I encountered a limitation of the `useBufferState` hook, where it doesn't update the local state value if the external data has been *reverted* to it's existing value after a user input change. So we'd need to either change this, or find a way to pass the *full* data set into the cell so we can compare rows within the cell.

# 🧪 Testing

- [ ] Can change min age value without being constrained by the current max
- [ ] Ranges can overlap (obviously this is not what we want, but solution to that will be done elsewhere)

### CODE REVIEW

File: client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx [hunk 1]
```diff
@@ -261,8 +261,8 @@ const VaccineCourseDoseTable = ({
           __typename: 'VaccineCourseDoseNode',
           id: FnUtils.generateUUID(),
           label: `${courseName} ${doses.length + 1}`,
-          minAgeMonths: (previousDose?.minAgeMonths ?? 0) + 1,
-          maxAgeMonths: (previousDose?.minAgeMonths ?? 0) + 2,
+          minAgeMonths: previousDose?.maxAgeMonths ?? 0,
+          maxAgeMonths: (previousDose?.maxAgeMonths ?? 0) + 1,
```
Comment (lache-melvin) [inline client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx:265]: I wonder whether this would be more a helpful default... so if the first range was 0-6mnths, next would be 6-12, rather than 6-7?
```ts
  const addDose = () => {
    const previousDose = doses[doses.length - 1];

    const previousMin = previousDose?.minAgeMonths ?? 0;
    const previousMax = previousDose?.maxAgeMonths ?? 0;
    const previousRange = previousMax - previousMin;

    updatePatch({
      vaccineCourseDoses: [
        ...doses,
        {
          __typename: 'VaccineCourseDoseNode',
          id: FnUtils.generateUUID(),
          label: `${courseName} ${doses.length + 1}`,
          minAgeMonths: previousMax,
          maxAgeMonths: previousMax + (previousRange || 1),
          minIntervalDays: previousDose?.minIntervalDays ?? 30,
        },
      ],
    });
  };
```

**Review by lache-melvin — COMMENTED** [review]
Thanks for fixing this Carl - let me know what you think of the defaults.. otherwise happy to merge 🙏

File: client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx (hunk 1 above)
Comment (CarlosNZ) [reply client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx]: Yeah, sure. Hard to know for sure without knowing real-world cases, but this seems reasonable: 8cdd1b7520

**Review by lache-melvin — APPROVED** [review]
ship it 🚀
