### PR TITLE
6597 navigate after not scheduling encounter

### LINKED ISSUE #6597: Continue navigation after opting not to schedule next encounter
## What went wrong? 😲

If I make a change to an encounter, and then click a link somewhere to navigate to another page, I get prompted to mark the encounter as visited:

Image

If I click "Keep as Pending" then I navigate away fine, but if I click "Mark as Visited", I get prompted to schedule the next encounter.

Image

I might not want to schedule the next encounter here though, so I click Cancel. This results on me staying on the encounter page, despite the fact that I was trying to navigate.

## Expected behaviour 🤔

I am navigated away after clicking Cancel

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Edit a `Pending` encounter
2. Navigate away
3. See prompt to mark as visited -  click mark as visited
4. See prompt to schedule next encounter
5. Click Cancel
6. Issue: I stay on encounter rather than redirecting.

## Your environment 🌱

- Open mSupply Version: 2.6 rc1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #6597

# 👩🏻‍💻 What does this PR do?

Per issue - continues navigation away from current page when you cancel the schedule next encounter modal after marking encounter as visited.

Pulls the save with status change hook out into own file bc that component was getting ungodly. wanted to do more refactor but i restrained 🙈 

## 💌 Any notes for the reviewer?

It's spaghetti, but I think would be a pretty big refactor to get something cleaner, which doesn't feel like a good thing to do during RC... could make refactor issue to improve this component/page?

Given I pulled the hook out, may or may not be easier to review commit by commit :)

# 🧪 Testing

- [ ] Create a vaccine program encounter
- [ ] Give a dose
- [ ] Navigate to a new page 
- [ ] You are prompted to mark as visited - Click Mark as Visited
- [ ] You are prompted to schedule next encounter - click cancel
- [ ] You are navigated to the new page you tried to go to

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalContext.ts [hunk 1]
```diff
@@ -9,7 +9,9 @@ export interface ConfirmationModalState {
   iconType?: IconType;
   buttonLabel?: string | undefined;
   cancelButtonLabel?: string | undefined;
-  onConfirm?: (() => void) | (() => Promise<void>);
+  onConfirm?:
+    | ((state: ConfirmationModalState) => void)
+    | ((state: ConfirmationModalState) => Promise<void>);
```
Comment (lache-melvin) [inline client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalContext.ts:14]: Give the onConfirm call access to the rest of the confirmation state if needed - used this to pass "onCancel" through to the subsequent modal..

File: client/packages/system/src/Encounter/DetailView/DetailView.tsx [hunk 2]
```diff
@@ -59,97 +56,6 @@ const getPatientBreadcrumbSuffix = (
   return encounter.patient.id;
 };
 
-/**
-+ * Updates the status and once the status has been updated saves the encounter
-+ */
-const useSaveWithStatus = (
```
Comment (lache-melvin) [inline client/packages/system/src/Encounter/DetailView/DetailView.tsx:65]: moved to own file

File: client/packages/system/src/Encounter/DetailView/DetailView.tsx [hunk 3]
```diff
@@ -244,16 +150,19 @@ export const DetailView: FC = () => {
   } = useSaveWithStatusChange(
     saveData,
     data as unknown as EncounterSchema,
-    updateEncounter,
-    nextEncounterModal.toggleOn
```
Comment (lache-melvin) [inline client/packages/system/src/Encounter/DetailView/DetailView.tsx:248]: Changed this openModal call from being another param to this hook, to being a callback of `saveWithStatusChange`, see below

File: client/packages/system/src/Encounter/DetailView/DetailView.tsx [hunk 4]
```diff
@@ -244,16 +150,19 @@ export const DetailView: FC = () => {
...
   const promptToMarkVisitedOnLeaving = useConfirmationModal({
     title: t('heading.are-you-sure'),
     message: t('messages.mark-as-visited'),
     cancelButtonLabel: t('label.leave-as-pending'),
     buttonLabel: t('label.mark-as-visited'),
-    onConfirm: () => saveWithStatusChange(EncounterNodeStatus.Visited),
+    onConfirm: ({ onCancel }) => {
+      saveWithStatusChange(EncounterNodeStatus.Visited, () =>
+        nextEncounterModal.onOpen({ onCancel })
+      );
```
Comment (lache-melvin) [inline client/packages/system/src/Encounter/DetailView/DetailView.tsx:164]: Callback here passes through the `onCancel` for prompt-on-leaving... which is to continue the navigation

File: client/packages/system/src/Encounter/DetailView/useSaveWithStatusChange.tsx [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+
+  const { Modal, hideDialog, showDialog } = useDialog({
+    disableBackdrop: true,
+  });
+
+  useEffect(() => {
+    if (!!saveStatus && saveStatus.status === encounterData?.status) {
+      onSave();
+      if (saveStatus.status === EncounterNodeStatus.Visited)
+        saveStatus.callback();
```
Comment (lache-melvin) [inline client/packages/system/src/Encounter/DetailView/useSaveWithStatusChange.tsx:46]: this is the key change

**Review by Chris-Petty — APPROVED** [review]
Frankly spaghetti gonna spaghetti I don't have deep thoughts on the code here... works as described though!
