### PR TITLE
1820 [Deployment Feedback] View Stock - sorting per dates seem to sort months only

### LINKED ISSUE #1820: [Deployment Feedback] View Stock - sorting per dates seem to sort months only
## What went wrong? 😲

In **View stock**, a user wanted to find expired stock (oldest expiry dates in stock) in this case 03/2023. 
They sorted the column Expiry date BUT the stocklines expiring in 03/2023 were at row 10 or 11 in the list. At row 1 was a stockline expiring in 01/2024. 
So it seems that sorting the column only sorts months but doesn't take in consideration years. I could not check but this issue may be present in other areas where sorting per dates is enabled. It is confusing because a user will trust the sorting process and not double check that the 1st line is actually the oldest expiry date. 

## Expected behaviour 🤔

When sorting expiry dates column per date, the oldest date should appear first in the list.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Add different stocklines with various expiry dates including expired dates in a stocktake
2. Click on View stock
3. Sort the column expiry dates per dates

## Your environment 🌱

 - Version: Open mSupply v1.1.13 (version before May 22nd)
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [X] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)
 
@richardmoizeau

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1820

# 👩🏻‍💻 What does this PR do? 
The sort value was checking the formatted date which was MM/YYYY, so if you have same month but different year it will sort by month first, e.g. 06/2022, 06/2023, 07/2022, so this PR removes the formatter to fix the stocktake, inbound, outbound, and prescription expiry date sorting. 

Screenshot 2023-11-03 at 01 25 26

# 🧪 How has/should this change been tested? 
- [ ] Have items with an various expiry dates (note: make some have the same month but different year)
- [ ] Go into any of the above sections and try to sort by expiry date.
- [ ] Dates should sort correctly now

### CODE REVIEW

**Review by mark-prins — APPROVED** [review]
👍 I was misled by the issue which says the `View Stock` is the problem; but that list is fine.

Tested and working 🙏

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 1]
```diff
@@ -137,16 +136,14 @@ export const useStocktakeColumns = ({
             if ('lines' in row) {
               const { lines } = row;
               const expiryDate =
-                ArrayUtils.ifTheSameElseDefault(lines, 'expiryDate', null) ??
-                '';
-              return (
-                (expiryDate && Formatter.expiryDate(new Date(expiryDate))) ||
-                t('multiple')
-              );
+                ArrayUtils.ifTheSameElseDefault(
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:139]: I've noticed that the method `getStocktakeReasons` is calling a hook, which is naughty!
I would suggest adding something [like this](https://github.com/openmsupply/open-msupply/compare/2429-Change-Formatter.naiveDateTime-to-Formatter.toISOString...2429-Change-Formatter.naiveDateTime-to-Formatter.toISOString(hook-usage))
