### PR TITLE
#7993 Change Forecasting field to match new UI

### LINKED ISSUE #7993: "Forecasting" plugin field appears incorrectly in new Internal Order detail modal
## What went wrong? 😲

Since the Internal Order modal has been given a UI facelift, the additional fields added via plugin are not appearing in the correct place:

image

## Expected behaviour 🤔

Plugin field should be part of the main data fields section

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Install "Forecasting plugins"
2. Go to Internal Order, click an order, open a line in modal -- note incorrect field placement

## Your environment 🌱

- Open mSupply Version: 2.8.0
- Platform: Browser

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #7993 (& #7998 & #8024)

# 👩🏻‍💻 What does this PR do?

Fixes the "Forecasting" front-end plugin to show the detail field in the new-look UI:

Screenshot 2025-06-04 at 12 27 55 PM

You will need the latest version of the plugin on branch "handle-doses-and-units-correctly" in the [open-msupply-forecasting-plugins](https://github.com/msupply-foundation/open-msupply-forecasting-plugins/pull/3) repo.

## 💌 Any notes for the reviewer?

I'm assuming we're only going to show the forecast amount in Units (for now), which is what the back-end is working in, so I've hard-coded those values into the `ValueInfoRow` props.

# 🧪 Testing

- [ ] Install latest version of plugins from the above branch (for front-end can use either development src, or compiled `bundle.json`
- [ ] Go to Internal Orders -> Click an order -> Click a line
- [ ] Observe "Forecasting quanity" info is in the correct place (as in screenshot above)
- [ ] When there is no forecast quantity (e.g. non-vaccine items, or not configured), both the table column and the modal field should display "-" for the value
- [ ] Check the forecast value appears correctly in list when adding an item (or deleting and re-adding), as per #8024

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/plugins/api/hooks/usePluginData.ts [hunk 1]
```diff
@@ -26,7 +34,7 @@ export const usePluginData = ({ pluginCode, filter }: PluginDataProps) => {
   };
 
   const { data, isError, isLoading } = useQuery({
-    queryKey: [PLUGIN_DATA, storeId, pluginCode],
+    queryKey: [PLUGIN_DATA, storeId, pluginCode, queryKey],
```
Comment (CarlosNZ) [inline client/packages/plugins/api/hooks/usePluginData.ts:37]: I realised that we needed a way to invalidate the query for individual items, so added a `queryKey` prop to this hook. I'm using it to pass in the line ID for the individual item modal view. Otherwise, the query wasn't fetching the new value when going directly to the next item with "OK and Next".

**Review by jmbrunskill — APPROVED** [review]
Looks good. Field's displaying correctly.

However...

I'm still not getting my remote store forecasts. Will re-test when you finish the other plugin updates. Maybe still something wrong with my setup...

**Review by jmbrunskill — APPROVED** [review]
Looks good, just check my merged changed before merging
