### PR TITLE
3276 delete duplicate name store joins on merge

### LINKED ISSUE #3276: Two different lines of same name in suppliers list after merge on cloud
## What went wrong? 😲
 
Two different lines of same name in suppliers list after merge on cloud.
Since it looks bad (having two suppliers of same names in a list); I'm calling this High severity!

## Expected behaviour 🤔
After merge, merged names should show up as one

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have two different names visible to your oms-store first
2. Merge them on desktop cloud
3. Sync
4. See the suppliers list
5. See error: two different lines of same name. 
image
Note that in other transactions, merge looks good though; the merge-effect can be seen in transaction names! Maybe a simple UI bug? 

## Your environment 🌱

- Version: v1.7-rc2 exe
- mSupply version: v713-beta22

- Platform: 

- Database type: sqlite

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #3276 

# 👩🏻‍💻 What does this PR do? 
 

When names are merged, this makes sure that name_store_joins that are effectively duplicates are deleted.

# 🧪 How has/should this change been tested? 

- [ ] mSupply central/primary server
- [ ] OMS remote with 2 stores which are not visible to each other
- [ ] Create 3 customers
- [ ] Make them all visible to store1 and only the 3rd visible to store2. Sync.
- [ ] Merge customers 3 and 2 and sync. customer 3 is no longer visible to both stores. customer 2 is now visible to store2.
- [ ] Merge customers 2 and 1 and sync. 2 is no longer visible. 1 is now visible to both stores.
- [ ] Merge the last remaining customer into a store active on the site and sync. When logged into that store, the store itself doesn't appear in the customer list. Store2 sees Store1 as a customer now.

## 💌 Any notes for the reviewer?

You must sync with each merge until [#3441](https://github.com/msupply-foundation/open-msupply/issues/3441) is done. Otherwise earlier merges will override later merges. e.g.

Create 3 customers, then merge 3->2->1 and THEN sync. The remote site will still have 3 visible, as the later merge overrode it in the buffer.

### CODE REVIEW

File: server/repository/src/mock/name_store_join.rs [hunk 1]
```diff
@@ -2,16 +2,6 @@ use crate::NameStoreJoinRow;
 
 use super::{mock_name_a, mock_name_store_a, mock_name_store_b, program_master_list_store};
 
-pub fn mock_name_store_join_a() -> NameStoreJoinRow {
```
Comment (Chris-Petty) [inline server/repository/src/mock/name_store_join.rs:5]: Invalid mock data ;) seems no test was relying on it.

File: server/graphql/general/src/queries/store.rs [hunk 2]
```diff
@@ -138,6 +138,7 @@ impl StoreFilterInput {
         StoreFilter {
             id: id.map(EqualFilter::from),
             code: code.map(StringFilter::from),
+            name_id: None,
```
Comment (clemens-msupply) [inline server/graphql/general/src/queries/store.rs:141]: Nit: Tending to exclude this `id` filter if not need...

File: server/repository/src/mock/name_store_join.rs (hunk 1 above)
Comment (clemens-msupply) [reply server/repository/src/mock/name_store_join.rs:5]: why was it invalid? or just unused?

Nit: mock names start with mock_name_store_join_b() now...

File: server/service/src/sync/translations/special/name_merge.rs [hunk 3]
```diff
@@ -56,7 +60,57 @@ impl SyncTranslation for NameMergeTranslation {
             })
             .collect();
 
-        Ok(Some(IntegrationRecords::from_upserts(upsert_records)))
+        let name_store_join_repo = NameStoreJoinRepository::new(connection);
+        let name_store_joins_for_delete = name_store_join_repo.query(Some(
+            NameStoreJoinFilter::new().name_id(EqualFilter::equal_to(&data.merge_id_to_delete)),
+        ))?;
+        let name_store_joins_for_keep = name_store_join_repo.query(Some(
+            NameStoreJoinFilter::new().name_id(EqualFilter::equal_to(&data.merge_id_to_keep)),
```
Comment (clemens-msupply) [inline server/service/src/sync/translations/special/name_merge.rs:68]: Nit: there is also `query_by_filter` if you want to avoid wrapping it into an Option

File: server/service/src/sync/translations/special/name_merge.rs [hunk 4]
```diff
@@ -56,7 +60,57 @@ impl SyncTranslation for NameMergeTranslation {
...
+        if let Some(store) = store {
+            name_store_joins_for_delete.iter().for_each(|nsj_delete| {
+                if nsj_delete.name_store_join.store_id == store.store_row.id {
+                    deletes.push(PullDeleteRecord {
+                        id: nsj_delete.name_store_join.id.clone(),
+                        table: PullDeleteRecordTable::NameStoreJoin,
+                    });
+                }
+            });
+        }
```
Comment (clemens-msupply) [inline server/service/src/sync/translations/special/name_merge.rs:111]: Found it hard to understand when you have two loops. For example, would it be possible to add the same nsj_delete to the `delete` Vec twice? (no but its hard to see)


To avoid it you could do it in a single filter_map():
```rust
let deletes = name_store_joins_for_delete
            .iter()
            .filter_map(|nsj_delete| {
                // delete nsj_delete if it points to the store that belongs to the "keep" name
                if let Some(store) = &store {
                    if nsj_delete.name_store_join.store_id == store.store_row.id {
                        return Some(PullDeleteRecord {
                            id: nsj_delete.name_store_join.id.clone(),
                            table: PullDeleteRecordTable::NameStoreJoin,
                        });
                    }
                }

                // delete dublicates
                if name_store_joins_for_keep.iter().any(|nsj_keep| {
                    nsj_keep.name_store_join.store_id == nsj_delete.name_store_join.store_id
                }) {
                    return Some(PullDeleteRecord {
                        id: nsj_delete.name_store_join.id.clone(),
                        table: PullDeleteRecordTable::NameStoreJoin,
                    });
                }

                None
            })
            .collect::<Vec<_>>();
```

File: server/service/src/sync/translations/special/name_merge.rs [hunk 5]
```diff
@@ -158,5 +210,87 @@ mod tests {
...
+                ))
+                .unwrap()
+                .len()
+        };
+
+        // Ensure the test data is what was expected as when written
+        assert_eq!(count_name_store_join(&"name_a"), 3);
+        assert_eq!(count_name_store_join(&"name2"), 1);
+        assert_eq!(count_name_store_join(&"name3"), 2);
+        assert_eq!(count_name_store_join(&"name_store_a"), 1);
```
Comment (clemens-msupply) [inline server/service/src/sync/translations/special/name_merge.rs:246]: Nice, but you could include a check that they all point to store_a :)

**Review by clemens-msupply — CHANGES_REQUESTED** [review]
Looks good, just one change request: thinks it makes it clearer to handle both delete cases in a single loop...

File: server/service/src/sync/translations/special/name_merge.rs [hunk 6]
```diff
@@ -56,7 +60,57 @@ impl SyncTranslation for NameMergeTranslation {
...
+
+        // Situation B:
+        // storeK.name_id == nameK.id
+        // storeK joined to nameD
+        // nameD merged into nameK
+        // storeK joined to nameK (delete the join before this happens, stores shouldn't be visible to themselves)
+        let store_repo = StoreRepository::new(connection);
+        let store_filter =
+            StoreFilter::new().name_id(EqualFilter::equal_to(&data.merge_id_to_keep));
+        let store = store_repo.query_one(store_filter)?;
```
Comment (roxy-dao) [inline server/service/src/sync/translations/special/name_merge.rs:100]: This is only being used here... can it be 
```
let store = StoreRepository::new(connection).query_one(StoreFilter::new().name_id(EqualFilter::equal_to(&data.merge_id_to_keep));
```
?

File: server/repository/src/mock/name_store_join.rs (hunk 1 above)
Comment (roxy-dao) [reply server/repository/src/mock/name_store_join.rs:5]: I vote for rename so it starts with a()~

Comment (Chris-Petty) [reply server/repository/src/mock/name_store_join.rs:5]: Not sure what rename is being requested?

The reason it's invalid is because stores shouldn't have an NSJ that points to itself. Least a store becomes a customer/supplier of itself.

File: server/graphql/general/src/queries/store.rs (hunk 2 above)
Comment (Chris-Petty) [reply server/graphql/general/src/queries/store.rs:141]: Sorry how do you exclude? Compiler was annoyed with me for not specifying it.

File: server/service/src/sync/translations/special/name_merge.rs (hunk 3 above)
Comment (Chris-Petty) [reply server/service/src/sync/translations/special/name_merge.rs:68]: shot 76278e8e4233

File: server/graphql/general/src/queries/store.rs (hunk 2 above)
Comment (Chris-Petty) [reply server/graphql/general/src/queries/store.rs:141]: I could do `..Default::default()` but seems verbose? And if adding more filters in the future it might make us miss it in gql without the compiler complaining?

File: server/repository/src/mock/name_store_join.rs (hunk 1 above)
Comment (roxy-dao) [reply server/repository/src/mock/name_store_join.rs:5]: rename join_b -> join_a() so it does starts in order D:

File: server/service/src/sync/translations/special/name_merge.rs (hunk 6 above)
Comment (Chris-Petty) [reply server/service/src/sync/translations/special/name_merge.rs]: It was hang over from when I did several queries and I thought it was more readable so kept it - though I'm inconsistent in the PR elsewhere.

Actually the formatter handles it nicely haha. f0c2bade134c

File: server/service/src/sync/translations/special/name_merge.rs (hunk 4 above)
Comment (Chris-Petty) [reply server/service/src/sync/translations/special/name_merge.rs:130]: Heh I actually tried reading how to use filter_map but found it confusing to get the syntax right as I've never used it before. So perhaps more readable if familiar with the esoteric rust dozens of [built in methods](https://doc.rust-lang.org/std/iter/trait.Iterator.html#provided-methods) that exist on `Iter` alone? 😛 

I actually like it though looks neat! Thanks. Just whinging about there always being 10 different ways to shave a yak in rust. Golang gang 🔫 🔫 🔫 🔫 🔫

Comment (Chris-Petty) [reply server/service/src/sync/translations/special/name_merge.rs:130]: Hmmm this might get gross now I've added an upsert too lol

File: server/graphql/general/src/queries/store.rs (hunk 2 above)
Comment (clemens-msupply) [reply server/graphql/general/src/queries/store.rs:141]: sorry I read it wrong all good

File: server/service/src/sync/translations/special/name_merge.rs (hunk 4 above)
Comment (clemens-msupply) [reply server/service/src/sync/translations/special/name_merge.rs:130]: yeah agree too many ways to do things. These methods also don't work well with async and handling Result is also a bit "magic"...

You can still merge it in the for_each() though, i.e. only iterate the `name_store_joins_for_delete` once

File: server/repository/src/mock/name_store_join.rs (hunk 1 above)
Comment (Chris-Petty) [reply server/repository/src/mock/name_store_join.rs:5]: 68f4266343ea deal with it lol 🤣

Comment (Chris-Petty) [reply server/repository/src/mock/name_store_join.rs:5]: my final offer is to just name them "join_1()" and so on lol.

File: server/service/src/sync/translations/special/name_merge.rs [hunk 7]
```diff
@@ -56,7 +60,89 @@ impl SyncTranslation for NameMergeTranslation {
...
+                }) {
+                    // We must also consider nsj_delete.name_is_customer and nsj_delete.name_is_supplier.
+                    // The remaining NSJ that we keep must logically OR each of these fields with the corresponding field in the deleted NSJs.
+                    // We prefer making the name visible to stores rather than losing visibility as it allows users to still make invoices and orders
+                    if (!nsj_keep.name_store_join.name_is_customer
+                        && nsj_keep.name_store_join.name_is_customer)
+                        || (!nsj_keep.name_store_join.name_is_supplier
+                            && nsj_keep.name_store_join.name_is_supplier)
+                    {
+                        upserts.push(PullUpsertRecord::NameStoreJoin(NameStoreJoinRow {
```
Comment (Chris-Petty) [inline server/service/src/sync/translations/special/name_merge.rs:124]: @clemens-msupply I personally feel I have done something illegal by having a `Vec.push()` side effect in the map function lol.

Comment (clemens-msupply) [reply server/service/src/sync/translations/special/name_merge.rs:124]: Oh yeah good point :) Alternative is to just fall back to a simple for loop. Main thing for me was to only iterate `name_store_joins_for_delete` once to make it clear items are not deleted twice...

**Review by clemens-msupply — APPROVED** [review]

File: server/service/src/sync/translations/special/name_merge.rs (hunk 5 above)
Comment (Chris-Petty) [reply server/service/src/sync/translations/special/name_merge.rs:278]: I'm not sure what you mean? name_store_a is store_a? You mean `name_store_join.store_id == "store_a"`? In that last case, there are actually couple others in the data set. I should test that on the outcome too I am being a little lazy...

```
SELECT nsj.store_id, nsj.id, nl.id, nl.name_id, name.name, name.id   FROM name_store_join nsj 
JOIN name_link nl ON nl.id = nsj.name_link_id
JOIN name ON name.id = nl.name_id
ORDER BY name.id
```

| store_id                     | id                                 | id                            | name_id                       | name                     | id                            |
| ---------------------------- | ---------------------------------- | ----------------------------- | ----------------------------- | ------------------------ | ----------------------------- |
| mock_test_name_query_store_2 | mock_name_1_join_id                | name1                         | name1                         | name_1                   | name1                         |
| store_c                      | name_linked_to_store_a_id          | name_linked_to_store_a_id     | name_linked_to_store_a_id     | Name linked to store a   | name_linked_to_store_a_id     |
| store_a                      | name_linked_to_store_id            | name_linked_to_store_id       | name_linked_to_store_id       | Name linked to store     | name_linked_to_store_id       |
| store_c                      | name_not_linked_to_store_a_id      | name_not_linked_to_store_a_id | name_not_linked_to_store_a_id | Name not linked to store | name_not_linked_to_store_a_id |
| store_a                      | name_not_linked_to_store_id        | name_not_linked_to_store_id   | name_not_linked_to_store_id   | Name not linked to store | name_not_linked_to_store_id   |
| store_a                      | mock_name_store_join_d             | name_a                        | name_store_a                  | Store A                  | name_store_a                  |
| store_c                      | mock_name_store_join_e             | name_a                        | name_store_a                  | Store A                  | name_store_a                  |
| program_master_list_store    | mock_name_store_master_list_join_a | name_store_a                  | name_store_a                  | Store A                  | name_store_a                  |
| mock_test_name_query_store_1 | mock_name_2_join_id                | name2                         | name_store_a                  | Store A                  | name_store_a                  |
| mock_test_name_query_store_2 | mock_name_3_join2_id               | name3                         | name_store_a                  | Store A                  | name_store_a                  |
| store_a                      | name_store_join_b                  | name_store_b                  | name_store_b                  | Store B                  | name_store_b                  |
| program_master_list_store    | mock_name_store_master_list_join_b | name_store_b                  | name_store_b                  | Store B                  | name_store_b                  |
| store_a                      | name_store_join_c                  | name_store_c                  | name_store_c                  | Store C                  | name_store_c                  |
| mock_test_name_query_store_1 | name_a_umlaut_join_id              | name_äÄ_umlaut                | name_äÄ_umlaut                | a*umlaut*äÄ_name         | name_äÄ_umlaut                |
| store_a                      | mock_patient_store_join_b          | patient2                      | patient2                      | patient2                 | patient2                      |
| store_a                      | mock_patient_store_join            | testId                        | testId                        | testId                   | testId                        |


One thing I've realised is to be precise it'd be nice to be able to just test `try_translate_pull_merge` outputs the right `IntegrationRecords`... should I do that today? Haha

File: server/service/src/sync/translations/special/name_merge.rs (hunk 7 above)
Comment (Chris-Petty) [reply server/service/src/sync/translations/special/name_merge.rs:124]: Yea I think that is a solid win from the filter_map. I'm happy with it as it is now though if you are.

File: server/service/src/sync/translations/special/name_merge.rs (hunk 5 above)
Comment (clemens-msupply) [reply server/service/src/sync/translations/special/name_merge.rs:278]: Oh yes sorry, they not all point to the same store (which wouldn't make any sense). It's just a bit hard to see that this data matches the test cases described above.

What we did before is to just inject new test specific data that is tailored to the current test case.
