### PR TITLE
7605 Add fallback to handle undefined value - fix crash on backspace NewStocklineModal

### LINKED ISSUE #7540: Available SOH shouldn't be on `New Stock` modal
## What went wrong? 😲
When adding new stock the focus is on available packs and when you input, save button doesn't enable.
https://github.com/user-attachments/assets/a287e5b1-7d70-4d54-9b33-d0796404c72f

## Expected behaviour 🤔
Available packs should only be available as a read-only component in the list view and detail view, since it is an indicator of how many packs you have minus any reserved in invoices. 

Remove this input from the new stock modal.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> View Stock
2. Click `New Stock` button
3. See focus is on `Available (packs)` 
4. If you enter a number in `Available (packs)` the Save button does not enable

## Your environment 🌱

- Open mSupply Version: 2.7
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### LINKED ISSUE #7605: omSupply crashes when backspacing in Inventory Adjustments
## What went wrong? 😲

When creating an Inventory Adjustment and backspacing (without entering any values, just backspacing straight away), the app/browser/apk crash

Error: 

Image

Video: 

Attached [here](https://drive.google.com/drive/folders/17spetJvjiiGtX4Z6yYIA1bjjpp6bB5dI)

## Expected behaviour 🤔

Should not crash

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> View Stock -> New Stock
2. Choose an item that has 0 stock
3. It will autofocus on Available (packs)
4. Backspace -> the page will crash

## Your environment 🌱

- Open mSupply Version: V2.7.1
- Legacy mSupply Central Server Version: V8.1.13

- Platform: happens on all platforms - Google Chrome (Mac) and Galaxy Tab A8 (apk)

- Database type: PostgreSQL & SQLite3

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #7605 fixes #7540

# 👩🏻‍💻 What does this PR do?

- Add fallback value for totalNumberOfPacks so that undefined value does not throw error
- Remove available packs input field

EDIT - after requested changes
Available packs field still available on stock detail view but not in new stockline modal

Screenshot 2025-05-07 at 09 25 40

Screenshot 2025-05-07 at 09 25 25

## 💌 Any notes for the reviewer?

~~I haven't applied the fix to the available packs field -> it seems redundant to add code that will only get removed later. We should also remove the available packs field as requested here #7540 but not sure if that needs to go into 2.7.1. I don't see why not~~

# 🧪 Testing

- [ ] Go to Inventory -> View Stock -> New Stock
- [ ] Choose an item that has 0 stock
- [ ] Autofocus on Pack Qty
- [ ] Enter an amount in Pack Qty
- [ ] Remove amount completely by backspacing 
- [ ] See that app does not crash

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Stock/Components/StockLineForm.tsx [hunk 1]
```diff
@@ -108,27 +108,17 @@ export const StockLineForm: FC<StockLineFormProps> = ({
...
+                    ? parseFloat(draft.totalNumberOfPacks.toFixed(2))
+                    : 0
+                }
                 onChange={totalNumberOfPacks =>
                   onUpdate({ totalNumberOfPacks })
                 }
               />
             }
           />
-          <StyledInputRow
```
Comment (noel-yeldos) [inline client/packages/system/src/Stock/Components/StockLineForm.tsx:118]: Addresses #7540

Comment (lache-melvin) [reply client/packages/system/src/Stock/Components/StockLineForm.tsx:118]: Available packs still needs to be available on the stock detail page, just not in the new stock line form 🙏

File: client/packages/system/src/Stock/Components/StockLineForm.tsx [hunk 2]
```diff
@@ -108,27 +108,17 @@ export const StockLineForm: FC<StockLineFormProps> = ({
                 autoFocus
                 disabled={!packEditable}
                 width={160}
-                value={parseFloat(draft.totalNumberOfPacks.toFixed(2))}
+                value={
+                  draft.totalNumberOfPacks
+                    ? parseFloat(draft.totalNumberOfPacks.toFixed(2))
+                    : 0
```
Comment (lache-melvin) [inline client/packages/system/src/Stock/Components/StockLineForm.tsx:114]: 🚀

File: client/packages/common/src/intl/utils/DateUtils.test.ts [hunk 3]
```diff
@@ -15,38 +15,43 @@ describe('useFormatDateTime', () => {
 });
 
 describe('getDisplayAge', () => {
+  jest.useFakeTimers().setSystemTime(new Date('2025-10-01'));
```
Comment (lache-melvin) [inline client/packages/common/src/intl/utils/DateUtils.test.ts:18]: Hm, assuming these changes went in because you branched off develop but now merging into RC? 

No worries for this one, just test changes so not concerned about them going in, but worth double checking when you branch 🤓

**Review by lache-melvin — CHANGES_REQUESTED** [review]

File: client/packages/common/src/intl/utils/DateUtils.test.ts (hunk 3 above)
Comment (noel-yeldos) [reply client/packages/common/src/intl/utils/DateUtils.test.ts:18]: @lache-melvin I branched off 2.7.1 and saw that tests were failing. Checked in with Carl and realised that the fix for the tests went into develop. Carl suggested just copying the changes across in this PR.

Comment (lache-melvin) [reply client/packages/common/src/intl/utils/DateUtils.test.ts:18]: Ah awesome, thanks for explaining 🚀

File: client/packages/system/src/Stock/Components/StockLineForm.tsx (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/system/src/Stock/Components/StockLineForm.tsx:118]: Thanks for catching that! Updated here cf82fe3f532d30203180daba1ac1d23861376149

Comment (lache-melvin) [reply client/packages/system/src/Stock/Components/StockLineForm.tsx:118]: Niiice 🎉  one last request...

This works, but `isInModal` is a display based prop, rather than a use case based prop. Currently we only have the two places this form is used, but it's good to treat it as though it might be used in more places. I think it makes more sense to say "we only show available packs, in cases where the number of packs is not editable. Available packs will always be readonly".

In that case, could we update to:

```tsx
 {!packEditable && (
            <StyledInputRow
              label={t('label.available-packs')}
              Input={
                <NumericTextInput
                  autoFocus
                  disabled
                  ...
```

Then good to go 🙏

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Just requesting the different prop used, then ready to ship 🔥

File: client/packages/system/src/Stock/Components/StockLineForm.tsx (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/system/src/Stock/Components/StockLineForm.tsx:118]: @lache-melvin ah I see, thank you for explaining that! I didn't think about it from the multiple use case perspective. Good learning 🙏 

Updated here 6b994c7d5dd090369727e08c638cc5670d01181f

**Review by lache-melvin — APPROVED** [review]
🚀
