### PR TITLE
6700 Update column arrangement encounters

### LINKED ISSUE #6700: Encounter status column is not visible when side menu is opened
## What went wrong? 😲

With the side menu/navigation panel opened, status column in Encounters practically disappears -> if all encounters are marked as `Visited`, you cannot tell the column is there due to the short length of the text string

Video attached ->>> [here](https://drive.google.com/drive/folders/1QpeGJQ5C48OOoSQeQXBQ9uIiGV8vfbrg)

## Expected behaviour 🤔

Can we shrink the `Additional Info` column a little bit so `Status` can fit in nicely too?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure you have Immunization Programs and Vaccination Card enabled for your store
2. Schedule a few encounter for your patients - have a few that are scheduled, and a few that are visited
3. Once saved, go to the encounter list view and note with the side menu closed, you can see the status column
4. Expand the menu navigation panel -> the column is almost invisible
5. Only the ones with the `Scheduled` status appear on screen as you can read the first few letters

## Your environment 🌱

- Open mSupply Version: `V2.6.0-RC3`
- Legacy mSupply Central Server Version: `V8.00.11`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #6700 

# 👩🏻‍💻 What does this PR do?
Update column arrangement for encounters list view. Move status column to the left of additional info. Reduce width of additional info column.

Screenshot 2025-03-14 at 17 22 02

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Make sure you have Immunization Programs and Vaccination Card enabled for your store
- [ ] Schedule a few encounter for your patients - have a few that are scheduled, and a few that are visited
- [ ] Once saved, go to the encounter list view 
- [ ] Observe that status column is moved to the left of additional info column
- [ ] Observe that additional info column width is reduced

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Encounter/ListView/columns.ts [hunk 1]
```diff
@@ -92,21 +92,21 @@ export const useEncounterListColumns = ({
...
-    sortable: false,
-    accessor: additionalInfoAccessor,
-    Cell: ChipTableCell,
-    minWidth: 400,
-  });
   columnList.push({
     key: 'effectiveStatus',
     label: 'label.status',
     sortable: false,
     align: ColumnAlign.Right,
```
Comment (aimee-mcneil-melville) [inline client/packages/system/src/Encounter/ListView/columns.ts:99]: NIT:  The right alignment on the Status column - with the rearrangement I personally would find Status as a left aligned column to look neater

Screenshot 2025-03-18 at 11 51 07 AM

**Review by aimee-mcneil-melville — APPROVED** [review]
Great! Works well, it would take some very unusually long names in order to push the last column off the screen

nit just something to consider, not necessary to action 😄

File: client/packages/system/src/Encounter/ListView/columns.ts (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/system/src/Encounter/ListView/columns.ts]: @aimee-mcneil-melville I agree! It does look neater. I've actually just removed the alignment altogether and it looks like it defaults to left aligned (other columns don't have any alignment set). Updated here: 51ae3e77718e0d770f1aad5776240599d28bada9

**Review by aimee-mcneil-melville — APPROVED** [review]
Lovely!
