### PR TITLE
4991 add report loading messages for rc

### LINKED ISSUE #4991: Reports initially render very slow and without loading indicators
## What went wrong? 😲

First time rendering reports looks like this:
https://github.com/user-attachments/assets/77c81a99-413d-4d1c-9fa0-8e63f4f3da9a

Subsequent reports are faster... but i still think loading indication would help!

## Expected behaviour 🤔

At least let me know the report is coming, rather than `not found` 😢 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. On APK, generate a report
2. Watch and wait 😁 

## Your environment 🌱

- Open mSupply Version: v2.3.0 RC5
- Legacy mSupply Central Server Version:

- Platform: APK

- Database type:

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #4991 for RC build

# 👩🏻‍💻 What does this PR do?

Adds loading messages for when report is slow to load

## 💌 Any notes for the reviewer?

# 🧪 Testing

Go to reports
Set throttling high
Load report and see spinner

- [ ] _(e.g.)_ Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] _(e.g.)_ This sample datafile: _google drive link_
- [ ] _(e.g.)_ Open a requisition with some lines
- [ ] _(e.g.)_ Make a couple invoices supplying some amount of those lines
- [ ] _(e.g.)_ Review that "issued" column is the sum of the amount already issued in invoices for this requisition

# 📃 Documentation

- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

### CODE REVIEW

File: client/packages/reports/src/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -180,14 +189,24 @@ const DetailViewInner = ({
...
-        <NothingHere body={errorMessage} />
+      {reportLoading && (
+        <BasicSpinner messageKey="messages.loading-report"></BasicSpinner>
+      )}
+      {fileId ? (
+        <iframe
+          src={url}
+          width="100%"
+          style={{ borderWidth: 0 }}
+          onLoad={loaded}
```
Comment (jmbrunskill) [inline client/packages/reports/src/DetailView/DetailView.tsx:206]:
```suggestion
          onLoad={() => {
            setReportLoading(false);
          }}
```
The `loaded` function was a bit confusing to me, feels like this would be clearer? But I'm ok with how it is if you disagree.

File: client/packages/common/src/intl/locales/en/common.json [hunk 2]
```diff
@@ -695,5 +695,23 @@
...
+  "title.stock-line-details": "Stock Line Details",
+  "title.stock-on-hand": "Available Stock",
+  "tools": "Tools",
+  "tooltip.import-fridge-tag": "Import Berlinger Fridge-tag and Q-tag log files. A sensor will be created, if necessary, for each log file imported.",
+  "warning.cannot-create-placeholder-packs": "There is a total of {{allocatedQuantity}} packs available. Unable to allocate all {{requestedQuantity}} packs.",
+  "warning.cannot-create-placeholder-units": "There is a total of {{allocatedQuantity}} units available. Unable to allocate all {{requestedQuantity}} units.",
+  "warning.caps-lock": "Warning: Caps lock is on",
+  "warning.field-not-parsed": "{{field}} not parsed",
+  "warning.nothing-to-supply": "Nothing left to supply!",
+  "messages.loading-report": "Loading report..."
```
Comment (jmbrunskill) [inline client/packages/common/src/intl/locales/en/common.json:716]: I think this is the only line we added right? Can you remove the others? Not a major as I assume they've been added in another branch?

**Review by jmbrunskill — APPROVED** [review]
Working great Ferg. A couple of suggestions but merge when you're ready.

File: client/packages/reports/src/DetailView/DetailView.tsx (hunk 1 above)
Comment (fergie-nz) [reply client/packages/reports/src/DetailView/DetailView.tsx:206]: Agree! I like your suggestion better also
