### PR TITLE
5733 remove numeric input mode for number inputs

### LINKED ISSUE #5733: Can't enter negative numbers on Samsung tablet
## What went wrong? 😲

Can't enter negative numbers in R&R fields on tablet, even though the field accepts negative (i.e. on browser)

This is because Samsung numeric keyboard doesn't have a `-` key!!

## Expected behaviour 🤔

Can enter negative numbers

## How to Reproduce 🔨

Steps to reproduce the behaviour:

- On samsung tablet
- try to enter negative number in R&R form `Adjustments` columns
- Can't!

## Your environment 🌱

- Open mSupply Version: v.2.3.4
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #5733

# 👩🏻‍💻 What does this PR do?

Couldn't enter negative values in R&R forms on samsung tablet!

This PR switches back to alphanumeric keyboard, so users have access to the `-` key as needed.

## 💌 Any notes for the reviewer?

R&R form and demographic growth rates are the only two places where we allow entering negative values... it feels a shame to remove the simplicity of the numeric keyboard everywhere for these two cases?

Considered something like `inputMode = allowNegative ? "text" : "numeric"` - but this was quite ick as you clicked through negative and non-negative fields in the R&R form. Probably best just to be consistent, but curious for thoughts! 😢 

Other interim solution for demo has been to install Gboard app, and set this as default keyboard. This keyboard has `-` key and allows us to keep the numeric keyboard. But I don't think this is a feasible option long term...

May we keep an eye out for the inevitable update where the `-` comes back!

# 🧪 Testing

- [ ] On Samsung tablet
- [ ] Have R&R form
- [ ] Edit a row 
  - [ ] Non-negative fields, like quantity received, you still can't make negative
  - [ ] Adjustments field, you can type a negative number

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx [hunk 1]
```diff
@@ -273,7 +275,6 @@ export const NumericTextInput = React.forwardRef<
           },
           ...sx,
         }}
-        inputMode="numeric"
```
Comment (jmbrunskill) [inline client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx:276]: Could this be based on the `allowNegative` bool?
Feels like it might be an ok trade off? Or maybe that's just a weird ui thing?

Personally I'm ok with always seeing the whole keyboard, but would require switching to number mode to enter numbers which is a bit of a slow down...

**Review by jmbrunskill — COMMENTED** [review]
I feel like we need some use feedback on this one, I imagine having numeric inputs at least for things like stock take where we need to enter lots of numbers is probably important???

File: client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx (hunk 1 above)
Comment (jmbrunskill) [reply client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx:276]: Sorry that's what you said you didn't like :( Need to read the PR properly first !

Comment (jmbrunskill) [reply client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx:276]: Maybe yet another prop to control this so we can limit it just to R&R forms for now?

**Comment by lache-melvin** [comment]
@jmbrunskill have updated to your suggestion, alphanumeric keyboard on the R&R form but keep the number pad elsewhere 🙏

**Review by jmbrunskill — APPROVED** [review]
Looks great, thanks Lache!
