### PR TITLE
5780 inbound Shipment table does not show total cost

### LINKED ISSUE #5780: Inbound Shipment table does not show total cost
## What went wrong? 😲

Inbound Shipment table/list: inbound shipment only display unit sell price, but not the total sell price (required by customer)

and label should clearly say whether it is sell price or cost price ?

## Expected behaviour 🤔

should have a column showing the total cost (next to the unit sell price)

## How to Reproduce 🔨

Create a new inbound shipment

## Your environment 🌱

- Open mSupply Version: 2.1 (but checked 2.4 and same issue)
- Legacy mSupply Central Server Version:

- Platform: Chrome

- Database type:

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #5780

# 👩🏻‍💻 What does this PR do?

Added a new column to display the total price for each row in Inbound Shipments. Improved the wording to clarify whether the price value is a Cost Price or a Sell Price: Cost Price for inbound shipments and Sell Price for outbound shipments.

### Inbound Shipment Changes

Screenshot 2025-01-08 at 9 03 05 AM

Screenshot 2025-01-08 at 9 03 39 AM

### Outbound Shipment Changes

Screenshot 2025-01-08 at 9 02 48 AM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Visit any existing inbound shipment
- [ ] Verify that the total price value of a row is displayed.
- [ ] Confirm that `Cost per unit` text has been changed to `Cost Price`.
- [ ] Visit any existing outbound shipment
- [ ] Verify that the total price value of a row is displayed.
- [ ] Confirm that `Unit Price` text has been changed to `Sell Price`.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/invoices/src/OutboundShipment/DetailView/columns.ts [hunk 1]
```diff
@@ -218,7 +218,7 @@ export const useOutboundColumns = ({
       },
     ],
     {
-      label: 'label.unit-price',
+      label: 'label.sell-price',
```
Comment (lache-melvin) [inline client/packages/invoices/src/OutboundShipment/DetailView/columns.ts:221]: I think including a description that this is per unit would be helpful, e.g. this example:

Pack sell price is $5.50:

Screenshot 2025-01-07 at 4 43 43 PM

File: client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts [hunk 2]
```diff
@@ -202,7 +216,7 @@ export const useInboundShipmentColumns = () => {
         },
       ],
       {
-        label: 'label.cost-per-unit',
+        label: 'label.cost-price',
```
Comment (lache-melvin) [inline client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts:219]: same here, i think per unit is helpful

File: client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts [hunk 3]
```diff
@@ -202,7 +216,7 @@ export const useInboundShipmentColumns = () => {
...
         key: 'costPricePerUnit',
         align: ColumnAlign.Right,
         width: 120,
```
Comment (lache-melvin) [inline client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts:222]: Not your changes but i think should fix, cost price looks right when group by item is on:
Screenshot 2025-01-07 at 4 48 32 PM

But wrong when its off!
Screenshot 2025-01-07 at 4 48 37 PM

**Review by lache-melvin — DISMISSED** [review]
Looking good! just a couple little fixes :)

**Review by lache-melvin — APPROVED** [review]
Epic thank you!
