### PR TITLE
3475 restarting server and refreshing causes user login error and potentially blocks user 

### LINKED ISSUE #3475: Restarting server and refreshing causes User Login Error and potentially blocks user...
## What went wrong? 😲

image

## Expected behaviour 🤔

If we need to relogin then the system should tell us, or maybe it should just skip refreshing the User if the credentials are not available after a restart

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Login to mSupply and go to the sync page
2. Restart your server
3. Refresh the page
4. Click Sync

## Your environment 🌱

- Version: 1.7.00

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3475

# 👩🏻‍💻 What does this PR do?
1. Gives a better error message telling the user to log out if the credentials don't match/are gone
2. Update cookies with new permissions / store preferences so that they are reflected immediately instead of on refresh

## 💌 Any notes for the reviewer?

# 🧪 Testing
Testing for permission/preferences updates
- [ ] Login
- [ ] Go to `Sync page
- [ ] Update some user permissions (like admin maybe since it's obvious) or store preferences
- [ ] Sync
- [ ] Should be able to do whatever perms/preferences were given

Error testing: 
- [ ] Login
- [ ] Go to `Sync` page
- [ ] Restart server
- [ ] Press sync button
- [ ] Should see error message telling user to log out

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Screenshot of new error message? Or maybe not needed idk
  3.

### CODE REVIEW

File: client/packages/common/src/authentication/AuthContext.tsx [hunk 1]
```diff
@@ -138,6 +144,13 @@ export const AuthProvider: FC<PropsWithChildrenOnly> = ({ children }) => {
     setCookie(newCookie);
   };
 
+  const {
```
Comment (roxy-dao) [inline client/packages/common/src/authentication/AuthContext.tsx:147]: Moved this to AuthContext for better access to cookie so that the expiry doesn't get overwritten or disappear!

File: client/packages/common/src/authentication/api/hooks/useLogin.ts [hunk 2]
```diff
@@ -58,6 +58,27 @@ const getMostRecentCredentials = (
   return [];
 };
 
+// returns MRU store, if set
+// or the first store in the list
+export const getStore = async (
```
Comment (roxy-dao) [inline client/packages/common/src/authentication/api/hooks/useLogin.ts:63]: Moved out of login function, so that store preferences could be updated when a user is updated

File: client/packages/common/src/intl/locales/en/common.json [hunk 3]
```diff
@@ -78,6 +78,7 @@
   "error.date_maxDate": "Date value is too large",
   "error.date_minDate": "Date value is too low",
   "error.general-query-error": "There was an error communicating with the server 😢",
+  "error.invalid-credentials": "Unable to fetch user details. Please re-login to update user details.",
```
Comment (roxy-dao) [inline client/packages/common/src/intl/locales/en/common.json:81]: Honestly would prefer to have the user log out straight away if updating fails since it's easy to ignore a message... but shouldn't happen in production often... more likely to happen in development with constantly server restarts and branch changes

**Review by jmbrunskill — CHANGES_REQUESTED** [review]
I was still able to lock myself out after your changes sadly...
Overall it looks pretty good, but I think if we don't have the user's password, we shouldn't even try to update the user.
Here's my suggestion branch.

https://github.com/msupply-foundation/open-msupply/compare/3475-Restarting-server-and-refreshing-causes-User-Login-Error-and-potentially-blocks-user-...3475_suggestion

The main thing is just skipping the user account update if the password is missing...

I also didn't seem to see the message consistently.

I think you're right if the user's credentials are wrong, we should log them out.
However, of they are just `missing` due to a server restart we should just skip the user update (maybe with a error message)

File: client/packages/common/src/authentication/hooks/useUpdateUserInfo.ts [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+      try {
+        const update = await updateUser();
+
+        if (update.__typename === 'UpdateUserNode') {
+          const permissions = await getUserPermissions(
+            cookie?.token,
+            cookie?.store
+          );
+          const userDetails = await getUserDetails(cookie?.token);
+          const store = await getStore(userDetails, mostRecentCredentials);
```
[the remark this answers is not in the document]
Comment (roxy-dao) [reply client/packages/common/src/authentication/hooks/useUpdateUserInfo.ts:41]: No it's just using the existing function, the default store should still be the same

**Review by jmbrunskill — APPROVED** [review]
Looks good, tested the user update thing and that's working too.
Left hand draw doesn't update but I think that's expected...

**Comment by roxy-dao** [comment]
> Looks good, tested the user update thing and that's working too. Left hand draw doesn't update but I think that's expected...

Not expected, some of those are store prefs so will check in another issue ;x 

Thanks James!
