### PR TITLE
#9706 Fix table date filters

### LINKED ISSUE #9706: Date range filter not working or infinite load for cold chain equipments
## What went wrong? 😲

It never retrieves records when you apply date range filter, i.e. I have applied installation date from and to date where I could see my CCE item belongs to that range.  It displays an console error message 

>>  Failed to parse "NaiveDate": trailing input while parsing "DateFilterInput"
(occurred while parsing "AssetFilterInput")
Uncaught TypeError: Right-hand side of 'instanceof' is not an object

## Expected behaviour 🤔

 * [ ] **G.4.2** The results update within 2 seconds for normal datasets.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold chain and click equipments
2. Click on upload CCE items (optional, if you don't have CCE) > https://drive.google.com/file/d/1MoDULBhEOVRWJ43pAXZQXaFByB9Q6CO4/view?usp=drive_link
3. Apply filter from date 2013-07-01 to date 2013-07-31
https://www.loom.com/share/6e1a8cfd113f43b7be6d0887070cd291
https://drive.google.com/file/d/1MdZxltxx8ZEsdptyF7z0LyoBrG2_HJSj/view?usp=sharing

## Your environment 🌱

- Open mSupply Version: 2.12.00-develop-11051748
- Legacy mSupply Central Server Version:

- Platform:

- Database type:PostgreSQL

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #9706  (Note: issue number incorrect in branch name, sorry)

# 👩🏻‍💻 What does this PR do?

Turns out that some GraphQL endpoints require the date filters to be "naive" date strings (e.g. "2025-11-10") rather than the typical "date-time" ISO strings. But when we did the new tables, we'd assumed they were all ISO strings as we hadn't come across any other the type yet.

Fix is to add an additional `dateFilterFormat` property to column definintions, and when this value is set to "date" (as opposed to the default "date-time") then the filter handler (in `useTableFiltering`) will update the URL with just a date rather than a date-time value.

## 💌 Any notes for the reviewer?

There are probably more places affected by this, I've just done the ones noted in the original issue. I'll announce to the dev chat to keep an eye out for others.

# 🧪 Testing

- [ ] Test all the table date filters mentioned in the original issue (and comment) -- confirm they behave as expected

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts [hunk 1]
```diff
@@ -17,8 +17,8 @@ export const useAssets = () => {
       { key: 'notes' },
       { key: 'model' },
       { key: 'assetNumber' },
-      { key: 'installationDate', condition: 'equalTo' },
-      { key: 'replacementDate', condition: 'equalTo' },
+      { key: 'installationDate', condition: 'between' },
+      { key: 'replacementDate', condition: 'between' },
```
Comment (CarlosNZ) [inline client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts]: Couple of these filter definitions were wrong too

File: client/packages/common/src/ui/layout/tables/material-react-table/useTableFiltering.ts [hunk 2]
```diff
@@ -37,32 +37,43 @@ export const useTableFiltering = <T extends MRT_RowData>(
   const filterUpdaters = useMemo(() => {
     const filterUpdaters: Record<string, (value: any) => void> = {};
 
-    columns.forEach(({ filterKey, id, accessorKey, filterVariant }) => {
```
Comment (CarlosNZ) [inline client/packages/common/src/ui/layout/tables/material-react-table/useTableFiltering.ts]: Review with "Ignore whitespace changes" enabled to see more easily the actual changes.
