### PR TITLE
6941 stock with decimals rounding

### LINKED ISSUE #6941: Problem of rounding off figures in stock
## NOTE:

**This has been re-opened, for ongoing discussion of decimal quantities that don't round nicely. Please see below comments.**

## What went wrong? 😲

There is a decimal problem in the stock display.  
The first screen shoot shows a quantity of 6.800000000000001.

Image

The second shows a quantity of 19.099999999999994.

Image

I think this happens after a dose of vaccine is delivered in the dispensary (but not for all vaccines and after every dispensation).

## Expected behaviour 🤔

Rounding must be to the second decimal place.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Dispense a new dose in Dispensary. (choose a Patient, add an encounter in the past, save and click on one vaccine to dispense, Dispense it)
2.  Go to 'Inventory', 'View Stock' 
3. The error is not found for all vaccines and for all dispensations. 

## Your environment 🌱

- Open mSupply Version: 2.6.00 Demo
- Legacy mSupply Central Server Version: N/A

- Platform: Mac 

- Database type: 

@richardmoizeau

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Partially Fixes #6941

# 👩🏻‍💻 What does this PR do?

Cells displaying numbers to show a tooltip with the unrounded value. This required a combination of adding NumberCell where needed, and removing overrides that rounded but prevented the default tooltip behaviour

I didn't make any changes where only whole packs could be used eg Inbound Shipments

The tooltip is formatted with regional settings 
Screenshot 2025-07-10 at 12 31 11 PM

Inventory -> View Stock -> List View (doses on)
https://github.com/user-attachments/assets/8ea058dc-c523-4d1d-abaf-b23c52ddf86f

Inventory -> View Stock -> List View (doses off)
Screenshot 2025-07-15 at 12 15 47 PM

Inventory -> View Stock -> Ledger tab
Screenshot 2025-07-10 at 12 38 20 PM

Inventory -> Stocktake -> Detail View
Screenshot 2025-07-10 at 12 45 39 PM

Catalogue -> Items -> Ledger tab
https://github.com/user-attachments/assets/d6ea75b9-ef96-4dcc-ac96-fbad36a3e00e

Replenishment -> Supplier Return Line Edit
Screenshot 2025-07-10 at 12 48 40 PM

Prescription -> Line Edit View (doses on)
Screenshot 2025-07-15 at 1 37 45 PM

Prescription -> Line Edit View (doses off)
Tooltips only when hovering over the number, not the whole string
Screenshot 2025-07-15 at 12 17 09 PM

## 💌 Any notes for the reviewer?

@mark-prins can I have feedback on the following please:
Values that may have decimals but aren't a Cell - should these be handled in the same way? eg Prescription line edit view?
Screenshot 2025-07-10 at 2 02 21 PM

Have commented on original issue re tooltip rounding, and currency tooltip, can come in a follow up PR
https://github.com/msupply-foundation/open-msupply/issues/6941#issuecomment-3054594263

# 🧪 Testing

- [ ] Have a vaccine item with a number of doses and units per pack that will create a long decimals if one dose is given eg. I used 3 doses per unit, 7 units per pack
- [ ] Prescribe one dose of the vaccine
- [ ] Use this item where changes have been made, see tooltip with decimals and rounding in the cell with ellipses
- [ ] Change language -> see where regional settings have `,` or `.` as the separator, the tooltip matches

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Comment by mark-prins** [comment]
> Values that may have decimals but aren't a Cell - should these be handled in the same way? eg Prescription line edit view?

@aimee-mcneil-melville yes, these should be rounded as well please

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx [hunk 1]
```diff
@@ -248,6 +248,9 @@ export const useStocktakeColumns = ({
       key: 'difference',
       label: 'label.difference',
       align: ColumnAlign.Right,
+      Cell: props => (
+        <NumberCell {...props} defaultValue={UNDEFINED_STRING_VALUE} />
+      ),
```
Comment (roxy-dao) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx:253]: You can't make this a number cell since it returns a string ;x

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks Aimee~
Just gotta fix one thing (:

File: client/packages/common/src/ui/layout/tables/columns/DifferenceColumn.tsx [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+    (rowData.countedNumberOfPacks ?? rowData.snapshotNumberOfPacks) -
+    rowData.snapshotNumberOfPacks;
+  const totalInDoses =
+    displayDoses && rowData.item.doses
+      ? total * (rowData.packSize ?? 1) * rowData.item.doses
+      : null;
+  return { displayDoses, total, totalInDoses };
+};
+
+export const getDifferenceColumn = (
```
Comment (roxy-dao) [inline client/packages/common/src/ui/layout/tables/columns/DifferenceColumn.tsx:55]: Nice~

File: client/packages/common/src/ui/layout/tables/columns/DifferenceColumn.tsx [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+        sx={{
+          display: 'flex',
+          alignItems: 'center',
+          justifyContent: 'flex-end',
+          width: '100%',
+        }}
+      >
+        <NumberCell {...props} />
+        {displayDoses && !!totalInDoses && (
+          <Typography sx={{ marginLeft: 1 }}>
```
Comment (roxy-dao) [inline client/packages/common/src/ui/layout/tables/columns/DifferenceColumn.tsx:85]: Too much spacing between the diff and doses 👀 

```suggestion
          <Typography>
```

**Review by roxy-dao — APPROVED** [review]
Thanks Aimee~ just one change and some comments should have been nice in the prescription area 😉
