### PR TITLE
2912 add timezone agnostic date time for picker

### LINKED ISSUE #2912: Date defaults to the previous day's date when selecting a DOB in the patient data picker field
## What went wrong? 😲
 

Date defaults to the previous day's date when selecting a DOB in the patient data picker field. E.g. select 26th Jan, system records 25th Jan as date. More info in linked issue: https://github.com/msupply-foundation/open-msupply-internal/issues/43

## Expected behaviour 🤔
Should choose the correct date 

## Your environment 🌱

 - Version: 
 - Platform:
   - [x] android (tablet) 
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

### PR DESCRIPTION
**Pull request by fergie-nz**
Add timezone agnostic function for datetime picker

Fixes #2912 

# 👩🏻‍💻 What does this PR do? 
Adds a function to convert date only strings to a ISO date for the start of day in users' local time rather than UTC local time.
Using normal naive date time functions caused issue when timezones behind UTC were used, which caused the date to be displayed as the previous day.

# 🧪 How has/should this change been tested? 
Go to patients -> open patient create modal or patient detail view
Change the DOB of a patient and see it show as the correct day in the modal / detail view.

## 💌 Any notes for the reviewer?
Still in draft - other use cases for date input to be added.

### CODE REVIEW

File: client/packages/common/src/intl/utils/DateUtils.ts [hunk 1]
```diff
@@ -33,13 +33,17 @@ import {
...
   setMilliseconds,
+  addMilliseconds,
 } from 'date-fns';
+import { getTimezoneOffset } from 'date-fns-tz';
 
 export const MINIMUM_EXPIRY_MONTHS = 3;
 
 const dateInputHandler = (date: Date | string | number): Date => {
+  // console.log('date input handler', date);
+  // TODO this is being called for every patient in list (it shouldn't)
```
Comment (clemens-msupply) [inline client/packages/common/src/intl/utils/DateUtils.ts:44]: This TODO doesn't make sense in a utils method... Should these two lines be removed?

File: client/packages/common/src/intl/utils/DateUtils.ts [hunk 2]
```diff
@@ -33,13 +33,17 @@ import {
...
   // Assume a string is an ISO date-time string
-  if (typeof date === 'string') return parseISO(date);
+  if (typeof date === 'string') parseISO(date);
```
Comment (clemens-msupply) [inline client/packages/common/src/intl/utils/DateUtils.ts:46]: That missing return doesn't look right...

File: client/packages/common/src/intl/utils/DateUtils.ts [hunk 3]
```diff
@@ -95,6 +99,7 @@ export const DateUtils = {
         : new Date(date);
     return isValid(maybeDate) ? maybeDate : null;
   },
+
```
Comment (clemens-msupply) [inline client/packages/common/src/intl/utils/DateUtils.ts:102]: Nit, revert new line?

File: client/yarn.lock [hunk 4]
```diff
@@ -8156,6 +8156,11 @@ dataloader@^2.2.2:
   resolved "https://registry.yarnpkg.com/dataloader/-/dataloader-2.2.2.tgz#216dc509b5abe39d43a9b9d97e6e5e473dfbe3e0"
   integrity sha512-8YnDaaf7N3k/q5HnTJVuzSyLETjoZjVmHc4AeKAzOvKHEFQKcn64OKBfzHYtE9zGjctNM7V9I0MfnUVLpi7M5g==
 
+date-fns-tz@^2.2.0:
+  version "2.0.0"
+  resolved "https://registry.yarnpkg.com/date-fns-tz/-/date-fns-tz-2.0.0.tgz#1b14c386cb8bc16fc56fe333d4fc34ae1d1099d5"
+  integrity sha512-OAtcLdB9vxSXTWHdT8b398ARImVwQMyjfYGkKD2zaGpHseG2UPHbHjXELReErZFxWdSLph3c2zOaaTyHfOhERQ==
+
```
Comment (clemens-msupply) [inline client/yarn.lock:8163]: Something is wrong with this lock file I am getting:

`Couldn't find any versions for "date-fns-tz" that matches "^2.2.0"`

For example, delete the `node_modules` directory and then try `yarn`. 

The reason is probaly that you specified 2.2.0 but 2.0.0 is the latest version...

**Review by clemens-msupply — CHANGES_REQUESTED** [review]

File: client/packages/common/src/intl/utils/DateUtils.ts [hunk 5]
```diff
@@ -195,6 +197,23 @@ export const useFormatDateTime = () => {
       : '';
   };
 
+  // this function acts in the same way as getDateOrNull, but will also convert date to start of the
+  // local datetime rather than local utc.
+  const getLocalStartOfDayFromDateOrNull = (
```
[the remark this answers is not in the document]
Comment (clemens-msupply) [reply client/packages/common/src/intl/utils/DateUtils.ts:202]: Would getLocalDate() be a better name? (The or Null is already encoded in the return type `Date | null`...)

File: client/packages/common/src/utils/formatters/formatters.test.ts [hunk 6]
```diff
@@ -48,12 +50,40 @@ describe('Formatter', () => {
...
+      localalisedStartOfDay,
+      dateFnsTz.getTimezoneOffset(timeZone, localalisedStartOfDay)
+    );
+    expect(Formatter.toIsoString(utcStartOfDay)).toBe(
+      '1984-03-13T00:00:00.000Z'
     );
+    expect(Formatter.toIsoString(null)).toBe(null);
+
+    const offsetInHours =
+      dateFnsTz.getTimezoneOffset(timeZone, new Date()) / 1000 / 60 / 60;
```
[the remark this answers is not in the document]
Comment (fergie-nz) [reply client/packages/common/src/utils/formatters/formatters.test.ts:65]: Yes I'm wondering if that is the right place to put the test for getLocalDate, or if it needs a test at all. 

I am seeing that all of the other dateUtils functions don't have tests.

I wonder if I should just remove the toIsoString test (because this will fail depending on either what timezone the test is run OR if daylight saving time changes in nz). I think this would be good regardless because it would be confusing for international collaborators.

And/or create a new test file for dateUtils which could test the functions there.

[the remark this answers is not in the document]
Comment (fergie-nz) [reply client/packages/common/src/utils/formatters/formatters.test.ts]: Have added a separate DateUtils.test.ts testing file

**Comment by fergie-nz** [comment]
I want to point out that this date picker issue will occur for a number of other datepickers.

I suspect that these are less urgent than date of birth or date of death

This one for example is for expiry of medicines:

```
            <ExpiryDateInput
              value={DateUtils.getDateOrNull(draft.expiryDate)}
              onChange={date =>
                onUpdate({ expiryDate: Formatter.naiveDate(date) })
              }
            />
```

onUpdate assumes start of UTC day from the date selected.

getDateOrNull will then convert this UTC date string to local time.

For expiry date it probably doesn't matter - because we are only showing the month (though if the user could see, it would be the day BEFORE the last day of the month in this case)

**Review by clemens-msupply — APPROVED** [review]
Thanks works fine! Only one small suggestion for the test...

**Comment by clemens-msupply** [comment]
> I want to point out that this date picker issue will occur for a number of other datepickers.
> 
> I suspect that these are less urgent than date of birth or date of death
> 
> This one for example is for expiry of medicines:
> 
> ```
>             <ExpiryDateInput
>               value={DateUtils.getDateOrNull(draft.expiryDate)}
>               onChange={date =>
>                 onUpdate({ expiryDate: Formatter.naiveDate(date) })
>               }
>             />
> ```
> 
> onUpdate assumes start of UTC day from the date selected.
> 
> getDateOrNull will then convert this UTC date string to local time.
> 
> For expiry date it probably doesn't matter - because we are only showing the month (though if the user could see, it would be the day BEFORE the last day of the month in this case)

I guess it doesn't hurt to update it anyway.

File: client/packages/common/src/intl/utils/DateUtils.ts [hunk 7]
```diff
@@ -195,6 +197,34 @@ export const useFormatDateTime = () => {
       : '';
   };
 
+  /**
+   * While getDateOrNull is naive to the timezone, the timezone will still change.
```
Comment (clemens-msupply) [inline client/packages/common/src/intl/utils/DateUtils.ts:201]: Nit, maybe a short sentence about what it does first, e.g. : 

"Converts a local date to a Date that has the same date in UTC, e.g. 2024-02-14 becomes 2024-02-14T10:00."

(was this the example problem for Cook Islands?)

File: client/packages/common/src/intl/utils/DateUtils.test.ts [hunk 8]
```diff
@@ -0,0 +1,25 @@
+import { renderHookWithProvider } from '../../utils/testing';
+import { useFormatDateTime } from './DateUtils';
+
+describe('useFormatDateTime', () => {
+  it('to be truthy', () => {
+    const truthy = true;
+    expect(truthy).toBe(true);
+  });
```
Comment (mark-prins) [inline client/packages/common/src/intl/utils/DateUtils.test.ts:8]: can remove?

**Review by mark-prins — CHANGES_REQUESTED** [review]
🎉  Works for me!
Thanks Ferg - that ended up a more complicated problem than I anticipated!
Just a tweak, and Clemens requested changes please 🙏

**Review by mark-prins — APPROVED** [review]
