### PR TITLE
9369 replace stocktake edit tables

### LINKED ISSUE #9465: App crashes when adding or opening Outbound Shipment lines
## What went wrong? 😲

When adding or opening item lines on an outbound shipment, the app crashes with an error 

Image

## Expected behaviour 🤔

Be able to add new lines to an outbound shipment, and open existing lines

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to outbound shipments -> open or create one
2. Add an item -> see error

## Your environment 🌱

- Open mSupply Version: develop 
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

Image

### PR DESCRIPTION
**Pull request by lache-melvin**
Part of #9369
Fixes #9465

# 👩🏻‍💻 What does this PR do?

Updates stocktake edit tables to new table implementation:

Screenshot 2025-10-01 at 2 45 29 PM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create a stocktake
- [ ] Add an item
- [ ] Enter stocktake data - ensure cell behaviour is as expected. Some things to look out for:
- [ ] Cells are all disabled when `count the line` is off
- [ ] Volume per pack is adjusted based on item variant + pack size
- [ ] Default sell price is cleared when pack size is changed
- [ ] Reason is cleared when `counted packs` changes to make the reason invalid (e.g. was `< snapshot`, now `> snapshot`)
- [ ] Error cells are highlighted after failed save (e.g. reason not entered, snapshot no longer up to date)

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/material-react-table/components/RequiredNumberInputCell.tsx [hunk 1]
```diff
@@ -0,0 +1,53 @@
+import React, { useState } from 'react';
```
Comment (CarlosNZ) [inline client/packages/common/src/ui/layout/tables/material-react-table/components/RequiredNumberInputCell.tsx:1]: I'm not entirely clear why we need a separate component for the "Required" version of this?

Comment (lache-melvin) [reply client/packages/common/src/ui/layout/tables/material-react-table/components/RequiredNumberInputCell.tsx:1]: The difference is using state vs buffer state - in the usual number cell, the input state can be overwritten externally. But with one we want -> clear input field, but set draft value to 1, so calculations always have a valid pack size as a base...

There's probably other ways to handle this, I just renamed to be a bit more generic than the old `PackSizeCell`... maybe can review the logic down the track?
