### PR TITLE
8574 remove default query pagination

### LINKED ISSUE #8574: Not all lines/items are available in reports
## What went wrong? 😲

Many of our standard and custom reports use graphQL queries for their data.

Most of our graphQL queries have default pagination, usually with a small limit (100 lines)

In the real world, reports are often printed for large amounts of data, easily thousands of lines.

Example bug - Standard OMS stocktake variance report was only showing first 100 lines. [Updated to use first 1000 lines here](https://github.com/msupply-foundation/open-msupply/compare/3932f6e6e0df433151bc47205221b3c639903b30...a0a9db6ec552dcfe56a53b94a5e967a74b47dce5?expand=1), as this is currently the API pagination maximum, but this is likely still to small for large stocktakes!

No workaround.

## Expected behaviour 🤔

All lines included in reports.

Probably, if no pagination is included, all lines should be returned? Or we expose Pagination::all() to graphql - need a reliable way to get all data for a report.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have big datafile - e.g. create a stocktake where you have more than 1000 stock lines
2. Print stocktake variance report
3. Only has first 1000 lines

There are probably examples still limited to first 100 lines, we tend to dev with small datafiles and not notice. I haven't done a sweep.

## Your environment 🌱

- Open mSupply Version: v2.10, but includes all prev versions using reports as well...
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### LINKED ISSUE #8729: Picked inbound shipment appears editable when pagination set to 500
## What went wrong? 😲

When pagination is increased picked inbound shipment appears editable, [see data file and screenshot here](https://drive.google.com/drive/u/1/folders/1BZuhuJ60V3fVryix-GCu56yQL9aQB7eN)

## Expected behaviour 🤔

Pagination settings should not have affects on table logic (like shades of editability etc..)

## How to Reproduce 🔨

Have lots of picked inbound shipments, change pagination to 500 (haven't tried all of the combination of statuses and pagination limits)

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### LINKED ISSUE #8765: Exporting stocktake not showing everything in the export
## What went wrong? 😲

We tried to export stocktake to a pdf and also an excel and items were missing from this. The attempted stocktake had 400 stock lines and we only had 101 stock lines come through in the excel and PDF.

Wondering if there is a problem if there are too many lines - the R&R had 150 lines earlier and it all exported fine. 

Makes it hard to get a report on stocktake with variance to see the changes in the stock quantities after a stocktake right now.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #8574
Fixes #8765
Fixes #8729

# 👩🏻‍💻 What does this PR do?

Removes pagination limits/defaults from service layer, so reports can access full report data

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Have a stocktake with hundreds of lines
- [ ] Export/print
- [ ] All lines are in the report
- [ ] Could also try a stock status report / expiring items report with more than 5000 items, see that these now show more than 5000

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/repository/src/db_diesel/filter_sort_pagination.rs [hunk 1]
```diff
@@ -369,16 +370,13 @@ pub struct Pagination {
 
 impl Default for Pagination {
     fn default() -> Self {
-        Pagination {
-            offset: 0,
-            limit: DEFAULT_PAGINATION_LIMIT,
-        }
+        Self::all()
     }
```
Comment (lache-melvin) [inline server/repository/src/db_diesel/filter_sort_pagination.rs:374]: this is the main change - using u32 max as the default pagination limit

File: standard_reports/expiring-items/latest/src/query.graphql [hunk 2]
```diff
@@ -11,7 +11,6 @@ query ExpiringItems(
       hasPacksInStore: true
       isActive: true
     }
-    page: { first: 5000 }
```
Comment (lache-melvin) [inline standard_reports/expiring-items/latest/src/query.graphql:14]: these were added to include as many items as possible - now removing so we actually get all of them

**Comment by lache-melvin** [comment]
Adding #8729 - was also a pagination problem!

**Comment by lache-melvin** [comment]
> While I think this is a good enough fix for now we are more open to easy DDoSing with massive requests. Is there a carry over issue for that somewhere?

@andreievg and I discussed, this, comfortable for now as API is closed, only accessible via auth... more open API/more integrations, starts to become more of an issue - @andreievg what's the latest location for long term carry over things like this?
