### PR TITLE
4171 remove as type usage

### LINKED ISSUE #4171: Remove the `as Type` usage in the demographics pages
Note: while cleaning up demographics page, would be great to remove the `as Type` usage - if we're needing it then we're doing something wrong with the types, and should fix that instead!

_Originally posted by @lache-melvin in https://github.com/msupply-foundation/open-msupply/issues/4075#issuecomment-2171928330_

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #4171

# 👩🏻‍💻 What does this PR do?

Cleans up a number of `as [Type]` usages throughout the Demographics page

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create some new demographic indicators
- [ ] Mess with the Growth percentages
- [ ] Everything still behaving as expected

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx [hunk 1]
```diff
@@ -75,54 +77,50 @@ const IndicatorsDemographicsComponent = () => {
...
+    Object.values(draft).forEach(row => {
       const updatedRow = calculateAcrossRow(
-        draft[row] as Row,
+        row,
         updatedHeader,
         indexPopulation
       );
       updatedDraft[updatedRow.id] = updatedRow;
     });
-    setHeaderDraft(updatedHeader);
```
Comment (lache-melvin) [inline client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx:125]: This was already done in `handleGrowthChange`, no need to do twice...

File: client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx [hunk 2]
```diff
@@ -75,54 +77,50 @@ const IndicatorsDemographicsComponent = () => {
...
       headerDraft,
       indexPopulation
     );
-    setDraft({ ...updatedDraft, [patch.id]: updatedRow });
+    setDraft({ ...draft, [patch.id]: updatedRow });
   };
 
   // generic function for handling percentage change, and then re calculating the values of that year
-  const handleGrowthChange = (patch: RecordPatch<HeaderValue>) => {
+  const handleGrowthChange = (updatedHeader: HeaderData) => {
```
Comment (lache-melvin) [inline client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx:105]: Letting the `GrowthRow` (header data management component) manage the new shape of HeaderData, just updating here

File: client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx [hunk 3]
```diff
@@ -75,54 +77,50 @@ const IndicatorsDemographicsComponent = () => {
...
 
   const setter = (patch: RecordPatch<Row>) => {
-    const updatedDraft = { ...draft };
     const percentage = !patch.percentage ? 0 : patch.percentage;
     const percentageChange = percentage != draft[patch.id]?.percentage;
 
     setIsDirty(true);
 
+    const existingRow = draft[patch.id];
+    if (!existingRow) return;
```
Comment (mark-prins) [inline client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx:86]: this would be better to have above `setIsDirty`

File: client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx [hunk 4]
```diff
@@ -209,7 +207,10 @@ const IndicatorsDemographicsComponent = () => {
 
   return (
     <>
-      <AppBarButtons patch={setter} rows={Object.values(draft)}></AppBarButtons>
+      <AppBarButtons
+        addRow={(newRow: Row) => setDraft({ ...draft, [newRow.id]: newRow })}
```
Comment (mark-prins) [inline client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx:211]: a slightly shortcutted version is possible here..
```suggestion
        addRow={newRow => setDraft({ ...draft, [newRow.id]: newRow })}
```

**Review by mark-prins — APPROVED** [review]
❤️  very nice - thanks. 
have a small suggestion re the dirty flag, which would get unnecessarily set in a certain (impossible afaik) situation

File: client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx (hunk 3 above)
Comment (lache-melvin) [reply client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx:86]: ah very true, thanks
