### PR TITLE
7997 keeps selected campaign when inbound shipment status updates

### LINKED ISSUE #7997: On confirming Delivered inbound shipments, the selected campaign is not saved to the stock take line
## What went wrong? 😲
After manually created an inbound shipment, I have selected campaign for multiple batches of the same item or a batch for a single batch of one item. 

Image

In all cases after confirming delivery and then confirmed Verified, the campaign selected for each batch were not saved to the newly created stock lines. The campaign_id field is empty.

Image

Image

It is working when assigning a campaign directly from stock line

## Expected behaviour 🤔
Campaign should be saved to stock line when confirming delivery or when verified of an inbound shipment

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Setup campaigns on oms central server. Sync your remote
1. Go to 'Inbound shipment'
2. Click on 'New Shipment'
3. Add some lines with quantities and assign a Campaign to some of your batch from the "Other table"
4. Confirm delivered and then confirm Verified
5. Go to inventory > View Stock
6. Find the stock line created for your inbound shipment batches lines
7. Open them
8. See error. The campaign you have assigned them are not there 

## Your environment 🌱

- Open mSupply Version: v2.8.0RC6
- Legacy mSupply Central Server Version: v8.2.0

- Platform: Android or Desktop

- Database type: SQLlite

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #7997 

# 👩🏻‍💻 What does this PR do?

Keeps the selected campaign on Inbound Shipments status updates

## 💌 Any notes for the reviewer?

**_More like self reflection_**
Hmm seems that `Stock line` is part of many moving components.  Few places where it gets updated. Would love to sit down at one point and just really get my head around `Stock line`

# 🧪 Testing

_**Inbound Shipment**_
- [ ] Go to 'Inbound shipment'
- [ ] Click on 'New Shipment'
- [ ] Add some lines with quantities and assign a Campaign to some of your batch from the "Other table"
- [ ] Confirm delivered and then confirm Verified
- [ ] Go to inventory > View Stock
- [ ] Find the stock line created for your inbound shipment batches lines
- [ ] Open them
- [ ] Campaign should be the same as `Inbound Shipment`

_**Stocktake**_
- [ ] Ensure that a `stock` have a `campaign` set
  - [ ] Please cover cases for `vvm status` and `donor`
- [ ] Navigate to 'Stocktake'
- [ ] Create a new 'Stocktake' and select the stock/batch with the `campaign` we just set
- [ ] Finalise `Stocktake` -> navigate back to 'View Stock'
- [ ] Ensure values didn't change

_**Outbound Shipment**_
- [ ] Create new outbound shipment to a store that is on the same site
- [ ] Add item where `campaign` have been set for it
- [ ] Issue packs for that stock
- [ ] Click Confirm Shipped button (button on bottom right)
- [ ] Navigate to the store where we requested from
- [ ] Ensure campaign is saved against the stock in that store

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Review by jmbrunskill — APPROVED** [review]
Looks good thanks John!

I really don't like destructuring then `..` pattern it's really hard to see where you might need to add this code...

**Comment by jmbrunskill** [comment]
@GeronimoJohn  does it need to be added too adjust_existing_stock too? What happens there does it loose the campaign?

Supplier/Customer returns also don't seem to use campaigns, I think that's probalby ok?

**Comment by jmbrunskill** [comment]
I feel like we maybe should add it too the invoice processors transfer invoice?
`service/src/processors/transfer/invoice/common.rs`

**Comment by jmbrunskill** [comment]
`service/src/stocktake/update/generate.rs` ? `generate_stock_in_out_or_update`
Seems like if it's needed there, we also need vvm status & donor as well?

```
            // Default
            total_before_tax: None,
            tax_percentage: None,
            donor_id: None,
            vvm_status_id: None,
            campaign_id: None,
```

I think it's ok, as it's defaulting to look up the old record in the backed but I'm not 100% sure...

File: server/service/src/invoice_line/stock_in_line/generate.rs [hunk 1]
```diff
@@ -20,7 +20,6 @@ pub struct StockLineInput {
     pub barcode_id: Option<String>,
     pub supplier_link_id: String,
     pub overwrite_stock_levels: bool,
-    pub campaign_id: Option<String>,
```
Comment (GeronimoJohn) [inline server/service/src/invoice_line/stock_in_line/generate.rs:23]: Have removed `campaign_id` from input. All of the impacted files actually use `generate_batch`, which now uses `campaign_id` from `InvoiceLineRow`

Impacted Files: 
`server/service/src/invoice/customer_return/update/generate.rs`
`server/service/src/invoice_line/inbound_shipment_from_internal_order_lines/generate.rs`
`server/service/src/invoice_line/stock_in_line/insert/generate.rs`
`server/service/src/invoice_line/stock_in_line/update/generate.rs`

**Comment by GeronimoJohn** [comment]
@jmbrunskill wondering if you could please give it another review. Bit of a code that got pushed. 

Can confirm as well that `transfer` works! Receiving store receives shipment and retains the `campaign` from the requesting store

**Review by jmbrunskill — APPROVED** [review]
Thanks John, changes look good. Haven't tested but trust you have :)

Lets get this in the next RC
