### PR TITLE
4499 expiring items report UI review 

### LINKED ISSUE #4499: Expiring items report UI review
## What went wrong? 😲

Had a look at the expiring items report, and I have some UI requests please

image

In the report arguments modal:
* can you make the label column a little wider, so that the labels aren't wrapping (in English, at least). Just making the modal width `600` would be better
* The numeric inputs look strange being not as wide as the other inputs, and right aligned. 
* The 'item code or name' input isn't as wide as the expiry date - can they be the same please
* there's more vertical space around the disabled numeric inputs - could the vertical spacing be consistent?
* It would be helpful to have a little introductory text e.g. "You can customise what is shown in the report, by specifying some of the optional details below. Click OK to view the report" is that possible? What does 'expiry date' do?

this is with width of `500` but a little tweaking of layout:

image

And some general items, most of which are noted in #4494

image

* Remove border around iframe
* Add padding to 'expiring in' chip
* Fix breadcrumb ( should show `Reports / Expiring items` with reports linking to list view )
* Add a CMD+K shortcut for reports

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4499

# 👩🏻‍💻 What does this PR do?
Added some css props to the numbers and text input to get the args modal for expiring items looking nicely without effecting other areas using the same component... The rest of the fixes asked for in the latter half of the issue has been fixed already.

Screenshot 2024-08-14 at 9 14 09 AM

# 🧪 Testing

- [ ] Have expiring reports set up (https://github.com/msupply-foundation/open-msupply-reports/pull/83)
- [ ] Click on it 
- [ ] Argument modal should look pretty now

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/programs/src/JsonForms/common/components/Date.tsx [hunk 1]
```diff
@@ -38,12 +38,7 @@ const UIComponent = (props: ControlProps) => {
 
   return (
     <DetailInputWithLabelRow
-      sx={{
-        marginTop: 0.5,
-        gap: 2,
-        minWidth: '300px',
-        justifyContent: 'space-around',
-      }}
+      sx={DefaultFormRowSx}
```
Comment (roxy-dao) [inline client/packages/programs/src/JsonForms/common/components/Date.tsx:41]: Side quest: Noticed this wasn't using default sx

File: client/packages/system/src/Report/components/ReportArgumentsModal.tsx [hunk 2]
```diff
@@ -68,17 +69,25 @@ export const ReportArgumentsModal: FC<ReportArgumentsModalProps> = ({
...
-        uiSchema={report.argumentSchema.uiSchema}
-        isError={false}
-        isLoading={false}
-        setError={err => setError(err)}
-        updateData={(newData: JsonData) => {
-          setData(newData);
-        }}
-      />
+      <>
+        <Typography
```
Comment (roxy-dao) [inline client/packages/system/src/Report/components/ReportArgumentsModal.tsx:73]: Thought it would be fine to show this on all the arg modals since it is for filtering

File: client/packages/programs/src/JsonForms/common/components/Date.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/programs/src/JsonForms/common/components/Date.tsx:41]: The Date component isn't as wide as the text input for me:

Screenshot 2024-08-16 at 9 37 57 AM

To align them I've had to do this:
```
    <DetailInputWithLabelRow
      sx={DefaultFormRowSx}
      inputSx={{
        '& > .MuiBox-root': {
          flexBasis: '90%',
          width: '100%',
        },
      }}
      label={label}
      labelWidthPercentage={FORM_LABEL_WIDTH}
      inputAlignment="start"
      Input={
        <BaseDatePickerInput
          sx={{ width: '100%' }}
...
```

that is, add the `inputSx` to the `DetailInputWithLabelRow` and the `sx` to the `BaseDatePickerInput`
which gives this pleasing view:

Screenshot 2024-08-16 at 10 06 04 AM

have checked a few other screens and I don't think it ruins anything else..

**Review by mark-prins — APPROVED** [review]
😍  so good! thanks Roxy!

I have a :nit about the date picker width, and a suggested fix - can you check that please and maybe pop that in too?
