### PR TITLE
6128 Internal order editing requested packs does not save changes

### LINKED ISSUE #6128: Internal order editing requested packs does not save changes
## What went wrong? 😲

https://github.com/user-attachments/assets/9a5028f8-bfe4-459d-8303-8c6552e5ccea

When toggled to "Packs" editing the "Requested packs" cell does not save the user's input. There is a work around where after editing the packs, toggle back and edit the "Requested quantity" and change focus, triggering a save.

## Expected behaviour 🤔

Both cells should have the same saving behaviour.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Toggle editing in packs
2. Edit requested packs
3. press next, previous, or close
4. See change was not saved

## Your environment 🌱

- Open mSupply Version: 2.5-rc3

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6128

# 👩🏻‍💻 What does this PR do?
Save requested quantity on blur if user is requesting in packs 

# 🧪 Testing

- [ ] Change toggle to packs
- [ ] Enter a quantity in requested packs
- [ ] Navigate away
- [ ] navigate back
- [ ] Should be same number

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx [hunk 1]
```diff
@@ -309,7 +309,6 @@ export const RequestLineEdit = ({
                   <InputWithLabelRow
                     Input={
                       <NumericTextInput
-                        autoFocus
```
Comment (roxy-dao) [inline client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx:312]: Removing cause we only want to auto focus first input >.>

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Create a program requisition for a store name
- [ ] Finalise Requisition
- [ ] Go to edit indicator
- [ ] Inputs should be disabled **-PASS-**
