### PR TITLE
4497 Report args modal backdrop blackening

### LINKED ISSUE #4497: Report args modal backdrop blackening
## What went wrong? 😲
Screenshot 2024-08-05 at 9 28 16 AM

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4497

# 👩🏻‍💻 What does this PR do?
Move report args out of react fragment
Screenshot 2024-08-05 at 9 30 58 AM

# 🧪 Testing

- [ ] Set up new reports from reports repo
- [ ] Click on a report to generate from the Report page
- [ ] The modal shouldn't be bugging anymore

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/reports/src/components/ReportWidget.tsx [hunk 1]
```diff
@@ -142,13 +142,13 @@ export const ReportWidget: React.FC<PropsWithChildren<ReportWidgetProps>> = ({
...
                       </Grid>
                     </Link>
-                    <ReportArgumentsModal
-                      report={reportWithArgs}
-                      onReset={() => setReportWithArgs(undefined)}
-                      onArgumentsSelected={reportArgs}
-                    />
                   </React.Fragment>
                 ))}
+                <ReportArgumentsModal
```
Comment (mark-prins) [inline client/packages/reports/src/components/ReportWidget.tsx:147]: doesn't fix it for me 😢 
Looking at the source - there are three modals showing:


image

**Review by mark-prins — COMMENTED** [review]
Still getting the issue, am looking into it

**Comment by mark-prins** [comment]
Have fixed in this [suggestion branch](https://github.com/msupply-foundation/open-msupply/compare/4497-Report-args-modal-backdrop-blackening...4497-Report-args-modal-backdrop-blackening(suggestion)).

The issue is that the modal is rendered for every `ReportWidget` component and all of these are using the same state object to determine visibility : that is, the state in the `ListView` component. when this is set with an object that has args, all of the report modals are shown. 

My suggestion is to move the modal to the ListView, so that there is only a single instance of it.

**Review by mark-prins — CHANGES_REQUESTED** [review]
Have added a suggested change

File: client/packages/reports/src/DetailView/DetailView.tsx [hunk 2]
```diff
@@ -128,6 +128,7 @@ const DetailViewInner = ({
         isPrinting={isPrinting}
       />
       <ReportArgumentsModal
+        key={report.id}
```
Comment (mark-prins) [inline client/packages/reports/src/DetailView/DetailView.tsx:131]: don't see why the `key` is necessary, or what value that adds 🤷

**Review by mark-prins — APPROVED** [review]
🙏  thanks - that does the trick

File: client/packages/reports/src/DetailView/DetailView.tsx (hunk 2 above)
Comment (CarlosNZ) [reply client/packages/reports/src/DetailView/DetailView.tsx:131]: Sorry, @mark-prins, this was from my PR (#4501 ) which I've merged into here already (I intended to wait, had an absent-minded moment).

Regarding the key:
> add a "key" to the ReportArgsModal so that it'll force a remount (and therefore data reset) when the report type (id) changes

This was because I removed a "clearData" function elsewhere and this was a way to ensure the form gets reset when the report type changes.

Comment (mark-prins) [reply client/packages/reports/src/DetailView/DetailView.tsx:131]: oh, nice! slick way to get the component to remount
