### PR TITLE
8935 cant clear expiry date

### LINKED ISSUE #8935: Unable to clear expiration dates for a stockline
## What went wrong? 😲

Unable to clear expiration dates for a stockline -> when clicking Save, you get the 'success' message however the date comes back and the refresh still shows the same

https://github.com/user-attachments/assets/ac43efab-e533-431f-8678-51430a524242

## Expected behaviour 🤔

Should be able to clear expiration dates

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> View Stock and choose an item to test with
2. Set an expiration date - either in the past or in the future
3. Save -> then try to clear it -> run into the date not clearing 

## Your environment 🌱

- Open mSupply Version: `2.10.00-RC-08181654`
- Legacy mSupply Central Server Version: `V8.04.00`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #8935

# 👩🏻‍💻 What does this PR do?

Allows saving cleared expiry date

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to View stock edit
- [ ] Have an expiry date saved on a stock line
- [ ] Clear the expiry date
- [ ] Save
- [ ] The cleared date is persisted
- [ ] Same check for stocktake line edit
- [ ] Inbound shipment line edit
- [ ] Customer return line edit

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/stocktake_line/update/mod.rs [hunk 1]
```diff
@@ -65,17 +63,6 @@ pub fn update_stocktake_line(
...
-            // Update stock line donor and item variant if changed and stock line exists
-            if let Some(mut stock_line) = existing.stock_line.clone() {
-                if let Some(donor_id) = &input.donor_id {
-                    stock_line.donor_link_id = donor_id.value.clone();
-                }
-                if let Some(item_variant_id) = &input.item_variant_id {
-                    stock_line.item_variant_id = item_variant_id.value.clone();
-                }
-                StockLineRowRepository::new(connection).upsert_one(&stock_line)?;
-            }
```
Comment (lache-melvin) [inline server/service/src/stocktake_line/update/mod.rs:77]: Found a bug while I was here - stocktake line edits were updating the stock line for these fields! This should only happen on stocktake finalisation, not while we're still in `New` status. I checked, they're being updated correctly on finalise 🙏

**Comment by lache-melvin** [comment]
@aimee-mcneil-melville ok i think this time! all those clearable fields should now apply when reducing stock 🫠

**Review by aimee-mcneil-melville — APPROVED** [review]
Awesome Laché, thanks for getting all those extra fields working too! 🤩
