### PR TITLE
3319 show actual error if no stock lines are associated with shipment lines to return

### LINKED ISSUE #3319: Unclear error when can't return lines
## What went wrong? 😲
 

Getting a please select lines to return error when i HAVE selected lines to return
Image

## Expected behaviour 🤔

The modal opens, or a more helpful error with why you can't open the modal...

## How to Reproduce 🔨

I have a hunch this is related to depending on the optional stock line field in the selected stock lines code... I thought it was always defined once the inbound shipment was marked as delivered, but apparently not? whoopsie 🙈 Either way, the error should actually reflect the problem!

Steps to reproduce the behaviour:

1. Go to a new or shipped inbound shipment
2. Mark as delivered
3. Select lines to return
4. See the warning (and if you inspect the shipment, stock lines haven't been assigned... maybe this is actually the bug?)

## Your environment 🌱

- Version: 
- mSupply version: 

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #3319

# 👩🏻‍💻 What does this PR do? 
 

This issue came about from another intermittent issue I appear to be having (#3320) where sometimes the inbound shipment lines don't have an associated stock line, which we need to generate the return.

Anyways, we were expecting the stockLine to always be present, and when it wasn't, we'd get a `please select lines to return` error even when we had selected lines. This PR shows an actual error message :)

Screenshot 2024-03-21 at 5 48 49 PM

# 🧪 How has/should this change been tested? 

Somehow set up a delivered inbound return with an invoice line with no stock_line_id (maybe just set to NULL in DB?)

- select that line to return
- see error popup

## 💌 Any notes for the reviewer?

In hindsight, I'm wondering if we should instead be sending the inbound shipment line ids to the generate method, and letting that query error if there is no associated stock line? But probably not worth the rework at this point...

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -55,17 +55,30 @@ export const DetailView: FC = () => {
...
       const selectLinesSnack = info(t('messages.select-rows-to-return'));
       selectLinesSnack();
-    } else {
-      onOpenReturns(selectedStockLineIds);
-      setReturnMode(ModalMode.Create);
+      return;
+    }
+    if (selectedLines.some(line => !line.stockLine)) {
+      console.error('No stock line associated with the selected line(s)');
+      const selectLinesSnack = error(t('error.something-wrong'));
```
Comment (lache-melvin) [inline client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx:71]: Keen for thoughts here... this isn't an error the user could do anything about, and it kind of confusing to explain... so just went with generic error, and slightly more detail to the console. Should I provide more/less anywhere?

Comment (andreievg) [reply client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx:71]: I think this would be an edge case with inbound shipments that have been created in og store.

My preference is to show to the user, we have no access to console in production, in that case I was wondering what value would console.error bring ? 

I think it's ok to show untranslated error concatenated with error.something-wrong

**Review by andreievg — APPROVED** [review]
Looks good thanks, approving but I think there should be a bit more info presented to the user.

> In hindsight, I'm wondering if we should instead be sending the inbound shipment line ids to the generate method, and letting that query error if there is no associated stock line? But probably not worth the rework at this point...

Agree, with both, nicely noted thanks

File: client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx (hunk 1 above)
Comment (lache-melvin) [reply client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx:71]: Ah ok perfect, will do :)
