### PR TITLE
4967 new encounter window appearance

### LINKED ISSUE #4967: New Encounter: improve the window appearance
## What went wrong? 😲

1. When adding a New Encounter, you cannot see the full name of the Encounter

2. The fields are not equal length/aligned

3. Too much unutilised white space on the side

4. Visit Date field is required however no indication it needs to be filled out before the entry can be saved

## Expected behaviour 🤔

1. Expected to see the full field without the text being cut off. Maybe we can extend the field a bit?
2. Standardise the field lengths to make the appearance more consistent
3. Either reduce the size of the window or extend the length of the fields a little bit which will also solve point 1
4. Ongoing in #4299 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Dispensary -> Patients`
2. Create a new patient or click on an existing one
3. Make sure they are enrolled in a Program to be able to add an Encounter
4. Click `Add Encounter`
6. See the entry form

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC3
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (apk)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #4967 

# 👩🏻‍💻 What does this PR do?

Improved the appearance of the new Encounter window
- Align the beginning of input fields
- Expand text input fields to take up the width of the space

Screenshot 2024-11-20 at 5 04 02 PM

Screenshot 2024-11-20 at 5 01 29 PM

## 💌 Any notes for the reviewer?

Visit Date is not an expandable field, it also can't go at the top (Encounter type needs to be the first entry). Open to suggestions on further improvements

I have not addressed validation appearance in this PR. To be done in  #4299 Standardise the appearance of required fields across omSupply

# 🧪 Testing

- [ ] Go to Dispensary -> Patients
- [ ] Create a new patient or click on an existing one with a Programme Enrollment
- [ ] Click Encounters -> Add Encounter
- [ ] See the entry form

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx [hunk 1]
```diff
@@ -253,14 +255,15 @@ export const CreateEncounterModal: FC = () => {
       width={700}
     >
       <React.Suspense fallback={<div />}>
-        <Stack alignItems="flex-start" gap={1} sx={{ paddingLeft: '20px' }}>
+        <Stack gap={1} sx={{ padding: '20px' }}>
           <InputWithLabelRow
+            labelProps={{ sx: { flex: `${LABEL_FLEX}` } }}
```
Comment (lache-melvin) [inline client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx:260]:
```suggestion
            labelProps={{ sx: { flex: LABEL_FLEX } }}
```

String interpolation shouldn't be needed here 😁

**Review by lache-melvin — APPROVED** [review]
Looks epic, thanks Aimee! Just requesting to remove the `${}` bits, merge when ready 🙏 

All good with the date picker, I think is a great improvement for now, and thanks for flagging that the validation will be done separately! 😀
