### PR TITLE
Save donor id and item variant id properly from stocktakes to stock line

### LINKED ISSUE #8745: Donor & item variants aren't being saved to stock lines from stocktake
## What went wrong? 😲
Donor & item variants aren't being saved to stock lines from stocktake

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #8745

# 👩🏻‍💻 What does this PR do?
Saves donor id and item variant id on stock line if they have been changed in stocktake

# 🧪 Testing

- [ ] Create stocktake
- [ ] Change donor / item variant on lines
- [ ] Finalise
- [ ] Stock's item variant & donor should update if changed in a stocktake

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Review by aimee-mcneil-melville — CHANGES_REQUESTED** [review]
Thanks Roxy, this is working well for existing lines changing the donor or the item variant 🚀 however... new lines are unable to be added to a stocktake 🥹 whether or not either of these new fields are set. I tried a bit of figuring out why but didn't get very far, I did confirm it works in v2.9.3-RC though

Error on finalise:
Screenshot 2025-08-08 at 3 12 45 PM

This test [here](https://github.com/msupply-foundation/open-msupply/blob/3f62e00aaad279dd79adcf6516fc0b4acf2edbe5/server/service/src/stocktake/update/mod.rs#L568-L569) shows the error also

I've filled in some missing structs [here](https://github.com/msupply-foundation/open-msupply/compare/8745-Donor-%26-item-variants-aren't-being-saved-to-stock-lines-from-stocktake...8745-structs-fix) also

I do love the row rename to stocktake_line - much more readable!

File: server/service/src/invoice_line/stock_out_line/insert/generate.rs [hunk 1]
```diff
@@ -89,6 +91,8 @@ fn generate_batch_update(
         pack_size: pack_size.unwrap_or(batch.pack_size),
         cost_price_per_pack: cost_price_per_pack.unwrap_or(batch.cost_price_per_pack),
         sell_price_per_pack: sell_price_per_pack.unwrap_or(batch.sell_price_per_pack),
+        item_variant_id: item_variant_id.or(batch.item_variant_id),
```
Comment (Chris-Petty) [inline server/service/src/invoice_line/stock_out_line/insert/generate.rs:94]: neat

File: server/service/src/invoice_line/stock_out_line/insert/generate.rs [hunk 2]
```diff
@@ -105,6 +109,8 @@ fn generate_line(
         total_before_tax,
         note,
         campaign_id,
+        item_variant_id: input_item_variant_id,
+        donor_id: input_donor_id,
```
Comment (Chris-Petty) [inline server/service/src/invoice_line/stock_out_line/insert/generate.rs:113]: Tangentially I think I prefer keeping the parameters of functions terse by just defining the structs and then destructuring in the function body

Comment (Chris-Petty) [reply server/service/src/invoice_line/stock_out_line/insert/generate.rs:113]: In fact when there is a number of fields coming from structs with some overlap maybe I don't like destructuring at all haha

File: server/service/src/stocktake/update/generate.rs [hunk 3]
```diff
@@ -76,9 +76,9 @@ fn generate_stock_in_out_or_update(
     stocktake_line: &StocktakeLine,
     stock_line: &StockLineRow,
 ) -> Result<StockLineJob, UpdateStocktakeError> {
-    let row = stocktake_line.line.to_owned();
+    let stocktake_line = stocktake_line.line.to_owned();
```
Comment (Chris-Petty) [inline server/service/src/stocktake/update/generate.rs:79]: nit: consistency would be to call this stocktake_line_row like you did in `generate_new_stock_line`
