### PR TITLE
7968 be able to assign campaign on remote site

### LINKED ISSUE #7968: Unable to assign a campaign to a stock line if on remote site
## What went wrong? 😲
I have created campaigns on my central server.
Looking at the stock line, I cannot see any and checking the API calls, it says `Not a central server`

Image

## Expected behaviour 🤔
I can assign a campaign to a stock line

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a campaign or two on your central server
2. On the remote site, sync and try to allocate to a stock line

## Your environment 🌱

- Open mSupply Version: 2.8 RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #7968

# 👩🏻‍💻 What does this PR do?

Can assign campaign on a remote site

## 💌 Any notes for the reviewer?

# 🧪 Testing

**Central Site**
- [ ] Campaign functionalities stays the same 
  - [ ] Create/Edit a campaign (Manage/**Campaigns page**)
  - [ ] Select/Remove campaign on a Stock (Inventory/**View Stock page**)
  - [ ] Select/Remove campaign for an InboundShipment (Replenishment/Inbound Shipments page - **other tab** for a line) 

**Remote Site**
- [ ] Select/Remove campaign on a Stock (Inventory/**View Stock page**)
- [ ] Select/Remove campaign for an InboundShipment (Replenishment/Inbound Shipments page - **other tab** for a line) 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/graphql/lib.rs [hunk 1]
```diff
@@ -118,10 +118,6 @@ impl CentralServerQueryNode {
     async fn plugin(&self) -> CentralPluginQueries {
         CentralPluginQueries
     }
-
-    async fn campaign(&self) -> CampaignQueries {
-        CampaignQueries
-    }
```
Comment (GeronimoJohn) [inline server/graphql/lib.rs:124]: Removed the `campaign` query from the central server collection of queries. I didn’t remove the `campaign` mutations under `central server`, as I think we’d likely only ever create campaigns there?

Support for inserting and removing campaigns on `Stock` lines and `Inbound Shipment` lines is already in place outside the `central server` mutations. We just needed a way to query the campaigns outside of central server

Comment (jmbrunskill) [reply server/graphql/lib.rs:124]: Yup exactly
