### PR TITLE
3801 Internal Order Page has misaligned "Filter Items" searchbox and "Actions" drop down

### LINKED ISSUE #3801: Internal Order Page has misaligned "Filter Items" searchbox and "Actions" drop down
## What went wrong? 😲

image

image

image

## Expected behaviour 🤔

Things should be aligned otherwise they look bad.

(whine: I'm gonna guess certain styles are inherited, rather than added in via composition. So things have correct padding in one context but not another...)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. view an internal order

## Your environment 🌱

- Open mSupply Version: 2.0.00 on demo-open.msupply.org (IDK what RC)

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3801

# 👩🏻‍💻 What does this PR do?
Forces height on grid so that the filter and actions align 👀 
Screenshot 2024-05-08 at 11 41 40

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to Internal Order
- [ ] Create a new Internal Order
- [ ] See they should be aligned on tool bar 👀 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Maybe screenshots if they're misaligned
  2.

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx [hunk 1]
```diff
@@ -129,7 +129,7 @@ export const Toolbar: FC = () => {
         display="flex"
         gap={1}
         justifyContent="flex-end"
-        sx={{ marginTop: 2 }}
+        sx={{ marginTop: 2, height: 37 }}
```
Comment (Chris-Petty) [inline client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx:132]: I'm too rusty on react but generally speaking adding random inline heights in the UI makes me sad 😢. Why does the search bar seemingly have padding above it? Or is it the DDL has margin below it? Ideally things would just grow to the container and the container aligns them :(

Comment (roxy-dao) [reply client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx]: Have removed and done with with some flexing instead 💪🏻

**Review by Chris-Petty — APPROVED** [review]
m a n i f i c e n t 

image
