### PR TITLE
6696 Add required indicator

### LINKED ISSUE #6696: When changing vax status, no indication that a reason must be provided
## What went wrong? 😲
Not obvious that reason must be provided if vaccination is changed from `given` to `not given`

## Expected behaviour 🤔
Some sort of indicator on reasons to show that it is a required field. Maybe red * like rest of app? Highlighted box? 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Should have vaccinations set up
2. Enrol patient into vax program
3. Add vax encounter
4. Change a dose to given
5. Go back to same dose and now click `vaccine not given`
6. See that `Ok` is disabled without any indication as to why

## Your environment 🌱

- Open mSupply Version: 2.6.0-RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #6696

# 👩🏻‍💻 What does this PR do?
Add required prop to common "InputWithLabelRow" component so that we can add a required flag to alert user why "Ok" button is disabled when stating that a vaccine has NOT been given

Screenshot 2025-04-01 at 11 36 40

## 💌 Any notes for the reviewer?
I don't think it should but hopefully this doesn't affect the use of the component in other areas.

# 🧪 Testing

- [ ] Should have vaccinations set up
- [ ] Enrol patient into vax program
- [ ] Add vax encounter
- [ ] Change a dose to given and click OK
- [ ] Go back to same dose and now click vaccine not given
- [ ] See that Ok is disabled and that reason now has required asterisk to indicate to user why OK is disabled

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx [hunk 1]
```diff
@@ -28,6 +37,19 @@ export const InputWithLabelRow: FC<InputWithLabelRowProps> = ({
         {label}:
       </FormLabel>
       {Input}
+      <Box width={2}>
```
Comment (roxy-dao) [inline client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx:40]: You're changing a common component, so good to check everywhere where it is used to make sure the style is still the same

Screenshot 2025-04-02 at 8 38 54 AM

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks Noel~

Have a lil request (: Common component so you'll have to check if anything has changed when you add another Box component to the input labels (:

File: client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx]: Thanks @roxy-dao. I've actually decided to revert change to the common component and instead make the change only where needed.

**Review by roxy-dao — APPROVED** [review]
Thanks Noel

nit: width now different..
Screenshot 2025-04-03 at 9 16 29 AM

File: client/packages/system/src/Vaccination/Components/VaccinationModal.tsx [hunk 2]
```diff
@@ -285,7 +285,7 @@ const VaccinationForm = ({
           <InputWithLabelRow
             label={t('label.reason')}
             Input={
-              <>
+              <Box sx={{ display: 'flex', width: 275 }}>
```
Comment (noel-yeldos) [inline client/packages/system/src/Vaccination/Components/VaccinationModal.tsx:288]: I had to give this box a fixed width for it to align. I hope that's all good?

**Comment by noel-yeldos** [comment]
Refactor issue raised https://github.com/msupply-foundation/open-msupply/issues/7213
