### PR TITLE
7841 allow verify inbound shipment with lines with 0 quantity

### LINKED ISSUE #7841: Cannot zero out inbound shipment transfer lines
## What went wrong? 😲

When i receive inbound shipment (say a historic one when new store is create from existing name), I should be able to zero out the whole inbound shipment, or shipment lines or individual stock line. 

I cannot zero out individual stock line, ok button goes grey.

After zeroing out through select lines and action at the bottom, it won't left me verify

## Expected behaviour 🤔

Able to at least zero out all lines and verify inbound shipment.

Should be able to zero out individual lines (what if they didn't arrive ?), and verify

## How to Reproduce 🔨

Create transfer

Try to zero out individual line or all lines, and try verify

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #7841

# 👩🏻‍💻 What does this PR do?

Applies #8459 to v2.9.3 (changes already merged into v2.10

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create outbound shipment in one store, mark as shipped so it transfers to second store
- [ ] In second store, mark as received
- [ ] Open line - you can set `packs received` to 0 and save the modal
- [ ] Click Mark as verified - it succeeds

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx [hunk 1]
```diff
@@ -219,6 +223,16 @@ const useStatusChangeButton = () => {
   };
 };
 
+export const validateEmptyInvoice = (lines: {
+  totalCount: number;
+  nodes: InboundLineFragment[];
+}): boolean => {
+  // Should only proceed if there is at least one line, with received or shipped packs defined
+  if (lines.totalCount === 0 || lines.nodes.every(isInboundPlaceholderRow))
```
Comment (andreievg) [inline client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx:231]: > // Should only proceed if there is at least one line, with received or shipped packs defined

If it's an old inbound shipment that we want to zero out (what the table action I believe is for), we should be able to verify it when all lines are zero (I think), would this prohibit it ? If so can we clarify with @mark-prins

Comment (andreievg) [reply client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx:231]: !row.shippedNumberOfPacks;
