### PR TITLE
10329 frontend table refactor

### LINKED ISSUE #10329: Important columns are not visible by default
## NOTE 

Andrei: See this comment for issue requirement: https://github.com/msupply-foundation/open-msupply/issues/10329#issuecomment-3820758645

## What went wrong? 😲
Some tables are not showing the most important columns on a default loading when using a tablet.

## Expected behaviour 🤔
We need to be able to see important columns by default without resizing or removing columns

- [x] **Internal orders** 
  * Detail view: change column order to be 
    * Comment
    * Code
    * Name
    * Available stock
    * AMC
    * MOS
    * Target stock
    * Suggested quantity
    * Requested
    * Unit
    * Doses per unit
    * Default pack size  
- [ ] **Inbound shipments** 
  * Detail view: `Expiry date` should not be as wide. here are the current columns - should we re-order?
    * Code
    * Comment
    * Name
    * Batch
    * Expiry date
    * VVM Status
    * Location
    *  ^--- visible ---^
    * Unit name
    * Pack size
    * Doses per unit
    * Pack Qty
    * Unit Qty
    * Doses
    * Cost per unit
    * Total
    * Donor
    * Campaign/program
- [x] **Stock** 
  * `SOH` should be visible
  * `Expiry` should not be as wide
  * `Pack size` should not be as wide?
  * move `Master lists` to be after `Total`
  * move `VVM status` to be after `Master lists`?
- [ ] **Stocktake** 
  * Detail view - no quantities are shown. should we move or remove columns? 
    * Code
    * Name
    * Batch
    * Expiry date
    * Location
    * Unit name
    * ^--- visible ---^
    * Pack size
    * Doses per unit
    * Packs Snapshot
    * Packs Counted
    * Difference
    * Reason
    * Donor
    * Comment
- [x] **Requisitions** 
  * Detail view: make unit slightly less wide so that `Units to supply` is visible
- [ ] **Outbound shipments** 
  * Detail view: What should change here? which columns are important?
    * Code
    * Name
    * Batch
    * Expiry date
    * VVM Status
    * Location
    * ^--- visible ---^
    * Unit name
    * Pack size
    * Doses per unit
    * Pack Qty
    * Unit Qty
    * Doses
    * Unit Sell Price
    * Total
- [ ] **Prescriptions** 
  * Detail view: What should change here? which columns are important?
    * Code
    * Name
    * Batch
    * Expiry date
    * Location
    * Unit name
    * ^--- visible ---^
    * Pack size
    * Doses per unit
    * Unit Qty
    * Doses
    * Pack Qty
    * Unit Price
    * Line total
    * Purchase cost

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by aneeshthunga26**
Fixes #10329

# 👩🏻‍💻 What does this PR do?

Align UI tables (ListView, DetailView) to how they looked in 2.11.3

# 🧪 Testing

- [ ] Run two instances with same datafile, one with 2.11.3 and one with this branch
- [ ] Compare all the table screens 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/DetailView/columns.tsx [hunk 1]
```diff
@@ -44,13 +44,14 @@ export const useStocktakeColumns = () => {
       {
         accessorKey: 'itemName',
         header: t('label.name'),
-        size: 400,
+        size: 300,
```
Comment (aimee-mcneil-melville) [inline client/packages/inventory/src/Stocktake/DetailView/columns.tsx]: The dose column was visible for me upon open in 2.11, looks that the name was a little smaller still

File: client/packages/system/src/Stock/ListView/ListView.tsx [hunk 2]
```diff
@@ -219,7 +221,7 @@ export const StockListView = () => {
     columns: mrtColumns,
     data: data?.nodes,
     totalCount: data?.totalCount ?? 0,
-    initialSort: { key: 'name', dir: 'desc' },
+    initialSort: { key: 'expiryDate', dir: 'asc' },
```
Comment (aimee-mcneil-melville) [inline client/packages/system/src/Stock/ListView/ListView.tsx]: Please change sort back to `Name, desc` which is the correct sort for this - the 2.11 tables would have shown expiry as the default sort, but it was updated separately at a similar time

https://github.com/msupply-foundation/open-msupply/pull/9531

**Review by aimee-mcneil-melville — APPROVED** [review]
Fantastic, thanks Aneesh! Good to go :)

Just noting that I made a change where vaccine settings were required, and I found  some other additional columns dependent on settings in request and response requisitions (but all of those matched!)
