### PR TITLE
#7915(2) Prefs key invalidation fix

### LINKED ISSUE #7915: When Preference Manage VVM status for stock is off, the VVM status field show in the View stock window as well as the Status history tab being visible
## What went wrong? 😲
As title plus the button to add VVM is clickable when clicking on a status history line, the VVM field is empty and the comment box can be interacted with will not display any text you are writing.  
https://drive.google.com/file/d/1nMI5VsYzEvpxIH819JQ1oACvFzqijgxE/view?usp=sharing

~~The VVM status is also appearing in the Outbound shipment;~~ The VVM status doesn't appear on outbound shipment after  I logged out and back but the stock window is till showing VVM status and status history tab
https://drive.google.com/file/d/1YJvnQsCVVH7gW787EAqE3SWi2RZ28Dr9/view?usp=sharing

## Expected behaviour 🤔
I think that when the `Manage VVM status for stock` is off, we should use the same behaviour than for item that are not a vaccine ie doesn't show the Vaccine history tab at all and the VVM status field is hidden. Same thing for Stock line when allocating stock of a vaccine in an outbound shipment

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Have some vaccine in stock that have VVM status  
On OMS central turn off the Preference `Manage VVM status for stock` for your store
Sync
1. Go to 'Inventory > View stock'
2. Click on one of your vaccine
3. See that the VVM status field is showing as well as the Status History tab
4. Create a new inboind shipment
5. Add a vaccine item
6. See error when allocating qty form your stock line. The VVM status is showing. 

## Your environment 🌱

- Open mSupply Version: v2.8RC3
- Legacy mSupply Central Server Version: v8.02

- Platform: Android

- Database type: SqLite3

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #7915 

# 👩🏻‍💻 What does this PR do?

@noel-yeldos already added the preference check to the VVM Status tab, but this PR fixes the preferences query invalidation so that when you change the preference the Tab appears/disappears without a page reload.

## 💌 Any notes for the reviewer?

There was an inconsistency with the queryKeys array, which is why the prefs weren't being re-fetched. However, I've also simplified the Prefs hooks to use the same API hook and not rely on the Auth API. This makes it a bit clearer and not quite so intertwined with the Auth API.

# 🧪 Testing

- [ ] Go to "View Stock" and click on a vaccine item
- [ ] Note whether the Status History tab (and the VVM status input) is available or not
- [ ] Open your store prefs by clicking "Edit" in the Footer (must be central server)
- [ ] Toggle the "Manage VVM status for stock" pref, and close
- [ ] Note the Status History tab and VVM input have switched (either on or off)
- [ ] Try it the other way round (turn it off/on)

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/authentication/api/hooks/usePreference.ts [hunk 1]
```diff
@@ -29,7 +27,7 @@ export const usePreference = <T extends PreferenceKey>(...prefs: T[]) => {
   };
 
   return useQuery({
-    queryKey: [keys.preferences(), ...prefs],
```
Comment (CarlosNZ) [inline client/packages/common/src/authentication/api/hooks/usePreference.ts:32]: This was the source of the bug -- `keys.preferences()` returns an array, so they key array was `[ [ "preferences"], "etc..." ]` when it should have been `[ "preferences"], "etc..." ]`.

The simplification to use the `usePreferencesGraphQL` API helps reduce this potential confusion.

File: client/packages/system/src/Manage/Preferences/api/useEditPreference.ts [hunk 2]
```diff
@@ -54,8 +52,7 @@ const useUpsertPref = () => {
     },
     {
       onSuccess: () => {
-        queryClient.invalidateQueries(keys.preferences());
-        queryClient.invalidateQueries(PREFERENCE_DESCRIPTIONS);
+        queryClient.invalidateQueries(PREFERENCES);
```
Comment (CarlosNZ) [inline client/packages/system/src/Manage/Preferences/api/useEditPreference.ts:55]: Now we only need to invalidate one set of keys :)

File: client/packages/system/src/Manage/Preferences/api/usePreferencesGraphQL.ts [hunk 3]
```diff
@@ -4,12 +4,13 @@ import {
...
+import { PREFERENCES } from './keys';
 
 export const usePreferencesGraphQL = () => {
   const { client } = useGql();
   const queryClient = useQueryClient();
   const { storeId, store } = useAuthContext();
   const api = getSdk(client);
 
-  return { api, queryClient, storeId, store };
+  return { api, queryClient, storeId, store, client, PREFERENCES };
```
Comment (CarlosNZ) [inline client/packages/system/src/Manage/Preferences/api/usePreferencesGraphQL.ts:15]: Just re-exporting key from here to avoid two ugly long imports in `usePreference`
