### PR TITLE
2523 requisition columns 'remaining' is confusing people

### LINKED ISSUE #2523: Requisition columns: 'Remaining' is confusing people
## What went wrong? 😲
 
There is some confusion of the intention of 'Remaining' on a customer requisition.
The column shows the quantity to supply less the quantity which has been added to outbound shipments already. And has been called `Remaining` which is shorthand for `Remaining to supply`

The column details are:
- **label**
  - `label.remaining-to-supply`
  - Remaining
- **description**
  - `description.remaining-to-supply`
  - The quantity remaining to be supplied, which is the Supply quantity less the quantity of this item on any linked Outbound Shipment

Here's how it works in practice:

https://github.com/msupply-foundation/open-msupply/assets/9192912/3ca6f35d-4149-4260-9a1b-ba3416f7ed84

As a possible reworking of the tooltip, here's Louisa's version in her docs: `the remaining quantity to supply to the customer which will be re-calculated after a shipment has been created`

The addition of the 're-calculation' is helpful, however I think the 'remaining quantity to supply' is slightly less clear and it removes the explanation of the quantity on outbound shipments.

There's a question of whether the columns is actually useful and if the use-case of a partially filled order is realistic. Advice so far is that it is very uncommon and the column is unlikely to be useful. However, columns can be hidden by the user.

Currently in mSupply the columns are 
- Customer requested
- Already issued
- Remaining to supply
- Supply this invoice

telegram-cloud-photo-size-1-5109393503523286405-x

Note that this gets even messier when the authorisation process is used - "What's left to supply from what quantity the authorisers approved"
We do have an 'approved quantity' shown in this case however. It's just that there is no calculation made to show a subtraction of issued against approved.

## Expected behaviour 🤔
To be defined.

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #2523

# 👩🏻‍💻 What does this PR do? 
Have added an `already issued` column with description and changed the `remaining` column to hopefully be more clearer.
Screenshot 2024-03-11 at 12 22 15

# 🧪 How has/should this change been tested? 
- [ ] `Store A` sends `Internal Order` to `Store B`
- [ ] Go to `Store B` -> `Requisition`
- [ ] First only partially supply the order and create shipments for that amount
- [ ] Go back to `Requisition` window and supply more without creating shipment
- [ ] See the different totals under `Supply`, `Issued` and `Remaining`.
- [ ] Also hover over `Issued` and `Remaining` tooltips to see if new descriptions are clearer

### CODE REVIEW

File: server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs [hunk 1]
```diff
@@ -16,7 +16,7 @@ pub fn generate(
     store_id: &str,
     user_id: &str,
     requisition: Requisition,
-    fullfilments: Vec<RequisitionLineSupplyStatus>,
+    fulfillments: Vec<RequisitionLineSupplyStatus>,
```
Comment (roxy-dao) [inline server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs:19]: Sidetrack: Typo

File: server/service/src/requisition/response_requisition/create_requisition_shipment/validate.rs [hunk 2]
```diff
@@ -33,11 +33,12 @@ pub fn validate(
     let supply_statuses =
         get_requisitions_supply_statuses(connection, vec![requisition_row.id.clone()])?;
 
-    let remaing_to_supply = RequisitionLineSupplyStatus::lines_remaining_to_supply(supply_statuses);
+    let remaining_to_supply =
+        RequisitionLineSupplyStatus::lines_remaining_to_supply(supply_statuses);
 
-    if remaing_to_supply.len() == 0 {
+    if remaining_to_supply.len() == 0 {
```
Comment (roxy-dao) [inline server/service/src/requisition/response_requisition/create_requisition_shipment/validate.rs:39]: Another sidetrack 😆

File: client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts [hunk 3]
```diff
@@ -90,6 +92,7 @@ export const useResponseColumns = () => {
           getItemId: row => row.itemId,
           getQuantity: row => NumUtils.round(row.requestedQuantity ?? 0),
         }),
+        width: 150,
```
Comment (roxy-dao) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts:95]: Added since the sort arrow was covering the tooltip

File: client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts [hunk 4]
```diff
@@ -131,7 +148,6 @@ export const useResponseColumns = () => {
       getItemId: row => row.itemId,
       getQuantity: row => NumUtils.round(row.remainingQuantityToSupply),
     }),
-    width: 100,
```
Comment (roxy-dao) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts:134]: This was fixed in another issue (which was causing the select boxes to overlap with last column) but was added back in PV?

File: server/graphql/general/src/queries/tests/master_lists.rs [hunk 5]
```diff
@@ -67,15 +67,6 @@ mod graphql {
                   name
                   code
                   description
-                  lines {
```
Comment (roxy-dao) [inline server/graphql/general/src/queries/tests/master_lists.rs:70]: Test fixes from a previous PR... should probably fix actions running out of space 👀

File: client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts [hunk 6]
```diff
@@ -121,6 +124,20 @@ export const useResponseColumns = () => {
       }),
     },
   ]);
+
+  columnDefinitions.push({
+    label: 'label.already-issued',
+    description: 'description.remaining-to-supply',
+    key: 'alreadyIssued',
+    align: ColumnAlign.Right,
+    getSortValue: rowData => rowData.remainingQuantityToSupply,
```
Comment (mark-prins) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts:133]:
```suggestion
    description: 'description.already-issued',
    key: 'alreadyIssued',
    align: ColumnAlign.Right,
    getSortValue: rowData => rowData.alreadyIssued,
```

File: client/packages/common/src/intl/locales/en/common.json [hunk 7]
```diff
@@ -55,7 +56,7 @@
   "description.our-soh": "Our Stock on Hand",
   "description.pack-quantity": "Total quantity in number of packs",
   "description.program": "Programs are used to manage groups of items, and replenishment schedules.",
-  "description.remaining-to-supply": "The quantity remaining to be supplied, which is the Supply quantity less the quantity of this item on any linked Outbound Shipment",
+  "description.remaining-to-supply": "The remaining quantity to supply to the customer which will be re-calculated after a shipment has been created",
```
Comment (mark-prins) [inline client/packages/common/src/intl/locales/en/common.json:59]: I thought the explanation of the calculation was useful - is there a reason to remove?
```
The quantity remaining to be supplied to the customer which will be re-calculated after a shipment has been created. The calculation is 'Supply - Issued'
```

**Review by mark-prins — APPROVED** [review]
😄 nice! thanks Roxy - I think that's clearer.
One change needed, and a suggestion on wording 🙏

File: client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts (hunk 6 above)
Comment (roxy-dao) [reply client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts:133]: Opps... nice catch 😆

File: client/packages/common/src/intl/locales/en/common.json (hunk 7 above)
Comment (roxy-dao) [reply client/packages/common/src/intl/locales/en/common.json:59]: No reason, have added it back (:
