### PR TITLE
3858 CCEI module: No details in error message when creating CCE with duplicate asset numbers

### LINKED ISSUE #3858: CCEI module: No details in error message when creating CCE with duplicate asset numbers
## What went wrong? 😲
The system prevents users from creating multiple CCE with the same asset number (as expected)

However the error message is unclear: 

image

## Expected behaviour 🤔

Explain to the user explicitly why they can't create this CCE: 

`Unable to create CCE: Asset Number already exists`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a CCE with Asset Number `1`
2. Create another CCE with Asset Number `1`

## Your environment 🌱

- Open mSupply Version: V2.0.0-RC4

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3858

# 👩🏻‍💻 What does this PR do?
Show correct error if asset number already exists
Screenshot 2024-05-13 at 17 03 17

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create an equipment with asset number = 1
- [ ] Try create another equipment with asset number = 1
- [ ] See error

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx [hunk 1]
```diff
@@ -70,10 +70,11 @@ const InputRow = ({
 const parseInsertError = (e: unknown) => {
   const message = (e as Error).message;
   if (
-    message.includes('DatabaseError(') &&
-    message.includes('UniqueViolation(') &&
-    message.includes('asset_asset_number_key') &&
-    message.includes('duplicate key')
+    message.includes('DatabaseError(') ||
```
Comment (roxy-dao) [inline client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx:73]: Not sure why this was using && ......

File: client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx [hunk 2]
```diff
@@ -70,10 +70,11 @@ const InputRow = ({
...
+    message.includes('UniqueViolation(') ||
+    message.includes('asset_asset_number_key') ||
+    message.includes('duplicate key') ||
+    message.includes('AssetNumberAlreadyExists')
```
Comment (mark-prins) [inline client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx:77]: for me, this is enough:

```suggestion
    message.includes('AssetNumberAlreadyExists')
```

and is easier to understand!

**Review by mark-prins — APPROVED** [review]
Looks good! thanks Roxy


I would suggest removing all the other cases entirely, only the `AssetNumberAlreadyExists` is needed isn't it?

File: client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx (hunk 2 above)
Comment (roxy-dao) [reply client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx:77]: yeah I wasn't sure why the others were added XD

**Comment by adamdewey** [comment]
@roxy-dao - @mark-prins - just had a thought, is this message specific to the CCE module? 

Wondering if it might need to be more generic if it's also going to be used for general assets?

If so could maybe remove the `CCE` from the message?

**Comment by mark-prins** [comment]
it is specific to the CCE module - it's also a translation item, so can be updated in the translation server if needs be!
