### PR TITLE
3934 Item name is cut off in requisition line edit modal

### LINKED ISSUE #3934: Item name is cut off in requisition line edit modal
## What went wrong? 😲
 

Per comment in [this issue](https://github.com/msupply-foundation/open-msupply/issues/3540#issuecomment-2114865474)

Item name is cut off, with no tooltip to see the full name:
image

## Expected behaviour 🤔

There is a tooltip for long item names

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Requisitions
2. Click on a requisition line with a long item name
3. See the name is cut off
4. You can't hover to see the full name

## Your environment 🌱

- Open mSupply Version: 2.1.0
- Legacy mSupply Central Server Version:

- Platform: browser/tablet

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3934

# 👩🏻‍💻 What does this PR do?
Add tooltip to requisition item name
Screenshot 2024-06-19 at 7 47 59 AM

# 🧪 Testing

- [ ] Have an item with a very long item name
- [ ] From Store A: Create an Internal Order to Store B with that item
- [ ] Go to Store B: View Requisition
- [ ] Click on line
- [ ] Hover over item name

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx [hunk 1]
```diff
@@ -98,8 +100,11 @@ export const ResponseLineEditForm = ({
           <Typography variant="body1" fontWeight="bold">
             {t('heading.stock-details')}
           </Typography>
-
-          <InfoRow label={t('label.name')} value={item.name} />
+          <Tooltip title={item.name}>
+            <Box>
```
Comment (roxy-dao) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx:104]: Needed to wrap the component to get tooltip to show up....

**Review by mark-prins — APPROVED** [review]
👍 nice! thanks Roxy
