### PR TITLE
3874 you can perform transactions on disabled oms store

### LINKED ISSUE #3874: You can perform transactions on disabled OMS store
## What went wrong? 😲
 

You can perform transactions on disabled store

Video Reference: https://drive.google.com/file/d/1ObJkJAH2OFDs9KQPUZYbtcj4E8-o2k4R/view?usp=share_link

## Expected behaviour 🤔
disable store means restrict any further stock transfers to the disabled store? 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. mSupply datafile having open mSupply stores
2. Make sure they are visible to msupply stores 
3. Now disable the open msupply store

Screenshot 2024-05-13 at 17 12 41

4. Sync, logout and login to open mSupply Sites
5. Now make Stock transfer to mSupply stores
6. You can make stock transfer, Even if the store is disabled 
(BUG)

## Additional
Can i call this severity high? .. since the `disabled` oms-store looks very active, not disabled at all

## Your environment 🌱

- Open mSupply Version: v2-00-rc5
- Legacy mSupply Central Server Version: v7-15-00-dev5

- Platform: standalone

- Database type: SQlite

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3874

# 👩🏻‍💻 What does this PR do?
1. Migration to add `is_disabled` to store
2. In store selector at the bottom left of the screen: Disable store + add on hold text
Screenshot 2024-06-21 at 7 28 44 PM
3. Filter out disabled store from most recent credentials 

## 💌 Any notes for the reviewer?
Note for testers: Will need to delete database and reinitialise since there has been a migration change to store..

Sorry I accidentally merged develop into the branch and couldn't rebase cleanly again 👀 

# 🧪 Testing

- [ ] in mSupply: Disable store
- [ ] Sync to OMS
- [ ] See that disabled store is greyed out in Store Selector in bottom left 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Add a note about disabled stores
  4.

### CODE REVIEW

**Comment by roxy-dao** [comment]
https://github.com/msupply-foundation/open-msupply/pull/4237#issuecomment-2185374973 @andreievg 

If they have it disabled... and that is their default store
Screenshot 2024-06-24 at 6 53 39 PM

BUT if they have some other store as their default then it'll log them into that store (if it's saved in cookie).... though, the user's default store should be the only store they can log into if they only have access to one store?

File: client/packages/common/src/authentication/api/hooks/useLogin.ts [hunk 1]
```diff
@@ -58,23 +58,26 @@ export const getMostRecentCredentials = (
...
-  const stores = userDetails?.stores?.nodes;
+  const stores = userDetails?.stores?.nodes.filter(s => !s.isDisabled);
   const mru = mostRecentCredentials?.find(
     item => item.username.toLowerCase() === userDetails?.username?.toLowerCase()
   );
 
-  if (mru?.store && stores?.some(store => store.id === mru?.store?.id)) {
+  if (
+    mru?.store &&
+    !mru.store.isDisabled &&
```
Comment (mark-prins) [inline client/packages/common/src/authentication/api/hooks/useLogin.ts:74]: :nit 
the `!mru.isDisabled` and `!s.isDisabled` aren't necessary

**Review by mark-prins — APPROVED** [review]
👍 looks good! thanks Roxy
I've popped in one small extra nit, but that's non essential!
