### PR TITLE
4161 Hardcode filtering out of patients from names query

### LINKED ISSUE #4161: Hardcode filtering out of patients from names query
NOTE: maybe this is a bug - the `type` property on the NameFilterInput now doesn't work, it gets overwritten in the service layer by a `type != PATIENT` filter... haven't _seen_ any other issues in the actual UI from it though 🤷‍♀️

## The suggestion

Context: #4146

Issue introduced by #4023

We have a `names` query endpoint, and a different one for `patients`. We only use the `names` one for non-patient related things, so we should hard code the filtering out of patients into the repository layer. 

We should then also remove the `NameNodeType::Patient` and `isPatient` options from the NameFilterInput, to make it clear its not possible to query patients via the name endpoint

### Why should we invest time in this?

Our API inputs should accurately reflect what you are able to get back!

Finish off the teasing apart of store/facility and patient, so we don't need to constantly consider this filtering while devving.

### Are there any risks associated with this change?

Just checking all the queries still work as expected?

### How much effort is required?

Couple hours?

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4161

# 👩🏻‍💻 What does this PR do?
Removes hardcoded patient filtering from the name service layer and have moved this to the repository layer, and remove is_patient filter and Patient from NameNodeType. 

Prescription insert/update now use a `check_patient_exists` for patient validation instead of the `check_other_party` function.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Make sure suppliers/customers are still loaded correctly
- [ ] Make sure that prescriptions can still be created
- [ ] (dev) Call name API with graphql. Patients shouldn't show at all even without filtering.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/repository/src/db_diesel/name.rs [hunk 1]
```diff
@@ -176,6 +175,7 @@ impl<'a> NameRepository<'a> {
                     .left_join(store_dsl::store),
             )
             .inner_join(name_oms_fields_alias)
+            .filter(name_dsl::type_.ne(NameType::Patient))
```
Comment (roxy-dao) [inline server/repository/src/db_diesel/name.rs:178]: Filtering out all patients in repo layer

**Comment by andreievg** [comment]
@roxy-dao this is where i got to with the refactor i was doing: https://github.com/msupply-foundation/open-msupply/tree/names-and-patients-separate-fitler-draft (the idea was to remove extra filtering in graphql and service layer, move them to repo layer and remove filter types that doin't apply to relevant repos like type Patient form NameRowType)

**Review by jmbrunskill — APPROVED** [review]
Looks good to me, tried prescriptions and all seems to work well.

Love PRs that reduce the amount of code!

**Comment by roxy-dao** [comment]
> Looks good to me, tried prescriptions and all seems to work well.
> 
> Love PRs that reduce the amount of code!

How do you feel about trying changing it up a little and getting some of Andrei's refactoring in~?

**Comment by jmbrunskill** [comment]
> > Looks good to me, tried prescriptions and all seems to work well.
> > Love PRs that reduce the amount of code!
> 
> How do you feel about trying changing it up a little and getting some of Andrei's refactoring in~?

I think you've achieved the goal with what you've done, but can see some advantages with Andrei's. Sorry I'd missed his comment when I first reviewed as he hadn't assigned himself, So I thought no one was looking at it. If I understand correctly Andrei's basically just cleans up the filter options so you can't send a filter type that doesn't make sense (like Name Type: `Patient`) to the `name` service. 

Personally I'm happy either way :)

**Review by andreievg — APPROVED** [review]
Looks great, happy for this to go through without the type changes for filters, but I wouldn't close the issue yet, and would also add to the issue:
relocate: GenderInput from Name to Patient in graphql
