### PR TITLE
10058 Phone only displays 20 CCE

### LINKED ISSUE #10058: [CCEI / GAPS] Phone only displays 20 CCE (page limited)
## What went wrong? 😲

The phone app only shows the first 20 CCE, the rest are hidden and there's no way to navigate to them

Image
Image

## Expected behaviour 🤔

Phone app should show all CCE in the store

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have more than 20 CCE in a store
2. Attempt to navigate to CCE #21

## Your environment 🌱

- Open mSupply Version: 2.13.1

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #10058 

# 👩🏻‍💻 What does this PR do?

Applied infinite scrolling to CCE mobile view. Allow users continuous scrolling and automatically load additional data. 

_**Notice Asset Number go past 20**_

https://github.com/user-attachments/assets/23f06a5a-8ce5-4668-b4a3-f0b3e77be40b

## 💌 Any notes for the reviewer?

Kinda set a new pattern for infinite scrolling on mobile? Keen to hear thoughts on it. AND please let me know if we have an existing pattern for infinite scrolling already

# 🧪 Testing

- [ ] On Android Mobile, with cold chain feature enabled. 
- [ ] Navigate to Equipment page
- [ ] If you have more than 20 CCE, it should allow continuous scrolling and automatically load additional data
- [ ] If you don't have more than 20 CCE, create more (lol)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Comment by mark-prins** [comment]
fine with splitting the issue into another if that's easier to manage - will ask about a design mock up

**Comment by rjekta1-droid** [comment]
**#10089******

**Comment by mark-prins** [comment]
I've tried the version with the button and the infinite scroll version and prefer the infinite scroll as a user. Agree that users should be scanning rather than scrolling forever though.. and the filter is not useful if you are using the scanner as intended

I have added the loader to the infinite scroll version when testing, though I'd use the `InlineSpinner` which is smaller and neater

```
        {isFetchingNextPage && <InlineSpinner />}
      </Box>
      <CreateAssetModal
...
```

File: client/packages/coldchain/src/Equipment/api/hooks/index.ts [hunk 1]
```diff
@@ -14,6 +14,7 @@ export const useAssets = {
     get: Document.useAsset,
     list: Document.useAssets,
     listAll: Document.useAssetsAll,
+    inifiniteAssets: Document.useInfiniteAssets,
```
Comment (mark-prins) [inline client/packages/coldchain/src/Equipment/api/hooks/index.ts]:
```suggestion
    infiniteAssets: Document.useInfiniteAssets,
```

**Comment by adamdewey** [comment]
@andreievg - I think the main use case for using the list was as a manual fall-back if scanning isn't working for whatever reason
