### PR TITLE
3112 fix sort direction

### LINKED ISSUE #3112: Unable to change sort direction in lists
## What went wrong? 😲
 
Click on a column header to sort, click again to change the direction and nothing happens
Not on all pages though. So far has been confirmed on:

* outbound shipment list view
* requisition list view
* internal order list view 

## Expected behaviour 🤔
Should be able to change direction

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to any table / list view
2. Click on column to sort
3. Click on the same column again

## Your environment 🌱

- Version: 
- mSupply version:

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #3112 

The bug has been introduced here:
https://github.com/msupply-foundation/open-msupply/pull/2638/files#r1426169816

The problem was that `asc` is mapped to an empty query string. This means when there was no sort direction because of that, the initial direction was always used.

# 👩🏻‍💻 What does this PR do? 
- Fixes some lint warnings (first commit)
- Fixes the sort problem

Note: the initial sort direction is not used now...

### CODE REVIEW

File: client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts [hunk 1]
```diff
@@ -70,18 +70,24 @@ export const useUrlQueryParams = ({
...
+      const sort = column.key as string;
+      if (sort !== currentSort) {
+        // change sort key
+        updateQuery({ sort, dir: '', page: '' });
+      } else {
+        // toggle sort direction
+        const dir = column.sortBy?.direction === 'desc' ? '' : 'desc';
+        updateQuery({ dir });
+      }
+    },
```
Comment (clemens-msupply) [inline client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts:88]: I added some comments here, are they correct?

@mark-prins I think this method should not do the toggling but just update the sort order, i.e. instead of taking a Column it should just take a SortBy. So this hook would really just update the query params for page, filter and sort, but doesn't know about columns. The toggling should IMHO happen in HeaderCell. If you agree I can put this in.

Comment (mark-prins) [reply client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts:88]: yes, comments correct thanks.
The sort is only called from the header cell, which is already typed with the Column: makes sense to push anything column specific down into that component and keep this function clean. 
So yes, if you don't mind - would be good to have that.

**Review by mark-prins — APPROVED** [review]
🎉  thanks - changes are good. would like to follow up on your suggestion re header cell too though 🙏

**Comment by clemens-msupply** [comment]
@mark-prins I made change so that the toggle happens only in the HeaderCell. It touched a couple of files and also useQueryParamsStore where I did similar changes. Could you please have another look?

File: client/packages/invoices/src/InboundShipment/api/hooks/line/useInboundItems.ts [hunk 2]
```diff
@@ -28,5 +28,5 @@ export const useInboundItems = () => {
       );
   const { data } = useInboundSelector(selectItems);
 
-  return { data, sortBy, onSort: onChangeSortBy };
```
Comment (clemens-msupply) [inline client/packages/invoices/src/InboundShipment/api/hooks/line/useInboundItems.ts:31]: I only removed it to make sure it wasn't used anywhere...

File: client/packages/common/src/hooks/useQueryParams/useQueryParams.test.tsx [hunk 3]
```diff
@@ -225,17 +225,27 @@ describe('sort', () => {
...
+    expect(result.current.sort.sortBy).toEqual({
+      key: 'id',
+      isDesc: true,
+      direction: 'desc',
+    });
+
+    act(() => {
       // should be: quantity/desc
-      result.current.sort.onChangeSortBy(quantityColumn);
+      result.current.sort.onChangeSortBy(quantityColumn.key, 'desc');
```
Comment (clemens-msupply) [inline client/packages/common/src/hooks/useQueryParams/useQueryParams.test.tsx:248]: This test didn't make too much sense anymore so I changed it a bit...

**Review by mark-prins — APPROVED** [review]
Looks great - thanks @clemens-msupply 

I've found one extra minor bug, would you mind adding this in too?

In `client/packages/invoices/src/OutboundShipment/api/api.ts` can you add the case for 'theirReference' as well. Currently you can click this header to sort, but the sort key used is 'status'

added at line 51:
```
      case 'theirReference': {
        return InvoiceSortFieldInput.TheirReference;
      }
```

**Comment by clemens-msupply** [comment]
> added at line 51:
> 
> ```
>       case 'theirReference': {
>         return InvoiceSortFieldInput.TheirReference;
>       }
> ```

done thanks, sure we can make it typesafe somehow but maybe another time :)
