### PR TITLE
7337 pending encounter reports are broken

### LINKED ISSUE #7337: Pending Encounter reports are broken
## What went wrong? 😲

@CarlosNZ tagging you

Pending Encounter reports are broken - running into endless spinning loader when trying to generate it

## Expected behaviour 🤔

Should run

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports -> Pending Encounters
2. Click -> run
3. Encounter endless loading

## Your environment 🌱

- Open mSupply Version: V2.7.0-RC4
- Legacy mSupply Central Server Version: V8.1.10

- Platform: Galaxy Tab A8 (Android 14)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #7337

# 👩🏻‍💻 What does this PR do?

Fixes pending encounters report. Fixes eternal loading on unknown server errors.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Open Pending Encounters report (your store will need to have program module enabled)
- [ ] It loads correctly

And then for the showing error:
- [ ] Intentionally cause internal error while generating report 
  - [ ] Easiest way if you're fine with editing DB data:
  - [ ] Filter `report` table where name = 'Pending Encounters'
  - [ ] Find the latest record (highest version)
  - [ ] Edit the `template` field - it is JSON, find the field called `convert_data_type` and change this to "Extism"
  - [ ] Save the edited record, and generate the report
- [ ] Upon generating the report, you see the failed to generate message rather than loading spinner
- [ ] There is a backend log that convert data failed

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/reports/src/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -133,7 +133,10 @@ const DetailViewInner = ({
           }
         }
       } catch (error) {
-        console.error(error);
+        setState({
+          s: 'error',
+          errorMessage: t('error.failed-to-generate-report'),
+        });
```
Comment (lache-melvin) [inline client/packages/reports/src/DetailView/DetailView.tsx:139]: We were just doing console.error, so nothing showing to user. Because we never set the state, always showed loading spinner.

Screenshot 2025-04-16 at 4 44 27 PM

File: server/service/src/report/report_service.rs [hunk 2]
```diff
@@ -569,7 +573,14 @@ fn generate_report(
         report.convert_data.clone(),
         &report.convert_data_type,
     )
-    .map_err(ReportError::ConvertDataError)?;
+    .map_err(|err| {
+        error!(
+            "Error transforming data for report {}: {}",
+            report.name,
+            format_error(&err)
+        );
```
Comment (lache-melvin) [inline server/service/src/report/report_service.rs:581]: Adding an error log here, frontend just shows "failed to generate" - good to be able to look at the logs and see what went wrong!

Maybe should add throughout the report generation code but would be bloat, figured adding in the places we touch is an ok start for now?

File: standard_reports/encounters/latest/report-manifest.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 {
   "is_custom": false,
-  "version": "2.6.2",
+  "version": "2.6.3",
```
Comment (lache-melvin) [inline standard_reports/encounters/latest/report-manifest.json:3]: Spoke with Ferg, sounds like this was a case of #7322 - this report was bumped to 2.6.2 from 2 different branches, first was extism 2.6.2, so boa 2.6.2 bump didn't get applied to existing DBs.

**Comment by noel-yeldos** [comment]
@lache-melvin I tested this in RC branch and did not get the loading spinner. Changing `convert_data_type` showed an error in backend log. Will need a review from someone with more knowledge

**Comment by lache-melvin** [comment]
> @lache-melvin thanks! I tested this in RC branch and did not get the loading spinner. Changing `convert_data_type` showed an error in backend log. Will need a review from someone with more knowledge.

Seeing backend log sounds like you're seeing the code changes I made rather than RC... you sure you didn't start the server on this branch?

**Comment by noel-yeldos** [comment]
> Seeing backend log sounds like you're seeing the code changes I made rather than RC... you sure you didn't start the server on this branch?
Ah sorry I mistyped. I meant to say that I tested on this branch (not on RC)

**Comment by lache-melvin** [comment]
Sounds like correct behaviour then...

File: server/service/src/report/report_service.rs (hunk 2 above)
Comment (andreievg) [reply server/service/src/report/report_service.rs:581]: I kind of like this at the top level, either at the entrypoint to the services or even at end consumer (in graphql, when mapping error I guess), although we are often not adding enough info in the error (like the report name you've added, which should technically be in the report error). 

Happy with this addition, it's an improvement

**Review by andreievg — APPROVED** [review]
Lokos great, thank you !
