### PR TITLE
Soft Delete for Asset Catalogue Items

### LINKED ISSUE #3675: Assets can fail to sync if asset catalogue item is deleted.
## What went wrong? 😲
Assets created with a deleted asset catalogue item don't sync to central server correctly

## Expected behaviour 🤔

Asset catalogue items should be soft deleted to avoid issues with Sync

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Import a new asset catalogue item (On central server)
image

2. Sync your remote site
4. Create an asset on the remote site using the new catalogue item
image
5. Before syncing to central, delete the catalogue item from central
image

6. Sync to central server
7.  Check that the asset show up in the central server

## Your environment 🌱

- Open mSupply Version: 2.0.0-RC

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #3675 

# 👩🏻‍💻 What does this PR do?

Adds soft delete for asset catalogue items.
The prevents a bug with sync if the catalogue item is deleted centrally but used remotely.
See issue for reproduction steps.

## 💌 Any notes for the reviewer?

To add the new column to the database, you'll need to run this command...

`ALTER TABLE asset_catalogue_item add column  deleted_datetime TIMESTAMP;`

# 🧪 Testing

1. Import a new asset catalogue item (On central server)
2. Sync your remote site
4. Create an asset on the remote site using the new catalogue item
5. Before syncing to central, delete the catalogue item from central
6. Sync to central server
7.  Check that the asset show up in the central server

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: .

### CODE REVIEW

File: server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs [hunk 1]
```diff
@@ -74,16 +76,6 @@ impl<'a> AssetCatalogueItemRowRepository<'a> {
         Ok(())
     }
 
-    pub fn insert_one(
```
Comment (jmbrunskill) [inline server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs:77]: Deleted this as it's not being used and makes the code simplier if we always use upsert with Sync

Comment (mark-prins) [reply server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs:77]: 🤔  can you soft delete this?

File: server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs [hunk 2]
```diff
@@ -38,6 +39,7 @@ pub struct AssetCatalogueItemRow {
     pub model: String,
     #[column_name = "asset_catalogue_type_id"]
     pub type_id: String,
+    pub deleted_datetime: Option<chrono::NaiveDateTime>,
```
Comment (clemens-msupply) [inline server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs:42]: Yes please, but didn't we say `is_active` for consistency?

File: server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs [hunk 3]
```diff
@@ -101,9 +93,10 @@ impl<'a> AssetCatalogueItemRowRepository<'a> {
     }
 
     pub fn delete(&self, asset_catalogue_item_id: &str) -> Result<(), RepositoryError> {
```
Comment (clemens-msupply) [inline server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs:95]: Should we call these `soft_delete()`?

File: server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs (hunk 2 above)
Comment (mark-prins) [reply server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs:42]: I know it's messy.. but.. I thought the discussion ended up saying that `deleted_datetime` is the preferred approach and we are using `is_active` to accomodate OG. in this case, we don't sync with OG, so we can use the preferred approach?

**Review by mark-prins — APPROVED** [review]
👍  LGTM!
(pending Clemens commend re `is_active`, that is)

all tested and working. The only thought was how truthful this statement now is:

Screenshot 2024-04-30 at 10 32 22 AM

File: server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs (hunk 3 above)
Comment (jmbrunskill) [reply server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs:95]: I used `mark_deleted` in HSH I think.
I do like the idea of having a slightly different name but want to be consistent too (Where possible)

**Comment by jmbrunskill** [comment]
> 👍 LGTM! (pending Clemens commend re `is_active`, that is)
> 
> all tested and working. The only thought was how truthful this statement now is:
> 
> Screenshot 2024-04-30 at 10 32 22 AM

I agree it's not quite correct but we'd rather people didn't delete something they didn't mean to. Not like is_active which is easy to re-establish. There's no UI to undelete, the soft delete is just for sync and historical records at this stage.

File: server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs (hunk 2 above)
Comment (jmbrunskill) [reply server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs:42]: I'll write up a wiki and get some review from the wider team.

**Comment by mark-prins** [comment]
yep, totally agree. the lack of UI around undeletes means that the message is correct in that sense. It's my strictly literal reading of it that prompted the 🤔

File: server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs (hunk 3 above)
Comment (clemens-msupply) [reply server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs:95]: `mark_deleted` sounds good to me.

I was working on name merge yesterday and there was also a currency soft delete earlier by @roxy-dao

**Review by Chris-Petty — APPROVED** [review]
Noice looks good to me (and trust Mark's test 🙂)

File: server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs (hunk 2 above)
Comment (jmbrunskill) [reply server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs:42]: https://github.com/msupply-foundation/open-msupply/wiki/Code-Review-Comments---Rust#soft-delete
