### PR TITLE
5669 Fix patient lookup failure

### LINKED ISSUE #5669: Patient lookup failure
## What went wrong? 😲

I did a patient lookup, the result list had a patient which is not local, so I click to download it. The response is this:

Screenshot 2024-12-02 at 4 05 51 PM

and looking at the network, I'm getting sync requests firing off continuously:

https://github.com/user-attachments/assets/a76e1c83-577a-445a-b3d9-3d6084ed1010

Here's the GraphQL query and response:

<details>
  <summary>Query</summary>
  
  ```gql
query syncStatus {
  syncStatus: latestSyncStatus {
    ...FullSyncStatus
  }
}

fragment FullSyncStatus on FullSyncStatusNode {
  __typename
  error {
    ...SyncError
  }
  integration {
    ...SyncStatusWithProgress
  }
  isSyncing
  prepareInitial {
    ...SyncStatus
  }
  pullCentral {
    ...SyncStatusWithProgress
  }
  pullRemote {
    ...SyncStatusWithProgress
  }
  push {
    ...SyncStatusWithProgress
  }
  pullV6 {
    ...SyncStatusWithProgress
  }
  pushV6 {
    ...SyncStatusWithProgress
  }
  summary {
    ...SyncStatus
  }
  lastSuccessfulSync {
    ...SyncStatus
  }
}

fragment SyncError on SyncErrorNode {
  __typename
  variant
  fullError
}

fragment SyncStatusWithProgress on SyncStatusWithProgressNode {
  __typename
  finished
  started
  done
  total
}

fragment SyncStatus on SyncStatusNode {
  __typename
  finished
  durationInSeconds
  started
}
  ```
</details>
<details>
  <summary>Response</summary>
  
  ```json
{
  "data": {
    "syncStatus": {
      "__typename": "FullSyncStatusNode",
      "error": {
        "__typename": "SyncErrorNode",
        "variant": "CONNECTION_ERROR",
        "fullError": "Error while pushing remote v6 records -> [\n    \"Sync api error, url: 'http://192.168.1.55:8888/central/sync/push', route: 'push'\",\n    \"Connection problem\",\n    \"error sending request for url (http://192.168.1.55:8888/central/sync/push)\",\n    \"client error (Connect)\",\n    \"tcp connect error: Connection refused (os error 61)\",\n    \"Connection refused (os error 61)\",\n]"
      },
      "integration": null,
      "isSyncing": false,
      "prepareInitial": {
        "__typename": "SyncStatusNode",
        "finished": "2024-12-02T03:06:57.236850+00:00",
        "durationInSeconds": 0,
        "started": "2024-12-02T03:06:57.234662+00:00"
      },
      "pullCentral": null,
      "pullRemote": null,
      "push": null,
      "pullV6": null,
      "pushV6": {
        "__typename": "SyncStatusWithProgressNode",
        "finished": null,
        "started": "2024-12-02T03:06:57.239009+00:00",
        "done": 0,
        "total": 7
      },
      "summary": {
        "__typename": "SyncStatusNode",
        "finished": null,
        "durationInSeconds": 0,
        "started": "2024-12-02T03:06:57.071775+00:00"
      },
      "lastSuccessfulSync": {
        "__typename": "SyncStatusNode",
        "finished": "2024-11-26T04:34:14.412086+00:00",
        "durationInSeconds": 2,
        "started": "2024-11-26T04:34:12.009746+00:00"
      }
    }
  }
}
```
</details>

## Expected behaviour 🤔
Well, a better error message for starters!
and no self-inflicted ddos attack on the graphql endpoint.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

0. Add a patient to a store in mSupply which is not part of your omSupply site

1. Create a patient
2. Enter details of the patient created in step 0
3. Click to download the patient

The issue for me was that my server IP had changed, and the IP of the central server in mSupply was therefore incorrect.
This sounds like an easy way to replicate the problem.

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #5669

# 👩🏻‍💻 What does this PR do?
Add error message when v6 not configured and stop infinite polling feedback loop

Screenshot 2025-01-10 at 4 18 29 PM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Ensure central server is not configured and test from remote site
- [ ] Create a new patient in og msupply
- [ ] Create that same patient in oms 
- [ ] Once search is complete, download patient and fetch patient data
- [ ] See error and see that requests are not being fired off endlessly

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts [hunk 1]
```diff
@@ -27,13 +27,18 @@ export const useFetchPatient = () => {
...
+
   const pollTillSynced = useCallback(async () => {
     while (true) {
       const result = await getSyncStatus();
       if (result?.error) {
         const error = mapSyncError(t, result.error, 'error.unknown-sync-error');
+
         setError(error.error);
-        continue;
+        hasErrored.current = true;
```
Comment (lache-melvin) [inline client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts:39]:
```suggestion
        // Setting a ref here, as `error` state not updated in time for us to within the `mutateAsync`
        hasErrored.current = true;
```

File: client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts [hunk 2]
```diff
@@ -27,13 +27,18 @@ export const useFetchPatient = () => {
   const { mutateAsync: manualSync } = useSync.sync.manualSync();
   const { mutateAsync: getSyncStatus } = useSync.utils.mutateSyncStatus();
 
+  const hasErrored = useRef<boolean>();
```
Comment (lache-melvin) [inline client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts:30]: maybe should call this `hasErroredDuringSync`? Because it doesn't get set from the other errors 🙏

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Naming things 😅 Otherwise looks great 🔥

File: client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts]: Updated here 18a1cd0c27b4858be348ece93a62952cb148cfaa

File: client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts (hunk 2 above)
Comment (noel-yeldos) [reply client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts]: Updated here 18a1cd0c27b4858be348ece93a62952cb148cfaa :)

**Review by lache-melvin — APPROVED** [review]
ship it 🚢
