### PR TITLE
9999 Inbound Shipments report: unable to clear the supplier filter

### LINKED ISSUE #9999: Inbound Shipments report: unable to clear the supplier filter
## What went wrong? 😲

Once Supplier option is selected from a filter dropdown, I am unable to clear it to get back to the general report

https://github.com/user-attachments/assets/abc56927-038f-4815-aed6-c6b38eec6089

## Expected behaviour 🤔

Should be able to clear the filter if you want to see the overall report again

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Upgrade to V2.14.00
2. Go to Reports -> Inbound Shipments
3. Run the report with no suppliers selected -> see all inbound shipments showing
4. Select a supplier -> only filtered inbound shipments show
5. Click on Filters again -> try to clear the selection
6. Unable to -> the choice persists and no way to see the general report unless you close and generate from scratch

## Your environment 🌱

- Open mSupply Version: `V2.14.00`
- Legacy mSupply Central Server Version: `V8.06.12`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #9999

# 👩🏻‍💻 What does this PR do?
Null on change on clear

# 🧪 Testing

- [ ] Generate Inbound or Outbound report
- [ ] Filter by supplier / customer
- [ ] Once report generated, click filter at the top
- [ ] Clear supplier / customer input
- [ ] Should get more results (if you have any)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Name/Components/CustomerSearchInput/CustomerSearchInput.tsx [hunk 1]
```diff
@@ -52,6 +52,15 @@ export const CustomerSearchInput = ({
         setBuffer(name);
         onChange(name);
       }}
+      onInputChange={(
+        _event: React.SyntheticEvent<Element, Event>,
+        _value: string,
+        reason: string
+      ) => {
+        if (reason === 'clear') {
```
Comment (mark-prins) [inline client/packages/system/src/Name/Components/CustomerSearchInput/CustomerSearchInput.tsx]: for no practical reason.. but a pedantic tidiness one.. what about creating an enum for the 7 instances that we check for reason === 'clear'?
