### PR TITLE
7511 Fix unable to save stocktake line for an item

### LINKED ISSUE #7511: Stocktake not letting you enter a stockline with error stockline already exist in stocktake
## What went wrong? 😲

https://github.com/user-attachments/assets/9704233a-4915-4d1f-9c3a-e60e35dfcd17

Right now when you go into stocktake and uncheck the "count this line" it will not let you enter the stock in. The only way to work around is you have to search with item filter and then enter the item in and it will not have the error message "stock line already exist in stocktake".

Not sure why the first way of doing it that it does not allow you to enter and says "stockline already exists in stock" - it should be able to let you do both ways, as users would not know to filter for the item and enter it in.

datafile is on the demo-open server (central tamaki warehouse)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #7511 

# 👩🏻‍💻 What does this PR do?

The problem was that if some of the stock_lines for the item you are editing are on a separate page in the API response, the UI doesn't know that the stock line has been created and there for 

## 💌 Any notes for the reviewer?

This fix feels a bit messy, I feel like an upsert from the backend might be a nice solution but it's a big change.
A slightly nicer solution would be to add an item_id filter to stocktake lines rather than relying on the existing itemNameOrCode filter.

Didn't do either of those right now to keep the fix small.

# 🧪 Testing

See testing steps in issue to re-create...

- [ ] Try editing stocktake lines where the lines for item item span across the pages of the stock take.
- [ ] Try adding new lines
- [ ] Try editing existing lines
- [ ] Basically try to find if there's a scenario where this fix doesn't work!

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [X] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeLines.ts [hunk 1]
```diff
@@ -2,11 +2,23 @@ import { useQuery, useUrlQueryParams } from '@openmsupply-client/common';
...
 import { useStocktakeNumber } from '../document/useStocktake';
 
-export const useStocktakeLines = (id: string) => {
+export const useStocktakeLines = (id: string, itemCode?: string) => {
   const { queryParams } = useUrlQueryParams({
     initialSort: { key: 'itemName', dir: 'asc' },
     filters: [{ key: 'itemCodeOrName' }],
   });
+
+  if (itemCode) {
```
Comment (jmbrunskill) [inline client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeLines.ts:11]: The existance of itemCode changes the behaviour of this hook quite a bit.
Maybe should be a seperate hook? or we could look at one of the other solutions I mention in the issue.

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useDraftStocktakeLines.ts [hunk 2]
```diff
@@ -8,7 +8,7 @@ export const useDraftStocktakeLines = (
 ): [DraftStocktakeLine[], Dispatch<SetStateAction<DraftStocktakeLine[]>>] => {
   const { id } = useStocktake.document.fields('id');
   const { data: stockLines } = useStockLines(item?.id || '');
-  const { lines } = useStocktake.line.rows();
+  const { lines } = useStocktake.line.rows(item?.code);
```
Comment (jmbrunskill) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useDraftStocktakeLines.ts:11]: Using itemCode here as theres isn't an item_id filter in the backend yet.
Should I add it? Or is there a better overall solution?

File: client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts [hunk 3]
```diff
@@ -15,9 +15,12 @@ const getStocktakeItems = (lines: StocktakeLineFragment[]) =>
     } as StocktakeSummaryItem;
   });
 
-export const useStocktakeRows = () => {
+export const useStocktakeRows = (itemCode?: string) => {
   const { data: stocktake } = useStocktake.document.get();
-  const { data: lineData, isLoading } = useStocktakeLines(stocktake?.id ?? '');
+  const { data: lineData, isLoading } = useStocktakeLines(
```
Comment (jmbrunskill) [inline client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts:20]: Maybe we need something like this?
```suggestion
  const { data: lineData, isLoading } = useStocktakeLinesForItem(
```

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useDraftStocktakeLines.ts (hunk 2 above)
Comment (jmbrunskill) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useDraftStocktakeLines.ts:11]: There's a risk that we item/code filter an item name might match a code or visa-versa, so I think correct would be to use the item_id

**Comment by jmbrunskill** [comment]
> Looks good. Took me a minute to figure out what was going on, but it makes sense. Only thing would be to add a filter by ID, as you suggested. How long do you think that would take? If it's quick I think it'd be worth doing, but otherwise can leave it for now.

Not too long will jump on it now

File: client/packages/common/src/types/schema.ts [hunk 4]
```diff
@@ -4248,6 +4248,7 @@ export type MasterListNode = {
   __typename: 'MasterListNode';
   code: Scalars['String']['output'];
   description: Scalars['String']['output'];
+  discountPercentage: Scalars['Float']['output'];
```
Comment (jmbrunskill) [inline client/packages/common/src/types/schema.ts:4251]: Unrelated but schema must not have been updated properly before

**Review by CarlosNZ — APPROVED** [review]
Nice, LGTM 👍
