### PR TITLE
5400 disallow negative numbers in store properties

### LINKED ISSUE #5400: iSC/GAPS/Cold chain: Can enter meaningless negative numbers when editing GAPS Store Properties
## What went wrong? 😲

I don't think any of those fields supposed to allow negative value input yet the users are able to enter & save them

Screenshot 2024-11-14 at 12 18 04 PM

## Expected behaviour 🤔

No negative values allowed

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Settings -> Configuration -> Initialise GAPS
2. Click on the edit button next to your store at the bottom
3. See new window pop up: enter negative numbers & click Save
4. The action is allowed

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome browser

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #5400

# 👩🏻‍💻 What does this PR do?

Prevent negative values being entered for numeric properties. Adds option for using `allowedValues` to permit negative values for a particular property, but none of the existing ones need this.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Initialise GAPS store properties
- [ ] Try to enter a number less than 0 in one of the number fields
- [ ] Same in asset details

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/PropertyInput/PropertyInput.tsx [hunk 1]
```diff
@@ -48,7 +48,7 @@ export const PropertyInput: FC<PropertyInput> = ({
         <NumericTextInput
           value={valueInt ?? 0}
           fullWidth
-          allowNegative
+          allowNegative={allowedValues?.includes('negative')}
```
Comment (roxy-dao) [inline client/packages/common/src/ui/components/inputs/PropertyInput/PropertyInput.tsx:51]: Would this be saved as `negative` in allowed values or `Negative`?

**Review by roxy-dao — APPROVED** [review]
LGTM~
