### PR TITLE
8969 update vaccination tables

### LINKED ISSUE #8969: Allow administering later doses when first dose not given
## What went wrong? 😲

The system restricts users from administering a dose if the previous dose in the vaccine course has not been administered. 

Image

However, in the real-world they do this. 

For example, if a patient doesn't receive a bOPV vaccination at birth (bOPV0) they are considered to have missed it and they skip to the next dose when they next visit (bOPV1)

Here is an example on paper

Image

## Expected behaviour 🤔

System should only warn user about giving doses out of order, not restrict the user. 

### Agreed rules

(Adding this here for clarity around expectations)

- Will be a per-vaccine-course preference
- Will receive UI warning dialog when administering a dose that is not the next in the sequence
- Will automatically apply "Not given" to all skipped doses
- Will only be able to edit the most recently applied (given or not given) dose (same as current behaviour)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Mark the 1st dose of a vaccine course as not given
2. Attempt to mark the next dose as given

## Your environment 🌱

- Open mSupply Version: 2.9.2

Money Works Code: SSUNI2OMD

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #8969 -- migrates the table to the new table pattern

# 👩🏻‍💻 What does this PR do?

Replicates the VaccinationCard table using the new table pattern:

**PREVIOUS**:
Screenshot 2025-10-15 at 2 56 39 PM

**NEW:**
Screenshot 2025-10-15 at 4 11 47 PM

## 💌 Any notes for the reviewer?

Fairly straightforward but matching the styling was a bit of a challenge -- I had to extend the table infrastructure to handle proper merging of props -- so we could add row and cell styling without overriding the table default styles.

# 🧪 Testing

- [ ] Vaccination Card table looks and behaves the same as it did before, but with the new table functionality

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/material-react-table/utils.ts [hunk 1]
```diff
@@ -20,24 +20,28 @@ type MuiTableBodyCellPropsParams<TData extends Record<string, any>> = {
...
+    | ((params: MuiTableBodyCellPropsParams<TData>) => TableCellProps),
   params: MuiTableBodyCellPropsParams<TData>
 ): TableCellProps => {
   const { table } = params;
   const globalPropsOption = table.options.muiTableBodyCellProps;
 
-  // Resolve global props if it's a function
+  const resolvedCustomProps =
+    typeof customProps === 'function' ? customProps(params) : customProps || {};
+
```
Comment (CarlosNZ) [inline client/packages/common/src/ui/layout/tables/material-react-table/utils.ts]: Changed to allow customProps to be the functional type as well (which they are in the VaccinationCard table, as the style is conditional on the column)

**Review by jmbrunskill — APPROVED** [review]
Looks good
