### PR TITLE
6070 Localise ledger date + fix adjustment calculation

### LINKED ISSUE #6070: Localise ledger date + fix adjustment calculation
## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6070

# 👩🏻‍💻 What does this PR do?
Fix calculation for ledger adjustment + localise date

# 🧪 Testing

- [ ] Have `use consumption data from customers` pref on
- [ ] Create an IO at a store that is a supplying store for another customer
- [ ] Add an item line that has previous requisitions made for it in the same period (note should have other data such as IA + Inbound/Outbound Shipments for this item in the same period)
- [ ] Check the adjustment column for this item for the store (table at the bottom of the input). The calculation should be for period: Delivered Inbound - Verified Outbound + IA (any reductions/additions)

Second:
- [ ] Change timezone and make sure the date is correct with OG

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx [hunk 1]
```diff
@@ -53,6 +53,7 @@ const ItemLedgerTable = ({
         label: 'label.date',
         format: ColumnFormat.Date,
         sortable: false,
+        accessor: ({ rowData }) => localisedDate(rowData.datetime),
```
Comment (lache-melvin) [inline client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx:56]: this one isn't needed (already done by `columnFormat.date` and adding it is banging up the display, date column type can't be string like this 😅

**Review by lache-melvin — APPROVED** [review]
🚀
