### PR TITLE
Fix minor sync UI bug

### LINKED ISSUE #10934: Setup graphql subscriptions
## The suggestion

Currently in the codebase the frontend uses polling for several APIs like
 - DB migration status
 - Sync
 - Initialisation status
 - Temp sensor notifications

I would like to see these APIs replaced with graphQL subscriptions (might use websockets, server sent events or long polling depending on implementation). This would reduce unnecessary requests from the client to the server and also show information as its made available.

### Are there any risks associated with this change?

Need to investigate compatibility with caddy

### How much effort is required?

Medium

### Agreed Solution
TBD

### PR DESCRIPTION
**Pull request by aneeshthunga26**
Fixes #10934

# 👩🏻‍💻 What does this PR do?

Cleans up a minor bug regarding showing stale data in the subscription modal.

Sync badge used to show the correct info eg. '5' but the sync modal would show 'there are no records to push'. After the change both modal and badge show the correct info:
image

## 💌 Any notes for the reviewer?
In `useSubscrition` - the hook for graphql subscriptions this change adds changes for cleaning up data so when a component mounts/un-mounts or toggles the enabled flag it will always refetch fresh data

# 🧪 Testing

- [ ] Make changes that trigger the sync badge to show number of records to push (e.g adding stock)
- [ ] Open sync modal
- [ ] Verify Modal is showing up-to-date info

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [x] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/api/hooks/useSubscription.ts [hunk 1]
```diff
@@ -59,6 +59,7 @@ export const useSubscription = <TSubscription, TData>({
   useEffect(() => {
     if (!enabled || (requireAuth && !token)) {
       setIsSubscribed(false);
+      setData(undefined);
```
Comment (andreievg) [inline client/packages/common/src/api/hooks/useSubscription.ts:62]: Why is this needed for this PR ? What is the use case for this one ? 

I think a good description about 'what' was changed and why in the PR would be helpful.

Similar to the setData in the return statement. 

To me it sounds like the only change is the cache key ? But how did it work previously ?

Comment (aneeshthunga26) [reply client/packages/common/src/api/hooks/useSubscription.ts:62]: The reason why we are setting data back to undefined here is because in the call site (useSyncInfo, useSyncStatus etc.) it uses the data fetched from useQuery when the data from subscription undefined. This is just a cleanup mechanism for when a component mounts, or is enabled in the case of a modal it would refetch the fresh data from db.

File: client/packages/common/src/api/hooks/useSubscription.ts [hunk 2]
```diff
@@ -105,6 +106,7 @@ export const useSubscription = <TSubscription, TData>({
     return () => {
       disposed = true;
       setIsSubscribed(false);
+      setData(undefined);
```
Comment (aneeshthunga26) [inline client/packages/common/src/api/hooks/useSubscription.ts:109]: Same here, cleaning up data from useSubscription, when useEffect cleans up

File: client/packages/system/src/Sync/api/hooks/utils/useSyncStatus.ts
Comment (aneeshthunga26) [inline client/packages/system/src/Sync/api/hooks/utils/useSyncStatus.ts:40]: useSyncInfo has the same nullish-coalescing. This is why we set data back to undefined when not enabled and useEffect cleanup function

**Review by aneeshthunga26 — COMMENTED** [review]
@andreievg The main reason is cleaning up data so when a component mounts/un-mounts or toggles the enabled flag it will always refetch fresh data

**Review by andreievg — APPROVED** [review]
After some discussion with Aneesh, it's the 'enabled' parameter change that is causing the issue. I can't actually reason about the logic when I look at it, i don't know when isSubscribed has a value, when useQuery will fetch, does it fetch the first time and then isSubscribed fired, would isSubscribed get the current value or any changes to the value. 

I think this logic can be consolidated in a follow up issue to useSubscriptionOrPoll. token should be mandatory (if it doesn't exist don't mount/render), enabled should also be handled upstream. 

It sounds like it should be safe to merge this work though

**Comment by aneeshthunga26** [comment]
> I think this logic can be consolidated in a follow up issue to useSubscriptionOrPoll. token should be mandatory (if it doesn't exist don't mount/render), enabled should also be handled upstream.

Will add it to the follow up ticket. Currently during `Initialisation` token will not exist as they haven't authenticated yet - can be discussed when working on the follow up
