### PR TITLE
Cold chain : various issues

### LINKED ISSUE #2436: Cold chain follow up
## What went wrong? 😲
 
~Two~ ~Three~ Four small things to address now that cold chain has been merged
- [x] Permissions for the notification query
- [x] Alignment of monitoring no-data message
- [x] No filters for chart view
- [x] Breach Log: duration is incorrectly calculated (?) and no temperature data

### Permissions
If the user does not have permission to the notification query then they get an unhelpful permission denied error shown, with no reason. The cause is this:

Screenshot 2023-11-04 at 8 55 26 AM

The notification bar is checking for breaches, but the user does not have permission to query. 
In this case the vaccine store permission was not even enabled!
Two changes:
- check the store permission and if cold chain is not used, do not query
- swallow any errors with the notification bar query

### Alignment
Some padding please:
Screenshot 2023-11-04 at 8 57 50 AM

### Breach Duration
Screenshot 2023-11-06 at 9 56 14 AM

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Un-grant permission to query sensors
2. View any page

1. View the chart and breach pages

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #2436 

# 👩🏻‍💻 What does this PR do? 
 
Some minor issues with cold chain work
- Permission and preference handling
- A better no-data message on the chart
- Adding filters to the chart view
- Breach duration display

Also noticed that the breach duration was being sent as seconds but stored in a column called 'milliseconds'. Have updated the API to store as milliseconds.

Other changes are commented in this PR

# 🧪 How has/should this change been tested? 

For a store which does not use cold chain, remove the user permission to view sensors. Currently, changing to this store would show an error. This PR will remove the breach API call and therefore the error.

Now remove permission to view sensors within a store that does use cold chain. 
This will now show an error when you browse to the breaches tab, but will not show an error on the site generally.

The breach duration in the breaches list view has been updated: the heading is just 'duration' (not 'duration (minutes)') and the message shown is more accurate ( it was showing only the minutes and seconds value of the datetime difference e.g. `02:03:04` would show as `03:04` ) It nows shows 'about 3 minutes'

The 'Nothing here' image is shown instead of the chart if there is no data to display.

Screenshot 2023-11-06 at 11 50 24 AM

Filters are added to the temperature chart.

## 📃 Documentation

- [ ] To be updated as part of the cc docs

### CODE REVIEW

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx [hunk 1]
```diff
@@ -18,6 +21,41 @@ import {
 import { BreachTypeCell } from '../../../common';
 import { Toolbar } from './Toolbar';
 
+const DurationCell = ({ rowData }: CellProps<TemperatureBreachFragment>) => {
+  const t = useTranslation('coldchain');
+  const { localisedDistance } = useFormatDateTime();
+  const duration = !rowData.endDatetime
+    ? t('label.ongoing')
+    : localisedDistance(rowData.startDatetime, rowData.endDatetime);
```
Comment (mark-prins) [inline client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx:29]: using the start and end dates, so that I can use the `formatDistance` fn from date-fns. That's easier than converting the milliseconds to something that `formatDuration` will accept.
It also means that what the user can see is the start, end, duration : all of which will be consistent with each other.

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx [hunk 2]
```diff
@@ -75,117 +85,109 @@ export const TemperatureChart = () => {
...
-                  strokeWidth={4}
-                />
-              ))}
-            </ComposedChart>
-          </ResponsiveContainer>
-        ) : (
-          <Typography width={450}>{t('error.no-data')}</Typography>
-        )}
-      </Box>
+  if (isLoading) {
```
Comment (mark-prins) [inline client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx:88]: just a little early-return-refactor; as the ternary conditions are hard to read

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx [hunk 3]
```diff
@@ -75,117 +85,109 @@ export const TemperatureChart = () => {
...
+    return <BasicSpinner />;
+  }
+
+  if (!hasData) {
+    return <NothingHere body={t('error.no-temperature-logs')} />;
```
Comment (mark-prins) [inline client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx:93]: looks nicer, rather than having plain text on the page

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx [hunk 4]
```diff
@@ -195,3 +197,19 @@ export const TemperatureChart = () => {
     </Box>
   );
 };
+
+export const TemperatureChart = () => {
```
Comment (mark-prins) [inline client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx:201]: new wrapper component, so that I can easily show the toolbar, with filter, regardless of whether data is available or not. If the filters are set, so that no data is returned, we still want the filter to show.

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/Toolbar.tsx [hunk 5]
```diff
@@ -52,7 +52,7 @@ export const Toolbar: FC<{ filter: FilterController }> = () => {
             },
             {
               type: 'enum',
-              name: t('label.type'),
+              name: t('label.breach-type'),
```
Comment (mark-prins) [inline client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/Toolbar.tsx:55]: renamed the filter - just `type` by itself is different from figma and not very helpful

File: client/packages/coldchain/src/Monitoring/api/TemperatureBreach/hooks/document/useTemperatureBreachNotifications.ts [hunk 6]
```diff
@@ -0,0 +1,14 @@
+import { useTemperatureBreachApi } from '../utils/useTemperatureBreachesApi';
+import { useQuery } from '@openmsupply-client/common';
+import { ListParams } from '../../api';
+
+// Fetches temperature breaches, without raising a permission denied error if one is returned by the API
+export const useTemperatureBreachNotifications = (queryParams: ListParams) => {
```
Comment (mark-prins) [inline client/packages/coldchain/src/Monitoring/api/TemperatureBreach/hooks/document/useTemperatureBreachNotifications.ts:6]: new hook which ignores errors - if the breach api call fails due to permissions, we don't want to notify users that something they didn't ask for has gone wrong

File: client/packages/coldchain/src/Monitoring/api/TemperatureBreach/hooks/document/useTemperatureBreaches.ts [hunk 7]
```diff
@@ -1,11 +1,19 @@
...
+import { AuthError, LocalStorage, useQuery } from '@openmsupply-client/common';
 import { ListParams } from '../../api';
 
 export const useTemperatureBreaches = (queryParams: ListParams) => {
   const api = useTemperatureBreachApi();
 
-  return {
-    ...useQuery(api.keys.paramList(queryParams), api.get.list(queryParams)),
-  };
+  return useQuery(api.keys.paramList(queryParams), () =>
```
Comment (mark-prins) [inline client/packages/coldchain/src/Monitoring/api/TemperatureBreach/hooks/document/useTemperatureBreaches.ts:8]: this one though, still needs to tell the user that they do not have permission to view breaches

File: client/packages/common/src/intl/locales/fr/common.json [hunk 8]
```diff
@@ -130,6 +130,7 @@
   "label.num-stocktake-packs": "Stock Théorique (boites)",
   "label.number": "Numéro",
   "label.on-hold": "Bloqué?",
+  "label.ongoing": "En cours",
```
Comment (mark-prins) [inline client/packages/common/src/intl/locales/fr/common.json:133]: added so that I could test. possibly not helpful? Richard did say it was ok 🤷

File: server/server/src/cold_chain/temperature_breach.rs [hunk 9]
```diff
@@ -126,8 +126,8 @@ fn upsert_temperature_breach(
             breach.start_unix_timestamp
         ))?;
 
-    let duration_milliseconds = match breach.end_unix_timestamp {
-        Some(end_unix_timestamp) => (end_unix_timestamp - breach.start_unix_timestamp)
+    let duration_milliseconds: i32 = match breach.end_unix_timestamp {
+        Some(end_unix_timestamp) => ((end_unix_timestamp - breach.start_unix_timestamp) * 1000)
```
Comment (mark-prins) [inline server/server/src/cold_chain/temperature_breach.rs:130]: the value which comes from the CCA is in seconds 🙄

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx (hunk 1 above)
Comment (andreievg) [reply client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx:29]: Sounds good.

> It also means that what the user can see is the start, end, duration : all of which will be consistent with each other.

Although I think this will be consistent right ? (mSupply Cold Chain would send it correctly ?) And I guess filtering would work on duration column in database and I guess it should still be consisten ?

File: server/server/src/cold_chain/temperature_breach.rs (hunk 9 above)
Comment (andreievg) [reply server/server/src/cold_chain/temperature_breach.rs:130]: In this case, do we need duration field in schema (we would for filtering ?) ? Or does it have to be in milliseconds.. we need to check that fridge tag integration is correct

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx (hunk 3 above)
Comment (andreievg) [reply client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx:93]: Also a big fin on early return rather then inline condition (where possible)

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx [hunk 10]
```diff
@@ -195,3 +197,19 @@ export const TemperatureChart = () => {
...
+  const { breachConfig, filter, hasData, isLoading, sensors } =
+    useTemperatureChartData();
+  return (
+    <>
+      <Toolbar filter={filter} />
```
Comment (andreievg) [inline client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx:206]: Ohh, so current filter toolbar is inside the tab selection (rather then above it ?)

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts [hunk 11]
```diff
@@ -9,10 +9,21 @@ const MAX_DATA_POINTS = 30;
...
 export const useTemperatureChartData = () => {
   const theme = useTheme();
-  const {
-    queryParams,
-  } = useUrlQueryParams({
-    initialSort: {key: 'datetime', dir: 'desc'},
+  const { filter, queryParams } = useUrlQueryParams({
+    initialSort: { key: 'datetime', dir: 'desc' },
+    filters: [
+      { key: 'datetime', condition: 'between' },
```
Comment (andreievg) [inline client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts:15]: Should this be consolidated with ListView ?

https://github.com/msupply-foundation/open-msupply/blob/c57b07040c13979ca5ffc37af229bde7620b90f8/client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx#L25-L41

File: client/packages/host/src/components/AppBar/AppBar.tsx [hunk 12]
```diff
@@ -26,10 +27,12 @@ const StyledContainer = styled(Box)(({ theme }) => ({
 export const AppBar: React.FC = () => {
   const { ref } = useAppBarRect();
   const isDashboard = useMatch(AppRoute.Dashboard);
+  const { store } = useAuthContext();
+  const hasVaccineModule = store?.preferences.vaccineModule ?? false;
 
   return isDashboard ? (
     <>
-      <ColdchainNotification />
+      {hasVaccineModule && <ColdchainNotification />}
```
Comment (andreievg) [inline client/packages/host/src/components/AppBar/AppBar.tsx:35]: Should this be common for both ?

Comment (andreievg) [reply client/packages/host/src/components/AppBar/AppBar.tsx:35]: And would this be the place to check permissions ? Rather then in API ?

**Review by andreievg — APPROVED** [review]
Thanks Mark, looks good, I have a few comments, although they don't really stop PR approval, I think below can be discussed, put in new issues at some point.

Filters don't really work as I would expect, I think we rushing this as a feature vs a bug fix in RC:
* Would expect to see aggragated view of from/to date (but it's paginated to 20), I guess this would come when aggegated chart data is done (I didn't actually think of the aggregated view with filters, this might add a bit more complexity and would be very hard to do)
* A bit concerend about the way we doing filters, looking for [datetime ](https://github.com/msupply-foundation/open-msupply/blob/c57b07040c13979ca5ffc37af229bde7620b90f8/client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts#L180) inside the field name to determine it's a date/time filter ? Also we don't really have type safety for filters, and requires a bit of manual testing that we can reduce/avoid with typescript ?  Also not a fan of splitting fields for nested fitler like 'sensor.name'.
* Should fitler dissapear once it's cleared ?
* Should sensor name be a filter dropdown (or we don't have those yet?)


I was wondering about notifications, were we not suppose to just do exposures, vs breaches (since breach notification is too late) ? Also was that beyond mvp ? Current berligner data just has unacknowledged breaches, with no way to acknowledge them in UI, so a constant breach.

I think we need another API for cold chain notifications, rather then front end figuring it out manually ?

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx:29]: it will be consistent yeah. and there is no sort or filter on duration currently.. so we are ok with that

File: server/server/src/cold_chain/temperature_breach.rs (hunk 9 above)
Comment (mark-prins) [reply server/server/src/cold_chain/temperature_breach.rs:130]: actually, we don't need duration in the schema. might just take that out.

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx (hunk 10 above)
Comment (mark-prins) [reply client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx:206]: No - it's in the usual place, above the tab selection. The toolbar is using a Portal to render, so it shows in a location which differs from where it's declared

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts (hunk 11 above)
Comment (mark-prins) [reply client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts:15]: yeah, I think it should - the breach filters differ slightly, but the log and chart ones are exactly the same.

**Comment by mark-prins** [comment]
> Should filter disappear once it's cleared ?

There was both 'clear' and 'remove' buttons in one version of the filters. I argued for a 'clear' only, since that removes the impact of the filter, so is kinda the same but without the possible confusion for users - having both clear and remove. less cluttered ui too. Personally, I like using this version, it allows me to clear some text and type in something else. Might not suit everyone tho

> Should sensor name be a filter dropdown (or we don't have those yet?)

Yes! I was finding that annoying - having only a few sensors and needing to copy and paste the name. a drop down would be better. Possibly not so useful if you have a lot of sensors and you want to search for the start of a name?

> I was wondering about notifications, were we not suppose to just do exposures, vs breaches

nuts. might have forgotten what we decided about that. We don't have breach config from CCA, so there's no way to know if a temp is an excursion unfortunately. All we've got is the breaches which the CCA gives us. We should discuss this one

> I think we need another API for cold chain notifications, rather then front end figuring it out manually ?

genius. that's a much nicer solution. 


I'll make a few changes to this PR and will need to have a chat and maybe make some new issues 🙏

**Comment by mark-prins** [comment]
🙏  thanks for review @andreievg 
I've made a few changes, would you mind having another look? the new notification endpoint involved a few files. it's a nicer approach though.

One addition: I didn't like just swallowing the error, so I've popped up a warning if the notification query fails for some reason. Shouldn't happen: if a site is configured to use cold chain, then users should have access to view.. but just in case..

**Comment by andreievg** [comment]
@mark-prins, thanks for the changes, I started re reviewing but there are compilation errors, and tbh it's a bit more diff then I expected. Do you think it would be better to do the notification update as a feature in develop (and just keep existing original change as a hot fix in 1.5.0 ?).

Was also wondering if we need to have a chat about how notifications will be handled, and how excursion limits are applied etc before doing further notification work ? Sorry I know you've done a lot of work on this already, but I am just unsure about how much of this applies to excursion notifications. Will be happy to review this change in develop though, and maybe start a conversation there ? (Btw, i think breaches should make their way to notification eventually, but maybe when we can acknowledge them manually in omSupply, or at least when berlinger breach acknowledgment is parse from the fridgetag file).

And sorry, I didn't quite elaborate, my though on the new notification endpoint was meant to be pending and issue/discussion.

> There was both 'clear' and 'remove' buttons in one version of the filters. I argued for a 'clear' only, since that removes the impact of the filter, so is kinda the same but without the possible confusion for users - having both clear and remove. less cluttered ui too. Personally, I like using this version, it allows me to clear some text and type in something else. Might not suit everyone tho

Oki, that makes sense.

> Yes! I was finding that annoying - having only a few sensors and needing to copy and paste the name. a drop down would be better. Possibly not so useful if you have a lot of sensors and you want to search for the start of a name?

As per our discussion earlier, autocomplete drop down would be amazing.

> nuts. might have forgotten what we decided about that. We don't have breach config from CCA, so there's no way to know if a temp is an excursion unfortunately. All we've got is the breaches which the CCA gives us. We should discuss this one

Yeah i think we also said just hard code 2 and 8 for excursions, but you are right for testing it would be nicer to get values from configs, but we don't quite have config->sensor association, so some further thinking is required to do it properly, I think that's why 2 and 8 were considered as hard coded for now (since that applies to all of our existing deployment, but we didn't quite think of testing)

**Comment by mark-prins** [comment]
thanks @andreievg - will take out the extra bits and make new issues 🙏

**Comment by mark-prins** [comment]
> but there are compilation errors

not seeing any errors in this branch - just the conflict which has now come in 🤷
