### PR TITLE
7498 translate pending encounter to fr

### LINKED ISSUE #7498: Translate pending encounters
## What went wrong? 😲

Please translate the `Pending Encounters` report title here to be `Suivi des visites`

## Expected behaviour 🤔
That report names be translated (this one is hard coded in English)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #7498

# 👩🏻‍💻 What does this PR do?
- Change code for pending encounters, too generic
- Drops any report that has code = encounters (should only be this one 👀 )
- Translate pending encounters to french

# 🧪 Testing

- [ ] Should only have one pending encounters report if upgrading
- [ ] Pending encounters should be translated to French

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/repository/src/migrations/v2_07_00/drop_encounters_report.rs [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+impl MigrationFragment for Migrate {
+    fn identifier(&self) -> &'static str {
+        "drop_encounters_report"
+    }
+
+    fn migrate(&self, connection: &StorageConnection) -> anyhow::Result<()> {
+        sql!(
+            connection,
+            r#"
+                DELETE FROM report WHERE code = 'encounters';
```
Comment (roxy-dao) [inline server/repository/src/migrations/v2_07_00/drop_encounters_report.rs:14]: The pending encounters report should be the only report using this code 👀

File: standard_reports/encounters/latest/report-manifest.json [hunk 2]
```diff
@@ -1,7 +1,7 @@
 {
   "is_custom": false,
-  "version": "2.6.3",
-  "code": "encounters",
+  "version": "2.6.4",
+  "code": "pending-encounters",
```
Comment (roxy-dao) [inline standard_reports/encounters/latest/report-manifest.json:4]: encounters too generic. Name should reflect what the report does

File: client/packages/common/src/intl/locales/fr/common.json [hunk 3]
```diff
@@ -1742,6 +1742,7 @@
   "reason.stored": "Stocké",
   "reason.unknown": "Inconnu",
   "replenishment": "Approvisionnement",
+  "report-code.pending-encounters": "Suivi des visites",
```
Comment (mark-prins) [inline client/packages/common/src/intl/locales/fr/common.json:1745]: There's an [existing translation](https://github.com/msupply-foundation/open-msupply/blob/v2.7.0-RC/client/packages/common/src/intl/locales/fr/common.json#L1817) for this. I'm wondering why it doesn't show in this PR?

can you move this to fr-DJ please? the request came through from Samira and there's some question about the translation made.

**Review by mark-prins — COMMENTED** [review]
awesome! 🙏  thanks Roxy 🫶 

pending the result of the translation chat w Pauline.. and maybe the need to move to fr-DJ

File: client/packages/common/src/intl/locales/en/common.json [hunk 4]
```diff
@@ -1977,16 +1981,13 @@
...
   "warning.check-before-vaccinating": "Vaccination records from other stores may not be up to date. Ensure you have synced recently, and always confirm against the patient's physical vaccination card first.",
   "warning.field-not-parsed": "{{field}} not parsed",
-  "warning.nothing-to-supply": "Nothing left to supply!",
-  "tooltip.defined-by-gs1-matrix": "Defined by GS1 datamatrix",
-  "label.cannot-edit-invoice": "Cannot edit invoice",
-  "label.cannot-add-item-to-shipment": "Cannot add items to shipment",
-  "error.cannot-add-from-masterlist-if-not-new": "Can only add from master list on 'New' invoice"
-}
+  "warning.nothing-to-supply": "Nothing left to supply!"
+}
```
[the remark this answers is not in the document]
Comment (roxy-dao) [reply client/packages/common/src/intl/locales/en/common.json:1993]: Yup >.>

File: client/packages/common/src/intl/locales/fr/common.json (hunk 3 above)
Comment (roxy-dao) [reply client/packages/common/src/intl/locales/fr/common.json:1745]: cause it's been changed to `report-code` instead of `report` in [this issue](https://github.com/msupply-foundation/open-msupply/pull/7268) 🙄

**Review by mark-prins — APPROVED** [review]
Looks lovely and works like a charm! ty Roxy!
