### PR TITLE
6287 fix missing item value

### LINKED ISSUE #6287: Prescription edit - selected item name does not display
## What went wrong? 😲

Image

Whoops, am assuming this is a result of #6228, sorry I tested in modal and internal order view but didn't think about prescription 🙈 

Looks like this is a custom input implementation which is now not mapping the selected item state correctly...

## Expected behaviour 🤔

Once i select an item, it shows in the input

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Prescriptions detail view
2. Click add item
3. Select an item from the dropdown
4. See error - no item displayed

## Your environment 🌱

- Open mSupply Version: develop 2.6
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### LINKED ISSUE #6291: Item search input glitches off screen then readjusts itself and input disabled for existing lines with selection opened
## What went wrong? 😲

https://github.com/user-attachments/assets/e86adbcb-3464-40bc-b3e1-f25cacb442c8

## Expected behaviour 🤔
Shouldn't jump. Input should be disabled for existing lines without the selection opened.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inbound/Outbound/Stocktake anywhere you can select item
2. See glitchy off screen before re-adjusting

## Your environment 🌱

- Open mSupply Version: 2.6
- Legacy mSupply Central Server Version: 

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #6287
Maybe? fixes #6291 @roxy-dao I can't replicate?

# 👩🏻‍💻 What does this PR do?

Screenshot 2025-01-29 at 12 43 38 PM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to any edit view with a selected item (e.g prescription line edit, stocktake line edit ETC)
- [ ] You can see the selected disabled item

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 1]
```diff
@@ -73,6 +73,10 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
     [selectedCode]
   );
 
+  useEffect(() => {
+    if (currentItem && search === '') setSearch(getOptionLabel(currentItem));
+  }, [currentItem]);
```
Comment (lache-melvin) [inline client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx:78]: Now that we manage independent search value (to allow for backspacing etc) 

search value was getting updated when you selected an item from the dropdown, but not when a currentItemId was passed in!

**Review by CarlosNZ — APPROVED** [review]
LGTM, thanks :) 

Tested as many ways I can think of in Prescription selector, can't find any probs 👍
