### PR TITLE
3085 Tetum translation FE errors

### LINKED ISSUE #3085: Tetum translation FE errors
## What went wrong? 😲

- [ ] The button in the bottom right of an inbound shipment to change status failing to localise and becoming unusable. image
- [ ] As are additional options 
image
- [ ] Adding an item to an outbound shipment image
  - [ ] {{numeru}} under the ddl for items
  - [ ] On hold column header
  - [ ] {{unidade}}
- [ ] All of these:
image

## Expected behaviour 🤔

Localised like pros.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open an inbound shipment
2. Change language to tetum
3. SHOCK

## Your environment 🌱

- Version: 1.7 dev
- Platform:
  - Firefox
  - SQLite3

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3085 

# 👩🏻‍💻 What does this PR do? 
Fix tet translation expressions.

# 🧪 How has/should this change been tested? 
- [ ] Check that status translation in shipments are translating correctly correct
- [ ] Check that units are being translated correctly

## 💌 Any notes for the reviewer?
Probably should let translators know that they shouldn't translate what is in the double curly braces. Also, didn't do any translation in this PR since I don't know Tetum. Spoke to Pauline and she said she would put it on Lawrence's radar (:

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/ListView/Toolbar.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const Toolbar: FC<{
         />
       </Box>
 
-      <DropdownMenu label="Select">
+      <DropdownMenu label={t('label.actions')}>
```
Comment (roxy-dao) [inline client/packages/requisitions/src/RequestRequisition/ListView/Toolbar.tsx:56]: Changed these two to be consistent... and it is an action...

**Review by lache-melvin — APPROVED** [review]
Awesome thanks Roxy! Just found one more :)
