### PR TITLE
5675.4 frontend

### LINKED ISSUE #5674: You can change the value of an indicator after the requisition has been finalised
## What went wrong? 😲

As title. See video [here](https://drive.google.com/file/d/1p4nptM3nD4KdQyo2ovu_cYAI8LblZzTp/view?usp=sharing)

And Sorry, I should have seen this way earlier ):

## Expected behaviour 🤔
You should not be able to modify the value of an indicator once the requisition has been finalised

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Have program setup and Regimen inidcators setup
1. Go to Distribution > Requisition and create a new program requisition
2. Click on Indicator tab and + Regimen button, add a value
3. Finalise your requisition 
4. Click back the requisition and go the indicator tab and change the value of the regimen you added a value
5. Change that value
6. See error. You should not be able to as the requisition has been finalised

## Your environment 🌱

- Open mSupply Version: v2.4.0
- Legacy mSupply Central Server Version: v7.19RC19

- Platform:

- Database type: SQLlite3

### LINKED ISSUE #5675: CIV 2.5: Link a manual Inbound Shipment to an Internal Order
## Step 1: 
Amend the `InsertInboundShipment` input to accept a `requisition_id` which should only be inputted if the store has the store preference: `Manually link Internal Order to Inbound Shipment`

## Step 2: 
- Note: This window will only show if the store has the preference `Manually link Internal Order to Inbound Shipment`
- Requisition endpoint to get all finalised Internal Orders
	- Filter by: 
		- Type: Request
		- Status: Sent
		- OtherPartyId: Selected from add customer (From `New Shipment` -> `Clicked supplier`)
- If the store has the above preference and the requisition endpoint returns some values then show below table for user to select which Internal Order they want to link to the Inbound Shipment.
Screenshot 2024-12-03 at 8 13 11 AM

## Step 3
- Add an `Add from Internal Order` option to the `Add item` button 
Screenshot 2024-12-03 at 8 11 14 AM
- Select items from the Internal Order to add to the Inbound Shipment
Screenshot 2024-12-03 at 8 11 45 AM
- When an item is added, the invoice line should be populated with information from the Internal Order line

### Moneyworks Jobcode 🧰
OMS:CIDV

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #5675 & #6161

# 👩🏻‍💻 What does this PR do?
- Adds split buttons for Inbound Shipment (Options are: Add item, Add from master list, Add from Internal Order)
Screenshot 2025-02-03 at 2 23 39 PM
- To add lines from Internal Order, the Internal Order: 
	- Store pref: manually link supplier invoice to requisition 
	- IS must be linked to an Internal Order (Go through steps from create invoice if pref is on)
- Also fix split button not having shadow

# 🧪 Testing

- [ ] Follow #6330 to create linked Inbound Shipment
- [ ] Click on the split button and choose `Add from Internal Order`
- [ ] Table should pop up with lines from that Internal Order
- [ ] Select lines to add to IS
- [ ] Click select
- [ ] Lines should be added populated with: requested quantity = pack qty, pack size = 1
- [ ] Note: Lines can be added multiple times. 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx [hunk 1]
```diff
@@ -55,7 +55,15 @@ export const SplitButton = <T,>({
...
       <Tooltip title={label}>
-        <ButtonGroup color={color} variant="outlined" aria-label={ariaLabel}>
+        <ButtonGroup
+          color={color}
+          variant="outlined"
+          aria-label={ariaLabel}
+          sx={{
+            boxShadow: theme => theme.shadows[2],
+            borderRadius: 24,
+          }}
```
Comment (roxy-dao) [inline client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx:65]: Fix for GEDSI bug, adding shadow back to the split buttons

File: client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx [hunk 2]
```diff
@@ -89,6 +97,7 @@ export const SplitButton = <T,>({
               borderRadius: 0,
               borderStartEndRadius: '24px',
               borderEndEndRadius: '24px',
+              borderLeft: theme => `1px solid ${theme.palette.divider}`,
```
Comment (roxy-dao) [inline client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx:100]: To show that both parts of the button can be clicked

**Review by jmbrunskill — COMMENTED** [review]
With `Can manually link requisition to suppiler invoice` turned off
image

I still seem to get the UI to select an internal order UI
image

Selecting an order crashes like this...
image

**Comment by jmbrunskill** [comment]
image
image

I think we should only show sent orders as possible things to link too? I see that in the requirements too, but it's not working for me...

**Comment by jmbrunskill** [comment]
How are we going to limit that list of possible requisitions to link too?
It seems like it's possible to link a number of shipments to the same internal order (which makes sense)

I wonder if there should be a way to finalise the internal order and remove it from the list via this manual linking process?
I assume (but haven't checked) we normally set the finalised status after receiving all the goods in when it's auto created?

**Comment by jmbrunskill** [comment]
Another nice to have, would be to offer too add the lines to the inbound shipment straight after you've selected your internal order? Definitely for another PR, but feels a bit clunky to link the internal order then have to go to add the lines using a different button, it's probably the logical next step almost every time right?

**Comment by jmbrunskill** [comment]
A few more questions, possibly for @mark-prins ?

- [ ] Should there be a way to correct your mistake if you select the wrong internal order? Or is the process just to Delete and start again?
- [ ] Should we show with internal order is linked in the Add from Internal Order Modal, you might be confused why the lines you expect aren't there if you've select the wrong order...
image

File: client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx [hunk 3]
```diff
@@ -57,13 +61,16 @@ export const AppBarButtonsComponent: FC<AppBarButtonProps> = ({
...
-          label={t('button.add-item')}
-          Icon={<PlusCircleIcon />}
-          onClick={() => onAddItem(true)}
+        <AddButton
+          onAddItem={onAddItem}
+          requisitionId={data?.requisition?.id ?? ''}
+          invoiceId={data?.id ?? ''}
+          disable={isDisabled}
+          disableAddFromMasterListButton={
+            data?.status !== InvoiceNodeStatus.New
```
Comment (jmbrunskill) [inline client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx:70]: Is there a reason why add from master list and add from internal order are only available in New status, but adding items is ok?
Not a major was just wondering why the logic is different for those? Particularly for inbound if you missed a line it would be good to be able to link to it?

**Review by jmbrunskill — CHANGES_REQUESTED** [review]
Thanks Roxy, a tonne of work here.
Would like to review these items before approval

- [x] Filter out Draft Inbound shipments from the list to select from? Unless there's a reason it's required?
- [ ] Fix the UI to not show the select internal order modal when pref `Can manually link requisition to suppiler invoice` turned off

File: client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx:65]: This is in 2.5, so it wasn't broken by MUI update

**Comment by roxy-dao** [comment]
> With `Can manually link requisition to suppiler invoice` turned off

are you sure your preferences are syncing properly? I just turned it off and I cannot make. Line below should stop it from showing

https://github.com/msupply-foundation/open-msupply/blob/24f7f165f73444a66ba42d9fcf0d4c63da139950/client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx#L116

**Comment by roxy-dao** [comment]
> How are we going to limit that list of possible requisitions to link too? It seems like it's possible to link a number of shipments to the same internal order (which makes sense)
> 
> I wonder if there should be a way to finalise the internal order and remove it from the list via this manual linking process? I assume (but haven't checked) we normally set the finalised status after receiving all the goods in when it's auto created?

OG doesn't restrict this. It shows all the IOs available to link even if they have been linked before. In a Requisition we would finalise once the user has supplied all they want to supply.... 

Not sure if we want to change existing behaviour? Would be a question for @mark-prins

**Comment by roxy-dao** [comment]
> Another nice to have, would be to offer too add the lines to the inbound shipment straight after you've selected your internal order? Definitely for another PR, but feels a bit clunky to link the internal order then have to go to add the lines using a different button, it's probably the logical next step almost every time right?

defo

File: client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx (hunk 3 above)
Comment (roxy-dao) [reply client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx:70]: Not to sure, the disable from master list button was always like this. I'm assuming that it's because 'delivered' can be from an outbound -> inbound, if that's the case we can just disable by linked id

**Comment by jmbrunskill** [comment]
> are you sure your preferences are syncing properly? I just turned it off and I cannot make. Line below should stop it from showing
Yup working after logging in and out

**Review by jmbrunskill — APPROVED** [review]
Thanks for the changes Roxy!
