### PR TITLE
7547 off 2.7.2 refactor customer program response requisition

### LINKED ISSUE #7070: Manual Requisitions (Program) : Should select the Customer before the Program
## What went wrong? 😲

Image

User's generally want to first select the customer they're wanting to enter a manual requisition for before other information.
By selecting the customer first it's easier to find the right program for that customer and test that it's working correctly.

Note: There also might be an issue with correctly assigning the available programs to the correct customer, but the waters are muddied by an issue with `name_tag_join` sync. Once that's fixed this issue might be updated, and priority might be increased if that is the case.

## Expected behaviour 🤔

Image

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Requisitions
2. Select a Customer
3. Check that the correct programs are selected for that customer

Note: It seems in mSupply, that for the customer to have program available when createing a manual requisition, they simply need to have the tag for the program assigned to the customer, however I think both the customer and the supplying store need the matching tags to in open-mSupply currently?

## Your environment 🌱

- Open mSupply Version: V2.6.1-RC
- Legacy mSupply Central Server Version: #16298-Add-assets-via-datamatrix-permission

- Platform:

- Database type:

### LINKED ISSUE #7547: Inconsistency of master list/program selection for customer in manual response requisition
Inconsistency between OG and OMS

## What went wrong? 😲

* We show current store programs (OMS) vs showing customer programs (OG) when creating manual response requisition
* Requisition is populated with items from this program rather then customer's program

See these screenshots (I'll try to share databases, they are quite large though, so will have a little go at making them smaller)

Need to also check if these programs actually exist for customer ?

## Expected behaviour 🤔

Do as per OG, would also mean we need to do this (most likely): https://github.com/msupply-foundation/open-msupply/issues/7070, which also means API should be adjusted to be 'consumer' based.

Might need to check manual general response requisition to see if master list are customer's

Who else might use this functionality ?

We don't really have a 'program' as such in OG so not sure how we see the intersection of master lists/programs between supplier and customer (unless esigl code is used ¯\_(ツ)_/¯)

See these screenshot (see screenshot names for details):https://drive.google.com/drive/u/1/folders/11PlZV_kqa6QiIJGz7jLkzPMfY2aDkv3o

## How to Reproduce 🔨

Setup program master lists, with name tags, have different program master list for customer and supplier, try create manual response requisition (should use customer's master lists)

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #7547  & Fixes #7070 

# 👩🏻‍💻 What does this PR do?
Client:
- When creating customer response program requisition, select customer first on modal.
- Adds filtering for orders with available periods - and UI visual indications when program has no orders with available periods.

Server:
- Adds separate end point to query program requisition settings by customer.
- Fixes filtering programs by customer available program (rather than supplier available program)
- Removes graphql layer mapping and filtering (moves this to service layer)
- Adds test cases for insert response requisition program

## 💌 Any notes for the reviewer?

# 🧪 Testing

Testing will require set up for program requisitions. 
- [ ] Create program available for customer store but NOT available for supplier store with order types and periods available
- [ ] Log in as supplier 
- [ ] Open creating a manual response program requisition by navigating to Distribution -> Requisitions -> 'New Requisition' button
- [ ] See customer is first drop down.
- [ ] Select customer, and see order types and periods.
- [ ] Create requisitions for each available period
- [ ] See that order types no longer render when no periods are available
- [ ] Create requisitions for each period of every order type
- [ ] See that the program changes colour when no order types with any periods are available.

# 📃 Documentation

I think no documentation changes required - but am needing to confirm this. Possibly we have documented restrictions of tags and/or it has become common practice for users and this will need to be redocumented.
- [ ] **No documentation required**: 

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/types/schema.ts [hunk 1]
```diff
@@ -1470,11 +1464,8 @@ export type CustomerIndicatorInformationNodeCustomerArgs = {
 
 export type CustomerProgramRequisitionSettingNode = {
   __typename: 'CustomerProgramRequisitionSettingNode';
-  customerAndOrderTypes: Array<CustomerAndOrderTypeNode>;
-  masterList: MasterListNode;
-  programId: Scalars['String']['output'];
-  programName: Scalars['String']['output'];
-  tagName: Scalars['String']['output'];
+  customerNameId: Scalars['String']['output'];
+  masterLists: Array<MasterListWithOrderTypesNode>;
```
Comment (fergie-nz) [inline client/packages/common/src/types/schema.ts:1468]: Changing this node structure. I thought this would be more clear as we can have multiple program_requisition_settings per customer / program combination.

So we now query on a program_requisition_settings basis - and include the 'tag' in the selection as seen below. This is to differentiate between what might appear to be duplicate programs for each customer.

File: client/packages/requisitions/src/ResponseRequisition/ListView/CreateRequisitionModal.tsx [hunk 2]
```diff
@@ -30,28 +32,35 @@ interface CreateRequisitionModalProps {
...
-  onCreate,
-}) => {
+export const CreateRequisitionModalComponent: FC<
+  CreateRequisitionModalProps
+> = ({ isOpen, onClose, onCreate }) => {
   const t = useTranslation();
-  const { data: programSettings, isLoading } =
-    useResponse.utils.programSettings();
+
+  const { data, isLoading } = useName.document.customers();
```
Comment (fergie-nz) [inline client/packages/requisitions/src/ResponseRequisition/ListView/CreateRequisitionModal.tsx:40]: Select customers in a parent component which is an independent query to program_requisition_settings query. 

Now call this separately based on selected customer.

File: client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx [hunk 3]
```diff
@@ -217,19 +244,23 @@ export const ProgramRequisitionOptions = ({
...
-          }}
-        >
-          {item.programName} ({item.tagName})
-        </Typography>
-      </Box>
-    </DefaultAutocompleteItemOption>
-  );
+  (): AutocompleteOptionRenderer<MasterListWithOrderTypesFragment> =>
+  (props, item) => {
+    const color = item.orderTypes.length === 0 ? 'red' : 'black';
```
Comment (fergie-nz) [inline client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx:249]: Maybe red is a bit too garish? Was thinking maybe slightly greyed out?

File: client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts [hunk 4]
```diff
@@ -797,34 +832,30 @@ export type CustomerProgramSettingsFragment = {
...
-      customer: {
-        __typename: 'NameNode';
-        code: string;
-        id: string;
-        isCustomer: boolean;
-        isSupplier: boolean;
-        isOnHold: boolean;
-        name: string;
-        store?: { __typename: 'StoreNode'; id: string; code: string } | null;
-      };
```
Comment (fergie-nz) [inline client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts:827]: The main reason we couldn't use this structure anymore is because previously we were implicitly filtering what programs to query by 'store_id' which was the suppliers store id (ie the supplying store had to have the name tag of the program).

We want to find programs available to customers which aren't necessarily available to the supplier, which would mean querying every program and every customer and every order type and every period which is unwieldy!

This is why we refactored to select a customer first, and then make a filtered query based on this selection.

File: server/graphql/requisition/src/lib.rs [hunk 5]
```diff
@@ -62,12 +62,13 @@ impl RequisitionQueries {
...
-    pub async fn customer_program_requisition_settings(
+    pub async fn program_requisition_settings_by_customer(
         &self,
         ctx: &Context<'_>,
         store_id: String,
-    ) -> Result<Vec<CustomerProgramRequisitionSettingNode>> {
-        get_customer_program_requisition_settings(ctx, &store_id)
+        customer_store_id: String,
+    ) -> Result<CustomerProgramRequisitionSettingNode> {
+        get_program_requisition_settings_by_customer(ctx, &store_id, &customer_store_id)
```
Comment (fergie-nz) [inline server/graphql/requisition/src/lib.rs]: Now we pass through customer_name_id and available programs on this rather than store_id

File: client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx [hunk 6]
```diff
@@ -217,19 +249,22 @@ export const ProgramRequisitionOptions = ({
...
+        <Box display="flex" flexDirection="row" gap={1} alignItems="center">
+          <Typography
+            overflow="hidden"
+            textOverflow="ellipsis"
+            sx={{
+              whiteSpace: 'nowrap',
+              color: color,
+            }}
+          >
+            {item.masterListName} ({item.masterListNameTagName})
```
Comment (fergie-nz) [inline client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx:265]: Adds tag name to differentiate between program settings of the same masterlist

File: server/repository/src/db_diesel/name_tag.rs [hunk 7]
```diff
@@ -73,4 +75,9 @@ impl NameTagFilter {
         self.store_id = Some(filter);
         self
     }
+
+    pub fn name_id(mut self, filter: EqualFilter<String>) -> Self {
+        self.name_id = Some(filter);
+        self
```
Comment (fergie-nz) [inline server/repository/src/db_diesel/name_tag.rs:81]: Needed to add filtering by customer name to filter programSetting when a customer is selected

File: server/service/src/requisition/program_settings/customer_program_settings/prepare.rs [hunk 8]
```diff
@@ -50,73 +86,121 @@ pub(super) fn prepare_customer_program_settings(
...
+                            order_type.clone(),
+                            periods.clone(),
+                            setting,
+                            requisitions_in_periods.clone(),
+                        )
+                    })
+                    // filter out order types which do not have available periods
+                    .filter(|order_type_with_periods| {
+                        order_type_with_periods.available_periods.len() > 0
+                    })
```
Comment (fergie-nz) [inline server/service/src/requisition/program_settings/customer_program_settings/prepare.rs:136]: Filter order types to those with periods available here rather than filtering on front end to be consumer focussed.

**Review by jmbrunskill — APPROVED** [review]
Looks good. I think the `map` and `prepare` file names don't make much sense so could clean that up, however seems to be working well.

Thanks for all the effort on this and the comments which help a lot!

**Comment by jmbrunskill** [comment]
Merged for rc build but @fergie-nz can you fix the tests and formatting please?

**Comment by fergie-nz** [comment]
> Merged for rc build but @fergie-nz can you fix the tests and formatting please?

Sounds good! Thanks James. Will make those changes tomorrow
