### PR TITLE
3674 assets locations dont show on central server

### LINKED ISSUE #3674: Assets Locations don't show on central server
## What went wrong? 😲
Asset Locations don't appear on the central server.

Remote site:
image

Central Site:
image

## Expected behaviour 🤔
An asset's location should be visible to central server administrators

>Note: this isn't a trivial fix because all locations aren't synced to central server currently. Because central server is just another store, it doesn't get access to other store's remote data (such as locations)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create and asset on a remote site
2. Assign a location to this asset
3. Sync to Central Server
4 Check if location appears on central server.

## Your environment 🌱

- Open mSupply Version: 2.0.0-RC

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #3674

# 👩🏻‍💻 What does this PR do?

Since all locations aren't available on Central Server, we hid the Location section of the Assets on central server, unless they relate to the currently logged in store.

Central Server - Logged in Store
image

Central Server - Other store

image

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] OMS Central Server
- [ ] 1 Asset assigned to Central Store
- [ ] 1 Asset assigned to another store
- [ ] Check that the asset from the remote store doesn't show any location section
- [ ] Check that the asset from the central store does show the location section.

# 📃 Documentation
- [ ] **No documentation required**: Technically we could update the docs to say the section won't show up but I don't think it's critical.

### CODE REVIEW

File: client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx [hunk 1]
```diff
@@ -184,35 +186,37 @@ export const Summary = ({ draft, onChange, locations }: SummaryProps) => {
...
-                      newSelectedLocations.map(location => location.value)
-                    ),
-                  });
-                }}
-                options={locations}
-              />
-            ) : null}
-          </Row>
-        </Section>
+        {(!isCentralServer || draft.storeId == storeId) && (
```
Comment (roxy-dao) [inline client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx:189]: `unless they relate to the currently logged in store`

So draft.storeId != storeID?

Comment (jmbrunskill) [reply client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx:189]: The logic is reversed, so we show the section if.
A) we are not on central server
or
B) If we are logged into the same store

Does that make sense? If it not working that way for you?

Comment (roxy-dao) [reply client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx:189]: Oh sorry my brain died for a moment. Yup it makes sense

**Review by roxy-dao — APPROVED** [review]
Thanks James
