### PR TITLE
#6997 #7014 Multiple file upload

### LINKED ISSUE #6997: Equipment document upload doesn't accept multiple file selection
## What went wrong? 😲

When you click the "Browse Files" button in the Documents section for an asset, you can select mulitiple items in the Finder. However, only one file is actually uploaded.

## Expected behaviour 🤔

It should *either*:
- upload multiple selected files, or
- restrict the File explorer to a single selection

Note: would pay to check other places that offer file uploads and make sure this is consistent throughout.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

- Go to Cold Chain -> Equipment -> Select an asset -> Documents tab
- Click "Browse files"
- Select multiple files (using Shift or Cmd), then click "OK"
- Notice only one file uploaded and listed

## Your environment 🌱

- Open mSupply Version: 2.6
- Platform: Browser/Firefox

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #6997 & #7014

# 👩🏻‍💻 What does this PR do?

Modifies the server's `upload_sync_file` endpoint function to handle an array of files rather than just the first one in the `formData` array.

# 🧪 Testing

- [ ] Go to ColdChain -> Equipment -> Select an asset -> Documents tab
- [ ] Drag and drop multiple files onto the Upload box
- [ ] *All* files should appear in the Downloaded documents list below
- [ ] Repeat by clicking the "Browse files" button and selecting multiple files in the Dialog

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [x] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/server/src/static_files.rs [hunk 1]
```diff
@@ -148,17 +148,26 @@ async fn upload_sync_file(
...
-        })?;
-
-    Ok(HttpResponse::Ok().json(static_file.id))
+    let path_inner = path.into_inner();
+
+    let mut static_file_ids: Vec<String> = [].to_vec();
+
+    for f in file {
+        let static_file =
+            upload_sync_file_inner(&service_provider, &settings, path_inner.clone(), f)
```
Comment (CarlosNZ) [inline server/server/src/static_files.rs:157]: Was trying to pass a reference to `path` rather than cloning here, but the called function takes a tuple of values here, so wasn't sure what the correct syntax to pass reference to object that is being destructured.

Comment (jmbrunskill) [reply server/server/src/static_files.rs:157]: FWIW, I tried this and the syntax is like this:   

 (table_name, record_id): &(String, String),

Then you pass it here as:

```suggestion
            upload_sync_file_inner(&service_provider, &settings, &path_inner, f)
```

However, I don't think it actually make is more efficient or simplier as you then need to call the `to_string()` or `to_owned()` methods on those variables in the `upload_sync_file_inner` function, so I think what you have is totally fine.

**Review by jmbrunskill — APPROVED** [review]
Thanks @CarlosNZ works great!

File: server/service/src/static_files.rs [hunk 2]
```diff
@@ -70,11 +70,14 @@ impl StaticFileService {
...
         &self,
-        temp_file: TempFile,
+        temp_file: &TempFile,
         category: &StaticFileCategory,
         file_id: Option<String>,
     ) -> anyhow::Result<StaticFile> {
-        let file_name = temp_file.file_name.context("Filename not provided")?;
+        let file_name = temp_file
+            .file_name
+            .clone()
```
Comment (jmbrunskill) [inline server/service/src/static_files.rs:79]:
```suggestion
            .to_owned()
```
It doesn't matter at all, but this might be slightly more correct, as you're using clone here to turn a reference into an `owned` value. The code underneath will probably be exactly the same but thought I'd mention anyway.

File: server/server/src/static_files.rs [hunk 3]
```diff
@@ -148,17 +148,26 @@ async fn upload_sync_file(
...
-            InternalError::new(
-                "Error uploading file, please check server logs",
-                StatusCode::INTERNAL_SERVER_ERROR,
-            )
-        })?;
-
-    Ok(HttpResponse::Ok().json(static_file.id))
+    let path_inner = path.into_inner();
+
+    let mut static_file_ids: Vec<String> = [].to_vec();
```
[the remark this answers is not in the document]
Comment (CarlosNZ) [reply server/server/src/static_files.rs]: 4deb62f62e
