### PR TITLE
3910 Post migration from desktop, previous 'sg' stocktakes have missing lines

### LINKED ISSUE #3910: Post migration from desktop, previous 'sg' stocktakes have missing lines
## What went wrong? 😲
 
Post migration from desktop, previous `sg` stocktakes have missing lines

## Expected behaviour 🤔
The lines should appear as well

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. First on mSupply-OG remote-site, create two stocktakes: one `fn` and one `sg` with some lines and sync
2. Then convert to oms by resetting hardware ID & all
3. Reinitialise the new oms-site from scratch
4. In oms, the `fn` stocktakes appear with lines properly
5. Also revisit the `sg` stocktake
6. See error: The `sg` stocktake has no line at all. 

## Your environment 🌱

- Open mSupply Version: v2.0.0
- Legacy mSupply Central Server Version: v7-14-02

- Platform: server exe + browser (chrome)

- Database type: sqlite

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3910

# 👩🏻‍💻 What does this PR do?
mSupply creates UUID for stock line in stocktakes if new batches are added, so null stock line id for stocktake line if it doesn't exist. 

# 🧪 Testing

- [ ] Have Store in mSupply
- [ ] Create stocktake with new batches
- [ ] Migrate Store to OMS site
- [ ] Integrate
- [ ] Stocktake should migrate without problem

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/service/src/sync/translations/stocktake_line.rs [hunk 1]
```diff
@@ -106,6 +107,23 @@ impl SyncTranslation for StocktakeLineTranslation {
...
+        };
+
+        if !is_stock_line_valid {
+            log::warn!(
+                "Stock line is not valid, stocktake_line_id: {}, stock_line_id: {:?}",
+                ID,
+                item_line_ID
+            );
+        }
+
```
Comment (lache-melvin) [inline server/service/src/sync/translations/stocktake_line.rs:126]: This is just logging... I think need something along the lines of:

```
           let stock_line_id = match is_stock_line_valid {
                true => item_line_ID,
                false => None,
            }
```

Comment (roxy-dao) [reply server/service/src/sync/translations/stocktake_line.rs:126]: Already done 🤣

**Review by lache-melvin — APPROVED** [review]
Looks goooood TY!
