### PR TITLE
6374 datepicker options for patient dob

### LINKED ISSUE #6374: On the patient's page, there is an option to clear date of birth however unable to save changes?
## What went wrong? 😲

On the patient's page, there is an option to clear date of birth however unable to save changes? 

Also, when confirming to navigate away from the page, the confirmation window pops up twice - you have to double-click to get it to close

https://github.com/user-attachments/assets/df490349-a12c-4be2-a04a-83d38e2b3d3f

## Expected behaviour 🤔

From my understanding, DOB is not an essential field and should be cleared if necessary as patients can be created without one filled out

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Patients
2. Create a patient without DOB -> the system allows it
3. Create another patient with a DOB -> the system allows it 
4. Go into the patient with a DOB set -> you should be able to change it if needed
5. Click on Clear -> the date is cleared, but you cannot save the changes

## Your environment 🌱

- Open mSupply Version: V2.6.0-build-test-3
- Legacy mSupply Central Server Version: V7.19.03

- Platform: Google Chrome (browser for Mac)

- Database type: PostgreSQL

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #6374 

# 👩🏻‍💻 What does this PR do?

Add an option to the DateOfBirth datepicker to hide the clear button

Used this option in the DefaultPatientUiSchema, so that once a patient is in the detail view area, if a DOB has been selected it can be changed but not removed

If a date of birth has been selected it is possible it might need to be updated, but shouldn't be removed if a DOB is known. This has no effect on the custom estimated dates

Hiding the clear button is 'opt in' so if hte component is being used in other custom areas they won't be affected

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Have no custom patient schemas in place
- [ ] Go to Patients -> New Patient -> Fill in required name fields
- [ ] Open the DOB picker and choose a date
- [ ] Open the picker again and clear the date - observe there are no errors for doing so
- [ ] Ok and next -> Create new patient -> should be in detail view
- [ ] Choose a DOB, observe there being no clear button in the picker
- [ ] Can create the patient and update the date of birth to a new date

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx [hunk 1]
```diff
@@ -139,6 +139,7 @@ export const Toolbar: FC = () => {
               format="P"
               onChange={handleDateChange}
               maxDate={new Date()}
+              actions={['cancel', 'accept']}
```
Comment (roxy-dao) [inline client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx:142]: Why was this added to the prescriptions? 🤔

**Review by roxy-dao — APPROVED** [review]
Works like a charm~
