### PR TITLE
6941 fix stock quantity rounding

### LINKED ISSUE #6941: Problem of rounding off figures in stock
## NOTE:

**This has been re-opened, for ongoing discussion of decimal quantities that don't round nicely. Please see below comments.**

## What went wrong? 😲

There is a decimal problem in the stock display.  
The first screen shoot shows a quantity of 6.800000000000001.

Image

The second shows a quantity of 19.099999999999994.

Image

I think this happens after a dose of vaccine is delivered in the dispensary (but not for all vaccines and after every dispensation).

## Expected behaviour 🤔

Rounding must be to the second decimal place.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Dispense a new dose in Dispensary. (choose a Patient, add an encounter in the past, save and click on one vaccine to dispense, Dispense it)
2.  Go to 'Inventory', 'View Stock' 
3. The error is not found for all vaccines and for all dispensations. 

## Your environment 🌱

- Open mSupply Version: 2.6.00 Demo
- Legacy mSupply Central Server Version: N/A

- Platform: Mac 

- Database type: 

@richardmoizeau

### PR DESCRIPTION
**Pull request by zachariah-at-msupply**
Fixes #6941 

# 👩🏻‍💻 What does this PR do?

This PR makes sure that Open mSupply rounds the pack quantities to 2 decimal places when it displays them.

It adds rounding functions to the pack quantities where they are displayed, in the:
- stock list view
- stock detail view
- inventory adjustment menu

Before (from a comment in the original issue discussion):

https://private-user-images.githubusercontent.com/163234798/424233451-cd0a0dae-81d0-416e-a327-7f42fa0d1b52.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM3Mjk3MjgsIm5iZiI6MTc0MzcyOTQyOCwicGF0aCI6Ii8xNjMyMzQ3OTgvNDI0MjMzNDUxLWNkMGEwZGFlLTgxZDAtNDE2ZS1hMzI3LTdmNDJmYTBkMWI1Mi5tb3Y_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQwNFQwMTE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzMyMGQ2OTY3NTczNGMyNDJhNGQ3NDllYzkyM2ZiODU0MjgyZDY0Y2ZkNzQ3ZjZhMzA4MDEyYmVlNjExZjY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zWDmr9Gaur-yM-BPwjAb3-nPAhbOfq9FMHMOWAY_US0

After:

https://github.com/user-attachments/assets/b4fe9818-3312-4f8c-bb35-ae96c7afdf4d

## 💌 Any notes for the reviewer?

Have a nice day :)

# 🧪 Testing

- [ ] In Open mSupply, create an stock item with a pack quantity which is a number with more than 2 d.p., e.g. 19.3333333333333366666666667.
- [ ] Go to Inventory > View Stock.
- [ ] Check that item's pack quantity is displayed with 2 d.p. (e.g. 19.33).
- [ ] Double click on that item to see its detail view.
- [ ] Check that the item's 'Pack Qty' and 'Available (packs)' fields are displayed with 2 d.p.
- [ ] Click on the adjust button in the top right corner to see the inventory adjustment modal.
- [ ] Check that the 'Pack Qty' and 'Available (packs)' fields are displayed with 2 d.p.
- [ ] Adjust the amount of packs by every possible second decimal place (e.g. 0.31, 0.32, 0.33 and so on) and check that with each adjustment the 'New Pack Qty' field only has 2 d.p., never more.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx [hunk 1]
```diff
@@ -107,13 +107,13 @@ export const InventoryAdjustmentModal: FC<InventoryAdjustmentModalProps> = ({
...
             label={t('label.pack-quantity')}
-            text={format(stockLine.totalNumberOfPacks)}
+            text={round(stockLine.totalNumberOfPacks, 2)}
             textProps={{ textAlign: 'end' }}
             labelProps={{ sx: { textWrap: 'wrap' } }}
           />
           <TextWithLabelRow
             label={t('label.available-packs')}
-            text={format(stockLine.availableNumberOfPacks)}
+            text={round(stockLine.availableNumberOfPacks, 2)}
```
Comment (fergie-nz) [inline client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx:116]: Hey Zachariah, 

Just flagging here that by removing the format function, we lose the ability to handle string or undefined inputs. 
This might cause unwanted behaviour if for whatever reason the availableNumberOfPacks is not a number.

In this case it won't be an issue (as the type of the input is number), so this is fine as is.

However I wonder what would happen if for example in future the type of totalNumberOfPacks in stockLineFragment became 'number | undefined'? An unlikely case, but would lead to unwanted displays.

Maybe we could add the 'format' functionality to the round function so that it could handle other input types?

I don't think you need to change anything here (and maybe you saw all of this already!) but just pointing out in case you didn't see this.

**Review by fergie-nz — APPROVED** [review]
Looks great, Zachariah. Nice one :)

File: client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx (hunk 1 above)
Comment (zachariah-at-msupply) [reply client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx:116]: Yeah, that's very valuable insight actually, thank you Ferg. It's great to know what kind of things can be going through my head as I look at these code patterns, much appreciated 👍👍
