### PR TITLE
3458 Fix receiving stock more than once in the stock transfer

### LINKED ISSUE #3458: Every status-update in Inbound is increasing stocklines of the same item again
## What went wrong? 😲
For stock transfer ONLY; in the received Inbound, first update status to Delivered, the items' stock gets in, now update the status to Verified, another set of same items stocklines is created.
Not replicable when creating a manual Inbound (with external supplier); only in case of stock transfer!
  
## Expected behaviour 🤔
Item line should be stocked only once on `Delivered` status,. not again in `Verified`?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Make sure to create a CI (from mSupply desktop) or Outbound from another oms-site with item (let's say Quan 1) to your oms-site so that there is a new inbound in your oms-store
2. OPen it and change the status to `Delivered` and check stock
3. There is 1 item in the stock
4. Now go back to that INbound and this time update status to `Verified` and check stock
5. See error: there is another stock line of same value; thus same line got stocked-in twice!

## Screenshot/Recording
https://recordit.co/twyIP06Cj3

## Your environment 🌱

- Version: v1.7.0-rc3 
- mSupply version: v7-13-00

- Platform: Android, browser

- Database type: sqlite

### PR DESCRIPTION
**Pull request by raviSussol**
Fixes #3458

# 👩🏻‍💻 What does this PR do? 
 
Fixes receiving stock not more than once during stock transfer.

# 🧪 How has/should this change been tested? 

- Setup multiple oms sites along with msupply desktop sites and the central sync server.
- Make visible of those sites' active stores among each other from the central sync server.
- Create an outbound shipment against one of those remote site from an another remote site and sync.
- Sync from another site and in the inbound shipment list you'll see a new inbound shipment from your supplying store.
- Now process that shipment and confirm it.
- Check item's stock, note it down.
- Again to goto the same inbound shipment and click confirm verified and again check the stock of that item.

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

**Comment by nisha-dangol** [comment]
Tested with [custom-exe](https://jenkins.msupply.org:8443/job/omSupplyMain%20-%20Installers/216/) from Jenkins by @raviSussol : 
Stock transfer from desktop-site to oms-site: changing Inbound status looked good; 
Will test remaining oms to oms stock transfer on Monday!

File: server/service/src/processors/transfer/shipment/create_inbound_shipment.rs [hunk 1]
```diff
@@ -152,6 +152,13 @@ fn generate_inbound_shipment(
         None => format!("Stock transfer"),
     };
 
+    // If outbound shipment has tax, then we will also have tax in inbound shipment
+    // but greater than 0.0
+    let tax = match outbound_shipment_row.tax {
+        Some(tax) if tax > 0.0 => Some(tax),
+        _ => None,
+    };
+
```
Comment (raviSussol) [inline server/service/src/processors/transfer/shipment/create_inbound_shipment.rs:161]: The actual issue was when the outbound shipment had no tax value (`None`) to be calculated for its linked inbound shipment, `outbound_shipment.tax` syncs to the central server with `null` value but the `transact.tax` in the central server is of `Real` typed so when saving record `null` converted to `0` automatically and then sync as `0` to the receiving site. But when inbound shipment is generated, an extra invoice line tries to get created cause of,
https://github.com/msupply-foundation/open-msupply/blob/1a203521ba589ef633386e2a52330a07374e2578/server/service/src/invoice/inbound_shipment/update/mod.rs#L92-L96
which is related to,
https://github.com/msupply-foundation/open-msupply/blob/1a203521ba589ef633386e2a52330a07374e2578/server/service/src/invoice/inbound_shipment/update/generate.rs#L93-L103

I presume if tax is configured (i.e. in the central server atm) then it should be > 0 or if it 0 then would be considered as (not being configured yet)?

**Comment by nisha-dangol** [comment]
@raviSussol This one can be broken by issuing out the received stocks (with `Delivered` status) before confirming as `Verified` in oms-1.7-IS3458 exe:
- Create outbound from store1 to store2 and sync
- In Store2, check that inbound and confirm the status to `Delivered` only
- Now create a outbound with same received stock and sync
- Go back to that previous inbound and this time finalise to `Verified`
- See stock level of that item: again new stocks is in - same bug!

**Comment by nisha-dangol** [comment]
Have tested with [the new exe](https://we.tl/t-Zg0d6CKWKg); looks good so far!

File: server/service/src/processors/transfer/shipment/create_inbound_shipment.rs (hunk 1 above)
Comment (roxy-dao) [reply server/service/src/processors/transfer/shipment/create_inbound_shipment.rs:161]: Tax in omSupply is actually (tax_rate), so actually different from how tax works in mSupply. There is an existing migration issues for this. #3018
This change actually doesn't do anything because if outbound.tax is None then it should be None when transferring to inbound and shouldn't get sent when syncing to central

**Review by roxy-dao — CHANGES_REQUESTED** [review]

File: server/service/src/invoice/inbound_shipment/update/generate.rs [hunk 2]
```diff
@@ -116,7 +116,7 @@ pub fn should_create_batches(invoice: &InvoiceRow, patch: &UpdateInboundShipment
         let invoice_status_index = invoice.status.index();
         let new_invoice_status_index = new_invoice_status.index();
 
-        new_invoice_status_index >= InvoiceRowStatus::Delivered.index()
+        new_invoice_status_index == InvoiceRowStatus::Delivered.index()
```
Comment (roxy-dao) [inline server/service/src/invoice/inbound_shipment/update/generate.rs:119]: There is an issue to refactor all these to match statements, but this will do for a hotfix XD

Comment (andreievg) [reply server/service/src/invoice/inbound_shipment/update/generate.rs:119]: What if status is moves straight to verified ?

File: server/service/src/processors/transfer/shipment/create_inbound_shipment.rs (hunk 1 above)
Comment (andreievg) [reply server/service/src/processors/transfer/shipment/create_inbound_shipment.rs:161]: @raviSussol 

> an extra invoice line tries to get created cause of,
> which is related to

To me, the issue is we are trying to update the line twice, and overwriting the first with the second, we had similar issue previously, we need to revert to using invoice_line_repository.update_tax

Comment (andreievg) [reply server/service/src/processors/transfer/shipment/create_inbound_shipment.rs:161]: Would be great to have a test to capture this btw

**Comment by roxy-dao** [comment]
Would you mind if I do these changes if you can't get it done by tomorrow? Since we're releasing tomorrow...

File: server/service/src/processors/transfer/shipment/create_inbound_shipment.rs (hunk 1 above)
Comment (roxy-dao) [reply server/service/src/processors/transfer/shipment/create_inbound_shipment.rs:161]: > @raviSussol
> 
> > an extra invoice line tries to get created cause of,
> > which is related to
> 
> To me, the issue is we are trying to update the line twice, and overwriting the first with the second, we had similar issue previously, we need to revert to using invoice_line_repository.update_tax

Probably for the best~

File: server/service/src/invoice/inbound_shipment/update/generate.rs (hunk 2 above)
Comment (raviSussol) [reply server/service/src/invoice/inbound_shipment/update/generate.rs:119]: Status straight to verified can't be done in the inbound shipment. Have to do in chronological order.

File: server/service/src/invoice/inbound_shipment/update/generate.rs [hunk 3]
```diff
@@ -117,18 +128,16 @@ pub fn should_create_batches(invoice: &InvoiceRow, patch: &UpdateInboundShipment
         let new_invoice_status_index = new_invoice_status.index();
 
         new_invoice_status_index >= InvoiceRowStatus::Delivered.index()
-            && invoice_status_index < new_invoice_status_index
+            && invoice_status_index < InvoiceRowStatus::Delivered.index()
```
Comment (raviSussol) [inline server/service/src/invoice/inbound_shipment/update/generate.rs:131]: Only return `true` if this inbound shipment hasn't been delivered yet.

File: server/service/src/processors/transfer/shipment/create_inbound_shipment.rs (hunk 1 above)
Comment (raviSussol) [reply server/service/src/processors/transfer/shipment/create_inbound_shipment.rs]: Thanks @andreievg - have updated changes.

File: client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx [hunk 4]
```diff
@@ -49,8 +49,8 @@ const getStatusOptions = (
     },
   ];
 
-  if (currentStatus === InvoiceNodeStatus.New) {
-    // When the status is new, delivered and verified are available to
+  if (currentStatus === InvoiceNodeStatus.Shipped) {
```
Comment (roxy-dao) [inline client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx:52]: Nice thanks~

File: server/service/src/invoice/inbound_shipment/update/generate.rs (hunk 3 above)
Comment (roxy-dao) [reply server/service/src/invoice/inbound_shipment/update/generate.rs:131]: You can still add stock if status is `Delivered`....

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Can a test be added to transfers as well~?

**Review by roxy-dao — APPROVED** [review]
Working fine now~ thanks

**Review by andreievg — APPROVED** [review]
Looks good, thanks @raviSussol

**Comment by roxy-dao** [comment]
Merging for Ravi so we can get release today
