### PR TITLE
10231 inventory stock view the doses quantity appear as 0 for a vaccine with stock

### LINKED ISSUE #10231: Inventory > Stock view : The doses quantity appear as 0 for a vaccine with stock
## What went wrong? 😲

I was looking for an item set as a vaccine to see the UI with doses. 
I enabled "Manage vaccines in doses" in the Store Preferences
When I went back to the list of items in my stock view, all the doses quantities were 0 : 

Image

#### Here's the stock detailed view : 
Image

#### Here is the Catalogue > Items view
Image

#### Here is the Catalogue > Item > Detailed view 
Image

Here is the General view on the central server 
Image

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to https://lmis2025.msupply.foundation/login
2. Login as mSupply Support
3. Store : Central Medical Warehouse
4. Go to Inventory > Stock 
5. See error## Your environment 🌱

- Open mSupply Version: 2.12.00
- Legacy mSupply Central Server Version: not sure

- Platform: browser

- Database type:

### LINKED ISSUE #10267: Internal Order shows doses per unit value instead of actual doses in the system
## What went wrong? 😲

Spotted by @adamdewey 🏅 

When adding items to an Internal Order, some columns will show you how many doses you have in the system - for example, SOH would be doses in stock. However, for all dose values it seems to be showing `doses per unit` value

And even though the item can have SOH = 0, doses show higher number which doesn't make sense

Doses per unit value set to 3: 

Image

That same number showing up in brackets: 

Image

## Expected behaviour 🤔

Should be showing actual doses value, not doses per unit value

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have `Manage vaccine in doses` preference turned on for your store
2. Have a vaccine item with no stock in your store (make sure the item is marked as vaccine in OG mSupply)
3. Have `doses per unit` set to something other than 1 (for example, 3)
4. Go to Replenishment -> Internal Order and create a new order
5. Add your item -> see in the overall view, SOH is 0 but doses show your `doses per unit` in brackets
6. Bug!

## Your environment 🌱

- Open mSupply Version: `2.16.00-develop-01151325`
- Legacy mSupply Central Server Version: `V8.06.12`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### LINKED ISSUE #10351: MOS value changes when switching between different ways of ordering an item
## What went wrong? 😲

MOS figure changes when switching between different measurements/ways of ordering an item. I am requesting the same quantity of units, just in a different shape - 12 doses in 2 packs is the same quantity as 12 doses in 4 vis

https://github.com/user-attachments/assets/8836d2e2-7f82-473d-86b0-41fd9e14a3ca

## Expected behaviour 🤔

MOS should remain the same regardless of how we order the item

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> Internal Orders and create a new Internal Order
2. Test with an item that has Default Pack Size > 1 (for example, my item's DPS is 2)
3. Optional: turn on dose management in preferences and have the item's doses per unit set to a different number (for example, my item's is 3)
4. Add an item to an internal order -> switch between whatever measurements you have available in the dropdown
5. Note dose value stays the same between options but MOS changes
6. Does not make sense

## Your environment 🌱

- Open mSupply Version: `V2.16.00-develop-01301031`
- Legacy mSupply Central Server Version: `V8.06.12`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #10231, Closes #10267, Closes #10351

# 👩🏻‍💻 What does this PR do?

- We still have a mixture of components for the old tables and the new tables and the app was getting confused about which one to use
- Doses wasn't displaying correctly in internal order detail view / stock list view, so have fixed this as well
- Have made it so MOS doesn't change when the unit / pack selector is used.

# 🧪 Testing

- [ ] Have vaccine items set up with doses (OG)
- [ ] Sync to OMS, have store preference "Manage vaccine in doses" on for the store
- [ ] Create Internal Order, go to IO -> add vaccine item
- [ ] Change to packs, MOS should stay same. Now click ok.
- [ ] The detail view should show the correct doses next to numbers
- [ ] Go to stock list view
- [ ] Correct number of doses should show next to vaccine items

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Stock/api/hooks/useStockLine.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ const defaultDraftStockLine: DraftStockLine = {
     code: '',
     name: '',
     isVaccine: false,
-    dosesPerUnit: 0,
+    doses: 0,
```
Comment (roxy-dao) [inline client/packages/system/src/Stock/api/hooks/useStockLine.ts]: This was the way to make the less changes, but we should decide if we wanna use doses or dosesPerUnit. Personally would vote for latter since it's a lot clearer
