### PR TITLE
Column header

### LINKED ISSUE #8048: "Helper" icons on table headers appear inconsistently
## What went wrong? 😲

I noticed the little "i" icons for helper text on column headers don't always look great, and appear inconsistently with respect to their header text:

Image

## Expected behaviour 🤔

The icons should appear consistently, probably in the lower right of the header cell.

Just looking at the HTML, it looks the icon is just inline with the text. I think it would make sense to place the icon using `absolute` positioning relative to the cell frame, but would need to experiment a bit to see what looks right.

## Your environment 🌱

- Open mSupply Version: 2.8.0-RC
- Platform: Browser

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #8048 & #8035 & #8364

# 👩🏻‍💻 What does this PR do?
- For now have moved tooltip to the bottom right of the text... moving it outside of the text doesn't work when there are a lot of columns.... (yes, it would look better being next to the text but not as a part of the text... but alas...)
- The text is forced to 2 rows of text and shows eclipses for text that will overflow... We need to stop making header names too long... My hot take is anything long should go into a description (need a better way to handle this than tooltips as well for tablets)
- Split buttons for adding from item / adding from master list
- Moved min / max MOS out of side panel
- Move things around in the toolbar to free up more real estate...
Screenshot 2025-07-08 at 4 16 56 PM
Screenshot 2025-07-08 at 4 17 06 PM
Screenshot 2025-07-08 at 4 17 16 PM

## Before
io-before-pt
io-before-eng

## After
pt-after
russian-after

## 💌 Any notes for the reviewer?
Should get input from designer for this doing forth...

# 🧪 Testing

- [ ] _(e.g.)_ Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] _(e.g.)_ This sample datafile: _google drive link_
- [ ] _(e.g.)_ Open a requisition with some lines
- [ ] _(e.g.)_ Make a couple invoices supplying some amount of those lines
- [ ] _(e.g.)_ Review that "issued" column is the sum of the amount already issued in invoices for this requisition

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Comment by roxy-dao** [comment]
> @roxy-dao what does this look like in Portuguese on a tablet ? Also how does the rest of internal order look ?
> 
> I think it's ok to remove the tooltip icon ?: [#3208 (comment)](https://github.com/msupply-foundation/open-msupply/issues/3208#issuecomment-2649635851)

Screenshot 2025-07-08 at 5 13 43 PM

Should we be removing it now? 👀

**Comment by andreievg** [comment]
> Should we be removing it now? 👀

Or keep 8048 open ?

File: client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListButton.tsx [hunk 1]
```diff
@@ -1,38 +1,29 @@
...
+  isOn: boolean;
+  toggleOff: () => void;
+}) => {
   const { addFromMasterList } = useRequest.utils.addFromMasterList();
-  const modalController = useToggle();
   const { storeId } = useAuthContext();
+  const filter = { isProgram: false, existsForStoreId: { equalTo: storeId } };
 
   return (
     <>
```
Comment (GeronimoJohn) [inline client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListButton.tsx:18]: We can drop the empty fragments since only one child now 😃

File: client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListButton.tsx [hunk 2]
```diff
@@ -1,38 +1,29 @@
...
-} from '@openmsupply-client/common';
+import { useAuthContext } from '@openmsupply-client/common';
 import { MasterListSearchModal } from '@openmsupply-client/system';
 import { useRequest } from '../../api';
 
-export const AddFromMasterListButtonComponent = () => {
-  const t = useTranslation();
-  const isDisabled = useRequest.utils.isDisabled();
-  const isProgram = useRequest.utils.isProgram();
+export const AddFromMasterListButtonComponent = ({
```
Comment (GeronimoJohn) [inline client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListButton.tsx:6]: Thoughts on `AddFromMasterListModal`? Seems to be just a modal now. Thinking we can even just call the modal directly but thats more changes haha

File: client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx [hunk 3]
```diff
@@ -59,41 +87,111 @@ export const Toolbar: FC = () => {
...
-      >
         <Grid>
-          <Switch
-            label={t('label.hide-stock-over-minimum')}
-            onChange={toggle}
-            checked={on}
-            color="secondary"
-            size="small"
-            labelSx={{ margin: '5px 0' }}
+          <InputWithLabelRow
```
Comment (GeronimoJohn) [inline client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx:97]: VERY NIT: Would personally move to their own files

**Review by GeronimoJohn — APPROVED** [review]
Good stuff! 🔥 UI changes looks nice but hey what do I know I'm not a designer 😁. Left a few notes. But approving since seems trivial
