### PR TITLE
5889 Make reference field multi-lined in inbound shipment detail view

### LINKED ISSUE #5889: Reference field needs to be fully visible in orders somehow
## What went wrong? 😲

Needs better way to see the full reference here otherwise can't trace which internal order it has come from or any other vital information that might be entered for reference. Note: Can alternatively go into the menu and hover over but not very obvious from a user perspective.

Screenshot 2024-12-23 at 3 46 49 PM

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #5889

# 👩🏻‍💻 What does this PR do?
Makes the reference field multi-lined in inbound shipment detail view so that more text can be seen at once

Replaced buffered text input with buffered text area

Screenshot 2025-04-07 at 14 33 18

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Navigate to Replenishment -> Inbound shipments
- [ ] Have or create an inbound shipment with long reference
- [ ] See that the reference in detail view is multi-lined

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx [hunk 1]
```diff
@@ -80,14 +80,25 @@ export const Toolbar: FC = () => {
...
                     sx={{ width: 250 }}
                     value={theirReference ?? ''}
                     onChange={event => {
                       update({ theirReference: event.target.value });
                     }}
+                    maxRows={2}
+                    slotProps={{
+                      input: {
+                        sx: {
+                          backgroundColor: theme =>
```
Comment (noel-yeldos) [inline client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx:95]: Using similar code from BasicTextInput to ensure consistency in appearance/colours

File: client/packages/common/src/ui/components/inputs/TextArea/BufferedTextArea.tsx [hunk 2]
```diff
@@ -24,6 +24,9 @@ export const BufferedTextArea: FC<StandardTextFieldProps> = ({
           ...slotProps?.input,
           sx: {
             backgroundColor: 'white',
+            // Ignoring below, see https://github.com/mui/material-ui/issues/45041
+            // @ts-expect-error: use mergeSlotProps when it's available in MUI-6
+            ...slotProps?.input?.sx,
```
Comment (noel-yeldos) [inline client/packages/common/src/ui/components/inputs/TextArea/BufferedTextArea.tsx:29]: Added this to common component to allow sx to be overridden in areas where BufferedTextArea component is used

File: client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx (hunk 1 above)
Comment (aimee-mcneil-melville) [reply client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx:95]: This works great!

**Review by aimee-mcneil-melville — CHANGES_REQUESTED** [review]
Looks great, nice solution for the theme colours!

Just a tiny thing, but I noticed that when only one line of text is present, and the Inbound Shipment is verified (so the text area is disabled) it takes the space of two lines however without the surrounding two-line box, therefore looking off-center compared to the label

Screenshot 2025-04-08 at 9 27 59 AM

I had a quick look and think that setting a minRows could work for this so the text area has some flexibility - though if you have another way to approach this, then by all means :)

File: client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx [hunk 3]
```diff
@@ -80,14 +80,26 @@ export const Toolbar: FC = () => {
...
+                  <BufferedTextArea
                     disabled={isDisabled}
                     size="small"
                     sx={{ width: 250 }}
                     value={theirReference ?? ''}
                     onChange={event => {
                       update({ theirReference: event.target.value });
                     }}
+                    maxRows={2}
+                    minRows={1}
```
Comment (noel-yeldos) [inline client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx:92]: Thanks for catching this! :)

**Review by aimee-mcneil-melville — APPROVED** [review]
Awesome, LGTM! 😁
