### PR TITLE
5635 when emptying an hiv indicator from it's default value, it is replaced by a strange text value and you can't change it easily to a valid value

### LINKED ISSUE #5634: When no indicators are configured for a program, the indicator tab still shows with a blank page
## What went wrong? 😲

Test suite mentions that the Indicators tab should not show if no Regimen have been configured  or that it is not a HIV program (HIV program box is not ticked). In this case, the Indicators tab is showing even though no regimen has been configured and the HIV program box is not ticked.

image

image

   

## Expected behaviour 🤔
As the testing suite mention ie Indicators tab should not show in the above scenario

## How to Reproduce 🔨

Steps to reproduce the behaviour:
On OG central server in master list, create a program with no Regimen and don't tick the HIV program box. Make that master list visible to the supplier store and the customer. Don't forget to add the tags to the stores involved     
1. On omSupply go to Distribution > Requisition 
2. Click on Add a new Requisition
3. Choose the program you have created and the customer who has access to that program and a period. Click create
4. See error. The Indicators tab is visible 

## Your environment 🌱

- Open mSupply Version: 2.4.0RC4
- Legacy mSupply Central Server Version: v7.18.10

- Platform: Android 14

- Database type: SQLLite3

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #5634 & #5635

# 👩🏻‍💻 What does this PR do?
Defaults to 0 if NaN input and hide indicators tab if no indicators

# 🧪 Testing

- [ ] Have number input indicator
- [ ] Go to that indicator and backspace
- [ ] Should still be able to enter number and shouldn't say NaN

Next:
- [ ] Have program without indicators
- [ ] Create program requisition
- [ ] Shouldn't see indicators tab

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -101,8 +101,13 @@ export const DetailView: FC = () => {
       value: 'Log',
     },
   ];
+  console.log('programIndicators', programIndicators);
```
Comment (Chris-Petty) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx:104]: a loggo

File: client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx [hunk 2]
```diff
@@ -54,7 +54,7 @@ const InputWithLabel = ({ data }: { data: IndicatorColumnNode }) => {
     data.valueType === IndicatorValueTypeNode.Number ? (
       <NumericTextInput
         width={INPUT_WIDTH}
-        value={Number(draft?.value)}
+        value={isNaN(Number(draft?.value)) ? 0 : Number(draft?.value)}
         onChange={v => {
           update({ value: String(v) }).then(errorHandler);
```
Comment (Chris-Petty) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx:59]: When holding down backspace to clear the value, it flickers no value and `0`. Then the back end is still getting requests of something causing this error: 
image

image

Undefined... weird. OK if you want to fix that one in a separate issue but may as well tackle in this PR if easy? Is the `v` in the handler function here undefined?

**Review by Chris-Petty — CHANGES_REQUESTED** [review]

File: client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx [hunk 3]
```diff
@@ -54,8 +54,11 @@ const InputWithLabel = ({ data }: { data: IndicatorColumnNode }) => {
     data.valueType === IndicatorValueTypeNode.Number ? (
       <NumericTextInput
         width={INPUT_WIDTH}
-        value={Number(draft?.value)}
+        value={isNaN(Number(draft?.value)) ? 0 : Number(draft?.value)}
         onChange={v => {
+          if (isNaN(Number(v))) {
+            update({ value: '0' }).then(errorHandler);
+          }
           update({ value: String(v) }).then(errorHandler);
```
Comment (Chris-Petty) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx:62]: Completely stylistic but I'd:
```suggestion
          const newValue = isNaN(Number(v)) ? 0 : v;
          update({ value: String(newValue) }).then(errorHandler);
```

**Review by Chris-Petty — APPROVED** [review]
Looks good to me!

One weird thing, it seems to be throwing errors for empty strings in the string type fields:

image
image

I imagine a backend change. New issue? Or fix here :D
