### PR TITLE
3408 Repacks: 'Number of packs to repack' field is not required

### LINKED ISSUE #3408: Repacks: 'Number of packs to repack' field is not required
## What went wrong? 😲

User is able to save the repack transaction despite not providing any number of packs to repack.

https://github.com/msupply-foundation/open-msupply/assets/132425096/64c5b049-6982-44c4-aa06-16c12f5a65c4

## Expected behaviour 🤔

Number os packs to repack should be a required/mandatory field for the repack to be saved.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Inventory'
2. Click on the  'repack' icon
3. Click on 'New' and input a new pack size, leaving 'Number of packs to repack' blank

## Your environment 🌱

- Version: 1.7
- mSupply version: V7.13

- Platform: Desktop app

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3408

# 👩🏻‍💻 What does this PR do? 
Disable save button if input has been cleared

# 🧪 How has/should this change been tested? 
- [ ] Go to `Stock`
- [ ] Click on `Repack` box
- [ ] Create `New` repack
- [ ] Enter numbers into both `Number of packs to repack` and `New pack size`
- [ ] Clear one of the numbers
- [ ] Save button should be disabled

### CODE REVIEW

File: client/packages/system/src/Stock/Components/Repack/RepackModal.tsx [hunk 1]
```diff
@@ -137,7 +137,12 @@ export const RepackModal: FC<RepackModalControlProps> = ({
       okButton={
         <DialogButton
           variant="save"
-          disabled={draft?.newPackSize === 0 || draft?.numberOfPacks === 0}
+          disabled={
+            draft?.newPackSize === 0 ||
+            draft?.numberOfPacks === 0 ||
+            !draft.newPackSize ||
+            !draft.numberOfPacks
+          }
```
Comment (Chris-Petty) [inline client/packages/system/src/Stock/Components/Repack/RepackModal.tsx:145]: I really wanted to just approve because I'm sure this works but... can't we just use that `0` is falsy in JS?
```suggestion
          disabled={!draft?.newPackSize || !draft?.numberOfPacks}
```

Easy to ignore but after a while I think it kinda bloats the code base. On the fence of when to request changes...

**Review by Chris-Petty — CHANGES_REQUESTED** [review]
Works... but 😃

File: client/packages/system/src/Stock/Components/Repack/RepackModal.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/system/src/Stock/Components/Repack/RepackModal.tsx]: Done~

**Review by Chris-Petty — APPROVED** [review]
