### PR TITLE
Fix temperature breach filter

### LINKED ISSUE #2537: Cold chain: Temperature logs are not synced from CCA to OMS while a breach is active
## What went wrong? 😲

Temperature logs are not coming across from CCA to OMS while there's an active breach on CCA. 

As soon as the excursion is resolved i.e. returns below the threshold (note, not breach acknowledged), then log syncing resumes. 

Observed on both tablet and Windows OMS. 

CCA during active breach: 

telegram-cloud-photo-size-1-5113892675039374097-y

OMS during active breach: 

telegram-cloud-photo-size-1-5113892675039374098-y

Note: the breach duration threshold is 4 mins, so the first 2 logs (17:54:16 and 17:56:16) came across to OMS before they were flagged as part of a breach. 

CCA after breach resolved: 

telegram-cloud-photo-size-1-5113892675039374105-y

OMS after breach resolved: 

telegram-cloud-photo-size-1-5113892675039374106-y

## Expected behaviour 🤔

Logs should come through allll the time

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Sync CCA to OMS (tablet or Windows)
2. Note logs coming through correctly
3. Trigger an breach on a sensor
4. Note that logs for that sensor stop coming through to OMS (other sensors will continue syncing as normal)
5. Resolve the breach
6. Note that logs start coming through again

## Your environment 🌱

 - CCA version: 0.5.6-rc1
 - OMS Version: 1.5.02
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #2537

# 👩🏻‍💻 What does this PR do? 
 
Could not repro the stated issue. A related issue was raised in conversation - that the breaches aren't showing.

That's the part which I've addressed here - it turns out that the breach filter was a little over complicated and didn't function as required. The filter was looking for `temperature_breach` records.. the query was

```
SELECT "temperature_log"."id", "temperature_log"."temperature", "temperature_log"."sensor_id", "temperature_log"."location_id", "temperature_log"."store_id", "temperature_log"."datetime", "temperature_log"."temperature_breach_id" 
FROM "temperature_log" 
WHERE "temperature_log"."temperature_breach_id" IN 
(SELECT "temperature_breach"."id" FROM "temperature_breach" WHERE "temperature_breach"."id" = 'fff4bac7-2256-43cf-acb9-78acfc8cc7e0') 
ORDER BY "temperature_log"."datetime" DESC
```

which will not work for new breaches, the breach has to be added before the breach can be added!

I've changed the filter to look for an `id` only, which simplifies things and allows breaches to be added.

# 🧪 How has/should this change been tested? 

Configure a CCA with a sensor and sync with omSupply. get the sensor into a breach and check if the breach shows in oms.

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx [hunk 1]
```diff
@@ -177,6 +177,7 @@ const Chart = ({
                       borderStyle: 'solid',
                       borderColor: theme.palette.gray.light,
                       padding: 3,
+                      textAlign: 'left',
```
Comment (mark-prins) [inline client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx:180]: Offroad: the legend was showing with names centred:

Screenshot 2023-12-06 at 10 24 39 AM

File: server/repository/src/db_diesel/temperature_log.rs [hunk 2]
```diff
@@ -92,6 +90,9 @@ impl<'a> TemperatureLogRepository<'a> {
             query = query.order(temperature_log_dsl::datetime.desc())
         }
 
+        // Debug diesel query
```
Comment (mark-prins) [inline server/repository/src/db_diesel/temperature_log.rs:93]: just to help with debugging 🤷

File: server/server/src/cold_chain/sensor.rs [hunk 3]
```diff
@@ -109,7 +109,7 @@ fn validate_sensor(sensor: &Sensor) -> Result<(), String> {
     }
     match sensor.log_delay {
         Some(log_delay) => {
-            if log_delay < 1 {
+            if log_delay < 0 {
```
Comment (mark-prins) [inline server/server/src/cold_chain/sensor.rs:112]: the 'add a debug sensor' function creates a record with `0` here, which meant that the sensor mutation fails for all sensors. since positive number is 0 and up, I figured changing this test still fits the intention

File: server/server/src/cold_chain/temperature_breach.rs [hunk 4]
```diff
@@ -126,11 +126,7 @@ fn upsert_temperature_breach(
         .get_temperature_logs(
             &ctx.connection,
             None,
-            Some(
-                TemperatureLogFilter::new().temperature_breach(
-                    TemperatureBreachFilter::new().id(EqualFilter::equal_to(&id)),
-                ),
-            ),
+            Some(TemperatureLogFilter::new().temperature_breach_id(EqualFilter::equal_to(&id))),
```
Comment (andreievg) [inline server/server/src/cold_chain/temperature_breach.rs:129]: I forgot, why do we need to check that there are logs for the breach ?

File: server/graphql/types/src/types/temperature_log.rs [hunk 5]
```diff
@@ -42,7 +41,7 @@ pub struct TemperatureLogFilterInput {
     pub id: Option<EqualFilterStringInput>,
     pub sensor: Option<SensorFilterInput>,
     pub location: Option<LocationFilterInput>,
-    pub temperature_breach: Option<TemperatureBreachFilterInput>,
+    pub temperature_breach_id: Option<EqualFilterStringInput>,
```
[the remark this answers is not in the document]
Comment (andreievg) [reply server/graphql/types/src/types/temperature_log.rs:44]: I think the breach type filter might be broken with this change ?

**Review by andreievg — CHANGES_REQUESTED** [review]
@mark-prins.

I haven't tested, but I can't see the difference between the queries, also there is a comment about the breach filter.

The reason I can't see the difference, is there is a referencial contraint on logs, can't set temperature_breach_id, unless the breach exists, so I can't quite see what the difference is between the new filter and the old. 

Btw does cold chain app push temperature_logs first or breaches first ? If it's the former then we might have an issue with referencial contraints.

Unforntunately I don't have the cold chain app set up, I wonder if we can share sqlite filter for it, or if there are some postman queries we can use to replicate/validate ?

File: server/server/src/cold_chain/sensor.rs (hunk 3 above)
Comment (mark-prins) [reply server/server/src/cold_chain/sensor.rs:112]: in the cold chain app - under developer settings you can add a sensor, and then add random logs for it.

**Comment by mark-prins** [comment]
Thanks Andrei for review.
I've reverted the filter changes, and removed the log check. Now the api will accept breaches which don't have a log in the database.

To remove any UI strangeness I've added a check in the notification component - if there's no min/max temperature then it just doesn't show. The temperature is also blank in the breach table.

**Comment by mark-prins** [comment]
Oh, and I'm using postgres, so don't have a sqlite file to share. You can use this postman collection to add a breach or log. I've been using CCA with some sensors that I'm shuttling in and out of the fridge to get it to breach which is a bit of a pain, but it did pick up this particular error that I'd missed earlier.

[Cold Chain.postman_collection.json.zip](https://github.com/msupply-foundation/open-msupply/files/13595278/Cold.Chain.postman_collection.json.zip)

**Review by andreievg — APPROVED** [review]
Looks good, thanks for changes @mark-prins.
