### PR TITLE
5122 fix user can create shipment from requisition without permission set

### LINKED ISSUE #5122: Requisitions: user can create OS, despite not having 'create invoice' permission
## What went wrong? 😲

Seems like the permission to create an outbound shipment from a requisition is tied to 'Edit Requisition', not 'Create Invoice'

It can be confusing for users.

## Expected behaviour 🤔

OS creation being linked to 'Create Invoice' permission

## Solution Proposed: 

Change permission to mutate outbound shipment. Credits goes to ~~@roxy-dao~~ @mark-prins  :) 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create User1 and give it permission to View Requisitions and Edit requisitions. Do not give 'Create invoice' permission
Screenshot 2024-10-15 at 12 22 51 PM

2. Goes to a Remote site>Distribution> Requisitions and choose a Requisition to supply
3. Click on the button 'Supply requested'
4. Click on button 'Create Shipment'
5. Error will appear 'Permission denied'
6. User1 cannot see any Outbound Shipments
7. Go back to the chosen Requisition. Column 'Issued' will be updated with values User1 chose.
8. Logout
9. Login with admin user or any other user that has all permissions on
10. Go to same Remote site from step 1.
11. Click on Distribution>Outbound Shipments
12. See the recent shipment created. In the logs, it will say 'Created by User1'

## Your environment 🌱

- Open mSupply Version: V2.3.0Rc8
- Legacy mSupply Central Server Version: V7.17

- Platform: android

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #5122 

# 👩🏻‍💻 What does this PR do?
Disable the creation of shipments from requisitions for users who do not have the ```create invoice``` permission set. Thanks @lache-melvin  for pointing me in the right direction!

Screenshot 2025-01-22 at 11 56 42 AM

https://github.com/user-attachments/assets/e6c7e4e2-74f7-427e-b40b-5d234db04746

## 💌 Any notes for the reviewer?
This change makes it so that users who do not have the "create invoice" permission cannot create invoices from the requisition. However, there is a "create customer invoice from requisition" permission in OG that hasn't been mapped yet to OMS. Therefore, if you leave "create customer invoice from requisition" unchecked, you can still create shipments from requisitions if you have "create invoice" permission. @mark-prins worth doing the mapping?

# 🧪 Testing

- [ ] Create User1 and give it permission to View Requisitions and Edit requisitions. Do not give 'Create invoice' permission
- [ ] Go to a Remote site>Distribution> Requisitions and choose a Requisition to supply
- [ ] Click on the button 'Supply requested'
- [ ] Click on button 'Create Shipment'
- [ ] Observe message that lets the user know they do not have permission to create shipment

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Review by lache-melvin — COMMENTED** [review]
LGTM - but before I approve, keen to hear from @mark-prins whether we want the granularity of mapping the `create invoices from requisitions` permission through instead

**Comment by mark-prins** [comment]
Actually - OG does not check the `create invoice` permission when creating invoices from a requisition!
That's checking for both the `Transfer goods between stores` and `Create invoices from requisitions` permissions to be set.

I would prefer to bring through the `Create invoices from requisitions` permission and use that. Only that though as this gives the greatest flexibility - it means that a user can be denied the permission to create invoices manually while still being about to fulfil customer requisitions. It does require setting two permissions for those users who do both, but that's ok

**Comment by noel-yeldos** [comment]
@mark-prins @lache-melvin What should be done here? Should I do the mapping in this PR or create an enhancement issue?

**Comment by lache-melvin** [comment]
Update in this PR please 🙏

File: client/packages/common/src/types/schema.ts
Comment (lache-melvin) [inline client/packages/common/src/types/schema.ts:1]: I think you might have hit save in this file, and it has formatted making a lot of changes... could you run another `yarn generate` just to clean up the diff? 🙏

File: client/packages/common/src/intl/locales/en/common.json [hunk 1]
```diff
@@ -284,6 +284,7 @@
   "error.no-asset-view-permission": "You do not have permission to view assets.",
   "error.no-customer-return-items": "No items have been added to this return.",
   "error.no-customer-returns": "There are no Customer Returns to display.",
+  "error.no-create-outbound-shipment-permission": "You do not have permission to create an Outbound Shipment",
```
Comment (lache-melvin) [inline client/packages/common/src/intl/locales/en/common.json:287]: nit: from a requisition?

File: server/graphql/tests/permissions.rs [hunk 2]
```diff
@@ -526,7 +526,7 @@ mod permission_tests {
                 }
               }"#,
                 expected: ResourceAccessRequest {
-                    resource: Resource::MutateRequisition,
+                    resource: Resource::MutateOutboundShipment,
```
Comment (lache-melvin) [inline server/graphql/tests/permissions.rs:529]: tests failing expecting `CreateOutboundShipmentFromRequisition`

File: server/repository/src/migrations/v2_06_00/add_create_invoice_from_requisition_permission.rs [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+    fn identifier(&self) -> &'static str {
+        "add_create_invoice_from_requisition_permission"
+    }
+
+    fn migrate(&self, connection: &StorageConnection) -> anyhow::Result<()> {
+        if cfg!(feature = "postgres") {
+            sql!(
+                connection,
+                r#"
+                    ALTER TABLE user_permission ADD VALUE IF NOT EXISTS 'REQUISITION_CREATE_OUTBOUND_SHIPMENT';
```
Comment (lache-melvin) [inline server/repository/src/migrations/v2_06_00/add_create_invoice_from_requisition_permission.rs:15]: Did you test this one? 😁  You can see PG tests failing, should be `ALTER TYPE permission_type ...`

**Review by lache-melvin — CHANGES_REQUESTED** [review]

File: client/packages/common/src/types/schema.ts
Comment (noel-yeldos) [reply client/packages/common/src/types/schema.ts:1]: Ah sorry! I wondered why there were so many changes and I just assumed that me adding the enum value had just re-formatted the file. Fixed here c924a12e1b312d754db962827ec1a5f4e7f3368a :)

Comment (lache-melvin) [reply client/packages/common/src/types/schema.ts:1]: Yeah it's easy to do - finally got around to making an issue for it 😁 #6308

File: client/packages/common/src/intl/locales/en/common.json (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/common/src/intl/locales/en/common.json]: Updated here ed0515db3063dff526e0879780032d2977f9ea6b

File: server/graphql/tests/permissions.rs (hunk 2 above)
Comment (noel-yeldos) [reply server/graphql/tests/permissions.rs]: Updated here ed0515db3063dff526e0879780032d2977f9ea6b

File: server/repository/src/migrations/v2_06_00/add_create_invoice_from_requisition_permission.rs (hunk 3 above)
Comment (noel-yeldos) [reply server/repository/src/migrations/v2_06_00/add_create_invoice_from_requisition_permission.rs]: Ah I always forget to run test before committing! Updated here ed0515db3063dff526e0879780032d2977f9ea6b :)

**Review by lache-melvin — APPROVED** [review]
Epic thanks for changes!
