### PR TITLE
8151 stock line details layout

### LINKED ISSUE #8151: Stock line details layout
## What went wrong? 😲

The `Reason` label is hugging the left of the screen and the input is a long way from any other inputs

Image

## Expected behaviour 🤔
Ideally under batch. Alternatively, move `Campaign` to the left column and just bring `Reason` over to be in line with the other elements on the page

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. View a stock line

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

Image

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #8151

# 👩🏻‍💻 What does this PR do?
- Make new stock line modal not full size on tablet
- Move the reason component to the stock line edit form
- Make pack size wider to match rest of input components in this area
- Delete unused Pack Size Input component 

# 🧪 Testing

- [ ] Go to Stock
- [ ] Click New Stock 
- [ ] Components should be closer together / width should be same

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Screenshots for new stock modal
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/DateTimePickers/TimePickerInput/TimePickerInput.tsx [hunk 1]
```diff
@@ -49,7 +49,7 @@ export const TimePickerInput = ({
         textField: {
           disabled: !!disabled,
           error: isInvalid(internalValue),
-          sx: getTextFieldSx(theme, !!props.label),
+          sx: getTextFieldSx(theme, !!props.label, false),
```
Comment (roxy-dao) [inline client/packages/common/src/ui/components/inputs/DateTimePickers/TimePickerInput/TimePickerInput.tsx:52]: passing dateOnly as false for the timepicker

File: client/packages/host/src/routers/ReplenishmentRouter.tsx [hunk 2]
```diff
@@ -14,9 +14,9 @@ const RequisitionService = React.lazy(
   () => import('@openmsupply-client/requisitions/src/RequisitionService')
 );
 
-const PurchaseOrderService = React.lazy(
-  () => import('@openmsupply-client/purchase_orders/src/PurchaseOrderService')
-);
+// const PurchaseOrderService = React.lazy(
```
Comment (roxy-dao) [inline client/packages/host/src/routers/ReplenishmentRouter.tsx:17]: Purchase Orders hidden, have commented out path since breaking compilation

File: client/packages/system/src/Stock/Components/StockLineForm.tsx [hunk 3]
```diff
@@ -193,6 +196,20 @@ export const StockLineForm = ({
...
+                width={INPUT_WIDTH}
+                type={ReasonOptionNodeType.PositiveInventoryAdjustment}
+                value={draft.reasonOption}
+                onChange={reason => onUpdate({ reasonOption: reason })}
+                reasonOptions={reasonOptions ?? []}
+                loading={loading}
+                disabled={draft?.totalNumberOfPacks === 0}
+              />
+            }
+          />
```
Comment (lache-melvin) [inline client/packages/system/src/Stock/Components/StockLineForm.tsx:212]: Hm, I think reason was originally outside of this main form because its only required when creating new stock line. It shouldn't be there when just editing stock line details:

Screenshot 2025-07-08 at 10 46 52 AM

I think either a `showReason` prop, or pass in "extraFields" to render?

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Looks great, thanks for cleaning up Roxy, just the hiding on edit view 🙏
