### PR TITLE
7232 unable to access linked prescription from vax card from another store

### LINKED ISSUE #7232: Unable to access linked Prescription from Vax card from another store
## What went wrong? 😲

Found while testing #7100 

Whilst accessing a vaccination with a prescription record from a store other than the prescribing store, a link to the prescription is visible. The user then cannot access the related prescription as it is on a different store

Image

Image

## Expected behaviour 🤔

Please correct if needed @mark-prins - I would expect that a prescription should not be able to be accessed from a different store. 

Quickest solution here would be to only show the `View Prescription` link if it is the prescribing store. If accessing the vaccination card on a different store, they can see only the green bar with text 'Vaccination was given on (date)'

## How to Reproduce 🔨

Steps to reproduce the behaviour:

- [ ] On site A - enrol a patient in a vaccination program
- [ ] Create an encounter and give a few vaccinations
- [ ] Go to site B, fetch this new patient
- [ ] View the patients vaccination encounters - you can see the card
- [ ] Go to the encounter - see the 'View prescription' link
- [ ] Click on the link -> prescription doesn't exist on store B so there is an error

## Your environment 🌱

- Open mSupply Version: 2.7
- Legacy mSupply Central Server Version:

- Platform:

- Database type: SLite3

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #7232

# 👩🏻‍💻 What does this PR do?
Hide link to prescription if the prescription was created at a different store. Both in vaccination cards and the reproductive health encounter UI

Screenshot 2025-04-10 at 12 35 13 PM

Screenshot 2025-04-10 at 12 35 00 PM

## 💌 Any notes for the reviewer?
Feels like we should be disabling the facility input if the vax was given at another store... to eliminate someone accidentally changing it but 🤷🏻 

# 🧪 Testing

- [ ] Create a vax encounter for Patient in Store A, and give Patient vax (this records prescription entry)
- [ ] Switch to Store B
- [ ] Go to the encounter from Store B, and click the `given` vaccination
- [ ] Shouldn't see `View prescription` link

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Document that the prescription link won't be available if it was created at another store
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Comment by andreievg** [comment]
> Feels like we should be disabling the facility input if the vax was given at another store... to eliminate someone accidentally changing it but 

@roxy-dao, we had a meeting about this, the summary was that you are allowed to 'give' vaccination that was 'not given' in another store, but you can't 'un give' vaccination that was given in another store

File: client/packages/programs/src/JsonForms/components/Prescription/PrescriptionInfo.tsx [hunk 1]
```diff
@@ -61,7 +64,7 @@ export const PrescriptionInfo = ({ prescription }: PrescriptionInfoProps) => {
     >
       <Box display="flex" alignItems="center" justifyContent="space-between">
         {getPrescriptionInfo()}
-        {prescription.id && (
+        {prescription.id && prescriptionCreatedAtStore && (
```
Comment (andreievg) [inline client/packages/programs/src/JsonForms/components/Prescription/PrescriptionInfo.tsx:67]: Nice of you to also deal with this use case, thanks!

**Review by andreievg — APPROVED** [review]
Looks great, thanks @roxy-dao

**Comment by roxy-dao** [comment]
> > Feels like we should be disabling the facility input if the vax was given at another store... to eliminate someone accidentally changing it but
> 
> @roxy-dao, we had a meeting about this, the summary was that you are allowed to 'give' vaccination that was 'not given' in another store, but you can't 'un give' vaccination that was given in another store

Nice (: yes this was my thinking as well with that comment~

**Comment by lache-melvin** [comment]
Thanks Roxy, will merge now 🙏
