### PR TITLE
7023 Remove mos from soh column

### LINKED ISSUE #7023: Internal order MOS shown as column and also next to Stock on Hand
Is this a bug or a feature ?

## What went wrong? 😲

In internal order (maybe in requisition too) we show MOS twice:

Image

## Expected behaviour 🤔

Show MOS once

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #7023

# 👩🏻‍💻 What does this PR do?
Removes function that adds mos to the soh column values

Screenshot 2025-04-03 at 16 26 58

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Navigate to replenishiments -> internal order
- [ ] Click on internal order
- [ ] See the Available SOH column in the detail view
- [ ] See that it no longer displays mos in months in the value -> You should only see available SOH

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts [hunk 1]
```diff
@@ -88,11 +66,11 @@ export const useRequestColumns = () => {
     },
     {
       key: 'availableStockOnHand',
-      label: 'label.stock-on-hand',
-      description: 'description.stock-on-hand',
+      label: 'label.available-soh',
+      description: 'description.available-soh',
```
Comment (noel-yeldos) [inline client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts:70]: Updated the label and description to reflect the data that is being displayed

**Comment by aimee-mcneil-melville** [comment]
I have a question about this for @mark-prins, @andreievg 

The MOS column is only visible for program orders and with the `useConsumptionAndStockFromCustomersForInternalOrders` pref on. Therefore a non-program order has no MOS shown. Should all orders have the MOS data available?
Screenshot 2025-04-04 at 8 53 13 AM

**Comment by mark-prins** [comment]
aha! good spotting @aimee-mcneil-melville 🙏 

the intention of the issue was to remove duplication. If the MOS column isn't always displayed.. then I agree, this PR will need a little tweaking

Some suggestions
* remove the MOS column and keep the bracketed text
* always show the MOS column and remove the bracketed text
* implement the change in this PR but only when the MOS column is shown
* just close the PR unmerged, close the issue and live with the duplication

Personally, I think the bracketed text is cute and I like that approach.
Even so.. my recommendation is to take the more boring option

always show the MOS column and remove the bracketed text

**Review by aimee-mcneil-melville — CHANGES_REQUESTED** [review]
Lovely thanks Noel! 

Just one thing - as the MOS column is no longer conditional it doesn't need to be pushed into columnDefinition, it can go inside the initial column definitions :)

**Review by aimee-mcneil-melville — APPROVED** [review]
Stunning! 🎉
