### PR TITLE
Remove disabled option from report selector

### LINKED ISSUE #8431: Unable to print labels when prescription is verified
## What went wrong? 😲

Should be able to still print a prescription label of a verified/finalised prescription but the option is grayed out right now. 

Please turn the option on.

** Update **
The main print button has been enabled, but the row/table action is disabled

Image

## Expected behaviour 🤔
Both print options should be enabled for Verified prescriptions

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #8431

# 👩🏻‍💻 What does this PR do?

Removes the option to disable the report selector, as we generally always want to allow report or printing if the use can view.

## 💌 Any notes for the reviewer?

Is there some reason why we do want to disable this? Examples seemed to be ok to me...

# 🧪 Testing

- [ ] Check reports/printing isn't disabled in prescriptions when verified.
- [ ] Check we haven't broken any reports or other functionality

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [X] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [X] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Stock/Components/Repack/RepackModal.tsx [hunk 1]
```diff
@@ -50,7 +50,6 @@ export const RepackModal: FC<RepackModalControlProps> = ({
   const { Modal } = useDialog({ isOpen, onClose });
 
   const [invoiceId, setInvoiceId] = useState<string | undefined>(undefined);
-  const [reportDisabled, setReportDisabled] = useState<boolean>(false);
```
Comment (jmbrunskill) [inline client/packages/system/src/Stock/Components/Repack/RepackModal.tsx:53]: From what I can see this was always set to false?

**Review by lache-melvin — CHANGES_REQUESTED** [review]
thanks James, will need to handle the repack case 🫠 🚀

**Comment by lache-melvin** [comment]
@jmbrunskill this one still on your radar? If needed I'm happy to pick up 🙏

**Comment by jmbrunskill** [comment]
@lache-melvin does this change cover the use case you were referring too? I can't actually seem so to figure out how to reliably replicate. I've tried delaying the requests, which I managed to trigger once. Since this change I can't seem to see a disabled button, so maybe I'm doing something wrong in my testing?

**Comment by jmbrunskill** [comment]
Also snuck in change after discussing with @mark-prins  to default to label printing for Prescriptions.
Most people aren't using the prescription receipt so will be less annoying for people to have to change for now.

**Comment by jmbrunskill** [comment]
Ah right I was always selecting a line then printing... Makes sense noW!
