### PR TITLE
6705 master list name hidden swap select for autocomplete

### LINKED ISSUE #6705: Master list name hidden when it is too long when creating a new stocktake
## What went wrong? 😲

UI modal issue while creating new location, stocktake patient, and prescription.
Text is hidden here when the masterlist name is too long
Image
Modal on full screen even if it is in the laptop window (expected this in android only)
Image
**Cerb Link:** 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: V2.6-RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #6705

# 👩🏻‍💻 What does this PR do?
Replace `Select` dropdown list component with `Autocomplete` component
 - Used existing `LocationSearchInput` to replace Location `Select`
 - Created new `MasterListSearchInput`component to replace Master List `Select` (this was done because all other instances where we select master lists uses `MasterListSearchModal`- seemed liked bad user experience to have a modal open inside another modal)
 - Modelled `MasterListSearchInput` off `LocationSearchInput`
 - This change now also allows for clearing selection  

Changes needed so that we can accommodate large lists and also to be more consistent with rest of the app.

`Master List selection field with popover open - shows full string`
Screenshot 2025-04-17 at 15 35 53

`Master List selection field after selection - shows ellipsis when text overflows`
Screenshot 2025-04-17 at 15 36 07

`Location selection field with popover open - shows full string`
Screenshot 2025-04-17 at 15 36 19

`Location selection field after selection - shows ellipsis when text overflows`
Screenshot 2025-04-17 at 15 36 33

## 💌 Any notes for the reviewer?
I was asked to check how this PR would impact #7194 but it looks like the scope of that issue has changed to only address `AutocompleWithPagination`. So I've added fixed width to the selection fields.

# 🧪 Testing

- [ ] Navigate to Inventory -> Stocktakes
- [ ] Create new stocktake to open modal

`Master List`
- [ ] Click on the Master List dropdown (ideally you would have a long master list name for testing)
- [ ] Observe that the master list name is shown in full in the selection dropdown and trimmed with ... once selected

`Location`
- [ ] Click on the Location dropdown (ideally you would have a long location name for testing)
- [ ] Observe that the location name is shown in full in the selection dropdown and trimmed with ... once selected

`Test Functionality`
- [ ] Observe that stocktake creation functionality works as expected with different filtering of master lists and location

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/MasterList/Components/MasterListSearchInput.tsx [hunk 1]
```diff
@@ -0,0 +1,112 @@
+import React, { FC } from 'react';
```
Comment (noel-yeldos) [inline client/packages/system/src/MasterList/Components/MasterListSearchInput.tsx:1]: Created this component because all other instances where we select master lists uses `MasterListSearchModal` - seemed liked bad user experience to have a modal open inside another modal. So thought this would be a good solution.

File: client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx [hunk 2]
```diff
@@ -192,16 +200,17 @@ export const CreateStocktakeButton: React.FC<{
...
-                          })
-                        }
-                        options={masterLists}
-                        value={createStocktakeArgs.masterListId}
+                            masterListId: masterList?.id ?? '',
+                          });
+                        }}
+                        disabled={false}
+                        selectedMasterList={selectedMasterList}
+                        width={380}
```
Comment (noel-yeldos) [inline client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx:213]: Have added fixed width to both dropdowns as scope of issue that was looking at Autocomplete styling has changed (issue mentioned in 'Notes for reviewer')

File: client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx [hunk 3]
```diff
@@ -69,6 +71,12 @@ export const CreateStocktakeButton: React.FC<{
   const [createStocktakeArgs, setCreateStocktakeArgs] =
     useState<CreateStocktakeArgs>(DEFAULT_ARGS);
 
+  const [selectedLocation, setSelectedLocation] =
```
Comment (noel-yeldos) [inline client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx:74]: Created these stateful variables to ensure that selection persists in UI

File: client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx (hunk 2 above)
Comment (aimee-mcneil-melville) [reply client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx:213]: Great, this works with the modal always being a fixed size

**Review by aimee-mcneil-melville — APPROVED** [review]
Thanks Noel, this looks great and works really well! 
I'm happy to approve as it is, modelling MasterListSearchInput from the LocationSearchInput works well and is visually consistent with the remove button in the list when opened - yay!

I do have some thoughts about the implementations and though you've likely already considered this I'd just like to mention it:

The use of the options renderer within the search component is usually used where like locations the selection will display multiple values such as 'code - name' which is not necessary here. An example like [ProgramSearchInput](https://github.com/msupply-foundation/open-msupply/blob/develop/client/packages/system/src/Program/ProgramSearchInput.tsx) is a cleaner and simpler component. However, this one instead has the remove button inline when the selection is closed, which can cause overlapping issues like this: 
Screenshot 2025-04-29 at 10 30 43 AM

As it seems the optionsRenderer is necessary for the remove option to display in the list this is a great solution for this issue, especially in terms of the consistency to the location search. 

I'll raise this all in issue for the ProgramSearchInput overlap, as there may be other ways to simplify and improve consistency throughout the app

**Comment by noel-yeldos** [comment]
Thanks @aimee-mcneil-melville! I hadn't considered the `ProgramSearchInput` but I understand your points. An inline remove button makes sense as I imagine users don't always want to scroll to the bottom of a large list to clear their selection. I implemented the changes in this PR to keep the functionality of the two input fields consistent as LocationSearchInput does have the remove button as part of the list of options. However, as this PR is introducing a new component for MasterListSearchInput I wonder if it needs a wider discussion around consistency as you've suggested.
