### PR TITLE
2560 program event remove stack fix

### LINKED ISSUE #2560: Removing program event stack uses wrong "stack end"
Bug from importing real data. Please see test case in PR.

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #2560 

# 👩🏻‍💻 What does this PR do? 
Fixes a program event bug and adds a test case for the failing setup.

Also refactor the existing tests to use a new `events()` helper method where possible.

# 🧪 How has/should this change been tested? 
Run test, with and without fix

### CODE REVIEW

File: server/service/src/programs/program_event.rs [hunk 1]
```diff
@@ -98,7 +98,7 @@ fn remove_event_stack(
     let mut current_end_datetime = longest.active_end_datetime;
     for mut current in previous_stack {
         current.active_end_datetime = current_end_datetime;
-        current_end_datetime = current.active_start_datetime;
+        current_end_datetime = std::cmp::min(current.active_start_datetime, current_end_datetime);
```
Comment (clemens-msupply) [inline server/service/src/programs/program_event.rs:101]: The actual fix

**Review by andreievg — APPROVED** [review]
Thanks @clemens-msupply. 

Approving, as per our conversation maybe good to
* Add diagram to the code explaining the reason for the fix
* If it's possible to name the test to reflect the logic, that would be great

**Comment by clemens-msupply** [comment]
Thank added a diagram/comment and renamed the test
