### PR TITLE
1684 refactor dashboard styline

### LINKED ISSUE #1684: Dashboard text wrapping
## What went wrong? 😲
 
If your screen is a little small, or you run the desktop version, you might see this:

Screenshot 2023-05-03 at 4 56 35 PM

## Expected behaviour 🤔
The dashboard should look pretty.

## Your environment 🌱
 - Version: 1.1.11
 - Platform: all

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #1684

# 👩🏻‍💻 What does this PR do? 
Changes dashboard to display better in cramped screens when the app bar is open

# 🧪 How has/should this change been tested? 
Open dashboard with a small screen (1024px wide laptop) 

## 💌 Any notes for the reviewer?
Some inline comments

### CODE REVIEW

File: client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ export interface StatsPanelProps {
 const Statistic: FC<Stat> = ({ label, value, link }) => {
   const t = useTranslation();
   return (
-    <Grid container alignItems="center" style={{ height: 30 }}>
```
Comment (fergie-nz) [inline client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx:26]: Remove fixed height of each satistic so that they can wrap text and won't sit on top of each other

File: client/packages/common/src/ui/components/domain/Dashboard/Widget.tsx [hunk 2]
```diff
@@ -17,7 +17,7 @@ export const Widget: React.FC<PropsWithChildren<WidgetProps>> = ({
   height = '100%',
   title,
 }) => (
-  <Paper
+  <Card
```
Comment (fergie-nz) [inline client/packages/common/src/ui/components/domain/Dashboard/Widget.tsx:20]: I've changed to a card here to avoid the Paper default 100% height property. That felt more clean than overriding Paper defaults, unless anyone is particularly attached to Paper?

File: client/packages/host/src/components/AppBar/AppBar.tsx [hunk 3]
```diff
@@ -31,25 +31,24 @@ export const AppBar: React.FC = () => {
...
     <>
       {hasVaccineModule && <ColdchainNotification />}
       <StyledContainer ref={ref} sx={containerStyle}>
-        <Toolbar disableGutters>
-          {!isDashboard && (
-            <>
-              <Box style={{ marginInlineEnd: 5 }}>
-                <SectionIcon />
-              </Box>
+        {!isDashboard && (
```
Comment (fergie-nz) [inline client/packages/host/src/components/AppBar/AppBar.tsx:41]: Removing tool bar for dashboard view

File: client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx (hunk 1 above)
Comment (fergie-nz) [reply client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx:26]: The Margin top adds spacing so that for single line text it doesn't look too cramped

**Comment by fergie-nz** [comment]
For these changes I've assumed that the minimum width would be a 1024px view (from a small laptop). Anything smaller than that and it will still break down.

Here is an example of the worst case of a narrow screen, open appbar, a wide number, and wrapping text:

0028DE9B-B33B-4CFB-9FE9-4F389AD5D5F4

**Review by mark-prins — APPROVED** [review]
🎉  Thanks - that's much better!

On first look, I thought that the spacing was too much 
**New**
Screenshot 2023-11-17 at 9 13 00 AM

**Old**
Screenshot 2023-11-17 at 9 13 43 AM

though now that I look again I don't mind it so much 🤷 .

All the same, I thought that I'd experiment a little and got to:

**big**
Screenshot 2023-11-17 at 9 28 52 AM

**small**
Screenshot 2023-11-17 at 9 29 00 AM

I've also lined up the text and right-aligned the numbers (for values up to 2 digits only though.. increasing the minWidth to `47` would allow for 3 digits, but I thought not worth it?)

For this, I've made the start of `StatsPanel` to be

```
const Statistic: FC<Stat> = ({ label, value, link }) => {
  const t = useTranslation();
  return (
    <Grid container alignItems="center" sx={{ marginTop: 1 }}>
      <Grid
        item
        sx={{ minWidth: '30px', display: 'flex', justifyContent: 'flex-end' }}
      >
        {value ? (
          <Typography
            style={{ fontSize: 24, fontWeight: 'bold', lineHeight: 1.2 }}
          >
            {value}
          </Typography>
```

what do you think?

**Comment by fergie-nz** [comment]
That is cool, Mark. I like that spacing.

I'll add that in.

Are you happy with Merging like so? I am not entirely confident I've covered all of the user use cases with me playing around with the system.

**Comment by mark-prins** [comment]
yep - happy with merging. What you've done is already better than the original!
