### PR TITLE
Don't convert dob to naivedate

### LINKED ISSUE #5869: Unable to select certain dates of births when editing a patient
## What went wrong? 😲

Noticed this behaviour with a date picker - unable to select certain dates of births for a patient. And when selecting a date, it seems to select the day before?

https://github.com/user-attachments/assets/d4baee0d-e830-47c3-8351-87b7c352c791

Unsure if related to #5438 - also have a suspicion it might be something to do with the patient being exactly one month old?

## Expected behaviour 🤔

Should be able to select any date as the date of birth

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Patients
2. Create a new patient or edit an existing one
3. Play around with their date of birth - try setting it to be 29 days, 30 days, 1 month and 1 day, etc. Save and refresh, go in and make changes - see if you can run into the issue above

## Your environment 🌱

- Open mSupply Version: V2.5.0-reports
- Legacy mSupply Central Server Version: V7.19.00

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #5869

# 👩🏻‍💻 What does this PR do?
Don't convert selected value to naivedate

- [ ] Go to patient
- [ ] Try selecting a variety of dates as the birth date

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Review by mark-prins — APPROVED** [review]
❤️  I'm a little nervous.. this is a minefield of unintended consequences.. but let's do it!

**Comment by CarlosNZ** [comment]
Didn't we just change this to this fairly recently? Have we tested that this doesn't display the wrong date at certain times of the day?

**Comment by roxy-dao** [comment]
> Didn't we just change this to this fairly recently? Have we tested that this doesn't display the wrong date at certain times of the day?

Yeah I tested it and converting to naive date does change the date to day before.. but also don't see why we are converting to naive date? DOB is saved as a date and no matter what time zone you are in... if you are born on 1st Jan then you are born on first Jan... or is this supposed to change to 31st December when you change timezones?

**Comment by CarlosNZ** [comment]
> if you are born on 1st Jan then you are born on first Jan... or is this supposed to change to 31st December when you change timezones?

No, you are correct, but that's what "naive date" is supposed to be -- a date that doesn't care about what timezone it's in. Is that correct? Changing this to naive date was the fix for the DOB jumping back a day before, so I'm struggling to understanding how changing it back would help.

I'll give this a quick test after lunch just to convince myself either way.

**Comment by roxy-dao** [comment]
> > if you are born on 1st Jan then you are born on first Jan... or is this supposed to change to 31st December when you change timezones?
> 
> No, you are correct, but that's what "naive date" is supposed to be -- a date that doesn't care about what timezone it's in. Is that correct? Changing this to naive date was the fix for the DOB jumping back a day before, so I'm struggling to understanding how changing it back would help.
> 
> I'll give this a quick test after lunch just to convince myself either way.

But it was jumping with the naive date 🤔

**Comment by CarlosNZ** [comment]
> But it was jumping with the naive date 🤔

It might be because the double conversion. Probably only needs naive date for input/save, and then can just display that in local time.

File: client/packages/programs/src/JsonForms/components/DateOfBirth.tsx [hunk 1]
```diff
@@ -61,7 +61,6 @@ const UIComponent = (props: ControlProps) => {
 
   useEffect(() => {
     if (!data) return;
-    const dob = DateUtils.getNaiveDate(data.dateOfBirth);
     setDoB(dob);
```
Comment (CarlosNZ) [inline client/packages/programs/src/JsonForms/components/DateOfBirth.tsx:64]: I think you still need this one. 

Firstly,  you're just setting `dob` to itself here now, if you remove the locally-defined `dob` 😆 -- that's why you're not seeing the "error", but you'll notice if you save and refresh, the date is gone altogether!

I would put the original back, but change the locally scoped `dob` to something else to avoid this confusion.

This seems to work for me:
```ts
  useEffect(() => {
    if (!data) return;
    const newDob = DateUtils.getNaiveDate(data.dateOfBirth);
    setDoB(newDob);
    if (newDob === null) {
      setAge(undefined);
      return;
    }
    setAge(DateUtils.age(newDob));
  }, [data]);
```

To convince yourself it's correct, do the following:
- set your system timezone to something that is still "yesterday" relative to us (I used "New York", but that'll only work for the next 4 hours)
- adjust the DOB and save, and refresh to check that is has saved and is correct
- change your system back to NZ timezone
- refresh the page, the DOB should show the same date, not have jumped forward a day.

Comment (roxy-dao) [reply client/packages/programs/src/JsonForms/components/DateOfBirth.tsx]: Yeah sorry, was supposed to revert. But then I did something else and have just come back from lunch

**Review by CarlosNZ — APPROVED** [review]
Don't love the name (`localDob` is pretty unclear if you weren't part of our previous convo), but I won't hold it up. 

Thanks 🙏
