### PR TITLE
8081 add logs to android error page

### LINKED ISSUE #8081: Android app fails to start with 'oops something went wrong' screen
## Summary of investigation

Connected with Android Studio, saw "unexpected syntax ?" in log, this is only visible if doing 'chrome://inspect' on your compute, while connecting with usb debug, developer mode (can look at console and see same error).

Chrome version was a bit old, didn't have required js target. Updated chrome (via play store), works.

## Still to do in this issue

Where to document this ?

Still add logs to oops page ?

## What went wrong? 😲

On fresh install, app fails to start with 'oops something went wrong' screen.

Subsequent restarts have the same error. Eventually app starts normally

Image

## Expected behaviour 🤔

App start or indication to user what went wrong

## Extra context

This is a bit hard to re-produce, my assumption is that migrations take a long time to run, especially on slower devices. 

Also drop and re-create views may take long, on every restart, so first time after re-install back button wouldn't work and on subsequent restarts drop view may take awhile but back button should work.

Would suggest progress for migrations: https://github.com/msupply-foundation/open-msupply/issues/4745

Need a way to get 'logs' without fully loading server, would suggest some sequence of presses etc, to get the logs.

Also maybe drop and re-create views should only run when at least one migration or migration fragment has run, although that still needs progress

## How to Reproduce 🔨

A bit hard to re-produce, I made a build for this with timeouts on every migration: 
https://www.dropbox.com/scl/fi/5yvvsl3vrhxg400b3hx1b/open-msupply-2.7.06-slow-migration.apk?rlkey=xlg7e9q9z7u4cf17bynb49c9v&st=8gy7pvwk&dl=1

I've also adde a show log file (maybe that's enough for now) in the ErrorPage:

[show_logs.diff.zip](https://github.com/user-attachments/files/20651299/show_logs.diff.zip)

[This is the build with show log files and delay](https://www.dropbox.com/scl/fi/p99pfchs3woglm67zzyga/open-msupply-2.7.06-delay-and-show-logs.apk?rlkey=r59326fhulcpomnun1tomyq8f&st=zs0g11t3&dl=1)

And another one to debug current problem in ST ([2.6.7 with show log file](https://www.dropbox.com/scl/fi/w9twwh086nl8g2o9gtih3/open-msupply-2.7.06-view-logs-on-error.apk?rlkey=ig880w6sop242mqiwp155kr71&st=dm07fkw2&dl=1))

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #8081

# 👩🏻‍💻 What does this PR do?

Add a `Show Logs` button to the `Error` page when the app doesn't start up correctly on Android. Logs are viewable in the modal that opens

In `Settings` -> `Server Settings` the view logs modal is now shared between web and android for a consistent view. The `Copy` button is hidden on Android as it is not needed (and doesn't work as-is). Is the same both on client or server mode

Error starting app:
https://github.com/user-attachments/assets/c4642204-1b9e-419a-b566-124bb509d20a

Save logs in app:
https://github.com/user-attachments/assets/68b16d23-1be0-4980-9d82-0b7158472414

In Android APK server mode, other files were visible (certs etc) as they reside in the same folder. The dropdown now has a front end filter and will only show `.log` file names
image

Also fixed the query key as the query for the file content would only run on the first file selected - there can be multiple log files on a device so need to be able to access each of them

Made some changes in android readme for ease of use

## 💌 Any notes for the reviewer?

Some improvements that could still be made to this: 
- Loading spinner only appears on first query
- Save button should have a loading state
- Is generally slow

I did have a look at getting a quick fix in for these but will need a bit of an overhaul

Follow up to tidy up logs - @andreievg has more on this

# 🧪 Testing

Have a tablet setup and server running to connect to

- [ ] Download APK here - https://drive.google.com/file/d/1nuqoMa-M7GMjqiEHNjtD72Fq5PkkQuSc/view?usp=drive_link -updated 17/7
- [ ] Start the server locally and open the app on tablet
- [ ] Go to Settings -> Server settings -> See error page and View Logs button - can access the logs
- [ ] See there is no `Copy to Clipboard` button
- [ ] Test that the log file can be selected, saved and opened
- [ ] add the following delay to the [server lib file](https://github.com/msupply-foundation/open-msupply/blob/1d79138f810d64a5122673a82493f5ce4cb80f3b/server/server/src/lib.rs) from line 320:
`  info!("Delaying server startup by 20 seconds...");
    tokio::time::sleep(std::time::Duration::from_secs(20)).await;`
Screenshot 2025-07-14 at 12 19 39 PM
- [ ] Restart the local server and the app
- [ ] The app should not start correctly and show the error page
- [ ] See View Logs button - can view the logs in the modal

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/android/app/src/main/java/org/openmsupply/client/ErrorPage.java [hunk 1]
```diff
@@ -27,11 +46,13 @@ public class ErrorPage {
             "      >\n" +
             "        <title>Error illustration</title>\n" +
             "        <defs>\n" +
-            "          <linearGradient x1=\"30.668%\" y1=\"40.384%\" x2=\"65.881%\" y2=\"53.418%\" id=\"prefix__c\">\n" +
+            "          <linearGradient x1=\"30.668%\" y1=\"40.384%\" x2=\"65.881%\" y2=\"53.418%\" id=\"prefix__c\">\n"
```
Comment (aimee-mcneil-melville) [inline client/packages/android/app/src/main/java/org/openmsupply/client/ErrorPage.java:49]: These are re-formatting of the SVG - no functional change here

File: client/packages/android/app/src/main/java/org/openmsupply/client/ErrorPage.java [hunk 2]
```diff
@@ -242,8 +277,57 @@ public class ErrorPage {
             "  </div>\n" +
             "  <div>\n" +
             "    <h5>Oops! Something's gone wrong.</h5>\n" +
+            "     <button\n" +
```
Comment (aimee-mcneil-melville) [inline client/packages/android/app/src/main/java/org/openmsupply/client/ErrorPage.java:280]: Functional changes here - new button and function

File: client/packages/common/src/utils/files/FileUtils.ts [hunk 3]
```diff
@@ -82,6 +82,17 @@ export const useExportCSV = () => {
   return exportCsv;
 };
 
+export const useExportLog = () => {
```
Comment (aimee-mcneil-melville) [inline client/packages/common/src/utils/files/FileUtils.ts:85]: new function to handle exporting log on webview vs android, using the new android export format

File: client/packages/android/README.MD [hunk 4]
```diff
@@ -197,21 +197,20 @@ abiFilters "armeabi-v7a", "arm64-v8a"
...
-## Debugging
-
-To make the an apk that you can install on a device for testing, run `yarn android:build:debug` in the client directory.
-You can then transfer it to the tablet and install it. This can be done by uploading the apk file via the android studio device manager, then clicking the apk file from the device itself. Or using [adb](https://developer.android.com/tools/adb)
+## Debugging with Android Studio
 
 It's recommended to use Android Studio for debugging and running the Android app, because there is a lot of functionality that cannot be replicated in Visual Studio Code (although there are some extensions for Visual Studio Code, they are quite limited).
 
-Open this directory (client/packages/android) in Android Studio - this will engage the gradle sync process (initialising pre-requisites etc.), if you get an error during 'sync' process Android Studio should outline the issue with suggested fix.
+Run `yarn android:build:debug` in the client folder and connect the tablet via USB (check USB debugging is enabled in the tablet settings).
```
Comment (andreievg) [inline client/packages/android/README.MD:204]: I think `androud:build:server` would be sufficient

File: client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java [hunk 5]
```diff
@@ -341,23 +345,20 @@ public void sendTabKeyPress(PluginCall call) {
                 eventTime,
                 KeyEvent.ACTION_DOWN,
                 KeyEvent.KEYCODE_TAB,
-                0
-        );
+                0);
```
Comment (andreievg) [inline client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java:348]: I think you'll avoid a lot of these formatting issues if you save files with Android Studio, although I am not fully sure about that

File: client/packages/host/src/Admin/ServerSettings.tsx [hunk 6]
```diff
@@ -1,142 +1,35 @@
...
-  const [isDownloading, setIsDownloading] = useState(false);
   const t = useTranslation();
   const {
     isOn: isLogShown,
     toggleOn: showLog,
     toggleOff: hideLog,
   } = useToggle();
-  const toggleNativeMode = () => {
-    const mode =
-      nativeMode === NativeMode.Server ? NativeMode.Client : NativeMode.Server;
```
Comment (andreievg) [inline client/packages/host/src/Admin/ServerSettings.tsx:43]: Have you had a look at diff in this file in the self review ?

**Review by andreievg — CHANGES_REQUESTED** [review]
Hi, looks great, thanks.

I have a question in ServerSettings.tsx

File: client/packages/host/src/Admin/ServerSettings.tsx (hunk 6 above)
Comment (aimee-mcneil-melville) [reply client/packages/host/src/Admin/ServerSettings.tsx]: Oops! I have added back in the rest of the settings for android.. Thanks Andrei!

**Comment by aimee-mcneil-melville** [comment]
Thanks for the review and assistance Andrei! 
I have made some changes and edited the main comment with updates

**Review by andreievg — APPROVED** [review]
Looks great thanks @aimee-mcneil-melville
