### PR TITLE
#6083 #6090 #6061 #6059 Prescription hotfixes x4

### LINKED ISSUE #6083: Can still edit details of a verified Prescriptions
## What went wrong? 😲

Verified a prescription but the input is still enabled, thus can change issue and directions. Also even if you don't edit this, and navigate away, the "unsaved changes" modal pops up

Screenshot_20250116_113221_Open mSupply

## Expected behaviour 🤔
Shouldn't be able to edit details of a finalised prescription.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a prescription
2. Add an item
3. Verify prescription
4. Go back to the edit page
5. See that input is still enabled

## Your environment 🌱

- Open mSupply Version: v2.5.0-RC3
- Legacy mSupply Central Server Version: Android

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #6083 #6090 #6061 #6059

(There's one more dispensing hotfix (#6078), but that'll require a bit more thinking about, so will do separately.)

# 👩🏻‍💻 What does this PR do?

Four small fixes for the above issues.

I've done each in a different commit, so you can review them individually if you like:

#6083 e249b567c5
#6090 d6767fb83d
#6061 9b825cdb5a
#6059 3953898422

I've also mentioned the issue # in my review comments below.

## 💌 Any notes for the reviewer?

See review comments for more details

# 🧪 Testing

These are all really tiny, so please just refer to the original issues and confirm behaviour is fixed when doing the "How to reproduce" steps.

### CODE REVIEW

File: client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx [hunk 1]
```diff
@@ -138,6 +138,7 @@ export const PrescriptionLineEditView = () => {
       );
     }
     setIsDirty(false);
+    setAllDraftLines({});
```
Comment (CarlosNZ) [inline client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx:141]: Fix for #6061. Problem was the item ended up in the `allDraftLines` array twice -- once indexed by `"new"` and once indexed by its ID. Best to just start with a fresh object after a save (same as when you first load the page).

File: client/packages/invoices/src/Prescriptions/LineEditView/hooks/usePrescriptionLineEditRows.ts [hunk 2]
```diff
@@ -54,8 +57,9 @@ export const usePrescriptionLineEditRows = (rows: DraftStockOutLine[]) => {
   }, [allocatableRows, wrongPackSizeRows, onHoldRows, noStockRows]);
 
   const disabledRows = useMemo(() => {
+    if (isDisabled) return orderedRows;
```
Comment (CarlosNZ) [inline client/packages/invoices/src/Prescriptions/LineEditView/hooks/usePrescriptionLineEditRows.ts:60]: Fix for #6083

If the prescription is verified, it is `disabled`, so we make sure *all* rows are disabled.

Unfortunately adds another prop that must be passed down through about 3 levels 🙄

File: client/packages/invoices/src/StockOut/utils.tsx [hunk 3]
```diff
@@ -406,8 +406,9 @@ export const UnitQuantityCell = (props: CellProps<DraftStockOutLine>) => (
       (props.rowData.stockLine?.packSize ?? 1)
     }
     id={getPackQuantityCellId(props.rowData.stockLine?.batch)}
-    decimalLimit={2}
     min={0}
+    // We're not allowing non-integer values (decimalLimit=0), as you can only
+    // issue whole units
```
Comment (CarlosNZ) [inline client/packages/invoices/src/StockOut/utils.tsx:411]: Fix for #6090. Remove `decimalLimit` prop which forces an integer.

Comment (roxy-dao) [reply client/packages/invoices/src/StockOut/utils.tsx:411]: idk if we want to fix this one because of the use case I mentioned in issue 🤔 maybe revert this change and just close the bug? 🤔

**Review by roxy-dao — APPROVED** [review]
Awesome~ Thanks Carl
