### PR TITLE
2276 handle dynamic sort from datatable UI to the stocktake report

### LINKED ISSUE #2276: Stocktake report not sorting correctly
## What went wrong? 😲
Stocktake report has no sorting level? Generated report list is random?(unsure but unable to see any pattern in the report like alphabetically or numerically etc)
Screenshot 2023-09-25 at 1 07 07 PM

## Expected behaviour 🤔
For report to generate based on how the list in omsupply is arranged (if possible)

https://github.com/openmsupply/open-msupply/assets/143057869/52bbb2ce-3e5b-4105-93b7-cfb3ab1492ef

Otherwise, if the report can be sorted by location (1st), then item name alphabetically (2nd) as this makes stocktaking easier to perform. 
(Note would also need the same to be on omSupply - will make a seperate request about Location column in the stocktake list)

## How to Reproduce 🔨
No

Steps to reproduce the behaviour:

## Your environment 🌱
v 1.3 Desktop

### PR DESCRIPTION
**Pull request by raviSussol**
Fixes #2276 

# 👩🏻‍💻 What does this PR do? 
 
Handle sorting in the stocktake report by passing current column sort status to the backend report data graphql schema.

# 🧪 How has/should this change been tested? 

Goto the stock input page and try to sort report columns (like code, location, item name) and click `Print`

Note: Please use this [stocktake_with_quantity.json](https://github.com/openmsupply/open-msupply/files/13246875/stocktake_with_quantity.json) for stocktake report to be working.

## 💌 Any notes for the reviewer?

Have created a separate graphql endpoint for the stocktake report - just to isolate the existing one from having a lot of code changes

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/DataTable.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ import { useFormatDateTime, useTranslation } from '@common/intl';
 import { useTableStore } from './context';
 
 interface RenderRowsProps<T extends RecordWithId> {
-  ref: React.RefObject<HTMLDivElement>;
+  mRef: React.RefObject<HTMLDivElement>;
   data: T[];
```
Comment (raviSussol) [inline client/packages/common/src/ui/layout/tables/DataTable.tsx:30]: This is to fix console error for datatable component.
Screenshot 2023-10-07 at 10 32 45 AM

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 2]
```diff
@@ -56,6 +56,26 @@ export const useStocktakeColumns = ({
...
+          return row.location?.code ?? '';
+        },
+        accessor: ({ rowData }) => {
+          if ('lines' in rowData) {
+            const { lines } = rowData;
+            return lines.reduce((_, line) => line.location?.code ?? '', '');
+          }
+          return rowData.location?.code;
+        },
+      },
```
Comment (raviSussol) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:78]: Added an extra `Location` column in the stocktake input page for a user to make sorting by location code easier in the report.

File: server/graphql/core/src/loader/stocktake_lines_report.rs [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+#[derive(Clone)]
+/// This struct is used as a key for the loader to load stocktake lines by stocktake id
+/// and sort them by sort field
+pub struct StocktakeBatchParams {
+    /// Stocktake id to load stocktake lines
+    pub stocktake_id: String,
+    /// Sort field to sort stocktake lines
+    pub sort: Option<DataSort>,
+}
```
Comment (raviSussol) [inline server/graphql/core/src/loader/stocktake_lines_report.rs:26]: Workaround with passing struct as a key for loader function to pass extra arguments. Not sure if this is a best practice to follow. Would love to have a take/suggestion on this.

File: client/packages/common/src/ui/layout/tables/DataTable.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/common/src/ui/layout/tables/DataTable.tsx:30]: good spotting! thanks

File: client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx [hunk 4]
```diff
@@ -31,14 +33,44 @@ export const AppBarButtonsComponent: FC<AppBarButtonProps> = ({
   const { data } = useStocktake.document.get();
   const { print, isPrinting } = useReport.utils.print();
 
+  const [isReportPrinting, setIsReportPrinting] = useState(false);
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx:36]: The changes in here aren't required - there's a `useCallback` in the report selector which doesn't have any dependencies.. this is causing your problem!

Try this suggestion: [2276-fix-stocktake-report-sorting-suggestion](https://github.com/openmsupply/open-msupply/compare/2276-fix-stocktake-report-sorting-issue...2276-fix-stocktake-report-sorting-suggestion) - it's working for me.

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts (hunk 2 above)
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:78]: I think location name is more useful? In which case you can use the existing column definition and just extend to get the sort value and accessor:

```suggestion
[
        'locationName',
        {
          getSortValue: row => {
            if ('lines' in row) {
              const { lines } = row;
              return (
                lines.reduce((_, line) => line.location?.name ?? '', '') ?? ''
              );
            }
            return row.location?.code ?? '';
          },
          accessor: ({ rowData }) => {
            if ('lines' in rowData) {
              const { lines } = rowData;
              return lines.reduce((_, line) => line.location?.name ?? '', '');
            }
            return rowData.location?.code;
          },
        },
      ],
```

**Review by mark-prins — CHANGES_REQUESTED** [review]
The sort in the appbarbuttons can be simplified by fixing a problem in the ReportSelector - see what you think.

I also think location name is better than code in the list 🙏 

and I have concerns about using a generic `DataSortInput` when we have specific sort objects which define which columns can be used for sorting. Is it necessary?

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts (hunk 2 above)
Comment (raviSussol) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts]: Had tried extending column for location code but was getting type error. So used key, label, ... way define location code column. Though it was working with location name without any errors. Have change location code to name. f7ea6f2ff

File: client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx (hunk 4 above)
Comment (raviSussol) [reply client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx]: Ah... I see.. Nice. Updated bec90a205 and its working for me too. Thanks for the idea.

**Comment by raviSussol** [comment]
> I have concerns about using a generic DataSortInput when we have specific sort objects which define which columns can be used for sorting. Is it necessary?

Not necessary. Or the `sortBy` argument is optional. Only required when we need to sort reports (stocktake, invoice, requisition, ...etc) from the UI dynamically.

File: client/packages/system/src/Report/api/api.ts [hunk 5]
```diff
@@ -7,6 +12,12 @@ export type ReportListParams = {
   sortBy: SortBy<ReportRowFragment>;
   offset: number;
 };
+export type PrintReportParams = {
```
Comment (andreievg) [inline client/packages/system/src/Report/api/api.ts:15]: Can you please use "QueriesPrintReportArgs" in PrintReportParams vs new type

**Review by andreievg — CHANGES_REQUESTED** [review]
Overall this looks very good Ravi, thanks !

The issue is actually a duplicate of: https://github.com/openmsupply/open-msupply/issues/1402, sorry I couldn't find the solution that i was suggesting for that issue, it must have been just made on telegram, but I think instead of a brand new query for stacktake, we should just expose lines (existing node) in a new query "stocktakeLines", and instead of accessing lines through stocktake, have another query in (like the store query), filtered by $dataId, sort will just be String! type input, and it's up to the report creator to make sure that sort matches the context when report is called.


So a few changes please:

* Update from develop (locationName already in useStocktakeLine)
* Create a new query for stocktake line (with check to make sure line belongs to stocktake that user can access, by storeId), instead of creating a complete new query for stocktake report with all new nodes.

Although your change looks good, the main reason for change request is the amount of code that needs to be maintained in the future (by keeping existing nodes and just creating a one extra query, we reduce code changes quite a lot)

**Review by andreievg — CHANGES_REQUESTED** [review]
Overall this looks very good Ravi, thanks !

The issue is actually a duplicate of: https://github.com/openmsupply/open-msupply/issues/1402, sorry I couldn't find the solution that i was suggesting for that issue, it must have been just made on telegram, but I think instead of a brand new query for stacktake, we should just expose lines (existing node) in a new query "stocktakeLines", and instead of accessing lines through stocktake, have another query in (like the store query), filtered by $dataId, sort will just be String! type input, and it's up to the report creator to make sure that sort matches the context when report is called.


So a few changes please:

* Update from develop (locationName already in useStocktakeLine)
* Create a new query for stocktake line (with check to make sure line belongs to stocktake that user can access, by storeId), instead of creating a complete new query for stocktake report with all new nodes.

Although your change looks good, the main reason for change request is the amount of code that needs to be maintained in the future (by keeping existing nodes and just creating a one extra query, we reduce code changes quite a lot)

**Review by andreievg — CHANGES_REQUESTED** [review]
Overall this looks very good Ravi, thanks !

The issue is actually a duplicate of: https://github.com/openmsupply/open-msupply/issues/1402, sorry I couldn't find the solution that i was suggesting for that issue, it must have been just made on telegram, but I think instead of a brand new query for stacktake, we should just expose lines (existing node) in a new query "stocktakeLines", and instead of accessing lines through stocktake, have another query in (like the store query), filtered by $dataId, sort will just be String! type input, and it's up to the report creator to make sure that sort matches the context when report is called.


So a few changes please:

* Update from develop (locationName already in useStocktakeLine)
* Create a new query for stocktake line (with check to make sure line belongs to stocktake that user can access, by storeId), instead of creating a complete new query for stocktake report with all new nodes.

Although your change looks good, the main reason for change request is the amount of code that needs to be maintained in the future (by keeping existing nodes and just creating a one extra query, we reduce code changes quite a lot)

**Comment by raviSussol** [comment]
@andreievg Thanks for reviewing. Was curious about what value the sort argument would contain with a string type?

**Comment by andreievg** [comment]
@raviSussol, something [like this](https://github.com/openmsupply/open-msupply/compare/develop(Example-of-report-sort-and-stocktake-line-end-point)) for string sort. Please notice that two sorts are present, one is typed and the other is string (report <- common type). And then there is a generic report_sort_to_typed_sort method, which does the conversion (using serde rather then to_string() for 'style' i.e. camelCase, maybe that's not important and we should just convert to lowercase and compare ?). 
Also report_sort_to_type_sort can try convert to underlying sort input type, but then that input type will need to use a new trait (I don't think we want that much indirection for now)

**Comment by raviSussol** [comment]
@andreievg Thanks for the idea. Have updated the pr. Let me know if there's any changes needed.

**Comment by raviSussol** [comment]
Btw, I've lowercased the sorting key after conversion to compare since `serde_json::to_string` method returns the word in upper camel case. I'm not sure if `#[graphql(rename_items = "camelCase")]` is supposed to handle that for the struct `StocktakeLineSortFieldInput`?

**Comment by raviSussol** [comment]
Another follow up pr related to this pr: https://github.com/openmsupply/open-msupply-reports/pull/48

File: server/graphql/stocktake_line/src/stocktake_line_queries.rs [hunk 6]
```diff
@@ -0,0 +1,337 @@
...
+        },
+    )?;
+
+    let service_provider = ctx.service_provider();
+    let service_ctx = service_provider.context(store_id.to_string(), user.user_id)?;
+    let service = &service_provider.stocktake_line_service;
+
+    let stocktake_filter = filter.clone().map(StocktakeLineFilter::from);
+
+    let mut stocktake_id = "".to_string();
```
Comment (andreievg) [inline server/graphql/stocktake_line/src/stocktake_line_queries.rs:103]: I think instead of filter this should be graphql query parameter. This should simplify this a little bit

File: server/graphql/stocktake_line/src/stocktake_line_queries.rs [hunk 7]
```diff
@@ -0,0 +1,337 @@
...
+        let formatted_error = format!("{:#?}", err);
+        let graphql_error = match err {
+            GetStocktakeLinesError::DatabaseError(err) => err.into(),
+            GetStocktakeLinesError::InvalidStore => {
+                StandardGraphqlError::BadUserInput(formatted_error)
+            }
+            GetStocktakeLinesError::InvalidStocktake => {
+                StandardGraphqlError::BadUserInput(formatted_error)
+            }
+            GetStocktakeLinesError::ListError(err) => match err {
```
Comment (andreievg) [inline server/graphql/stocktake_line/src/stocktake_line_queries.rs:141]: I think just `return Err(list_error_to_gql_error(err))` ?

File: server/service/src/report/definition.rs [hunk 8]
```diff
@@ -41,6 +51,16 @@ impl GraphQlQuery {
                 variables[key] = value;
             }
         };
+
+        if let Some(sort) = sort {
+            let mut sort_value = serde_json::json!({});
```
Comment (andreievg) [inline server/service/src/report/definition.rs:56]: I wonder if this would work ?
```rust
variables["sort"] = json!{
    key: sort.key,
    desc: sort.desc
}
```

File: server/graphql/stocktake_line/src/stocktake_line_queries.rs [hunk 9]
```diff
@@ -0,0 +1,337 @@
...
+                ListError::DatabaseError(err) => err.into(),
+                ListError::LimitBelowMin(_) => StandardGraphqlError::BadUserInput(formatted_error),
+                ListError::LimitAboveMax(_) => StandardGraphqlError::BadUserInput(formatted_error),
+            },
+        };
+        Err(graphql_error.extend())
+    }
+}
+
+pub fn report_sort_to_typed_sort<T: IntoEnumIterator + Serialize>(
```
Comment (andreievg) [inline server/graphql/stocktake_line/src/stocktake_line_queries.rs:151]: can this be next to PrintReportSortInput, in generic_inputs ?

**Review by andreievg — COMMENTED** [review]
This looks really good Ravi, thanks !

Sorry still have a few small things please.


> I'm not sure if #[graphql(rename_items = "camelCase")] is supposed to handle that for the struct StocktakeLineSortFieldInput?

Can use serde for this:

https://github.com/msupply-foundation/open-msupply/compare/2276-fix-stocktake-report-sorting-issue...2276-fix-stocktake-report-sorting-issue(Lowercase-conversion-in-serde)


Can you also fix confclits with develop please.

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 10]
```diff
@@ -65,6 +65,27 @@ export const useStocktakeColumns = ({
 
   return useColumns<StocktakeLineFragment | StocktakeSummaryItem>(
     [
+      [
+        'locationName',
```
[the remark this answers is not in the document]
Comment (raviSussol) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:69]: You mean already exists in the `develop`? Couldn't see in the conflict files.

File: client/packages/common/src/ui/layout/tables/DataTable.tsx [hunk 11]
```diff
@@ -38,7 +38,7 @@ interface RenderRowsProps<T extends RecordWithId> {
   additionalRows?: JSX.Element[];
 }
 const RenderRows = <T extends RecordWithId>({
-  ref,
+  mRef,
```
[the remark this answers is not in the document]
Comment (raviSussol) [reply client/packages/common/src/ui/layout/tables/DataTable.tsx:41]: To fix this one: https://github.com/msupply-foundation/open-msupply/pull/2342/#discussion_r1349460909

File: server/graphql/stocktake_line/src/stocktake_line_queries.rs (hunk 6 above)
Comment (raviSussol) [reply server/graphql/stocktake_line/src/stocktake_line_queries.rs:104]: Yeah could simplify that but I thought to handle it through the filter so that this graphql endpoint becomes reusable for any cases? Making `stocktake_id` parameter to this method makes this endpoint stocktake id specific (where we might not be able to just use this endpoint to get just stocktake lines - not sure where we use it thought).

Comment (andreievg) [reply server/graphql/stocktake_line/src/stocktake_line_queries.rs:104]: I had similar thought, but I couldn't quite figure out the use case for it, plus the service requires stocktake_id. I think if we need it in the future we can make another end point for all stocktake lines. 
Do you mind changing to stocktake_id in query parameters for now, and we can explore other options in the future, when the use case arrises, thanks !

File: server/graphql/stocktake_line/src/stocktake_line_queries.rs (hunk 7 above)
Comment (raviSussol) [reply server/graphql/stocktake_line/src/stocktake_line_queries.rs:146]: I had used that method before but was getting incompatible error types. It expects the `StandardGraphqlError` error type to be returned. But the `` method returns the `async_graphql::Error` error type.

File: server/service/src/report/definition.rs (hunk 8 above)
Comment (raviSussol) [reply server/service/src/report/definition.rs]: 23fa9568a It did! Thanks.

File: server/graphql/stocktake_line/src/stocktake_line_queries.rs (hunk 9 above)
Comment (raviSussol) [reply server/graphql/stocktake_line/src/stocktake_line_queries.rs]: 1695bb79c

File: server/graphql/stocktake_line/src/stocktake_line_queries.rs (hunk 6 above)
Comment (raviSussol) [reply server/graphql/stocktake_line/src/stocktake_line_queries.rs]: f9f96d248

File: client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx [hunk 12]
```diff
@@ -31,12 +32,21 @@ export const AppBarButtonsComponent: FC<AppBarButtonProps> = ({
   const { data } = useStocktake.document.get();
   const { print, isPrinting } = useReport.utils.print();
 
+  const {
+    queryParams: { sortBy },
+  } = useUrlQueryParams({ initialSort: { key: 'itemName', dir: 'asc' } });
```
[the remark this answers is not in the document]
Comment (raviSussol) [reply client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx]: Make sense! 46cf7f80f

**Review by andreievg — APPROVED** [review]
@raviSussol thanks, this is great, btw this is what i mean for the error mapping
https://github.com/msupply-foundation/open-msupply/compare/2276-fix-stocktake-report-sorting-issue...2276-fix-stocktake-report-sorting-issue(Use-list-error-to-gql-err)

Would you be doing similar to invoices ?

**Comment by raviSussol** [comment]
> @raviSussol thanks, this is great, btw this is what i mean for the error mapping

Ah I see.. didn't use `Err` wrapper function with `list_error_to_gql_err` method. Thanks updated with 05e96188b

File: server/graphql/stocktake_line/src/stocktake_line_queries.rs (hunk 7 above)
Comment (raviSussol) [reply server/graphql/stocktake_line/src/stocktake_line_queries.rs]: 05e96188b

**Comment by raviSussol** [comment]
Hi @mark-prins do you have anything to review further or suggestion you want to share in this pr?

**Comment by mark-prins** [comment]
> Hi @mark-prins do you have anything to review further or suggestion you want to share in this pr?

No - thanks @raviSussol, it's looking great. Am just looking at why the tests were complaining - will pop in some changes if needed.

**Review by mark-prins — APPROVED** [review]

**Comment by raviSussol** [comment]
Thanks for checking @mark-prins I think I've forgotten to lowercase the `SortField` struct for testing as (just like `StocktakeLineSortFieldInput`) 438d72121
