### PR TITLE
4180 customer requisition doesn’t accept the decimal values that came form msupply sites via internal orders and remote auth

### LINKED ISSUE #4180: Customer Requistion doesn’t accepts the decimal Values that came form mSupply sites via Internal Orders and remote auth
## What went wrong? 😲

Screenshot 2024-06-18 at 16 55 03

Screenshot 2024-06-18 at 15 37 26

## Expected behaviour 🤔

The decimal values in Customer Requisition should also synced.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. mSupply and Open mSupply Setup
2. Make sure items are visible on both mSupply Store and Open mSupply Store
3. Create IO form mSupply store for Open mSupply Store
4. Enter the Requested quantities in decimal
5. Finalize the IO
6. SYNC
7. See the related CR on Open mSupply Store
8. See the decimal Values not synced (BUG)
9. Same issue for by remote auth (BUG)

## Your environment 🌱

- Open mSupply Version: v2.1-decimal
- Legacy mSupply Central Server Version: v7-16-00-dev10
- Platform: Browser
- Database type: SQLite

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4180

# 👩🏻‍💻 What does this PR do?
Allows `Requested`, `Supply`, `Issued` and `Remaining` to be displayed in 2 decimal places with ellipsis if there are more than 2 dp to indicate to users that there is a tooltip
Screenshot 2024-07-09 at 8 45 50 AM

# 🧪 Testing

- [ ] Have two sites (one OMS and one OG)
- [ ] Create an Internal Order in OG to send to OMS
- [ ] Enter some decimal in requested (e.g. 1.224131)
- [ ] Sync
- [ ] Go to OMS -> Requisitions
- [ ] Requested amount in requisition should be in decimals

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx [hunk 1]
```diff
@@ -23,10 +26,19 @@ export const PackVariantQuantityCell =
 
     const quantity = getQuantity(rowData);
     const packQuantity = numberOfPacksFromQuantity(quantity);
+    const hasMoreThanTwoDp =
+      packQuantity.toString().split('.')[1]?.length ?? 0 > 2;
+    const roundedPackQuantity = NumUtils.round(packQuantity, 2);
```
Comment (andreievg) [inline client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx:31]: would useFormatNumber.dumber work here ?

Comment (roxy-dao) [reply client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx:31]: Shouldn't use in callback 👀

Comment (andreievg) [reply client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx:31]: Hmm, we use `usePackVaraint` hook here, would that be problematic ?

**Review by andreievg — CHANGES_REQUESTED** [review]
Pending [this change](https://github.com/msupply-foundation/open-msupply/compare/4180-Customer-Requistion-doesn%E2%80%99t-accepts-the-decimal-Values-that-came-form-mSupply-sites-via-Internal-Orders-and-remote-auth...4180-Customer-Requistion-doesn%E2%80%99t-accepts-the-decimal-Values-that-came-form-mSupply-sites-via-Internal-Orders-and-remote-auth(useFormatNumber))

Unless it's not safe, need a use case to specify why it wouldn't be safe

**Comment by roxy-dao** [comment]
> Pending [this change](https://github.com/msupply-foundation/open-msupply/compare/4180-Customer-Requistion-doesn%E2%80%99t-accepts-the-decimal-Values-that-came-form-mSupply-sites-via-Internal-Orders-and-remote-auth...4180-Customer-Requistion-doesn%E2%80%99t-accepts-the-decimal-Values-that-came-form-mSupply-sites-via-Internal-Orders-and-remote-auth(useFormatNumber))
> 
> Unless it's not safe, need a use case to specify why it wouldn't be safe

We still want to display the full value in tooltip tho?

**Comment by andreievg** [comment]
> We still want to display the full value in tooltip tho?

Yep, I was hoping we can remove the need to do any extra check and just [do this one](https://github.com/msupply-foundation/open-msupply/compare/4180-Customer-Requistion-doesn%E2%80%99t-accepts-the-decimal-Values-that-came-form-mSupply-sites-via-Internal-Orders-and-remote-auth...4180-Customer-Requistion-doesn%E2%80%99t-accepts-the-decimal-Values-that-came-form-mSupply-sites-via-Internal-Orders-and-remote-auth(Remove-hasMoreThenTwoDp-check))

**Comment by roxy-dao** [comment]
> > We still want to display the full value in tooltip tho?
> 
> Yep, I was hoping we can remove the need to do any extra check and just [do this one](https://github.com/msupply-foundation/open-msupply/compare/4180-Customer-Requistion-doesn%E2%80%99t-accepts-the-decimal-Values-that-came-form-mSupply-sites-via-Internal-Orders-and-remote-auth...4180-Customer-Requistion-doesn%E2%80%99t-accepts-the-decimal-Values-that-came-form-mSupply-sites-via-Internal-Orders-and-remote-auth(Remove-hasMoreThenTwoDp-check))

I like the ellipsis to indicate that there is more... but sure~

**Comment by mark-prins** [comment]
yeah - I like the ellipsis too, when using it, having the ellipsis made is much clearer

**Comment by andreievg** [comment]
@mark-prins should this be a general pattern for all decimals fields in UI ? Can we put it in a pattern document somewhere ?

@roxy-dao can you please make an issue to apply this to the all of the other areas that display and round decimals (should be it's own component at this stage)

**Review by andreievg — APPROVED** [review]
Thanks looks good !
