### PR TITLE
6292 cant backspace/change patient

### LINKED ISSUE #5155: Updated patient's information is not showing in a prescription
## What went wrong? 😲

Scenario: I am changing patient's personal information, like first name. 

The change is reflected under `Dispensary -> Prescriptions` (in the overall view), but not when clicking on an individual prescription issued to that patient. Video of the behaviour is attached ->>> [here](https://drive.google.com/drive/folders/1e4sJzD7AfvKBYgKTkWdxHg51QRq6h2Az)

Marking as `Normal` as technically there is a workaround of removing the patient and retyping their new information to re-add them to the prescription

## Expected behaviour 🤔

Information should be updated consistently across the platform

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Dispensary -> Prescriptions`
2. Create a prescription for a patient
3. Go to `Dispensary -> Patients`
4. Change the patient's first name for testing purposes
5. Go back to the prescriptions window -> you can see the change in the overall view but not when clicking on a specific prescription
6. Inconsistency! 

## Your environment 🌱

- Open mSupply Version: `V2.3.0-RC9-b`
- Legacy mSupply Central Server Version: `V7.17.10`

- Platform: Tablet (apk)

- Database type: SQLite3

### LINKED ISSUE #6292: Unable to backspace/remove/change the patient when issuing prescriptions
## What went wrong? 😲

Unable to backspace/remove/change the patient when issuing prescriptions

https://github.com/user-attachments/assets/691d3da5-f4fe-4aec-95a9-14f283c7d7bc

## Expected behaviour 🤔

Should be able to: 
1. Backspace
2. Highlight and remove
3. Change the patient

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Prescriptions 
2. Make sure you have at least two patients added to your store
3. Create a new prescription
4. In the top left corner, attempt to change the patient or backspace or highlight and remove
5. Not possible

## Your environment 🌱

- Open mSupply Version: V2.6.0-cooldown-build-test
- Legacy mSupply Central Server Version: V7.19.03

- Platform: Google Chrome (browser) and Galaxy Tab A8 (Android 14)

- Database type: PostgreSQL and SQLite3

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #6292

# 👩🏻‍💻 What does this PR do?

Brings back ability to backspace/change patient in prescription:
Screenshot 2025-01-29 at 1 04 03 PM

It broke in #6171, trying to resolve https://github.com/msupply-foundation/open-msupply/issues/5155- I have implemented a new way to resolve this with waiting for non-stale data before rendering the input. What do you think of this fix?

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Testing steps from #6171 still pass
- [ ] Can then backspace/change the patient within prescription

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ export const PatientSearchInput: FC<NameSearchInputProps> = ({
       isOptionEqualToValue={(option, value) => option.name === value.name}
       width={`${width}px`}
       popperMinWidth={width}
-      value={value && { ...value, label: value.name }}
+      defaultValue={value && { ...value, label: value.name }}
```
Comment (lache-melvin) [inline client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx:35]: default value can't change after initial render - this was causing the original bug of patient name not updating when you had stale patient data.

By doing the wait until fetched after mount, we get the up to date patient data, then render the input 🎉

**Review by CarlosNZ — APPROVED** [review]
Looks good, working well.

Just wondering -- why not just mirror the way the `StockItemSearchInput` works? Seems like a very similar case.

Also, one tiny thing if you wouldn't mind adding. Currently the `noOptionsText` prop of the PatientSearchInput is just an empty string -- would probably be more helpful to make it "No Patients found" or something similar. There's already a string defined in common.json you can re-use: `  "messages.no-matching-patients": "No matching patients! 😁",`

Thanks.

**Comment by lache-melvin** [comment]
Yeah I wondered about doing the same as `StockItemSearchInput` - was trying to avoid if possible as I figured if we could leave Autocomplete to handle its state internally, that's less renders, and surface area for more bugs for us. StockItemSearchInput seems to have more requirements in terms of being updated internally and externally. This one might need that at some point too 🤷‍♀️ 

Was just thinking about the empty message! Will update 🙏

**Comment by mark-prins** [comment]
Would you mind changing the no patients message please? It seems unnecessarily cheerful for the intended usage:

`"No matching patients! 😁"` > `"No matching patients"`

File: client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx [hunk 2]
```diff
@@ -16,26 +16,53 @@ export const PatientSearchInput: FC<NameSearchInputProps> = ({
 }) => {
   const PatientOptionRenderer = getPatientOptionRenderer();
   const { isLoading, patients, search } = useSearchPatient();
+  const t = useTranslation();
+
+  const [input, setInput] = useState('');
+
+  useEffect(() => {
+    if (value) setInput(value.name);
+  }, [value]);
```
Comment (CarlosNZ) [inline client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx:25]: Looking good -- there's just this one UI thing that I think we can quickly fix.

Seems like the patient options list is lingering with a stale value -- when you go into the input, the dropdown first shows the previous results (or no results) rather than properly reflecting the current selection:



This seems to fix it:
```ts
  useEffect(() => {
    if (value) {
      setInput(value.name);
      search(value.name);
    }
  }, [value]);
```

Bit clunky to run another search after a selection, but is there a better way?

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
Thanks for the update. See [this one comment](https://github.com/msupply-foundation/open-msupply/pull/6328/files/3bbe2f4c3d98d8b55ee4de05008f41192a517e1d..87e1edff1813058a69bba66a4052d14eb6a8a9b3#r1933224708), would be good to fix. :)

File: client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx (hunk 2 above)
Comment (lache-melvin) [reply client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx]: Done :) [0cd486b](https://github.com/msupply-foundation/open-msupply/pull/6328/commits/0cd486b511d9d4a7bd495dbf18527f46d85e2d8e)

Comment (lache-melvin) [reply client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx]: Realised the onFocus call wasn't needed with this change 🙏  [59e7782](https://github.com/msupply-foundation/open-msupply/pull/6328/commits/59e77821dd21212090b13a3f77b3ed57eea36d35)

**Review by CarlosNZ — APPROVED** [review]
Brilliant, thanks. Working nicely 👍
