### PR TITLE
6312 Align placeholder row packSize column

### LINKED ISSUE #6312: Placeholder line always showing 1
## What went wrong? 😲

not sure if this is intentional, but the placeholder line in outbound shipments is always showing 1

for example, i was testing a brand new item that had no previous stock movement or allocation, with the exception of 1 repack. when adding that item to an outbound shipment, i noticed placeholder said 1 - even though it is not added elsewhere

Image

Image

i then went ahead and added that same item to two different outbound shipments, allocated them and picked them -> they showed up in the item's ledger. however, when i went to create a third outbound shipment with the same item, placeholder still said 1? shouldn't it be 2 if the item is picked in 2 different outbound shipments?

Image

Image

## Expected behaviour 🤔

i think the number should be reflective of how many other places the item is being used in? and if none, it should be zero?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have an item that you haven't tested with - if it's easier, create a new one :)
2. Go to Inventory -> View Stock and add some stock to it, for example 500 units at pack size 1
3. I then repacked my item, so take 100 units and repack them into 50 packs at pack size 2
4. Go to Distribution -> Outbound Shipments and create a new shipment. Add your item to it
5. When adding, note placeholder lines say '1' even though your item is not used elsewhere
6. Now create 2 other outbound shipments and add the same item to them
7. Confirm Allocated -> Picked, note the outbound shipments now show up in the item's ledger
8. Open your third outbound shipment and try and add your item - note the placeholder still says 1 even though you have 2 other shipments
9. Unclear!

## Your environment 🌱

- Open mSupply Version: V2.6.0-cooldown-build-test
- Legacy mSupply Central Server Version: V7.19.03

- Platform: Google Chrome (browser for Mac)

- Database type: PostgreSQL

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #6312 

# 👩🏻‍💻 What does this PR do?
Move column to the right by one so that it aligns with packSize column of the table

Screenshot 2025-04-02 at 12 26 39

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to Distribution -> Outbound Shipments and create a new shipment. Add an item to it
- [ ] When adding, note placeholder lines say '1' for pack size 
- [ ] Observe that it is now aligned correctly

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx [hunk 1]
```diff
@@ -56,8 +56,13 @@ const PlaceholderRow = ({ line }: { line?: DraftStockOutLine }) => {
...
       </PlaceholderCell>
-      <PlaceholderCell style={{ textAlign: 'right' }}>1</PlaceholderCell>
-      <PlaceholderCell colSpan={4}></PlaceholderCell>
+      <PlaceholderCell
+        style={{ textAlign: 'right', paddingRight: '14px' }}
+        colSpan={2}
+      >
+        1
+      </PlaceholderCell>
+      <PlaceholderCell colSpan={3}></PlaceholderCell>
```
Comment (noel-yeldos) [inline client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx:65]: While this has fixed it, I'm thinking that this set up for the placeholder cells is fragile. Surely we don't want to have to come in and make changes each time a column gets added or removed from the data table above the placeholder row?

Comment (aimee-mcneil-melville) [reply client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx:65]: Thanks, Noel! I agree - it is fragile! 

From what I see with this setup is the column spans create the placement - and when an extra column was added in the outbound rows the placeholder row was misaligned as a result - each count of the colSpans will push that cell one column to the right.

I'll add a suggestion below, it looks to me that the value showing for both the placeholder row and total row under the `Qty issued` column, are actually representative of `Pack qty issued` and are also misaligned - very hard to tell on UI as the 1 could represent either!

A comment on the outbound shipment 'columns' file would probably be helpful, as when making changes to the columns it would be quite easy to miss that the Placeholder/Total rows also need adjusting

Comment (aimee-mcneil-melville) [reply client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx:65]:
```suggestion
      <PlaceholderCell colSpan={4} sx={{ color: 'secondary.main' }}>
        {t('label.placeholder')}
      </PlaceholderCell>
      <PlaceholderCell style={{ textAlign: 'right' }} colSpan={1}>
        1
      </PlaceholderCell>
      <PlaceholderCell colSpan={2}></PlaceholderCell>
```

**Review by aimee-mcneil-melville — CHANGES_REQUESTED** [review]
Thanks Noel, your solution lines it up nicely! 

If you could adjust the right-hand value in Placeholder and Total  to line up with `Pack qty issued` column as well please as they are also misaligned :)

**Comment by noel-yeldos** [comment]
@aimee-mcneil-melville thanks for the review! :)

From what I'm seeing it appears that the total and placeholder qty cells are where they need to be? I'm basing that off the numbers when looking at the rows in the data table.
e.g 355 + 2145 = 2500 whereas 71 + 2145 = 2216 which doesn't add up

Screenshot 2025-04-03 at 11 47 06
Screenshot 2025-04-03 at 11 45 11

**Comment by aimee-mcneil-melville** [comment]
Thanks for checking into that, I had thought the quantity issued column was representing number of packs - that column is all good then! :)

I do have a concern with the padding fix for the longer term however, in that every time a column is changed (an extra column or a width change) the pack size column could easily become misaligned again. Setting the column span so that the cell falls into the correct column I believe is a cleaner and more robust fix for the placeholder pack size as it will move with the table headers.

Can you update it to reflect that please? Let me know if you've got any questions or concerns!

**Comment by noel-yeldos** [comment]
> Thanks for checking into that, I had thought the quantity issued column was representing number of packs - that column is all good then! :)
> 
> I do have a concern with the padding fix for the longer term however, in that every time a column is changed (an extra column or a width change) the pack size column could easily become misaligned again. Setting the column span so that the cell falls into the correct column I believe is a cleaner and more robust fix for the placeholder pack size as it will move with the table headers.
> 
> Can you update it to reflect that please? Let me know if you've got any questions or concerns!

@aimee-mcneil-melville yup your concern about adding fixed padding to the cell is valid! 

However, the Placeholder cells already all have fixed padding.
Screenshot 2025-04-03 at 17 11 56

Without the additional padding this is what the alignment is like
Screenshot 2025-04-03 at 17 12 13

And with the padding override to the specific cell
Screenshot 2025-04-03 at 17 14 02

Did you still want me to remove the additional padding?

**Review by aimee-mcneil-melville — APPROVED** [review]
Ah, sorry I do I see what you mean! 

I had misread some of it thinking the padding was moving it a column over 😅  Your fix is good and it does line up better with the padding there!

All good to merge in :)
