### PR TITLE
Parse dates in date filter

### LINKED ISSUE #2712: Cold chain: Touching screen causes date filters to reset
## What went wrong? 😲

Touching the screen removes any date filters - meaning you can't touch breach icons to show more details. 

https://github.com/msupply-foundation/open-msupply/assets/19318937/cb662294-cf26-40a4-bf36-6af3eb28e341

## Expected behaviour 🤔

Date filters shouldn't change unless user changes them deliberately. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Select a date filter
2. Touch anywhere on graph

## Your environment 🌱

 - Version: V1.6.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #2712 #2713

# 👩🏻‍💻 What does this PR do? 
 
The DateTimePickerInput was failing to parse the date - the default format of `P p` is used to both format a date object to a string and to parse the date string.

However, the parse was failing silently with the result that the input was setting the date value to `null` on a blur event, resetting the input value.

The fix, for me at least, is to provide a locale to the `parse` call.
An alternative is to set the date format at `dd/MM/yyyy HH:mm` as this works for parsing as well. However, I thought it best to use the local regional format if possible. I've tried setting my OS regional settings to something different, however this has no effect.

# 🧪 How has/should this change been tested? 

As per the issues, focus on a date input and then click elsewhere, triggering a blur event.
If the input is populated with a date, you should see no effect i.e. the current date value remains.

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx [hunk 1]
```diff
@@ -126,7 +130,7 @@ export const DateTimePickerInput: FC<
       minDate={minDate}
       maxDate={maxDate}
       {...props}
-      value={DateUtils.getDateOrNull(props.value)}
+      value={DateUtils.getDateOrNull(props.value, undefined, dateParseOptions)}
```
Comment (CarlosNZ) [inline client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx:133]: Strictly speaking, you probably don't need this one, as the `value` should always be a Date object (not a string) -- it gets converted on input (onBlur), or is already a Date if using the Picker.

File: client/packages/common/src/intl/utils/DateUtils.ts [hunk 2]
```diff
@@ -83,13 +83,14 @@ export const DateUtils = {
   addCurrentTime,
   getDateOrNull: (
     date?: Date | string | null,
-    format?: string
+    format?: string,
+    options?: Parameters<typeof parse>[3]
```
Comment (CarlosNZ) [inline client/packages/common/src/intl/utils/DateUtils.ts:87]: Might be overkill, but I wonder if we should tighten the type definitions here to ensure that if a string date is provided, then `format` and `options` (with `locale`) must also be provided (but optional if date is `Date`).

Might make the input type ridiculously complicated though, so only if you think its worth it.

**Review by CarlosNZ — APPROVED** [review]
Looks good thanks. I think this is the correct way to handle it. The `onBlur` event is intended for a string input, in which case a format and locale should be required to interpret it correctly.

File: client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx:133]: yes, good point. I'll just remove the `getDateOrNull` then and see if that causes any problems..

File: client/packages/common/src/intl/utils/DateUtils.ts (hunk 2 above)
Comment (mark-prins) [reply client/packages/common/src/intl/utils/DateUtils.ts:87]: the `options` is only required if you have a format which uses locale specific items (such as `P` or `p` in this case) so I wouldn't want to make that required.
I like the idea, so had a look - and can make the type of `format` depend on the `date` type, something like:

```
  getDateOrNull: <T extends Date | string | null | undefined>(
    date: T,
    format: T extends string ? string : string | undefined,
    options?: Parameters<typeof parse>[3]
  ): Date | null => {
```

but.. couldn't see how to have format as optional, only how to have the type change i.e. `string | undefined`. the format paramater still has to be specified, and that results in lots of code changes to add in `getDateOrNull(date, undefined)` which isn't great.
