### PR TITLE
7228 cant access encounter if clinician not visible

### LINKED ISSUE #7228: Can't access an encounter created in another store if the Clinician doesn't exist
## What went wrong? 😲

Found whilst testing #7100 

When a clinician is recorded on a vaccination card in store A, and store B (who doesn't have the clinician visible) attempts to access the vaccination card, there is an error and the user is prevented from accessing the encounter

Error UI: 
Image

GraphQL error preventing the encounter from loading
Image

## Expected behaviour 🤔

To be able to view the encounter record, regardless of whether the linked clinician is visible for my site.

@mark-prins can you please weigh in on how this should behave? If the clinician is not visible on the second store, should we just show a blank clinician field? Or do we want the clinicians to sync to and show on other stores?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

- [ ] Have some clinicians on site A but not site B
- [ ]  On site A - enrol a patient in a vaccination program
- [ ]  Create an encounter and give a few vaccinations, include a clinician
- [ ]  Go to site B, fetch this new patient
- [ ]  View the patients vaccination encounters - you can see the list view
- [ ] Click on the encounter - see the error 'encounter not found' and unalbe to access the encounter details/vaccination card

## Your environment 🌱

- Open mSupply Version: 2.7
- Legacy mSupply Central Server Version:

- Platform:

- Database type: SQLite

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #7228

# 👩🏻‍💻 What does this PR do?

Store A (Site Y) created an encounter which has an associated clinician. 

Store B (Site Z) tries to pull the encounter, as it also has visibility of the patient.

Fixes 2 cases:

- No stores on Site Z have visibility of the linked clinician. The om_document failed sync translation, and no encounter was visible in store B
- A different store on Site Z has visibility of the linked clinician, but not Store B. The translation passes, you can see the encounter in the list view, but when you click it to go to the detail view, got not found error (as clinician not exist for store).

## 💌 Any notes for the reviewer?

I tried to to add store_id to encounter create_filtered_query, and only left_join onto clinicians table where clinicians visible via clinician store join. But it was a diesel type error rabbit hole, felt I was already wasting too much time. 

So just swallowing the error at graphql layer, hopefully ok for now?

Also per issue... should I open a secondary issue to handle "display clinician name even if not actually a visible/active clinician for this store"?

# 🧪 Testing

- [ ] Have a patient enrolled in a program, visible on two stores on different sites
- [ ] For site 1/store 1, ensure there is a clinician (OG prescriber) that is not visible on any of the stores on the other site
- [ ] Create an encounter for the patient from store 1, with the clinician
- [ ] Sync to store 2
- [ ] You can see the encounter
- [ ] Now make the clinician visible on a different store on site 2 (not the store currently looking at the patient record)
- [ ] Sync again
- [ ] You can open the encounter detail view, no error

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/repository/src/migrations/v2_07_00/remove_encounter_clinician_constraint.rs [hunk 1]
```diff
@@ -0,0 +1,81 @@
+use crate::migrations::*;
```
Comment (andreievg) [inline server/repository/src/migrations/v2_07_00/remove_encounter_clinician_constraint.rs:1]: ⛓️‍💥 freedom ⛓️‍💥

**Review by andreievg — APPROVED** [review]
Looks good thanks, didn't check, i assume that it's ok to return none/null for clinician in loader

**Comment by lache-melvin** [comment]
> i assume that it's ok (from f/e perspective) to return none/null for clinician in loader

Yup this is common behaviour when we don't set clinician id, which is most of the time...
