### PR TITLE
10202 table error display

### LINKED ISSUE #10202: Table error state
## What went wrong? 😲

I have an error in the server and the new table gave me the following result:

Image

which is a modification of the 'Nothing here' component

Image

I have some concerns with this implemenation:

* The 'new shoot' icon is being used to display an error - the intention of the icon was to show that there are no results and that this is an opportunity for the user to add / create items. Using it as an error icon changes the intention of the icon - it would be better to have an error icon
* The text without the title row looks strange
* There is no way to display additional details about the error which is the pattern that we've been introducing with the `BoxedErrorWithDetails` and `ErrorWithDetails` components
* The change has resulted in conditional logic in the `NothingHere` component which is not necessary - I think better to use an error component 

## Expected behaviour 🤔
Can we evaluate the use of the standard `NothingHere` component as an error display state please.
Here are some suggestions using existing components:

Image

Image

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #10202 

# 👩🏻‍💻 What does this PR do?

Add a component to display an error message & icon, and implement it as the error fallback on tables

Consistent style with the `Nothing Here` component, but with relevant symbol and colours. I looked at using the existing ErrorWithDetails components and they seemed a bit empty in the space + extra styling needed around them anyway to center nicely

Screenshot 2026-01-30 at 3 28 05 PM

## 💌 Any notes for the reviewer?

The issue mentions being able to display details of the error, I do think this is a good idea (detail is in the toast but it disappears quickly). Happy to add a tooltip or extra text in this PR or a follow up if we want this functionality in. 
To get the query error into the message will take a bit of extra work as it's currently handled at the Site level in [QueryErrorHandler.tsx](https://github.com/msupply-foundation/open-msupply/blob/e3b7b9286d01c9c275317da8988a6ca5a8c1e937/client/packages/host/src/QueryErrorHandler.tsx)

# 🧪 Testing

- [ ] Go to a list view page with a table
- [ ] Change the url - specifically misconfiguring the sort parameter or add a select filter and change that parameter
- [ ] eg /localhost:3003/inventory/stocktakes?status=FINALISD has the 'E' in FINALISED removed -> crashes
- [ ] See error component

The error page is used on many list views, and some detail views, though I couldn't trigger it on many of them. If the page refreshes, try a changing a different parameter, some crash it and some don't

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/components/errors/DataError.tsx [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+      padding={1}
+      sx={{ color: theme.palette.background.error }}
+    >
+      <AlertIcon sx={{ fontSize: 120 }} />
+      <Box justifyContent="center"></Box>
+      <Typography fontSize={18} fontWeight={700} sx={{ color: 'error.main' }}>
+        {heading}
+      </Typography>
+      <Typography fontSize={14} sx={{ color: 'error.main' }} display="inline">
+        {error ? error : t('error.unable-to-load-data')}
```
Comment (aneeshthunga26) [inline client/packages/common/src/ui/components/errors/DataError.tsx]: nit: This can be simplified to `error ?? t('error.unable-to-load-data')`
