### PR TITLE
Use local keystore sync url not the requests

### LINKED ISSUE #7772: Sync v6 auth using wrong url
## What went wrong? 😲

https://github.com/msupply-foundation/open-msupply-internal/issues/79

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #7772

# 👩🏻‍💻 What does this PR do?

Munge the sync_settings data with the url from the keystore in the central server DB. Without doing anything clever this is the way to do it I think.

Should stop incorrect auth server occurring

## 💌 Any notes for the reviewer?

- I am pretty sure I found everywhere... perhaps there should be some middleware or something that does this.
- This adds an extra DB call on most endpoints. Probably negligible considering we're making an HTTP request to anther server to authenticate. One day we'll have the site table in OMS and not have to make that HTTP call. So performance I'm not that bother making this better.
- There should probably be tests? Integration tests?
- I touched a patient name store join API not 100% sure how to test off the top of my head. I have not tested that API.

# 🧪 Testing

1. Have 2 copies of OG central running (A and B) with webservers on different ports. They should be copies of the same datafile with same sync sites. Both should have same OMS central site configured with same URL.
2. OMS Central syncing with OGC A
3. Initialise your remote site with OGC B - it should fail on v6 requests

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/sync/sync_on_central/mod.rs [hunk 1]
```diff
@@ -62,12 +62,10 @@ pub async fn pull(
...
 
-    // Check credentials again mSupply central server
-    let response = SyncApiV5::new(sync_v5_settings)
-        .map_err(|e| Error::OtherServerError(format_error(&e)))?
-        .get_site_info()
+    let ctx = service_provider.basic_context()?;
+    let response = validate_site_auth(&ctx, &sync_v5_settings)
         .await
-        .map_err(Error::from)?;
+        .map_err(|e| Error::OtherServerError(format_error(&e)))?;
```
Comment (Chris-Petty) [inline server/service/src/sync/sync_on_central/mod.rs:68]: Maybe this func should also return `Result<SyncBatchV6, CentralApiError>` rather than `Result<SyncBatchV6, SyncParsedErrorV6>`. Then it'd match `add_patient_name_store_join` returning `Result<_, CentralApiError>`, or vice versa. `validate_site_auth` can only do one or the other?

File: server/service/src/sync/api/core.rs [hunk 2]
```diff
@@ -238,6 +242,30 @@ async fn response_or_err(
     Err(SyncApiErrorVariantV5::from_response_and_status(response.status(), response).await)
 }
 
+// OMS Central does not yet do auth validation for site credentials
+// So we call Legacy central server for this
+// (Use sync API for simplest auth)
+pub async fn validate_site_auth(
```
Comment (Chris-Petty) [inline server/service/src/sync/api/core.rs:248]: This little refactor as one commit probably makes these changes hard to cherry pick into old releases' patches. Oh well...

File: server/service/src/sync/api/core.rs [hunk 3]
```diff
@@ -238,6 +242,30 @@ async fn response_or_err(
...
+    ctx: &ServiceContext,
+    sync_v5_settings: &SyncApiSettings,
+) -> Result<SiteInfoV5, CentralApiError> {
+    // We need to ignore the OG server URL provided by the remote and ensure we use the one that the OMS central server is expecting
+    let kv_repo = KeyValueStoreRepository::new(&ctx.connection);
+    let kv_url = kv_repo.get_string(KeyType::SettingsSyncUrl)?.unwrap();
```
Comment (Chris-Petty) [inline server/service/src/sync/api/core.rs:254]: This unwrap is probably illegal yes?

File: server/service/src/sync/api/core.rs [hunk 4]
```diff
@@ -238,6 +242,30 @@ async fn response_or_err(
...
+    let sync_v5_settings = sync_v5_settings.clone();
```
Comment (Chris-Petty) [inline server/service/src/sync/api/core.rs:255]: A cool kid probably doesn't even do this clone()

File: server/service/src/sync/api/core.rs (hunk 3 above)
Comment (jmbrunskill) [reply server/service/src/sync/api/core.rs:254]: I think so but I prefer to leave a comment with justification when using an unwrap...

**Review by jmbrunskill — COMMENTED** [review]
Looks good to me Chris, but haven't actually tested it out, will leave other reviews to do that.

File: server/service/src/sync/api/core.rs (hunk 3 above)
Comment (Chris-Petty) [reply server/service/src/sync/api/core.rs]: With renewed energy I have just handled it properly by returning an error. No panics!

File: server/service/src/sync/sync_on_central/mod.rs (hunk 1 above)
Comment (andreievg) [reply server/service/src/sync/sync_on_central/mod.rs:68]: Great point, can't wait till v7 where we don't need to stack errors like this : ), a bit hard to know why it was done as CentralApiError now ¯\_(ツ)_/¯

File: server/service/src/sync/api/core.rs (hunk 2 above)
Comment (andreievg) [reply server/service/src/sync/api/core.rs:248]: That's ok, i like the refactor, plus this will be the only version it goes to, I've rebased to 2.7.3 (as that's the next release, coming hot)

**Review by andreievg — APPROVED** [review]
Very good, thank you !

I tested by:

* Initialising central 
* Change port of OG 
* Try initialise remote (didn't work, connection errors, but worked in main 👍 )
