### PR TITLE
Query with user customer store name id

### LINKED ISSUE #5995: Front end incorrectly querying indicators with other_party_id rather than customer_name_id
## What went wrong? 😲

[this pr](https://github.com/msupply-foundation/open-msupply/pull/5958) added saving indicator value customer_name_id correctly, but corresponding changes in front end were not implemented.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Attempt to view regimen data in request requisition
2. Data is no longer visible

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #5995 

# 👩🏻‍💻 What does this PR do?

Fixes request requisition queries for indicator values

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to an request requisition with regimen data
- [ ] See that indicator values are now visible.

# 📃 Documentation

- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -26,15 +27,18 @@ export const DetailView: FC = () => {
...
   const { data: programIndicators, isLoading: isProgramIndicatorsLoading } =
     useRequest.document.indicators(
-      data?.otherPartyId ?? '',
+      store?.nameId ?? '',
       data?.period?.id ?? '',
       data?.program?.id ?? '',
       !!data
     );
 
+  console.log('other party id', data?.otherPartyId);
```
Comment (andreievg) [inline client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx:40]: stray log

**Review by andreievg — APPROVED** [review]
Look good, but please remove the stray console log

**Review by mark-prins — APPROVED** [review]
👍 LGTM
