### PR TITLE
Display current item in OS and Stocktake when you have many items in the system

### LINKED ISSUE #2614: **URGENT** No item name appearing on tablet when selecting on an item from a list
## What went wrong? 😲
Item name does not appear when you create a stocktake and the list generates, and then you select on the item. See video:

https://github.com/msupply-foundation/open-msupply/assets/143057869/796ca04d-4025-44c6-bf55-35577b0cde51

Also happens with other methods of opening items such as opening an outbound shipment and then selecting on the order, and clicking on the item in the order - this is empty.

 
See vid

## Expected behaviour 🤔
Item name should appear after you select on the item in the lists

## How to Reproduce 🔨
See vid

Steps to reproduce the behaviour:
1. Create stocktake
2. Open up a masterlist of your stocktake 
3. Select on the item

This is also similar for outbound shipment - select the item that is already in an outbound shipment order, the name will not appear.

## Your environment 🌱
v1.5 on android tablet samsung

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #2614

# 👩🏻‍💻 What does this PR do? 
 
The current item i.e. the selected value in the autocomplete, is picked from the list of available items which is fetched with the `useItemStockOnHand` hook. If you have more than 500 items available, and the current item is further than position 500 when the list is sorted by name, then that item won't be in the first set of paginated results.

This means that the item won't be shown in the disabled autocomplete component.

The fix here is to also fetch the current item by id, and add that to the list of items. This list is already unique by id, so we won't be adding a duplicate. When editing a stocktake or OS line, the selected items aren't changeable, so the input will be disabled when showing the current item. This means that the position in the list is also not important.

# 🧪 How has/should this change been tested? 

You can edit `packages/system/src/Item/Components/StockItemSearchInput/hooks.ts` and change the page size to something smaller than your available items, or you can use a large dataset, such as that linked to in the issue.

Then, create an OS or stocktake with an item that starts with a letter low down in the alphabet (V? Z?)
Refresh the page, open the edit modal again. You will see the item name.

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts [hunk 1]
```diff
@@ -141,9 +141,9 @@ export const useUrlQueryParams = ({
         : 0,
     first: rowsPerPage,
     sortBy: {
-      key: urlQuery['sort'] ?? '',
-      direction: urlQuery['dir'] ?? 'asc',
-      isDesc: urlQuery['dir'] === 'desc',
+      key: urlQuery['sort'] ?? initialSort?.key ?? '',
```
Comment (mark-prins) [inline client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts:144]: offroad: this bug is adding errors to console. user shouldn't notice, so I didn't create a new issue.
the problem is that when you click a menu item (in this case 'stocktake') the sort key is empty and an error raised - even though the 'initialSort' has been provided.

To check - try develop branch, or undo this change. Click on stocktake in the left hand menu and check console for errors. You'll also see the network request fail with an error.

File: client/packages/common/src/types/schema.ts [hunk 2]
```diff
@@ -3160,6 +3160,7 @@ export type NameNode = {
   comment?: Maybe<Scalars['String']['output']>;
   country?: Maybe<Scalars['String']['output']>;
   createdDatetime?: Maybe<Scalars['DateTime']['output']>;
+  customData?: Maybe<Scalars['JSON']['output']>;
```
Comment (mark-prins) [inline client/packages/common/src/types/schema.ts:3163]: offroad: I've re-generated, and the generate wasn't called after the custom data was added to names

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx [hunk 3]
```diff
@@ -10,13 +10,14 @@ import {
...
   ItemRowFragment,
+  ItemStockOnHandFragment,
 } from '@openmsupply-client/system';
 import { useStocktake } from '../../../api';
 
 interface StocktakeLineEditProps {
   item: ItemRowFragment | null;
   mode: ModalMode | null;
-  onChangeItem: (item: ItemRowFragment | null) => void;
+  onChangeItem: (item: ItemStockOnHandFragment | null) => void;
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx:20]: I've changed to use a shared type - the different item api calls returned different objects. Am now using a fragment that represents the common intersection of properties

File: client/packages/system/src/Item/Components/ItemOptionRenderer/ItemOptionRenderer.tsx [hunk 4]
```diff
@@ -1,33 +1,31 @@
...
-            width: 200,
-            textAlign: 'right',
-          }}
-        >{`${formatNumber(item.availableStockOnHand)} ${label}`}</span>
-      </ItemOption>
-    </Tooltip>
-  );
+  (props: React.HTMLAttributes<HTMLLIElement>, item: ItemStockOnHandFragment) =>
+    (
+      <Tooltip title={`${item.code} ${item.name}`}>
```
Comment (mark-prins) [inline client/packages/system/src/Item/Components/ItemOptionRenderer/ItemOptionRenderer.tsx:10]: this is mostly whitespace due to the shorter props line

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 5]
```diff
@@ -47,10 +56,15 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
     [items]
   );
 
-  const cachedSearchedItems = useMemo(
-    () => ArrayUtils.uniqBy([...items, ...(data?.nodes ?? [])], 'id'),
-    [data]
-  );
+  const cachedSearchedItems = useMemo(() => {
```
Comment (mark-prins) [inline client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx:59]: this is the fix - add the current item to the list, and fetch value from the cached items list.

File: client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts (hunk 1 above)
Comment (andreievg) [reply client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts:144]: Ohh yeah i remember seeing this error, was going to make an issue, thanks for fixing !

**Review by andreievg — APPROVED** [review]
Thanks Mark, looks good, a couple of things to maybe think about for future.
* If there are more then paginated number of items, user won't be able to search for one (when adding new stocktake line or OS line)
* Maybe it's simpler to display different element rather then make autocomplete work for both searchable and when item selection is disable

**Comment by mark-prins** [comment]
cool - thanks for review @andreievg 

you can search for items - there's an infinite query on the stock item select autocomplete: if you scroll to the bottom it loads more items (using the current filter)

Now that I look at it, I'd like to refactor - there's a `useInfiniteQuery` hook which handles all of that. I implemented that to load up all items as a first attempt at this fix, and it's pretty easy to use.

Good point about the autocomplete doing double duty - could just replace it with text. The main reason for keeping it in, was that it looks the same (there's the drop down icon and padding). That's not a good enough reason though!
