### PR TITLE
7195 add correct id in build route

### LINKED ISSUE #7195: Merge issue from changing number to id
## What went wrong? 😲

Merge issue resulting from:

https://github.com/msupply-foundation/open-msupply/pull/6899

Selecting an item from within an internal order causes nothing to be found (probably a lingering find_by_number).
Also breadcrumbs setting to be number rather than ID header is failing.

Image

Further (and probably related) failures when adding an item to an internal order:

Image

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to internal orders
2. Click on an order
3. 2. Click on anitem
4. See bug

- Open mSupply Version: develop (2.7)
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #7195 

# 👩🏻‍💻 What does this PR do?

Fixes adding of wrong id to nested route

Also adds mapping of asset number to breadcrumbs (which previously wasn't required when we accessed via number rather than ID).

I've made this fix also to response requisitions, which while not part of this issue, had the same missing breadcrumb.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Navigate to internal orders, select an item
- [ ] See that it doesn't fail AND breadcrumbs are shown correctly as the requisition (internal order) number (not messy id)
- [ ] Navigate to distribution -> requisitions
- [ ] Select a requisition
- [ ] Select an item
- [ ] See that breadcrumbs are shown correctly as the requisition number

# 📃 Documentation

- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -29,6 +30,7 @@ export const DetailView: FC = () => {
   const { setCustomBreadcrumbs } = useBreadcrumbs();
   const navigate = useNavigate();
   const { data, isLoading } = useRequest.document.get();
+  const { requisitionId = '' } = useParams();
```
Comment (fergie-nz) [inline client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx:33]: I thought better to get this from url params instead of waiting for data to return

**Review by GeronimoJohn — COMMENTED** [review]
Almost there! Just found a few things testing it.

Navigate Internal Orders -> Select an order -> Select Item -> Page shows Nothing here component. I think meant to show the item

Clicking on breadcrumb returns error -> 'Internal Order Not found'

Navigate Internal Orders -> Select an order -> Click add item button -> Choose item in dropdown -> Returns input error

https://github.com/user-attachments/assets/989225d6-3377-479d-bbb4-3b91a6ef3921

**Comment by fergie-nz** [comment]
> Almost there! Just found a few things testing it.
> 
> Navigate Internal Orders -> Select an order -> Select Item -> Page shows Nothing here component. I think meant to show the item
> 
> Clicking on breadcrumb returns error -> 'Internal Order Not found'
> 
> Navigate Internal Orders -> Select an order -> Click add item button -> Choose item in dropdown -> Returns input error
> 
>  Screen.Recording.2025-04-07.at.11.04.35.AM.mov

Hey @GeronimoJohn would you be willing to retest this?

I can't replicate (I think this was what was fixed in the merge) and wonder if the issue was occurring on a different branch?

**Review by GeronimoJohn — APPROVED** [review]
LGTM! Works well
