### PR TITLE
8354 add use campaigns preference

### LINKED ISSUE #8354: Campaigns showing up in remote sites when they haven't been configured
## What went wrong? 😲
Screenshot below from a remote site. 
Image

## Expected behaviour 🤔
Campaigns shouldn't be showing at all if they aren't configured. Either hide it behind a pref, so add in a check to hide the column if it isn't available

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2.8
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #8354

# 👩🏻‍💻 What does this PR do?

Adds campaign global pref

Hides campaigns where global pref is turned off

## 💌 Any notes for the reviewer?

Note - campaign management still visible on central server.

I thought this would be helpful for admin staff to set up a campaign to their desired settings before enabling and releasing to remote sites.

I'm just thinking now that 'useCampaigns' is similar wording to standard hook wording. Is that okay? Or 'showCampaigns' better to more easily differentiate

# 🧪 Testing

- [ ] Turn on useCampaign global pref
- [ ] See app unchanged
- [ ] Turn off useCampaign global pref
- [ ] See that preferences are no longer visible in inbound shipment line view, outbound shipment line view, or stock line edit

# 📃 Documentation

Unsure - does this need to be documented in OMS docs?

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Review by jmbrunskill — APPROVED** [review]
Looks good. I was confused why I couldn't see the pref on the remote site but then realised on store prefs are visible on remote sites.
@mark-prins should we add an issue for making global prefs visible on remote sites?
I think that would be very useful when debugging & setting up new sites...
Although right now even the current view for store prefs is hidden behind a permission I think?

File: server/graphql/types/src/types/preferences.rs [hunk 1]
```diff
@@ -105,15 +110,14 @@ pub enum PreferenceKey {
...
-            // Global preferences
             PrefKey::AllowTrackingOfStockByDonor => PreferenceKey::AllowTrackingOfStockByDonor,
             PrefKey::ShowContactTracing => PreferenceKey::ShowContactTracing,
             PrefKey::GenderOptions => PreferenceKey::GenderOptions,
-            // Store preferences
             PrefKey::ManageVaccinesInDoses => PreferenceKey::ManageVaccinesInDoses,
             PrefKey::ManageVvmStatusForStock => PreferenceKey::ManageVvmStatusForStock,
             PrefKey::SortByVvmStatusThenExpiry => PreferenceKey::SortByVvmStatusThenExpiry,
             PrefKey::UseSimplifiedMobileUi => PreferenceKey::UseSimplifiedMobileUi,
+            PrefKey::UseCampaigns => PreferenceKey::UseCampaigns,
```
Comment (roxy-dao) [inline server/graphql/types/src/types/preferences.rs:120]: pls move up so all the prefs are grouped...
