### PR TITLE
#11191 Sync PO line link via oms_fields

### LINKED ISSUE #11191: PO linked inbound shipment line's PO line link isn't synced
## What went wrong? 😲

Image

After reinitialising invoice lines in a PO linked inbound shipment lose their purchase order link. This breaks a decent bit of the PO linked inbound shipment functionality like the grouping, delivery status and shipped number of items. This is in 2.17 release.

Image

## Expected behaviour 🤔

PO line link is kept through sync and reinitialisation.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

- [ ] Make an external inbound shipment linked to a PO
- [ ] Add some lines from the PO
- [ ] Sync
- [ ] Reinitialise

## Your environment 🌱

- Open mSupply Version: 2.17
- Platform: MacOS Chrome
- Database type: Both

### PR DESCRIPTION
**Pull request by ria8651**
Fixes #11191

# 👩🏻‍💻 What does this PR do?

Adds `purchase_order_line_id` to `TransLineRowOmsFields` so the purchase order line link is preserved through sync for invoice lines.

Previously, `purchase_order_line_id` was hardcoded to `None` on pull and ignored (via `_`) on push. This meant that after syncing and reinitialising a PO-linked inbound shipment, the lines would lose their PO link — breaking grouping, delivery status, and shipped number of items.

The fix stores `purchase_order_line_id` in the `oms_fields` JSON blob on the `trans_line` record, following the same pattern used for `campaign_id`, `program_id`, `status`, and `manufacture_date`.

## 💌 Any notes for the reviewer?

- The legacy `goods_received_lines_ID` mSupply field was considered as an alternative to `oms_fields`, since it has a similar intent. However, the open mSupply `purchase_order_line_id` would be invalid/meaningless in mSupply's context (different ID scheme), so `oms_fields` is the correct place for this.
- Only one file changed — the sync translation for invoice lines.

# 🧪 Testing

- [ ] Set up a central sync server with at least one OMS remote site
- [ ] Create an external inbound shipment linked to a PO on the remote site
- [ ] Add lines from the PO
- [ ] Sync to central
- [ ] Reinitialise on the remote site
- [ ] Verify the PO line link is preserved (grouping, delivery status, shipped number of items should all work correctly)

# 📃 Documentation

- [x] **No documentation required**: bug fix, no change in user-facing behaviour

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Comment by jmbrunskill** [comment]
@ria8651 looks like the tests are failing can you check please?

**Review by jmbrunskill — CHANGES_REQUESTED** [review]
Please update the test cases as well.

File: server/service/src/sync/translations/invoice_line.rs [hunk 1]
```diff
@@ -51,6 +51,9 @@ pub struct TransLineRowOmsFields {
     pub status: Option<String>,
     #[serde(default)]
     pub manufacture_date: Option<NaiveDate>,
+    #[serde(default)]
+    #[serde(deserialize_with = "empty_str_as_option_string")]
```
Comment (jmbrunskill) [inline server/service/src/sync/translations/invoice_line.rs]: Don't need `empty_str_as_option_string` for oms fields `null` comes through correctly so default serde is fine.

Comment (ria8651) [reply server/service/src/sync/translations/invoice_line.rs]: @copilot no need for PR just fix it here

**Review by jmbrunskill — CHANGES_REQUESTED** [review]
Can I have a test case where the purchase_order_line_id is set for sync please? Looks like we still have the no sync tests with purchase_order_line_id set right? Do you want me to do an example branch of what I mean?

**Review by ria8651 — COMMENTED** [review]
LGTM assuming tests pass

**Review by jmbrunskill — APPROVED** [review]
Thanks Brian, looks great.

**Comment by jmbrunskill** [comment]
Updated branch to 2.17.3
