### PR TITLE
6280 fix exporting and importing coldchain equipment

### LINKED ISSUE #6280: CCEI: 'Needs replacement' value `FALSE` treated as `TRUE` when importing CCE
## What went wrong? 😲

When CCE are exported the system generates a .csv with `FALSE` for those CCE that do not have the `Needs replacement` checkbox ticked and `TRUE` for those that do. 

However, when importing the same file, the `FALSE` are treated the same as the `TRUE`

.csv export: 

Image

Import UI: 

Image

Note: there is a side bug where there is an inconsistency in whether `FALSE` or <blank> is populated during the export - looks likely related to whether dates for `Replacement due` are populated or not. 

## Expected behaviour 🤔

The values exported for empty checkboxes should result in empty checkboxes when re-imported. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Export CCE - some with checked box, some without
2. Reimport the exported .csv

## Your environment 🌱

- Open mSupply Version: 2.5.00
- Legacy mSupply Central Server Version: 7.19.06
- Platform: Windows
- Database type: Postgres

### PR DESCRIPTION
**Pull request by zachariah-at-msupply**
Fixes #6280 

# 👩🏻‍💻 What does this PR do?

This PR makes sure that the needs replacement field of cold chain equipment is correctly imported and exported.
It achieves this by adding a formatting function to the 'needs replacement' field in one of the functions that processes the data imported from the csv data.
You'll find that function in line 336 of client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx.

## 💌 Any notes for the reviewer?

It seems the side bug of the issue (that sometimes a blank was inserted instead of 'false' in the needs replacement column in the exported CSV file) was resolved as well as, when I checked it, it seemed that false was consistently added to the correct rows in the CSV file.

# 🧪 Testing

- [ ] In open mSupply, go to Coldchain > Equipment and add at least three assets (the button is in the top right hand corner).
- [ ] Open one of those assets and tick the 'needs replacement' box.
- [ ] Back on the Equipment page, click export.
- [ ] Open the exported CSV using a spreadsheet app or similar (it will be in your downloads folder) and check that it has 'true' in the needs replacement column where it should.
- [ ] Back on the Equipment page in open mSupply, delete all the assets you added.
- [ ] Click import (top right hand corner) and select the file you just exported.
- [ ] Once you've imported the assets, make sure each one has the 'needs replacement' box ticked or not ticked as it should be.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Comment by zachariah-at-msupply** [comment]
To correct my note to the reviewer: it seems that the side issue isn't fixed after all based on some further testing :( Thanks for confirming that @GeronimoJohn 👍 !

File: client/packages/coldchain/src/Equipment/utils.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ export const assetsToCsv = (
       Formatter.csvDateString(node.warrantyEnd),
       node.serialNumber,
       status ? t(status.key) : '',
-      node.needsReplacement,
+      node.needsReplacement ? node.needsReplacement?.toString() : 'false',
```
Comment (GeronimoJohn) [inline client/packages/coldchain/src/Equipment/utils.ts:64]: Thanks Zac! Just wondering if they need to be a string. I think we can go without it and it should work the same 

`node.needsReplacement ? node.needsReplacement : false,`

**Review by GeronimoJohn — APPROVED** [review]
Thanks for the fix @zachariah-at-msupply, good stuff. Works well for me! Just left a few comments but approving!

File: client/packages/coldchain/src/Equipment/utils.ts (hunk 1 above)
Comment (GeronimoJohn) [reply client/packages/coldchain/src/Equipment/utils.ts:64]: Note* `Formatter.csv` formats the value that is returned by `assetsToCsv` to a string. So thought we could let it handle the type conversion instead

File: client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx [hunk 2]
```diff
@@ -55,6 +55,14 @@ const formatDate = (value: string): string | null => {
   return Formatter.naiveDate(DateUtils.getDateOrNull(value, 'dd/MM/yyyy'));
 };
 
+const formatNeedsReplacement = (value: string): boolean | null => {
+  if (value.match(/true/i)) {
+    return true;
+  } else {
+    return false;
+  }
+};
```
[the remark this answers is not in the document]
Comment (CarlosNZ) [reply client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx]: Or just:
```ts
const formatNeedsReplacement = (value: string) => !!value.match(/true/i)
```

😉

**Comment by zachariah-at-msupply** [comment]
It seems like the suggested fix (increasing the width of the list items) might already be implemented. Here is a screenshot from tablet-size sreen (1080x810) to show you what it is like now:

image

However, as you can see from that screenshot, there are some other problems!
The name is wrapping, but seems to be constrained by the row height and overflowing the column width.
Perhaps a horizontal scrollbar is a good solution, or maybe a different way of wrapping, or maybe something else; what are your thoughts @mark-prins?

(Just for reference for the future, I'm making the note that the files effecting this change are client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx and client/packages/system/src/Store/components/StoreSearchInput/StoreOptionRenderer.tsx)
