### PR TITLE
6088 dispensary directions popover shows batch but unclear this is batch

### LINKED ISSUE #6088: Dispensary directions popover shows batch but unclear this is batch
## What went wrong? 😲
Dispensary directions popover in the detail view shows batch number but it's unclear that this is the batch number. Also is it useful to show batch in the Directions? 

Also if you dispense more than 1 batch like the screenshot below, it only shows one batch number

Screenshot 2025-01-16 at 1 46 09 PM

Screenshot 2025-01-16 at 1 46 00 PM

## Expected behaviour 🤔
Should probably remove batch from Directions since you can't give specific directions for each batch and I don't see why you should since it's all the same medicine?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a prescription
2. Add item with direction
3. Go back to detail view
4. Long press note icon
5. See batch number... Just the batch number without any description of what the number means

## Your environment 🌱

- Open mSupply Version: v2.5.0-RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #6088

# 👩🏻‍💻 What does this PR do?

image

Dispensing `directions` pop over not longer shows batch numbers, and only one directions section is shown

## 💌 Any notes for the reviewer?

UI looks a little bit untidy. could be Cleaned up at some point.

# 🧪 Testing

- [ ] Create a prescription
- [ ] Add lines with directions
- [ ] Add multiple batches to a single line.
- [ ] Got to the main view for the prescriptoin and hoverover the notes button
- [ ] You should see the directions shown, but no batch numbers.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/invoices/src/Prescriptions/DetailView/columns.ts [hunk 1]
```diff
@@ -73,18 +73,22 @@ export const usePrescriptionColumn = ({
...
+            const noteSections = [
+              {
+                header: null,
+                body: lineWithNote.note ?? '',
+              },
+            ];
+
             return noteSections.length ? noteSections : null;
-          } else {
-            return rowData.batch && rowData.note
```
Comment (jmbrunskill) [inline client/packages/invoices/src/Prescriptions/DetailView/columns.ts:84]: Don't think we need this for prescriptions maybe makes sense for outbound shipments? Not sure...

**Review by roxy-dao — APPROVED** [review]
LGTM~
