### PR TITLE
Tooltip for item code

### LINKED ISSUE #3353: Code is not fully visible in omSupply -> Catalogue -> Items
## What went wrong? 😲
 

When navigating under omSupply -> Catalogue -> Items and looking at the items' codes, some are not fully visible. There is no functionality to adjust the width of the column either, so you have to click into each individual item to see the code. 

image

## Expected behaviour 🤔

Either the user is able to see the full code straight away, or there is a functionality to adjust the width of the column to minimise/maximise it if necessary. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Catalogue -> Items
2. Scroll through the items
3. Note codes on the left-hand side -> see error

## Your environment 🌱

- Version: 1.7.00
- mSupply version: v7-13-00-Beta25

- Platform: Android Galaxy Tablet A8

- Database type: ?

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3353

# 👩🏻‍💻 What does this PR do? 
Adds tooltips to anywhere that displays the item code

# 🧪 How has/should this change been tested? 
- [ ] Have a really long item code
- [ ] Add the item with this really long code to an invoice
- [ ] Hover over code to see tooltip

## 💌 Any notes for the reviewer?
Probably should implement #3208 soon rather than later since this issue will keep popping up in mobile. Have tested and tried long pressing to get tooltip to show up like MUI docs says, but doesn't trigger 👀

### CODE REVIEW

**Review by clemens-msupply — CHANGES_REQUESTED** [review]
There is this file: `packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts`

For my other PR I made the changes there, i.e. set the Cell in `getColumnLookup()`. Think this should work here as well?

File: client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts [hunk 1]
```diff
@@ -180,6 +180,7 @@ const getColumnLookup = <T extends RecordWithId>(): Record<
     label: 'label.code',
     key: 'code',
     width: 20,
+    Cell: TooltipTextCell,
```
Comment (clemens-msupply) [inline client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts:183]: Didn't you previously had it for 'itemCode' as well?

Comment (roxy-dao) [reply client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts:183]: Oh don't know why it didn't go through 👀 ... because it was in my stash 🤦🏻

**Review by clemens-msupply — APPROVED** [review]
Looks good thank you!
