### PR TITLE
6015 sync pull and push tests failing

### LINKED ISSUE #6015: sync pull and push tests failing on develop
## What went wrong? 😲

Tests still failing on develop:

(sync::test::pull_and_push::test_sync_pull_and_push)

Note 
requisition::program_settings::customer_program_settings::prepare::test::get_customer_program_requisition_settings
requisition::program_settings::supplier_program_settings::test::get_supplier_program_requisition_settings

Are currently failing on develop branch. These can be ignored as are fixed by [this PR](https://github.com/msupply-foundation/open-msupply/pull/5988/files) which is soon to be merged to develop.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. cargo test

## Your environment 🌱

Develop OMS

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #6015 

# 👩🏻‍💻 What does this PR do?

Fixes the CI tests - push_and_pull now passes!

Needed so that we can pick up future things causing failing tests

There were three areas that needing adjusting because while it was failing, further areas were changed that would have also failed the tests if in isolation. Roughly separate commits per part that was failing

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] run: cargo test
- [ ] The CI tests should have passed

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/service/src/sync/test/test_data/master_list.rs [hunk 1]
```diff
@@ -15,7 +16,8 @@ const MASTER_LIST_1: (&str, &str) = (
     "gets_new_items": false,
     "tags": null,
     "isProgram": false,
-    "programSettings": null,
+    "programSettings": {
+    "elmisCode": "elmis"},
```
Comment (lache-melvin) [inline server/service/src/sync/test/test_data/master_list.rs:20]: Hm, shouldn't need this change (should be valid for master lists not to have any program settings, if they aren't programs!)

Tracked it down to this commit, need to add back the is not a program check in the program requisition settings translation 😱 

https://github.com/msupply-foundation/open-msupply/commit/35752e6cea606a00fe44b9120dcac076e031fb61#diff-707ef0e5ba98775e7a08bab3b0c33c6e7c3d00ee995d53043061093467533e73L93-L96

**Review by lache-melvin — CHANGES_REQUESTED** [review]
All tests passing 🥳 🔥 

Just one needs changing 🙏

File: server/service/src/sync/test/test_data/master_list.rs (hunk 1 above)
Comment (aimee-mcneil-melville) [reply server/service/src/sync/test/test_data/master_list.rs]: Great I have moved this - tests pass and I can remove/re-add the program from within mSupply

File: server/service/src/sync/test/test_data/master_list.rs [hunk 2]
```diff
@@ -46,6 +46,7 @@ const MASTER_LIST_2: (&str, &str) = (
 }"#,
 );
 
+//program settings not found
```
Comment (lache-melvin) [inline server/service/src/sync/test/test_data/master_list.rs:49]: can we remove here too plz 🙏

File: server/service/src/sync/test/test_data/master_list.rs [hunk 3]
```diff
@@ -68,6 +69,7 @@ const DEFAULT_PRICE_LIST: (&str, &str) = (
...
```
Comment (lache-melvin) [inline server/service/src/sync/test/test_data/master_list.rs:72]: and this one 😁

File: server/service/src/sync/translations/program_requisition_settings.rs [hunk 4]
```diff
@@ -89,45 +89,49 @@ impl SyncTranslation for ProgramRequisitionSettingsTranslation {
...
-            .program_requisition_order_type_rows
-            .into_iter()
-            .for_each(|u| integration_operations.push(IntegrationOperation::upsert(u)));
-
-        Ok(PullTranslateResult::IntegrationOperations(
-            integration_operations,
-        ))
+        if !data.is_program {
+            return Ok(PullTranslateResult::NotMatched);
+        } else {
```
Comment (lache-melvin) [inline server/service/src/sync/translations/program_requisition_settings.rs:94]: Thanks Aimee - two things here:

First one is just a nit - seeing as you have a `return` inside the if, there's no need for the `else`, and it spares us a layer of nesting 😁 

Secondly - I wonder if maybe you didn't restart backend when re-testing the checking/unchecking `is a program`? When I was unchecking, the program was staying in OMS for me. This is because the soft delete is handled below... i.e. if it _was_ a program, but no longer is, we still want to translate it.

I have a suggestion branch here: https://github.com/msupply-foundation/open-msupply/compare/6015-sync-pull-and-push-tests-failing...6015-sync-pull-and-push-tests-failing(only-early-exit-if-not-a-program)

Hopefully makes sense!

**Review by lache-melvin — CHANGES_REQUESTED** [review]

File: server/service/src/sync/translations/program_requisition_settings.rs (hunk 4 above)
Comment (aimee-mcneil-melville) [reply server/service/src/sync/translations/program_requisition_settings.rs:94]: Yes that does make sense thank you!!

File: server/service/src/sync/test/test_data/master_list.rs (hunk 3 above)
Comment (aimee-mcneil-melville) [reply server/service/src/sync/test/test_data/master_list.rs:72]: Whoops😅

**Review by lache-melvin — APPROVED** [review]
LGTM, thanks for changes Aimee!
