### PR TITLE
9033 subtotal shows the discounted price

### LINKED ISSUE #9033: Subtotal shows the discounted price
## What went wrong? 😲

Image

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create Purchase Order
2. Add PO lines
3. Make sure you have entered diffrent prices and different discount percentages 
4. No go to "More" tab
5. See the `Subtotal`, `After Discount` and `Final Cost` values always stays the same (BUG)

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #9033

# 👩🏻‍💻 What does this PR do?
- Fix purchase order stats view to calculate total before tax as sum of lines after tax
- Move discount side panel information into the pricing section

Screenshot 2025-09-18 at 2 17 56 PM

# 🧪 Testing

- [ ] Have some lines with prices and discount amount
- [ ] See that the side panel's subtotal should equal the lines' total after tax
- [ ] Enter a number in discount info and final cost should change accordingly

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/purchasing/src/purchase_order/DetailView/SidePanel/PricingSection.tsx [hunk 1]
```diff
@@ -36,23 +57,49 @@ export const PricingSection = ({ draft }: PricingSectionProps) => {
...
+  };
+
   return (
     <DetailPanelSection title={t('title.pricing')}>
       <Grid container gap={1} key="pricing-section">
         <PanelRow>
           <PanelLabel>{t('label.cost-subtotal')}</PanelLabel>
-          <PanelField>{c(draft.lineTotalAfterDiscount)}</PanelField>
-        </PanelRow>
-        <PanelRow>
```
Comment (roxy-dao) [inline client/packages/purchasing/src/purchase_order/DetailView/SidePanel/PricingSection.tsx:46]: Mark said this isn't needed, so have removed

File: client/packages/purchasing/src/purchase_order/DetailView/SidePanel/PricingSection.tsx [hunk 2]
```diff
@@ -36,23 +57,49 @@ export const PricingSection = ({ draft }: PricingSectionProps) => {
...
-          <PanelField>{c(draft.orderTotalAfterDiscount)}</PanelField>
+          <PanelField>{c(draft.orderTotalBeforeDiscount)}</PanelField>
         </PanelRow>
         <PanelRow>
           <PanelLabel>
             {splitTranslatedLines(t('label.cost-additional-fees'))}
           </PanelLabel>
           <PanelField>{c(additionalFees)}</PanelField>
         </PanelRow>
+        <PanelRow>
```
Comment (roxy-dao) [inline client/packages/purchasing/src/purchase_order/DetailView/SidePanel/PricingSection.tsx:83]: Moved this here since it makes more sense grouped with the pricing

File: server/service/src/sync/test/test_data/purchase_order.rs [hunk 3]
```diff
@@ -176,8 +176,8 @@ fn purchase_order_1_push_record() -> TestSyncOutgoingRecord {
             communications_charge: None,
             insurance_charge: Some(1.0),
             freight_charge: None,
-            supplier_discount_amount: 20.0,
-            order_total_before_discount: 400.0,
+            supplier_discount_amount: 18.0,
```
Comment (aimee-mcneil-melville) [inline server/service/src/sync/test/test_data/purchase_order.rs:179]: The test still expects 20.0 here to match the legacy record
```suggestion
            supplier_discount_amount: 20.0,
```

**Review by aimee-mcneil-melville — CHANGES_REQUESTED** [review]
Yaaay nice! I like the UI improvements 🎉  

Just the test to fix up otherwise all looking great!
