### PR TITLE
5032 add siteName to OG login v4 requests

### LINKED ISSUE #5032: Slow login/sync user refresh and occasional DB error
## What went wrong? 😲

Using a very large testing central server testing datafile, 100s of stores and users, it was frequently taking up to 60s to simply login in OMS on a decent android tablet. Occasionally, I'd get a error reporting a db locking issue which I am certain was the tablet's DB, not the OMS central. 
image

A similar effect was present for doing a manual sync - it'd say "Updating user" for about 60s and then blast through the rest of sync steps like everything was normal. Once I got a similar DB lock error.
Screenshot_20241007_103407_Open mSupply

## Expected behaviour 🤔

Login should take a couple seconds at most, ideally near instantaneous! No errors thx.

## How to Reproduce 🔨

My chungus datafile: https://drive.google.com/file/d/1DtpWT48Lod9FxeYb4b1QsbF3cnYv4Ysp/view?usp=drive_link

1. Yuuuuge central data? My site had roughly 70k central records and 70k normal records to initialise (which isn't that bad really)
2. Initialise
3. Login (takes ages. Restarting app or any other tricks does not help)
4. Once logged in try manual sync. Hangs on updating user for ages.

## Your environment 🌱

- Open mSupply Version: 2.2.03 and 2.3.0-RC5
- Legacy mSupply Central Server Version: 2.3.0-RC5 (dev)
- Platform: Android Samsung SM-X200
- Database type: sqlite for both remote and central

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #5032 

# 👩🏻‍💻 What does this PR do?

This PR https://github.com/msupply-foundation/msupply/pull/16188 adds `siteName` to the login API to allow filtering by site, reducing the store permission records sent to just those of active stores on the site.

## 💌 Any notes for the reviewer?

I could have made the API a set of store IDs instead. Maybe that'd have been better. 

# 🧪 Testing

- [ ] Checkout https://github.com/msupply-foundation/msupply/pull/16188
- [ ] run OMS and OG central servers
- [ ] Sync an OMS remote site on android
- [ ] Can login with android fine (and other versions)
- [ ] If your user on OG happens to have login rights to 500+ stores, login is still fast provided your site only has a few active stores (if OMS has 500+ active stores then the original problem will still exist)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/login.rs [hunk 1]
```diff
@@ -206,6 +206,7 @@ impl LoginService {
     }
 
     pub async fn fetch_user_from_central(
+        service_provider: &ServiceProvider,
```
Comment (Chris-Petty) [inline server/service/src/login.rs:209]: This feels just a bit spaghetti but it was quick...

**Review by lache-melvin — APPROVED** [review]
woah so speed 🔥
