### PR TITLE
Prevent android crashing when network disabled

### LINKED ISSUE #2526: Android version not running when no network available
## What went wrong? 😲
 

"The tablet is working with WiFi or internet but not working in local host.
..while choosing server to e don’t have localhost as option at all when we connect to WiFi, 
and then we turned off WiFi and choose local host as server but it crashed"

To be investigated.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Turn off wifi
2. From the login screen, click on the server list (pencil icon)
3. Select localhost
4. Boom!

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #2526

# 👩🏻‍💻 What does this PR do? 
 
Two fatal exceptions observed when running the android app without a network
- `CertWebViewClient.shouldOverrideUrlLoading` was raising an Exception about String.length() of a null object
- `NativeApi.java` also raised a null object Exception in the `getHostAddress` call

# 🧪 How has/should this change been tested? 

Turning off wifi on the tablet and starting the app was enough to have the app crash. 

I've cleared app data and run in both Client and Server modes, without a network when displaying the list of servers, only `127.0.0.1` is available - which is a bit of an issue if you are configuring cold chain, but then the network isn't available so cold chain wouldn't be able to connect anyway!

I've uploaded a debug apk file (open-msupply-1.5.00-debug.apk) to a [google drive folder](https://drive.google.com/open?id=117AXnR0If3I_GD6fOW7CAkrH66-zB9PL&usp=drive_fs) to help with testing. The app does not need to be initialised, it will crash prior to that 😉 

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java [hunk 1]
```diff
@@ -199,10 +199,14 @@ public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request
...
+        try {
+            if (url.toString().startsWith(nativeApi.getServerUrl())) {
+                return false;
+            }
+        }
+        catch(Exception e){
+            Log.e(TAG,e.getMessage());
         }
-
         return bridge.launchIntent(url);
```
Comment (andreievg) [inline client/packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java:210]: > CertWebViewClient.shouldOverrideUrlLoading was raising an Exception about String.length() of a null object

Hmm i wonder if the logic here means that when running android app without network, and exception will be called and we will open URL in new browser window ?

File: client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java [hunk 2]
```diff
@@ -499,7 +510,7 @@ public FrontEndHost(JSObject data) {
             // so that we can display the local server IP for users to connect to the API
             if (data.getBool("isLocal") && (ip.equals("127.0.0.1") || ip.equals("localhost"))) {
```
Comment (andreievg) [inline client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java:511]: Sorry I missed this in the previous PR review. 

I was wondering at this stage, wouldn't ip address already be translated (since JSObject data comes from front end, and front end gets it from serviceInfoToObject). 

This is definitly not a PR request atm (don't want to re-test this bit atm), but just wondering, maybe we can simplify in the future.

File: client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java [hunk 3]
```diff
@@ -349,30 +349,41 @@ public void onResolveFailed(NsdServiceInfo serviceInfo, int errorCode) {
...
                     }
                 }
+            } catch (Exception ex) {
+                Log.e(OM_SUPPLY, ex.toString());
             }
-        } catch (SocketException ex) {
+        }
+        try {
+            return serviceInfo.getHost().getHostAddress();
+        } catch (Exception ex) {
```
Comment (andreievg) [inline client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java:370]: nit: maybe nicer to use finally and one exception ?
```java
    private String getHostAddress(NsdServiceInfo serviceInfo, Boolean isLocal) {
        try {
            if (isLocal) {
                for (Enumeration<NetworkInterface> en = NetworkInterface.getNetworkInterfaces(); en
                        .hasMoreElements();) {
                    NetworkInterface intf = en.nextElement();
                    for (Enumeration<InetAddress> enumIpAddr = intf.getInetAddresses(); enumIpAddr.hasMoreElements();) {
                        InetAddress inetAddress = enumIpAddr.nextElement();
                        if (!inetAddress.isLoopbackAddress() && !inetAddress.isLinkLocalAddress()
                                && inetAddress.isSiteLocalAddress()) {
                            return inetAddress.getHostAddress();
                        }
                    }
                }
            }

            return serviceInfo.getHost().getHostAddress();
            
        } catch (Exception ex) {
            Log.e(OM_SUPPLY, ex.toString());
        } finally {
            // with no network available the getHostAddress() will
            // throw an Exception - in this case default to local loopback
            // as no other network is reachable!
            return "127.0.0.1";
        }
    }
```

**Review by andreievg — APPROVED** [review]
Thanks @mark-prins, looks good to me, some observations.

I haven't tested.

I was wondering what do we do with the release (we still haven't gotten to the bottom of the transfers issues, but the test fix is working, do we just merge test fix in main for now and make sure we remove it later ?)

File: client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java (hunk 2 above)
Comment (mark-prins) [reply client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java:511]: you'd think so, but there's also this:

```
export const DEFAULT_LOCAL_SERVER = {
  protocol: 'https' as 'https' | 'http',
  port: 8000,
  ip: '127.0.0.1',
  clientVersion: '',
  hardwareId: '',
  isLocal: true,
};
```

which gives this:

Screenshot 2023-11-22 at 5 09 33 PM

File: client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java (hunk 3 above)
Comment (mark-prins) [reply client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java:370]: yep, nicer. thanks!
