### PR TITLE
5582 Add rounding to internal order request edit

### LINKED ISSUE #5582: Internal Order - Suggested Quantity with decimals
## What went wrong? 😲

discovered during a demo with customer

the suggested quantity is displayed with decimals 

The consequence of this is that if the user wishes to use the ‘Use Suggested Quantity’ button, they must then round up the quantity requested for all order lines where the quantity appears with decimals... which defeats the purpose of simply checking that the suggested quantity is appropriate and moving on to the next item. 

Screenshot 2024-11-27 at 11 42 55 AM

## Expected behaviour 🤔

Would it be possible for the system to automatically round up the suggested quantity? 

if the user chooses to order by unit, then by the unit above, and if by pack, by the multiple of the pack size above?

## How to Reproduce 🔨

You would need a datafile with some consumption history and for the system to calculate suggested quantities for some items
Place an internal orders
Look at the suggested quantities 

## Your environment 🌱

- Open mSupply Version: 2,3,02
- Legacy mSupply Central Server Version:

- Platform: browser (chrome)

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #5582 

# 👩🏻‍💻 What does this PR do?
Update ```Requested quantity``` to round up to next integer and update ```Suggested quantity``` to round to 2 decimal places.

Before
Screenshot 2025-01-14 at 11 12 59 AM

After
Screenshot 2025-01-14 at 11 14 15 AM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create internal order
- [ ] Add item (ensure SOH is lower than AMC)
- [ ] Observe that suggested quantity now rounds to 2 decimal places if number has decimals
- [ ] Toggle from ```units``` to ```packs``` and enter any number with decimals
- [ ] Observe that ```Requested quantity``` only displays a whole integer (not a number with decimals)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx [hunk 1]
```diff
@@ -352,7 +352,7 @@ export const RequestLineEdit = ({
                 Input={
                   <NumericTextInput
                     width={INPUT_WIDTH}
-                    value={draft?.suggestedQuantity}
+                    value={Math.round(draft?.suggestedQuantity * 100) / 100}
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx:355]: We actually have our own number utils for this! Would be:

```tsx
 value={NumUtils.round(draft?.suggestedQuantity, 2)}
```

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Looks great! Just one implementation fix 🙏

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx]: Ah yes I should have noticed that it was used in other places on the page! Updated here b46b9555eb7da42edb31a688562bc604016981ec

**Review by lache-melvin — APPROVED** [review]
🙏
