### PR TITLE
Fix yarn compilation/item warnings graphql

### LINKED ISSUE #6767: Should sync item warnings and print on prescription labels
## What went wrong? 😲

We don't sync warnings so cannot print them on labels. We should sync and print the warnings.

## Expected behaviour 🤔

When printing labels in dispensary 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have an item with a warning defined
2. Print labels in OMS
3. No warning

## Your environment 🌱

- Open mSupply Version: 2.6.0-RC6

## Agreed solution

Turns out in OG we have tables with relationships

`warning <- item_warning_link -> item`

And the link/join table has a `priority` field. You can have many warnings associated with an item. The priority field indicates which gets printed. 

I will go with this for now although, ideally multiple warnings should be printed, and ideally we'd spill over to multiple labels. THAT is out of scope though.

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #6767 

# 👩🏻‍💻 What does this PR do?

Adds the warning node type into the stockline node within the operations.graphql for prescription line and item

This appears to be a duplication as warnings are in the item node, and the stockline node contains the item node so it is required there also

Including warnings in both areas allows correct compilation

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] run yarn re-compile -> no errors
- [ ] yarn test -> no errors
- [ ] Check warnings print as per original PR testing steps in #7251 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/types/schema.ts [hunk 1]
```diff
@@ -9761,7 +9760,7 @@ export type VaccinationNode = {
   invoiceId?: Maybe<Scalars['String']['output']>;
   notGivenReason?: Maybe<Scalars['String']['output']>;
   stockLine?: Maybe<StockLineNode>;
-  vaccinationDate?: Maybe<Scalars['NaiveDate']['output']>;
+  vaccinationDate: Scalars['NaiveDate']['output'];
```
Comment (aimee-mcneil-melville) [inline client/packages/common/src/types/schema.ts:9763]: An update from the regeneration

**Review by CarlosNZ — APPROVED** [review]
LGTM, thanks @aimee-mcneil-melville !
