### PR TITLE
6616 Update disabled action button workflow

### LINKED ISSUE #6616: Clickable disabled button
## What went wrong? 😲
Button is disabled but you can still click to get a message about why it was disabled
Image

## Expected behaviour 🤔
Button should be enabled but with message about why the user cannot do an action. Please check that other sections aren't disabling buttons as well. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a transferred Inbound Shipment
2. Select some lines
3. See clickable disabled delete button

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #6616 

# 👩🏻‍💻 What does this PR do?
Update disabled action footer button workflow. Buttons will now appear 'enabled' but if underlying functionality is disabled then a toast notification will be displayed explaining why action can't be performed. 

Changes needed to standardise functionality/workflow.

## 💌 Any notes for the reviewer?
I'm concerned that removing linkedrequisition check in request requisition and manuallyCreated check in inbound shipment will mess things up. However, I'm hoping that the checks were purely for the disabled button appearing disabled and that there is underlying code that will still run these checks to ensure that the action is indeed disabled. I've left comments in the relevant code areas. 

# 🧪 Testing

- [ ] Navigate to all the various detail view tables
- [ ] Ensure that you have line items that are both in New/Draft and Verified/Finalised stages
- [ ] Select lines and perform actions from action footers
- [ ] For lines that are New/Draft the actions should be carried out as expected
- [ ] For lines that are Verified/Finalised the actions should display a toast notification

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/components/footer/ActionsFooter.tsx [hunk 1]
```diff
@@ -26,20 +24,6 @@ export const ActionsFooter: FC<ActionsFooterProps> = ({
...
-
-  const handleDisabledClick = (
-    disabled?: boolean,
-    disabledToastMessage?: string
-  ) => {
-    if (!disabled) return undefined;
-    return showDisabledActionToastMessage(
-      disabledToastMessage ?? `${t('messages.cannot-perform-action')}`
-    );
-  };
```
Comment (noel-yeldos) [inline client/packages/common/src/ui/components/footer/ActionsFooter.tsx:27]: This was only added because I initially misunderstood how the disabled buttons should work. So, no longer needed.

File: client/packages/common/src/ui/components/footer/ActionsFooter.tsx [hunk 2]
```diff
@@ -61,28 +45,17 @@ export const ActionsFooter: FC<ActionsFooterProps> = ({
...
+        <FlatButton
+          key={label}
+          startIcon={icon}
+          label={label}
+          disabled={disabled}
+          onClick={onClick}
+          // Flatbutton doesn't shrink by default but we want it to in actions footer
+          shouldShrink={shouldShrink ?? true}
+        />
+      ))}
```
Comment (noel-yeldos) [inline client/packages/common/src/ui/components/footer/ActionsFooter.tsx:58]: Removed the div that made the 'disabled' button clickable

File: client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx [hunk 3]
```diff
@@ -31,35 +32,42 @@ export const Footer = () => {
...
+      ? info(t('label.cant-change-location'))()
+      : changeLocationModal.onOpen();
+  };
+
+  const handleReduceLinesClick = () => {
+    !!isDisabled
+      ? info(t('label.cant-zero-stock-lines-disabled'))()
+      : reduceModal.onOpen();
+  };
+
```
Comment (noel-yeldos) [inline client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx:53]: Had to add checks to prevent modal from opening even when action was disabled.

File: client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx [hunk 4]
```diff
@@ -78,10 +77,6 @@ export const FooterComponent: FC<FooterComponentProps> = ({
       label: t('button.delete-lines'),
       icon: <DeleteIcon />,
       onClick: onDelete,
-      disabled: isDisabled || !isManuallyCreated,
-      disabledToastMessage: !isManuallyCreated
-        ? t('messages.cant-delete-transferred')
-        : t('messages.cant-delete-generic'),
```
Comment (noel-yeldos) [inline client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx:84]: Unsure if removing this check for !isManuallyCreated affects underlying functionality or whether it is for displaying a button as disabled only?

File: client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx [hunk 5]
```diff
@@ -44,8 +36,6 @@ export const Footer: FC<FooterComponentProps> = ({
       label: t('button.delete-lines'),
       icon: <DeleteIcon />,
       onClick: confirmAndDelete,
-      disabled: isDisabled || hasLinkedRequisition,
```
Comment (noel-yeldos) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx:47]: Unsure if removing this check for !!hasLinkedRequisition affects underlying functionality or whether it is for displaying a button as disabled only?

File: client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx [hunk 6]
```diff
@@ -36,9 +36,7 @@ export const DetailView: FC = () => {
       data?.program?.id ?? '',
       !!data
     );
-  const { linkedRequisition } = useResponse.document.fields([
-    'linkedRequisition',
-  ]);
```
Comment (noel-yeldos) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx:41]: Relating to https://github.com/msupply-foundation/open-msupply/pull/6749/files#r1974482439. Not sure if removing this affects some other logic?

File: client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx [hunk 7]
```diff
@@ -112,15 +112,12 @@ export const FooterComponent: FC = () => {
...
       icon: <DeleteIcon />,
       onClick: confirmAndDelete,
-      disabled: isDisabled,
-      disabledToastMessage: t('messages.cant-delete-generic'),
     },
     {
       label: t('button.print-prescription-label'),
       icon: <PrinterIcon />,
       onClick: handlePrintLabels,
       disabled: isDisabled || isPrintingLabels,
```
Comment (noel-yeldos) [inline client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx:120]: Have not removed disabled prop from print label button. Desired functionality is to have buttons in footer appear as enabled even if action is disabled under the hood. @Chris-Petty @aimee-mcneil-melville thoughts?

File: client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx (hunk 4 above)
Comment (fergie-nz) [reply client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx:84]: The useDeleteSelectedLines hook will still handle toast and isDisabled. However, in this case this hook (located here: open-msupply/client/packages/invoices/src/InboundShipment/api/hooks/line/useDeleteSelectedLines.ts) is not checking for isManuallyCreated, and so will execute an api request if it is not manually created.

Our back end checks will not allow lines to be deleted in this case, but it would be messy.

I think best would be to add the isManuallyCreated hook to the useDeleteSelectedLines hook, so that it won't try to delete when is manually created.

You could also add a custom message to the hook in this case. ie if the inboundShipment was not manually created, use a different message than if useInbound.utils.isDisabled(); returns true.

File: client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx (hunk 7 above)
Comment (Chris-Petty) [reply client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx:120]: Well it's a mistake to be honest. You should be able to print labels for a verified prescription so please do remove `disabled` here 🙂.

**Review by fergie-nz — CHANGES_REQUESTED** [review]
Looks great Noel.

A couple of requested changes to not send api requests for when the button should be disabled in the respective confirmAndDelete hooks.

And an option to make custom messages in those hooks where there are two ways in which the action can be disabled. These aren't all of the non-specific errors in OMS, so this could be in a follow up issue.

The only one I think we should have custom messages is deleting inboundShipment lines, where you previously had custom messages for generic or can't-delete-transferred. Would you be willing to add this custom message to useDeleteSelectedLines hook in InboundShipment/api/hooks/line

File: client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx (hunk 7 above)
Comment (noel-yeldos) [reply client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx:120]: @Chris-Petty thanks! I was also wondering about ``isPrintingLabels```. Do we need to move that into the isDisabled hook so that I can remove the disabled prop completely from the button? (to be consistent with all other functionality for a disabled button)

File: client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx (hunk 4 above)
Comment (noel-yeldos) [reply client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx:84]: @fergie-nz ah thanks that's what I was wondering about. Makes sense to add that to isDisabeld hook

**Comment by Chris-Petty** [comment]
Probably out of scope, but I'd say it's a mute point whether or not the button is disable or not because the error messages aren't super useful:

image

The user needs to know _why_ they can't do the action.

File: client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx (hunk 7 above)
Comment (Chris-Petty) [reply client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx:120]: Frankly `isPrintingLabels` should show loading progress rather than disabling the button, so that's not awesome either.

Probably out of scope for this issue and probably more a missed review for @GeronimoJohn who I think made the initial PR adding the component:

I came across the design of the footer component I noticed the other day and have been thinking about it since haha. I think it would be more composable if we used the `children` prop built into JSX rather than passing an array of actions. Then we'd be at liberty to use any button we liked. Also no mucking around with arrays and maps, that's just duplicating the work JSX/react does for us there!

https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children

i.e. I want to simply do

```jsx
<ActionsFooter>
  <FlatButton
    startIcon={<DeleteIcon />}
    label={t('button.delete-lines')}
    disabled={disabled}
    onClick={onClick}
    shouldShrink
  />
  <FlatButton
    startIcon={<PrinterIcon />}
    label={label}
    disabled={disabled}
    onClick={onClick}
    shouldShrink
  />
</ActionsFooter>
```

And then you don't have the arrays or the mapping and the JSX more directly reflects what's being rendered. You could argue the array prop deliberately constrains to one button type, but I'd rather have more flexible components I can compose with (reviewer can tell me off if I try put a table in the table footer 😉).

Comment (aimee-mcneil-melville) [reply client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx:120]: I feel like specifically for the isPrintingLabels state it would make more sense to a user if the button greyed out when isPrinting, rather than having no visible change and they need to click again to see a message. That way there is some visual feedback that something happened when they clicked the button

Having the option of a loading button would be great, however the buttons are visually quite different. Throwing it out there of maybe adding a loading state to the flat buttons?

File: client/packages/common/src/ui/components/footer/ActionsFooter.tsx [hunk 8]
```diff
@@ -61,30 +45,18 @@ export const ActionsFooter: FC<ActionsFooterProps> = ({
...
-              // Flatbutton doesn't shrink by default but we want it to in actions footer
-              shouldShrink={shouldShrink ?? true}
-            />
-          </div>
-        )
-      )}
+      {actions.map(({ label, icon, onClick, disabled, shouldShrink }) => (
+        <div key={label}>
+          <FlatButton
+            startIcon={icon}
```
Comment (Chris-Petty) [inline client/packages/common/src/ui/components/footer/ActionsFooter.tsx:51]: I can really see the purpose of this `div`, you should be able to just pass `key` to `FlatButton` to appease react 
```suggestion
          <FlatButton
            key={label}
            startIcon={icon}
```

Comment (noel-yeldos) [reply client/packages/common/src/ui/components/footer/ActionsFooter.tsx:51]: @roxy-dao am I correct in stating that this was needed to right align the clear selection button?

Comment (roxy-dao) [reply client/packages/common/src/ui/components/footer/ActionsFooter.tsx:51]: No.... this line of code `justifyContent: 'space-between'` the key was added to fix console error about how keys should be unique

File: client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx (hunk 4 above)
Comment (noel-yeldos) [reply client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx:84]: Updated here: f1d7c6f401dda676c6d01d84a850290213664421

File: client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx (hunk 6 above)
Comment (noel-yeldos) [reply client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx:41]: Updated here: 31d155813a67a0bb912df49daa313d21d9ddf432

File: client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx (hunk 7 above)
Comment (noel-yeldos) [reply client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx:120]: @Chris-Petty @aimee-mcneil-melville will leave this as is for now 🙏

**Review by fergie-nz — APPROVED** [review]
Nice Noel looks great :)
