### PR TITLE
4826 cold chain equipment module 'store' to show store name too instead of only store code

### LINKED ISSUE #4826: Cold chain equipment module 'store' to show store name too instead of only store code
## What went wrong? 😲
IMAGE 2024-09-20 12:49:50

On the Cold chain Equipment module - when you add a new CCE, the header "store" only shows store code which can be difficult for user to know who to assign asset to.

Suggestion of having both:

Screenshot 2024-09-20 at 12 36 01 PM

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4826

# 👩🏻‍💻 What does this PR do?
Show code and store name in store's search auto complete. 
Screenshot 2024-09-30 at 12 01 50 PM

## 💌 Any notes for the reviewer?
Do we want to change the store column to display the store name instead of store code since it has been commented that store code may make it difficult for user's to know where the asset is?

# 🧪 Testing

- [ ] Create new equipment
- [ ] Select store - see store code and name
- [ ] Go to equipment detail view
- [ ] Click on store
- [ ] See store code and name in selection
- [ ] Also try typing some of the name or code for filtering

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Screenshots for equipment
  2.

### CODE REVIEW

File: client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx [hunk 1]
```diff
@@ -29,18 +38,22 @@ const StoreSearchComponent = ({
   onChange,
 }: StoreSearchInputProps) => {
   const { data, isLoading } = useStore.document.list();
+  const StoreOptionRender = getStoreOptionRenderer();
```
Comment (andreievg) [inline client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx:41]: This should just be a component StoreOptionRender

File: client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx [hunk 2]
```diff
@@ -20,6 +21,14 @@ type StoreSearchInputProps = {
   ) => void;
 };
 
+const filterByNameAndCode = (options: StoreRowFragment[], state: any) =>
```
Comment (andreievg) [inline client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx:24]: Instead of any can we put: FilterOptionsState<StoreRowFragment> ? Or can even add the filter inline in Autocomplete below

File: client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx [hunk 3]
```diff
@@ -132,7 +132,7 @@ export const CreateAssetModal = ({
         __typename: 'StoreNode',
         id: store.id,
         code: store.code ?? '',
-        storeName: '',
+        storeName: store.storeName,
```
Comment (andreievg) [inline client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx:135]: what does this do ? was it previously a bug ?

**Review by andreievg — CHANGES_REQUESTED** [review]
Looks great, samll request StoreOptionRender should just be a component (don't need getStoreOPtionRenderer())

**Review by andreievg — APPROVED** [review]
Looks great, thanks @roxy-dao

**Comment by adamdewey** [comment]
> Do we want to change the store column to display the store name instead of store code since it has been commented that store code may make it difficult for user's to know where the asset is?

Did this get included? 

I think it would be a lot easier to use with the name (or both name and code)

**Comment by roxy-dao** [comment]
> > Do we want to change the store column to display the store name instead of store code since it has been commented that store code may make it difficult for user's to know where the asset is?
> 
> Did this get included?
> 
> I think it would be a lot easier to use with the name (or both name and code)

In the 2.4.0 test build
