### PR TITLE
9731 triplicated gender options in patient filter

### LINKED ISSUE #9731: Triplicated gender options in patient filter
## What went wrong? 😲

Seeing triplicated transgender gender options when filtering patients

Image

## Expected behaviour 🤔

Single `Transgender Male` & `Transgender Female`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Patients
2. Click on the filter option -> click on gender dropdown
3. See triplication

## Your environment 🌱

- Open mSupply Version: `V2.13.00-develop-11101516`
- Legacy mSupply Central Server Version: `V8.06.00`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #9731 

# 👩🏻‍💻 What does this PR do?

Filters out the hormone and surgical gender options from Patients filter table. 

Screenshot 2025-12-10 at 2 19 44 PM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Navigate to Patients page
- [ ] Open up options for filtering via Gender
- [ ] Notice no triplicated gender options

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/utils/mappers/gender.ts [hunk 1]
```diff
@@ -1,6 +1,15 @@
...
 
+export const isSupportedGender = (gender: GenderTypeNode) => {
+  return ![
+    GenderTypeNode.TransgenderFemaleHormone,
+    GenderTypeNode.TransgenderFemaleSurgical,
+    GenderTypeNode.TransgenderMaleHormone,
+    GenderTypeNode.TransgenderMaleSurgical,
+  ].includes(gender);
+};
+
```
Comment (GeronimoJohn) [inline client/packages/common/src/utils/mappers/gender.ts]: If we're specifically trying to resolve the error in the issue. Then filtering out the options is the easiest and quickest solution. 

If we want to fully remove these from the enum. I think would require further discussions, a few migrations, and type regeneration. Mainly the discussion bit - if its still going to be used or is currently used

File: client/packages/system/src/Patient/ListView/ListView.tsx [hunk 2]
```diff
@@ -120,10 +121,12 @@ export const PatientListView = () => {
         enableColumnFilter: true,
         size: 120,
         filterVariant: 'select',
-        filterSelectOptions: Object.values(GenderTypeNode).map(status => ({
-          value: status,
-          label: t(getGenderTranslationKey(status)),
-        })),
+        filterSelectOptions: Object.values(GenderTypeNode)
```
Comment (roxy-dao) [inline client/packages/system/src/Patient/ListView/ListView.tsx]: Can you filter this out by pref gender please thanks, then wouldn't need above (:

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks John , change request below (:

File: client/packages/system/src/Patient/ListView/ListView.tsx (hunk 2 above)
Comment (GeronimoJohn) [reply client/packages/system/src/Patient/ListView/ListView.tsx]: Thats a cleaner solution. Please see changes: https://github.com/msupply-foundation/open-msupply/pull/10002/commits/9c94eb931df83c6f3730275f01e1f510a5cda4fe

Comment (roxy-dao) [reply client/packages/system/src/Patient/ListView/ListView.tsx]: `genderOptions.map`...   then you don't need to filter the gender type node 👀

**Review by roxy-dao — CHANGES_REQUESTED** [review]
map straight from gender options pls (:
