### PR TITLE
Default to allocating in packs if there's only one packsize

### LINKED ISSUE #8258: Outbound Shipment > Add item page: implement a preference for user to choose whether issuing is in units or in packs
Bug cause this feature is to replicate a behaviour that existed in previous versions of Open mSupply. 

## What went wrong? 😲

Some countries may decide to do most of their issuing in quantity of packs, and not in quantity of units. 
However, when adding an item to an Outbound Shipment, the default is to dispense in units, even when there is a single stock line with a pack size of >1

Meaning that user, for each item added to the O/S, will have to select to dispense in packs. In previous versions of OMS, system would automatically suggest to dispense in the pack size of the available stockline. 

## Expected behaviour 🤔

Dropdown should default to the available pack size, where there's only one. 

Another solution would be to have a preference to specify whether default should be units or packs. Similar to what is suggested in https://github.com/msupply-foundation/open-msupply/issues/7954 for ordering. 

## Your environment 🌱

- Open mSupply Version: 2.8.1
- Legacy mSupply Central Server Version:

- Platform: browser (Chrome)

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #8258

# 👩🏻‍💻 What does this PR do?

When creating an outbound shipment, if there's only one existing packsize in stock, default to allocating in that packsize

## 💌 Any notes for the reviewer?

Feels like this maybe should be done in Allocation Context somewhere, however this limits this just to the Outbound shipment page.

# 🧪 Testing

- [ ] Try allocating stock for an item with only one packsize in stock, the sysmte should default to packs of size X where X is the size of the existing stock lines
- [ ] If there's more than one packsize, it should default to units (or doses if vaccine item and `manageVaccinesInDoses` is selected
- [ ] Check I haven't broken anything else.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [X] **These areas should be updated or checked**: 
  1. Allocation docs
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx [hunk 1]
```diff
@@ -62,6 +63,23 @@ export const Allocation = ({
...
 
+      const packsizes = [
+        ...new Set(data.draftLines.map(line => line.packSize)),
+      ];
+
+      // if there is only one packsize, we should auto-allocate in packs for that size
+      let allocateInPacksize: AllocateInOption | undefined = undefined;
+      if (packsizes.length === 1) {
+        const packSize = packsizes[0];
+        if (packSize) {
```
Comment (jmbrunskill) [inline client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx:74]: These multiple `if` statements are a bit messy but Typescript didn't seem to trust that packsize might not be defined. Pretty sure if can be cleaned up but also this works?

**Review by GeronimoJohn — APPROVED** [review]
LGTM! 🔥
