### PR TITLE
#8259 fix/ Adding a reason in stocktake not always possible until clicking on Ok

### LINKED ISSUE #8259: Adding a reason in inventory is not always possible until clicking on OK
## What went wrong? 😲

When we do a stocktake, and try to add a reason, we cannot see the reasons in the drop-down menu. 
We have to click first on OK and then the reasons are available.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Stocktakes', 'New Stocktakes'
2. Click on a 'Masterlist' and chose a 'Masterlist'
3. Chose an item, and enter information (batch, expiry date, stock) 
4. Try to click on 'Reason', see error
5. Click on OK, now it's possible to click on reason

## Your environment 🌱

See video until 00:35

https://github.com/user-attachments/assets/23ff5149-c425-47be-970f-57176303bc2f

https://github.com/user-attachments/assets/470d2e70-43da-4653-88b3-c433e20ffc8b

- Open mSupply Version: demo 2.8.01 on web server and 2.8.01 on tablets 
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

@richardmoizeau 
@Cyrilbrites

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #8259

# 👩🏻‍💻 What does this PR do?
Update `useMemo` dependency array for `columnDefinitions` so that variable changes trigger update without having to click OK

https://github.com/user-attachments/assets/7c7208e8-e42c-4f20-a50e-0b3d12180b5c

## 💌 Any notes for the reviewer?
Not sure if all the dependencies need to be added.

# 🧪 Testing

- [ ] Navigate to Stocktake
- [ ] Create a stocktake
- [ ] Add an item
- [ ] Adjust stock
- [ ] Observe that reasons are enabled immediately after an adjustment number has been entered
- [ ] Observe that when both snapshot and counted are equal then reason is disabled
# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx [hunk 1]
```diff
@@ -267,7 +267,16 @@ export const BatchTable = ({
...
+  }, [
+    update,
+    theme,
+    itemVariantsEnabled,
+    errorsContext,
+    reasonOptions,
+    isLoading,
+    isInitialStocktake,
+    displayInDoses,
+  ]);
```
Comment (noel-yeldos) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx:279]: Not sure if all these dependencies need to be added. Previously it was just `itemVariantsEnabled`

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks Noel... still missing the required asterisk...~

Screenshot 2025-06-23 at 11 41 53 AM

File: client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx [hunk 2]
```diff
@@ -53,8 +53,8 @@ export const ReasonOptionsSearchInput = ({
             }
           : null
       }
+      required={isRequired && !disabled}
       inputProps={{
-        required: isRequired && !disabled,
```
Comment (noel-yeldos) [inline client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx:57]: Thanks @roxy-dao for catching this. It appears that when passing required as inputProps it doesn't actually get sent to the input but when I add it as a prop to Autocomplete it gets applied

**Review by roxy-dao — APPROVED** [review]
Thanks. Gonna get it merged through and James gonna test on tablet
