### PR TITLE
10894 store pref can't set decimal values for under overstock thresholds

### LINKED ISSUE #10894: [Store pref] Can't set decimal values for under / overstock thresholds
## What went wrong? 😲

One of our clients uses the following under/over stock thresholds for their supply levels: 

- National: 1.5 MOS / 7.5 MOS
- Regional: 1 MOS / 5 MOS
- Provincial: 0.5 MOS / 2.5 MOS
- Service point: 0.25 MOS / 1.25 MOS

However we do not allow decimal MOS in the under / overstock thresholds in Store preferences: 

Image

## Expected behaviour 🤔

Can use decimal MOS for these thesholds

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Manage > Stores
2. Try to set a decimal MOS

## Your environment 🌱

- Open mSupply Version: 2.16

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #10894

# 👩🏻‍💻 What does this PR do?
- Adds float preference to support decimal places
- Changed under/overstock MOS threshold preferences to allow floats
- Days in months pref was already f64 value, so have changed that to float type too

# 🧪 Testing

- [ ] Login to store and edit store preferences: under / over stock alerts with some number to 2 decimal places
- [ ] Click save -> Should save
- [ ] Validate dashboard widgets still load and show correct values

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/preference/preferences/days_in_month.rs [hunk 1]
```diff
@@ -14,6 +14,6 @@ impl Preference for DaysInMonth {
     }
 
     fn value_type(&self) -> PreferenceValueType {
-        PreferenceValueType::Integer
+        PreferenceValueType::Float
```
Comment (roxy-dao) [inline server/service/src/preference/preferences/days_in_month.rs:17]: Technically days in months can be decimals ... since avg month in year is 30.42..... and value is already set to f64 👀

**Review by Chris-Petty — APPROVED** [review]
Thanks looks great!

I think it's a shame that the stored value isn't days but nbd. For like `NumberOfMonthsThresholdToShowLowStockAlertsForProducts` you might have a ward pharmacy that just wants like up to 5 days stock, with a 2 day low stock threshold. Bit janky with months input!
