### PR TITLE
9928 asset integration order fix

### LINKED ISSUE #9928: Assets fail to sync (failing integration FK constraint)
## What went wrong? 😲

When initialising a site with stores that have asset data, the asset data fails to integrate due to a FK constraint on asset.store_id (store doesn't exist)

## Expected behaviour 🤔

Assets sync and integrate fine on initialising

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Initialise a site that has assets on its stores
2. Don't see assets!

## Your environment 🌱

- Open mSupply Version: 2.12 (probably existed for at least a year though!)

## Solution

The translator doesn't have FK dependency for `store`, add it!

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #9928

# 👩🏻‍💻 What does this PR do?

Asset had FK constraints that the sync translator was missing for topological sorting before integration

# 🧪 Testing

The original bug might be hit and miss depending on the order of records that come from your central server

- [ ] Central setup with Assets on some stores active on the central server
- [ ] On OG central move the stores to a remote OMS site (trying to ensure that stores are pulled _after_ assets in sync)
- [ ] Initialise the remote site 
- [ ] actually have assets and all related logs/statuses 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/sync/translations/asset_catalogue_type.rs [hunk 1]
```diff
@@ -12,12 +12,12 @@ use super::{
...
 pub(crate) fn boxed() -> Box<dyn SyncTranslation> {
-    Box::new(AssetTypeTranslation)
+    Box::new(AssetCatalogueTypeTranslation)
 }
 
-pub(crate) struct AssetTypeTranslation;
+pub(crate) struct AssetCatalogueTypeTranslation;
 
-impl SyncTranslation for AssetTypeTranslation {
+impl SyncTranslation for AssetCatalogueTypeTranslation {
```
Comment (Chris-Petty) [inline server/service/src/sync/translations/asset_catalogue_type.rs]: it annoyed me looking for the file/struct that it didn't match the table name like every other translator

**Review by andreievg — CHANGES_REQUESTED** [review]
Looks great, want to approve, just one thing thought, about base:

> @andreievg know if this should be based on main or 2.13.0 or create 2.13.1 or?

v2.13.1-RC

**Review by andreievg — CHANGES_REQUESTED** [review]
Please add migration to update sync_buffer, setting integration_datetime and error to null for all the records that are effected with this integration, 'asset', 'asset_log'

**Comment by Chris-Petty** [comment]
@andreievg Took a million years of unrelated compiler errors and cargo cleaning to test this locally but I got there, migration seems to work

**Review by andreievg — APPROVED** [review]
Looks great, thanks Chris
