### PR TITLE
only render quantity inputs after item is set

### LINKED ISSUE #3393: Internal Order defaults to Number Pad when adding Item
## What went wrong? 😲

When adding an item to an internal order, the numpad appears instead of the keyboard (maybe by design). This might confuse our clients on Andoird tablets.

Users have been clicking the Item textbox to bring up the keyboard, and adding quantity after selecting the item.

https://github.com/msupply-foundation/open-msupply/assets/132425100/5ce07edb-283b-41bc-bf59-dcfa08138e27

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Use a Samsung tablet (or even an emulator)
2. Create internal order
3. Click Add Item
4. See Numberpad appears

## Your environment 🌱

- Version: v1.7.0.0 RC1
- mSupply version: 

- Platform: Andoid Tablet - Samsung A8 10"

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #3393

# 👩🏻‍💻 What does this PR do?

Conditionally render requested quantity inputs on internal order, only once item has been set. Item picker now maintains focus, with correct keyboard:

Screenshot 2024-05-06 at 12 09 07 PM

## 💌 Any notes for the reviewer?

Stacked on #3763 to make it slightly easier to validate (enables number pad for numeric quantity inputs)

# 🧪 Testing

- [ ] Use a Samsung tablet (or even an emulator)
- [ ] Create internal order
- [ ] Click Add Item
- [ ] Item picker is in focus (blue underline) and you have the alphanumeric keyboard
- [ ] If you click off the item picker (so it closes, without selecting an item) no quantity inputs are visible
- [ ] Select an item
- [ ] Quantity inputs now appear
- [ ] From Internal Order detail view, open the edit modal for an existing line
- [ ] Quantity inputs should be visible and should autofocus (with numeric keyboard)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx [hunk 1]
```diff
@@ -210,74 +210,79 @@ export const RequestLineEditForm = ({
...
-            <Box display="flex" justifyContent="flex-end" alignItems="center">
-              <Switch
-                label={t('label.units')}
-                checked={isPacks}
-                onChange={(_event, checked) => setIsPacks(checked)}
-                size="small"
-              />
-              <Box paddingLeft={2} paddingRight={2}>
-                {t('label.packs')}
+        currentItem ? (
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx:213]: oh woah big diff... actually just adds this conditional 🙃

Comment (CarlosNZ) [reply client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx:213]: Screenshot 2024-05-06 at 3 07 08 PM

Not so bad with "Hide whitespace" selected 😉

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx [hunk 2]
```diff
@@ -210,74 +210,79 @@ export const RequestLineEditForm = ({
...
+                  />
+                }
+                labelWidth="750px"
+                label={t('label.requested-packs')}
+              />
+            )}
+          </>
+        ) : (
+          <></>
+        )
```
Comment (CarlosNZ) [inline client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx:285]:
```suggestion
  ) : null
```

Prefer this to empty tags personally :)

Comment (CarlosNZ) [reply client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx:285]: Oh, you have to also expand the type: `Middle: React.ReactElement | null;`

Seems reasonable though, since `null` is the standard way to render empty React elements.

**Review by CarlosNZ — APPROVED** [review]
Cool, does the job nicely. I was going to suggest hiding the whole "block" (Left, Middle & Right), but it's too messy to do with the current structure (passing them all separately as JSX chunks), so this is fine. 

Small suggestion about the `null` rather than empty tags, not a big deal either way.
