### PR TITLE
Manually add local server to discovery for local host

### LINKED ISSUE #1349: Mobile app should work without wifi
## What went wrong? 😲

Screenshot 2023-03-14 at 4 07 28 PM

## Expected behaviour 🤔

Tis

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Install App (fresh install or clear data)
2. Turn off wifi and mobile data
3. Press server on start screen

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #1349 

# 👩🏻‍💻 What does this PR do? 

When wifi and mobile data are turned of found out that discovery wasn't working on mobile, errorCode = 0 was returned for `onResolveFailed` method. Now adding local server discovery manually

# 🧪 How has/should this change been tested? 

Reinstall app

- [ ] Turn wifi off and mobile data off
- [ ] Start app in server mode (should go to initialisation screen)
- [ ] Stop app, turn wifi on
- [ ] Start app (should go to initialisation screen)

Try the same in reverse order:

Reinstall app

- [ ] Turn wifi on
- [ ] Start app in server mode (should go to initialisation screen)
- [ ] Stop app, turn wifi off and mobile data off
- [ ] Start app (should go to initialisation screen)

### CODE REVIEW

File: client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java [hunk 1]
```diff
@@ -194,6 +189,8 @@ public void onUnregistrationFailed(NsdServiceInfo serviceInfo, int errorCode) {
                     }
                 });
         isAdvertising = true;
```
Comment (mark-prins) [inline client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java:191]: I wonder if `isAdvertising` and `isDiscovering` should be true when there is no network available?

**Review by mark-prins — APPROVED** [review]
Well, I cannot replicate. Tried several versions on the tablet and have used `develop` on an emulator with mobile data off and wifi off. Checked that chrome cannot reach external sites.. but the discovery still doesn't fail for me.

Will take you word for it - the changes look fine 🤷
