### PR TITLE
4365 the decimal will get too long in outbound shipments

### LINKED ISSUE #4365: The Decimal will get too long in outbound shipments
## What went wrong? 😲

Screenshot 2024-07-04 at 1 36 16 PM
Screenshot 2024-07-04 at 11 04 31 AM

## Expected behaviour 🤔

The values should be rounded up to fixed decimal places

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a item in mSupply with default packsize like 12.3565
2. Receive Some items in decimal and send stocks to OMS store
3. Receive items in OMS store, without altering the packsizes
4. Create outbound shipments and enter values to pack quantity issued to `0.01`
5. Now see the long decimal values

## Your environment 🌱

- Open mSupply Version: v2.1.00-rc6
- Legacy mSupply Central Server Version: v7-15

- Platform: Standalone, Server

- Database type: SQLite

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4365 

# 👩🏻‍💻 What does this PR do?
Only display values at 2 dp and hide longer decimal places with tooltip

Screenshot 2024-07-12 at 6 47 23 PM
Screenshot 2024-07-12 at 6 47 41 PM

# 🧪 Testing

- [ ] Create a item in mSupply with default packsize like 12.3565
- [ ] Receive Some items in decimal and send stocks to OMS store
- [ ] Receive items in OMS store, without altering the packsizes
- [ ] Create outbound shipments and enter values to pack quantity issued to 0.01
- [ ] Alternatively: Keep issuing an item in fraction
- [ ] Go to item/stock
- [ ] See decimal values for stock on hand/average monthly consumption/months of stock 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx [hunk 1]
```diff
@@ -26,8 +26,7 @@ export const PackVariantQuantityCell =
     const formatNumber = useFormatNumber();
     const quantity = getQuantity(rowData);
     const packQuantity = numberOfPacksFromQuantity(quantity);
-    const hasMoreThanTwoDp =
-      packQuantity.toString().split('.')[1]?.length ?? 0 > 2;
+    const hasMoreThanTwoDp = (packQuantity * 100) % 1 !== 0;
```
Comment (mark-prins) [inline client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx:29]: nice! this version looks more robust and easier to read

**Review by mark-prins — APPROVED** [review]
👍 lovely! thanks Roxy 😃
