### PR TITLE
3532 issue stock not clearing values

### LINKED ISSUE #3532: Invoice line: Input retaining previous value and not rendering properly
## What went wrong? 😲
I had an item and put in a number to get the warnings to show up then swapped to another item to try and get this warning to show up but modal wasn't updating. So I closed modal and clicked `Add item` again, and it still has the previous values!

UPDATE: Does seem to reload at some point if I turn away from the web app... but if I enter a new value the value debounces back to the old value 😄 and the message disappears if input no longer in focus... Is this a bug though?!
Screenshot 2024-04-04 at 11 29 32

https://github.com/msupply-foundation/open-msupply/assets/61820074/502d3b0a-dc45-422c-a017-60593ca644f7

In prescription while trying to clear value: (Also can't clear value 👀 ) 

https://github.com/msupply-foundation/open-msupply/assets/61820074/117cdae5-47a2-447b-adf4-15a4ca62922a

## Expected behaviour 🤔
Should be rendering properly

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Add an item with only expired stock to OS
2. Enter value in `Issue`
3. Change to an item with stock available
4. Enter value in `issue`
5. Close modal
6. Click `Add item` again
7. Add the same item as step 3
8. Enter a new value
9. See above message

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #3532

# 👩🏻‍💻 What does this PR do?

- Resets issue quantity to 0 if you change items for Prescription/OS (and clears any warnings)
- Prevents allocation warnings from clearing until you make a change to an issue packs quantity
- Adds debouncing to prescription issue quantity input (immediate auto allocation prevented being able to clear it!)

## 💌 Any notes for the reviewer?

Stacked on #3814, because #3736 reallocation issue was also mentioned in this issue. But now have realised that maybe I should rebase off develop, seeing this issue was actually slated for 2.1.0... thoughts?

# 🧪 Testing

Resets issue quantity to 0 if you change items for Prescription/OS (and clears any warnings)

- [ ] Go to outbound shipment
- [ ] Click add item
- [ ] Select an item
- [ ] Enter a value in `Issue [quantity]`
- [ ] Change the item
- [ ] TEST: Issue quantity should be reset to 0
- [ ] TEST: same for prescription

Prevents allocation warnings from clearing until you make a change to an issue packs quantity

- [ ] In OS, enter a quantity to issue that results in a warning (e.g. if only pack size 10 available, and you say to issue 8)
- [ ] Click on the pack quantity input of one of the rows
- [ ] Click off that input (defocus)
- [ ] TEST: warnings still visible
- [ ] Change the value of the pack quantity input of one of the rows
- [ ] TEST: warnings now disappear
- [ ] TEST: same for prescription

Adds debouncing to prescription issue quantity input (immediate auto allocation prevented being able to clear it!)

- [ ] In prescription edit modal, enter a value in `Issue [quantity]`
- [ ] TEST: You should be able to backspace to clear the value
- [ ] In prescription, issue stock for an item where pack sizes > 1 available
- [ ] TEST: you can type a quantity which starts with 1 e.g. 10, 12, 100.. 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx [hunk 1]
```diff
@@ -47,6 +47,7 @@ export const NumberInputCell = <T extends RecordWithId>({
       }}
       onChange={num => {
         const newValue = num === undefined ? min : num;
+        if (buffer === newValue) return;
         setBuffer(newValue);
         updater({ ...rowData, [column.key]: Number(newValue) });
```
Comment (lache-melvin) [inline client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx:52]: This is what resolves the issue of the allocation warnings being hidden when the pack quantity input is only focused/defocused (rather than actually changed in any way.) `updater` ends up triggering allocation, which clears the warning...

In #3814 I took the opposite approach, expecting `updater` to handle being called with the same value multiple times. However, I don't really see any value in calling these state updates if the value hasn't changed in the first place?

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx [hunk 2]
```diff
@@ -244,6 +244,7 @@ export const OutboundLineEdit: React.FC<ItemDetailsModalProps> = ({
           packSizeController={packSizeController}
           onChangeItem={(item: ItemRowFragment | null) => {
             if (status === InvoiceNodeStatus.New) setIsDirty(true);
+            setIsAutoAllocated(false);
```
Comment (lache-melvin) [inline client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx:247]: This does most of the heavy lifting resetting the the issue quantities if you change the item... which honestly doesn't make that much sense to me? Is there a better name for what this state actually represents?

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx [hunk 3]
```diff
@@ -81,14 +81,10 @@ export const useDraftOutboundLines = (
...
       if (status === InvoiceNodeStatus.New) {
-        let placeholder = lines?.find(
+        const placeholder = lines?.find(
           ({ type }) => type === InvoiceLineNodeType.UnallocatedStock
         );
-        if (!placeholder) {
-          placeholder = draftStockOutLines.find(
-            ({ type }) => type === InvoiceLineNodeType.UnallocatedStock
-          );
-        }
```
Comment (lache-melvin) [inline client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx:91]: This was the other piece to reset to 0 on item change... when the item changed, we were stealing the placeholder line from the previous item, and reassigning it to this one, hence retaining an `issue` quantity via placeholder for that new item 🤯 

I think we only need to worry about a "previous" placeholder if we're editing an existing line (covered above)

I'm a little worried to remove it, I'm sure it was added for a reason? But I can't think of that use case... this useEffect is only triggered when item changes, or API data changes, so should be safe??

**Review by CarlosNZ — APPROVED** [review]
Looks good, thanks @lache-melvin .

I'm still getting a few little quirks in this modal (e.g when it first loads and the pack-size is something other than 1, you briefly see the quantity in single units appear before it settles to the correct quantity for the pack size), but I don't think it's related to this issue, and we discussed needing a bit more substantial overhaul of this modal at some point anyway. So all g for now I think. 👍

**Review by roxy-dao — APPROVED** [review]
Looks good! There's an issue where you: 
1. Put in some number in issue but all lines are expired (e.g. 10)
2. See can't allocated because lines are expired
3. You actually wanted to issue expired so you manually issue (e.g. 10)
4. the total packs becomes 20 since placeholder line + expiry line get added

But okay to leave this for now XD

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx (hunk 3 above)
Comment (lache-melvin) [reply client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx:91]: Oh yeah - didn't touch bc placeholder line not used for prescriptions, but should remove for when we enable 😅

**Comment by lache-melvin** [comment]
> Looks good! There's an issue where you:
> 
> 1. Put in some number in issue but all lines are expired (e.g. 10)
> 2. See can't allocated because lines are expired
> 3. You actually wanted to issue expired so you manually issue (e.g. 10)
> 4. the total packs becomes 20 since placeholder line + expiry line get added
> 
> But okay to leave this for now XD

Oo great spot! I will leave this for now as it looks like I didn't introduce it... do you know if there is an existing issue for it?
