### PR TITLE
6889 enable insurance tab even when program module off

### LINKED ISSUE #6889: Patient Insurance isn't available without the `uses Om Program Module` store pref
## What went wrong? 😲

There's a note in the code but we obviously missed it :(

```
      {/* Only show tabs if program module is on and patient is saved.
      TODO: Prescription tab? - would need tab refactoring since also seems useful in programs
      */}
      {!createNewPatient && store?.preferences.omProgramModule ? (
        <DetailTabs tabs={tabs} requiresConfirmation={requiresConfirmation} />
      ) : (
        <PatientDetailView onEdit={setIsDirtyPatient} />
      )}
```

Image

## Expected behaviour 🤔

If insuranceProviders are available, the tab should show for insurance, even if the `Uses Program Module` is turned off

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Turn off `Open mSupply: Uses Program Module`
2. Go to Patients
3. Try to add Insurnace

## Your environment 🌱

- Open mSupply Version: 2.6.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #6889 

# 👩🏻‍💻 What does this PR do?

If insuranceProviders are available, the tab should show for insurance, even if the Uses Program Module is turned off.

## 💌 Any notes for the reviewer?

Side Quest: I've moved `PatientDetailView` to its own file. `PatientView` had a lot going on for it, navigating can be a bit overwhelming

# 🧪 Testing

If you have insurance providers in your store and programs module is on
- [ ] Turn off `Open mSupply: Uses Program Module` within legacy mSupply for your store
- [ ] Navigate to a Patient
- [ ] Should be able to see any Programs related component
   - [ ] E.g. programs tab, encounter button in dropdown of `AddButton` 
- [ ] Should be able to navigate to insurance tab and add insurance

If you don't have insurance providers in your store and programs module is off
- [ ] Turn off `Open mSupply: Uses Program Module` within legacy mSupply for your store
- [ ] Navigate to a Patient
- [ ] Should not be able to see any programs related component
- [ ] Should not be able to add insurance or visit insurance tab

If you don't have insurance providers in your store but programs module is on
- [ ] Navigate to a Patient
- [ ] Should be able to see any Programs related component
   - [ ] E.g. programs tab, encounter button in dropdown of `AddButton` 
- [ ] Should not be able to navigate to insurance tab or add insurance

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Patient/PatientView/PatientDetailView.tsx
Comment (GeronimoJohn) [inline client/packages/system/src/Patient/PatientView/PatientDetailView.tsx:1]: Extracted `PatientDetailView` into it's own file as `PatientView` can be a bit overwhelming to navigate

File: client/packages/system/src/Patient/PatientView/AddButton.tsx [hunk 1]
```diff
@@ -5,77 +5,98 @@ import {
...
+        }
+      );
+    }
+
+    if (InsuranceProvidersData?.length > 0) {
+      baseOptions.push({
+        value: PatientModal.Insurance,
+        label: t('button.add-insurance'),
+      });
+    }
```
Comment (GeronimoJohn) [inline client/packages/system/src/Patient/PatientView/AddButton.tsx:66]: Added to support that case where we can add an insurance policy for a patient. Even though Programs Module is off.

File: client/packages/system/src/Patient/PatientView/AddButton.tsx [hunk 2]
```diff
@@ -5,77 +5,98 @@ import {
...
+      ),
+      [PatientTabValue.ContactTracing]: options.find(
+        option => option.value === PatientModal.ContactTraceSearch
+      ),
+      [PatientTabValue.Insurance]: options.find(
+        option => option.value === PatientModal.Insurance
+      ),
+    };
+
+    setSelectedOption(optionMap[currentUrlTab as string] || options[0]);
```
Comment (CarlosNZ) [inline client/packages/system/src/Patient/PatientView/AddButton.tsx:98]: Any particular reason to change from the `switch` block?

I like the "map" approach in general, but in this case it seems unnecessarily complicated (with the `.find()`in every value.

File: client/packages/system/src/Patient/PatientView/AddButton.tsx [hunk 3]
```diff
@@ -92,16 +113,18 @@ export const AddButton: React.FC<AddButtonProps> = ({
 
   return (
     <>
```
Comment (CarlosNZ) [inline client/packages/system/src/Patient/PatientView/AddButton.tsx:115]: I'm not usually a fan of the single node inside a fragment (99% of the time it's a mistake), but this might be cleaner in this case. I'd probably go for a ternary here (`return condition ? <SplitButton> : null`), but you decide which you think is tidier.

**Review by CarlosNZ — COMMENTED** [review]
Looking good, @GeronimoJohn -- working as intended. Couple of minor stylistic comments, up to you really.

File: client/packages/system/src/Patient/PatientView/AddButton.tsx [hunk 4]
```diff
@@ -5,77 +5,98 @@ import {
...
+          isDisabled: disableEncounterButton,
+        },
+        {
+          value: PatientModal.ContactTraceSearch,
+          label: t('button.add-contact-trace'),
+        }
+      );
+    }
+
+    if (InsuranceProvidersData?.length > 0) {
```
[the remark this answers is not in the document]
Comment (GeronimoJohn) [reply client/packages/system/src/Patient/PatientView/AddButton.tsx:61]: woops missed that, usually am for camelCase as well

File: client/packages/system/src/Patient/PatientView/AddButton.tsx (hunk 2 above)
Comment (GeronimoJohn) [reply client/packages/system/src/Patient/PatientView/AddButton.tsx:98]: I initially tried sticking with the existing `switch` statement, but due to the dynamic nature of the options array, which now change based on conditions, accessing the values by their index pretty much was not reliable. Before we could do this:

`const [programOption, encounterOption, contactTraceOption, insuranceOption] = options`

And directly pass values in the `switch` statement. But now, the order of options can change. Meaning `programOption` or index 0 might actually be an insurance option. So I thought map might be a better approach.

Though very open for thoughts/improvements. I do think theres a bit going on in the map

**Comment by GeronimoJohn** [comment]
Thanks @CarlosNZ 😃, worked on those changes: https://github.com/msupply-foundation/open-msupply/pull/6910/commits/6534b426bab36869a76420609257c0adb6d99ba7

File: client/packages/system/src/Patient/PatientView/AddButton.tsx (hunk 2 above)
Comment (CarlosNZ) [reply client/packages/system/src/Patient/PatientView/AddButton.tsx:98]: Maybe it'd be a little nicer to just have a static map between PatientTabValue and PatientModal value, and then just one "find" function, something like:
```ts
const optionMap: {
      [key: PatientTabValue]: SplitButtonOption<PatientModal> | undefined;
    } = {
      [PatientTabValue.Programs]: PatientModal.ProgramSearch,
      [PatientTabValue.Vaccinations]: PatientModal.ProgramSearch,
      [PatientTabValue.Encounters]: PatientModal.Encounter,
      [PatientTabValue.ContactTracing]: PatientModal.ContactTraceSearch ,
      [PatientTabValue.Insurance]: PatientModal.Insurance,
    };

setSelectedOption(options.find(option => option.value === optionMap[currentTab])
```

That's untested, but you get the idea. (Also, I think you can properly type the `key` of the map and avoid having to use `as string`

Comment (CarlosNZ) [reply client/packages/system/src/Patient/PatientView/AddButton.tsx:98]: Also, you should be able to define the optionMap outside the component to avoid recreating a new instance every render.

Comment (GeronimoJohn) [reply client/packages/system/src/Patient/PatientView/AddButton.tsx]: So much cleannerrrr. Thanks @CarlosNZ please see changes here: https://github.com/msupply-foundation/open-msupply/pull/6910/commits/98db54624fdb647b6665265e4dcb656bf87ef26a

I've tested and seems to be running the same. And I also tried moving `optionsMap` outside of the component, but JavaScript threw an error indicating that it couldn't access values in it before they were initialised or populated.

Comment (CarlosNZ) [reply client/packages/system/src/Patient/PatientView/AddButton.tsx]: > And I also tried moving `optionsMap` outside of the component, but JavaScript threw an error indicating that it couldn't access values in it before they were initialised or populated.

Even if the `optionsMap` is up the top? (just under the `interface`)

**Review by CarlosNZ — APPROVED** [review]
LGTM! Thanks @GeronimoJohn 

(P.S. I think you could put the `optionsMap` outside the function if it were at the top, but it's not a big deal either way)

**Comment by GeronimoJohn** [comment]
> LGTM! Thanks @GeronimoJohn
> 
> (P.S. I think you could put the `optionsMap` outside the function if it were at the top, but it's not a big deal either way)

Thanks @CarlosNZ, I gave it a go again of moving `optionsMap` above and under the `interface`. Yea it seems to be `undefined` during initialisation which make sense I think. Then gets populated after.  

Screenshot 2025-03-14 at 11 42 45 AM

Error it returns when defined outside of component

Screenshot 2025-03-14 at 11 31 05 AM

Hoping it's not just my machine kinda thing 😅
