### PR TITLE
1633 disable actions if invoice/requisition is uneditable

### LINKED ISSUE #1633: Disable actions if invoice/requisition is uneditable
## What went wrong? 😲
Screenshot 2023-04-28 at 12 18 40 PM

## Expected behaviour 🤔
Note: This is behaviour is blocked in backend. 
Disable actions if invoice/requisition is uneditable (see stocktake for example), maybe also disable the checkboxes too? 

## How to Reproduce 🔨
- Make invoice/requisition uneditable by changing status
- See that you can still select `Delete lines` in actions

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1633

# 👩🏻‍💻 What does this PR do?
Disable actions that aren't available. Thought of disabling whole action bar if user can't interact with it, but we now have returns, so have decided to just disable the action for unification. Also fixed dup return in prescriptions

# 🧪 Testing

- [ ] Have finalised Outbound/Inbound/Returns
- [ ] Click action
- [ ] See actions that aren't available with status disabled.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx [hunk 1]
```diff
@@ -139,20 +139,16 @@ export const StatusChangeButton = () => {
...
     lines?.nodes?.every(l => l.type === InvoiceLineNodeType.UnallocatedStock);
 
-  if (!selectedOption) return null;
-  if (isDisabled) return null;
-
   const noLinesNotification = useDisabledNotificationToast(
     t('messages.no-lines')
   );
 
-  if (!selectedOption) return null;
```
Comment (roxy-dao) [inline client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx:149]: Side quest... dup return

**Review by mark-prins — APPROVED** [review]
🎉  very nice thnx Roxy!
