### PR TITLE
fix internal order value after backspace

### LINKED ISSUE #6185: Doesn't let you enter value when you click on backspace
## What went wrong? 😲

While creating Internal order in android oms (Happens in browser as well), after adding an item it will show`NAN` when you click on backspace and doesn't let you enter value in Requested quantity field.
Video: [HERE](https://drive.google.com/drive/folders/1agIyorH5S0fX08UCnQyq0qRtN3zGN6yv) 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go Replenishment -> Internal Orders
2. Click on `New Order`
3. Create new order and add an item
4. add requested quantity and click on backspace
5. Now you will see NAN and can't delete it or add value

## Your environment 🌱

- Open mSupply Version: `2.5.00-RC4`
- Legacy mSupply Central Server Version:

- Platform: Android

- Database type:

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #6185 

# 👩🏻‍💻 What does this PR do?

When backspacing a value in Internal Order -> New Item -> Requested Quantity, the empty value populates as 'NaN'
Added a NaN check, if the value is not a number it will show '0'. The user will then be able to type in the field with the new number

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go Replenishment -> Internal Orders
- [ ] Click on New Order
- [ ] Create new order and add an item
- [ ] add requested quantity and click on backspace
- [ ] See '0' and that you can type into the field with a new value

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx [hunk 1]
```diff
@@ -259,7 +259,11 @@ export const RequestLineEdit = ({
                   Input={
                     <NumericTextInput
                       width={INPUT_WIDTH}
-                      value={Math.ceil(draft?.requestedQuantity)}
+                      value={
+                        isNaN(Number(draft?.requestedQuantity))
+                          ? 0
+                          : Math.ceil(draft?.requestedQuantity)
+                      }
```
Comment (lache-melvin) [inline client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx:266]: This is how we've done it elsewhere - preventing the storing of the `NaN` value on the draft at all, rather than then having to handle it anywhere we might want to use the draft.requestedQuantity:

https://github.com/msupply-foundation/open-msupply/blob/62ce998db4fa0e5788bca0b4747bceca0cf4f600/client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx#L356-L358

Will hopefully get cleaned up as part of [NumericTextInput fixes](https://github.com/msupply-foundation/open-msupply/issues/4213#issuecomment-2581450867) coming soon, but I think best to update this to match how we are handling everywhere else 🙏

**Review by lache-melvin — CHANGES_REQUESTED** [review]

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx (hunk 1 above)
Comment (aimee-mcneil-melville) [reply client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx:266]: Have updated the solution :)

**Review by lache-melvin — APPROVED** [review]
lovely thank you!
