### PR TITLE
3198 fix rust warnings

### LINKED ISSUE #3198: Fix current Rust warnings (latest Rust)
Also run `cargo update` since current version doesn't compile with latest Rust version (on Linux).

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #3198 

# 👩🏻‍💻 What does this PR do? 
- Updates Cargo.lock using `cargo update`
- Fix resulting warnings

# 🧪 How has/should this change been tested? 
Compile/ run tests

### CODE REVIEW

File: server/graphql/types/src/types/program/encounter.rs [hunk 1]
```diff
@@ -247,7 +247,7 @@ pub struct SuggestedNextEncounterNode {
 #[Object]
 impl SuggestedNextEncounterNode {
     async fn start_datetime(&self) -> DateTime<Utc> {
-        DateTime::<Utc>::from_utc(self.suggested.start_datetime, Utc)
```
Comment (clemens-msupply) [inline server/graphql/types/src/types/program/encounter.rs:250]: This was a warning I introduced recently and missed because of all the other warnings...

**Review by roxy-dao — APPROVED** [review]
Thanks Clemens! I wasn't getting any warnings except for `from_utc`, but still compiles fine for me!
