### PR TITLE
9998 fix sensor list sorting

### LINKED ISSUE #9998: Infinite loading when clicking on Sensors menu twice
## What went wrong? 😲

Possibly related to #9832 

Clicking on `Sensors` twice leads to infinitely loading page

https://github.com/user-attachments/assets/e9d32cd6-5e9f-4b05-a43b-8843a6d0a3e6

## Expected behaviour 🤔

Should not endlessly load

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain -> Sensors
2. Page loads fine first time
3. Click on Sensors again -> endless spinning

## Your environment 🌱

- Open mSupply Version: `V2.14.0`
- Legacy mSupply Central Server Version: `V8.06.12`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

### PR DESCRIPTION
**Pull request by raviSussol**
Fixes #9998 

# 👩🏻‍💻 What does this PR do?
Fixes sensor list sorting error.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to Cold Chain -> Sensors
- [ ] Page loads fine first time
- [ ] Click on Sensors again -> Shouldn't show any error in the notification at the bottom.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/coldchain/src/Sensor/ListView/ListView.tsx [hunk 1]
```diff
@@ -129,7 +129,7 @@ export const SensorListView: FC = () => {
         onOpen(sensor);
       }
     }
-  }, [data?.nodes]);
+  }, [data?.nodes, onOpen, updateQuery, urlQuery]);
```
Comment (raviSussol) [inline client/packages/coldchain/src/Sensor/ListView/ListView.tsx]: Made linter happy.

**Review by Chris-Petty — APPROVED** [review]
Thanks!
