### PR TITLE
5293 backspace autocomlete

### LINKED ISSUE #5293: Unable to backspace item selection
## What went wrong? 😲

Unable to backspace item selection in some modals in omSupply (for example, when adding an item to Inbound or Outbound Shipments)

Video of the behaviour is attached ->>> [here](https://drive.google.com/drive/folders/15g23PCJtCf5FqBo69z8HewK4nMpaAiDa)

## Expected behaviour 🤔

Able to backspace the item's name, instead of fully deleting it (which seems to be the only workaround for now)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> Inbound Shipments
2. Create a new Inbound Shipment
3. Add an item -> after selecting one, attempt to backspace it

## Your environment 🌱

- Open mSupply Version: V2.3.1-RC4
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Galaxy Tablet A8 (Android)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #5293

# 👩🏻‍💻 What does this PR do?

Allows backspacing in item select.

Also fixes searching by both name and code. This was working in 2.4, but only for the first set of items (if you had many items, pagination was broken).

Screenshot 2025-01-22 at 11 25 28 AM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] In outbound shipment
- [ ] Click add item to open modal
- [ ] Search by item name -> you get results
- [ ] Search by item code -> you get results
- [ ] Select an item
- [ ] Click the input again, you can backspace
- [ ] If you backspace far enough, other items start to match again

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 1]
```diff
@@ -26,7 +31,16 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
   includeNonVisibleWithStockOnHand = false,
   itemCategoryName,
 }) => {
-  const { filter, onFilter } = useStringFilter('name');
+  const { filter, onFilter } = useStringFilter('codeOrName');
+  const [search, setSearch] = useState('');
+
+  const [selectedCode, setSelectedCode] = useState('');
+
+  const debounceOnFilter = useDebouncedValueCallback(
```
Comment (lache-melvin) [inline client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx:39]: switched to this useDebouncedValueCallback - useDebounceCallback just fired every call after a delay, rather than only the most recent one 🤷‍♀️

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 2]
```diff
@@ -50,11 +64,17 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
...
+    options: ItemStockOnHandFragment[],
+    state: FilterOptionsState<ItemStockOnHandFragment>
+  ) =>
+    options.filter(
+      option =>
+        option.code.includes(state.inputValue) ||
+        option.name.includes(
+          getItemNameFilterValue(state.inputValue, selectedCode)
+        )
+    );
```
Comment (lache-melvin) [inline client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx:77]: This was needed to have the `{code} {name}` display, but show results when _either_ code or name matches

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 3]
```diff
@@ -100,6 +124,28 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
           'name'
         ).sort((a, b) => a.label.localeCompare(b.label))
       }
+      inputValue={search}
+      inputProps={{
+        onChange: e => {
+          const { value } = e.target;
+          setSearch(value);
+          if (!!currentItem) {
```
Comment (roxy-dao) [inline client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx:132]: Current item doesn't seem to exist for me when I select an item but it does exist after I try to change the item...

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks Lache~

I think the selected item should be added back into the search list since the whole edit section is gone once you try to change the item, but what happens if this was a misclick? 🤔  Can't go back to re-select the item..

Also the filtering doesn't seem to be working properly? I searched for para, but paracetamol didn't show up 👀 

https://github.com/user-attachments/assets/2a559d6a-a2a0-4f35-b914-73a6729fb64c

**Comment by lache-melvin** [comment]
Thanks Roxy:

> I think the selected item should be added back into the search list since the whole edit section is gone once you try to change the item, but what happens if this was a misclick? 🤔 Can't go back to re-select the item..

Ah I was removing it because it was affecting the scrolling but apparently some other change has fixed that, so have added back in 😅 Also ensuring selected item name is restored if you type something else, but then click off [cbef211](https://github.com/msupply-foundation/open-msupply/pull/6228/commits/cbef2119d6d9ca63e909099c5776de1f1e3e097a)

> Also the filtering doesn't seem to be working properly? I searched for para, but paracetamol didn't show up 👀

Wasn't a case insensitive check! Thanks for catching 🙏  [7744efb](https://github.com/msupply-foundation/open-msupply/pull/6228/commits/7744efbb373f9de07f4ac9ae795747f0bd3e8a47) [cb25c32](https://github.com/msupply-foundation/open-msupply/pull/6228/commits/cb25c323dc78b7fdbb869e60ff518875a984e2d8)

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 4]
```diff
@@ -75,24 +102,27 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
...
         t('label.units'),
         formatNumber.format
       )}
       width={width ? `${width}px` : '100%'}
       popperMinWidth={width}
       isOptionEqualToValue={(option, value) => option?.id === value?.id}
-      // open={selectControl.isOn}
-      open={true}
-      onInputChange={(_, value) => debounceOnFilter(value)}
+      open={selectControl.isOn}
```
Comment (lache-melvin) [inline client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx:125]: 🙈 apparently committed something I shouldn't have in the modal PR 😅

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 5]
```diff
@@ -50,11 +65,23 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
...
+    options.filter(option => {
+      const searchValue = RegexUtils.escapeChars(state.inputValue);
+      return (
+        RegexUtils.includes(searchValue, option.code) ||
+        RegexUtils.includes(
+          getItemNameFilterValue(searchValue, selectedCode),
+          option.name
+        )
+      );
+    });
```
Comment (roxy-dao) [inline client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx:81]: Nit: Can this be moved out?

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 6]
```diff
@@ -50,11 +65,23 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
...
+
+  const getOptionLabel = (option: ItemStockOnHandFragment) =>
+    `${option.code} ${option.name}`;
```
Comment (roxy-dao) [inline client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx:84]: This is also used in quite a few item search components, can this be moved to utils to use across?

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks <3 that works like a charm (: Just a few changes below and I think we're good to go~!

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx (hunk 5 above)
Comment (lache-melvin) [reply client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx]: Moved out of component [f1be7e1](https://github.com/msupply-foundation/open-msupply/pull/6228/commits/f1be7e19e087789a780d5af81ea17883804ea225)

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx (hunk 6 above)
Comment (lache-melvin) [reply client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx]: Moved out of the component [f1be7e1](https://github.com/msupply-foundation/open-msupply/pull/6228/commits/f1be7e19e087789a780d5af81ea17883804ea225) - found that the other item search components are not used, so actually just removed them [73743bc](https://github.com/msupply-foundation/open-msupply/pull/6228/commits/73743bca1fddd9541cf68315982839034cf3311e) 🎉
