### PR TITLE
10440 add missing filters pt2

### LINKED ISSUE #10440: More missing table filters
## What went wrong? 😲

* Stock view: cannot filter for items by code
* No date filters for Breaches and Log tabs of cold chain monitoring
* Manage > Stores: no code or name filter
* Catalogue > Items: code or name filter does not work

Image

Image

Image

Image

Image

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #10440

# 👩🏻‍💻 What does this PR do?

Restore filters toolbar on Cold Chain -> Monitoring -> Breaches & Log tab

Fix name or code search on Item List

The remaining raised filter on the issue is for `stock list view` item name or code - it does work correctly and is a name/code/batch search, so does not have the same label as the other name and code searches - left as it is. Maybe the naming isn't intuitive is users are looking for a `code or name` search

Screenshot 2026-02-11 at 4 52 51 PM
Screenshot 2026-02-11 at 4 52 25 PM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to Cold Chain -> Monitoring -> check filters work on each of the Breaches & Log tabs
- [ ] Go to Catalogue -> Items -> check the Code or Name filter works

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Item/ListView/ListView.tsx [hunk 1]
```diff
@@ -89,33 +88,28 @@ export const ItemListView = () => {
         description: t('description.months-of-stock'),
         columnType: ColumnType.Number,
         size: 120,
-        // TODO: Mix-max filter on months of stock
```
Comment (aimee-mcneil-melville) [inline client/packages/system/src/Item/ListView/ListView.tsx]: Not using column filters in the table now and there are individual min/max filters in place already, so I think this won't apply any longer

**Comment by aimee-mcneil-melville** [comment]
> Thanks Aimee (:
> 
> The stock list view should be searchable by item code or name as well.

Thanks Roxy, I found the stock list one worked, it is titled 'search' perhaps the naming isn't intuitive?
I have edited the pr comment also for clarity

> The remaining raised filter on the issue does work correctly and is a name/code/batch search
