### PR TITLE
Fix tests failing on Main branch.

### LINKED ISSUE #10320: Tests failing on main branch
## Expected behaviour 🤔

Tests should pass

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Run tests in CI

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #10320

# 👩🏻‍💻 What does this PR do?

Tests were failing to run as dependancies weren't available to build `node-hid` I think previously we were using a pre-build package from the maintainer, but due to the node version change it was no longer finding one.

```
error /home/runner/work/open-msupply/open-msupply/client/node_modules/node-hid: Command failed.
Exit code: 1
Command: prebuild-install --runtime napi || node-gyp rebuild
Arguments: 
Directory: /home/runner/work/open-msupply/open-msupply/client/node_modules/node-hid
Output:
prebuild-install warn This package does not support N-API version undefined
prebuild-install warn install No prebuilt binaries found (target=undefined runtime=napi arch=x64 libc= platform=linux)
```

So long ans short, it seems like a `yarn upgrade` fixed this problem. Not entirely sure why!
I think the updated version of the nodehid must have a compatible pre-build.

I spent a bunch of time trying to find which pre-builds are available, and trying different versions of node etc...

## 💌 Any notes for the reviewer?

Also tried this, but then fails to build on another dependancy, this appraoch would also work but will slow down the builds so would like to avoid it.
```
      - name: Install libusb (needed for node-hid build)
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev
```

Also updated to remove `[set-output]` on our workflows as apparently that's deprecated and will reduce our warnings.

# 🧪 Testing

- [ ] Check the github actions pass
- [ ] Make sure json forms is ok
- [ ] Make sure the app hasn't broken due to any of the depenancy updates

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx [hunk 1]
```diff
@@ -201,7 +201,7 @@ const UIComponent: FC<LayoutProps & AjvProps> = ({
 
   const categories = categorization.elements.filter(
     (category: Category | Categorization): category is Category =>
-      isVisible(category, data, '', ajv) && category.type === 'Category'
+      isVisible(category, data, '', ajv, undefined) && category.type === 'Category'
```
Comment (CarlosNZ) [inline client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx]: Not sure what it uses the `config` for, but probably safer to pass the actual config rather than `undefined`:

https://github.com/msupply-foundation/open-msupply/compare/10320-testfailinginci...10320-testfailinginci-suggestion

**Review by CarlosNZ — APPROVED** [review]
Okay, LGTM, thanks 👍 

(Just wait for the current tests to finish before merging, cos wouldn't that be ironic...)

**Comment by Chris-Petty** [comment]
I was having the problem locally and this branch fixed it for meeee
