### PR TITLE
4883 create return when not this facility

### LINKED ISSUE #4883: Vaccine card: customer return not created when changing this facility -> other
## What went wrong? 😲

Can't reverse the prescription when changing to another facility 😢 

## Expected behaviour 🤔

If you check the `reverse prescription` toggle... it reverse!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a vaccination that was `given` at this facility (that has a prescription created)
2. Change facility to `Other`
3. Toggle the `Revert existing stock transaction` ON
4. Save
5. BUG: Reopen - still shows prescription at the top of the vaccination, no customer return was created

## Context

I think this is from the change to allow `given` vaccinations with no associated stockline... stockline might need to be NullableUpdate now? Currently, if given == true and stockline == null, we keep the existing stockline!

## Your environment 🌱

- Open mSupply Version: 2.3 RC1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #4883

# 👩🏻‍💻 What does this PR do?

Ensures invoices are updated when facility is changed from this facility to other.

Also fixes the `record historic transaction` toggle showing up when it shouldn't

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to a vaccination that was given at this facility (that has a prescription created)
- [ ] Change facility to Other
- [ ] Toggle the Revert existing stock transaction ON
- [ ] Save
- [ ] prescription no longer shows at the top of the vaccination, customer return was created

ALSO
- [ ] Create vaccination at Other facility
- [ ] Enter for date in the past
- [ ] Set to given
- [ ] Ensure no toggle shows up to `record historic stock transaction`

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks Lache~

The return does get created for me but the prescription link is still showing on top for me. 
Screenshot 2024-09-27 at 9 25 04 AM

Also, shouldn't a prescription be created at a store if the user accidentally enters some facility and changes it to an mSupply facility?

**Comment by lache-melvin** [comment]
Yeah expected behaviour, I'll double check it all now 🫠:

- Give at this facility: creates a prescription
- Change to `other` (or to not given): creates return, removes link to prescription
- Change back to given at this facility: creates new prescription, adds link to it
- Change the item/batch: creates return for old batch and new prescription

File: server/service/src/vaccination/update/generate.rs [hunk 1]
```diff
@@ -62,44 +64,53 @@ pub fn generate(
...
-
-            let create_return = InsertCustomerReturn {
-                id: uuid(),
-                other_party_id: patient_id.clone(),
-                is_patient_return: true,
-                outbound_shipment_id: None,
-                customer_return_lines: vec![CustomerReturnLineInput {
+    let create_customer_return = if (stock_line_has_changed || should_revert) && update_transactions
+    {
+        existing_prescription_line
```
Comment (lache-melvin) [inline server/service/src/vaccination/update/generate.rs:72]: added in prescription line - realised there were a couple MORE cases:

- If you give (and create prescription) -> change batch and _don't_ update transactions -> un-give and _do_ revert transactions, it was creating a return of the new batch, rather than what was in the prescription!
- Also needed to handle give (create prescription) -> change to Other facility (which clears vaccination `stock_line`) but don't revert prescription -> reopen modal and click revert... so needed to check if the prescrizzle existed rather than if the vaccination stock line was changing!

File: client/packages/system/src/Vaccination/api/useVaccination.ts [hunk 2]
```diff
@@ -218,17 +220,15 @@ const useUpdate = (vaccinationId: string | undefined) => {
         clinicianId: setNullableInput('id', input.clinician),
```
Comment (roxy-dao) [inline client/packages/system/src/Vaccination/api/useVaccination.ts:220]: Should Clinician id also be nulled if isOtherFacility?

File: server/service/src/vaccination/update/generate.rs (hunk 1 above)
Comment (roxy-dao) [reply server/service/src/vaccination/update/generate.rs:72]: can use and_then instead of map.flatten (:

File: client/packages/system/src/Vaccination/api/useVaccination.ts (hunk 2 above)
Comment (lache-melvin) [reply client/packages/system/src/Vaccination/api/useVaccination.ts:220]: Oo great catch, thank you!

**Review by roxy-dao — APPROVED** [review]
Thanks for the changes Lache (:
