### PR TITLE
8416 masterlist stocktake placeholder

### LINKED ISSUE #8416: Cannot create stocktake from master list with placeholder lines
## What went wrong? 😲

Cannot create stocktake with placeholder lines from master list in 2.9

## Expected behaviour 🤔

Can create stocktake with placeholder line from master list, as per 2.8

**Edited**
Add a checkbox below the master list selection, which shows when a master list has been chosen (or all the time if that is difficult). The label is `Include out of stock items`

for example:

Image

when selected:
* the `Location` and the `Items expiring..` inputs are disabled.
* all items on the selected master list are added to the stocktake
* the `Lines found` number shows the full count of lines on the master list

Rename the `Stock lines found` label to be `Stocktake lines` to avoid the confusion when adding all lines from a master list.

## Extra

Putting this as bug because I think it's a regression ?

## How to Reproduce 🔨

Compare (notice it's on port 9000), Admin:pass, with demo server:

`docker run --platform="linux/amd64" -e LOAD_REFERENCE_FILE=reference1 -p 9000:8000 msupplyfoundation/omsupply:v2.9.00-RC-07081817-dev`

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #8416

# 👩🏻‍💻 What does this PR do?
Allow users to select a master list and optionally get all the items related to that master list added to the stocktake.

Blank Stocktake shows 0 estimated lines
image

Master List shows the 2 
image

Master list plus include `out of stock items` shows the full masterlist number
image

If `Include out of stock items` is checked the other filters are disabled.

If there's more in stock lines than master list lines, we keep the estimated lines even if the user selects include out of stock items

image

image

## 💌 Any notes for the reviewer?

Did I miss anything from the requirements?

The styling is not nice using 160px to push the label to the right. This is not my forte so very happy if there's a nicer solution there!

# 🧪 Testing

- [ ] Try creating a stocktake for a master list and make sure you can get all the other of stock items too.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [X] **These areas should be updated or checked**: 
  1. Stocktake
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [X] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Comment by jmbrunskill** [comment]
NOTE: Missed these requirements... will update shortly...

- [ ] The Lines found number shows the full count of lines on the master list
- [ ] Rename the Stock lines found label to be Stocktake lines to avoid the confusion when adding all lines from a master list.

File: server/service/src/stocktake/insert/generate.rs [hunk 1]
```diff
@@ -121,8 +137,8 @@ fn generate_stocktake_lines(
                          barcode_id: _,
                          item_variant_id,
                          donor_link_id,
-                         vvm_status_id: _,
-                         campaign_id: _,
+                         vvm_status_id: _, // Todo?
+                         campaign_id: _,   // Todo?
```
Comment (jmbrunskill) [inline server/service/src/stocktake/insert/generate.rs:141]: Should we be pulling campaigns into stocktake, I feel like we probably should?

File: server/service/src/stocktake/insert/generate.rs [hunk 2]
```diff
@@ -201,3 +217,110 @@ fn generate_lines_initial_stocktake(
 
     Ok(result)
 }
+
+pub fn generate_lines_from_master_list(
```
Comment (jmbrunskill) [inline server/service/src/stocktake/insert/generate.rs:221]: THis is pretty much a copy and paste from the old code...

File: server/service/src/stocktake/insert/generate.rs [hunk 3]
```diff
@@ -201,3 +217,110 @@ fn generate_lines_initial_stocktake(
...
+                StockLineFilter::new()
+                    .item_id(EqualFilter::equal_to(item_id))
+                    .store_id(EqualFilter::equal_to(store_id))
+                    .has_packs_in_store(true),
+                Some(store_id.to_string()),
+            )
+            .unwrap();
+        let item_name = ItemRowRepository::new(connection)
+            .find_active_by_id(item_id)
+            .unwrap()
```
Comment (jmbrunskill) [inline server/service/src/stocktake/insert/generate.rs:251]: Don't like these unwraps, should I handle them better?

Comment (roxy-dao) [reply server/service/src/stocktake/insert/generate.rs:251]: .find_active_by_id(item_id)?
            .map(|item_row| item_row.name);

File: server/service/src/stocktake/insert/generate.rs [hunk 4]
```diff
@@ -76,6 +78,20 @@ fn generate_stocktake_lines(
...
+            None => {
+                return Err(RepositoryError::DBError {
+                    msg: "Master list ID is required when including all master list items"
+                        .to_string(),
+                    extra: "include_all_master_list_items is true".to_string(),
+                });
+            }
+        };
+        return generate_lines_from_master_list(connection, store_id, &id, &master_list_id);
+    }
```
Comment (roxy-dao) [inline server/service/src/stocktake/insert/generate.rs:93]:
```suggestion
    if let Some(true) = include_all_master_list_items {
        match master_list_id {
            Some(master_list_id) => {
                return generate_lines_from_master_list(connection, store_id, id, &master_list_id)
            }
            None => {
                return Err(RepositoryError::DBError {
                    msg: "Master list ID is required when including all master list items"
                        .to_string(),
                    extra: "include_all_master_list_items is true".to_string(),
                });
            }
        };
    }
```

or just empty vec...

File: server/service/src/stocktake/insert/generate.rs (hunk 1 above)
Comment (roxy-dao) [reply server/service/src/stocktake/insert/generate.rs:141]: Yes, that's in 2.10 probably

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks James~ Just one nit 👀 and other comments~

**Review by roxy-dao — APPROVED** [review]
Clicked wrong button
