### PR TITLE
#7476 Fix log re-opening bug

### LINKED ISSUE #7476: `View log` won't show second time after you open and close after the first time and window does not gets closed after downloading database
## What went wrong? 😲

`View log` won't show log second time after you open and close after the first time

https://github.com/user-attachments/assets/f55b0f7d-03d2-4adc-97d7-9a50aa6470f5

https://github.com/user-attachments/assets/57cd2edf-da07-4541-9687-82dbaadb2f8c

## Expected behaviour 🤔

The log should be opened every time when requested

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Settings->Support->Server log
2. Click on `View the log`
3. View the log
4. Close the window
5. Again try to view log
6. Now, you cannot view log (BUG)

## Your environment 🌱

- Open mSupply Version: v2.7-00-RC7
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #7476

# 👩🏻‍💻 What does this PR do?

Fixes the "Log" modal not re-opening if you close it via the "X" icon (rather than the OK button).

The `onClose` handler wasn't being passed to the `useDialog` hook, so wasn't being called when clicking the "close" icon.

## 💌 Any notes for the reviewer?

Have also changed for Android (as it uses a different component for the Modal).

# 🧪 Testing

- [ ] Go to Settings -> Support
- [ ] Click the "View" button for Server Log
- [ ] Close the modal via the "X" icon
- [ ] Click the "View" button again
- [ ] The modal should open again as expected

Would suggest also testing on Android and Electron if possible.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/host/src/Admin/DisplaySettings.tsx [hunk 1]
```diff
@@ -110,7 +110,6 @@ export const DisplaySettings: React.FC = () => {
 
   return (
     <>
-      {' '}
```
Comment (CarlosNZ) [inline client/packages/host/src/Admin/DisplaySettings.tsx:113]: Unrelated, but just noticed this pointless space hanging around.

**Review by jmbrunskill — APPROVED** [review]
Looks safe to me :) Haven't tested though.
