### PR TITLE
5102 cannot change servers tablet

### LINKED ISSUE #5102: Cannot change servers unless logged in
## What went wrong? 😲

Cannot change servers unless logged in

https://github.com/user-attachments/assets/771865ec-db11-41e1-bef4-00bc9ddd8409

## Expected behaviour 🤔

Able to change servers

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to omSupply on a tablet (apk)
2. Try to change the server when not logged in
3. Cannot perform the action

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC8
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (apk)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #5102 

# 👩🏻‍💻 What does this PR do?

Tablet - Shouldn't be able to change servers if a user decides to initialise via the Server.

When initializing or going through the Client, users can change the server without any issues. However, initializing through the Server causes an authentication issue when a user tries to change servers.

Screenshot 2025-01-17 at 11 57 43 AM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Run in tablet
- [ ] Initialise OMS through Server mode
- [ ] After initialise, login page shouldn't have the ability to change servers

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Comment by GeronimoJohn** [comment]
Revisiting solution

**Comment by GeronimoJohn** [comment]
ready for review

File: client/packages/host/src/components/SiteInfo.tsx [hunk 1]
```diff
@@ -27,8 +30,17 @@ const RowWithLabel = ({
...
 
 export const SiteInfo: FC<{ siteName?: string | null }> = ({ siteName }) => {
-  const { connectedServer, goBackToDiscovery } = useNativeClient();
   const t = useTranslation();
+  const nativeApi = getNativeAPI();
+  const [localMode, setLocalMode] = useState(NativeMode.None);
+  const { connectedServer, goBackToDiscovery } = useNativeClient();
+
+  useEffect(() => {
+    getPreference('mode', '"none"').then(setLocalMode);
```
Comment (lache-melvin) [inline client/packages/host/src/components/SiteInfo.tsx:39]: NIT: 

```suggestion
    getPreference('mode', NativeMode.None).then(setLocalMode);
```

**Review by lache-melvin — APPROVED** [review]
LGTM, thank you!
