### PR TITLE
#2932 Number fixes

### LINKED ISSUE #2932: Remaining Number Input issues
EDIT: As well as the below problem, there are a few other implementations around where the logic of the parent components still needs updating to work with the new input component (from #2794).

Let's use this issue to list them all as we find them and I'll sort them out all at once. Please add to the checklist here, and put any further detail/screenshots etc in comments below. Thanks.

- [x] Problem clearing # packs (below) (something is turning it into `type="number"` from above which is odd, too)
- [x] Still have a couple of `type="number"` attributions in Programs that should be removed
- [x] [Inbound shipment pack quantity](https://github.com/msupply-foundation/open-msupply/issues/2932#issuecomment-1942859584) should just be a NumberDisplayCell (i.e. not editable)
- [x] [French currency formatting of thousands test failing](https://github.com/msupply-foundation/open-msupply/issues/2932#issuecomment-1944492789)
- [ ] See if "react-currency-input-field" can be removed and just use the built-in IntlNumber.format() function to do what we want
- [ ] [The separator for EU should be  but input always ends up adding , for the last two numbers even if you are not typing a decimal?](https://github.com/msupply-foundation/open-msupply/issues/2932#issuecomment-1963032660)
- [x] [Decimal doesn't work beyond 2 dp](https://github.com/msupply-foundation/open-msupply/issues/2932#issuecomment-1963048439)

## What went wrong? 😲
 

https://github.com/msupply-foundation/open-msupply/assets/55115239/40ac1ca7-4693-48ab-a706-834fbf2aa50d

I'm passing in props that this should be a required value with a minimum of 1, but clearing the input results in NaN, which I can then clear to nothing...

I think this is broadly an issue with the `NumberInputCell`, as I've seen this issue in at least Inbound Shipment, Stocktake and new Supplier Returns so far...

## Expected behaviour 🤔

Clearing the input sets the value to 0, or the minimum value if min>0.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to an Inbound Shipment details page
2. Click on a line to edit
3. Clear the # packs input
4. See `NaN`
5. Clear the `NaN`
6. See nothing in the input

## Your environment 🌱

 - Version: 1.6.x (develop)
 - Platform: browser (Chrome)

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #2932 

# 👩🏻‍💻 What does this PR do? 
 

This fixes the items listed in #2932, except for two of them (unticked), but they're covered by [this issue's suggested solution](https://github.com/msupply-foundation/open-msupply/issues/2918#issuecomment-1965489335).

The main problem I discovered is that the `format` method (in NumUtils), which uses `Intl.NumberFormat`, defaults to 3 dp. So I've just made set that to default to the maximum allowed (21 dp) and we can continue using our `.round()` method to handle precision.

# 🧪 How has/should this change been tested? 

Tested the main cases listed in the issue. However I haven't properly tested the two Programs components affected. All I did there was remove the `type="number"` attribute, so I think it should be fine but if anyone has Programs set up on their system and can confirm it's okay, that'd be great.

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts [hunk 1]
```diff
@@ -205,7 +203,6 @@ export const useInboundShipmentColumns = () => {
       [
         'numberOfPacks',
         {
-          Cell: props => <NumberInputCell {...props} min={1} />,
           accessor: ({ rowData }) => {
```
Comment (CarlosNZ) [inline client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts:206]: Should have been a read-only cell, accidentally changed in last PR.

File: client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx [hunk 2]
```diff
@@ -44,7 +44,7 @@ export const NumberInputCell = <T extends RecordWithId>({
         ...TextInputProps?.InputProps,
       }}
       onChange={num => {
-        const newValue = num;
+        const newValue = num === undefined ? 0 : num;
```
Comment (mark-prins) [inline client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx:47]: I would change to this - as it currently stands, you can clear the input and it gets set to `0`. then, you can press the down arrow to go lower than zero and the value changes to the min, which defaults to `1`. Setting the default to be the min feels more intuitive

```suggestion
        const newValue = num === undefined ? min : num;
```

that was along with 
line 17: `min = 1,` and move the comment from 53 to here as well
line 53: `min={min}`

File: client/packages/common/src/intl/number/IntlNumber.ts [hunk 3]
```diff
@@ -15,7 +15,11 @@ export const useFormatNumber = () => {
     ) => {
       if (value === undefined) return '';
       const locale = options?.locale ?? currentLanguage;
-      return new Intl.NumberFormat(locale, options).format(value);
+      return new Intl.NumberFormat(locale, {
+        // Don't round here, as most use cases have their own internal rounding
```
Comment (mark-prins) [inline client/packages/common/src/intl/number/IntlNumber.ts:19]: I don't believe the comment is accurate!
Have looked for all usages of `format` and only the NumericTextInput is rounding, though not with options to the format (`setTextValue(format(constrained))`) 

The usages are in:
* NumericTextInput (this relies on downstream usage specifying dp which I think they all do)
* StockItemSearchInput
* StockItemSearchInputWithStats
* OutboundLineEditForm
* PrescriptionLineEditForm

all the others are using integers, so won't have an issue with the change.

Maybe just remove the comment. it only really makes sense in light of the change

**Review by mark-prins — APPROVED** [review]
👍  thanks @CarlosNZ looking good!

I have a request to change behaviour, see what you think. It's a bit odd with the clearing of a text value resetting to `0` when the min is higher than this.

File: client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx (hunk 2 above)
Comment (CarlosNZ) [reply client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx:47]: Yes, makes sense. I'll update this.

File: client/packages/common/src/intl/number/IntlNumber.ts (hunk 3 above)
Comment (CarlosNZ) [reply client/packages/common/src/intl/number/IntlNumber.ts]: Yeah, it made more sense when I was considering a few additional updates.
