### PR TITLE
7314 regenerate report and improve item usage performance

### LINKED ISSUE #7314: Generated report have extism functions and item usage report is too slow
## What went wrong? 😲

Generated report have extism functions (12mb vs 100kb) and item usage report is too slow

## Expected behaviour 🤔

Generated report have small bundle size

## How to Reproduce 🔨

Run with postgres feature, on 2.6.2

In local.yaml set backup_dir to something valid

Download backup from [here D2025_04_13T22_00_02](https://drive.google.com/drive/u/1/folders/1Pm1Pac33bPh_BwIH7khGCw-8Iq-vG0RK), extract to the folder specified above

Run `cargo run  --features postgres --bin remote_server_cli -- restore -b D2025_04_13T22_00_02

Login with credentials [here](https://docs.google.com/document/d/1QbIBs77pagYIzlZd7kHK2eQQLoC6Gunq7d6nFnFwdDE/edit?tab=t.0)

Try to generate item usage report, you'll get an error with extism.

Run `cargo run --features postgres --bin remote_server_cli -- build-reports && cargo run --features postgres --bin remote_server_cli -- upsert-reports`

Now run item usage report it will take a long time to run (i didn't have it finish, it's too long)

Also if you install 2.6.2 to central and then try to sync remote you will see that pull is taking a bit of time (if remote and central don't have great internet connection)

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #7314

# 👩🏻‍💻 What does this PR do?

Fix item usage performance

Regenerate reports

Remove current standard reports (not custom), these will be re-instated by upsert script that run on startup. Without these change central server will sync all of these report out

## 💌 Any notes for the reviewer?

Sorry commit message is wrong "Remove current non custom standard reports" should be non custom reports, will update when squashing

# 🧪 Testing

Replication steps in issue. 

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/repository/src/migrations/v2_06_03/remove_non_custom_standard_reports.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+        "add_assign_requisition_number_processor_cursor_pg_enum_type"
+    }
+
+    // For non-transfer-related processing of requisitions
+    fn migrate(&self, connection: &StorageConnection) -> anyhow::Result<()> {
+        if cfg!(feature = "postgres") {
+            sql!(
+                connection,
+                r#"
+                    ALTER TYPE key_type ADD VALUE IF NOT EXISTS 'ASSIGN_REQUISITION_NUMBER_PROCESSOR_CURSOR';
```
Comment (roxy-dao) [inline server/repository/src/migrations/v2_06_03/remove_non_custom_standard_reports.rs:16]: Assign requisition number processor cursor...? Isn't this a 2.6.2 migration...?

File: standard_forms/generated/standard_forms.json [hunk 2]
```diff
@@ -12,21 +12,21 @@
             "query.graphql"
           ],
           "convert_data": null,
-          "custom_wasm_function": null
+          "convert_data_type": "Extism"
```
Comment (roxy-dao) [inline standard_forms/generated/standard_forms.json:15]: Are we not removing it extism for standard reports? 👀

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks Andrei~ Just have some q`s below!

File: server/repository/src/migrations/v2_06_03/remove_non_custom_standard_reports.rs (hunk 1 above)
Comment (andreievg) [reply server/repository/src/migrations/v2_06_03/remove_non_custom_standard_reports.rs]: Thank Roxy i really don't know what happened here, I should have checked PR more thoroughly sorry

File: standard_forms/generated/standard_forms.json (hunk 2 above)
Comment (andreievg) [reply standard_forms/generated/standard_forms.json:15]: This is is tricky, we will actually keep this variant of [ConvertDataType](https://github.com/msupply-foundation/open-msupply/blob/3c37126fd0958d2d9b83affb539bdf6a4e8de22a/server/service/src/report/definition.rs#L82-L86), even when we remove Extism, and this data type Serializes by default to "Extism", there is no effect here though since, since convert_data above is null. Maybe we should change the default to BoaJs on that data file in develop, but it doesn't hurt having it as Extism either for now:  https://github.com/msupply-foundation/open-msupply/blob/41d19ccfbb05cf411de1d653cf88c8c0a2226ce8/server/service/src/report/report_service.rs#L545-L547

**Comment by andreievg** [comment]
Thanks for review Roxy, I updated and re-reviewd

File: standard_reports/item-usage/latest/report-manifest.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 {
   "is_custom": false,
-  "version": "2.6.1",
+  "version": "2.6.2",
```
Comment (Chris-Petty) [inline standard_reports/item-usage/latest/report-manifest.json:3]: not .3 ?

File: standard_forms/generated/standard_forms.json (hunk 2 above)
Comment (roxy-dao) [reply standard_forms/generated/standard_forms.json:15]: Okiie should be fine, can you make an issue to default to BoAJs in develop~? Thanks, would be nice to have it default to the one we're actually using

File: server/repository/src/migrations/v2_06_03/remove_non_custom_standard_reports.rs [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+
+    // For non-transfer-related processing of requisitions
+    fn migrate(&self, connection: &StorageConnection) -> anyhow::Result<()> {
+        if cfg!(feature = "postgres") {
+            sql!(
+                connection,
+                r#"
+                    DELETE FROM changelog WHERE record_id IN 
+                    (SELECT id FROM report WHERE is_custom = false AND context = 'REPORT');
+                    DELETE FROM report WHERE is_custom = false AND context = 'REPORT';
```
Comment (roxy-dao) [inline server/repository/src/migrations/v2_06_03/remove_non_custom_standard_reports.rs:18]: Do you think we will get the same problem with custom reports if upgrading?

File: standard_reports/item-usage/latest/report-manifest.json (hunk 3 above)
Comment (andreievg) [reply standard_reports/item-usage/latest/report-manifest.json:3]: Nope, report don't follow app versioning they just get bumped up patch when they changed, or if there is backward compatibility break they get bumped up version to the minor of omSupply and previous version is split for backwards compatibility:

https://github.com/msupply-foundation/open-msupply/tree/develop/standard_reports#report-versioning

File: server/repository/src/migrations/v2_06_03/remove_non_custom_standard_reports.rs (hunk 4 above)
Comment (andreievg) [reply server/repository/src/migrations/v2_06_03/remove_non_custom_standard_reports.rs:18]: We could generate lots of sync traffic with custom reports, especially if we upsert a bundle that uses extism, but this should have been removed now, hopefully and report sync was only added in 2.6

File: standard_forms/generated/standard_forms.json (hunk 2 above)
Comment (andreievg) [reply standard_forms/generated/standard_forms.json:15]: https://github.com/msupply-foundation/open-msupply/issues/7328

**Review by roxy-dao — APPROVED** [review]
Thanks for the changes Andrei! LGTM~
