### PR TITLE
7950 When turning on the preference to track donor, the donor of existing stockline in OG doesn't sync to the corresponding stock line in omSupply

### LINKED ISSUE #7950: When turning on the preference to track donor, the donor of existing stockline in OG doesn't sync to the corresponding stock line in omSupply
## What went wrong? 😲
Because the Tracking donor preference in OG was activated, there were many stock lines with an donor_ID. After activating this preference on OMS central, the donor of existing stock lines in OG doesn't sync back to the corresponding stock line in OG. It will probably if I re-initialise the site but do we want to have to re-initialise the site if we turn this preference on.

In OG before I turn the preference on:

https://drive.google.com/file/d/1d1ROXiC7LFAEszP7pq6Y2znc8AGRP2j0/view?usp=sharing

 In OMS after I turn on the preference to track donor
https://drive.google.com/file/d/1dBE6q4REA95D39mb48xZemfKPrsFX6rO/view?usp=sharing

## Expected behaviour 🤔
Existing stocktake donor in OMS should probably be consistent with what is on OG. So either we accept to re-initialise the site when we activate this preference or we find a way to get the donor of the existing OG stock line if any. Saying that maybe will also need to the same with all transactions and stocktakes ?   

## How to Reproduce 🔨

Steps to reproduce the behaviour:
In OG have the `Allow tracking of received stock by donor`  in OG preferences.

Image

1. Go to OMS Central and in "Manage > Global Preferences" activate preference `Allow tracking of stock by donor`
2. Sync your remote to get the preference 
3. Sync again and check some stock lines to see if the donor in oms correspond to those in OG 
4. See error. The donor in OG doesn't show in OMS

## Your environment 🌱

- Open mSupply Version: v2.08RC4
- Legacy mSupply Central Server Version: 8.02.0

- Platform: Android

- Database type: SQLite

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #7950 

# 👩🏻‍💻 What does this PR do?

Migrates donor information from legacy sync buffer data (`item_line` entries) to existing stock lines that don't have `donor_link_id` set before v2.8 upgrade.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Verify that during v2.8 upgrade, existing stock lines get `donor_link_id` populated
- [ ] Go to OMS Central and in "Manage > Global Preferences" activate preference Allow tracking of stock by donor
- [ ] Sync your remote to get the preference
- [ ] Sync again and check some stock lines to see if the donor in oms correspond to those in OG

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/repository/src/db_diesel/mod.rs [hunk 1]
```diff
@@ -123,7 +123,7 @@ pub mod rnr_form_row;
 pub mod sensor;
 mod sensor_row;
 pub mod stock_line;
-mod stock_line_row;
+pub mod stock_line_row;
```
Comment (jmbrunskill) [inline server/repository/src/db_diesel/mod.rs:126]: Don't think you need this as there's a line 
`pub use stock_line_row::*;` right?
Can just refer to it as `crate::stock_line_row` or something like that?

That said i'm fine with this approach, I don't like the `pub use something::*` with IDE tools it's not needed and adds lot of lines of code...

**Review by jmbrunskill — DISMISSED** [review]
Can you fix tests, and remove the extra add column migration?
I'm also thinking we should probably do the same thing for invoice_line just incase...

**Comment by GeronimoJohn** [comment]
> Can you fix tests, and remove the extra add column migration? I'm also thinking we should probably do the same thing for invoice_line just incase...

Thanks for the review @jmbrunskill, please see changes here: https://github.com/msupply-foundation/open-msupply/pull/8041/commits/76055b5ec521d104386540f383765cb408a8ebe8
