### PR TITLE
3994 Don't display foreign currency total if foreign currency id is the same as home currency

### LINKED ISSUE #3994: Don't display foreign currency total if foreign currency id is the same as home currency
## What went wrong? 😲
Foreign currency total is still being displayed even if it is the home currency

## Expected behaviour 🤔
Should only be displaying foreign currency total if the currency_id on invoice is actually a foreign currency

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create some invoices in OG
2. Move store to OMS
3. Initialise or Sync
4. Go to the invoices created
5. See the foreign currency total is there even if its home currency

## Your environment 🌱

- Open mSupply Version: 2.1.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3994

# 👩🏻‍💻 What does this PR do?
Use '-' instead of foreign currency total in invoice if the foreign currency is home currency, also noticed that the rates were showing up as 0 in older invoices, so have handled that as well 👀 .... 
Screenshot 2024-06-26 at 8 20 34 AM

# 🧪 Testing

- [ ] Have `issue in foreign currency` store pref on
- [ ] Create an invoice for an external customer/supplier
- [ ] Add some lines with sell price
- [ ] See `-` for foreign currency total
- [ ] Change currency
- [ ] See total

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Screenshots with foreign currency 
  2.

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx [hunk 1]
```diff
@@ -165,14 +166,16 @@ export const PricingSectionComponent = () => {
...
+          <PanelField>{currencyRate === 0 ? 1 : currencyRate}</PanelField>
         </PanelRow>
         <PanelRow>
           <PanelLabel>{t('heading.total')}</PanelLabel>
           <PanelField>
-            {foreignCurrency(
-              pricing.foreignCurrencyTotalAfterTax ?? 0
-            ).format()}
+            {isHomeCurrency
+              ? '-'
```
Comment (mark-prins) [inline client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx:175]: side thought: this has been used in a number of places and I wonder if we should create a global const for `UNDEFINED_STRING_VALUE` or similar?

**Review by mark-prins — APPROVED** [review]
🚢  lovely - thanks Roxy!

File: client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx]: wasn't sure where to put it... so just created a file under common -> utils
