### PR TITLE
Demographic UI updates

### LINKED ISSUE #4075: GAPS: Demographics UI tweaks
## What went wrong? 😲

Few tweaks: 

- [x] Change column order to: `Name`, `Percentage`, `Population`
- [x] Add `%` sign after values in `Percentage` column
- [x] Right align values in Growth columns
- [x] Change label to `Growth on previous year` (i.e. drop the %)
- [x] Add `%` sign after values in Growth columns
- [x] Right align `Growth on previous year` 
- [x] Change label from `Population` to `Current population`
- [x] Make table full width

## Expected behaviour 🤔

image

## How to Reproduce 🔨

Steps to reproduce the behaviour:

8. Click on '....'
9. Scroll down to '....'
10. See error

## Your environment 🌱

- Open mSupply Version: Develop 2.1.0
- Legacy mSupply Central Server Version: 2.0.0

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #4075

# 👩🏻‍💻 What does this PR do?

As per the issue, have done these changes
- [x] Change column order to: `Name`, `Percentage`, `Population`
- [x] Add `%` sign after values in `Percentage` column
- [x] Right align values in Growth columns
- [x] Change label to `Growth on previous year` (i.e. drop the %)
- [x] Add `%` sign after values in Growth columns
- [x] Right align `Growth on previous year` 
- [x] Change label from `Population` to `Current population`
- [x] Make table full width

And an additional thing that I noticed:
- [x] Removed sorting from all columns except `name` ( this is the only sort option in the API )
- [ ] Fixed the sorting of the `name` column - the change of direction wasn't working

image

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Check the list of items above

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

**Review by jmbrunskill — APPROVED** [review]
Looks good to me, but sorting is still not working for me on Name.
I think even if the backend was being called (which for some reason it doesn't appear to be), we'll still have issues with unsaved rows.
We probably either need to move all the sorting to the frontend, or just a quick fix option to remove sorting for name too.

I also noticed that we'd lost the ability to enter decimal growth rates, I've pushed a fix for that to your branch.

File: client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx [hunk 1]
```diff
@@ -95,18 +98,27 @@ export const GrowthRow = <T extends RecordWithId>({
...
-                        }
+                      <NumericTextInput
+                        value={columnHeader.value ?? 0}
+                        decimalLimit={2}
+                        decimalMin={1}
+                        InputProps={{
+                          endAdornment: (
+                            <InputAdornment position="end">%</InputAdornment>
+                          ),
+                        }}
```
Comment (lache-melvin) [inline client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx:114]:
```suggestion
                        InputProps={{
                          inputProps: { sx: { padding: '2px 0' } },
                          endAdornment: (
                            <InputAdornment position="end">%</InputAdornment>
                          ),
                        }}
```

nit: adding padding something like this will make the input value and the `%` sign line up vertically 😅

**Comment by lache-melvin** [comment]
Can't enter negative growth values now - turns out this wasn't supported by the numeric text input yet! Made a suggestion branch here: https://github.com/msupply-foundation/open-msupply/compare/4075-demographic-ui...4075-demographic-ui(growth-input-fixes)

Also adds a buffer state so we can backspace the value completely 👀
