### PR TITLE
fix: add debounce to units-received input to prevent premature roundi…

### LINKED ISSUE #10683: In inbound shipments when editing the number of units, the value is changed to a multiple of the pack size even before I finish to put my whole.
## What went wrong? 😲
For example, if I have a packsize of 5 units and and I try to edit the Total qty of units received to 125, after I type the 1 it is changed to 5, my 2 is also changed to 5 and the 5 stay the same, so my final number is 555 instead of 125. Sometimes it is working correctly when I type very fast but most of the time it is not. 

https://github.com/user-attachments/assets/1159c842-753e-4d19-9153-a79ffba0a5c1

Same thing in prescription

https://github.com/user-attachments/assets/9aaa583d-2ed8-4bbc-8faa-21ba6c595d96

## Expected behaviour 🤔
The qty I typed should not be changed until I finished or there should no be any validation until I click OK (the total qty can be changed then with the alert explaining why the qty was changed)

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Choose an item that has a default pack size that is not one.
1. Go to 'Replenishment > Inbound Shipment', open an inbound shipment
2. Click on 'Add item' and add the item you have chosen
3. Put a shipped qty, a received pack size, and a receive pack qty
4. The total number of units is automatically calculated.
5. Now change the total number of units and make sure that first digit you put is not a multiple of the default pack size of your item. eg if your default pack size is 5, have your first digit be 1 or 2 or 3, etc but not 5
6. See error

## Your environment 🌱

- Open mSupply Version: 2.16.00-RC-02260440
- Legacy mSupply Central Server Version: v8.08

- Platform: All

- Database type: SQlite

## Additonial Notes

Found while testing #10580. I was tempted to put Hotfix but I settled for high severity because you can change the number of pack instead of changing the total of units but it would be good that this is fix relatively quickly.

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #10683

# 👩🏻‍💻 What does this PR do?

When editing "Total qty of units" in inbound shipment line edit, the `NumberInputCell`'s `updateFn` rounds to the nearest pack-size multiple and writes the result back to the input buffer on every keystroke (`debounceTime=0`). Typing "125" with pack size 5: `1→5`, `52→55`, `555→555` — user gets 555 instead of 125.

Added `debounceTime={300}` to the units-received `NumberInputCell`. The rounding now fires only after 300ms of inactivity, letting the user finish typing before pack-size adjustment occurs.

```diff
 <NumberInputCell
   cell={cell}
+  debounceTime={300}
   updateFn={(value: number) => {
```

This prop is already supported by `NumberInputCell` and used elsewhere (`RequiredNumberInputCell`: 250ms, `AutoAllocateField`: 1000ms).

**How this surfaced:** PR #10617 added an `isDirty` guard preventing background refetches from resetting draft state. Before that fix, refetches may have been masking the immediate-rounding behavior.

## 💌 Any notes for the reviewer?

Single-line change. The `return actualUnits` in `updateFn` is still needed for the edge case documented in `NumberInputCell` (repeated inputs rounding to the same external value).

# 🧪 Testing

- [ ] Open an inbound shipment, add an item with default pack size ≠ 1 (e.g. 5)
- [ ] Edit the "units received" field — type a multi-digit number where the first digit is not a multiple of pack size (e.g. 125)
- [ ] Verify the input retains typed value during typing and only rounds after a brief pause
- [ ] Verify the rounding message appears correctly for non-multiples (e.g. typing 127 → rounds to 130)
- [ ] Verify editing "packs received" still updates immediately (no debounce on that column)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**:
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

<details>

<summary>Original prompt</summary>

> 
> ----
> 
> *This section details on the original issue you should resolve*
> 
> <issue_title>In inbound shipments when editing the number of units, the value is changed to a multiple of the pack size even before I finish to put my whole.</issue_title>
> <issue_description>## What went wrong? 😲
> For example, if I have a packsize of 5 units and and I try to edit the Total qty of units received to 125, after I type the 1 it is changed to 5, my 2 is also changed to 5 and the 5 stay the same, so my final number is 555 instead of 125. Sometimes it is working correctly when I type very fast but most of the time it is not. 
> 
> https://github.com/user-attachments/assets/1159c842-753e-4d19-9153-a79ffba0a5c1
> 
> 
> 
> ## Expected behaviour 🤔
> The qty I typed should not be changed until I finished or there should no be any validation until I click OK (the total qty can be changed then with the alert explaining why the qty was changed)
> 
> ## How to Reproduce 🔨
> 
> Steps to reproduce the behaviour:
> Choose an item that has a default pack size that is not one.
> 1. Go to 'Replenishment > Inbound Shipment', open an inbound shipment
> 2. Click on 'Add item' and add the item you have chosen
> 3. Put a shipped qty, a received pack size, and a receive pack qty
> 4. The total number of units is automatically calculated.
> 5. Now change the total number of units and make sure that first digit you put is not a multiple of the default pack size of your item. eg if your default pack size is 5, have your first digit be 1 or 2 or 3, etc but not 5
> 6. See error
> 
> 
> ## Your environment 🌱
> 
> 
> 
> - Open mSupply Version: 2.16.00-RC-02260440
> - Legacy mSupply Central Server Version: v8.08
> 
> - Platform: All
> 
> - Database type: SQlite
> 
> ## Additonial Notes
> 
> Found while testing msupply-foundation/open-msupply#10580. I was tempted to put Hotfix but I settled for high severity because you can change the number of pack instead of changing the total of units but it would be good that this is fix relatively quickly.
> 
> </issue_description>
> 
> <agent_instructions>Fix this bug please, also have a look at how this bug developed</agent_instructions>
> 
> ## Comments on the Issue (you are @copilot in this section)
> 
> <comments>
> </comments>
> 

</details>

- Fixes msupply-foundation/open-msupply#10683

---

🔒 GitHub Advanced Security automatically protects Copilot coding agent pull requests. You can protect all pull requests by enabling Advanced Security for your repositories. [Learn more about Advanced Security.](https://gh.io/cca-advanced-security)

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx [hunk 1]
```diff
@@ -271,6 +271,7 @@ export const QuantityTable = ({
         Cell: ({ row, cell }) => (
           <NumberInputCell
             cell={cell}
+            debounceTime={300}
```
Comment (CarlosNZ) [inline client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx]: I'd be inclined to increase this to 500ms, still feels a little tight for me, and not everyone types quickly.
