### PR TITLE
4013 Ignore orphaned master list lines

### LINKED ISSUE #4013: Ignore orphaned master list lines
## What went wrong? 😲
Orphaned master list lines are getting sent from OG -> OMS for integrating and error since the master list is missing.

## Expected behaviour 🤔
Shouldn't error. Should ignore these records

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4013

# 👩🏻‍💻 What does this PR do?
Ignore orphaned master list lines

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] _(e.g.)_ Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] _(e.g.)_ This sample datafile: _google drive link_
- [ ] _(e.g.)_ Open a requisition with some lines
- [ ] _(e.g.)_ Make a couple invoices supplying some amount of those lines
- [ ] _(e.g.)_ Review that "issued" column is the sum of the amount already issued in invoices for this requisition

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/service/src/sync/translations/master_list_line.rs [hunk 1]
```diff
@@ -71,7 +82,7 @@ mod tests {
         let translator = MasterListLineTranslation {};
 
         let (_, connection, _, _) =
-            setup_all("test_master_list_line_translation", MockDataInserts::none()).await;
+            setup_all("test_master_list_line_translation", MockDataInserts::all()).await;
```
Comment (roxy-dao) [inline server/service/src/sync/translations/master_list_line.rs:85]: With new none check... the master list line will always be ignored cause there are no master lists in the mock database...

File: client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts [hunk 2]
```diff
@@ -185,7 +185,7 @@ const getColumnLookup = <T extends RecordWithId>(): Record<
   code: {
     label: 'label.code',
     key: 'code',
-    width: 20,
+    width: 100,
```
Comment (clemens-msupply) [inline client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts:188]: Unrelated change?

File: server/graphql/general/src/queries/tests/names.rs [hunk 3]
```diff
@@ -185,6 +185,7 @@ mod graphql {
                 email,
                 is_patient: _,
                 is_donor,
+                code_or_name: _,
```
Comment (clemens-msupply) [inline server/graphql/general/src/queries/tests/names.rs:188]: Unrelated change?

File: server/service/src/sync/translations/master_list_line.rs [hunk 4]
```diff
@@ -38,18 +41,26 @@ impl SyncTranslation for MasterListLineTranslation {
...
-        _: &StorageConnection,
+        connection: &StorageConnection,
         sync_record: &SyncBufferRow,
     ) -> Result<PullTranslateResult, anyhow::Error> {
         let data = serde_json::from_str::<LegacyListMasterLineRow>(&sync_record.data)?;
+        let master_list =
+            MasterListRowRepository::new(connection).find_one_by_id(&data.item_master_ID)?;
+
+        if master_list.is_none() {
+            return Ok(PullTranslateResult::Ignored("Orphaned line".to_string()));
```
Comment (clemens-msupply) [inline server/service/src/sync/translations/master_list_line.rs:61]: Maybe saying "Missing master list" is more clear?

Nit: remove empty line...

File: server/service/src/sync/translations/master_list_line.rs (hunk 1 above)
Comment (clemens-msupply) [reply server/service/src/sync/translations/master_list_line.rs:85]: Could you please add a comment on why all() is needed? i.e. that test_data::test_pull_upsert_records() requires a master_list from the mock data.

Could you also please add a test for the new `Ignored` case?

**Review by clemens-msupply — CHANGES_REQUESTED** [review]

File: client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts (hunk 2 above)
Comment (roxy-dao) [reply client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts:188]: Oh yup sorry.

File: server/service/src/sync/translations/master_list_line.rs (hunk 4 above)
Comment (roxy-dao) [reply server/service/src/sync/translations/master_list_line.rs:61]: What empty line? 🤔

Comment (clemens-msupply) [reply server/service/src/sync/translations/master_list_line.rs:61]: the empty line just before `if master_list.is_none() {` The previous statement is only used in the if statement. Think its nicer to have them close together, with the extra line it looks like they don't belong together...

**Review by clemens-msupply — APPROVED** [review]
Looks good, thank you!
