### PR TITLE
5713 empty inbound shipment sent to oms site

### LINKED ISSUE #5713: Empty Inbound Shipment sent to OMS site
## What went wrong? 😲

Found while testing [THIS](https://github.com/msupply-foundation/msupply/issues/15668)
empty Inbound shipment is sent to Oms remote site from mSupply remote site.
Photos [HERE](https://drive.google.com/drive/folders/10bKO1QM4AuscWPd7QYmbLXPVlM-OHjeS)

## Expected behaviour 🤔
Inbound shipment should have transaction lines

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Setup mirror sync 
2. Create a customer invoice from mSupply remote site and finalize it
3. Check in Inbound shipment of receiving OMS site
4. Open the Inbound shipment (OMS remote site in android) and see no lines received (error) 
5. Same happening while creating supplier credit from mSupply site to customer return in the oms remote site
6. Looks good when sending transaction from the mirror cloud store

## Your environment 🌱

- Open mSupply Version:` V2.4.0`
- Legacy mSupply Central Server Version: `V7.19.00rc5`

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #5713

# 👩🏻‍💻 What does this PR do?
Fixes stock line 
Not sure if this fixes it... but added a test and it seems fine? 

# 🧪 Testing

- [ ] _(e.g.)_ Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] _(e.g.)_ This sample datafile: _google drive link_
- [ ] _(e.g.)_ Open a requisition with some lines
- [ ] _(e.g.)_ Make a couple invoices supplying some amount of those lines
- [ ] _(e.g.)_ Review that "issued" column is the sum of the amount already issued in invoices for this requisition

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/sync/translations/invoice_line.rs [hunk 1]
```diff
@@ -219,12 +219,11 @@ impl SyncTranslation for InvoiceLineTranslation {
         // TODO: remove the stock_line_is_valid check once central server does not generate the inbound shipment
         // omSupply should be generating the inbound, with valid stock lines.
         // Currently a uuid is assigned by central for the stock_line id which causes a foreign key constraint violation
-        let is_stock_line_valid = match stock_line_id {
-            Some(ref stock_line_id) => StockLineRowRepository::new(connection)
-                .find_one_by_id(stock_line_id)?
-                .is_some(),
-            None => true,
-        };
+        let is_stock_line_valid = stock_line_id.as_ref().is_some_and(|stock_line_id| {
```
Comment (Chris-Petty) [inline server/service/src/sync/translations/invoice_line.rs:222]: Will the `is_some_and` fn call return false if `None`, not integrating records if there is no ID?

The first workflow that I think would break for this is that if you are reinitialising a site that that has some amount of "New" inbound shipments with lines. No stock affected yet, so no stock_lines relating to the invoice_lines.

**Review by Chris-Petty — CHANGES_REQUESTED** [review]

File: server/service/src/sync/translations/invoice_line.rs (hunk 1 above)
Comment (roxy-dao) [reply server/service/src/sync/translations/invoice_line.rs:222]: Yes, that's what I understood from the docs. There's code below that saves None for stock line if not valid... do you think it will still break?

```js
       let stock_line_id = if is_record_active_on_site && is_stock_line_valid {
            stock_line_id
        } else {
            None
        };
```

Comment (Chris-Petty) [reply server/service/src/sync/translations/invoice_line.rs:222]: nah yea that's fine 👍

**Review by Chris-Petty — APPROVED** [review]
