### PR TITLE
6069 fix suggested quantities replacing requested quantities - internal order

### LINKED ISSUE #6069: On internal order using the "Use suggested quantities" button will erase all previously requested quantities you have put in
## What went wrong? 😲

as title. I am not sure if it is a bug as usually you would use the "Use suggested quantities"  and then add your other quantities but sometimes somebody can put his quantities that have 0 suggested quantity first and then press the button and then everything he put in the requested quantity will be replaced by the suggested quantity.

## Expected behaviour 🤔
I am not sure but I do think that it would be better that when you click the button, you would use the suggested quantity only for lines that have a requested quantity of 0 and leave those that already have a requested quantity as they are.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an internal order
2. Add some requested quantity
3. Click on the button "Use suggested quantities"
4. All the requested quantity you have put in have been replaced by the suggested quantity even the suggested quantity was 0 

## Your environment 🌱

- Open mSupply Version: v2.5.0RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #6069 

# 👩🏻‍💻 What does this PR do?
Update suggested quantitiy button to only update requested quantities with suggested quantities if requested quantity value is 0

Screenshot 2025-03-06 at 17 22 06

## 💌 Any notes for the reviewer?

I couldn't find anything that states that response requisitions has the same functionality of using suggested quantities to update requested quantity. If I'm wrong in how I've understood it, then happy to find and make the change in this PR.

# 🧪 Testing

- [ ] Create an internal order
- [ ] Add some requested quantity
- [ ] Click on the button "Use suggested quantities"
- [ ] See updated confirmation message
- [ ] See that only lines with requested quantity of 0 being updated by suggested quantity

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/host/src/components/Sync/SyncModal.tsx [hunk 1]
```diff
@@ -213,9 +213,9 @@ const FormattedSyncDate = ({ date }: { date: Date | null }) => {
 
   if (!date) return UNDEFINED_STRING_VALUE;
 
-  const relativeTime = `( ${t('messages.ago', {
+  const relativeTime = `(${t('messages.ago', {
     time: localisedDistanceToNow(date),
-  })} )`;
+  })})`;
```
Comment (noel-yeldos) [inline client/packages/host/src/components/Sync/SyncModal.tsx:219]: Just a sidequest for QA, not related to issue.

File: client/packages/common/src/intl/locales/en/common.json [hunk 2]
```diff
@@ -1610,7 +1610,7 @@
   "messages.reduced-to-zero_other": "Reduced {{ count }} lines to quantity of 0",
   "messages.regenerate-id-confirm": "This will create a new ID and cannot be undone.",
   "messages.repack-log-info": "Repacked from stock line",
-  "messages.requested-to-suggested": "This will set all lines requested quantity to the suggested quantity.",
+  "messages.requested-to-suggested": "This will set requested quantity to the suggested quantity for lines where requested quantity is 0.",
```
Comment (noel-yeldos) [inline client/packages/common/src/intl/locales/en/common.json:1613]: Updated to match functionality

**Review by roxy-dao — APPROVED** [review]
Thanks LGTM~
