### PR TITLE
4010 Repack New Location showing as old Location (new shows blank)

### LINKED ISSUE #4010: Repack `New Location` showing as old `Location` (new shows blank)
## What went wrong? 😲

When looking at a historic repack, it shows the updated location on the left with the "original data", and shows nothing for the "new location":

https://github.com/msupply-foundation/open-msupply/assets/55115239/8b52a08f-49b2-4f7b-931b-8331b6a5ebf2

i.e. Why are these different?

Editing:
Screenshot 2024-05-28 at 9 53 31 AM

Saved:
Screenshot 2024-05-28 at 9 53 39 AM

## Expected behaviour 🤔

Old location on the left, new location on the right
**Triage comment** not sure if we have the old location, or if it is easily attainable. Populate if it is available, but we are fine if only the new location is displayed on the right.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a stock line
2. Create a repack, and move that new stock to a new location
3. Save
4. View your repack line
5. BUG: See your inputted new location on the left, and empty `New location` field on the right

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version:

- Platform: Browser

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4010

# 👩🏻‍💻 What does this PR do?
Correctly display old/new locations for repacks. Have opted to use text to display the new location so it's consistent with the component next to it...

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Have a stock line in a location
- [ ] Click on Stock -> Line -> Repack
- [ ] Change the location of the repack
- [ ] Click on the repack in the list view 
- [ ] See that old/new location are correctly displayed

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Location/Components/LocationSearchInput.tsx [hunk 1]
```diff
@@ -104,6 +104,7 @@ export const LocationSearchInput: FC<LocationSearchInputProps> = ({
       noOptionsText={t('messages.no-locations')}
       renderOption={optionRenderer}
       getOptionLabel={getOptionLabel}
+      isOptionEqualToValue={(option, value) => option.value === value?.value}
```
Comment (roxy-dao) [inline client/packages/system/src/Location/Components/LocationSearchInput.tsx:107]: Side quest: Fix console warning

File: client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx [hunk 2]
```diff
@@ -29,7 +29,7 @@ export const RepackEditForm: FC<RepackEditFormProps> = ({
 }) => {
   const t = useTranslation('inventory');
   const [location, setLocation] = useState<LocationRowFragment | null>(null);
-  const textProps = { textAlign: 'end' as 'end' | 'start', paddingRight: 3 };
+  const textProps = { textAlign: 'end' as 'end' | 'start' };
```
Comment (roxy-dao) [inline client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx:32]: Padding made the text unaligned with input

File: client/packages/system/src/Stock/Components/Repack/RepackModal.tsx [hunk 3]
```diff
@@ -149,11 +150,11 @@ export const RepackModal: FC<RepackModalControlProps> = ({
               const result = await onInsert();
               const errorMessage = mapStructuredErrors(result);
 
-              // The new stockline is the second of two lines in the resulting
+              // The new stockline is the first of two lines in the resulting
               // invoice
               const newLineId =
                 result.__typename === 'InvoiceNode'
-                  ? result?.lines?.nodes?.[1]?.stockLine?.id ?? ''
+                  ? result?.lines?.nodes?.[0]?.stockLine?.id ?? ''
```
Comment (roxy-dao) [inline client/packages/system/src/Stock/Components/Repack/RepackModal.tsx:157]: Side quest: Redirection wasn't working because the new line is the first line

File: client/packages/system/src/Stock/DetailView/DetailView.tsx [hunk 4]
```diff
@@ -41,7 +41,7 @@ export const StockLineDetailView: React.FC = () => {
   } = useUrlQuery();
   const { success, error } = useNotification();
   const t = useTranslation('inventory');
-  const { navigateUpOne } = useBreadcrumbs();
+  const { setCustomBreadcrumbs, navigateUpOne } = useBreadcrumbs();
```
Comment (roxy-dao) [inline client/packages/system/src/Stock/DetailView/DetailView.tsx:44]: Side quest: Somehow missed this during the big problematic issue 👀

File: client/packages/system/src/Stock/Components/Repack/RepackModal.tsx [hunk 5]
```diff
@@ -122,15 +122,16 @@ export const RepackModal: FC<RepackModalControlProps> = ({
...
-    const { numberOfPacks, packSize } = repackData.from;
+    const { numberOfPacks, packSize, location: oldLocation } = repackData.from;
     const { packSize: newPackSize, location } = repackData.to;
     return {
       stockLineId: stockLine.id,
       numberOfPacks,
       packSize,
       newPackSize,
-      locationName: location?.name,
+      locationName: oldLocation ? oldLocation.name : location?.name,
```
Comment (andreievg) [inline client/packages/system/src/Stock/Components/Repack/RepackModal.tsx:132]: this would show old location as new location even if old location was not set, Would it be ok to just map from.location to locationName and new to.location to newLocationName ?

File: client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx [hunk 6]
```diff
@@ -117,24 +117,33 @@ export const RepackEditForm: FC<RepackEditFormProps> = ({
...
-                onChange={location => {
-                  setLocation(location);
-                  onChange({
-                    newLocationId: location?.id,
-                  });
-                }}
-              />
-            }
-          />
+          {data.newLocationName ? (
```
Comment (andreievg) [inline client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx:120]: If new location was not set, we still show not editable drop down ?

Comment (roxy-dao) [reply client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx:120]: It shows as { code } - { name } and would need tooltip on hover... which was different from how we were showing old location...

**Comment by roxy-dao** [comment]
> Thanks for the changes Roxy, looks great. There is one thing you may want to look at, if the location is not set on a new repack or if there was not location of stock line when repack was done.
> 
> Looks good any ways, happy to merge. Thanks for fixing other issues too

If no location of stock line when repack was done then it shows with our undefined_string `-`and will now show the same if repack is finalised and there is no new location (:

**Comment by andreievg** [comment]
Thanks for changes @roxy-dao
