### PR TITLE
7254 generate typescript types for plugins

### LINKED ISSUE #7254: When running cargo test backend plugin typescript files show up in git changes
## What went wrong? 😲

At some point there was prettier re-format of every .ts file, this included files generated for backend plugins, from rust structs, [using ts-rs](https://github.com/msupply-foundation/open-msupply/blob/98b80b3bf57e87ee199ac74b5f4bbe0d82d8ed2e/server/service/src/backend_plugin/types/mod.rs#L34-L38). When we run tests now the plugin types are re-exported but not formatted, causing a diff

## Expected behaviour 🤔

Move plugin type generation to cli, add prettier command to re-format them after export

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #7254 

# 👩🏻‍💻 What does this PR do?

Move plugin type generation to its own CLI command, and run prettier to format the generated files 

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [x] on open terminal for OMS
- [x] cd or move into `server` directory
- [x] run command `cargo run --bin remote_server_cli -- generate-type-script-types`
- [x] should automatically generate types for plugins (if there are any new ones)
- [x] should automatically format generated types (if there are any to format)
- [x] running `cargo test` shouldn't generate any plugin types

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [x] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [x] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [x] Postgres
- [x] SQLite
- [x] Frontend

### CODE REVIEW

File: server/cli/src/generate_typescript_types.rs [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+    >,
+    graphql_query: Function<graphql_query::Input, graphql_query::Output>,
+    // Extra types to expose, not directly related to plugin interface
+    // like for input or output of global methods
+    get_store_preferences: StorePreferenceRow,
+    get_plugin_data: Function<PluginDataFilter, Vec<PluginDataRow>>,
+}
+
+pub fn generate_typescript_types() -> Result<()> {
+    println!("Running test to generate TypeScript types...");
```
Comment (fergie-nz) [inline server/cli/src/generate_typescript_types.rs:31]: I think should be `info!` flag?

File: server/cli/src/generate_typescript_types.rs [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+            "--",
+            "--ignored",
+            "--nocapture",
+        ])
+        .status()
+        .map_err(|e| anyhow!("Failed to run test: {}", e))?;
+
+    if !generate_result.success() {
+        return Err(anyhow!("TypeScript type generation failed"));
+    }
```
Comment (fergie-nz) [inline server/cli/src/generate_typescript_types.rs:47]: Hey John, I think you'll never reach this error on !generate_result.success() because you will already exit the function above using the '?' operator to escape the function

File: server/service/src/backend_plugin/types/mod.rs [hunk 3]
```diff
@@ -1,38 +1,3 @@
 pub mod amc;
 pub mod graphql_query;
 pub mod transform_request_requisition_lines;
```
Comment (andreievg) [inline server/service/src/backend_plugin/types/mod.rs:3]: @GeronimoJohn, I think the types should live closer together.

I would make export_plugin_typescript() `pub` and use it in cli (less code changes too)

File: server/cli/src/generate_typescript_types.rs [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+
+    let prettier_verbose = Command::new("npx")
```
Comment (andreievg) [inline server/cli/src/generate_typescript_types.rs:49]: sorry this is not documented anywhere but I've been using the wrapper "run_command_with_error"

**Review by andreievg — DISMISSED** [review]
Looks good, a couple of change requests please

File: server/cli/src/generate_typescript_types.rs (hunk 1 above)
Comment (GeronimoJohn) [reply server/cli/src/generate_typescript_types.rs]: Thanks Ferg, applied in https://github.com/msupply-foundation/open-msupply/pull/7358/commits/10905fdbb53faaec75e4b0b266b84124945df538

**Review by zachariah-at-msupply — APPROVED** [review]
All seems well! Lovely job.
L
G
T
M
!
(...I have waited so long to say that 😁)

**Comment by andreievg** [comment]
@GeronimoJohn, i can't quite see your changes when looking at 'changes' of this PR, sorry not sure what this one is:

Screenshot 2025-04-29 at 2 55 35 PM

Also it's for v2.7.0-RC, should be develop now, thanks

**Comment by andreievg** [comment]
@GeronimoJohn would be great if you add the commit from the requested changes to this branch please

**Review by andreievg — APPROVED** [review]
Thanks changes look great, sorry for the confusion.
