### PR TITLE
Use invoice status to adjustStockLines

### LINKED ISSUE #4936: Available can be bigger then total in outbound line edit
## What went wrong? 😲

Available can show higher then total in picked outbound shipment line edit

## Expected behaviour 🤔

Total should never be lower then available.

## How to Reproduce 🔨

Create new outbound, issue some stock, change status to picked, see that total is lower then available in outbound line edit.

## Agreed solution

Adjust total + number of packs issued for picked outbound lines.

Related:
https://github.com/msupply-foundation/open-msupply/pull/4911
https://github.com/msupply-foundation/open-msupply/issues/3252

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #4936 

# 👩🏻‍💻 What does this PR do?

Changes the code for creating draftStockOutLines to decide when to adjust stock levels based on 

Logic should be

Available Stock show is the total of the available stock in store (e.g total stock - allocated to other invoices) plus the amount  you have allocated or picked on this invoice line.
Total stock (in store) is also adjusted to include what you have allocated to this line too, once the invoice is in the picked state.

This is because by updating that line you can adjust the total stock and or available stock levels, so we need to show the adjusted stock levels to avoid confusion about how much you can or can't allocate to the invoice.

## 💌 Any notes for the reviewer?

Any status things I'm missing?
Is there some kind of magic logic from before that I've missed?

# 🧪 Testing

- [ ] Create an outbound shipment
- [ ] Try editing lines, saving, re-opening, etc, check that the available stock is always less than total stock (in store)
- [ ] Update status e.g allocated, repeat earlier tests
- [ ] Update status to Picked, repeat earlier tests
- [ ] Do the same but with prescriptions (these are affected by this change too)

# 📃 Documentation
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
Is there some documentation on this that needs to be updated?

### CODE REVIEW

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx [hunk 1]
```diff
@@ -73,11 +73,12 @@ export const useDraftOutboundLines = (
           const invoiceLine = lines?.find(
             ({ stockLine }) => stockLine?.id === batch.id
           );
-
           if (invoiceLine) {
             return createDraftStockOutLine({
               invoiceLine,
+              stockLine: batch,
```
Comment (jmbrunskill) [inline client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx:79]: Wasn't 100% if this should be passed in or not, I think it wasn't included before to try to trigger the adjustment logic but there might have been another reason I'm not aware of too?

File: client/packages/invoices/src/StockOut/hooks/usePackSizeController.test.tsx [hunk 2]
```diff
@@ -37,6 +38,7 @@ const testLine = ({
 }: TestLineParams): DraftStockOutLine =>
   createDraftStockOutLine({
     invoiceId: '',
+    invoiceStatus: InvoiceNodeStatus.New,
```
Comment (jmbrunskill) [inline client/packages/invoices/src/StockOut/hooks/usePackSizeController.test.tsx:41]: Didn't look at these tests but they do seem to pass with `New` so I left it as New for now

File: client/packages/invoices/src/StockOut/utils.tsx [hunk 3]
```diff
@@ -93,28 +93,43 @@ export const createDraftStockOutLineFromStockLine = ({
...
-});
+  invoiceStatus,
+}: DraftStockOutLineSeeds): DraftStockOutLine => {
+  // When creating a draft stock out line from an invoice line we may need to adjust the available and total number of packs
+  // This is because, once an invoice line is created and it is in the allocated state, the available number of packs is reduced by the number of packs in the invoice line
+  // After it is in picked status, the total number of packs is also reduced by the number of packs in the invoice line
+  // Other statuses such as Shipped shouldn't show the stock line as available, so we don't need to adjust the available number of packs
+  // If the invoice is New, no adjustments are needed, as the stockLines shouldn't be updated yet
+
+  const adjustAvailableNumberOfPacks =
```
Comment (andreievg) [inline client/packages/invoices/src/StockOut/utils.tsx:104]: I am pretty sure we adjustAvailableNumberOfPacks for all invoice statuses

File: client/packages/invoices/src/StockOut/utils.tsx [hunk 4]
```diff
@@ -93,28 +93,43 @@ export const createDraftStockOutLineFromStockLine = ({
 export const createDraftStockOutLine = ({
   invoiceLine,
   stockLine,
```
Comment (andreievg) [inline client/packages/invoices/src/StockOut/utils.tsx:95]: Wouldn't invoiceLine always have stockLine ?

**Review by andreievg — CHANGES_REQUESTED** [review]
Thanks James, only request is for the availableNumberOfPacks to be adjusted in all invoice statuses

File: client/packages/invoices/src/StockOut/utils.tsx (hunk 3 above)
Comment (jmbrunskill) [reply client/packages/invoices/src/StockOut/utils.tsx:104]: apart from new right? Then the lines don't actually exist. Although I think we don't call this code when the invoice is new... We call the draftFromStockLIne one instead...

File: client/packages/invoices/src/StockOut/utils.tsx (hunk 4 above)
Comment (jmbrunskill) [reply client/packages/invoices/src/StockOut/utils.tsx:95]: Yeah I'm a little confused by the reasoning for this being passed as well, as the `invoice.stockLine` which should already exist...
Maybe better to remove it to remove any confusion...

File: client/packages/invoices/src/StockOut/utils.tsx (hunk 3 above)
Comment (jmbrunskill) [reply client/packages/invoices/src/StockOut/utils.tsx:104]: What do we want to do with Shipped for example I'm ok with always adjusting I'm just not sure if adjusting really makes sense...

File: client/packages/invoices/src/StockOut/utils.tsx (hunk 4 above)
Comment (jmbrunskill) [reply client/packages/invoices/src/StockOut/utils.tsx:95]: Was scared to remove it and find somewhere it was needed but missed in testing.
That being said it feels like it's unnecessary, maybe some state thing when only one of the queries is refreshed but even then it's the invoice one that should matter right?

Comment (andreievg) [reply client/packages/invoices/src/StockOut/utils.tsx:95]: Yeah could be true, I am ok to keep, especially since we will be refactoring this area

File: client/packages/invoices/src/StockOut/utils.tsx (hunk 3 above)
Comment (andreievg) [reply client/packages/invoices/src/StockOut/utils.tsx:104]: > apart from new right? Then the lines don't actually exist. Although I think we don't call this code when the invoice is new... We call the draftFromStockLIne one instead...

You can add and edit lines in new status.

>  I'm just not sure if adjusting really makes sense...

We've been following mSupply logic for this (even thought statuses are different, adjustment for available always happens)

**Review by andreievg — APPROVED** [review]
Thanks @jmbrunskill
