### PR TITLE
7273 always assign serial number

### LINKED ISSUE #7273: Open mSupply should assign requisition serial numbers for response requisitions (even when not attached to an internal order)
## What went wrong? 😲

For DHIS2 LMIS integration on mSupply Central Server we pull orders from DHIS2 and create response requisition for the supplying store. Then mSupply central server will force sync the requisition to the remote sites where the supplying store is.

This came from [a change in mSupply,](https://github.com/msupply-foundation/msupply/pull/15356) where mSupply was (I think incorrectly) setting the serial number for response requisitions, but when it was removed we did not check for other implications 

note that this doesn't have a linked request requisition

## Expected behaviour 🤔

The created requisition serial number in the central server is -1, once synced the remote sites should determine the available serial number and assign it.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Setup and configure DHIS2 LMIS
2. Create order in DHIS2
3. mSupply will pull the order and create requisition
4. sync
5. See error

Image

## Your environment 🌱

- Open mSupply Version: 2.6.1
- Legacy mSupply Central Server Version: V8.1.03
- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #7273

# 👩🏻‍💻 What does this PR do?

Always assign a serial number, to any response requisition coming from OG (serial number -1).

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Set up for DHIS2 integration
- [ ] Create an order
- [ ] OG will generate a response requisition and queue to force push it to your remote site
- [ ] Check OG requisition list for that store - see requisitions with serial number -1
- [ ] Sync remote site
- [ ] Check requisition list - the new requisitions have serial numbers assigned
- [ ] Sync again
- [ ] You now see the serial numbers in OG

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [x] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [x] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [x] Postgres
- [x] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/processors/assign_requisition_number/assign_requisition_number.rs [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+        let repo = RequisitionRowRepository::new(&ctx.connection);
+
+        let requisition =
+            repo.find_one_by_id(&changelog.record_id)?
+                .ok_or(ProcessorError::RecordNotFound(
+                    "Requisition".to_string(),
+                    changelog.record_id.clone(),
+                ))?;
+
+        // Only assign requisition number to response requisitions
```
Comment (Chris-Petty) [inline server/service/src/processors/assign_requisition_number/assign_requisition_number.rs:37]: Seriously having the comments where they're relevant rather than the big block at the top is much easier reading

File: server/service/src/processors/assign_requisition_number/assign_requisition_number.rs [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+
+    fn try_process_record(
+        &self,
+        ctx: &ServiceContext,
+        _service_provider: &ServiceProvider,
+        changelog: &ChangelogRow,
+    ) -> Result<Option<String>, ProcessorError> {
+        let repo = RequisitionRowRepository::new(&ctx.connection);
+
+        let requisition =
```
Comment (Chris-Petty) [inline server/service/src/processors/assign_requisition_number/assign_requisition_number.rs:30]: I think it is much more straightforward to follow just doing a query for the relevant records in the relevant methods like this. If it ends up duplicated (3 times rule of thumb...) then extract out a fn rather than having a bunch of hard to navigate (via LSP) shared logic somewhere else?

File: server/service/src/processors/assign_requisition_number/test.rs
Comment (Chris-Petty) [inline server/service/src/processors/assign_requisition_number/test.rs:1]: 🔥

File: server/service/src/processors/general_processor.rs [hunk 3]
```diff
@@ -91,12 +99,13 @@ pub(crate) fn process_records(
 
 pub(super) trait Processor {
     fn get_description(&self) -> String;
+
     /// Default to using change_log_table_names
-    fn changelogs_filter(&self) -> ChangelogFilter {
-        ChangelogFilter::new().table_name(EqualFilter {
+    fn changelogs_filter(&self, _ctx: &ServiceContext) -> Result<ChangelogFilter, ProcessorError> {
```
Comment (lache-melvin) [inline server/service/src/processors/general_processor.rs:104]: Altered this method to accept context, so can query for active stores on site in changelog filter

File: server/service/src/processors/transfer/requisition/mod.rs [hunk 4]
```diff
@@ -109,7 +107,6 @@ pub(crate) fn process_requisition_transfers(
         Box::new(LinkRequestRequisitionProcessor),
         Box::new(UpdateRequestRequisitionApprovedQuantitiesProcessor),
         Box::new(UpdateRequestRequisitionStatusProcessor),
-        Box::new(AssignRequisitionNumberProcessor),
```
Comment (Chris-Petty) [inline server/service/src/processors/transfer/requisition/mod.rs:112]: just so I understand correctly - before this processor and the ones above all shared the same cursor. Now this one has it's own cursor. Is that so it can run again from 0 without running the other ones?

Or 'cause conceptually it's not really a requisition transfer as such, just requisition related?

File: server/service/src/processors/transfer/requisition/assign_requisition_number.rs
Comment (lache-melvin) [inline server/service/src/processors/transfer/requisition/assign_requisition_number.rs:1]: So... I removed this, but would like thoughts, maybe I should put it back seeing as this is a patch fix?

The new processor _should_ apply the requisition number in all relevant cases. This one was being triggered after OMS insert/edit requisition, but those all already have the serial number assigned, so its actually only if a -1 is received from OG.

But maybe we should just add the new processor for patch, and remove this one in 2.8 so can be validated that everything still working as expected?

**Review by Chris-Petty — COMMENTED** [review]
Basically approval but know I'm jumping the gun so tell me when ready haha

File: server/service/src/processors/transfer/requisition/assign_requisition_number.rs
Comment (Chris-Petty) [reply server/service/src/processors/transfer/requisition/assign_requisition_number.rs:1]: Hmm I like the new one

File: server/service/src/processors/transfer/requisition/mod.rs (hunk 4 above)
Comment (Chris-Petty) [reply server/service/src/processors/transfer/requisition/mod.rs:112]: I see https://github.com/msupply-foundation/open-msupply/pull/7281#discussion_r2036386623

Comment (lache-melvin) [reply server/service/src/processors/transfer/requisition/mod.rs:112]: Moved from being a transfer processor to a general processor...

The existing processor was for transfers only - so only determined that there was a response requisition that needed a serial number applied when it could find a request requisition with name_link_id of a store on this site (request requisition that should result in a response requisition for this store) 🤯 

So - no associated request requisition = no number assigned. But seeing as no associated request requisition, its not really a transfer processor task. So moved to be a general record processor. Which each have their own cursor 😅

**Comment by lache-melvin** [comment]
FYI - I did do the DHIS2 integration test and it did work 🔥

File: server/service/src/processors/transfer/requisition/assign_requisition_number.rs
Comment (lache-melvin) [reply server/service/src/processors/transfer/requisition/assign_requisition_number.rs:1]: is he sayin burn it

Comment (Chris-Petty) [reply server/service/src/processors/transfer/requisition/assign_requisition_number.rs:1]: We stay the course. BURN THE OLD ONE

**Comment by Chris-Petty** [comment]
Oh looks we both had the same plan to manually run the tests 
image

Tangentially... wow so much duration variance???

**Comment by lache-melvin** [comment]
wow ouch such time - i think our runner isn't doing things in parallel...

**Comment by lache-melvin** [comment]
wait soz were u waiting on that test run or smth else?

**Review by Chris-Petty — APPROVED** [review]
To the moon

File: server/service/src/processors/assign_requisition_number/test.rs
Comment (andreievg) [reply server/service/src/processors/assign_requisition_number/test.rs:1]: 🚒

File: server/service/src/processors/assign_requisition_number/test.rs [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+
+use crate::{
+    processors::ProcessorType,
+    test_helpers::{setup_all_with_data_and_service_provider, ServiceTestContext},
+};
+
+/// Ensure requisition number is always assigned to response requisition
+/// Even if it doesn't have a linked request requisition
+#[tokio::test]
+async fn assigns_requisition_number_to_response_requisitions() {
```
Comment (andreievg) [inline server/service/src/processors/assign_requisition_number/test.rs:16]: Nice

File: server/service/src/processors/general_processor.rs (hunk 3 above)
Comment (andreievg) [reply server/service/src/processors/general_processor.rs:104]: Nice, this is good extension, vs checking during processing

File: server/service/src/processors/transfer/requisition/assign_requisition_number.rs
Comment (andreievg) [reply server/service/src/processors/transfer/requisition/assign_requisition_number.rs:1]: I think it's safe, -1 only arrives via sync form OG, we trigger processor then, i am happy in patch
