### PR TITLE
6257 fix encounter filter date

### LINKED ISSUE #6257: Encounter Datetime filter changes values per time zone
## What went wrong? 😲

Datetime picker field changes values when interacted with in Encounters

Seems to be going back in time by a certain increment when clicked on, clicked out of and clicked anywhere on the screen?

Video attached ->>> [here](https://drive.google.com/drive/folders/1BtsX3EpHRrN95BLyUKVBv19bnSPTduXt)

## Expected behaviour 🤔

Values stay the same regardless of where on the screen you click or whether or not you click on the field?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Encounters
2. Click on Filters -> Start date / time
3. Enter values -> click on the field again -> click out of it -> click anywhere on the screen
4. See values jumping while interacted with

## Your environment 🌱

- Open mSupply Version: V2.5.0-RC8
- Legacy mSupply Central Server Version: V7.19.03

- Platform: Galaxy Tab A8 (Android 14)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #6257

# 👩🏻‍💻 What does this PR do?

Input a date/time in the encounter list filter. Click out, the right time stays (and filters encounters correctly):
Screenshot 2025-02-27 at 5 52 04 PM

Plus side quest - saw inbound shipment was doing same thing, but we don't actually have times displayed on shipments, so updated filter to support a date only input of a datetime field. 

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Encounters list view
- [ ] Input a date & time
- [ ] Click out - the time stays what you entered
- [ ] Encounters are filtered correctly by your input
- [ ] Inbound shipment list view
- [ ] Date filters no longer have `time` input
- [ ] Filtered correctly by `from date`
- [ ] Select the `to date` - this is now inclusive

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [x] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [x] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [x] Postgres
- [x] SQLite
- [x] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx [hunk 1]
```diff
@@ -72,7 +80,7 @@ export const DateFilter: FC<{ filterDefinition: DateFilterDefinition }> = ({
 
 const getDateFromUrl = (query: string, range: RangeOption | undefined) => {
   const value = typeof query !== 'object' || !range ? query : query[range];
-  return DateUtils.getNaiveDate(value);
+  return DateUtils.getDateOrNull(value);
```
Comment (lache-melvin) [inline client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx:83]: This was the bit that was causing original bug

File: client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx [hunk 2]
```diff
@@ -39,8 +41,14 @@ export const DateFilter: FC<{ filterDefinition: DateFilterDefinition }> = ({
         updateQuery({ [urlParameter]: { [range]: '' } });
         return;
       }
+
+      const date =
+        range === 'to' && displayAs === 'date' // if no time picker, set "TO" field to end of day
+          ? DateUtils.endOfDay(selection)
+          : selection;
```
Comment (lache-melvin) [inline client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx:48]: Cheeky little addition, so if querying a datetime field, e.g. createdDatetime, but its really only a date as far as user is concerned, make the "to" date of the range inclusive

**Review by roxy-dao — APPROVED** [review]
LGTM~

Just have a nit: the inbound shipment label is Create date / time can this be changed to created date to reflect the changes here?
