### PR TITLE
7433 remove drag and drop from tablets

### LINKED ISSUE #7433: Drag and drop showing on Tablet
## What went wrong? 😲

Issue mentioned in #6851 release testing

## Expected behaviour 🤔

Tablet web app and tablet APK should show buttons rather than drag and drop.

Drag and drop doesn't make sense on tablet and mobile, so we should have the button functionality in this case.

When a user is using a computer, drag and drop should show.

Note there are 5 environment cases where users are accessing the UX:
| | | | | 
| ----- | ------- | -------- | ------- |
| *device* |  mobile | tablet | desktop |
| *environment* | web app vs capacitor | web app vs capacitor | web app OR app |

When in tablet or mobile - we want to show buttons (for both capacitor and web app)
When in desktop - we want to show drag and drop

## How to Reproduce 🔨

Navigate to CCE status settings 
You may need to set up CCE for this device.

Note this can probably be fixed by changing out cutoff thresholds in the edit status UX.

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by zachariah-at-msupply**
Fixes #7433 

# 👩🏻‍💻 What does this PR do?

This PR makes sure that the 'drag and drop' option of uploading a document in the coldchain > equipment > update status modal will not be shown on a mobile device.

It does this by using Capacitor.isNativePlatform() and EnvUtils.os to test whether OMS is running on Android or not.

## 💌 Any notes for the reviewer?

I hope your day's going well 👍 

# 🧪 Testing

- [ ] On an Android device, open the OMS app and go to coldchain > equipment  and click update status (top right hand corner).
- [ ] Check that the drag and drop area is not shown and the take photo button is shown (the modal should look like this:)

Screenshot 2025-04-23 at 18 21 41

- [ ] On an Android device, connect to OMS via the browser and go to coldchain > equipment  and click update status (top right hand corner).
- [ ] Check that the drag and drop area is not shown and the take photo button is shown (the modal should be the same as above).
- [ ] On a not-Android device, open OMS and, like in the first step, go to coldchain > equipment and click update status like before.
- [ ] Check that the drag and drop area *is* shown (the modal should look like this:)

image

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Comment by roxy-dao** [comment]
Have hijacked this PR since we need to get it done today and @zachariah-at-msupply away. 

Implemented changes according to [this comment](https://github.com/msupply-foundation/open-msupply/issues/6851#issuecomment-2819650283) and have removed photo option on desktop.

photo_2025-04-24 15 05 40
photo_2025-04-24 15 05 35

File: client/packages/coldchain/src/Equipment/DetailView/StatusForm.tsx [hunk 1]
```diff
@@ -1,28 +1,24 @@
...
+import { Capacitor } from '@capacitor/core';
 import {
   AssetLogStatusInput,
   Box,
-  CameraIcon,
   InsertAssetLogInput,
   StatusType,
   useDebounceCallback,
-  useIsSmallScreen,
+  LocaleKey,
```
Comment (roxy-dao) [inline client/packages/coldchain/src/Equipment/DetailView/StatusForm.tsx:9]: I got a little sidetracked with moving things around..

File: client/packages/coldchain/src/Equipment/DetailView/StatusForm.tsx [hunk 2]
```diff
@@ -127,33 +122,6 @@ export const StatusForm = ({ draft, onChange }: StatusForm) => {
     onChange({ files });
   };
 
-  const renderUploadButton = (): ReactNode => {
```
Comment (roxy-dao) [inline client/packages/coldchain/src/Equipment/DetailView/StatusForm.tsx:130]: Component now moved to ui/common component

File: client/packages/coldchain/src/Equipment/DetailView/StatusForm.tsx [hunk 3]
```diff
@@ -127,33 +122,6 @@ export const StatusForm = ({ draft, onChange }: StatusForm) => {
...
-    return (
-      <UploadButton
-        onUpload={onUpload}
-        files={draft.files}
-        customLabel={t('button.browse-files')}
-      />
-    );
-  };
-
-  const renderTakePhotoButton = (): ReactNode => {
```
Comment (roxy-dao) [inline client/packages/coldchain/src/Equipment/DetailView/StatusForm.tsx:142]: Rending TakePhotoButton directly below for android only

File: client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx [hunk 4]
```diff
@@ -123,10 +123,10 @@ export const toUpdateEquipmentInput = (
   id: row.id,
 });
 
-export const EquipmentImportModal: FC<EquipmentImportModalProps> = ({
+export const EquipmentImportModal = ({
```
Comment (roxy-dao) [inline client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx:126]: Side tracked with removing the FCs I stumble upon..

File: client/packages/common/src/ui/components/inputs/Upload/UploadDragAndDrop.tsx [hunk 5]
```diff
@@ -12,18 +12,18 @@ import {
...
-export interface UploadProps {
+interface UploadDragAndDropProps {
   accept?: Accept;
   color?: 'primary' | 'secondary' | 'gray';
   maxSize?: number;
   onUpload: <T extends File>(files: T[]) => void;
 }
 
-export const Upload: FC<UploadProps> = ({
+export const UploadDragAndDrop = ({
```
Comment (roxy-dao) [inline client/packages/common/src/ui/components/inputs/Upload/UploadDragAndDrop.tsx:22]: Renamed to reflect what component does

File: client/packages/common/src/ui/components/inputs/Upload/UploadFile.tsx [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+import { UploadButton } from './UploadButton';
+import { UploadDragAndDrop } from './UploadDragAndDrop';
+
+interface UploadFileProps {
+  onUpload: (files: File[]) => void;
+  files?: File[];
+  color?: 'primary' | 'secondary' | 'gray';
+}
+
+export const UploadFile = ({
```
Comment (roxy-dao) [inline client/packages/common/src/ui/components/inputs/Upload/UploadFile.tsx:12]: Here's where `renderUploadButton` was moved to ;x

File: client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx [hunk 7]
```diff
@@ -279,7 +281,7 @@ export const AssetItemUploadTab: FC<ImportPanel & AssetItemUploadTabProps> = ({
         </Grid>
       ) : null}
       <Stack spacing={2}>
-        <Upload onUpload={csvImport} />
+        <UploadDragAndDrop onUpload={csvImport} />
```
Comment (lache-melvin) [inline client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx:284]: should we not... always use UploadFile? Can't see why it would make sense on android anywhere?

Comment (roxy-dao) [reply client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx:284]: Well we could, but some things are only available on central and thus shouldn't be on Android. But will make them all use UploadFile 😉

Comment (lache-melvin) [reply client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx:284]: True... though yeah, still think healthy to expect someone will connect a tablet as a client to oms central at some point 😅

Comment (lache-melvin) [reply client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx:284]: Guess if you do that, we don't really need to isMobile check in the drag and drop component anymore....

**Review by lache-melvin — CHANGES_REQUESTED** [review]
Looks great on desktop and tablet! But I think I might have pointed you wrong - if I now understand this requirement correctly:

`User is able to take a photo instead of selecting a file from the app using the webview (on mobile)`

This would be using the web, on a phone. With current changes, that looks like this:

Screenshot 2025-04-24 at 4 37 12 PM

But should have the take photo option, and I guess we still do need the isMobile check after all?

**Comment by roxy-dao** [comment]
> User is able to take a photo instead of selecting a file from the app using the webview (on mobile)
> But should have the take photo option, and I guess we still do need the isMobile check after all?

We're not supporting mobile browser atm... I think he means app.. Changes do reflect in mobile app ;x

**Comment by lache-melvin** [comment]
> We're not supporting mobile browser atm... I think he means app.. Changes do reflect in mobile app ;x

Ah lol ok, so prob didn't need to revert, but I reckon keep it, no harm in the extra check for mobile :)

**Review by lache-melvin — APPROVED** [review]
ship it e hoa 🌱
