### PR TITLE
6604 dispensing fixes

### LINKED ISSUE #6766: Too much history (double history buttons)
## What went wrong? 😲

Image

## Expected behaviour 🤔

Just one history button

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open a prescription

## Your environment 🌱

- Open mSupply Version: 2.6.0-RC 
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #6766 
and most of #6604

# 👩🏻‍💻 What does this PR do?

Removes duplicate history button
Shows Required symbols for fields in Insurance modal

image

## 💌 Any notes for the reviewer?

The french selection issue from #6604 is probably plugin related so, will look at that separately

# 🧪 Testing

- [ ] Check how many history buttons we have
- [ ] Check how the Patient -> Insurance -> Add new Insurance modal looks, is it clear what needs to be filled in?

# 📃 Documentation

- [X] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Patient/Insurance/InsurancePolicySelect.tsx [hunk 1]
```diff
@@ -60,6 +61,9 @@ const getDefaultValue = (policyType: string, t: TypedTFunction<LocaleKey>) => {
         value: InsurancePolicyNodeType.Business,
       };
     default:
-      return { label: '', value: '' as InsurancePolicyNodeType };
+      return {
```
Comment (jmbrunskill) [inline client/packages/system/src/Patient/Insurance/InsurancePolicySelect.tsx:64]: Changed to default to Personal Policy.
I think this is better than having no default and an extra field to fill out...

Comment (CarlosNZ) [reply client/packages/system/src/Patient/Insurance/InsurancePolicySelect.tsx:64]: The Autocomplete takes  a `clearable` prop, so probably good to set `clearable={false}` to get rid of the X icon if we're not going to allow it.

File: client/packages/system/src/Patient/Insurance/InsuranceProvidersSelect.tsx [hunk 2]
```diff
@@ -33,6 +33,7 @@ export const InsuranceProvidersSelect: FC<InsuranceProvidersSelectProps> = ({
       label={t('label.provider-name')}
       Input={
         <Autocomplete
+          required
```
Comment (CarlosNZ) [inline client/packages/system/src/Patient/Insurance/InsuranceProvidersSelect.tsx:36]: Same for this one: `clearable={false}`

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
Cool, can we just add `clearable={false}` to those two drop-downs and we'll be good. Cheers.

**Comment by jmbrunskill** [comment]
@CarlosNZ made a another small bug fix, as policy type looked like it had a default value but that wasn't in the draft...
