### PR TITLE
8441 clinician gender sync fix

### LINKED ISSUE #8441: Clinician gender is lost across sync and reinitialisation
## What went wrong? 😲

QA Reported on OG: https://github.com/msupply-foundation/msupply/issues/16865

## Expected behaviour 🤔

When you use the various gender options on a Clinician in OMS, you when you sync that clinician to another OMS store you should get the correct gender showing. When reinitialising, the gender also persist correctly.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Set a Clinician's gender as "Unknown"
2. Sync
3. Reinitialise
4. The Clinician's gender is now "Male"

## Your environment 🌱

- Open mSupply Version: 2.9.0-rc
- Legacy mSupply Central Server Version: 8.03

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #8441

# 👩🏻‍💻 What does this PR do?

Updates clinician translators to use the `legacy_clinician_row.oms_fields` struct 

## 💌 Any notes for the reviewer?

This is quirky.

- If the `oms_fields` are None, then use the old `female` boolean
- else use `oms_fields`...
- If `oms_fields.gender` is None then set gender to None (ignore `female`)
- If `oms_fields.gender` is Some _valid_ `GenderType` variant then set gender to it
- If `oms_fields.gender` is Some* _invalid_ `GenderType` variant (say from a future version of OMS syncing it to an older version site) then set gender to None (* will write comment in PR code but it's actually if there is any error)
- If on migration to new versions of OMS that add `GenderType` variants, we should write migrations that check query `clinician.gender == None` and then lookup the sync_buffer to see if there is a valid variant to upsert on the clinician record.
- If a clinician is updated to some `GenderType` on it's homestore, then that clinician's homestore is moved to an old OMS site, then updated on that OMS site, if the GenderType was unsupported it'll sync out and overwrite it with `None`. Not ideal, but should be rare. Welcome ideas to prevent this.
- Our `pull_and_push` sync tests assume that the raw JSON going in will equal the raw JSON coming out. There are few scenarios in this gender handling logic that break that assumption. e.g. `"oms_fields": null,`, the incoming sync logic falls back to the boolean and populates the OMS record with `gender: GenderType::Male | GenderType::Female`. Then on "push" it'll translate that into the outgoing json `"oms_fields": { "gender": "MALE" | "FEMALE" },`. In this case the test fails as push JSON != pull JSON.
  - So that is to say I have definitely not written tests for everything as I didn't want to rewrite `pull_and_push` test...
- I'm not 100% sure our frontend is equipped to handle `clinician.gender` being null...

# 🧪 Testing

- [ ] OG central with v2.9 OMS remote, and some v2.8.x OMS remote 
- [ ] OG Create a clinician and set gender to male and make visible to both OMS remotes. Both OMS remotes see a clinician with gender "Male"
- [ ] OG Create a clinician and set gender to female and make visible to both OMS remotes. Both OMS remotes see a clinician with gender "Female"
- [ ] <v2.8.x Remote create Male/Female clinicians (A and B) and sync
- [ ] Make them visible to 2.9 remote and OG. They show as correct gender on OG and 2.9 remote
- [ ] v2.9 create a Transgender clinician (C) and sync.
- [ ] Make them visible to 2.8.x remote and OG. They show as Male in both OG and 2.8.x (default db behaviour)
- [ ] Migrate 2.8.x to 2.9. Clinician C should show as Transgender. A and B are still Male and Female respectively
- [ ] Reinitialise 2.9 remote. Clinicians A, B and C are Male, Female and Transgender respectively.

# 📃 Documentation

Well... The exact behaviours would be disturbing to document...

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+
+    let str_d: StrDeserializer<D::Error> = s.as_str().into_deserializer();
+    Ok(Some(T::deserialize(str_d)?))
+}
+
+pub fn ok_or_none<'de, T: Deserialize<'de>, D: Deserializer<'de>>(
+    d: D,
+) -> Result<Option<T>, D::Error> {
+    Ok(empty_str_as_option(d).map_or(None, |v| v))
+}
```
Comment (Chris-Petty) [inline server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs:32]: Annoyingly duplicated this out of sync_serde. I see they have been moved to a more accessible place in `develop`... I'm happy to resolve that conflict when it comes. That is if we don't want to just rebase this PR to develop at this stage of the release cycle!

File: server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+    gender -> Nullable<crate::GenderTypeMapping>,
+  }
+}
+
+#[derive(Clone, Queryable, Insertable, AsChangeset, Debug, PartialEq, Default)]
+#[diesel(table_name = clinician)]
+pub struct ClinicianRow {
+    pub id: String,
+    pub gender: Option<GenderType>,
+}
```
Comment (Chris-Petty) [inline server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs:59]: Similarly these are all duplicated/subsets of other types that exist and is quite nasty IMO. It makes me want to review our project structure entirely 👀. One might be able to argue that the problem is that I should be using the repository layer rather than diesel directly, however that is not the established pattern in migration `templates` directory. That also wouldn't fix the lack of access to `LegacyClinicianRow` and `ClinicianOmsFields`. Maybe there's a case that it's better this way?

File: server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+            let legacy_row = serde_json::from_str::<LegacyClinicianRow>(&data)
+                .with_context(|| format!("Cannot parse sync buffer row data: {}", data))?;
+
+            let Some(fields) = legacy_row.oms_fields else {
+                continue;
+            };
+
+            if let Some(gender) = fields.gender {
+                diesel::update(clinician::table)
+                    .filter(clinician::id.eq(id))
```
Comment (Chris-Petty) [inline server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs:88]: I was tempted to explore some store_ID filters based on homesite, but didn't want to define 2 more diesel tables and structs... and on second thought it's probably best to not do that filter anyway. If they're from another site you want to integrate what they may have sent but weren't able to integrate previously. If they're from _this_ site either oms_fields is already None so we don't update, or this clinician was moved from another site to this site with a valid oms_fields.gender that can now be integrated.

File: server/service/src/sync/sync_serde.rs [hunk 4]
```diff
@@ -24,6 +24,12 @@ pub fn empty_str_as_option<'de, T: Deserialize<'de>, D: Deserializer<'de>>(
     Ok(Some(T::deserialize(str_d)?))
 }
 
+pub fn ok_or_none<'de, T: Deserialize<'de>, D: Deserializer<'de>>(
```
Comment (Chris-Petty) [inline server/service/src/sync/sync_serde.rs:27]: I was gonna call this something confusing like `empty_str_as_option_and_enum_invalid_variant_as_none` however that is obnoxiously long and the real behaviour really just is `ok_or_none`, cause any error will be returned as None.

I had wanted to check specifically for the `invalid enum variant` error that serde throws but couldn't quite figure out how to do so if that is possible.

File: server/service/src/sync/translations/clinician.rs [hunk 5]
```diff
@@ -83,8 +97,17 @@ impl SyncTranslation for ClinicianTranslation {
...
             store_id,
+            oms_fields,
         } = serde_json::from_str::<LegacyClinicianRow>(&sync_record.data)?;
 
+        let gender = if let Some(fields) = oms_fields {
+            fields.gender
+        } else {
+            is_female
+                .then_some(GenderType::Female)
+                .or(Some(GenderType::Male))
```
Comment (Chris-Petty) [inline server/service/src/sync/translations/clinician.rs:108]: why they bother making `.then_some()` but not `or_some()`?

File: server/service/src/sync/translations/clinician.rs [hunk 6]
```diff
@@ -134,9 +153,12 @@ impl SyncTranslation for ClinicianTranslation {
             )))?;
 
         let is_female = gender
-            .map(|gender| matches!(gender, GenderType::Female))
+            .as_ref()
+            .map(|g| *g == GenderType::Female)
             .unwrap_or(false);
 
+        let oms_fields = Some(ClinicianOmsFields { gender });
```
[the remark this answers is not in the document]
Comment (lache-melvin) [reply server/service/src/sync/translations/clinician.rs:160]: Sounds ok to me - only time we would sync out is if OMS site made a change to the clinician, at which point we should be using the OMS fields

File: server/repository/src/db_diesel/name_row.rs [hunk 7]
```diff
@@ -86,6 +86,10 @@ allow_tables_to_appear_in_same_query!(name_oms_fields, master_list_name_join);
 allow_tables_to_appear_in_same_query!(name_oms_fields, master_list);
 allow_tables_to_appear_in_same_query!(name_oms_fields, program);
 
+// If adding to this enum remember that we need to add migrations.
+// Old versions may integrate through sync the new gender variant as `None`.
+// Your migration should address this by checking all records with `None` values and
+// convert them to the new more concrete variant you have added.
```
[the remark this answers is not in the document]
Comment (Chris-Petty) [reply server/repository/src/db_diesel/name_row.rs:92]: It's not true for name until it uses `ok_or_none` correct, though until then patients specifically may suffer the issue of not being able to integrate the name record if there is an unsupported gender variant.

I think we should change that as a separate issue.

**Review by lache-melvin — CHANGES_REQUESTED** [review]
IT WORKS, but no warning that my OG version was too low, didn't have oms field, needs sync version bump 🙏

File: server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+}
+
+pub(crate) struct Migrate;
+
+impl MigrationFragment for Migrate {
+    fn identifier(&self) -> &'static str {
+        "reintegrate_clinician_gender"
+    }
+
+    fn migrate(&self, connection: &StorageConnection) -> anyhow::Result<()> {
```
[the remark this answers is not in the document]
Comment (lache-melvin) [reply server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs:68]: ouuuuuu oki, so clinicians probs okay atm in that we can't update them on remotes yet, but that will change at some point im sure
