### PR TITLE
9032 The PO with only placeholder items can be confirmed and finalised

### LINKED ISSUE #9032: The PO with only placeholder items can be confirmed and finalised
## What went wrong? 😲

https://github.com/user-attachments/assets/6d0cd6c8-d55b-4760-bb7c-e23d8dc9ffca

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a PO
2. Add item via masterlist
3. Don't edit any lines
4. Just Confirm/Finalise the masterlist

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #9032 

# 👩🏻‍💻 What does this PR do?

Updated the logic that checks for empty lines for a PO. It was using an outdated check - have updated to be checking if any of the lines doesn't have a set value for `requestedNumberOfUnits`.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Navigate to a PO
- [ ] Add multiple Items (Don't set Requested Packs for some of them to create a placeholder line)
- [ ] Click on Confirm button -> Should get warning if placeholder lines exists and shouldn't change status
- [ ] Either delete the placeholder lines or update Requested Packs
- [ ] Should let you change Status

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/purchasing/src/purchase_order/DetailView/Footer/StatusChangeButton/StatusChangeButton.tsx [hunk 1]
```diff
@@ -20,7 +20,7 @@ export const StatusChangeButton = (): ReactElement | null => {
   if (!selectedOption) return null;
 
   const handleClick = () => {
-    if (!validateEmptyPurchaseOrder(lines)) return noLinesNotification();
+    if (!hasValidPurchaseOrderLines(lines)) return noLinesNotification();
```
Comment (aimee-mcneil-melville) [inline client/packages/purchasing/src/purchase_order/DetailView/Footer/StatusChangeButton/StatusChangeButton.tsx:23]: The toast message in the notification should be updated to fit the new workflow - rather than preventing 'only' placeholder lines this is now preventing on 'any' placeholder lines.

New message could be along the lines of: `Cannot change the status until all lines have a requested quantity.`

**Review by aimee-mcneil-melville — DISMISSED** [review]
Awesome, this is working well 🎉 

Just the toast message to update as it doesn't quite fit with the changes :)

File: client/packages/purchasing/src/purchase_order/DetailView/Footer/StatusChangeButton/StatusChangeButton.tsx (hunk 1 above)
Comment (GeronimoJohn) [reply client/packages/purchasing/src/purchase_order/DetailView/Footer/StatusChangeButton/StatusChangeButton.tsx:23]: Great catch! 🙏🏽 Fix here: https://github.com/msupply-foundation/open-msupply/pull/9109/commits/17a6dd6bab23a2ebc80a9917fc7dd49e1e574624

**Review by aimee-mcneil-melville — APPROVED** [review]
Awesome, good to go 🎉
