### PR TITLE
#2476 Inactivity timer fix

### LINKED ISSUE #2476: Login timer: Problem with "getLastRequestTime" after refresh
Okay, so I've figured out what's happening with the inactivity detector and why we sometimes get logged out even when active.

It's very odd -- turns out the `getLastRequestTime()` method called in `useRefreshToken` is getting a stale value (i.e. it's not being updated). But here's the weird part -- it _only_ starts behaving like this after a page refresh.

E.g. after normal login, the `getLastRequestTime()` result is the same as the value stored in the GqlContext, and they increase as expected on new requests:
Screenshot 2023-11-14 at 2 55 13 PM
Screenshot 2023-11-14 at 2 55 25 PM

However, after a page refresh, the `getLastRequestTime()` value never increases any more, even though the actual value in GqlContext is being set from new requests as expected:
Screenshot 2023-11-14 at 2 55 58 PM
Screenshot 2023-11-14 at 2 56 07 PM

So this explains why we often get logged out -- the last request time doesn't update, and eventually is older than the 1-hour timeout, and so the refreshToken method doesn't run when it's supposed to.

Not 100% sure what's going on, but it seems to be something to do with the `createGql` method called in the `GqlProvider` -- it's creating a *new* instance of `GQLClient` every time it's called, but it probably should be only be using a single instance -- the one created when the app loads (as it's outside the hooks). Casual testing suggests that I can fix it by replacing:

```ts
  const [{ client }, setApi] = useState<{
    client: GQLClient;
  }>(() => createGql(url, skipRequest));
```

with 
```ts
 const [{ client }, setApi] = useState<{
    client: GQLClient;
  }>({ client: new GQLClient(url, { credentials: 'include' }, skipRequest) });
```

And then not using the "createGql" function at all (since we don't want multiple). This *seems* to solve at least that problem, although I'm not sure what else it might be breaking.

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #2476

~~(Putting PR in Draft initially as I'm not 100% sure what else is going on)~~

# 👩🏻‍💻 What does this PR do? 
 

Detailed analysis of the problem in [original issue](https://github.com/msupply-foundation/open-msupply/issues/2476#issue-1991827917)

Update `GqlContext` to ensure only one instance of `GQLClient` is ever created. This prevents the `refreshToken` method from ending up with a different instance and therefore not getting the `lastRequestTime` updated correctly.

# 🧪 How has/should this change been tested? 

There's a couple of `console.log()`s in there (commented out -- will remove for non-Draft PR) which you can enable to test. The values from each should be the same value, which updates as you make requests. Can compare to the original issue (where I described the condition for them getting different values).

## 💌 Any notes for the reviewer?

Anything that might break from this?

### CODE REVIEW

File: client/packages/common/src/api/GqlContext.tsx [hunk 1]
```diff
@@ -170,9 +163,9 @@ export const GqlProvider: FC<PropsWithChildren<ApiProviderProps>> = ({
   skipRequest,
   children,
 }) => {
-  const [{ client }, setApi] = useState<{
-    client: GQLClient;
-  }>(() => createGql(url, skipRequest));
+  const client = useRef(
+    new GQLClient(url, { credentials: 'include' }, skipRequest)
+  ).current;
```
Comment (CarlosNZ) [inline client/packages/common/src/api/GqlContext.tsx:168]: Seems like a good case for `useRef` rather than `useState`, as we're not going to be "setting state" anymore, we're just going to mutate `client` directly using its internal setters.

File: client/packages/common/src/api/GqlContext.tsx [hunk 2]
```diff
@@ -196,7 +189,8 @@ export const GqlProvider: FC<PropsWithChildren<ApiProviderProps>> = ({
   );
 
   useEffect(() => {
-    setApi(createGql(url, skipRequest));
+    if (skipRequest) client.setSkipRequest(skipRequest);
+    if (url) client.setEndpoint(url);
   }, [url, skipRequest]);
```
Comment (CarlosNZ) [inline client/packages/common/src/api/GqlContext.tsx:194]: Not sure if this `useEffect` is actually needed at all? The `url` shouldn't change, but I'm not sure when `skipRequest`might.

**Review by mark-prins — APPROVED** [review]
👍  that's working for me - nice work in figuring that one out!

I've also noticed that you get a little bonus time before the system logs you out. 
that's because the refresh token call will update the cookie expiry.. so..

- login
- every minute
  - check if cookie almost expires
  - if so, and you've done something to access API within the last COOKIE_LIFETIME_MINUTES then refresh

For example, you only login, and don't interact in any other way:
- login, set expiry to 60 mins
- at 58 or 59 mins and refresh the token, update the cookie expiry to be now+60 mins
- you get logged out, at around 2hours

what about 

```
export const setAuthCookie = (cookie: AuthCookie) => {
  const expires = addMinutes(new Date(), COOKIE_LIFETIME_MINUTES / 2);
```

or changing cookie lifetime to 30 mins with a comment to say why?

**Comment by CarlosNZ** [comment]
> 👍 that's working for me - nice work in figuring that one out!
> 
> I've also noticed that you get a little bonus time before the system logs you out. that's because the refresh token call will update the cookie expiry.. so..
> 
>     * login
> 
>     * every minute
>       
>       * check if cookie almost expires
>       * if so, and you've done something to access API within the last COOKIE_LIFETIME_MINUTES then refresh
> 
> 
> For example, you only login, and don't interact in any other way:
> 
>     * login, set expiry to 60 mins
> 
>     * at 58 or 59 mins and refresh the token, update the cookie expiry to be now+60 mins
> 
>     * you get logged out, at around 2hours
> 
> 
> what about
> 
> ```
> export const setAuthCookie = (cookie: AuthCookie) => {
>   const expires = addMinutes(new Date(), COOKIE_LIFETIME_MINUTES / 2);
> ```
> 
> or changing cookie lifetime to 30 mins with a comment to say why?

Okay, I think I have something that is working nicely now, @mark-prins : https://github.com/msupply-foundation/open-msupply/pull/2485/commits/18a45fbb388a27a0fdabbc51a36aa3645d020f94

Basically, it just runs the "expiry" functionality (delete cookie, throw auth error) when the "minutesSinceLastRequest" reaches the Timeout time, regardless of the cookie expiry time.

If you want to see it working, I've saved another branch `2476-inactivity-timer-console-demo` which has `console.logs` throughout so you can confirm what its doing at any given event.

File: client/packages/common/src/authentication/api/hooks/useRefreshToken.ts [hunk 3]
```diff
@@ -40,6 +40,7 @@ export const useRefreshToken = () => {
         setHeader('Authorization', `Bearer ${token}`);
       });
     }
+    if (minutesSinceLastRequest >= COOKIE_LIFETIME_MINUTES) onTimeout();
```
Comment (mark-prins) [inline client/packages/common/src/authentication/api/hooks/useRefreshToken.ts:43]: If you make this an early return and move it before the refresh api call:

```suggestion
    if (minutesSinceLastRequest >= COOKIE_LIFETIME_MINUTES) {
      onTimeout();
      return;
    }
```

then you can remove the `minutesSinceLastRequest` check, rather than repeating it

```
    const expiresSoon = expiresIn === 1 || expiresIn === 2;
    if (expiresSoon) {
      mutateAsync().then(data => {
        const token = data?.token ?? '';
        const newCookie = { ...authCookie, token };
        setAuthCookie(newCookie);
        setHeader('Authorization', `Bearer ${token}`);
      });
    }
```

**Review by mark-prins — COMMENTED** [review]
this changes behaviour a little - and now `COOKIE_LIFETIME_MINUTES` doesn't exactly reflect what it does.

That constant now refers to how long you'll be logged in for - the cookie might well be valid still, but you will be logged out if you haven't queried the API within that time interval. 

for example, the cookie is refreshed at 59 minutes, you now have a cookie that's valid for a further 60 mins. you haven't queried in the previous 30 mins though, so you will be logged out with 30 mins of cookie validity on the clock.

overall it's better - the intention was that you'd be logged out after x minutes of inactivity and that's what you've done. perhaps just rename the const? or don't worry and ignore this burst of pedantry?

File: client/packages/common/src/authentication/AuthContext.tsx [hunk 4]
```diff
@@ -107,7 +107,10 @@ export const AuthProvider: FC<PropsWithChildrenOnly> = ({ children }) => {
     mostRecentCredentials,
   } = useLogin(setCookie);
   const getUserPermissions = useGetUserPermissions();
-  const { refreshToken } = useRefreshToken();
+  const { refreshToken } = useRefreshToken(() => {
+    Cookies.remove('auth');
+    setError(AuthError.Timeout);
```
Comment (mark-prins) [inline client/packages/common/src/authentication/AuthContext.tsx:112]: I think you should add  `setCookie(undefined);` here too.

this logs the user out, but does not prompt  - I have to navigate to a different page before I'm told that I'm logged out.
two options:
- navigate to the login page, with a message displayed 'You've been logged out due to inactivity' or similar
- do something here to update the local state and force a refresh which would refresh `AuthenticationAlert` and prompt the user

I rather like option 1 even though we have a beautiful 'you've been logged out' alert already and redirecting to login is slightly unconventional.

for the second option, a dirty version would be to add `window.location.reload();` to the callback method here 😉

**Comment by CarlosNZ** [comment]
> overall it's better - the intention was that you'd be logged out after x minutes of inactivity and that's what you've done. perhaps just rename the const? or don't worry and ignore this burst of pedantry?

> this changes behaviour a little - and now `COOKIE_LIFETIME_MINUTES` doesn't exactly reflect what it does.

Yup, I think just changing the constant name is best -- how about `INACTIVITY_TIMEOUT_MINUTES`?

> for example, the cookie is refreshed at 59 minutes, you now have a cookie that's valid for a further 60 mins. you haven't queried in the previous 30 mins though, so you will be logged out with 30 mins of cookie validity on the clock.

Yes, there's two separate processes going on, so we either:
1. Log out after the correct period of inactivity, which leaves a possible cookie "out there" which could be used for another X minutes.
2. Log out when the cookie expires, which leave the user logged in for longer than the intended inactivity time
3. Do some complicated shenanigans to keep them both in sync.

Option 3 seems overly complicated and unnecessary (and would probably involve some additional back-end work to be really robust). I think Option 1 is what we want (and what I've done). The cookie is deleted on logout, so it can't really be re-used unless someone went to the trouble of copying it and keeping it before being logged out -- but if they were going to that much trouble, they may as well just stay logged in by keeping active! 😆 

Thanks for the comments, I'll update according to your suggestions.

**Comment by mark-prins** [comment]
> how about INACTIVITY_TIMEOUT_MINUTES?

yeah, that's nice and clear. thanks

> there's two separate processes going on, so we either

yep. option one is best I think

File: client/packages/common/src/authentication/AuthContext.tsx (hunk 4 above)
Comment (CarlosNZ) [reply client/packages/common/src/authentication/AuthContext.tsx:112]: > this logs the user out, but does not prompt - I have to navigate to a different page before I'm told that I'm logged out.

Not quite getting this one. I get the correct (same as current) dialog that pops up at logout time:
Screenshot 2023-11-21 at 10 25 11 AM

I get this without having to navigate anywhere else, it just appears. And this works whether I have `setCookie(undefined)` or not -- are you seeing something different?

Comment (mark-prins) [reply client/packages/common/src/authentication/AuthContext.tsx:112]: yeah - I get the console log saying that things have been cleared, but nothing shows in the UI. I left it for a further 5 mins.. nothing. I navigated to another page and it popped up.

Comment (CarlosNZ) [reply client/packages/common/src/authentication/AuthContext.tsx:112]: Hmm, interesting, I'll check it out in different browsers and compare it to the current behaviour.

I thought `setError(AuthError.Timeout)` should cause this prompt. Does it work as expected for you in the current system?

Comment (CarlosNZ) [reply client/packages/common/src/authentication/AuthContext.tsx:114]: Yeah, I can't replicate the problem you're describing in either Firefox or Chrome. I'll wait and see what it looks like on yours tomorrow when we're both in the office. Damn, thought this was sorted :/

Comment (mark-prins) [reply client/packages/common/src/authentication/AuthContext.tsx:114]: I've tested again and it worked fine that time. let's just merge this and monitor.. what you've done makes sense and is much better than it is currently

Comment (CarlosNZ) [reply client/packages/common/src/authentication/AuthContext.tsx:114]: Good to hear! Will keep an eye on it.
