### PR TITLE
2109 Patient query fails for name_or_code AND identifier

### LINKED ISSUE #2109: Patient query fails for name_or_code AND identifier
The branch https://github.com/openmsupply/open-msupply/compare/develop...patient-search-and-or-bug contains a test case where a query returns results where it shouldn't:

```rust
PatientFilter::new()
                    .name_or_code(StringFilter::equal_to("codePatient"))
                    .identifier(StringFilter::like("not existing"))
```
This should be evaluate like:
`(name == "codePatient" OR code == "codePatient) AND (code like "not existing" OR  national_health_number like "not existing")`

but the used SQL is:

```sql
SELECT "name"."id", "name"."name", "name"."code", "name"."type", "name"."is_customer", "name"."is_supplier", "name"."supplying_store_id", "name"."first_name", "name"."last_name", "name"."gender", "name"."date_of_birth", "name"."phone", "name"."charge_code", "name"."comment", "name"."country", "name"."address1", "name"."address2", "name"."email", "name"."website", "name"."is_manufacturer", "name"."is_donor", "name"."on_hold", "name"."created_datetime", "name"."is_deceased", "name"."national_health_number"
FROM "name"
WHERE (
        (
            ("name"."code" ILIKE $1 OR "name"."national_health_number" ILIKE $2)
            OR "name"."id" IN (
                SELECT "program_enrolment"."patient_id"
                FROM ("program_enrolment" INNER JOIN "program" ON "program_enrolment"."program_id" = "program"."id")
                WHERE "program_enrolment"."program_enrolment_id" ILIKE $3
            )
        )
        AND "name"."name" = $4
        OR "name"."code" = $5
    )
    AND "name"."type" = $6
ORDER BY "name"."id" ASC LIMIT $7 OFFSET $8 -- binds: ["%nhn%", "%nhn%", "%nhn%", "codePatient", "codePatient", Patient, 100, 0]
```

This is tricky to solve with current diesel filter... We could disallow two OR queries in the same filter throw if there they are both set. Or we could put the name check into the `identfier` filter as well? e.g. `name == $1 OR code == $1 OR national_health_number == $1 OR program_enrolment_id == $1`

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #2109

# 👩🏻‍💻 What does this PR do? 
Unify name_or_code and identifier filter for patient (i.e. add `OR` name filtering to identifier and remove name_or_code)

# 🧪 How has/should this change been tested? 
- [ ] Test patient search in `New Patient` still works

### CODE REVIEW

File: server/repository/src/db_diesel/patient.rs [hunk 1]
```diff
@@ -490,12 +480,9 @@ mod tests {
             )
             .unwrap();
         assert_eq!(result.len(), 0);
-        // test filter for name_or_code and identifier
         let result = repo
             .query_by_filter(
-                PatientFilter::new()
-                    .name_or_code(StringFilter::equal_to("codePatient"))
-                    .identifier(StringFilter::like("nhn")),
+                PatientFilter::new().identifier(StringFilter::like("test_name")),
```
Comment (clemens-msupply) [inline server/repository/src/db_diesel/patient.rs:485]: Nit: add test cases for `code`/`code2` or for an identifier matching two patient,e.g.

|Name| code |code2|
|----|--|--|
|Patient1| test1| code11 |
|Patient2| code22| test2 |

and then search for `test`

**Review by clemens-msupply — APPROVED** [review]
Thanks! Patient search is still working
