### PR TITLE
4161 move patient out of name type node

### LINKED ISSUE #4161: Hardcode filtering out of patients from names query
NOTE: maybe this is a bug - the `type` property on the NameFilterInput now doesn't work, it gets overwritten in the service layer by a `type != PATIENT` filter... haven't _seen_ any other issues in the actual UI from it though 🤷‍♀️

## The suggestion

Context: #4146

Issue introduced by #4023

We have a `names` query endpoint, and a different one for `patients`. We only use the `names` one for non-patient related things, so we should hard code the filtering out of patients into the repository layer. 

We should then also remove the `NameNodeType::Patient` and `isPatient` options from the NameFilterInput, to make it clear its not possible to query patients via the name endpoint

### Why should we invest time in this?

Our API inputs should accurately reflect what you are able to get back!

Finish off the teasing apart of store/facility and patient, so we don't need to constantly consider this filtering while devving.

### Are there any risks associated with this change?

Just checking all the queries still work as expected?

### How much effort is required?

Couple hours?

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4161

# 👩🏻‍💻 What does this PR do?
Last bit of 4161, move patient out of name type

# 🧪 Testing

- [ ] Make sure customers and suppliers are still loading correctly

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/service/src/rnr_form/tests/finalise.rs [hunk 1]
```diff
@@ -71,11 +71,6 @@ mod finalise {
             .context(mock_store_a().id, "".to_string())
             .unwrap();
 
-        let last_requisition_number = RequisitionRowRepository::new(&context.connection)
```
Comment (roxy-dao) [inline server/service/src/rnr_form/tests/finalise.rs:74]: This variable isn't being used anywhere in the test 🤷🏻

File: server/service/src/sync/test/test_data/rnr_form_line.rs [hunk 2]
```diff
@@ -48,6 +48,7 @@ fn rnr_form_line_1() -> RnRFormLineRow {
         requested_quantity: 0.0,
         comment: None,
         confirmed: false,
+        previous_average_monthly_consumption: 0.0,
```
Comment (mark-prins) [inline server/service/src/sync/test/test_data/rnr_form_line.rs:51]: I think I've fixed this somewhere too 😆

**Review by mark-prins — APPROVED** [review]
🎉  thanks Roxy - looks great!
