### PR TITLE
Bug fix making currency_id required

### LINKED ISSUE #3438: Migration fails 1.7.0 -> 2.0.0
## What went wrong? 😲
Migration failing because of invoice.currency_id migration. Also version needs to be renamed from 1.8 -> 2.0

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Version: 
- mSupply version: 

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #3438

# 👩🏻‍💻 What does this PR do? 
Separate SQLite and postgres migrations

# 🧪 How has/should this change been tested? 
I've tested a demo datafile from 1.7 to this branch on postgres and sqlite.

## 💌 Any notes for the reviewer?
It's nice to keep things the same between SQLite and Postgres where possible but this feels like a good chance to use postgres features which aren't available in sqlite.

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: server/repository/src/migrations/v1_08_00/invoice_required_currency_id.rs [hunk 1]
```diff
@@ -3,16 +3,30 @@ use crate::StorageConnection;
 pub(crate) fn migrate(connection: &StorageConnection) -> anyhow::Result<()> {
     use crate::migrations::sql;
 
-    sql!(
+    if cfg!(feature = "postgres") {
+        sql!(
+            connection,
+            r#"
+                UPDATE invoice SET currency_id = (SELECT id FROM currency WHERE is_home_currency = true) WHERE currency_id is NULL;
```
Comment (roxy-dao) [inline server/repository/src/migrations/v1_08_00/invoice_required_currency_id.rs:10]: Ooh so Postgres does allow this 👀 . I wasn't sure XD

**Review by roxy-dao — APPROVED** [review]
Yay! Thanks /o/
