### PR TITLE
4306 4305 Fix transfer migrations from mobile

### LINKED ISSUE #4305: Lines missing in SI after mobile-migration
## What went wrong? 😲
From [here](https://github.com/msupply-foundation/open-msupply/issues/4139#issuecomment-2177911790): Lines missing in SI after mobile-migration

## Expected behaviour 🤔
no lines should be missing in transaction after migration

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have two mobile stores setup.
2. Create CI from mobile-storeA to mobile-storeB
3. In mobile-storeB, receive SI, don't finalise yet
4. Make sure everything is synced till this point
5. Migrate storeB to oms. In Cloud, remove hardware, and reinitialise oms from scratch
6. Now oms-storeB; open that unfinalised SI
7. See error: no lines at all

## Your environment 🌱

- Open mSupply Version: v2.1.0-rc4
- Legacy mSupply Central Server Version: v7-15-06

- Platform: apk, browser(chrome)

- Database type: sqlite

### LINKED ISSUE #4306: Can't process the previous requisition from mobile if requestor was oms-store
## What went wrong? 😲
From [here](https://github.com/msupply-foundation/open-msupply/issues/4139#issuecomment-2177911790): Can't process the previous requisition from mobile if requestor was oms-store

## Expected behaviour 🤔
previous requisition should be allowed to proceed in normal manner

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have a oms-storeA and mobile-storeB
2. Create a IO from oms-storeA to mobile-storeB
3. In mobile-storeB, there's a customer-requisition received. Don't process it yet
4. Make sure everything is synced till this point
5. Migrate storeB to oms. In Cloud, remove hardware, and reinitialise oms from scratch
6. Now oms-storeB; open that previous customer-requisition
7. See error: the status is Sent and thus you can't proceed further
Note: when IO was from mobile-store(requestor), that requisition can be processed just fine after migration. Problem is only when IO was made by oms-store

## Your environment 🌱

- Open mSupply Version: v2.1.0-rc4
- Legacy mSupply Central Server Version: v7-15-06

- Platform: apk, browser(chrome)

- Database type: sqlite

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #4306 
Fixes #4305 

# 👩🏻‍💻 What does this PR do?

Both fixes are relate to existing transfers being migrated to omSupply (inbound shipment and response requisition from existing mSupply mobile store to omSupply store)

There is a check during integration of invoice lines that stock line exists, and if it doesn't we ignore it. Stock line is only added to invoice line in omSupply when inbound shipment is delivered, but in mobile placeholder stock line is id added (either in mobile or during inbound shipment generation in mSupply central). Actually this check was already added but during find_one_by_id refactor it was missed (I went through all of the find_one_by_id and made sure this is not a problem somewhere else, you'll see some minor changes due to this). So added is_some() check on top of is_ok()

For requisition being not editable, when mSupply creates supplier invoice or response, it will copy everything from that original record, this was noted as issue previously for invoices and sanitisation was added, same added here in this PR for requisition

I added an extra macro to help with tests, to be able to assert and extract a variant.

## 💌 Any notes for the reviewer?

Looks like the stock_line will be cleared on invoice line regardless of invoice type and status, I think this could be an issue down the road, would expect sync to guarantee some sort of data integrity so we don't get runtime errors down the track, only noticed this when writing PR description. Do you think i should change that now, is it ok to query for invoice on every invoice line integration ?

# 🧪 Testing

You can use this data file:

[43054306.4DD.zip](https://github.com/user-attachments/files/16060893/43054306.4DD.zip)

Use config user to register etc.. Use wasmobile site and test user, first initialise pre this change you will see that requisition is not editable and invoice line is missing from inbound shipment. 

When using the fixed version you will see that requisition is editable and line is present in inbound shipment.

To start test form scratch please see issue test case or just have a mobile store/site to which you send internal order and outbound shipment, sync mobile site to make sure those are received. Then convert that site to omSupply site, and check both invoice and requisition

### CODE REVIEW

File: server/repository/src/db_diesel/requisition/requisition_row.rs [hunk 1]
```diff
@@ -250,6 +252,10 @@ impl Upsert for RequisitionRow {
             Ok(Some(self.clone()))
         )
     }
+
+    fn as_mut_any(&mut self) -> Option<&mut dyn Any> {
```
Comment (andreievg) [inline server/repository/src/db_diesel/requisition/requisition_row.rs:256]: this is needed to downcast to requisition row from Boxed upsert in requisition translation test

File: server/service/src/sync/translations/invoice_line.rs [hunk 2]
```diff
@@ -198,8 +198,8 @@ impl SyncTranslation for InvoiceLineTranslation {
         // Currently a uuid is assigned by central for the stock_line id which causes a foreign key constraint violation
         let is_stock_line_valid = match stock_line_id {
             Some(ref stock_line_id) => StockLineRowRepository::new(connection)
-                .find_one_by_id(stock_line_id)
-                .is_ok(),
+                .find_one_by_id(stock_line_id)?
+                .is_some(),
```
Comment (andreievg) [inline server/service/src/sync/translations/invoice_line.rs:202]: this is the fix for the invoice line missing

File: server/service/src/sync/translations/requisition.rs [hunk 3]
```diff
@@ -160,6 +160,47 @@ pub struct LegacyRequisitionRow {
     #[serde(deserialize_with = "empty_str_as_option_string")]
     pub programID: Option<String>,
 }
+
+/// When mSupply central creates transfers it copies over all of the data
```
Comment (andreievg) [inline server/service/src/sync/translations/requisition.rs:164]: there is similar method that existing in invoice already, copied but added partial row struct because now there are two field to manual deserialise (so thought to do it with a struct)

File: server/service/src/sync/translations/requisition.rs [hunk 4]
```diff
@@ -607,4 +652,74 @@ mod tests {
...
+                "store_ID": "8659A64D2CF245A1B1BCC7C8F7CDC577",
+                "thresholdMOS": 0,
+                "type": "response",
+                "user_ID": ""
+            }
+            "#.to_string(),
+            ..Default::default()
+        };
+
+        let mut op = assert_variant!(
```
Comment (andreievg) [inline server/service/src/sync/translations/requisition.rs:703]: using new assert_variant macro here

File: server/service/src/sync/translations/requisition.rs [hunk 5]
```diff
@@ -607,4 +652,74 @@ mod tests {
...
+            translator.try_translate_from_upsert_sync_record(&connection, &sync_record),
+            Ok( PullTranslateResult::IntegrationOperations(out)) => out
+        );
+
+        let mut upsert =
+            assert_variant!(op.pop(), Some(IntegrationOperation::Upsert(out, _)) => out);
+
+        let requisition_row = upsert
+            .as_mut_any()
+            .and_then(|any| any.downcast_mut::<RequisitionRow>())
```
Comment (andreievg) [inline server/service/src/sync/translations/requisition.rs:713]: there is an example of downcasting in repository/lib under the trait (with a test)

File: server/util/src/test_helpers.rs [hunk 6]
```diff
@@ -9,3 +9,13 @@ macro_rules! assert_matches {
         )
     }};
 }
+
+#[macro_export]
+macro_rules! assert_variant {
```
Comment (andreievg) [inline server/util/src/test_helpers.rs:14]: this macro could be useful to others, i should have added it earlier for tests helpers

**Review by jmbrunskill — APPROVED** [review]
Looks good to me.
That find_one_by_id part is pretty subtle!

Good to see the downcast stuff in action, never heard of it before.

**Comment by andreievg** [comment]
Thanks @jmbrunskill, just in time for RC5, will wait a little bit, since assigned to Mark, if he has the time and notices something, merging in 30mins

**Review by mark-prins — APPROVED** [review]
🚢  works like a charm! 

apart from a gripe about using the US spelling of sanitise, for which I suspect @Chris-Petty is the originator, is all good.

one question: there are still 6 instances of `find_one_by_id` which then only `unwrap`s once. is this ok? they're in tests, so presumably we'd know if there was an issue right?

image

**Comment by mark-prins** [comment]
> Do you think i should change that now, is it ok to query for invoice on every invoice line integration ?

fwiw, I think that's ok.

**Comment by mark-prins** [comment]
> Thanks @jmbrunskill, just in time for RC5, will wait a little bit, since assigned to Mark, if he has the time and notices something, merging in 30mins

tested and working nicely 🙏

**Comment by andreievg** [comment]
thanks for review @mark-prins !

> one question: there are still 6 instances of find_one_by_id which then only unwraps once. is this ok?

Yep i am pretty sure i went through them all, and those ones do an assert for Some(_) or some other follow up check.

Thanks for checking though !
