### PR TITLE
5774 revert schema changes

### LINKED ISSUE #5774: Remove redundant totalStockOnHand from graphql schema
## What went wrong? 😲

totalStockOnHand was added for a bug fix which was reverted. Changes to graphql schema were added, and now generation fails

## How to Reproduce 🔨

Attempt to generate graphql schema

## Your environment 🌱

To fix - remove totalStockOnHand from front end itemStats (it has been removed from back end)

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #5774 

# 👩🏻‍💻 What does this PR do?

Reverts schema changes by removing totalStockOnHand from item stats
Regenerates schema
Note that fix for report test will be superseded by fix in 2.4.2

## 💌 Any notes for the reviewer?

No testing or UI changes required. This PR is just removing redundant field from schema.

# 🧪 Testing

- [ ] Ensure test suites and generation of schema working as expected

# 📃 Documentation

- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

### CODE REVIEW

File: server/reports/expiring-items/2_3_0/convert_data_js/src/utils.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ const processStockLines = (nodes, sort, dir) => {
     if (!!expectedUsage) {
       line.expectedUsage = Math.min(
         expectedUsage,
-        totalNumberOfPacks ?? expectedUsage
+        line?.totalNumberOfPacks * line?.packSize ?? expectedUsage
```
Comment (roxy-dao) [inline server/reports/expiring-items/2_3_0/convert_data_js/src/utils.js:16]: Why is it totalNumberOfPacks * packSize? The expected usage should be based on average consumption * diff in months between expiryDate and now... and if that ist available then it should show not applicable

File: client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts [hunk 2]
```diff
@@ -5,719 +5,1549 @@ import gql from 'graphql-tag';
 import { ReasonOptionRowFragmentDoc } from '../../../../system/src/ReasonOption/api/operations.generated';
 import { NameRowFragmentDoc } from '../../../../system/src/Name/api/operations.generated';
 type GraphQLClientRequestHeaders = RequestOptions['requestHeaders'];
-export type ItemWithStatsFragment = { __typename: 'ItemNode', id: string, name: string, code: string, unitName?: string | null, defaultPackSize: number, availableStockOnHand: number, stats: { __typename: 'ItemStatsNode', averageMonthlyConsumption: number, availableStockOnHand: number, totalStockOnHand: number, availableMonthsOfStockOnHand?: number | null, totalConsumption: number } };
+export type ItemWithStatsFragment = {
```
Comment (andreievg) [inline client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts:8]: @fergie-nz these files should not be saved with formatting, otherwise we would be getting big diffs

File: server/reports/expiring-items/2_3_0/convert_data_js/src/utils.js (hunk 1 above)
Comment (andreievg) [reply server/reports/expiring-items/2_3_0/convert_data_js/src/utils.js:16]: @roxy-dao, `!!expectedUsage` would deal with AMC not available case. And this line caps expectedUsage to totalNumberOfPacks (because that's all that can be used)

Comment (roxy-dao) [reply server/reports/expiring-items/2_3_0/convert_data_js/src/utils.js:16]: Missed Math.min. Thanks Andrei

**Comment by roxy-dao** [comment]
can we get these changes in 2.4.2 too?

**Review by roxy-dao — APPROVED** [review]
Thanks Ferg
