### PR TITLE
Split button drop down now clickable across entire component

### LINKED ISSUE #7278: Intermittent failing report rendering from ReportSelector
## What went wrong? 😲

Report rendering via report selector is sometimes not rendering report. Sometimes it works, other times clicking the button does nothing. See video linked for example of behaviour.

Note that due to report bundle not being updated - this might have been occurring with extism reports.
Have since been updated to BoaJS, which may have fixed this issue.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Navigate to Outbound Shipments
2. Open a shipment, and try to render reports then closing, then rendering another report
3. Sometimes cannot render report, sometimes can (intermittent)

Video of recreating issue [here](https://drive.google.com/file/d/17x0prfWbhYE2lvCZtrKWWeWGtgsPrzsU/view?usp=drive_link)

Generally not blocking but makes for a clunky UX

## Your environment 🌱

- Open mSupply Version: 2.7
- Platform: Web app

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #7278

# 👩🏻‍💻 What does this PR do?

Makes full menu item in new split button functionality clickable.
Previously only text was clickable.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Navigate to a AppBarButton split button where there are multiple options of different text length
(A good example of this is in inboundShipments -> open a shipment -> and see the 'add item' split button drop down
- [ ] Try clicking on the menu item - but to the right of the text.
- [ ] Should still action click

# 📃 Documentation

- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Review by noel-yeldos — APPROVED** [review]
Thanks Ferg, LGTM! Tested - entire menu item now performs action on click.

File: client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx [hunk 1]
```diff
@@ -149,14 +149,12 @@ export const SplitButton = <T,>({
...
+            }}
           >
-            <FlatButton
-              label={option.label}
-              onClick={e => {
-                onSelectOption(option, e);
-                setAnchorEl(null);
-              }}
-            />
+            <FlatButton label={option.label} onClick={() => {}} />
```
Comment (noel-yeldos) [inline client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx:157]: Just a point for discussion (not stopping approval)- Do we need this `FlatButton` inside the menu item? 
```
<MenuItem
            key={option.label}
            disabled={option?.isDisabled}
            selected={option.value === selectedOption.value}
            onClick={() => {
              onSelectOption(option);
              setAnchorEl(null);
            }}
          >
            {option.label}
          </MenuItem>
```
We may need to add some padding around the individual menu items but functionality seems to be the same without `FlatButton`
Screenshot 2025-04-17 at 11 33 40

Comment (fergie-nz) [reply client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx:157]: Oh nice looks great! I don't understand the potential implications on UI in all cases of screen size with removing the button, but seems fine?

@CarlosNZ I wonder if you have any hot takes for removing button in this case?

Comment (noel-yeldos) [reply client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx:157]: @fergie-nz true! Maybe can be a refactor issue so that it doesn't impede 2.7?
