### PR TITLE
6651 display approved quantity in requisition, update chart calculations

### LINKED ISSUE #6651: Customer requisition
## What went wrong? 😲

- [ ] Approved quantity is not displayed on the requisition line page (formerly requisition line modal)
- [ ] Chart: "Qty requested by others" quantity takes into account quantities from rejected/denied requisitions (remote authorisation)

## Expected behaviour 🤔

1. Approved quantity should be displayed as user needs to know how much they can supply
2. Chart: Qté requested by others" should not show quantity from rejected orders

## Your environment 🌱

- Open mSupply Version: 2.5.2
- Legacy mSupply Central Server Version: 

- Platform: Desktop (Windows)

- Database type:

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #6651

# 👩🏻‍💻 What does this PR do?

Changed calculations in the response requisition where remote authorisation is used, as the approved quantity can be different to the initial requested quantity. Previously everything was done by the requested quantity

If a requisition has remote authorisation: 
The approved quantity field is visible in the response requisition line edit (non-editable field)

Recalculated the quantities shown in the chart: `Requested` and `Other requested`
if there is an approved quantity for a line, this value will be used. The calculation ignores items in requisitions with pending or denied statuses
If there is no remote authorisation, the value will be the requested quantity 

The responding store will now see the approved values and accurate calculations when editing their response requisition

Screenshot 2025-03-06 at 4 51 54 PM

Screenshot 2025-03-06 at 4 51 33 PM

## 💌 Any notes for the reviewer?

# 🧪 Testing

**This will need some manual calculations - it will be easier if you don't have too many existing Request Requisitions / test with an item that you don't have requisitions for already**

- [ ] Set up access to a request store and a response store. The request store will need a program with items
- [ ] Configure the remote authorisation module so that the request store's orders need to be authorised
- [ ] Create three orders for one program (request amounts of the same items) from the request store to the response store
- [ ] Make another order with the same items, but not on a program
- [ ]  Send the orders to the response store

In remote authorisation:
-  [ ] Approve two orders, but change the approved quantity on items. Keep track of each approved amount for the item plus the total for the item
-  [ ] Deny one order

Change to response store -> sync -> go to order 1 -> click on a line
- [ ] See the `Approved quantity` appear below  `Requested quantity` -> should match what you authorised
- [ ] Open the graph beside `Quantity to supply` -> see requested quantity is equal to the approved quantity
- [ ] See `Other requested` is equal to to the approved quantity of order 2 plus the requested quantity from order 4

- [ ] Test the other orders in the same manner
- [ ] if an order is finalised, that orders `Other requested` is not included in the calculations anymore

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx [hunk 1]
```diff
@@ -353,6 +355,23 @@ export const ResponseLineEdit = ({
...
               </Box>
+              {hasApproval && (
+                <Box>
+                  <InputWithLabelRow
+                    Input={
+                      <NumericTextInput
+                        width={INPUT_WIDTH}
+                        value={draft?.approvedQuantity}
+                        disabled={!!hasLinkedRequisition}
+                        onBlur={save}
```
Comment (roxy-dao) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx:366]: Should always be disabled and shouldn't be editable by local user. This is all done through the Auth App (:

File: client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx [hunk 2]
```diff
@@ -90,6 +90,7 @@ const ResponseLineEditPageInner = ({
           Right={
             <ResponseLineEdit
               hasLinkedRequisition={!!requisition.linkedRequisition}
+              hasApproval={requisition.approvalStatus === 'APPROVED'}
```
Comment (roxy-dao) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx:93]:
```suggestion
                requisition.approvalStatus === RequisitionNodeApprovalStatus.Approved
```

File: server/service/src/requisition_line/response_line_stats/response_line_stats.rs [hunk 3]
```diff
@@ -89,18 +89,44 @@ pub fn response_store_stats(
...
+            Some(ApprovalStatusType::Denied)
+            | Some(ApprovalStatusType::DeniedByAnother)
+            | Some(ApprovalStatusType::Pending) => 0.0,
+
+            Some(ApprovalStatusType::None) | None => {
+                let quantity = line.requisition_line_row.requested_quantity;
+                quantity
+            }
+        }
+    };
```
Comment (roxy-dao) [inline server/service/src/requisition_line/response_line_stats/response_line_stats.rs:114]:
```suggestion
    let calculate_line_quantity = |line: &RequisitionLine| -> f64 {
        match line.requisition_row.approval_status {
            Some(ApprovalStatusType::Approved)
            | Some(ApprovalStatusType::ApprovedByAnother)
            | Some(ApprovalStatusType::AutoApproved) => {
                if line.requisition_line_row.approved_quantity > 0.0 {
                    line.requisition_line_row.approved_quantity
                } else {
                    line.requisition_line_row.requested_quantity
                }
            }
            Some(ApprovalStatusType::Denied)
            | Some(ApprovalStatusType::DeniedByAnother)
            | Some(ApprovalStatusType::Pending) => 0.0,

            Some(ApprovalStatusType::None) | None => line.requisition_line_row.requested_quantity,
        }
    };
```
Can return the value directly without declaring it (:

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks Aimee (: Looks good just some change requests below (:

File: server/service/src/requisition_line/response_line_stats/response_line_stats.rs (hunk 3 above)
Comment (roxy-dao) [reply server/service/src/requisition_line/response_line_stats/response_line_stats.rs:114]: Can probably hide the match behind store pref as well so it only calculates if store has response_requisition_requires_authorisation, request_requisition_requires_authorisation these prefs
