### PR TITLE
10173 reduce needless log entries

### LINKED ISSUE #10173: Reduce needless log entries
## What went wrong? 😲

I tried to find the cause of a problem on one of our test servers and on viewing the log had to wade through MB of this:

Image

## Expected behaviour 🤔
Do we have to log these empty results? they don't provide any useful information to me and are just filling up the log.

If they must remain could the log level be something more verbose than `WARN` please - for warnings I would only want to see entries which are of concern. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Configure your log settings to display warnings
2. Sync
3. Check logs

You should see entries like these

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #10173

# 👩🏻‍💻 What does this PR do?
Reduces number of logs from sync. Results should only log if there is a result, and warning is separated from info logs.

# 🧪 Testing

- [ ] Run server
- [ ] Don't see endless integration result logs
- [ ] Don't see countless push / pull logs

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/sync/translation_and_integration.rs [hunk 1]
```diff
@@ -247,6 +247,23 @@ impl TranslationAndIntegrationResults {
         Default::default()
     }
 
+    pub(crate) fn log_if_has_results(&self, operation_name: &str) {
```
Comment (jmbrunskill) [inline server/service/src/sync/translation_and_integration.rs]: I wonder if we can extend this to log all these operations but at debug level? It can be helpful to see that an action has occured but has nothing to do, rather than just not logging? Just a general comment feels like its helpful to be able to turn on debug and see that it at least tried to to integrate records, or tried to sync and got nothing etc.

Comment (Chris-Petty) [reply server/service/src/sync/translation_and_integration.rs]: I tend to agree! Can then just chop the fn name to `log` then I think.
