### PR TITLE
5098 a single processor error blocks all future processor events

### LINKED ISSUE #5098: A single processor error blocks all future processor events
## What went wrong? 😲

On a test installation, a processor error was created (TBD How)

```
2024-10-14 10:10:05.356468978 [ERROR] <service/src/processors/mod.rs:97>:Error in invoice transfer processor (Problem getting upsert operation Error while fetching invoice operation ChangelogRow { cursor: 3404, table_name: Invoice, record_id: "07319E1A3B3C5043A0F106089E7F456A", row_action: Upsert, name_id: Some("2245F8E700DC476B8BF3816EB2646CD9"), store_id: Some("19D2898203BE4642B235279385A9E7E5"), is_sync_update: true, source_site_id: None } Requisition not found "C3D465EC25BA66479E3A187972E0A75F")
```

This single error means that future processor actions are not longer processed, as the same error re-occurs constantly.

## Expected behaviour 🤔

Not 100% sure, but would be nice if processor could process all the records it can process, and just record errors in a database table or something for investigation?

Completely blocking a system due to one issue seems problematic?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

TBD

## Your environment 🌱

- Open mSupply Version: 2.3.0-RC8
- Legacy mSupply Central Server Version:

- Platform:

- Database type: SQLite

### LINKED ISSUE #5617: Customer's Inbound Shipment status changes do not get updated in Supplier's Outbound Shipment
## What went wrong? 😲

Scenario: I have a Supplier store on my omSupply Central Server and my Customer store on Remote Site. Central Server is Google Chrome browser on Mac, Remote Site is Galaxy Tab A8 on Android 14. 

When supplier sends the outbound shipment, it becomes an inbound shipment in the customer's store. I went ahead and updated the shipment to Delivered and then Verified, synced many times both sites, restarted the app and the status changes have not synced/updated on Central Server for my Supplier store. 

Outbound Shipment screenshot: 

[here](https://drive.google.com/file/d/1UMEZotPIw012XjZRCsV1bf7S88WE578X/view?usp=drive_link)

Inbound Shipment screenshot: 

[here](https://drive.google.com/file/d/1OqP-eCruZj1I8P1-6bHxJgTOFUbhEPhj/view?usp=drive_link)

Datafile shared via [this link](https://mega.nz/folder/NUBkHRZC#iun85zeqSy42LusGe8nHLw)

## Expected behaviour 🤔

Statuses should update accordingly without any delays/inconsistencies

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have a Supplier store setup on your Central Server
2. Have a Customer store setup on your Remote Site
3. I had a process of creating Internal Order -> Requisition -> Outbound Shipment -> Inbound Shipment, but for the testing purposes, you can probably start with creating an Outbound Shipment manually and selecting your Customer store as a receiver
4. Once Inbound is received, go through the steps of marking it as Delivered and Verified
5. Sync both sites many times just in case
6. See on the Supplier store, the Outbound Shipment's status does not get updated

## Your environment 🌱

- Open mSupply Version: `V2.4.0-RC4`
- Legacy mSupply Central Server Version: `V7.18.11`

- Platform: Central Server: `Google Chrome on Mac; Remote Site: Galaxy Tab A8 (Android 14)`

- Database type: `SQLite3`

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #5098
Fixes #5617

# 👩🏻‍💻 What does this PR do?

Moves the processor error handling to save any errors in to the new `system_log` and continue on
`system_log` entries are synced to OMS Central Server, so Support can potentially access and or review these errors.

## 💌 Any notes for the reviewer?

No UI for system_log as yet, you'll have to do db queries to access it.

# 🧪 Testing

- [ ] Start up a datafile which is broken e.g. https://drive.google.com/drive/u/0/folders/1rbscWr9_tWs817Nmdd7gP9soE0E-xSU1
- [ ] Check that transfers work (e.g. Internal Order is turned into a requisition)
- [ ] Previously an existing error would block new requistions from being processed.

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/repository/src/db_diesel/system_log_row.rs [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+use serde::{Deserialize, Serialize};
+
+table! {
+    system_log (id) {
+        id -> Text,
+        #[sql_name = "type"] type_ -> crate::db_diesel::system_log_row::SystemLogTypeMapping,
+        sync_site_id -> Nullable<Integer>,
+        datetime -> Timestamp,
+        message -> Nullable<Text>,
+        is_error -> Bool,
```
Comment (jmbrunskill) [inline server/repository/src/db_diesel/system_log_row.rs:16]: Thought this would be useful for filtering when/if we add other kinds of events into this log...

**Comment by andreievg** [comment]
Triage, @jmbrunskill can you please have a quick looks at this: https://github.com/msupply-foundation/open-msupply/issues/5617, let us know if you don't have the time, might be easy fix while you in the same context

**Comment by jmbrunskill** [comment]
> Triage, @jmbrunskill can you please have a quick looks at this: #5617, let us know if you don't have the time, might be easy fix while you in the same context

@andreievg sorry I somehow missed this message, I've had a look but seems like the datafiles shared are incomplete...

**Comment by jmbrunskill** [comment]
Looks like that other bug is fixed by this too.
Please review when you get a chance @andreievg

File: server/service/src/processors/transfer/invoice/mod.rs [hunk 2]
```diff
@@ -93,6 +94,60 @@ pub(crate) enum ProcessInvoiceTransfersError {
     NameIsNotAnActiveStore(ChangelogRow),
 }
 
+fn log_system_error(
+    connection: &StorageConnection,
+    error: &ProcessInvoiceTransfersError,
+) -> Result<(), ProcessInvoiceTransfersError> {
+    let error_message = format!("ProcessInvoiceTransfersError: {:?}", error);
```
Comment (andreievg) [inline server/service/src/processors/transfer/invoice/mod.rs:101]: Not 100% sure how this would look as database change log, but [format_error](https://github.com/msupply-foundation/open-msupply/blob/2fd3228f7bd8cc40acbd16e71c9a987c31c2d9b8/server/util/src/error.rs#L36) is usually better for displaying to user

File: server/service/src/processors/transfer/requisition/mod.rs [hunk 3]
```diff
@@ -59,6 +61,55 @@ pub(crate) enum ProcessRequisitionTransfersError {
...
 
+fn log_system_error(
+    connection: &StorageConnection,
+    error: &ProcessRequisitionTransfersError,
+) -> Result<(), ProcessRequisitionTransfersError> {
+    let error_message = format!("ProcessRequisitionTransfersError: {:?}", error);
+    log::error!("{}", error_message);
+    system_log_entry(connection, SystemLogType::ProcessorError, &error_message)
+        .map_err(|e| ProcessRequisitionTransfersError::DatabaseError(RepositoryError::from(e)))?;
+    Ok(())
```
Comment (andreievg) [inline server/service/src/processors/transfer/requisition/mod.rs:72]: Btw `.map_err(ProcessRequisitionTransfersError::DatabaseError)` would work, we should have implemented 'From' for database error though earlier on

Comment (andreievg) [reply server/service/src/processors/transfer/requisition/mod.rs:72]: https://github.com/msupply-foundation/open-msupply/compare/5098-a-single-processor-error-blocks-all-future-processor-events...5098-a-single-processor-error-blocks-all-future-processor-events(Use-repository-errro)

File: server/repository/src/db_diesel/changelog/changelog.rs [hunk 4]
```diff
@@ -179,6 +180,7 @@ impl ChangelogTableName {
             ChangelogTableName::PackagingVariant => ChangeLogSyncStyle::Central,
             ChangelogTableName::IndicatorValue => ChangeLogSyncStyle::Legacy,
             ChangelogTableName::BundledItem => ChangeLogSyncStyle::Central,
+            ChangelogTableName::SystemLog => ChangeLogSyncStyle::Remote,
```
Comment (andreievg) [inline server/repository/src/db_diesel/changelog/changelog.rs:183]: I would suspect this would be 'special' type and in `create_filtered_outgoing_sync_query` we would add a special filter to system log and source site id ?

**Review by andreievg — CHANGES_REQUESTED** [review]
Looks great, realy like this, the only request is the sync one, I think currently, the log wouldn't sync back to the site (it's remote type and store_id not set)

**Comment by jmbrunskill** [comment]
@andreievg Merged your suggestion and added a new SyncStyle to clarify it won't sync back...

**Review by andreievg — APPROVED** [review]
Looks good to me thanks
