### PR TITLE
10498: if base dir does not exist then create it at startup

### LINKED ISSUE #10498: Creating base dir on server start up if does not already exist
## What went wrong? 😲

On a relatively new set up when running locally and uploading txt and json files across the application, I was getting errors
eg when uploading a json for reports or when importing a fridge sensor like below

Image

On investigation the problem was that I did not have a folder `app_data` (the base_dir specified in base.yml).  And no error was thrown until I tried to do operations that required this folder

## Expected behaviour 🤔
We would expect this base directly to be made at start up if it did not already exist -> add this to the process for starting up the server. It should be idempotent so doesnt matter if already exists

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

Running dev branch locally

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by esmehm**
Fixes #10498 

# 👩🏻‍💻 What does this PR do?

When running locally, if you do not have a base directory (app_data according to base.yml) then some requiests like report importing and fridge sensor importing fail further down the line
Eg I got this error
image
This doesnt occur too often coz it's probs newbies who havent run the build script

But nevertheless this dir should be created on sevrer stsrt up if it does not already exist for a smoother dev experience

## 💌 Any notes for the reviewer?

Very open to other ideas of where it should occur!

# 🧪 Testing

If you wanted to test , delete your app_data folder, and try to import fridge sensor on dev branch, see the failure and then switch to this branch and restart the server and it should work

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

**Review by ria8651 — DISMISSED** [review]
Just waiting on andreievg's comments

File: server/server/src/lib.rs [hunk 1]
```diff
@@ -106,6 +106,11 @@ pub async fn start_server(
         CentralServerConfig::set_is_central_server_on_startup();
     }
 
+    // CREATE BASE DIRECTORY IF IT DOESN'T EXIST
+    let base_dir = settings.server.base_dir.clone().unwrap_or(".".to_string());
```
Comment (esmehm) [inline server/server/src/lib.rs]: @andreievg do you agree withw this or did you have something else in mind if not specified? eg app_data?
