### PR TITLE
6915 Target MOS is slightly different after migration

### LINKED ISSUE #6915: Target MOS is slightly different after migration
## Expected behaviour 🤔

Matches exactly after migration from OG

## How to Reproduce 🔨

Create internal order with OG, migrated to omSupply, see the difference

## Suggested fix

Use 30 rather then NUMBER_OF_DAYS_IN_A_MONTH when converting between daysToSupply

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6915

# 👩🏻‍💻 What does this PR do?
Use 30 instead of days in month const. Min threshold seems to be correct and doesn't need changing

# 🧪 Testing

- [ ] Have a store in OG site
- [ ] Create IO for that store, adjust threshold/target MOS
- [ ] Transfer store to OMS site
- [ ] Sync
- [ ] Check threshold/target MOS match OG record

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/sync/translations/requisition.rs [hunk 1]
```diff
@@ -269,7 +269,7 @@ impl SyncTranslation for RequisitionTranslation {
                 date_and_time_to_datetime(data.date_entered, 0),
                 from_legacy_sent_datetime(data.last_modified_at, &r#type),
                 from_legacy_finalised_datetime(data.last_modified_at, &r#type),
-                data.daysToSupply as f64 / NUMBER_OF_DAYS_IN_A_MONTH,
+                data.daysToSupply as f64 / 30.0,
```
Comment (jmbrunskill) [inline server/service/src/sync/translations/requisition.rs:272]: Might be nice to have a `MSUPPLY_NUMBER_OF_DAYS_IN_A_MONTH` constant or something?
Feels slightly sad to use a less accurate number just to align with mSupply.

**Review by jmbrunskill — APPROVED** [review]
I'm seeing some rounding issues, which probably isn't a blocker but maybe a follow up?

Image


Also for my example OMS seems to have a target stock  for the second item but legacy doesn't?

image

image


Not sure why that would be?
