### PR TITLE
1402 Handle sorting in inbound/outbound shipment reports

### LINKED ISSUE #1402: Invoice lines sorting
## What went wrong? 😲

In need of lines sorting functionality exposed so that when in need to print the forms, We get a much control over the sorting instance by item name, Originally idea came through that.

## Expected behaviour 🤔

Same sorting as invoice to Invoice lines as well.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Print the outbound / Inbound invoice
   5. Printed details comes out randomly 

## Your environment 🌱
 - Version [e.g. 1.2.6]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### PR DESCRIPTION
**Pull request by raviSussol**
Fixes #1402 

# 👩🏻‍💻 What does this PR do? 
 

# 🧪 How has/should this change been tested? 

Use report json from [here](https://github.com/msupply-foundation/open-msupply-reports/pull/51)

## 💌 Any notes for the reviewer?

Please also help to review its report template here: https://github.com/msupply-foundation/open-msupply-reports/pull/51

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 1]
```diff
@@ -65,27 +65,6 @@ export const useStocktakeColumns = ({
 
   return useColumns<StocktakeLineFragment | StocktakeSummaryItem>(
     [
-      [
-        'locationName',
```
Comment (raviSussol) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:69]: Removing redundant field `Location` from the stocktake datatable

**Review by mark-prins — CHANGES_REQUESTED** [review]
Nice! Thanks @raviSussol - looking good!

A change request please.. 🙏 

The issue says 'invoice lines' but the sort is only applied for Inbound Shipments. can you add the AppBarButtons change to outbounds as well please?

**Comment by raviSussol** [comment]
@mark-prins Ah.. my bad! Updated with 916d81781

**Review by mark-prins — APPROVED** [review]
