### PR TITLE
3601 authorisation required for sync file endpoints

### LINKED ISSUE #3601: Authorisation Required for Sync File Endpoints
## What went wrong? 😲
Currently there's no login required for endpoints that allow 
- file uploads for sync files
- Downloading sync files

## Expected behaviour 🤔
Only logged in users should be able to download and upload files

(Maybe we need something more targetted? Permissions based on the table we're uploading too?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Upload a file (See assets -> Documents for example)
2. Click on an uploaded document to get the link.
3. Copy link into new browser (Private Browsing Mode, or Differnet browser not logged in to OMS)
4. Should give you a permission denied error

## Proposed Solution

Could include https://github.com/msupply-foundation/open-msupply/issues/3002 to check the login cookie.
Permissions could be simply do you have a login for now...

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #3601

# 👩🏻‍💻 What does this PR do? 
Requests to upload, download files now have improved authentication

For remote_server the endpoints are just checking if the user is logged in or not.
For sync, we're using sync_v5 credentials similar to the other central sync requests.

# 🧪 How has/should this change been tested? 
Bit of local testing which seems ok...

## 💌 Any notes for the reviewer?

Could/should apply the Logged in Function logic to import fridge tag, and sqlite file downloads.
SQLite download need to retain the permissions check too.

## 📃 Documentation
_No user facing changes_

### CODE REVIEW

File: server/service/src/sync/api_v6/upload_file.rs [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+        // Read the file into memory (ideally could be a stream or something, and upload the file in chunk so we can stop quickly when sync starts/stops/pauses)
+        let mut file_bytes = Vec::new();
+        file_handle.read_to_end(&mut file_bytes).map_err(|err| {
+            log::error!("Error reading file: {:#?}", err);
+            FileSyncError::StdIoError(err)
+        })?;
+
+        // This is an example request structure, it just exists to give a compiler warning if the structure changes
+        // You'll need to modify the actual request using the reqwest::multipart::Parts below if there's a change here...
+        let _canary_request = SyncUploadFileRequestV6 {
```
Comment (jmbrunskill) [inline server/service/src/sync/api_v6/upload_file.rs:64]: Created this canary as I didn't see easy to go from an Actix multpart request to an request multipart request.
If there's a nice conversion process we could do that here...

File: server/service/src/sync/sync_on_central/mod.rs [hunk 2]
```diff
@@ -180,3 +182,96 @@ pub async fn download_file(
...
+
+        let static_file = file_service.reserve_file(
+            &sanitized_filename,
+            &static_file_category,
+            Some(file_id.clone()),
+        )?;
+        let destination = Path::new(&static_file.path);
+
+        // Copy the file from the temp location to the final location
+        // TODO: Ideally these fs operations should be done in a separate such as using web::block (see handle_upload in static_files.rs)
```
Comment (jmbrunskill) [inline server/service/src/sync/sync_on_central/mod.rs:245]: I had lifetime issues doing this, so figured we'd probably get away with this in the short term. Potentially to hang the webserver if there was some kind of disk issue but that probably suggests bigger issues...

File: server/server/src/support/mod.rs [hunk 3]
```diff
@@ -34,6 +34,8 @@ fn validate_request(
     service_provider: &ServiceProvider,
     auth_data: &AuthData,
 ) -> Result<ValidatedUser, AuthError> {
+    // TODO: Refactor to use authentication::validate_cookie_auth
```
Comment (andreievg) [inline server/server/src/support/mod.rs:37]: Thanks

File: server/service/src/sync/api_v6/mod.rs [hunk 4]
```diff
@@ -162,3 +166,10 @@ pub struct SyncDownloadFileRequestV6 {
     pub(crate) id: String,
     pub(crate) sync_v5_settings: SyncApiSettings,
 }
+
+#[derive(MultipartForm)]
+pub struct SyncUploadFileRequestV6 {
+    pub sync_v5_settings: Json<SyncApiSettings>,
```
Comment (andreievg) [inline server/service/src/sync/api_v6/mod.rs:172]: This looks great !

File: server/server/src/sync_on_central/mod.rs [hunk 5]
```diff
@@ -103,68 +101,33 @@ async fn download_file(
...
-            Ok(_) => {}
-            Err(err) => {
-                log::error!(
-                    "Error saving sync file reference after sync upload: {}",
-                    err
-                );
 
-                return Err(InternalError::new(err, StatusCode::INTERNAL_SERVER_ERROR).into());
+    let result = sync_on_central::upload_file(&settings, &service_provider, file_id, form).await;
+    match result {
```
Comment (andreievg) [inline server/server/src/sync_on_central/mod.rs:113]: I think here we can follow the existing pattern of push and pull response ? Otherwise we would have three patterns for doing it, pull/push, download-file (I didn't know how to do multipart response, if that's even a thing, so the error is serialized in an error response), and then this one with statuses.

**Review by andreievg — APPROVED** [review]
Hi, thanks James. 

I approve but only the front end authorization, I have post poned a meeting to try and get this PR reviewed but didn't quite manage to review the central upload part. 

Do you mind splitting the PR into two, and maybe merging the local endpoints auth ?

File: server/server/src/sync_on_central/mod.rs (hunk 5 above)
Comment (jmbrunskill) [reply server/server/src/sync_on_central/mod.rs:113]: Do you mean I should have a return type like `SyncUploadSuccessV6`?
Not entirely sure what you mean sorry!

**Comment by andreievg** [comment]
Merging this one, as there is follow up PR: https://github.com/msupply-foundation/open-msupply/pull/3653
