### PR TITLE
5409 fix location filter

### LINKED ISSUE #5409: iSC/Cold chain/GAPS: do not show temperature ranges if they haven't been specified
## What went wrong? 😲

At the moment, it seems like when you add Location Type in OG mSupply, the temperature input is compulsory - e.g. it is pre-populated with 0, and there cannot be a blank value. However, not every Location Type needs to have temperature associated with it, and the user can leave it unchanged. 

Screenshot 2024-11-14 at 6 35 35 PM

In omSupply though, it comes out as a temperature range 0-0, which can be confusing for the user and does not look nice. 

Screenshot 2024-11-14 at 6 35 42 PM

## Expected behaviour 🤔

As a solution, we can either: 

- Hide the temperature range if both values entered are 0
- Hide the temperature range if it hasn't been tempered with in OG mSupply
- Or allow empty values in the cells, so if there is a value that is 0, the user can enter it themselves

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. In OG mSupply, create a Location Type with both 0 as values
2. Sync omSupply 
3. Go to Inventory -> Locations -> click on an existing location or create a new one
4. Once done, click on it and set the test temperature range
5. See the range appear even if it is 0-0

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac) and Galaxy Tab A8 (Android)

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #5409

# 👩🏻‍💻 What does this PR do?

Correctly filters out only location_types with min and max temperature both 0.0.
E.g. you can now have a temperature range that goes from 0 to 15 for example.

image

## 💌 Any notes for the reviewer?

Should have pick this up in code review.
Was actually worried about this and I thought I'd tested it... Here: https://github.com/msupply-foundation/open-msupply/pull/5518#pullrequestreview-2453186364

Not sure what happened!

# 🧪 Testing

- [ ] Test you can have a location_type with range 0 -> something and assign to a location in OMS

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/repository/src/db_diesel/cold_storage_type.rs [hunk 1]
```diff
@@ -96,11 +96,9 @@ impl<'a> ColdStorageTypeRepository<'a> {
...
         // Any cold storage types that don't have temperature set (OdegC to 0degC default value) are invalid => filter out
 
-        query = query.filter(
-            cold_storage_type_dsl::min_temperature
-                .ne(0.0)
-                .and(max_temperature.ne(0.0)),
-        );
+        query = query.filter(not(cold_storage_type_dsl::min_temperature
+            .eq(0.0)
+            .and(max_temperature.eq(0.0))));
```
Comment (roxy-dao) [inline server/repository/src/db_diesel/cold_storage_type.rs:101]: can't this just be 

```suggestion
        query = query.filter(cold_storage_type_dsl::min_temperature
            .eq(0.0)
            .and(max_temperature.ne(0.0)));
```


?

**Review by roxy-dao — APPROVED** [review]
Works great thanks James!

File: server/repository/src/db_diesel/cold_storage_type.rs (hunk 1 above)
Comment (jmbrunskill) [reply server/repository/src/db_diesel/cold_storage_type.rs:101]: I don't think so? Did you try it? I'm happy with the solution I have...

Comment (roxy-dao) [reply server/repository/src/db_diesel/cold_storage_type.rs:101]: Yeah I tried both works XD. So I'm happy with either 🤷🏻
