### PR TITLE
Only show initial stocktake if no stocktakes exist for a store

### LINKED ISSUE #8419: Create `initial stocktake` message is shown to users even if they have stocktakes
## What went wrong? 😲
Create `initial stocktake` message is shown to users even if they have stocktakes. Clicking it will prompt an unhandled error since it won't be the store's first stocktake

* EDIT *
* this is when the stocktake list is filtered - you'll see in the screenshot that only 'New' stocktakes are shown and there aren't any
* END *

Image

## Expected behaviour 🤔
The `initial stocktake` message should only be be shown if the store has never created a stocktake before~

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have some finalised stocktakes and no new ones
2. Use the filter to filter out only new stocktakes
3. See the message to create an initial stocktake

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #8419 

# 👩🏻‍💻 What does this PR do?

Adds an additional SQL query to check if any stocktakes exist for a store before allowing initial stocktake to be used.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Create a new store with no stock takes
- [ ] Make sure you can complete a initial stock take
- [ ] Make sure the if you have no stock takes in `New Status` filtering on new doesn't show you the option to create an initial stocktake

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/ListView/ListView.tsx [hunk 1]
```diff
@@ -44,6 +44,8 @@ export const StocktakeListView = () => {
   } = useUrlQueryParams();
   const pagination = { page, first, offset };
   const { data, isError, isLoading } = useStocktakeOld.document.list();
+  const { data: hasStocktake, isLoading: firstStocktakeLoading } =
```
Comment (roxy-dao) [inline client/packages/inventory/src/Stocktake/ListView/ListView.tsx:47]: Why couldn't you reuse the list() api call? 🤔

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks James~

File: client/packages/inventory/src/Stocktake/ListView/ListView.tsx (hunk 1 above)
Comment (jmbrunskill) [reply client/packages/inventory/src/Stocktake/ListView/ListView.tsx:47]: It's affected by the URL parameters. I could probably have used it and somehow over-ride the URL params in a second hook? Never done that before but definitely would be nice to keep it simple?

Comment (roxy-dao) [reply client/packages/inventory/src/Stocktake/ListView/ListView.tsx:47]: Ah right yeah I see now~

**Review by roxy-dao — APPROVED** [review]
Thanks James~ I would have used the new api pattern to implement this 👀

**Comment by jmbrunskill** [comment]
> Thanks James~ I would have used the new api pattern to implement this 👀

I agree would have been nice but didn't want to do lots of changes for this small task :)
