### PR TITLE
7186 Add confirmation on leaving modal when navigating with unsaved changes - View stock

### LINKED ISSUE #7186: Navigating away from view stock after making change doesn't show alert
## What went wrong? 😲

After making a change to a stock item and navigating away, app doesn't warn you that you have unsaved changes.

https://github.com/user-attachments/assets/0218796f-48e9-4f8a-995a-75065b8d7815

## Expected behaviour 🤔
As in the patient view, the app should alert you that you have unsaved changes when you try to navigate away after making a change

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> view stock
2. Click on an item
3. Make a change
4. Navigate away from page without saving
5. See that alert modal for unsaved changes doesn't appear

## Your environment 🌱

- Open mSupply Version: 2.7
- Legacy mSupply Central Server Version: 8.01.03

- Platform: Chrome Mac OS

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #7186 

# 👩🏻‍💻 What does this PR do?
Display confirmation modal if user navigates away from or refreshes page with unsaved changes

Added a `useEffect` that syncs stockLine `isDirty` state with `useConfirmationOnLeaving` hook's internal `isDirty` state

https://github.com/user-attachments/assets/6db79f22-01b5-4aba-8a21-301a383c5b73

## 💌 Any notes for the reviewer?
I did some reading and tried to see if I could do this without using the `useEffect`. Unfortunately, I wasn't able to figure that out. Please let me know if I've missed something! 

# 🧪 Testing

- [ ] Go to Inventory -> view stock
- [ ] Click on an item
- [ ] Make a change
- [ ] Navigate away from page or refresh without saving
- [ ] See that alert modal for unsaved changes appears (modal for refresh looks different and has been raised)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Stock/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -77,6 +78,14 @@ export const StockLineDetailView: React.FC = () => {
     title: t('heading.are-you-sure'),
   });
 
+  const { setIsDirty } = useConfirmOnLeaving('view-stock');
+
+  useEffect(() => {
+    // Getting isDirty from 'draftStockLine' rather than from 'useConfirmOnLeaving' hook
+    // so need to update it manually to sync external isDirty state with hook's isDirty state
```
Comment (noel-yeldos) [inline client/packages/system/src/Stock/DetailView/DetailView.tsx:85]: This is my understanding of why the `useEffect` was needed

Comment (lache-melvin) [reply client/packages/system/src/Stock/DetailView/DetailView.tsx:85]: Hm - ideally extra useEffect shouldn't be required to sync the isDirty... but to fix is a bit more work.

I think this is ok for now, I can see we have done it in one or two other places as well. Though would you be up for writing up a refactor issue? We should consider how to solve isDirty well, beyond just this case.

To remove the need for the useEffect, either we use the isDirty provided by useConfirmOnLeaving hook (which is looking like a non-option, given dirty check from usePatchState) or we make the isDirty state returned by `usePatchState` easy to pass into useConfirmOnLeaving.

So isDirty would need to be a ref, so useConfirmOnLeaving gets the latest value, maybe [something like this](https://github.com/msupply-foundation/open-msupply/commit/d00727762fbe358b734da9a85206686c779678df). 

However, I don't want to rush this change in now, I think we need to zoom out, what is our long term plan for the relationship between those draft state management hooks, and useConfirmOnLeaving. Maybe they can sit closer together?

🙏

**Review by lache-melvin — APPROVED** [review]
LGTM, if you can write up refactor issue 🙏

File: client/packages/system/src/Stock/DetailView/DetailView.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/system/src/Stock/DetailView/DetailView.tsx:85]: https://github.com/msupply-foundation/open-msupply/issues/5237 useEffect refactor issue
