### PR TITLE
Change OK button to Loading Button type

### LINKED ISSUE #4915: 'Line Already Exists' error when entering Prescription
## What went wrong? 😲

A little hard to recreate! I've seen it twice, and they occurred when there was an action (e.g. adding a new item to a prescription), and the system was a bit slow to update, causing the screen to freeze, and when I clicked the `Save` button again to try and save the changes, the error showed up

Screenshot 2024-09-30 at 5 16 04 PM

Hard to run into, so marking as `Low Severity`

## Expected behaviour 🤔

Error should not be there

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Prescriptions
2. Add a new prescription or edit an existing one
3. Use dev tools to throttle network speed
4. Add item
5. Click `OK` multiple times in quick succession
6. See error

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC3
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (apk)

- Database type: SQLite 3

### PR DESCRIPTION
**Pull request by aimee-mcneil-melville**
Fixes #4915 

# 👩🏻‍💻 What does this PR do?

Changed the OK button for creating/editing a prescription from a Dialog button to a Loading button. Uses loading state to prevent clicking OK multiple times, therefore preventing the action that leads to the error.

Updated to match the original button with color, aria label. New loading icon is blue to match buttons

If the OK button was clicked more than once whilst loading, the api was called more than once creating the 'Line already exists' error

Screenshot 2024-11-15 at 11 29 37 AM

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ]  Go to Dispensary -> Prescriptions
- [ ] Add a new prescription or edit an existing one
- [ ] Use dev tools to throttle network speed
- [ ] Add item
- [ ] Ensure the OK button cannot be clicked more than once

# 📃 Documentation

- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

### CODE REVIEW

File: client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx [hunk 1]
```diff
@@ -201,11 +203,18 @@ export const PrescriptionLineEdit: React.FC<PrescriptionLineEditModalProps> = ({
...
+          startIcon={<CheckIcon/>}
+          loadingStyle={{iconColor:'secondary.main' }}
+          variant="contained"
+          color='secondary'
+          aria-label={t('button.ok')}
           onClick={() => handleSave(onClose)}
-        />
+        >
+          {t('button.ok')}
+          </LoadingButton>
```
Comment (lache-melvin) [inline client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx:217]: Did the format on save stop working? The "button.ok" bit should be more indented than the loading button 👀

**Review by lache-melvin — APPROVED** [review]
Looks great Aimee! Just would be great to fix up the file formatting before merging, once you get that going feel free to merge!

Also noticed that the button doesn't collapse on a narrow screen like the other two - but this is a [known issue](https://github.com/msupply-foundation/open-msupply/issues/4690): 

Screenshot 2024-11-15 at 2 11 47 PM

File: client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx (hunk 1 above)
Comment (aimee-mcneil-melville) [reply client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx:217]: Oh, it picked up 5 lines to reformat. Have done this now!
