### PR TITLE
6793 Add icon for create/save button patientView

### LINKED ISSUE #6793: Save button in Patient Detail View has no Icon
## What went wrong? 😲

The create / save button in Patients detail view/edit has a button with no icon - create on new patients and save when editing an existing patient

Image

Image

Image

## Expected behaviour 🤔

The button should have an icon for consistency across the app

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Patients -> new patient -> enter a name -> ok -> create new
2. You should be able to generate a code here, and see the `Create` button enable, with no icon
3. Go back to patients -> open a patient -> See the button now labelled `Save` with no icon

## Your environment 🌱

- Open mSupply Version: v2.6.0-RC
- Legacy mSupply Central Server Version:

- Platform: Browser

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #6793 

# 👩🏻‍💻 What does this PR do?
Add icon for create/save button

Screenshot 2025-03-13 at 14 14 42
Screenshot 2025-03-13 at 14 15 00

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Go to Patients -> new patient -> enter a name -> ok -> create new
- [ ] You should be able to generate a code here, and see the Create button enable with plus icon
- [ ] Go back to patients -> open a patient -> See the button now labelled Save with floppy disk icon

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [x] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [x] Frontend

### CODE REVIEW

File: client/packages/system/src/Patient/PatientView/Footer.tsx [hunk 1]
```diff
@@ -81,6 +83,9 @@ export const Footer: FC<FooterProps> = ({
               label={
                 inputData?.isCreating ? t('button.create') : t('button.save')
               }
+              startIcon={
+                inputData?.isCreating ? <PlusCircleIcon /> : <SaveIcon />
```
Comment (noel-yeldos) [inline client/packages/system/src/Patient/PatientView/Footer.tsx:87]: Added ```PlusCircleIcon``` to be consistent with other adding/creating functionality across app. Can keep it as just the ```SaveIcon``` is that is preferred.

Comment (aimee-mcneil-melville) [reply client/packages/system/src/Patient/PatientView/Footer.tsx:87]: Great! It is consistent with most other places, and the `PlusCircleIcon` icon signals the user that the patient doesn't exist yet

**Review by aimee-mcneil-melville — APPROVED** [review]
Nice, looks great!
