### PR TITLE
4229 assets with no store cant be edited

### LINKED ISSUE #4229: iSC/GAPS/Cold Chain: Cold chain -> Equipment -> Asset with no store assigned cannot be updated/saved after editing due to an error
## What went wrong? 😲

Cold chain -> Equipment -> Asset with no store assigned cannot be updated/saved after editing due to an error. An error 'LocationDoesNotBelongToStore' pops up anytime I try to save an asset.

Other findings: once you create an asset with no store assigned, and go in to assign it to a store to resolve the problem, the error still prevents you from doing so. 

photo_2024-06-21 15 13 13

## Expected behaviour 🤔

Updates can be saved successfully, without an error

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold chain -> Equipment
2. Try and create an asset but don't assign a store (it should be created with no issues)
3. Go to the same asset and edit a small detail -> press Save -> encounter error

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC1 (Central Server)
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop App on Windows

- Database type: SQLite3

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #4229

# 👩🏻‍💻 What does this PR do?

Fixes ability to edit assets with no store on central server.

The error was a bit of a weird one, about locations - you need a store defined to set locations, and we were sending an empty array (Some) instead of undefined (None)

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] On central, Create asset with no store
- [ ] Edit it
- [ ] it saves!

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/Store/api/api.ts [hunk 1]
```diff
@@ -1,19 +1,11 @@
...
-};
-
 export const getStoreQueries = (sdk: Sdk) => ({
   get: {
-    list: async ({ filterBy, first, offset }: ListParams) => {
+    list: async (filterBy: FilterByWithBoolean | null) => {
       const result = await sdk.stores({
         filter: filterBy,
-        first,
-        offset,
```
Comment (lache-melvin) [inline client/packages/system/src/Store/api/api.ts:16]: side quest bc only the first 20 stores were in the list!

**Review by jmbrunskill — APPROVED** [review]
Working great,thanks!
