### PR TITLE
2926 Datepicker moves if it is to close to the edge

### LINKED ISSUE #2926: Datepicker moves if it is to close to the edge
## What went wrong? 😲
Datepicker moves if it is to close to edge, so you can't select a date...... Popping this here since might be able to fix this with: https://mui.com/x/react-date-pickers/custom-components/#popper

https://github.com/msupply-foundation/open-msupply/assets/61820074/125fc709-e47b-4ccc-9fef-8ff3eacd82c7

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 
 - Platform:
   - desktop (macOS)

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #2926

# 👩🏻‍💻 What does this PR do? 
Fix position of the datetime popper, so that it doesn't move when selecting dates.

https://github.com/msupply-foundation/open-msupply/assets/61820074/1b781609-9e0e-4664-ab88-8e4fbecb7a9c

# 🧪 How has/should this change been tested? 
- [ ] Have an item with lots of lines for stocktake (8+)?
- [ ] Create a stocktake with that item
- [ ] Click on item to open the stocktake line edit modal
- [ ] Try change the date of the last line
- [ ] The date picker shouldn't move and you should be able to set an expiry date

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx [hunk 1]
```diff
@@ -91,6 +91,9 @@ export const BaseDatePickerInput: FC<
             '& .MuiPickersDay-root.Mui-selected': {
               backgroundColor: `${theme.palette.secondary.main}`,
             },
+            '& .MuiPickersPopper-paper': {
+              position: 'fixed',
+            },
```
Comment (clemens-msupply) [inline client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx:96]: It works but do you know why it's doing this? i.e. is it a bug in MUI?

Could you please also add a comment here about why this is needed?

**Review by clemens-msupply — APPROVED** [review]
Looks good thanks.

Please see the comment / add a comment before merging.

File: client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx:96]: Think that's just their default popper values
