### PR TITLE
4067 view stock 'cancel/close' button disabled

### LINKED ISSUE #4067: View stock: 'Cancel/Close' button disabled
## What went wrong? 😲

On 'View stock' > 'Details'  the 'Cancel/close' button is disabled, unless you try to make a change.
It can be confusing for users, you shouldn't have to make a change to then cancel and close a window.

Screenshot 2024-06-07 at 12 56 24 PM

On other parts of the system this button is always enabled. 

## Expected behaviour 🤔

The button should be enabled all the time, this way users can go back to the list without going back to the navigation bar.
This is how it already works on other parts of OMs like Outbound shipments, Inbound shipments, etc..

## Your environment 🌱

- Open mSupply Version: v2.1.0-IA-test-2
- Legacy mSupply Central Server Version: V7.16

- Platform: Desktop app

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #4067

# 👩🏻‍💻 What does this PR do?
Change button to `Close`. If stock line has been edited, prompt user that they will lose all their data if they continue or redirect back to Stock page.

# 🧪 Testing

- [ ] Go to `Stock`
- [ ] Click on stock line
- [ ] Click close -> Should redirect back
- [ ] Follow step 1 & 2
- [ ] Edit stock line
- [ ] Click Close
- [ ] See prompt

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Screenshots for Stock page
  2.

### CODE REVIEW

File: client/packages/system/src/Stock/DetailView/Footer.tsx [hunk 1]
```diff
@@ -44,9 +48,10 @@ export const Footer: FC<FooterProps> = ({
             marginLeft="auto"
           >
             <DialogButton
-              variant="cancel"
-              disabled={disabled}
-              onClick={() => showCancelConfirmation()}
+              variant="close"
+              onClick={() =>
+                isDirty ? showCancelConfirmation() : navigateUpOne()
```
Comment (mark-prins) [inline client/packages/system/src/Stock/DetailView/Footer.tsx:53]: with the change - can you please add the `navigateUpOne` to the `onConfirm` of the cancel confirmation modal. The button now says 'close' but when you click it, effectively nothing happens. The `resetDraft` call doesn't revert my changes and I'm still on the same page!

Side note: the resetDraft should be doing something, right? and with this change it can actually be removed - we don't have the pattern of resetting form state anywhere else in the app

```
  const onCancel = () => {
    resetDraft();
    navigateUpOne();
  };

  const showCancelConfirmation = useConfirmationModal({
    onConfirm: onCancel,
    message: t('messages.confirm-cancel-generic'),
    title: t('heading.are-you-sure'),
  });
```

**Review by mark-prins — CHANGES_REQUESTED** [review]
Nice - thanks! Can you tweak it please before shipping, the close button confirmation doesn't 'close' when you confirm, which feels weird to me when using.

File: client/packages/system/src/Stock/DetailView/Footer.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/system/src/Stock/DetailView/Footer.tsx:53]: The resetDraft resets draft 🤣

Comment (mark-prins) [reply client/packages/system/src/Stock/DetailView/Footer.tsx:53]: buut, I edited, clicked the button and my changes didn't get reset 🤷

**Review by mark-prins — APPROVED** [review]
LGTM 🚢
