### PR TITLE
Make final column auto-width

### LINKED ISSUE #2823: UI issue: Check box and Symbol overlapped
## What went wrong? 😲
UI issue: Check box and Symbol overlapped

Screenshot 2024-01-24 at 17 08 45

## Expected behaviour 🤔

No overlapping of the text and symbol

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. OMS
2. Create internal Order form mSupply to OMS site
3. See the customer requisition on. the remote site
4. See the list
5. See the symbol and checkbox overlapped in top side of the window (BUG)

## Your environment 🌱
v1.600
 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #2823

# 👩🏻‍💻 What does this PR do? 
 

Fixes the overlapping column header/checkbox for Requisition detail view.

Very tiny fix, just disabled the width and let it determine it automatically. I could just set a bigger width (change from 100 to 150, say), but I'm just copying what has been done for Internal orders.

# 🧪 How has/should this change been tested? 

## 💌 Any notes for the reviewer?

@roxy-dao I think the scroll bar is a bit of a red herring -- I get the horizontal scroll bar fine when I narrow the window (in all browsers)

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts [hunk 1]
```diff
@@ -118,7 +118,6 @@ export const useRequestColumns = () => {
       label: 'label.requested-packs',
       description: 'label.requested-number-packs',
       align: ColumnAlign.Right,
-      // width: 150,
```
Comment (CarlosNZ) [inline client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts:121]: This was left from previous, thought it better to remove rather than leave commented?

Comment (roxy-dao) [reply client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts:121]: Better to remove I think

**Review by roxy-dao — APPROVED** [review]
LGTM~ 👏🏻
