### PR TITLE
3729 Returns: if there is no 'Reason' configured on mSupply, you still can type to search

### LINKED ISSUE #3729: Returns: if there is no 'Reason' configured on mSupply, you still can type to search
## What went wrong? 😲

- Enhancement - 

After talking to @lache-melvin about returns, we noticed the 'Reason' field is editable, which can be confusing for users as they may think a new reason can be input on that window. 
However the field is editable to enable the search only. 

We think it can be confusing for users. 

telegram-cloud-photo-size-1-5015052128800058620-y

## Proposed solution 🤔

I agree with Lache's idea: it would be a nicer user experience if the reason dropdown was disabled if there were no reasons setup in mSupply.

## Your environment 🌱

- Open mSupply Version: V2.0 RC2
- Legacy mSupply Central Server Version: V7.14.0

- Platform: Desktop app (windows)

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #3729

# 👩🏻‍💻 What does this PR do?
Disables return reason if no reason is configured
Screenshot 2024-06-19 at 2 53 18 AM

# 🧪 Testing

- [ ] Have no return reasons set up
- [ ] Go to `Inbound Returns`
- [ ] Create a new return and add a line
- [ ] Put in a quantity and go to next step
- [ ] See that reason should be disabled

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ export const ReturnReasonSearchInput: FC<ReturnReasonSearchInputProps> = ({
       <Autocomplete
         fullWidth
         autoFocus={autoFocus}
-        disabled={isDisabled}
+        disabled={isDisabled || data?.nodes.length === 0}
```
Comment (lache-melvin) [inline client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx:36]: Nit~

```suggestion
        disabled={isDisabled || reasons.length === 0}
```

**Review by lache-melvin — APPROVED** [review]
Yay thank youuu
