### PR TITLE
Update migration to fix issues with pref re-initalisation

### LINKED ISSUE #10159: re-initialisation fails if a central server was upgraded to 2.15.* after 2.14.* was installed and `skip_intermediate_statuses_in_outbound` pref was used
## What went wrong? 😲

```
Error while pulling central v6 records -> [ "Sync api error, url: 'http://127.0.0.1:8890/central/sync/pull', route: 'pull'", "Could not parse response", "Other server error: Problem translation push record: ChangelogRow { cursor: 18628, table_name: Preference, record_id: \"skip_intermediate_statuses_in_outbound_34660F1A61E249DF9777FCC6588FE98C\", row_action: Upsert, name_id: None, store_id: Some(\"34660F1A61E249DF9777FCC6588FE98C\"), is_sync_update: false, source_site_id: None } -> [\n \"preference row (skip_intermediate_statuses_in_outbound_34660F1A61E249DF9777FCC6588FE98C) not found\",\n]", ]
```

## Expected behaviour 🤔

Initialisation should work 
2.14 clients should still be able to re-initialise and keep their `skip_intermediate_statuses_in_outbound` settings that were previously set, (central server will no longer be able to set it)
2.15 clients should get the new pref

It's ok for old pref to stick around for the few sites that might still have it.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Install 2.14.3 on central & on remote
2. Set the `skip_intermediate_statuses_in_outbound` pref in Central server and sync to remote
3. Update central to  2.15
4. Re-inititalise the 2.14 remote
5. Check skip_intermediate_statuses_in_outbound is still set
6. Upgrade remote to 2.15
7. Make sure the outbound status are unticked
8. Re-initialise remote on 2.15
9. 7. Make sure the outbound status are unticked

## Your environment 🌱

- Open mSupply Version: 2.15 (main)
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #10159 

# 👩🏻‍💻 What does this PR do?

The migration now creates a new pref record for the new pref, old records for old sites will still exist (probably only affecting a few customers, and some devs)

Any broken 2.15 upgrades should be fixes as we delete any invalid changelogs for `skip_intermediate_statuses_in_outbound`

## 💌 Any notes for the reviewer?

This was missed in code review, it's not clear if any `real` customers will be affected but definitely would affect some Demo, QA, and dev enviroments

# 🧪 Testing

- [ ] Install 2.14.3 on central & on remote
- [ ] Set the skip_intermediate_statuses_in_outbound pref in Central server and sync to remote
- [ ] Update central to 2.15
- [ ] Re-inititalise the 2.14 remote
- [ ] Check skip_intermediate_statuses_in_outbound is still set
- [ ] Upgrade remote to 2.15
- [ ] Make sure the outbound status are unticked
- [ ] Re-initialise remote on 2.15
- [ ] Make sure the outbound status are unticked

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [X] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [X] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [X] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/repository/src/migrations/v2_15_00/remove_skip_immediate_statuses_in_outbound_pref.rs [hunk 1]
```diff
@@ -4,20 +4,39 @@ pub(crate) struct Migrate;
...
-                id = 'invoice_status_options_' || store_id,
-                key = 'invoice_status_options',
-                value = '["NEW","SHIPPED","RECEIVED","DELIVERED","VERIFIED"]'
+            INSERT INTO preference (id, store_id, key, value)
+            SELECT
+                'invoice_status_options_' || store_id,
+                store_id,
+                'invoice_status_options',
+                 CASE 
+                    WHEN value = 'true' THEN '["NEW","SHIPPED","RECEIVED","DELIVERED","VERIFIED"]'
```
Comment (jmbrunskill) [inline server/repository/src/migrations/v2_15_00/remove_skip_immediate_statuses_in_outbound_pref.rs]: This now should get the correct `old` settings for exiting sites

Comment (roxy-dao) [reply server/repository/src/migrations/v2_15_00/remove_skip_immediate_statuses_in_outbound_pref.rs]: =/ honestly the old migration worked for me as well since the pref doesn't get created unless skip_intermediate_statuses_in_outbound exists, and that doesn't exist until it's set 🤷🏻

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks James, honestly the old migration worked for me as well since the pref doesn't get created unless skip_intermediate_statuses_in_outbound exists, and that doesn't exist until it's set 🤷🏻, so just needed to add changelog migration.

You're now inserting without getting rid of the old pref 

Screenshot 2026-01-05 at 9 32 06 AM

**Comment by jmbrunskill** [comment]
> > Thanks James, honestly the old migration worked for me as well since the pref doesn't get created unless skip_intermediate_statuses_in_outbound exists, and that doesn't exist until it's set 🤷🏻, so just needed to add changelog migration.
> > You're now inserting without getting rid of the old pref
> > Screenshot 2026-01-05 at 9 32 06 AM
> 
> This is intentional, I discussed with @andreievg we think it's best to keep the old pref there so it's still there if they re-initialise with the old version.

Should only affect a very small number of customers...

**Comment by jmbrunskill** [comment]
> > This is intentional, I discussed with @andreievg we think it's best to keep the old pref there so it's still there if they re-initialise with the old version.
> 
> Sure. But there was no mention of that in the PR nor the code. Can you add comment in code please, thanks

Code comment added. 

FWIW, the pr did explain this I thought?
`The migration now creates a new pref record for the new pref, old records for old sites will still exist (probably only affecting a few customers, and some devs)`

**Comment by roxy-dao** [comment]
> > > This is intentional, I discussed with @andreievg we think it's best to keep the old pref there so it's still there if they re-initialise with the old version.
> > 
> > 
> > Sure. But there was no mention of that in the PR nor the code. Can you add comment in code please, thanks
> 
> Code comment added.
> 
> FWIW, the pr did explain this I thought? `The migration now creates a new pref record for the new pref, old records for old sites will still exist (probably only affecting a few customers, and some devs)`

Oh sorry. Misinterpretation on my end.

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Too soon. Tests failing.

**Comment by jmbrunskill** [comment]
Tests are checking out develop but should be `v2.15.1` I don't know why!
AI says the workflow is correct...
