### PR TITLE
3738 transfer comment and reference updates

### LINKED ISSUE #3738: Comments and reference field values don't sync in stock transfer
## What went wrong? 😲
 
Comments and reference field values don't sync in stock transfer

## Expected behaviour 🤔
ALong with quantities, comments & references should also sync?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Setup at least 2 oms-stores
2. Create an outbound from one storeA to storeB with comments(eg: commentABC) and references(eg: refABC)
3. Just put status upto `picked` and sync
4. On storeB, you can already see that shipment under Inbounds with `picked` status
5. You cannot edit yet but can see the previous comments and references all
6. Now in storeA, make changes in comments (change it to sth like commentXYZ), quantities & references (change it tom sth like refXYZ) and confirm status to `shipped` now, and sync
7. In storeB, you can finally see that shipment as editable
8. See error: the old comments(commentABC) & references(refABC) are there instead of updated ones, only the quantities are updated-ones

## Your environment 🌱

- Open mSupply Version: v2.0.0-rc2
- Legacy mSupply Central Server Version: v7-14-00

- Platform: oms-central on server exe, remote-oms on server + browser (chrome)

- Database type: sqlite

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #3738

# 👩🏻‍💻 What does this PR do?

Ended up fixing a few things!

The issue: comments/references weren't being transferred on update (only on insert). I.e. if you set these things before setting outbound to picked, they were transferred, but if you update them between picked and shipped, the changes do not map through. I also updated transport reference and tax percentage to transfer through on updates as well.

THEN I found a few bugs along the way, which honestly, I'm not sure how we didn't find them before??

- Service charge lines have no cost price per pack, nor pack size... so when running `convert_invoice_to_single_pack`, we would end up with a `NaN` and transfers stopped working completely?!
- Transferred service charge totals were showing as 0, becuase they were being calculated as `cost_price_per_pack * number_of_packs` ... both of which were 0 😁 

So added some logic around service lines 😅 

## 💌 Any notes for the reviewer?

Would appreciate a double check on the logic/if I've transferred anything that we actually don't want to be? I don't think I have but 🙏 

# 🧪 Testing

- [ ] Create an outbound shipment
- [ ] Add a comment/reference/transport reference/some service charge etc
- [ ] Set to picked
- [ ] Log in to receiving store
- [x] All the above mapped through correctly
- [ ] Go back to sending store, update all those fields to something else
- [ ] Set to shipped
- [ ] Go back to receiving store
- [x] All your changes are reflected

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: server/service/src/processors/transfer/invoice/test.rs [hunk 1]
```diff
@@ -59,6 +59,10 @@ async fn invoice_transfers() {
         r.id = uuid();
     });
 
+    let service_item = inline_init(|r: &mut ItemRow| {
```
Comment (lache-melvin) [inline server/service/src/processors/transfer/invoice/test.rs:62]: Added a service line to the transfer tests, hopefully will help catch anything funky going forward 😁

File: server/service/src/processors/transfer/invoice/test.rs [hunk 2]
```diff
@@ -1269,24 +1317,41 @@ fn check_line(connection: &StorageConnection, inbound_id: &str, outbound_line: &
...
-    assert_eq!(inbound_line.r#type, InvoiceLineType::StockIn);
+
+    match outbound_line.r#type {
+        InvoiceLineType::Service => {
+            assert_eq!(inbound_line.r#type, InvoiceLineType::Service);
+            assert_eq!(
+                inbound_line.total_before_tax,
+                outbound_line.total_before_tax
+            );
+            assert_approx_eq::assert_approx_eq!(
```
Comment (lache-melvin) [inline server/service/src/processors/transfer/invoice/test.rs:1328]: Test was failing will `110.0 != 110.00000000000001` ... in DB the value looks correct... is assert_approx ok here or should I have some rounding in the transfer logic?

File: server/service/src/processors/transfer/invoice/update_inbound_invoice.rs [hunk 3]
```diff
@@ -93,10 +93,41 @@ impl InvoiceTransferProcessor for UpdateInboundInvoiceProcessor {
             invoice_line_repository.upsert_one(line)?;
         }
 
+        let outbound_invoice_row = &outbound_invoice.invoice_row;
+
+        let formatted_ref = match &outbound_invoice_row.their_reference {
+            Some(reference) => format!(
+                "From invoice number: {} ({})",
```
Comment (mark-prins) [inline server/service/src/processors/transfer/invoice/update_inbound_invoice.rs:100]: the returning nagging thought that we need to have translatable text in the backend, somehow

File: server/service/src/processors/transfer/invoice/test.rs (hunk 2 above)
Comment (mark-prins) [reply server/service/src/processors/transfer/invoice/test.rs:1328]: I think approx is fine - trying to approximate floating point numbers in binary 🤔 
If we change, I'd update `calculate_total_after_tax` and have that round the numbers slightly. But I'd prefer not to - just have dodgy floats in the database and round in the UI layer.

Though I would also do this:

```
total_after_tax: calculate_total_after_tax(total_before_tax, tax_percentage),
```

in `/server/service/src/processors/transfer/invoice/common.rs:65` to make the calculation consistent.

**Review by mark-prins — APPROVED** [review]
👍 lovely! thanks - that works nicely!
