### PR TITLE
6138 Add "New (On Hold)"  status display in stocktake list view

### LINKED ISSUE #6138: Should we have 'On Hold' as a status option for Stocktakes?
## What went wrong? 😲

When I mark a stocktake as On Hold, I notice the status stays as 'New' but the line is disabled like it's Finalised. I am wondering if it will make sense to add an option 'On Hold' to show in a Status column, alongside adding it to the status filter at the top - so the user can filter by New, Finalised or On Hold stocktakes?

Otherwise I am wondering if it can be confusing for the user why stocktake is new but greyed out (especially since the action of putting a stocktake on hold does not show in the Log events for that stocktake).

Image

## Expected behaviour 🤔

As above :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> Stocktakes
2. Create a new stocktake and add an item to it
3. Mark it as Locked
4. Go back to the list view -> see it's greyed out
5. But the status is still New
6. Confusing?

## Your environment 🌱

- Open mSupply Version: V2.5.0-RC3
- Legacy mSupply Central Server Version: V7.18.00

- Platform: Google Chrome (browser for Mac)

- Database type: PostgreSQL

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #6138 

# 👩🏻‍💻 What does this PR do?
Add check for "IsLocked" so that "New (On Hold)" status can be displayed if Stocktake is "On Hold" 

## 💌 Any notes for the reviewer?
Screenshot 2025-03-31 at 12 13 19

# 🧪 Testing

- [ ] Go to Inventory -> Stocktakes
- [ ] Create a new stocktake and add an item to it
- [ ] Mark it as "On Hold"
- [ ] Go back to the list view -> see it's greyed out
- [ ] See status "New (On Hold)"

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx [hunk 1]
```diff
@@ -34,7 +34,7 @@ export const StocktakeLockButton: FC = () => {
       value={isLocked}
       selected={isLocked}
       onClick={() => getConfirmation()}
-      label={t('label.locked')}
+      label={t('label.on-hold')}
```
Comment (noel-yeldos) [inline client/packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx:37]: Although the label in the front end has changed to say "On Hold". The stocktake table in db still has column that says "is_locked" - not sure if we need to add a migration to update column name

File: client/packages/common/src/intl/locales/en/common.json [hunk 2]
```diff
@@ -1131,6 +1131,7 @@
   "label.stocktake-comment": "Comment",
   "label.stocktake-date": "Stocktake Date",
   "label.stocktake-frequency": "Stocktake frequency",
+  "label.stocktake-on-hold": "New (On Hold)",
```
Comment (noel-yeldos) [inline client/packages/common/src/intl/locales/en/common.json:1134]: I've made the translation key specific to stocktakes for now

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx (hunk 1 above)
Comment (aimee-mcneil-melville) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx:37]: It would be nice to have everything consistently named, 'locked' is referred to throughout the whole workflow
@roxy-dao can you give some insight on the balance between cleaning up the names vs time cost here?

Comment (roxy-dao) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx:37]: Fine for now, but can create a refactor issue for changing name for consistency. Might require the table to be recreated..

**Review by aimee-mcneil-melville — CHANGES_REQUESTED** [review]
Thanks Noel, looking nice! 

I noticed while testing it the confirmation at the time of activating the hold refers to locked - can you please reword this message so that it works with the term on hold? 
Screenshot 2025-04-01 at 8 40 08 AM

File: client/packages/common/src/intl/locales/ar/common.json [hunk 3]
```diff
@@ -696,7 +696,6 @@
   "messages.deleted-returns_other": "تم حذف {{count}} إرجاعات",
   "messages.deleted-vaccine-courses_one": "تم حذف دورة لقاح 1",
   "messages.deleted-vaccine-courses_other": "تم حذف {{count}} دورات لقاح",
-  "messages.locked-description": "سيمنع ذلك من إجراء المزيد من التغييرات على جرد المخزون حتى يتم فتح القفل.",
```
Comment (noel-yeldos) [inline client/packages/common/src/intl/locales/ar/common.json:699]: Appeared twice in arabic file. Checked with Raja who confirmed that they are identical so removed one.

**Review by aimee-mcneil-melville — APPROVED** [review]
Nice, thanks for that Noel!

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx (hunk 1 above)
Comment (noel-yeldos) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx:37]: Refactor issue raised: https://github.com/msupply-foundation/open-msupply/issues/7128
