### PR TITLE
7875 date picker cooldown

### LINKED ISSUE #5379: Datetime picker: Backspacing is buggy and end time can be typed manually to be before start date
## What went wrong? 😲

https://github.com/user-attachments/assets/80c43e35-e08e-4b91-a7e4-0b5dbd6fc331

1. Unable to backspace time (can only backspace when the minute or the hour slot is highlighted)
2. Backspacing is buggy - e.g. can backspace hours, but skipping minutes
3. When using the time picker, end date can only be set in the future. However, if typed manually, end date can be set before the start date. 

## Expected behaviour 🤔

1. Should be able to backspace time digit by digit, not necessarily the highlighted part
2. Backspacing should be consistent - starting with minutes, and then with hours
3. Even when typing manually, the end date should only be allowed in the future, and not before the start date

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Encounters
2. Create a new Encounter
3. Play around with the time picker with the scenarios described above - see behaviour!

## Your environment 🌱

- Open mSupply Version: V.2.3.2
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome Browser

- Database type: SQLite 3

### LINKED ISSUE #6579: Able to select 'To date' that happened before 'From date' in Pending Encounters report
## What went wrong? 😲

Seems like date validation is missing - any options before 'From date' should be greyed out like in other parts of omSupply when selecting 'To date'

Image

## Expected behaviour 🤔

Any options before 'From date' should be greyed out like in other parts of omSupply when selecting 'To date'

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports -> Pending Encounters report
2. Choose a date for 'From date' -> click on 'To date' and see the dates before 'From date' are available

## Your environment 🌱

- Open mSupply Version: V2.6.0-RC1
- Legacy mSupply Central Server Version: N/A

- Platform: Galaxy Tab A8 (Android 14)

- Database type: SQLite3

### LINKED ISSUE #7513: More date picker translations
## What went wrong? 😲

Image
DD/MM/YYYY ->JJ/MM/AAAA

must be string -> ???
appear when you didn't choose a date from the date picker. I am not sure if this the right wording in english for that event. Should probably be something like 
"The date has not been selected" ->  La date n'a pas été sélectionnée

Image

The header should probably be Select date instead of Select date & time

Select date - > Sélectionnez une date

## Expected behaviour 🤔
See translation above
## How to Reproduce 🔨

Steps to reproduce the behaviour:

Set your language to french:

1. Go to 'Dashboard > Reports'.
2. Click on a report which have a range of dates as filter.
3.See the inside text in the date fields is not translated.
4. Click on the date picker. See the header is not translated.
5. close the date picker without choosing a date
6. See error

## Your environment 🌱

- Open mSupply Version:2.7.0RC7
- Legacy mSupply Central Server Version: v8.0.13

- Platform: Android amc64

- Database type: SQLite

### LINKED ISSUE #7557: Encounters: datetime picker is looking odd, not responsive to clicks
## What went wrong? 😲

Was testing datetime pickers for another issue and noticed this odd behaviour in Encounters: 

1. Clicking on the datetime picker icon in the fields focuses the courser on the field, second click brings up the actual selector
2. Sometimes the clicks are not responsive, note in the second half of the video - e.g. the courser will focus on the field, second click de-selects the field instead of bringing up the datetime picker
3. The colours seem to contrasted to me - why do we have orange against the blue background?
4. More importantly, why do we have buttons at the bottom showing calendar and time? Clicking on them does not do anything (e.g. open new areas, re-focus your selection) - they are just there, and the picker itself is intuitive enough to select the date and time without these buttons?

https://github.com/user-attachments/assets/212e68f0-2547-4a95-b339-43cde01c3c24

## Expected behaviour 🤔

This is date picker from prescriptions - smooth, no weird colours, no buttons

https://github.com/user-attachments/assets/907d12d0-774d-4207-862b-bc18c0063da8

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Encounters
2. Click on the filter selection and select the date filter
3. Play around with it like I did on the video - note the delayed behaviour and the funky colours

## Your environment 🌱

- Open mSupply Version: 2.7.1-RC1
- Legacy mSupply Central Server Version: V8.1.13

- Platform: Google Chrome (browser for Mac)

- Database type: PostgreSQL

### LINKED ISSUE #7561: Datetime picker icon is not showing on Android
## What went wrong? 😲

Android design of date fields (no calendar icon): 

Image

Desktop/Browser design of date fields (calendar icon present): 

Image

## Expected behaviour 🤔

I am not sure - but whatever the behaviour is, it should be consistent across platforms

Solution 1: add calendar icon to Android. Questions: will it take up valuable real estate when the user is already going to click on the field? Does the icon add value? And the text looks better centered/aligned without it.

Solution 2: remove calendar icon from Browser/Desktop versions. Would prefer this - less clutter in the field, the text might be better aligned, user intuitively will already know to click the field to select the values.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. On Android: go to Dispensary -> Encounters, select the date filter. See calendar icon missing
2. On Desktop: go to Dispensary -> Encounters, select the date filter. See calendar icon present

## Your environment 🌱

- Open mSupply Version: V2.7.1-RC1
- Legacy mSupply Central Server Version: V8.1.13

- Platform: Google Chrome (browser for Mac) and Galaxy Tab A8 (Android 14)

- Database type: PostgreSQL (browser) and SQLite3 (apk)

### LINKED ISSUE #7875: Cooldown improvement: Date picker
We have a number of bugs raised in the date picker area. This is a catch-all for them.

Request is to please review the issues in full, and use cooldown time to build a more robust solution for datepicker - focus on resolving root issues rather than patch fixes for each individual small bugs, thanks 🙏

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #7875 
Fixes #7561 
Fixes #7557
Fixes #7513
Fixes #5379
Fixes #6579

# 👩🏻‍💻 What does this PR do?

- Updates MUI date pickers to latest version (v8)
  - Use default slots, just styled to look like our components. This is looking more robust in terms of what you can type, when you can click etc.
- Pull in MUI localisations so all text is translated
- Consolidates "base" into the main `DatePickerInput` seeing as they were basically dupes
- Adds a `DateRange` JSON form component to support range validation for reports

## 💌 Any notes for the reviewer?

I know it looks massive, but mostly report regeneration and some files rearranged 🫠 + cleaned up a bunch of FCs as I went lol

# 🧪 Testing

- [ ] Reports -> Pending encounters - can't set a `to` date earlier than the `from` date
  - [ ] Report still generates with and without ranges set
- [ ] Expiry dates still enterable in view stock, stocktake, inbound shipment etc.
- [ ] Date range filters in List Views behaving well (e.g. encounter list view)
- [ ] Switch languages, translations apply - e.g. in french, empty shows JJ/MM/AAAA
- [ ] Anywhere - can type to edit the value, or use the calendar button to open the picker

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/intl/strings/IntlStrings.ts [hunk 1]
```diff
@@ -31,9 +31,9 @@ export const useTranslation = (ns?: Namespace): TypedTFunction<LocaleKey> => {
           ? { ...opts, returnDetails: false }
           : { returnDetails: false, defaultValue };
 
-      return key
+      return key && i18n.exists(key, options)
         ? t(key, options)
-        : String(defaultValue || options?.defaultValue || '');
+        : String(defaultValue || options?.defaultValue || key || '');
```
Comment (lache-melvin) [inline client/packages/common/src/intl/strings/IntlStrings.ts:36]: Ohh - open to feedback on this one... was a side quest. We get lots of warnings in console when working with JSON forms - seeing as they are custom data, we don't translate the strings, was clogging console. Potentially this should be a flag passed into useTranslation from JSON Form components though, so we still get warnings otherwise? 
Screenshot 2025-06-10 at 9 16 02 AM

Idk, personally haven't found the logs helpful, if I'm working on a page, I'll see the missing translation key in the UI before I see the log 👀

File: client/packages/common/src/intl/utils/IntlUtils.ts [hunk 2]
```diff
@@ -35,6 +42,36 @@ export const getLocale = (language: SupportedLocales) => {
...
+
+    case 'pt':
+      return getLocalisations(ptPT);
+
+    // Not every language is supported by MUI, and some dialects may want
+    // overrides. If/when needed - pass in t() here and set required fields,
+    // or define full localeText object for the required language
+    case 'en':
+    case 'ar':
+    case 'tet':
```
Comment (lache-melvin) [inline client/packages/common/src/intl/utils/IntlUtils.ts:68]: Probably worth reviewing for tetum? Though haven't heard any concerns over existing english date picker 👀

File: client/packages/common/src/ui/components/inputs/DateTimePickers/DateTimePickerInput/DateTimePickerInput.tsx [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+        }}
+        label={label}
+        slotProps={{
+          mobilePaper: { sx: getPaperSx(theme) },
+          desktopPaper: { sx: getPaperSx(theme) },
+          actionBar: {
+            actions: actions ?? ['clear', 'accept'],
+            sx: getActionBarSx(theme),
+          },
+          textField: {
```
Comment (lache-melvin) [inline client/packages/common/src/ui/components/inputs/DateTimePickers/DateTimePickerInput/DateTimePickerInput.tsx:136]: Huh, GH diff is showing this as new file, but actually not too many changes here - main thing was removing our text field for the display slot, and instead just styling base input to match our other inputs. This means the day/month/year sections behave more reliably, and we have accessible DOM structure.

Also pulled styles into own file (to share with time picker)

Note that with v8, you can now type in the date field on mobile as well, so calendar icon shows on both browser and tablet. There is an option to prevent typing for everyone, only open date selector, but I don't think we should move to this without validating which way works better for our users

File: client/packages/common/src/ui/components/inputs/DateTimePickers/TimePickerInput/TimePickerInput.tsx [hunk 4]
```diff
@@ -46,13 +41,15 @@ export const TimePickerInput: FC<
     <TimePicker
```
Comment (lache-melvin) [inline client/packages/common/src/ui/components/inputs/DateTimePickers/TimePickerInput/TimePickerInput.tsx:41]: we don't actually have any usages of tieme picker in our app right now, but i think best to keep, likely we will want in future

File: client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx [hunk 5]
```diff
@@ -65,24 +66,26 @@ export const DateFilter: FC<{ filterDefinition: DateFilterDefinition }> = ({
...
 
-const getDateFromUrl = (query: string, range: RangeOption | undefined) => {
+const getDateFromUrl = (
+  query: string,
+  range: RangeOption | undefined,
+  format: string
+) => {
   const value = typeof query !== 'object' || !range ? query : query[range];
-  return DateUtils.getDateOrNull(value);
+  return DateUtils.getDateOrNull(value, format);
```
Comment (lache-melvin) [inline client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx:88]: without passing in the format, partially entered dates (e.g. 10/02/0020, on my way to typing 10/02/2025) would get read as 20/02/2010 and mess with the input

File: client/packages/programs/src/JsonForms/components/DateRange.tsx [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+    hideClear: z.boolean().optional(),
+  })
+  .strict()
+  .optional();
+
+type Options = z.input<typeof Options>;
+
+export const dateRangeTester = rankWith(10, uiTypeIs('DateRange'));
+
+const UIComponent = (props: ControlProps) => {
```
Comment (lache-melvin) [inline client/packages/programs/src/JsonForms/components/DateRange.tsx:33]: This one added for the encounter report - new JSON forms component designed to capture a date range (i.e. 2 inputs), "to" date shouldn't be less than "from" date - these should be captured together, rather than 2 separate date inputs

File: client/packages/system/src/Encounter/ListView/Toolbar.tsx [hunk 7]
```diff
@@ -35,17 +34,17 @@ export const Toolbar: FC<{ filter: FilterController }> = () => {
...
             {
               type: 'group',
-              name: t('label.start-datetime'),
+              name: t('label.start-date'),
               elements: [
                 {
-                  type: 'dateTime',
-                  name: t('label.from-start-datetime'),
+                  type: 'date',
+                  name: t('label.from-date'),
```
Comment (lache-melvin) [inline client/packages/system/src/Encounter/ListView/Toolbar.tsx:41]: We no longer show times on encounters, so filter should just be for the date

File: standard_reports/encounters/2.6.0/argument_schemas/arguments.json [hunk 8]
```diff
@@ -0,0 +1,30 @@
+{
+  "$schema": "http://json-schema.org/draft-07/schema#",
```
Comment (lache-melvin) [inline standard_reports/encounters/2.6.0/argument_schemas/arguments.json:2]: As per, 2.6 folder was the old "latest", can ignore these ones, see changes in the diff under "latest"

File: standard_reports/encounters/latest/src/encountersQuery.graphql [hunk 9]
```diff
@@ -1,15 +1,14 @@
...
-  $before: DateTime
+  $startDatetime: DatetimeFilterInput
 ) {
   encounters(
     storeId: $storeId
     filter: {
       programId: { equalTo: $programId }
       status: { equalTo: "PENDING" }
-      startDatetime: { afterOrEqualTo: $after, beforeOrEqualTo: $before }
+      startDatetime: $startDatetime
```
Comment (lache-melvin) [inline standard_reports/encounters/latest/src/encountersQuery.graphql:11]: capturing as date range means we can pass the filter in directly now

File: client/packages/common/src/intl/strings/IntlStrings.ts (hunk 1 above)
Comment (Chris-Petty) [reply client/packages/common/src/intl/strings/IntlStrings.ts:36]: GOOD

File: client/packages/common/src/intl/utils/IntlUtils.ts (hunk 2 above)
Comment (Chris-Petty) [reply client/packages/common/src/intl/utils/IntlUtils.ts:68]: If it was gonna be anything I'd suggest `pt` as that's their other official language. Think fair to leave as en. I do wonder if it's worth checking with other PMs for changes for users above, as they aren't complaining either? With the exception of Russian as there are no Russian users yet.

File: client/packages/common/src/styles/ThemeProvider.tsx [hunk 10]
```diff
@@ -38,22 +38,23 @@ const ThemeContext = createRegisteredContext<ThemeProviderProps>('mui-theme', {
   theme: {},
 });
 
-export const ThemeProviderProxy: FC<PropsWithChildrenOnly> = ({ children }) => {
```
[the remark this answers is not in the document]
Comment (lache-melvin) [reply client/packages/common/src/styles/ThemeProvider.tsx:41]: Hm ok I did a google - at one point Roxy told me that FC is being removed in a newer version of react, so we should strip from our codebase, but actually, I think that's just create-react-app lol... the FCs are redundant but I don't think causing any harm 👀 stateful vs functional is only a thing with class based components - hooks allow stateful functional components, hence the community shift away from FC...

File: standard_reports/encounters/latest/report-manifest.json [hunk 11]
```diff
@@ -1,6 +1,6 @@
 {
   "is_custom": false,
-  "version": "2.6.4",
+  "version": "2.6.5",
```
[the remark this answers is not in the document]
Comment (lache-melvin) [reply standard_reports/encounters/latest/report-manifest.json:3]: OHH so right

File: client/packages/common/src/styles/ThemeProvider.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (roxy-dao) [reply client/packages/common/src/styles/ThemeProvider.tsx:41]: I could have sworn I heard James mentioned something about removing FC a while back but can't seem to fine the issue...

Anyways, like Laché said, apparently FC troubles with children were fixed in React 18 and typescript 5
1..

[the remark this answers is not in the document]
Comment (Chris-Petty) [reply client/packages/common/src/styles/ThemeProvider.tsx:41]: I agree cleaner. Thanks for the update on react terminology hehe. My poor class based brain (hooks came in 2018 I should keep up lol)

**Comment by lache-melvin** [comment]
Report updated, plus added a couple more json form error translated highlighted in the translation issue. Lol about the RTL, seems good plan to address when needed 🙏
