### PR TITLE
prevent duplicates

### LINKED ISSUE #3758: Errors when adding same locations multiple times in asset’s location
## What went wrong? 😲
 

(BUG1)Errors when adding same locations multiple times in asset’s location

https://github.com/msupply-foundation/open-msupply/assets/117138852/9c3b7231-b2ec-4a66-9bd1-7b8eb3d68a30

https://github.com/msupply-foundation/open-msupply/assets/117138852/aa050627-2092-45e5-aba9-29c6b1ff84e8

## Expected behaviour 🤔

For BUG1: There should be no error
For BUG1: The locations should appear in list, when the location are not selected

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Enable Cold chain and assets settings in mSupply 
2. Open any assets
3. Put same Cold storage location

Screenshot 2024-05-03 at 16 00 37

4. Click on OK 
5. See error(BUG 1)
6. Now put the Unique Locations so that it gets saved
7. Reload the page
8. See the locations, and remove all locations
9. Now search of locations
10.You won’t see the locations (BUG2)

## Your environment 🌱
<!-- e.g. 1.2.3 —>
- Open mSupply Version: v2-00-rc2
- Legacy mSupply Central Server Version: v7.15-00-dev2
<!-- e.g. android, browser (extra points if you tell us which one), desktop (windows), desktop (macOS), server (windows) —>
- Platform:
<!-- PostgreSQL or SQLite3 —>
- Database type:SQlite

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #3758

# 👩🏻‍💻 What does this PR do?

Two fixes in here:

* Filter out duplicates of the location ids before saving the draft
* Removed duplicates from the available options

Screenshot 2024-05-06 at 2 52 44 PM

## 💌 Any notes for the reviewer?

One outstanding issue, which I won't fix here.
If you assign a location, save the asset; then remove the location and save; the location is no longer available to be selected from the list. Refreshing the page will repopulate the list and allow the location to be added again.

The issue here is that the Autocomplete component is managing its value internally and not updating as expected when removing. 

# 🧪 Testing

- [ ] as per the issue; try to add a location multiple times.

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx [hunk 1]
```diff
@@ -176,6 +177,9 @@ export const Summary = ({ draft, onChange, locations }: SummaryProps) => {
           <Row label={t('label.cold-storage-location')}>
             {locations ? (
               <AutocompleteMulti
+                isOptionEqualToValue={(option, value) =>
```
Comment (mark-prins) [inline client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx:180]: this allows the `filterSelectedOptions` prop to work as expected

File: client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx [hunk 2]
```diff
@@ -188,8 +192,8 @@ export const Summary = ({ draft, onChange, locations }: SummaryProps) => {
                   }[]
                 ) => {
                   onChange({
-                    locationIds: newSelectedLocations.map(
-                      location => location.value
+                    locationIds: ArrayUtils.dedupe(
```
Comment (mark-prins) [inline client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx:195]: `dedupe` is an alias of lodash `uniq` and does what it sounds like
