### PR TITLE
7030 release testing feedback

### LINKED ISSUE #7030: CIV release testing feedback
## What went wrong? 😲

Issues raised by @Cyrilbrites which require implementation / fixing before release

* Outbound shipment: There is no `Date` or `Reference` filter for the list view (EXF124, EXF131)
* Patients: There's a 'Deceased' column but no way to enter this (EXF95, EXF96, EXF107, EXF72)
* Prescriptions: No prescribed quantity column (EXF95, EXF96, EXF107, EXF72)
* Prescriptions: Insurance status of the patient doesn't show in the detail view (EXF95, EXF96, EXF107, EXF72)

## Expected behaviour 🤔
* Add a filter for `Created date`, `Shipped date` and `Reference` in the outbound shipment list view
* Add a date of death field to the json schema (JSON schema repo change)
* Add prescribed quantity column (also raised in #7044)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #7030

# 👩🏻‍💻 What does this PR do?
Adds following filters to the `Outbound Shipment`:
- Reference
- Created date
- Shipped date
Screenshot 2025-03-26 at 9 38 51 AM
Adds ability to declare that the patient has passed away:
Screenshot 2025-03-26 at 9 38 43 AM

# 🧪 Testing

- [ ] Test filters in Outbound Shipment, the date filters are a between filter: from a certain date to a certain date
- [ ] Go to patients
- [ ] Tick that the patient is deceased
- [ ] Add date of death
- [ ] Go to list view see that deceased has a dot

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Generic patient?
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx [hunk 1]
```diff
@@ -51,6 +51,47 @@ export const Toolbar: FC<{ filter: FilterController }> = () => {
...
+                  type: 'date',
+                  name: t('label.from-shipped-datetime'),
+                  urlParameter: 'shippedDatetime',
+                  range: 'from',
+                },
+                {
+                  type: 'date',
+                  name: t('label.to-shipped-datetime'),
+                  urlParameter: 'shippedDatetime',
+                  range: 'to',
```
Comment (noel-yeldos) [inline client/packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx:91]: Just clarifying that if an end date is not provided that it uses today's date? And what date does it use if you only provide an end date and not a start date?

Also do the datepickers need to have a clear date option?
Screenshot 2025-03-26 at 11 22 13

**Review by noel-yeldos — CHANGES_REQUESTED** [review]
Thanks Roxy! UI looks good and functionality seems to be working in OMS. 

EDIT: I forget that in OG the last name appears first!!! 

~~The big thing that I noticed was the syncing of the deceased record going from OMS to OG. It is marking the wrong person as deceased in OG.

Below you can see that I've marked ```Tim Tom``` and ```Jim Jam``` as deceased in OMS. However, they are not marked as deceased in OG. Instead ```Tom Tim``` and ```Jam Jim``` are marked as deceased in OG when they are not marked as deceased in OMS.

Screenshot 2025-03-26 at 11 14 55
Screenshot 2025-03-26 at 11 16 44
Screenshot 2025-03-26 at 11 19 03

Screenshot 2025-03-26 at 11 17 54
Screenshot 2025-03-26 at 11 19 46~~

**Review by noel-yeldos — COMMENTED** [review]
Sorry @roxy-dao, ignore my premature request for changes above. Just the question about date filters :)

File: client/packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx:91]: If no date is provided, it doesn't use any date...

**Review by noel-yeldos — APPROVED** [review]
Thanks Roxy, looks good!
