### PR TITLE
9896 store properties ok throws error

### LINKED ISSUE #9896: Store properties OK throws error
## What went wrong? 😲

Clicking on the **Edit** button in the footer to view store properties, and then clicking **OK** to close the modal throws an error:

Image

The page sends this mutation:

```
mutation updateNameProperties(
  $storeId: String!
  $input: UpdateNamePropertiesInput!
) {
  updateNameProperties(storeId: $storeId, input: $input) {
    __typename
    ... on NameNode {
      ...Name
    }
    ... on UpdateNamePropertiesError {
      error {
        __typename
        description
      }
    }
  }
}
```

and I receive this error:

```
"Missing permission: EditCentralData, Required permissions: And([HasPermission(NamePropertiesMutate), HasPermission(EditCentralData)]), Store: Some("80004C94067A4CE5A34FC343EB1B4306")"
```

and a permission denied modal pops up if you are not using dev mode or clear the error

Image

## Expected behaviour 🤔
No error. I did not change any properties, as I am unable to. the system should not try to mutate in this case

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #9896

# 👩🏻‍💻 What does this PR do?
- Disables supply level input if the user does not have the correct permission 
- Created another permission for configuring name properties since properties have a 'is remote editable' flag, which means they should be able to edit name properties but not configure them even outside of central 

# 🧪 Testing

- [ ] Users who don't have permission to update properties for a name `Edit customer, supplier & manufacturer names` in OG, should see a disabled supply level. 
- [ ] Clicking ok without changing anything shouldn't give an error

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/graphql/general/src/queries/name_property.rs [hunk 1]
```diff
@@ -29,7 +29,7 @@ pub fn configure_name_properties(
     validate_auth(
         ctx,
         &ResourceAccessRequest {
-            resource: Resource::MutateNameProperties,
+            resource: Resource::ConfigureNameProperties,
```
Comment (roxy-dao) [inline server/graphql/general/src/queries/name_property.rs]: Created another permission for configuring name properties since properties have a 'is remote editable' flag, which means they should be able to edit name properties but not configure them even outside of central

**Review by GeronimoJohn — APPROVED** [review]
Working well! 🔥
