### PR TITLE
Reverse preference buttons

### LINKED ISSUE #7593: Store preference names are illegible (Improve store/global preferences selection)
## What went wrong? 😲

The formatting of the store preference titles might need some work.
Because the names of store preferences have no gap between them, it is hard to see which belongs to which toggle, and could get worse if we had many store preferences:

Image

## Expected behaviour 🤔

Toggle should be on the left hand side allowing more space for longer preference names
A small divider gap might still be needed...

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. In OMS go to manage in the side bar, and then facilities.
2. Click on a store and see the table of store preferences.

## Your environment 🌱

- Open mSupply Version: v2.8.0 development branch
- Legacy mSupply Central Server Version: 8.01 development branch

- Platform: desktop MacOS

- Database type: SQLite

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #7593 

# 👩🏻‍💻 What does this PR do?

Moved the toggle to the left hand side

Screenshot 2025-05-28 at 10 35 08 AM

Screenshot 2025-05-29 at 2 10 10 PM

## 💌 Any notes for the reviewer?

This introduces the idea of `labelRight` to the `InputLabelRow` common component. Which if true lets the label and Input swap positions

# 🧪 Testing

- [ ] Navigate to store or global preferences

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx [hunk 1]
```diff
@@ -15,17 +16,29 @@ export const InputWithLabelRow: FC<InputWithLabelRowProps> = ({
...
-    <Box display="flex" alignItems="center" gap={1} sx={sx}>
+    <Box
+      sx={{
+        ...sx,
+        display: 'flex',
+        alignItems: 'center',
+        gap: 1,
+        ...(labelRight
+          ? { gap: 2, flexDirection: 'row-reverse', justifyContent: 'flex-end' }
+          : {}),
```
Comment (CarlosNZ) [inline client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx:33]: It probably won't make much of a difference, but we'd normally put `...sx` last so that the defined properties can be overridden if needed :)

**Review by CarlosNZ — COMMENTED** [review]
Looks good, thanks John. Just the one comment about the `sx` placement.

Also, maybe can do this in another issue, but if it's quick can do here:

I notice the "Store" prefs have a nice dashed-line separator between them, but the Global ones don't:
Screenshot 2025-05-29 at 10 44 18 AM
Screenshot 2025-05-29 at 10 44 09 AM

Might be good to do the Global ones the same? Perhaps they can even share a common component? Up to you.

**Comment by GeronimoJohn** [comment]
Commits above are applied because changed commit head from `develop` to `v2.8.0-RC`
