### PR TITLE
#8167 Fix forecasting store properties initialisation

### LINKED ISSUE #8167: "Initialise Forecasting Properties" doesn't actually create all required properties
## What went wrong? 😲

When you click "Initialise store properties for population based forecasting" (in Config), only the "population served" property is added, but it also should include "Supply Interval" and "Buffer Stock", which are required for the forecasting calculation

## Expected behaviour 🤔

Should add all required properties

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Clear out any existing store properties (manually edit the database, I think)
2. Go to Settings -> Configuration -> Initialise store properties for population based forecasting and click "Initialise"
3. Go to "Edit" store properties (bottom footer)
4. Notice only "Population served" is available for editing

## Your environment 🌱

- Open mSupply Version: 2.8
- Platform: Browser

- Database type: Postgres

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fix #8167

# 👩🏻‍💻 What does this PR do?

Made sure to include the correct keys for "forecasting", not just the single "population_served" key.

Also renamed "population" keys to "forecasting" keys, as it's a bit more precise.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Clear all existing store properties (run this SQL on database):  
  ```sql
  DELETE FROM name_property;
  DELETE FROM property;
  ```
- [ ] Go to Settings -> Configuration
- [ ] Click "Initialise" for "Initialise store properties for population based forecasting"
  - [ ] Button should now read "Re-initialise"
  - [ ] In your store properties, only the three forecasting properties should be visible
- [ ] Go back to Configuration and now initialise "Initialise store properties for GAPS"
  - [ ] Button should now read "Re-initialise"
  - [ ] In your store properties, ALL Gaps properties should be visible

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/host/src/api/hooks/settings/useConfigureNameProperties.ts [hunk 1]
```diff
@@ -48,14 +48,7 @@ export const useConfigureNameProperties = () => {
...
     const primaryProperties = localiseProperties(primaryConfig.properties);
 
-    const properties = [...primaryProperties];
-
-    Object.entries(propertyConfigurations).forEach(([type, config]) => {
-      if (type !== propertyType && config.isConfigured)
-        properties.push(...localiseProperties(config.properties));
-    });
-
-    return properties;
```
Comment (CarlosNZ) [inline client/packages/host/src/api/hooks/settings/useConfigureNameProperties.ts:58]: I cannot figure out what the purpose of this extra code was for. Seems redundant to me, and I can't see any functional difference (it returns exactly the same thing, as far as I can tell)

Comment (CarlosNZ) [reply client/packages/host/src/api/hooks/settings/useConfigureNameProperties.ts:58]: @GeronimoJohn -- apparently you were the last to edit this -- am I missing something silly here?

**Review by jmbrunskill — APPROVED** [review]
Changes look good to me, Sorry I should have picked up on this much earlier!
Need to improve my code reviewing!

**Comment by CarlosNZ** [comment]
> I think it's ok to go into main, do we need to build today or it is something that can sit for a few days till we see if there's other bugs to go into 2.8.2, there's a few already triaged to that milestone..

Yeah, I don't think it needs to go out today, just wanted it in a 2.8 branch so people using Forecasting in 2.8 get it.
