### PR TITLE
6660 When prescription is created from an encounter, program field is not pre-populated

### LINKED ISSUE #6660: When prescription is created from an encounter, program field is not pre-populated
## What went wrong? 😲

When creating a prescription from an encounter, program field appears empty

Image

## Expected behaviour 🤔

My logic is - encounters cannot be created without patients enrolled into a program, so for every prescription created from an encounter program is already enabled for a patient. So the field should be pre-populated for those types of prescriptions. 

I know there were two different streams of work going into programs and prescriptions, but let's try and make those two work together!

Tagging @mark-prins after a discussion

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure you have Immunization Programs and Vaccination Card enabled for your store
2. Create an encounter for a patient who is enrolled into a program
3. From that encounter, create a prescription for a vaccine - you will have to mark the encounter as the one where vaccine was given, and toggle the stock transaction selection
4. When the prescription is created, go to Dispensary -> Prescriptions and see the one created
5. Click More -> see Programs field empty 

## Your environment 🌱

- Open mSupply Version: V2.6.0-RC2
- Legacy mSupply Central Server Version: V8.00.11

- Platform: Google Chrome (browser for Mac)

- Database type: PostgreSQL

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #6660

# 👩🏻‍💻 What does this PR do?
Save program when creating / updating prescription from encounter

# 🧪 Testing

- [ ] Have immunisation program & encounter set up
- [ ] Enrol patient in program -> create encounter
- [ ] Click on any vaccine and give vaccination
- [ ] Go to prescription
- [ ] See program saved in header

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/vaccination/update/mod.rs [hunk 1]
```diff
@@ -501,6 +501,14 @@ mod update {
         // ----------------------------
         // Update: Not given -> given, from another store
         // ----------------------------
+        let vaccinations_repo = VaccinationRowRepository::new(&context.connection);
```
Comment (roxy-dao) [inline server/service/src/vaccination/update/mod.rs]: These two tests weren't actually testing not given -> given, so have fixed that... though they should still pass now anyways even if you do given -> given
