### PR TITLE
7341 add navigate via

### LINKED ISSUE #7341: It takes too long to create customer returns
## What went wrong? 😲

Creating customer return takes too long.The window actually doesn't open. Video [HERE](https://drive.google.com/drive/folders/190t_FCcNFz2O_Bu6b_a0bzYm-lYg3JeI) 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Distribution > Customer Returns
2. Click on `New Return`
3. Choose a customer name

## Your environment 🌱

- Open mSupply Version: `V2.7RC4`
- Legacy mSupply Central Server Version:

- Platform:

- Database type: Postgres

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #7341

# 👩🏻‍💻 What does this PR do?

Adds navigate via id rather than invoice number

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [x]  Go to Distribution > Customer Returns
- [x]  Click on `New Return`
- [x]  Choose a customer name
- [x] See return generated and navigate to return

# 📃 Documentation

- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx [hunk 1]
```diff
@@ -68,7 +68,7 @@ export const AppBarButtonsComponent: FC<{
               navigate(
                 RouteBuilder.create(AppRoute.Distribution)
                   .addPart(AppRoute.CustomerReturn)
-                  .addPart(String(customerReturn?.invoiceNumber))
+                  .addPart(String(customerReturn?.id))
                   .build()
               );
```
Comment (GeronimoJohn) [inline client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx:73]: NIT: Noticed that the `try/catch` around `navigate` is mixing two patterns - `async/await` and promises `.then()` chains. We should probably stick to one for consistency (preferably `async/await`, as it's the more modern and widely adopted approach in the JS community).

e.g.

```ts
try {
  const customerReturn = await onCreate({
      id: FnUtils.generateUUID(),
      customerId: name?.id,
      customerReturnLines: [],
  });
  
  if (customerReturn) 
    navigate(
      RouteBuilder.create(AppRoute.Distribution)
        .addPart(AppRoute.CustomerReturn)
        .addPart(String(customerReturn.id))
        .build()
    );
} catch (e) {
  const errorSnack = error(
    `${t('error.failed-to-create-return')} ${(e as Error).message}`
  );
  errorSnack();
}
```

**Review by GeronimoJohn — APPROVED** [review]
LGTM! 🔥 🚀. Just left a NIT 😅

File: client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx (hunk 1 above)
Comment (fergie-nz) [reply client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx:73]: Good point, John. I'm just having a read up on those patterns now.

I can see that it is a commonly used mix in our code base (searching via await.*[\n\s].*[\n\s].*[\n\s].*[\n\s].*[\n\s].*then).

I'll make a refactor issue for this
