### PR TITLE
5776 Show available stock in Inventory

### LINKED ISSUE #5776: Available stock not shown in View Stock area
## What went wrong? 😲

When in ```Inventory -> View Stock``` the amount of stock showing is only 'Stock on Hand'. 'Stock Available' is not included as a column value
This also occurs in ```Inventory -> View Stock -> Detail``` as well as in ```Inventory -> View Stock -> Adjust``` 

When trying to reduce the amount of stock via an adjustment, the user is unable to determine how much stock is available. The system correctly prevents removing stock that allocated, however this is difficult and confusing for a user if SOH is the only value shown.

Screenshot 2024-12-12 at 1 03 32 PM

## Expected behaviour 🤔

Be able to see a value for available stock in:

- [ ] Inventory -> View Stock
- [ ] Inventory -> View Stock -> Detail
- [ ] Inventory -> View Stock -> Adjust

This would be in addition to the SOH value

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> View Stock -> Select the stock line -> Adjust
2. Add a new stock line with X quantity
3. Go to Distribution -> Outbound Shipment -> New Shipment -> Add item
4. Create a shipment for the new stockline, select the recently added stockline, and issue one pack
5. Select Confirm Allocated
6. Go back to Inventory -> View Stock -> Select the stockline -> Adjust
7. The quantity in SOH will be X, try to decrease the quantity by X
8. See that not all of the stock is available

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #5776

# 👩🏻‍💻 What does this PR do?
Display available SOH in 'View Stock' -> List view
Display available packs in 'View Stock' -> Detail view
Display availble packs in 'View Stock' -> Detail view -> adjustment modal

Screenshot 2025-04-01 at 16 38 47
Screenshot 2025-04-01 at 16 39 02
Screenshot 2025-04-01 at 16 39 22

## 💌 Any notes for the reviewer?
Although issue had asked to show available SOH in all areas, it made sense to show available packs in detail view and adjustment modal. This is because total SOH was not shown in those areas.

# 🧪 Testing

```View Stock -> List view```
- [ ] Go to Inventory -> View Stock 
- [ ] Observe that available SOH is displayed next to SOH (showing as SOH est. remaining)

```View Stock -> Detail view```
- [ ] Add a new stock line or click on existing
- [ ] Observe that available packs is displayed below pack qty

```View Stock -> Detail view -> Adjustment modal```
- [ ] From detail view -> adjustment modal
- [ ] Observe that available packs is displayed below pack qty

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/system/src/Stock/ListView/ListView.tsx [hunk 1]
```diff
@@ -129,6 +129,15 @@ const StockListComponent: FC = () => {
         width: 125,
       },
     ],
+    [
+      'availableStockOnHand',
```
Comment (noel-yeldos) [inline client/packages/system/src/Stock/ListView/ListView.tsx:133]: The label for this comes from ```ColumnDefinitionSetBuilder.ts``` which translates it as ```SoH (Est. remaining)```. I wonder if it would be better to create a new translation key ```Available SOH```

Comment (roxy-dao) [reply client/packages/system/src/Stock/ListView/ListView.tsx:133]: Yes, having 2 SOH columns may be confusing

**Review by roxy-dao — CHANGES_REQUESTED** [review]
Thanks for changes Noel~

Just change the label in the list view table

**Review by roxy-dao — APPROVED** [review]
Thanks LGTM
