### PR TITLE
Browser print errors

### LINKED ISSUE #9935: USB label printing : show errors
## What went wrong? 😲

If the zebra browser print application isn't running and you try to print, no error is shown to the user

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Plugin in a USB printer
2. enable in settings
3. Print
4. Nothing happens

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #9935 
also, the network printing was disabled in the 2.13 branch so I've restored that functionality

# 👩🏻‍💻 What does this PR do?

Now displays an error if you try to print using USB and don't have the browser print utility running.
and you can use a network printer.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] print to the network
- [ ] print using USB

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx [hunk 1]
```diff
@@ -84,6 +77,12 @@ export const AppBarButtonsComponent = () => {
     const date = new Date().toLocaleDateString();
     setIsPrinting(true);
     try {
+      if (!window.BrowserPrint) {
```
Comment (andreievg) [inline client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx]: Why would this be the case ? There is also a check for the below in the if statement, do we think that bundle won't be present ?

**Review by andreievg — COMMENTED** [review]
Thanks @mark-prins, i had a quick look through the PR, i am not seeing any changes related to ` the network printing was disabled in the 2.13 branch so I've restored that functionality`

Keen to approve, but just need to understand that comment first
