### PR TITLE
9839 and 9902

### LINKED ISSUE #9839: Cannot see source of sync error in initialisation screen
## What went wrong? 😲

While initialising 2.13 my central omS wasn't available, I didn't see error just red icon next to the step:

Image

## Expected behaviour 🤔

An error is visible

## How to Reproduce 🔨

Try initialising a remote site while central omSupply config is pointing to not available server

## Your environment 🌱

- Open mSupply Version: 2.13
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Fixes #9839 & #9902

# 👩🏻‍💻 What does this PR do?

#### 9839

Sync Error was removed 👀 from being shown in sync progress. It was added as its own component in `Sync Modal` but have missed adding it to `InitialiseLayout`. 

Added a new sub component for `InitialiseLayout` - `SyncErrorMessage`.

#### 9902

Also ensured that pulling V6 data shows that its finished in Sync Modal. Before its stuck with 0.

https://github.com/user-attachments/assets/968f798a-27f4-4546-b76b-2d1d86f5c1e2

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] 9839
- [ ] Try initialising a remote site while central omSupply config is pointing to not available server
- [ ] See error message under Sync Progress
- [ ] 9902
- [ ] After initialising, navigate to a running OMS central
- [ ] Modify some data in OMS Central (e.g. name properties)
- [ ] Check the number of Sync V6 pull records, should be correct. E.g. 2/2

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: server/service/src/sync/central_data_synchroniser_v6.rs [hunk 1]
```diff
@@ -124,6 +126,11 @@ impl SynchroniserV6 {
             // TODO it's likely that above update to cursor is redundant, this comment is to record this observation in a PR https://github.com/msupply-foundation/open-msupply/pull/4283/files/ac66350bc5aee585a10c2a8450e8d2abeffc527b#r1656344877
             cursor_controller.update(connection, end_cursor + 1)?;
 
+            logger.progress(
+                SyncStepProgress::PullCentralV6,
+                total_records - batch_length,
+            )?;
+
             if is_last_batch {
```
Comment (andreievg) [inline server/service/src/sync/central_data_synchroniser_v6.rs]: I reckon, just set to zero here
