### PR TITLE
4884 vaccine age range fixes

### LINKED ISSUE #4884: Vaccine course - Issue filling Age Range for doses
## What went wrong? 😲

When creating a new Vaccine Course, if you try to edit the age range starting with 'From age' the field won't accept any number smaller than the 'To age'. This causes a problem when the default value for 'To age' is pre-filled with 0Y 2M.

Considering the design, the user is lead to start filling the form by 'From age', but with this restriction, for now the user needs to edit 'To age' first.

For example, if the interval is supposed to be "From age" = 5Y ", To age"= 10Y, the only way to make it work is inputting 10Y first. See video below:

https://github.com/user-attachments/assets/32bea7b8-08b4-48a7-bdca-b9437d2b0194

If not done in this order, the system will not accept the number 5Y, as the default value for 'To age' is 0Y 2M
Screenshot 2024-09-26 at 4 19 49 PM

## Expected behaviour 🤔

If 'To age' < ' From age', error message appears.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Programs' >Immunisations
2. Click on 'Add Vaccine course'
3. Scroll down to '+ Dose'
4. Try typing 'From age' = 3Y 
5. See error

## Your environment 🌱

- Open mSupply Version: V2.3.RC1
- Legacy mSupply Central Server Version: V7.17

- Platform: Desktop app

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #4884 

# 👩🏻‍💻 What does this PR do?

Adds this validation check before save ("OK")

image

## 💌 Any notes for the reviewer?

I could make the other validation nice and indicate which row is nasty.

Will make an issue for renaming the columns Min/Max age to match the errors and flag stakeholders.

# 🧪 Testing

- [ ] central OMS server
- [ ] Edit program > immunisations
- [ ] Add a dose to a vaccine course
- [ ] Set the "From age" to be greater than the "To age"
- [ ] Press OK - get error
- [ ] Add another dose and make the from age lower than the first dose's
- [ ] Press OK - get the other error  

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx [hunk 1]
```diff
@@ -114,18 +114,25 @@ export const VaccineCourseEditModal: FC<VaccineCourseEditModalProps> = ({
...
   const save = async () => {
-    const agesAreInOrder = (draft.vaccineCourseDoses ?? []).every(
-      (dose, index, doses) => {
-        const prevDoseAge = doses[index - 1]?.minAgeMonths ?? -0.01;
-        return dose.minAgeMonths > prevDoseAge;
-      }
-    );
+    const doses = draft.vaccineCourseDoses ?? [];
+
+    const agesAreInOrder = doses.every((dose, index, doses) => {
```
Comment (Chris-Petty) [inline client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx:119]: hmm kinda double references to `doses` whoops. I assume the arrow function scope uses the param one rather than the upper scope one added...

Comment (Chris-Petty) [reply client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx:119]: This validation is otherwise just formatting changes.

File: client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx [hunk 2]
```diff
@@ -81,6 +81,13 @@ interface VaccineCourseEditModalProps {
   mode: ModalMode | null;
 }
 
+function doseIndex(
+  doses: VaccineCourseDoseFragment[],
+  dose: VaccineCourseDoseFragment
+) {
+  return doses.indexOf(dose) + 1;
+}
```
Comment (Chris-Petty) [inline client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx:89]: I am quite wary of list indexes relying on order of the array - though I see the repo layer does sort by min age

https://github.com/msupply-foundation/open-msupply/blob/aa859cbf1345acac1a8d336691d9d05464a4b68d/server/repository/src/db_diesel/vaccine_course/vaccine_course_dose.rs#L89-L90

Regardless of sorting or having an row ordering number field, could be some weird edge cases with soft deleted doses but I think it's fuzzy what to even do about them and unlikely to occur anyway.

Comment (lache-melvin) [reply client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx:89]: Yeah... I think this is okay though, we're not saving this number just using it for display. Yeah, if you have 5 doses, then delete the 4th one, it will say dose # 4, label = Dose 5... but at least dose # column and error message line up? 🤷‍♀️

**Review by lache-melvin — APPROVED** [review]
🔥 TY
