### PR TITLE
fix confirm on leaving with multiple blockers

### LINKED ISSUE #6321: No 'You have unsaved changes' warning when navigating away from Vaccination encounters
## What went wrong? 😲

I can navigate away from the encounter without a prompt even when I have unsaved changes!

This is due to two `useBlocker` calls - one from `DetailTabs` and one from `useJsonForms`.

useBlocker can only have one active instance at a time, so naturally neither are working.

## Expected behaviour 🤔

Vaccination encounters still have the navigation warnings if I have unsaved changes

Update the implementation so that we can register multiple blockers in as many places as we need, and this can inform one useBlocker call at the base of the app.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a vaccination encounter
2. Edit some JSON form data, e.g. visit type, encounter start time...
3. Save button should be enabled - you have changes that need to be saved - do NOT save the form
4. Try to navigate away
5. You are not blocked from navigating/warned that you have unsaved changes!

## Your environment 🌱

- Open mSupply Version: 2.5
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by lache-melvin**
Fixes #6321

# 👩🏻‍💻 What does this PR do?

useBlocker can only have one active instance at a time. In encounters, there were two blockers (one from JSON form, one from `DetailTabs`) - so neither were working. You could edit encounter, then navigate away without saving with no warning.

This updates the implementation so that we can register multiple blockers in as many places as we need, and this informs the one `useBlocker` call at the base of the app. 

## 💌 Any notes for the reviewer?

Actually ended up fixing the detail tabs so that it doesn't use the confirm on leaving hook - see comment - but will have the same multiple blockers rendered problem with my next vax card PR. Just didn't want this bloat in that PR 🙏 

# 🧪 Testing

- [ ] Setup for vaccine card - see testing setup: #4642 
- [ ] Create/go to a vaccination encounter
- [ ] Make a change e.g. set visit type or start time
- [ ] Try to navigate away - you get the are you sure confirmation modal
- [ ] Also test it still works in the other places:
  - [ ] Refreshing page in inbound/outbound shipment edit modals
  - [ ] R&R form
  - [ ] Editing CCE
  - [ ] Editing prescription
    - [ ] Check you still _can_ change between items in prescription, just not to a different page

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

### CODE REVIEW

File: client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx [hunk 1]
```diff
@@ -82,8 +79,9 @@ export const PrescriptionLineEditView = () => {
     });
   }, [currentItem]);
 
-  useConfirmOnLeaving(
-    isDirty,
+  // tODO: does the state turn up right lol
```
Comment (lache-melvin) [inline client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx:82]: chris has brought it to my attention that it indeed does not 😭

Comment (lache-melvin) [reply client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx]: Fixed in f0f0cce153, thanks Chris 🙏

**Review by Chris-Petty — APPROVED** [review]
Yisss
