### PR TITLE
#6078 Prevent unnecessary scrolling

### LINKED ISSUE #6078: Prescriptions add item keeps refocusing on first accordion
## What went wrong? 😲
The screen keeps going back to the first opened accordion

https://github.com/user-attachments/assets/0872c922-1d00-4acd-8d1c-7692e759ad68

## Expected behaviour 🤔
Shouldn't jump around the place

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Add new item to prescription
2. Go through inputs
3. See screen keeps scrolling back up

## Your environment 🌱

- Open mSupply Version: V2.5.0-RC3
- Legacy mSupply Central Server Version:

- Platform: Android

- Database type:

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #6078

# 👩🏻‍💻 What does this PR do?

Turns out the `ref` definition in `<ListOptions>` was calling `scrollIntoView` on every re-render, which was pulling the whole page up.

I've changed it to define the ref in a parent component, and passed it down to the ListOptions, and also defined a `scrollIntoView` method which calls `scrollIntoView()` on that ref from the Nav Bars (Prev/Next buttons).

Also, this problem was affecting *all* `<ListOptions>` implementations, so have made the same fix (in addition to Prescriptions) for:
- Requisitions
- Internal Orders
- Indicators for both of the above

## 💌 Any notes for the reviewer?

There's a lot of duplicate code, plus the different implementations of the Navigation bars are inconsistent, so hopefully can consolidate this a bit better with #5973 .

# 🧪 Testing

Go to a prescription "Line Edit View" with a decent number of items, and make your browser window small enough to require a scroll bar on the list of items, like this:
Screenshot 2025-01-17 at 12 40 52 PM

Then, scroll down so the selected item is no longer visible:
Screenshot 2025-01-17 at 12 41 01 PM

- [ ] Then, click the "Next" button and the next item should smoothly scroll back into view :)
- [ ] Try out different variations with the "Previous" button, etc.
- [ ] Do similar for the Requisition line edit views
- [ ] Please also test the "How to reproduce" from the original issue (#6078) to confirm the unwanted scrolling is no longer a problem,

### CODE REVIEW

File: client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx [hunk 1]
```diff
@@ -64,12 +66,7 @@ export const ListOptions = ({
           <ListItem
             sx={{ padding: '5px 0px', cursor: 'pointer' }}
             onClick={() => onClick(option.id)}
-            ref={
-              option.id === currentId
-                ? l =>
-                    l?.scrollIntoView({ behavior: 'smooth', block: 'center' })
-                : null
-            }
+            ref={option.id === currentId ? scrollRef : null}
```
Comment (CarlosNZ) [inline client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx:69]: The `scrollRef` gets applied to the element containing the current selection, which changes. I've had to add a small time delay to the `scrollIntoView` method to ensure that the ref has been applied to the *new* selection before scrolling to it. Without that, it scrolls to the previously select (so it's off by one) as it starts scrolling before the re-render has changed the ref assignment.

I don't love it, but it seems the most straightforward for this particular situation.

**Comment by jmbrunskill** [comment]
@CarlosNZ I'm building an APK to give this a test on tablet...

**Comment by CarlosNZ** [comment]
> I'm interested to know what the desired behaviour is, and why the scroll inter view is needed. Are we trying to focus the item selector when changing pages?

I think it was just so when you have a long list of items, we can make sure the currently selected item is *always* in view. Without it, you can keep clicking "Next" until the selected item is outside the visible area, which is not that nice.

**Comment by roxy-dao** [comment]
> > I'm interested to know what the desired behaviour is, and why the scroll inter view is needed. Are we trying to focus the item selector when changing pages?
> 
> I think it was just so when you have a long list of items, we can make sure the currently selected item is _always_ in view. Without it, you can keep clicking "Next" until the selected item is outside the visible area, which is not that nice.

Yes! This was why (: but I can have a quick whirl if you want @jmbrunskill

**Review by roxy-dao — APPROVED** [review]
LGTM~ Thanks Carl (:
