### PR TITLE
7566 fix pack size issues stocktake

### LINKED ISSUE #7566: Stocktake: pack size is 0 for items with no stock, default pack size ignored
## What went wrong? 😲

Stocktake generated from master list, so this was a placeholder line for an item with no stock:
Image

I entered the 25 counted packs, and pressed save. The line saved fine, even though in the form it says pack size 0 - pack size is saved as 1.  To make matters worse, my default pack size for this item was 50! 

Image

The pack size 0 thing seems to only affect placeholder lines - add item button, or add batch to existing item, has pack size 1 - but this is also an issue, it is 1 regardless of default pack size 

Image

Image

I double checked, pack size to 1 store pref is not on!

## Expected behaviour 🤔

Pack size field always defaults to the default pack size for the item

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Generate stocktake from master list
2. Click a row for an item which doesn't have any stock
3. BUG: see pack size 0

And second bug
1. Find an item with default pack size other than 1
2. Add a stocktake row (either using Add Item button, or Add Batch within the edit modal)
3. BUG: see pack size 1

## Your environment 🌱

- Open mSupply Version: v2.7.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

### PR DESCRIPTION
**Pull request by noel-yeldos**
Fixes #7566 

# 👩🏻‍💻 What does this PR do?

- Show `defaultPackSize` for items with no stock line when adding from masterlist or otherwise
  - Cannot enter 0 for `packSize` in `StocktakeLineEdit`modal
- When adding a new batch line from `StocktakeLineEdit` modal, the `packSize` is the item's `defaultPackSize` 

`defaultPackSize` now displays in Stocktake detail view
Screenshot 2025-05-19 at 14 40 02

`defaultPackSize` now displays in modal -> no longer showing 0
Screenshot 2025-05-19 at 14 41 08

`defaultPackSize` now displays when adding a new batch line -> no longer showing 1 (unless packSize is 1)
Screenshot 2025-05-19 at 14 41 48

## 💌 Any notes for the reviewer?
I don't know why the colours for `packSize` and `snapshotPacks` has changed to black - possibly a recent change that went into develop? I was sure they were blue before for placeholder lines

# 🧪 Testing

Ensure `Set pack to one for all visible items in this store` pref is off in OG

`Scenario 1`
- [ ] Generate stocktake from master list
- [ ] Click a row for an item which doesn't have any stock
- [ ] See pack size is the item default pack size

`Scenario 2`
- [ ] Find an item with default pack size other than 1
- [ ] Add a stocktake row (either using Add Item button, or Add Batch within the edit modal)
- [ ] See pack size is the item default pack size

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

# 📃 Reviewer Checklist

The PR Reviewer(s) should fill out this section before approving the PR

**Breaking Changes**
- [ ] No Breaking Changes in the Graphql API
- [ ] Technically some Breaking Changes but not expected to impact any integrations

**Issue Review**
- [ ] All requirements in original issue have been covered
- [ ] A follow up issue(s) have been created to cover additional requirements

**Tests Pass**
- [ ] Postgres
- [ ] SQLite
- [ ] Frontend

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx [hunk 1]
```diff
@@ -172,7 +172,7 @@ export const useStocktakeColumns = ({
           getColumnProperty(rowData, [
             { path: ['lines', 'packSize'] },
             { path: ['packSize'] },
-          ]),
+          ]) ?? rowData.item?.defaultPackSize,
```
Comment (noel-yeldos) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx:175]: Fallback to item defaultPackSize if no stock line

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx [hunk 2]
```diff
@@ -198,6 +198,8 @@ export const BatchTable = ({
         cellProps: {
           getIsDisabled: (rowData: DraftStocktakeLine) => !!rowData?.stockLine,
         },
+        accessor: ({ rowData }) =>
+          rowData.packSize ?? rowData.item?.defaultPackSize,
```
Comment (noel-yeldos) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx:202]: Fallback to item defaultPackSize if no stock line

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 3]
```diff
@@ -28,8 +28,6 @@ export const useStocktakeLineEdit = (
   const { saveAndMapStructuredErrors: upsertLines, isLoading: isSaving } =
     useStocktakeOld.line.save();
 
-  const defaultPackSize = 1;
```
Comment (noel-yeldos) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts:31]: Remove hardcoded defaultPackSize value for adding new lines. Now using item defaultPackSize

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx [hunk 4]
```diff
@@ -173,6 +173,9 @@ export const useStocktakeColumns = ({
             { path: ['lines', 'packSize'] },
             { path: ['packSize'] },
           ]),
+        cellProps: {
+          defaultValue: UNDEFINED_STRING_VALUE,
+        },
```
Comment (lache-melvin) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx:178]: Changed this one, per the pattern we have elsewhere, to show `-` when the line is just a placeholder, value doesn't really exist :)

File: client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx [hunk 5]
```diff
@@ -36,7 +36,7 @@ const StocktakeTabs = ({
 }: {
   id: string | undefined;
   isDisabled: boolean;
-  onOpen: (item?: ItemRowFragment | null | undefined) => void;
+  onOpen: (item?: StocktakeLineFragment['item'] | null | undefined) => void;
```
Comment (lache-melvin) [inline client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx:39]: By replacing `ItemRowFragment` with the actual item type from the stocktake line fragment, we don't need to go adding defaultPackSize in all the other places where it wasn't actually required 😁

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 6]
```diff
@@ -48,10 +45,7 @@ export const useStocktakeLineEdit = (
 
   const addLine = () => {
     if (item) {
-      setDraftLines(lines => [
-        DraftLine.fromItem(id, item, defaultPackSize),
-        ...lines,
-      ]);
+      setDraftLines(lines => [DraftLine.fromItem(id, item), ...lines]);
```
Comment (lache-melvin) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts:48]: Went one step further - seeing as we're already passing in `item` - just using it directly in `DraftLine.fromItem` rather than passing in separately

**Review by lache-melvin — APPROVED** [review]
Looks awesome, thanks Noel - pushed a couple of changes to get this over the line for today, mainly just to use the specific type of StocktakeLineFragment['item'] which has the extra field 🚀

File: client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx (hunk 5 above)
Comment (noel-yeldos) [reply client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx:39]: Oh that's so much better, thank you for pointing that out!
